### ISSUE TITLE
cors problem while labeling

### ISSUE THREAD

**Issue by lfgogogo** [heartexlabs/label-studio#1013]
I have started the server,created a account,and imported my data by a .txt file,but when i start to label my data,i get an error below.I just don't know why i have imported my data but get an error like this while labeling.And my .txt file is below,i start LS by 'label-studio',data server by 'python -m http.server 8081 -d'.

cors problem:
![image](https://user-images.githubusercontent.com/42054022/120612188-83745380-c487-11eb-9c8a-dc3cd245414c.png)

.txt file:
![image](https://user-images.githubusercontent.com/42054022/120612276-9e46c800-c487-11eb-94cc-7e06ea491b24.png)

data server console error:
![image](https://user-images.githubusercontent.com/42054022/120613007-5f654200-c488-11eb-8e5b-fca317847380.png)
It says an existing connection was forcibly closed by the remote host.

**Comment by kaitco** [comment]
Starting python simple http module will not allow CORS. Use following script to start a simple http server with CORS enabled
[https://stackoverflow.com/questions/21956683/enable-access-control-on-simple-http-server](https://stackoverflow.com/questions/21956683/enable-access-control-on-simple-http-server)
```#!/usr/bin/env python3
from http.server import HTTPServer, SimpleHTTPRequestHandler, test
import sys

class CORSRequestHandler (SimpleHTTPRequestHandler):
    def end_headers (self):
        self.send_header('Access-Control-Allow-Origin', '*')
        SimpleHTTPRequestHandler.end_headers(self)

if __name__ == '__main__':
    test(CORSRequestHandler, HTTPServer, port=int(sys.argv[1]) if len(sys.argv) > 1 else 8```

**Comment by niklub** [comment]
That's great! Also there is an even simpler method mentioned in this stackoverflow thread, without creating any line of code:

```
npm install http-server -g
http-server -p 3000 --cors
```

**Comment by lfgogogo** [comment]
@kaitco @niklub I have tried，both of them are working，thank you.
