### ISSUE TITLE
Import of local files fails

### ISSUE THREAD

**Issue by alexhagen** [heartexlabs/label-studio#1024]
**Describe the bug**
When I import local files (from my desktop folder), I receive a message that "12 files uploaded", but when I go to label them, I receive "Cannot load image (/data/upload/MSG_OEM_XSW_IMAGE_LBRV-F1_Brownsville-2021-02-25T201450_000Z_UHvf_2021-02-25T201_VRpriLI.tiff). Check console/network panel for more info."

**To Reproduce**
1. Install label-studio 1.0.2 using pip on conda environment on MacOSX 10.15.7.
2. Start label-studio, start a new project, start import of files
3. Choose files to upload
4. Click Import
5. Choose file to annotate.

**Expected behavior**
I expect the files to be uploaded.

**Screenshots**
<img width="2552" alt="Screen Shot 2021-06-04 at 7 13 00 AM" src="https://user-images.githubusercontent.com/871540/120815139-6c277b80-c504-11eb-97b4-5a6ac725d007.png">
<img width="2553" alt="Screen Shot 2021-06-04 at 7 13 11 AM" src="https://user-images.githubusercontent.com/871540/120815135-6b8ee500-c504-11eb-8075-83764eb5d4ed.png">
<img width="2550" alt="Screen Shot 2021-06-04 at 7 13 20 AM" src="https://user-images.githubusercontent.com/871540/120815131-69c52180-c504-11eb-9166-c68b3d371c65.png">

**Environment:**
 - OS: MacOSX 10.15.7.
 - Label Studio Version v1.0.2
 - Python: 3.8 from conda-forge

**Comment by alexhagen** [comment]
I found this in the label-studio output:

```
[04/Jun/2021 14:12:14] "PATCH /api/dm/views/12?project=5 HTTP/1.1" 200 579
Traceback (most recent call last):
  File "/Users/hage581/sw/miniconda/envs/stelviolabel/lib/python3.8/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Users/hage581/sw/miniconda/envs/stelviolabel/lib/python3.8/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/Users/hage581/sw/miniconda/envs/stelviolabel/lib/python3.8/wsgiref/handlers.py", line 293, in write
    self._write(data)
  File "/Users/hage581/sw/miniconda/envs/stelviolabel/lib/python3.8/wsgiref/handlers.py", line 467, in _write
    result = self.stdout.write(data)
  File "/Users/hage581/sw/miniconda/envs/stelviolabel/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
OSError: [Errno 41] Protocol wrong type for socket
```

**Comment by alexhagen** [comment]
I've reproduced this on Ubuntu 18.04

**Comment by makseq** [comment]
@alexhagen TIFFs are supported by Safari browser only. Please, try to convert your images to png or jpg.

**Comment by alexhagen** [comment]
Thanks @makseq, in that case, I'd recommend changing these the list of supported images to reflect that.

<img width="2094" alt="Screen Shot 2021-05-21 at 8 12 36 AM" src="https://user-images.githubusercontent.com/871540/120835002-a0a53280-c518-11eb-86fd-699355a17de8.png">

**Comment by alexhagen** [comment]
Thanks @makseq, that fixed it.  I'd recommend changing the supported image types to reflect that.  I can submit the merge request for that change if you want.
<img width="640" alt="Screen Shot 2021-06-04 at 9 39 11 AM" src="https://user-images.githubusercontent.com/871540/120835197-d9dda280-c518-11eb-85f8-c276402ab8d5.png">
