### ISSUE TITLE
Is there a way to disable the authorization step (sign in/log in) on label-studio?

### ISSUE THREAD

**Issue by coldtomatojuice** [heartexlabs/label-studio#1028]
**Is your feature request related to a problem? Please describe.**

_Given that label-studio is deployed on a containerized environment like kubernetes,
It's not hard to imagine that one may already be authorized by container orchestrator or another pod to access label-studio pod.
Therefore, additional log in on label-studio is no longer needed
(only one person or an approved group can access the label-studio pod)_

**Describe the solution you'd like**

_In that case, Can we disable authorization process in the current label-studio?_

**Describe alternatives you've considered**

_Disable authorization in server start with a flag_

**Additional context**

**Comment by salmenf** [comment]
This would be very useful for my use case, as well: I want to use label-studio in a docker-compose environment where all endpoints are already protected with basic-auth, so the login is redundant. I also want to automatically create a user, project and task. The way it works right now, I see no way to do this, since I need to manually create a first user and login to get my auth token before I can use the HTTP API.

I'd really like a way to fully disable auth, both for login and API calls.

**Comment by makseq** [comment]
@coldtomatojuice 

> Can we disable authorization process in the current label-studio?

How do you distinguish annotators if there is no auth? Who performed the annotation A and who performed the annotation B? 

@salmenf 
You can create a user using this command line call:
https://labelstud.io/guide/signup.html?from_search=create%20user#Create-an-account

Also you can create a project and a task via API:
https://api.labelstud.io/#operation/api_projects_create
https://api.labelstud.io/#operation/api_tasks_create

The bottleneck is the login, yes. Maybe we have to implement it via token, something like:
```
http://localhost:8080/user/login?user_token=<token>
```

**Comment by salmenf** [comment]
@makseq 
Thanks for the tips! Exactly, the login is the issue, some automatic login via HTTP would be great! 

I don't think your suggestion works in my case, though, if I'm understanding it right: If I can login only via token, how do I get the token automatically (without the UI)? There's this API method (https://labelstud.io/api#operation/api_current-user_token_list), but it requires a token to get the token. Rather, I'd need to login via username and password to be able to get the token with the API method.

**Comment by makseq** [comment]
> how do I get the token automatically (without the UI)

check this branch please: https://github.com/heartexlabs/label-studio/pull/1065

**Comment by salmenf** [comment]
Excellent, thanks! That branch and the login via token would solve my use case completely.
