### ISSUE TITLE
Do you store imported file real name?

### ISSUE THREAD

**Issue by Mohitduklan** [heartexlabs/label-studio#1029]
When we upload files with the same name, Label studio add some random text at the end of the file name.
Is there a way from which I can get the file's original name?

**Comment by makseq** [comment]
As far as I remember LS addes postfix to your original filename, e.g.: you imported `src.png` => `src_ZoqW18z.png`, so, you can split your filename with `_` and get your original filename:

```python
ls_filename = 'src_ZoqW18z.png'
original_filename = '_'.join(ls_filename.split('_')[:-1]) + '.png'
```

**Comment by Mohitduklan** [comment]
Yes, but if the original filename is  'src_ZoqW18z.png', I split the file name with '_' will give me 'src.png' the wrong name.

**Comment by makseq** [comment]
I think the target name will be src_ZoqW18z_anotherHash.png. So, my linea should work ok

**Comment by Mohitduklan** [comment]
Suppose I imported 3 images: 'abc_def.png', 'ijk.png', 'ijk.png'.
Label studio will store them as 'abc_def.png', 'ijk.png', 'ijk_someHash.png'
then how will I get original names of images.

**Comment by makseq** [comment]
Releated: https://github.com/heartexlabs/label-studio/issues/729

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio/pull/1426 
Sorry for late answer, but hope this helps.
