### ISSUE TITLE
not showing predictions after training

### ISSUE THREAD

**Issue by hienvantran** [heartexlabs/label-studio#1035]
**Describe the bug**
There are 2 problems:

1. After training ML backend model, I cannot find the model predictions in the UI when labeling. (no error showing and having job_result.json)
![UI_CMD](https://user-images.githubusercontent.com/54805500/121126479-cbfe8900-c85a-11eb-96a4-6bc890ce5bbe.png)

2. Often cannot fully train all 100 epochs, the system will stop training at the middle, 30-70 epochs although dataset is small (50) and have GPU (Azure).
![backendCMD](https://user-images.githubusercontent.com/54805500/121126487-cdc84c80-c85a-11eb-898d-707c8d1088b3.png)

**To reproduce**

1. Import pre annotated data
[task_file: small samples of IMDB dataset for sentiment analysis; bert_classifier.py: model script (get from label-studio-transformers)
2. Manually label some of them
3. Go to ML UI in Setting, connect model (BERT classifier) and start training
4. After finishing, come back to Label UI. In the prediction tab, only the pre annotated predictions are shown.

**Expected behavior**:
ML training should be completed and new predictions should be shown in UI with pre annotated predicts  even if without fully trained models (as it works well in the previous version 1.0.1)
![image](https://user-images.githubusercontent.com/54805500/121126833-66f76300-c85b-11eb-887b-7109d73432ac.png)

**Comment by makseq** [comment]
1. Try to delete predictions via data manager actions. When they are empty, LS will retrieve ML backend.
2. You have to create a new background process or thread which trains the model. LS sends only a signal when to start training and POST /train

**Comment by makseq** [comment]
We added a lot of codes about ML, I hope the ML usage is more clear now. 
I'm closing this issue as unanswered and believe it could be solved with the latest LS 1.3 version.
