### ISSUE TITLE
API `/api/current-user/token` returns bad token in 1.0.2

### ISSUE THREAD

**Issue by bobokvsky** [heartexlabs/label-studio#1049]
**Describe the bug**
API `/api/current-user/token` returns bad token in 1.0.2

**To Reproduce**
1. Run Label Studio
2. Sign up, when go to user settings, we get good token (ex.: `bab6e8097bfce780fb84836ad66d69a2bc81d323`)
3. Use GET from API `/api/current-user/token`, it returns cropped token (ex: `{"detail":"bab6e8097bfce780fb84836ad66d69a`)

**Environment**
 - OS: Ubuntu 20.04.2 LTS
 - Label Studio Version: 1.0.2 (is running local and by Docker)

**Comment by makseq** [comment]
@triklozoid

**Comment by triklozoid** [comment]
Thanks for the report, can you try fix from this PR: https://github.com/heartexlabs/label-studio/pull/1051
If includes little format change `/api/current-user/token` will return `{"token":"bab6e8097bfce780fb84836ad66d69a2bc81d323"}`

**Comment by bobokvsky** [comment]
Yeah, it's good now, thanks!
