### ISSUE TITLE
Configurable behaviour of dragging (moving) a polygon (like pressing CTRL key while dragging moves bounding shapes)

### ISSUE THREAD

**Issue by vijaygill** [heartexlabs/label-studio#105]
**Is your feature request related to a problem? Please describe.**
Many times I end up dragging whole polygon where I just want to move a point. In some cases it is very difficult to make it fit back in on the image.

**Describe the solution you'd like**
Allowing user to have a flag in config.json / config.xml to allow dragging of polygon when only CTRL key is pressed. This way I will be moving stuff when I am sure I want it to move.

I am using only polygons for now so my problem may seem to be related to those only. But you can evaluate it for other shapes too and decide.

**Describe alternatives you've considered**
None TBH..

**Additional context**
None

**Comment by shevchenkonik** [comment]
@vijaygill 

Yes, your point is scalable for other labeling types (for example bounding boxes) and I think that we implement this one on the next versions of LS. Currently, we are focused on features and bugs of polygons, bounding boxes, key points, image segmentation.

If you can describe your workflow with polygons and Image zoom, then we'll implement more correct UI.

**Comment by VictorAtPL** [comment]
@vijaygill @shevchenkonik 
I think this issue can have something in common with my list I wrote in #27:

> [IMPROVEMENT] When you drag the edge (a dot is shown) it should create new point of polygon between the two nearest points and place it in the place you are moving the mouse. Right now it starts to move whole of the polygon, which is not intuitive.

I think we should make here some conclusions what would be the best. I am planning to implement some improvements to _Polygons_ next month.

**Comment by makseq** [comment]
Polygons are strongly reworked and now it's much more comfortable.
