### ISSUE TITLE
Invite People to sign up link, malformed link, running with reversed proxy

### ISSUE THREAD

**Issue by schafsam** [heartexlabs/label-studio#1058]
**Describe the bug**
Invite people to sign up for label-studio. Using the +Add People button under /people I get a wrong link. The link looks like  `http://example.abc.com/labelstudio/labelstudio/user/signup/?token=12Csa` . Meaning the route labelstudio is double.

**To Reproduce**
1. Go to Hamburger sign
2. Go to 'Organization'
3. Click on '+ Add People'
4. See the link http://example.abc.com/labelstudio/labelstudio/user/signup/?token=12Csa

**Expected behavior**
http://example.abc.com/labelstudio/user/signup/?token=12Csa

**Screenshots**
<img width="678" alt="ls-invite-people" src="https://user-images.githubusercontent.com/37704298/122004595-e5508980-cdb4-11eb-8c1e-b43414a03004.PNG">

**Environment (please complete the following information):**
 - CentOS
 - Apache Httpd reverse proxy: Where the route /labelstudio goes to localhost:8080.
 - Label Studio Version [e.g. 1.0.2] within conda and the  `--host "http://example.intern.com/labelstudio"`

**Comments**
Label-studio works and when I remove the extra /labelstudio in the url, I can sign up.
On the server I see a GET /api/current-user/whoami request, when clicking on the '+ Add People' button.

**Comment by makseq** [comment]
@schafsam https://github.com/heartexlabs/label-studio/pull/1062 could you check this branch please, hope it's fixed there.

**Comment by schafsam** [comment]
@makseq: I was able to test it now with the current master branch and it works.
