### ISSUE TITLE
Relations not appearing in UI (relation extraction, v1.0.2.)

### ISSUE THREAD

**Issue by joeydb94** [heartexlabs/label-studio#1072]
**Description of the issue**
The relations are saved (they show up when you export) but they don’t appear on the UI when you go back and look at an annotated task.

**Steps to recreate the issue**
1. Set up relation extraction
2. label a task and add relations
3. When you submit and return to that task, the relation will not appear (shows no relations despite showing up when you export).

**Expected behavior**
Expect to see relations when revisiting a task.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version 1.0.2.

**Comment by smoreface** [comment]
cc: @nicholasrq 

I was able to reproduce this (v1.0.2, Docker install). It seems possibly related to both #1014 and #1026. 

A mobx state tree error appears in the console when you try to view an already-labeled task with relations in the data manager quick view: `Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree.`

**Comment by smoreface** [comment]
Fixed with [version 1.3.0 release](https://github.com/heartexlabs/label-studio/releases/tag/v1.3.0).
