### ISSUE TITLE
Different methods of labeling for Computer Vision tasks

### ISSUE THREAD

**Issue by imjwang** [heartexlabs/label-studio#1074]
**Is your feature request related to a problem? Please describe.**
I don't want to have to click so often

**Describe the solution you'd like**
A drag tool would be great. semi-automated labeling would also be nice

**Describe alternatives you've considered**
coco-annotator](https://github.com/jsbroks/coco-annotator)

**Comment by smoreface** [comment]
@imjwang we're working on improved object detection with less clicking required for the 1.1 release, visible in the roadmap: https://github.com/orgs/heartexlabs/projects/1
It should be available soon, but some of the functionality includes double click to create a bounding box or shape.

**Comment by makseq** [comment]
We support interactive pre-annotations now, check this article: https://labelstud.io/blog/release-130.html
