### ISSUE TITLE
Issue while building from source

### ISSUE THREAD

**Issue by heisenberg1804** [heartexlabs/label-studio#1092]
I followed the exact command mentioned for building from source, but i am getting "ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?".
I just can't seem to resolve this because django is installed in my current conda virtual environment as when i run "django-admin --version" i get the version as "3.1.12".
![image](https://user-images.githubusercontent.com/43610582/122881655-0424c200-d359-11eb-99c2-2932653f2536.png)

**Comment by SAdnen** [comment]
From the error message `ujson` is missing, you can install it with conda: `conda install -c anaconda ujson `

**Comment by heisenberg1804** [comment]
After resolving that issue , and resolving a couple of more issues with numpy and pandas version, i'm stuck with this...
![image](https://user-images.githubusercontent.com/43610582/123170327-0477a700-d498-11eb-9387-479621c48443.png)

**Comment by SAdnen** [comment]
You are trying  to run label-studio from source the code using the command `python label_studio/manage.py ...` and at the same time you are inside a conda environment `label-studio` which has already label-studio installed. The function that is causing this error is `cast_bool_from_str`, it was added 3 days ago, so it exists in the source code but not in your conda env `label-studio`. So, if you want to use the label-studio of your conda env, use the command `label-studio start`, if you want to use the most recent version of label-studio, you can create another conda env, activate the new env and run `pip install -e . ` inside `label-studio` directory.

**Comment by heisenberg1804** [comment]
I had actually resolved the issue with your help thank SAdnen
