### ISSUE TITLE
Slide the mouse over the picture and zoom in and out of the picture

### ISSUE THREAD

**Issue by fanweiya** [heartexlabs/label-studio#1096]
thanks label-studio,very good label annotation tools,please add slide the mouse over the picture and zoom in and out of the picture.

**Comment by makseq** [comment]
@fanweiya it's already there. Please add zoom="true" and zoomControl="true" to <Image> tag. 
Hope it solves your issue. 

For more info: 
https://labelstud.io/tags/image.html#Parameters
