### ISSUE TITLE
Labeling view go back to previous task functionality

### ISSUE THREAD

**Issue by schafsam** [heartexlabs/label-studio#1098]
Front-end labelling view has a Skip and Submit button.

**Suggested solution idea**
An option, controll field or button to go back to the previsou task in the labeling view. Even tough the previous task is labeled to corect or check.

**Rational**
For example If I am a bit to trigger happy with the Skip button or if press the Submit button to early. 
That is usually the case when I am labeling a bunch of "monotonic" data with some pre-annotated labels. So I editing is quicker. Then it can be that I need to go back to the previous task. Because I am browsing with the task and be a bit to trigger happy by clicking either in Skip or Submit to ealry.

**Comment by makseq** [comment]
This feature was added in the latest master commits. You can use latest docker image or wait until LS 1.4.1. 
![image](https://user-images.githubusercontent.com/501780/151669005-ecf9af87-5a99-48fd-bef8-ed7d99c857fe.png)
![image](https://user-images.githubusercontent.com/501780/151669026-d31b356f-50ec-4c8c-9f33-119bf654f3b7.png)
