### ISSUE TITLE
Export only selected items

### ISSUE THREAD

**Issue by mauricio-repetto** [heartexlabs/label-studio#1114]
**Is your feature request related to a problem? Please describe.**
I'm still not sure if this is a bug or should be requested as a feature but I realized the other day that the export actually exports the entire set of items from the project instead of those selected. Sadly, when I realized it was too late.. So I had to manually edit the exported files because I had a bunch of work done that I needed to keep. It's a little annoying to have to create two projects to keep files separated for tagging (i.e. one for training and other for test).

**Describe the solution you'd like**
Export only the items selected (probably to avoid possible human errors there could be a description of how many items are going to be exported).

**Describe alternatives you've considered**
Like I've said.. you could create two projects one for each subset of images to tag but in my case this is not the type of project organization that I would like to have.

**Additional context**
-

**Comment by nateraw** [comment]
:heavy_check_mark: I just came here to submit this issue too. Very frustrating...

**Comment by KDercksen** [comment]
I would love this as well..

**Comment by loveychen** [comment]
+1  for this feature.

**Comment by makseq** [comment]
@loveychen @KDercksen @nateraw @mauricio-repetto 
We are preparing a big changes in export, hope you will love it :-) 

![image](https://user-images.githubusercontent.com/501780/133697116-22cd2dbc-9b26-4e3d-926f-d78151f06eae.png)

**Comment by CySlider** [comment]
How is the status on this one? I really was surprised just now that this does not work, even when a filter is set previously.

**Comment by FabrizioPe** [comment]
Could someone update us on this? It's a really necessary feature :)
Thanks a lot

**Comment by makseq** [comment]
@CySlider @FabrizioPe This feature was release, however GUI is available only in the enterprise edition. 
In opensource you can do it using API or even better SDK:
* API - https://labelstud.io/guide/export.html#Export-snapshots-using-the-API
* SDK - https://labelstud.io/sdk/project.html#create-new-export-snapshot 
* SDK example - https://github.com/heartexlabs/label-studio-sdk/blob/master/examples/export_snapshots.py

To apply a tab filter you should pass this tab id (view id) to this API/SDK call like it's done on this line:
https://github.com/heartexlabs/label-studio-sdk/blob/master/examples/export_snapshots.py#L29

**Comment by Busterfake** [comment]
@makseq I still don't get it... How do you export only selected items, i accidently labeled videos with 10 fps on label studio and changed it to 25 fps. the problem is that the box are no longer at the right place when i change the frame rate. So i would like to export my videos at 25 fps and then export my video at 10 fps. How can i do that ??

**Comment by makseq** [comment]
@Busterfake why are you talking about exporting of selected items? It's completely unrelated to this issue. 

Seems you need to export your labeling into json, then you have to write a script, that changes the timing for your all bbox keyframes corresponding to your new framerate. You will see something like this in json:
```
"result": [
        {
          "id": "pEn7yZzRuh",
          "meta": {
            "text": [
              "sdfsdfsdf"
            ]
          },
          "type": "videorectangle",
          "value": {
            "duration": 42.024,
            "sequence": [
              {
                "x": 28.57142857142857,
                "y": 58.031474698141366,
                "time": 0.04,
                "frame": 1,
                "width": 16.605616605616607,
                "height": 31.257631257631246,
                "enabled": true,
                "rotation": 0
              }
            ],
            "framesCount": 1051
          },
          "origin": "manual",
          "to_name": "video",
          "from_name": "box"
        },
        .... 
```

So, you have to change 
```
                "time": 0.04,
```
for 1st frame it's 0.04 in case of FPS = 25. For FPS = 10, it's 0.1.

**Comment by Busterfake** [comment]
@makseq I don't see how this is not related as the subject of this issue is "Export only selected items" which is exaclty what i need.It is useful in the specific case that I explained above but for amny other reasons too. Like if I add some videos to a project for video annotation, how do I export only the annotations (json format) of these videos and not of all other videos on the project. 

Regardless, thanks for the explanation, ill try this out !

**Comment by Aariciah** [comment]
Unfortunate to see that in Nov 2024 this feature still hasn't been implemented in the open source version. I'm doing NER labeling and I only want to export the tasks I labeled, not all those that I haven't as well.
