### ISSUE TITLE
Add new [category] id attribute in label tags

### ISSUE THREAD

**Issue by mauricio-repetto** [heartexlabs/label-studio#1115]
**Is your feature request related to a problem? Please describe.**
I'm not seeing a way to specify in the settings the id each class should have when exported. A few days ago we split our tagging work in different sets (one per each person) but when we tried to join them we realized that the ids on the json were totally different on each project. Very annoying. You should at least give the ids based on a name order or something that keep consistency between different projects that work with the same labeling idea. Right now it seems that it's based on how they are tagged (the first to be tagged gets the id 0 and so on).

**Describe the solution you'd like**
Give the possibility to specify the ids in the settings, right now it seems that's no possible.

![image](https://user-images.githubusercontent.com/11300196/124016702-53539e00-d9bc-11eb-9485-4dbd6d52ce38.png)

**Describe alternatives you've considered**
I've seen no alternatives to this.

**Additional context**
![image](https://user-images.githubusercontent.com/11300196/124016939-8433d300-d9bc-11eb-9592-7252c479945a.png)
![image](https://user-images.githubusercontent.com/11300196/124017036-9e6db100-d9bc-11eb-874c-6488aa44532f.png)

**Comment by makseq** [comment]
@mauricio-repetto We can't assign ids manually, because it's DB depending and DB decides what ids there will be. 

Why don't you put your ids into task.data and then filter/order by this column?

**Comment by makseq** [comment]
Why can't you use "name" for joining?

**Comment by makseq** [comment]
note: https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/converter.py#L460

**Comment by mauricio-repetto** [comment]
Just in case, we were three persons working on a tagging task, each of us with a local version of the tool. After exporting files to COCO format the idea was to merge "easily" the three files. But then we realized that the ids didn't match, so, yes, we ended up building a python script to read each individual file and do some sort of mapping (based on the name), I think it could be easier if you allow people to specify the id each class should have (or at least to be consistent among tools, the three files had different ids for the exact same classes).

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio/issues/737

**Comment by makseq** [comment]
@mauricio-repetto 
Could you check this PR? If everything ok we will include it to the nearest release! I hope you can do it quickly to be in time. https://github.com/heartexlabs/label-studio-converter/pull/50/

**Comment by mauricio-repetto** [comment]
Hi @makseq I'm not familiar with label-studio code so I don't feel confident enough to approve a pr, so far way of getting the ids looks like it was changed the and it seems to be more consistent now from what I can tell. Thanks for coming back with this issue, much appreciated.

**Comment by makseq** [comment]
We need only your checks with your data on this PR :slightly_smiling_face: No code reviewing.

**Comment by mauricio-repetto** [comment]
yes it does! :raised_hands:

**Comment by makseq** [comment]
MR is merged to master :)

**Comment by mauricio-repetto** [comment]
Thanks very much! :raised_hands:

**Comment by hachreak** [comment]
Hi @makseq @mauricio-repetto 
could you explain how it works?
How can I specify category name and id number?
I can't find it in docs.. :smile: 
Thanks

**Comment by makseq** [comment]
Related:
https://github.com/heartexlabs/label-studio/issues/3653
https://github.com/heartexlabs/label-studio/issues/3324
https://github.com/heartexlabs/label-studio/issues/2886
https://github.com/heartexlabs/label-studio/issues/1115
https://github.com/heartexlabs/label-studio/issues/737
