### ISSUE TITLE
Text labeling not working with spans containing non-standard characters

### ISSUE THREAD

**Issue by somejonus** [heartexlabs/label-studio#1122]
When trying to label a span that contains a non-standard character at the beginning or the end of a word eg. "Collé" not the word itself, but an empty space before or after is marked.

1. Select label to mark a span that contains a non-standard character at beginning or end
2. Double click on span or make selection to label it 

Span should be labeled as expected.

https://user-images.githubusercontent.com/13364398/124103857-fad6dc00-da61-11eb-90d2-98eb88aaf25f.mov

 - OS: MacOS 11.4
 - Label Studio Version v1.1.0

**Comment by Gondragos** [comment]
Just to make sure that I understand the problem. Do you use `granularity= "word"` attribute of the text tag?

**Comment by somejonus** [comment]
Correct!

`<Text name="text" value="$ner" granularity="word"/>`

**Comment by Gondragos** [comment]
It seems that we solved this problem, and it should work well in the last version.

**Comment by Gondragos** [comment]
So I'm closing this issue. Feel free to reopen it if you have any troubles.
