### ISSUE TITLE
Cannot locate the region

### ISSUE THREAD

**Issue by function2-llx** [heartexlabs/label-studio#1125]
**Describe the bug**
Cannot locate the region when click on it.

**To Reproduce**
1. Setup project with the following interface and upload some text.
```xml
<View>
  <View style="display:flex;align-items:start;gap:8px;flex-direction:column">
    <Header name="text-header" value="text"/>
    <View style="height: 400px; overflow: auto">
      <Text name="text" value="$text"/>
    </View>
    <Labels name="labels" toName="text" showInline="true">
      <Label value="la"/>
      <Label value="lb"/>
    </Labels>
  </View>
</View>
```
2. Select a label and annotate it to some region.
3. Scroll to somewhere else
4. Click the region on the right

**Expected behavior**
The text scrolls to where the region locates, however nothing happens. 

**Screenshots**
When click the region on the right, the text does not scroll.
![图片](https://user-images.githubusercontent.com/38486514/124143485-bed16480-dabd-11eb-85c1-2940c0c1d302.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version 1.1.0

**Additional Information**

This function works fine for previous version until I update to the latest 1.1.0 version.

**Comment by function2-llx** [comment]
May I ask why this is added to the 1.3 milestone? This works very well in the previous version.

**Comment by makseq** [comment]
@function2-llx Sorry, I missed when chose the milestone. Thank you for your report.

**Comment by function2-llx** [comment]
By checking commits in [this page](https://github.com/heartexlabs/label-studio/commits/release/1.1.0?after=94e8f7061637800f16551a5e75f4d81e9de3d67b+69&branch=release%2F1.1.0), the oldest commit since which I find this function not work is: c9f2b560eead444d97ac94b74f18ca9b10ac628a, in e7c0642bee79af10a1643c3ca5bb3c0af21e269d it still works.

**Comment by makseq** [comment]
@function2-llx Could you check the latest master branch on the main LS repo? Is it fixed there?

**Comment by function2-llx** [comment]
@makseq I've tried the latest commit in the master branch and it seems to work well again! Thanks!

**Comment by Gondragos** [comment]
Seems to be fixed in https://github.com/heartexlabs/label-studio/milestone/7
