### ISSUE TITLE
Performance issues while exporting a project ~5000 images

### ISSUE THREAD

**Issue by R-Peleg** [heartexlabs/label-studio#1134]
**Describe the bug**
When trying to export a Bounding Box labeling project contains 4982 images, a gateway timeout occurred.
Raising the Nginx timeout did not resolve the problem, with more than 10 minutes passed without a response.

**To Reproduce**
1. create a project
2. Import several thousands of annotated images
3. Hit "Export", then select "COCO" and click "export"

**Expected behavior**
A COCO dataset should be downloaded

**Screenshots**

**Environment (please complete the following information):**
 - OS: mac OS, LS run with `docker-compose up`
 - Label Studio Version master (commit 185ed8e4), with the branch `fix/export-performance` merged.

**Additional context**
Using `py-spy` I collected some profiling info during the request. It seems that much of the time is spent downloading the image files, so a solution might involve handling those downloads better (caching, parallel downloading). The flame SVG reports generated attached.
[profiles.zip](https://github.com/heartexlabs/label-studio/files/6762594/profiles.zip)

**Comment by makseq** [comment]
@R-Peleg Could you try to use the export from the latest master branch?

**Comment by R-Peleg** [comment]
Tried on commit `1a3b1677`, still got timeout

**Comment by makseq** [comment]
We made some improvements here: https://github.com/heartexlabs/label-studio/pull/1151
Could you change the latest master please? @R-Peleg

**Comment by twsl** [comment]
I had the same issue just exporting to COCO format.
There should be a option only to export the label file and keep the images in the cloud.

**Comment by smoreface** [comment]
This should be addressed with the [version 1.3.0 release](https://github.com/heartexlabs/label-studio/releases/tag/v1.3.0).

**Comment by makseq** [comment]
You can use `download_resources` in API request /api/projects/<id>/export?download_resources=0 to avoid image downloading.

**Comment by hyp530** [comment]
Issue not resolved.
