### ISSUE TITLE
Render custom visualizations from Bokeh or iframe/url

### ISSUE THREAD

**Issue by mstump** [heartexlabs/label-studio#114]
We're labeling large, complex, multi-variant time series with > 2000 features. We have an existing workflow that integrates weak labeling, causal graph output and temporal clustering. This workflow runs as a Bokeh/Flask app. 

We have a rudimentary internal labeling tool that I'd like to replace with label-studio but reuse the visualization/exploration logic. 

Is it possible to embed an iframe as the media visualization but reuse all of the tagging/labeling functionality? I'd just need to pass the media parameters as URL query parameters or path elements to the Bokeh/Flask app.

**Comment by tstumm** [comment]
See the documentation of [HyperText](https://labelstud.io/tags/hypertext.html), which is also incorporated in [dialogue analysis](https://labelstud.io/templates/dialogue_analysis.html).
This allows to embed any kind of HTML and should fit your use case quite well.

**Comment by deppp** [comment]
@mstump I think what @tstumm suggests can work well. You'd provide a `value` prop with the iframe code and the URL. Another direction to explore is to create a separate page with the visualization and embed label-studio there directly, check out the npm [package](https://www.npmjs.com/package/label-studio) and embed [docs](https://labelstud.io/guide/frontend.html). It's going to take more integration effort though.

**Comment by deppp** [comment]
@mstump Were you able to integrate LS into your workflow? I'm curious to learn about your experience and what can be improved. Thanks!
