### ISSUE TITLE
Negative width and height in bbox after resize in object detection example

### ISSUE THREAD

**Issue by VladYushchenko** [heartexlabs/label-studio#1141]
**Describe the bug**
Task/Example: image object detection 
It is possible to create bbox with negative width, height or both using Label Studio web interface.  

**To Reproduce**
1. Create bbox and select it
2. Resize bbox by dragging bottom right corner towards upper left corner and little bit beyond
3. The bbox will flip and the bbox anchor point shall be located under the bbox 
4. Check bbox coordinates - both W and H will be negative

**Expected behavior**
My expectation would be that bbox (X,Y,W,H) has W > 0 and H > 0, so that X and Y are referring always to the top left corner. 

Overall, such bbox flipping behavior is expected, but then top left corner shall be changed accordingly.

This induces hard-to-debug errors in large datasets once data is exported for training. 
And furhtermore is really hard to tell smth is wrong by just looking at the labeled image.

**Screenshots**
Step 2
![Selection_017a](https://user-images.githubusercontent.com/13710810/124642448-260d6100-de90-11eb-8b13-f7109ceb56ee.png)

Step 3
![Selection_018](https://user-images.githubusercontent.com/13710810/124642471-2c034200-de90-11eb-8541-549f46137a4e.png)

Step 4
![Selection_019](https://user-images.githubusercontent.com/13710810/124642482-2efe3280-de90-11eb-8aff-c5d6cef73232.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Label Studio Version: 1.1.0, bug exists in earlier versions 1.0 and 0.9.1 

**Additional context**
Possibly was referred in https://github.com/heartexlabs/label-studio/issues/416 

Thanks!

**Comment by makseq** [comment]
@VladYushchenko Please. could you check it in LS 1.3 ?

**Comment by VladYushchenko** [comment]
@makseq In LS 1.3 works as expected, thanks a lot!
