### ISSUE TITLE
Enable zoom by scrolling

### ISSUE THREAD

**Issue by twsl** [heartexlabs/label-studio#1142]
**Is your feature request related to a problem? Please describe.**
It's super annoying to zoom by clicking a button, if you have small objects in big pictures

**Describe the solution you'd like**
zoom by scrolling.

**Describe alternatives you've considered**
-

**Additional context**

**Comment by denck007** [comment]
If you click the image then hold down CTRL while using the scroll wheel you can zoom in and out. CTRL+SCROLL_DOWN is zoom in (which is backwards of what is typically expected).

**Comment by twsl** [comment]
Thats why scrolling didn't work, I didn't tried the inverted direction. Thanks for the tip @denck007.
That means I'm now rooting for changing th scroll direction.

**Comment by makseq** [comment]
@twsl does it mean that this issue is solved?

**Comment by twsl** [comment]
Unless you want to resolve the invertion of the scrolling direction in this issue, yes.
