### ISSUE TITLE
Image labeling: increase the width and height of the image

### ISSUE THREAD

**Issue by davidblom603** [heartexlabs/label-studio#1146]
When using large screens, and annotating high resolution drone images, the image canvas is too small. It would be great if the container element around the canvas is not set to a max width of 750 pixels.

Screenshot for label studio 1.1.0:

![Screenshot from 2021-07-07 16-07-29](https://user-images.githubusercontent.com/63226970/124773832-98884a80-df3d-11eb-9761-a02d641f7afd.png)

Screenshot with the max-width style removed:

![Screenshot from 2021-07-07 16-07-29](https://user-images.githubusercontent.com/63226970/124773805-92926980-df3d-11eb-9957-fe496dffefab.jpg)

**Comment by twsl** [comment]
That goes hand in hand with #1142 , but maybe both of these issue should rather be placed at the frontend repo?

**Comment by denck007** [comment]
I ran into this as well,  you need to set the maxWidth property in the tag, not in the style. Your tag should look like this:
`<Image name="image" value="$image" zoom="true" zoomControl="true" maxWidth="1500px"/>`

**Comment by niklub** [comment]
Another way of doing that is to specify `maxWidth` in percentages like 
```
<Image name="image" value="$image" zoom="true" zoomControl="true" maxWidth="100%"/>
```
Please close this issue if it works in large screen cases.
