### ISSUE TITLE
Show PDF from local storage or upload

### ISSUE THREAD

**Issue by sumanshusamarora** [heartexlabs/label-studio#1155]
I am trying to use PDF Classification template and when i upload my pdfs, they show as a text path to the pdf in-stead-of pdf view. Screenshot attached. Is this something expected or a bug?
![Capture](https://user-images.githubusercontent.com/45642655/124915648-2135e200-e035-11eb-8a2c-95f13c2f4411.PNG)

**Comment by dentalala** [comment]
Hi! You need to prepare a JSON-file with `HyperText` tag. You can find out how a similar config is set up [here at Playground](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CHyperText%20name%3D%22pdf%22%20value%3D%22%24pdf%22%2F%3E%3Cbr%3E%3Cbr%3E%20%20%3CHeader%20value%3D%22Rate%20this%20article%22%2F%3E%3Cbr%3E%20%20%3CRating%20name%3D%22rating%22%20toName%3D%22pdf%22%20maxRating%3D%2210%22%20icon%3D%22star%22%20size%3D%22medium%22%20%2F%3E%3Cbr%3E%3Cbr%3E%20%20%3CChoices%20name%3D%22choices%22%20choice%3D%22single-radio%22%20toName%3D%22pdf%22%20showInline%3D%22true%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Important%20article%22%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Yellow%20press%22%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E) and compare it to yours.

**Comment by sumanshusamarora** [comment]
The example takes the pdf source from an image which seems to work but in my case pdf comes from local storage and thats not working.

**Comment by schafsam** [comment]
Hi @sumanshusamarora 

This is how I was able to get my images into the project. But should work the same way with PDF’s. 
 
I assume you run LabelStudio with the local files serving, described in the guide the whole section [here](https://labelstud.io/guide/storage.html#Local-storage) . 
 
To get the path you can check the "Treat every bucket object as a source file" and copy a file to your _absolute local path_. 
![0](https://user-images.githubusercontent.com/37704298/125577669-71429d8b-ee80-49ed-9edd-c66c5fa1fe76.png)
 
Sync Storage and import your test document. 

![0-1](https://user-images.githubusercontent.com/37704298/125577783-89b0e250-fdbf-47f9-a20b-e7a5ab5ede50.png)

Then check with the blue </> button in the Data Manager the documents URL.
  

`
{ 
    "id": 1, 
    "data": { "$undefined$": "https://some-url.top/labelstudio/data/local-files/?d=data/inbox/test.jpeg" },
    "annotations": [], 
    "predictions": [] 
} 
`
 
_If you need further customization for your tasks_ 
 
For an image on your local deployment it might look like this "$undefined$": "/data/local-files/?d=dataset1/1.jpg". 
But the **/data/local-files/** route stays the same where the path to your file follows in the **?d=/abs/path/to/your/file** http URL parameter. 
 
Finally create your task according to your URL schema just discovered and set your path. Uncheck the “Treat every bucket object...” copy the files to the data directory and import your created task.json.


If there are hellper moduls for such kind of import task I am also very interested in them.

Hope this helps.

**Comment by sumanshusamarora** [comment]
Hi @schafsam The images work just fine mate. The problem is pdf preview. Try putting a pdf into your storage and see if that shows up even for pdf rating project.

**Comment by schafsam** [comment]
@sumanshusamarora

I just tried the PDF classification template from the Playground with creating the task from syncronizing the storage. It also does not work for me. This is what I got:

<img width="833" alt="ls-pdf-problem" src="https://user-images.githubusercontent.com/37704298/125753876-121e47f3-0bd7-4ada-98ef-f34ea4ab48da.png">

<img width="833" alt="ls-pdf-problem-data-manager" src="https://user-images.githubusercontent.com/37704298/125753928-698ee0c6-04f0-42f1-8e38-3e0e797cfc8e.png">


@dentalala 
I run version 1.1.0 from a conda environment.

**Comment by sumanshusamarora** [comment]
Ok, me too. Version 1.1.0 in a conda environment.

**Comment by makseq** [comment]
@sumanshusamarora @schafsam You have to use specially prepared tasks and load them as JSON files: 

task.json
```
{
    "pdf": "<embed src='https://app.heartex.ai/static/samples/sample.pdf' width='100%' height='600px'/>"
}
```


Add Local Storage (or another one) and DO NOT press sync button. 
After you should prepare your task.json (or tasks.json) manually using links provided via Local Storage (like `https://some-url.top/labelstudio/data/local-files/?d=data/inbox/test.jpeg`) in <embed> tag:

```
{
    "pdf": "<embed src='https://some-url.top/labelstudio/data/local-files/?d=data/inbox/test.jpeg' width='100%' height='600px'/>"
}
```

I know It's not very convenient, but we don't have direct PDF support yet in LS.
