### ISSUE TITLE
Upload already labeled data

### ISSUE THREAD

**Issue by JulesBelveze** [heartexlabs/label-studio#1160]
**Describe the bug**
I have an already labeled dataset and I want to upload it to Label Studio. I am using the API to do so and everything is working perfectly. 

However, I would like those tasks to be considered as labeled. Because what I'm seeing right now in the project panel is `0 /  xxx`.
When is a task considered as "done"? Because I can seen that the `Completed` column has a value and I've tried to add a field `is_labeled=True` to my tasks when uploading but without success.

Thanks for your help !

**Comment by JulesBelveze** [comment]
I managed to achieve the wanted behaviour by adding:
```
"ground_truth": False
```
to the tasks.

But now when trying to export the data from the UI,  I get an empty JSON and an error 502 when using the API...

**Comment by makseq** [comment]
Looks like a bug, LS doesn't update is_labeled=True statistics or did it incorrectly. What API do you use?

**Comment by makseq** [comment]
What is your LS version? We fixed some troubles with is_labeled in the latest release 1.1.0

**Comment by JulesBelveze** [comment]
Hey @makseq thanks for the quick answer!
I'm currently using v1.0.1 let me do the upgrade and see if I still run into the same trouble 😄

**Comment by makseq** [comment]
I hope it was solved with LS update.
