### ISSUE TITLE
NER HTML Tagging gives wrong offsets

### ISSUE THREAD

**Issue by prohor33** [heartexlabs/label-studio#1164]
**Describe the bug**
Markup json from NER HTML looks like this:
```
"start": "/div[1]/p[10]/text()[3]",
"end": "/div[1]/p[10]/text()[3]",
"startOffset": 2,
"endOffset": 16,
"text": "",
"htmllabels": [
  "Judge"
...
```

From Andrey comment in Slack:
> XPath describing start & end nodes of range in document. text()[2] means second text node in the given region. Like for `<p>Hi <b>user</>!!!</p> xpath /p[1]/text()[2]` would point to **text node** “!!!”
> Now LS use current document state to calculate this nodes **even including already labeled regions** (as they alter html). So to reproduce this on your side you should apply all the previous results to display current one.

Does this means HTML markup from LS become useless if the user labels entities in not top-to-bottom order? In this case offset will be counted from previous entity, but we don’t know has this entity already been marked or not when  current entity was labeled.
Given the fact, that we can’t guarantee top-to-bottom markup order, this raises questions if could use html ner markup at all.
For now, we don't know workaround for this issue. Any help would be appreciated.

**To Reproduce**

1. Tag any document with NER HTML Tagging
2. Export json markup
3. Can't use markup, because of wrong entities positions - offsets counted from previous html tag, including highlight tags, which where there in the moment of markuping. 

**Expected behavior**
Exported markup should contain entities position in original html, without highlights.

**Environment (please complete the following information):**
 - OS: any
 - Label Studio Version 1.0.1

**Comment by makseq** [comment]
Fixed in release https://github.com/heartexlabs/label-studio/releases/tag/v1.1.1
