### ISSUE TITLE
Unable to export my tagging 

### ISSUE THREAD

**Issue by shubhangi27397** [heartexlabs/label-studio#1174]
**Describe the bug**
I am unable to export my data.

It is taking long time when I click on export but nothing happen and no error I found there.

I have also copy both sqlite.dll and sqlite.def and deploy on it another machine but unable to see any data from database backup.

Suggest me some steps.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

**Comment by makseq** [comment]
@shubhangi27397 
Could you provide some logs from LS terminal? And a browser console?

**Comment by makseq** [comment]
@shubhangi27397 Is your problem solved with new LS versions? What type of export do you have?

**Comment by smoreface** [comment]
This should be addressed with the [version 1.3.0 release](https://github.com/heartexlabs/label-studio/releases/tag/v1.3.0).
