### ISSUE TITLE
meta fields are lost after importing

### ISSUE THREAD

**Issue by lluissalord** [heartexlabs/label-studio#1179]
**Describe the bug**
We are importing our tasks using pre-annotated data and we are including some metadata on `meta` field which is a dictionary with two string values. On the original file we have this `meta` field with data, but after importing if we export or look on the Target Storage we see that the `meta` field is empty.

**To Reproduce**
1. Import JSON task/s with some data in `meta` field
2. Export data as JSON file

**Expected behavior**
There should appear the metadata information on the exported file

**Environment (please complete the following information):**
 - OS: Linux
 - Most updated Label Studio Version from pip install

**Comment by makseq** [comment]
@lluissalord Where do you place `meta` ? In a task or in a prediction? 
I recommend to put meta in a task.data:

```
{
 data: {
  meta: { ... }
 }, 
 predictions: [{...}]
}
```

**Comment by lluissalord** [comment]
@makseq I place the `meta` at task level as it is specified on the API https://labelstud.io/api#tag/Tasks
```
{
 data: {
   text: "",
 }, 
 predictions: [{...}]
 meta: { ... }
}
```

I understand that inside task.data will work because that field is intent to remain, however I would recommend to fix the issue or modify the API in order to not confuse.

**Comment by makseq** [comment]
@lluissalord Thank you for your feedback, I hope we remove it soon.

**Comment by makseq** [comment]
@lluissalord Just checked this issue, in the latest master the export json file contains meta field with all subfields. However, we will remove meta from task in the future. 

https://github.com/heartexlabs/label-studio/pull/1307
