### ISSUE TITLE
Use prelabeling (precomputed suggestions) in NER task

### ISSUE THREAD

**Issue by gf0507033** [heartexlabs/label-studio#118]
Hello, thx for great work!

I'm stuck on simple problem. Can I add to `tasks.json` field (compatible with completion's `result` field) with precomputed suggestions? I.e. my goal is to verify or modify existing markup, not to create one.

And one more question: can I add bunch of classification fields to NER task?

**Comment by draganrakas** [comment]
+1 for this!

This tool is great, and having the ability to support precomputed suggestions would be a huge improvement for our use case as well!

**Comment by deppp** [comment]
Hey @gf0507033 and @draganrakas 

Just want to let you know that we're currently working on this, and it's gonna be included in one of the next releases. I'll update you on our progress here.

Stay tuned!

**Comment by makseq** [comment]
Hi, @gf0507033 and @draganrakas, I've implemented predictions here: https://github.com/heartexlabs/label-studio/issues/118

Let's check it together. The receipt is: 
1) open tasks.json,
2) add "predictions": [ {...}, {...} ] to each task inside,
3) the format of prediction is the same as completion BUT: 
  a) exclude "id" field from prediction
  b) add "model_version": "version 1" (optional)
  c) add "created_ago": "1 hour" (optional)

The example could be found here: https://github.com/heartexlabs/label-studio/blob/2f3d85c479171d235d1f1fd1742dcd7736ac3dab/examples/named_entity/tasks.json

So, it will be great if you write me feedback!

**Comment by vade** [comment]
Some feedback - does it make sense for a static json file to have a relative time offset?

May I suggest having an optional "created" with a date time string rather than "created_ago"? The UI could then handle logic to dynamically say, 3 days ago, then tomorrow, 4 days, or alternatively just show the absolute date which also seems reasonable.

BTW, this project is awesome, and is already proving hugely helpful and very easy to set up. So thank you!

**Comment by makseq** [comment]
@vade Thank you for your feedback!
"created" is a good idea. But right now you can use "created_ago" for as "created" because it's a simple string. It's a little big crooked but working :-)

**Comment by vade** [comment]
Oh I see. Ha. Makes sense. Thanks for the quick reply.

**Comment by draganrakas** [comment]
Love the change, looking forward to the release. Thank you!

**Comment by niklub** [comment]
We've added full support for prelabeling in https://github.com/heartexlabs/label-studio/releases/tag/v0.2.2
