### ISSUE TITLE
Labeling instructions ignore empty lines formatting 

### ISSUE THREAD

**Issue by zakajd** [heartexlabs/label-studio#1180]
**Describe the bug**
When typing text into "Labeling instructions" field, I use new lines to split the text into logical blocks. 
But when it showed, all text is formatted as one big paragraph, without any formatting. 

**To Reproduce**
1. Create new project
1. Go to Settings -> Intructions -> Labeling Instructions
2. Type any text with empty lines.
4. See error when it's displayed.

**Expected behavior**
Proper handling of empty lines.

**Screenshots**
<img width="819" alt="image" src="https://user-images.githubusercontent.com/15848838/125446758-125b974f-cb61-4802-8c32-9c5ebb5d5913.png">
<img width="392" alt="image" src="https://user-images.githubusercontent.com/15848838/125446800-61820a3d-28fd-43f3-bf5a-982e3c85398a.png">

**Environment (please complete the following information):**
 - OS: Ubuntu 16
 - Label Studio Version: 1.1

**Comment by makseq** [comment]
Instructions are in html format, please, use <br> for new line.
