### ISSUE TITLE
Selected parameter in `Label` tag not working

### ISSUE THREAD

**Issue by queenieho** [heartexlabs/label-studio#1185]
**Describe the bug**
Setting selected to be true in a label is not preselecting it. 

In an NER usecase, we're trying to allow the user to select a label once, and label multiple entities until they select a different label. This would be possible only if we're able to get the `selected` parameter working on a `Label`, but that's not the case at the moment. 

**To Reproduce**
Given the following codeblock, I would expect the `Person` label to be pre-selected. But it's not. 
```
<View>
  <Labels name="label" toName="text" choice="single">
    <Label value="Person" background="red" selected="true"/>
    <Label value="Organization" background="darkorange"/>
  </Labels>
  <Text name="text" value="$text"/>
</View>
```

**Expected behavior**
If we set the `selected` parameter on a `Label` I expect it to be selected.

**Comment by hlomzik** [comment]
Hi, @queenieho!
`<Label selected/>` really is broken, we'll fix it soon, it may be useful.
But to label continuously by the same label you can use setting "Keep label selected after creating a region".
Settings available from small button on the right sidebar with annotation info.

**Comment by hlomzik** [comment]
Hi! It was fixed finally. You can try it in [LSF master](https://github.com/heartexlabs/label-studio-frontend) right now or we'll release this to LS very soon

**Comment by hlomzik** [comment]
Now every time you switch the annotation this Label will be selected. And it is selected on initial task load of course
