### ISSUE TITLE
How do I access the label-studio without login?

### ISSUE THREAD

**Issue by corum04190tws** [heartexlabs/label-studio#1186]
Hi, as title
I've built  the label studio in dockerfile, I also add the "LABEL_STUDIO_USERNAME", "LABEL_STUDIO_PASSWORD" and "LABEL_STUDIO_USER_TOKEN" in env; then I still need to login my account.
Does any method let me access label studio without login the account?

Thanks for your answer!

**Comment by makseq** [comment]
@corum04190tws Hi! Why do you have to avoid a login? 

>  I also add the "LABEL_STUDIO_USERNAME", "LABEL_STUDIO_PASSWORD" and "LABEL_STUDIO_USER_TOKEN"

This pre-register your user in LS, so you can use these credentials in LS. You have to do it only once, your browser will save your credentials.

**Comment by corum04190tws** [comment]
@makseq Hi!! Thanks for your answer!
I want other team members to use this great labeling tool, that I made a docker image. If user want to use the tool, they have to know the account or register and then login, which is not a convenient step.

**Comment by makseq** [comment]
Relative: https://github.com/heartexlabs/label-studio/issues/1281

**Comment by makseq** [comment]
@tahesse SAML logins is supported in LS Enterprise only, so you can avoid the login screen in the Enterprise edition.

**Comment by vineetverma28** [comment]
@makseq  I need to restrict login in case of iframe. How can restrict login page.

**Comment by jtlz2** [comment]
@makseq How can I disable the sign-up magic link as well? If gets into the wild (from the console) then all bets are off.

**Comment by Aldrumont** [comment]
Hello,

Today, December 1, 2023, I am working on serving a page in Label Studio without the login form. I found a way to bypass the login by modifying the label_studio/users/views.py file. In the user_login function, I added the following code snippet:

```
from django.contrib.auth import get_user_model, login
from django.shortcuts import redirect

def user_login(request):
    # ... existing code ...

    # Automatically login with a predefined user
    email = 'email@example.com'  # Replace with an email already in the database
    user = get_user_model().objects.get(email=email)
    login(request, user, backend='django.contrib.auth.backends.ModelBackend')
    
    next_page = request.GET.get('next', '/')  # Redirect to the home page by default
    return redirect(next_page)

    # ... existing code ...
```

This modification automatically logs in a user with a specified email address that already exists in the database. Remember to replace 'email@example.com' with the actual email address you want to use.

Please note that this approach should be used cautiously, especially regarding security implications, as it bypasses the standard authentication process.

**Comment by prashant-sharma22** [comment]
Hi @Aldrumont can I build custom image of label studio with these changes exposing env variables for email and password?
