### ISSUE TITLE
Programmatically create relations

### ISSUE THREAD

**Issue by uklft** [heartexlabs/label-studio#1191]
Hi folks,

its a breeze to work with LS, thanks for the great tool!

Would it be possible to create Relations between Annotations/Predictions programmatically?

We would like to use the ml-backend to create Predictions that contain relations.
A simple solution would allow me to create an id for each Prediction-Label, which then can be referenced by the Relation. 
But as far as i've seen Predictions neither allow a Label-ID, nor may they contain Relations at all.

Alternatively I thought about achieving this by (ab)using the API and the ML-Backend, with the drawback that i have to store the Prediction as Annotation:
1. Use `predict()` to get the tasks
2. Get Predictions from the model
3. Create Annotations from the Predictions via the REST API to obtain the ID
4. Get the Annotations by ID via REST
5. Find Annotations in Predictions by text + start + end
6. Add Relations to Annotation with `from_id + to_id`
7. Update Annotations via REST
8. Return Predictions

If there is an easier way to achieve this i would be grateful for a hint!

**Comment by makseq** [comment]
Hi, 

Predictions are same as annotations, so you can try to make a relation by hands, submit an annotation and then explore the result. Copy the same relation structure to your ML backend. 

[Check this example to see how the relation json looks](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Link%20logger%20events%20with%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20monitoring%20signals%20using%20relations%22%2F%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3C!--%20Text%20setup%20--%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Mark%20actions%20in%20text%22%20size%3D%226%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabels%20name%3D%22logger_label%22%20toName%3D%22logger%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Error%22%20background%3D%22red%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Success%22%20background%3D%22orange%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FLabels%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3CText%20name%3D%22logger%22%20value%3D%22%24event%22%2F%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3C!--%20Time%20series%20setup%20--%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Mark%20regions%20in%20time%20series%22%20size%3D%226%22%2F%3E%3Cbr%3E%20%20%20%20%3CTimeSeriesLabels%20name%3D%22ts_label%22%20toName%3D%22ts%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Error%22%20background%3D%22red%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22High%20load%22%20background%3D%22darkorange%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FTimeSeriesLabels%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3CTimeSeries%20name%3D%22ts%22%20valueType%3D%22url%22%20value%3D%22%24csv%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sep%3D%22%2C%22%20timeColumn%3D%22time%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CChannel%20column%3D%22temperature%22%20units%3D%22%C2%B0C%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20strokeColor%3D%22%2317b%22%20legend%3D%22Temperature%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FTimeSeries%3E%3Cbr%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E%3Cbr%3E%3Cbr%3E%3C!--%3Cbr%3E%20%20%20%20Sample%20task%20data%20and%20completion%3Cbr%3E%20%20%20%20are%20for%20preview%20only%3Cbr%3E--%3E%3Cbr%3E%3Cbr%3E%3Cbr%3E%3C!--%20%7B%3Cbr%3E%20%20%22data%22%3A%20%7B%3Cbr%3E%20%20%20%20%22event%22%3A%20%22Authorization%20success%5CnError%20requesting%20auth%3A%20Authorization%20check%20failed%22%3Cbr%3E%20%20%7D%2C%3Cbr%3E%20%20%22completions%22%3A%20%5B%7B%3Cbr%3E%3Cbr%3E%20%20%20%20%22result%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%2022%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%2071%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22text%22%3A%20%22Error%20requesting%20auth%3A%20Authorization%20check%20failed%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22labels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22Error%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%22ohdmBWCbqB%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22logger_label%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22logger%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22labels%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%206%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%2017%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22instant%22%3A%20false%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22timeserieslabels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22High%20load%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%22JlujfAED9-%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22ts_label%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22ts%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22timeserieslabels%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%200%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%2021%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22text%22%3A%20%22Authorization%20success%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22labels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22Success%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%22pA0JwD5dAF%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22logger_label%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22logger%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22labels%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%2013%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%2022%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22instant%22%3A%20false%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22timeserieslabels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22Error%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%22G4m2fkQAb4%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22ts_label%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22ts%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22timeserieslabels%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22from_id%22%3A%20%22JlujfAED9-%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22to_id%22%3A%20%22pA0JwD5dAF%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22relation%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22direction%22%3A%20%22right%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22from_id%22%3A%20%22G4m2fkQAb4%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22to_id%22%3A%20%22ohdmBWCbqB%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22relation%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22direction%22%3A%20%22right%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%3Cbr%3E%20%20%20%20%5D%3Cbr%3E%20%20%7D%5D%3Cbr%3E%7D%3Cbr%3E--%3E%3Cbr%3E)

**Comment by uklft** [comment]
Hi, thanks for the reply!
I looked into the json data of annotations and relations.
My problem here is that the `id` field is set (randomly?) by the application on upload.
So if i want to create a relation programmatically i would need to know the id's of the Annotation beforehand:

~~~json
{
    "from_id": "G4m2fkQAb4",
    "to_id": "ohdmBWCbqB",
    "type": "relation",
    "direction": "right"
}
 ~~~

If there was a way to set the id field on upload i could use that.

**Comment by makseq** [comment]
Why can't you use randomly generated ids? The main note: they must be different for all annotations.

**Comment by uklft** [comment]
I wasn't sure if i break some inner logic of the app if i upload Labels with the id already set. Testing this by setting predictions in the database seems to work, so i will test this further and see if it works with the ml_backend.
Thanks for the hint!

**Comment by makseq** [comment]
No, it mustn't break inner app logic.
