### ISSUE TITLE
How to combine labels and choices? 

### ISSUE THREAD

**Issue by liebkne** [heartexlabs/label-studio#1201]
Hi, 

I'd like to show different choices when different labels is selected, to add attributes to labels. Something like 

```
<View>

  <Text name="text" value="$text" />
  
  <Labels name="label" toName="text">
    <Label value="Person" background="red"/>
    <Label value="Organization" background="darkorange"/>
  </Labels>
  
  <Choices name="other-props" toName="text"
  	   choice="single" showInLine="true"
           visibleWhen="region-selected"
           whenTagName="label"
           whenLabelValue="Person">
    <Choice value="111" />
    <Choice value="222" />
  </Choices>

  <Choices name="other-props1" toName="text"
  	   choice="single" showInLine="true"
           visibleWhen="region-selected"
           whenTagName="label"
           whenLabelValue="Organization">
    <Choice value="xxx" />
    <Choice value="yyy" />
  </Choices>

</View>
```

does not work properly. I know I can use metadata to add attributes. But I'd like to provide different choices to help annotating. How can I do that? Thanks!

**Comment by makseq** [comment]
I checked your labeling config and I'd say it works. What's wrong with it exactly? 
When I select different labels there are different choices are shown.

**Comment by liebkne** [comment]
Sorry. It indeed works. I misunderstood the 'region' concept before.

**Comment by addisonklinke** [comment]
@makseq Is it possible to have different control tags per label? Specifically for each region show 
* `TextArea` corresponding to `whenLabelValue="Organization"`
* `Choices` corresponding to `whenLabelValue="Person"`

**Comment by Marxlp** [comment]
I tried, but it didn't work, @failable. as far as I know, the region is the text selected after some label selected. 


> Sorry. It indeed works. I misunderstood the 'region' concept before.
