### ISSUE TITLE
image classification

### ISSUE THREAD

**Issue by sonfiree** [heartexlabs/label-studio#122]
Please add image classification. Binary and multi classification

**Comment by shevchenkonik** [comment]
@sonfiree currently, we prepare a new minor release with image classification and the first implementation will be soon.

**Comment by niklub** [comment]
> Please add image classification. Binary and multi classification

Hi, @sonfiree ! Could you please clarify what exactly do you mean? The data labeling for image classification with single and multi label support is currently available. This config does the job:
```
<View>
  <Choices name="image_class" toName="image" choice="single">
    <Choice value="first_class"></Choice>
    <Choice value="second_class"></Choice>
  </Choices>
  <Image name="image" value="$image_source"></Text>
</View>
```
and changing `choice="multiple"` lead to multilabel classification. 
Please refer to [docs](https://labelstud.io/tags/choices.html) or see [examples](https://github.com/heartexlabs/label-studio/tree/master/examples/image_multilabel) for details
