### ISSUE TITLE
Reset button doesn't reset images if it has multiple completions 

### ISSUE THREAD

**Issue by lxtadhamnawito** [heartexlabs/label-studio#1224]
**Description**
Let's say you are a reviewer and reviewing someone's work. So you opened his Task it contains (2 completions) both contain his image classification for example. 
Now if I tried to do some changes to one of the completions and switched back to the second one, then returned again to the first, and pressed RESET, nothing will happen.
After investigation I found that history[0] which the reset returns the snapshot to got overridden by reinit().
where it override the first occurrence which was the guy's work with what it sees right now which the guy's work and my work, so it  resets me to a wrong snapshot.

**Steps to reproduce the behavior:**
1. Open a Task that has a some polygon segmentation work done inside for a completion, and has a previous completions too
2.  Add a new polygon
3. Go to any of the other previous completions
4. Return to the one you edited
5. Press Reset

**Expected behavior**
My added polygon should be removed and completion should be reset to where it was before.

 - OS: Tried on both Windows & Mac (but currently i'm using windows)
 - Label Studio Version: 0.7.3

**Additional context**
Reset works fine with all the other XML configurations that I've tried but it mainly fail with anything related to image if u followed the above steps.
Also it works fine with Images if and only if u didn't toggle between completions.

**Comment by makseq** [comment]
@lxtadhamnawito Sorry, this is very old LS version and we don't support it. Why are you using it still?

**Comment by lxtadhamnawito** [comment]
> @lxtadhamnawito Sorry, this is very old LS version and we don't support it. Why are you still using it?

@makseq , I've been using it for long time ago and built things upon it and can't upgrade to newer versions of LS rn.
