### ISSUE TITLE
Ability to *enlarge* an image (not zoom in) or fix the default image display size (for small images)

### ISSUE THREAD

**Issue by wanburana** [heartexlabs/label-studio#1229]
**Is your feature request related to a problem? Please describe.**
The images i was annotating is very small (80*60) and the display is showing that size, which is too small to do comfortably
![image](https://user-images.githubusercontent.com/66191669/127422425-b6d81899-a501-4868-8275-db1c8d2357a3.png)

I'm not sure if I miss anything but I have tried changing the config according to this [page](https://labelstud.io/tags/image.html)
![image](https://user-images.githubusercontent.com/66191669/127422543-861bd83a-90b4-4804-8438-fb04d4925130.png)
Still, the setting here still did not satisfy what I want, for example, all the zoom option 'zoom in' the image instead of enlarge it.

**Describe the solution you'd like**
The config setting to *enlarge* the image (not zoom in)

**Describe alternatives you've considered**
A default display image size (in case of small or very large image)

**Additional context**
It was hard to work with in case of labelling or segmenting small or very large image

**Comment by makseq** [comment]
@wanburana Try to combine `width`, `maxWidth` and zoom options:

```
<View>
<Image name="image" value="$image" 
         zoom="true" zoomBy="1.1" zoomControl="true"
         maxWidth="800px" width="800px" />
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="Car" background="blue"/>
  </RectangleLabels>
</View>
```

Hope this helps.

**Comment by wanburana** [comment]
> @wanburana Try to combine `width`, `maxWidth` and zoom options:
> 
> ```
> <View>
> <Image name="image" value="$image" 
>          zoom="true" zoomBy="1.1" zoomControl="true"
>          maxWidth="800px" width="800px" />
>   <RectangleLabels name="label" toName="image">
>     <Label value="Airplane" background="green"/>
>     <Label value="Car" background="blue"/>
>   </RectangleLabels>
> </View>
> ```
> 
> Hope this helps.

yep, it worked!, thank you~
