### ISSUE TITLE
Label UI editing without destruction of completed tasks

### ISSUE THREAD

**Issue by vade** [heartexlabs/label-studio#123]
**Is your feature request related to a problem? Please describe.**
After building a labeling interface and using it for sometime, its often insightful and inspires some possible user interface changes. However, editing the labeling interface requires completions to be destroyed.

**Describe the solution you'd like**
It would be nice if one could edit the layout, without changing the labels, and if somehow a smart 'only destroy task completions if the label interface output is inconsistent with completed tasks' 

**Describe alternatives you've considered**
Alternatively an opt out of destroying the task data, that says 'your labels may be inconsistent'

Alternatively somehow locking the editing of <choices> or other tags that effect labels, and allowing only edits to say, View or style components?

**Additional context**

**Comment by deppp** [comment]
@vade Thanks for the report. It's indeed a limitation of the current implementation, and something that will go away when we split up the visual representation from the input/output description. That's going to happen only sometime in early 2020, though. I'll mark this as won't fix for now.
