### ISSUE TITLE
Regex filter

### ISSUE THREAD

**Issue by lluissalord** [heartexlabs/label-studio#1231]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use regex patters in order to filter among all the text tasks which I have in my project

**Describe the solution you'd like**
Add regex operation on the filters

**Describe alternatives you've considered**
Currently I am using the `contains` operation but it lacks some features in comparison to regex

**Comment by makseq** [comment]
@lluissalord Could you check this branch please?
https://github.com/heartexlabs/label-studio/pull/1300

**Comment by makseq** [comment]
Regex filters can now be used in release 1.2.
