### ISSUE TITLE
GCP import doesn't work correctly

### ISSUE THREAD

**Issue by anyght** [heartexlabs/label-studio#1232]
I've deploy label studio with the latest image on Kubernetes, then complete the form to connect to google storage bucket. the sync is OK, but I have  the task number updated with no picture added.

![image](https://user-images.githubusercontent.com/59748997/127687837-e7fa6e82-edbf-4790-8540-1388d77d2037.png)

when I delete the bucket sync, i can see some objects but I cant access to it.

![image](https://user-images.githubusercontent.com/59748997/127689683-368a439b-7c17-4543-b26e-098dbadb3d3d.png)

Someone know what is happened?

**Comment by makseq** [comment]
@anyght Do you have 23 tasks on your bucket or more?

**Comment by anyght** [comment]
I have 23 task on my bucket.

**Comment by farioas** [comment]
@anyght could you please provide the detailed configuration of volumes from your k8s manifest: `spec.containers.volumes[]`

**Comment by anyght** [comment]
![image](https://user-images.githubusercontent.com/59748997/127841883-a0b43eb1-97b6-486f-84b3-149794c13059.png)
![image](https://user-images.githubusercontent.com/59748997/127842018-99f91cfc-0883-4ec4-bd00-94f3e0b5555f.png)

**Comment by anyght** [comment]
any suggestion?

**Comment by eric-onesourceregulatory** [comment]
It's most likely due to label studio not being able to produce a signed URL because of Google Cloud permissions and setup.

![image](https://user-images.githubusercontent.com/66736084/131672046-6aae7c26-912a-4e64-8bcd-dd4d3a34fa05.png)

If you run your label-studio with logging enabled, you may see errors like the above in your output when you go to the project
task list and don't see any of the tasks imported from the Google Storage Bucket.

`label-studio start --log-level DEBUG --no-browser 2>&1 | tee ls_eric.log
`

Next question though is how to fix this.

**Comment by farioas** [comment]
Please ensure, that `https://www.googleapis.com/auth/cloud-platform` scope is granted for the instance.

**Comment by eric-onesourceregulatory** [comment]
What can I say, @farioas , but simply thanks.  That solved my issue.  Is there someway we can filter this important information back to the documentation to save others from running into the same issue?

**Comment by makseq** [comment]
@smoreface I saw your thumb up, but please, add this info to docs asap! 
@farioas you rock!

**Comment by anyght** [comment]
> Please ensure, that `https://www.googleapis.com/auth/cloud-platform` scope is granted for the instance.
> 
> Ref: https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

Hello, do you have some references for a kubernetes deployment?

**Comment by farioas** [comment]
Sure 🤓 

https://cloud.google.com/ai-platform/pipelines/docs/configure-gke-cluster#grant-access

**Comment by anyght** [comment]
![image](https://user-images.githubusercontent.com/59748997/135489009-35eea9fe-cd2e-415c-8ccc-daefd3cccc44.png)

this is the security configuration, that is sufficient for get bucket objet? I have try to connect on pod and execute the command `gsutils cp <object>`it work correctly. So, I don't known where I'm missing

**Comment by namazia** [comment]
@anyght , Yeah I gave that a try but didn't work for me. For me it's the same as yours, runs fine locally but in google kubernetes deployment gets permission denied error.
