### ISSUE TITLE
Ability to insert Views within <Choices> tags for more substantive label UI layouts.

### ISSUE THREAD

**Issue by vade** [heartexlabs/label-studio#124]
**Is your feature request related to a problem? Please describe.**
A particular labeling task I have has close to 130 multiple choice for a multi class image classification task. These tags are broken up into logical groups, and it would be nice to be able to design a UI in such a way that allows me to group these `choices` within multiple flexed views.

It appears however, either due to a bug, or due to how specific design decisions, that one cannot have multiple `choices` tags (as they would require the same name) and nor can one have a nest `view` or `header` tags inside of a `choices` tag group.

ie: 

```
<View>
  <choices name="someUniqueName">
    <view>
    <choice value="choice1"></choice>
    <choice value="choice3"></choice>
    </view>
    <view>
    <choice value="choice2"></choice>
    <choice value="choice4"></choice>
    </view>

  </choices>
</View>
```

While the above is a silly example, being able to control the layout (and perhaps even visibility) of some choices might be very helpful.

**Comment by deppp** [comment]
@vade Excellent point! Making multiple tags with the same name can't work because then the model may get confused. But adding an ability to adjust the view can be an option. I'll experiment later today and let you know if that's doable.

As a side note, I've run some experiments with nesting the `Choice` tags inside other `Choice` tags, something like this:

```html
<View>
  <Choices name="checkbox">
    <Choice value="main group 1">
      <Choice value="sub group 1"></Choice>
    </Choice>
    <Choice value="main group 2" />
  </Choices>
</View>
```

It would render the main group only, and you can "open" it by clicking on it and find a specific item. Also, something that can be useful is to show an input to filter.

**Comment by vade** [comment]
Oh goodness the latter option would be amazing!

**Comment by vade** [comment]
Yea if nested choices are revealed when the parent is clicked that would be amazing. Does

`    <Choice value="main group 1">` 

also have the ability to have a value and alias to send to the model and show up as a task output? 

Perhaps if it has the tags it can? That would help make a flexible 'tree' of choices to navigate.

Alternatively it might be nice to have the sub-group expand - select some choices for the data , and then collapse the set of choices while retaining your selection.

Perhaps some sort of disclosure triangle like metaphor? 
 
Very much appreciate the quick reply! Thank you!

**Comment by deppp** [comment]
@vade that is now supported with the latest release, you can include the `<View>` and `<Header>` and `<HyperText>` tags inside either `Choices` or `Labels` tags. Check it out

**Comment by joaourbano** [comment]
Hi,

Browsing through this topic. Could someone get me an example of it working? Running into problems.

Thanks

**Comment by makseq** [comment]
Try to check this examples:

1 [conditional classification](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CText%20name%3D%22text1%22%20value%3D%22%24text1%22%20%2F%3E%3Cbr%3E%20%20%3CChoices%20name%3D%22sentiment%22%20toName%3D%22text1%22%20showInLine%3D%22true%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Positive%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Negative%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Neutral%22%20%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%3Cbr%3E%20%20%3CView%20visibleWhen%3D%22choice-selected%22%3Cbr%3E%20%20%20%20%20%20%20%20whenTagName%3D%22sentiment%22%20whenChoiceValue%3D%22Positive%22%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22What%20about%20this%20text%3F%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CText%20name%3D%22text2%22%20value%3D%22%24text2%22%20%2F%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%20%20%3CChoices%20name%3D%22sentiment2%22%20toName%3D%22text2%22%3Cbr%3E%20%20%09%20%20%20choice%3D%22single%22%20showInLine%3D%22true%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20visibleWhen%3D%22choice-selected%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20whenTagName%3D%22sentiment%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20whenChoiceValue%3D%22Positive%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Positive%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Negative%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Neutral%22%20%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E)

2 [two level classification](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%3Cbr%3E%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%20%2F%3E%3Cbr%3E%20%20%3CChoices%20name%3D%22sentiment%22%20toName%3D%22text%22%20showInLine%3D%22true%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Positive%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Negative%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Neutral%22%20%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%3Cbr%3E%20%20%3CChoices%20name%3D%22other-props%22%20toName%3D%22text%22%3Cbr%3E%20%20%09%20%20%20choice%3D%22single%22%20showInLine%3D%22true%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20visibleWhen%3D%22choice-selected%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20whenTagName%3D%22sentiment%22%3E%3Cbr%3E%20%20%20%20%3CView%20style%3D%22width%3A100%25%22%3E%3Cbr%3E%20%20%20%20%20%20%3CHeader%20value%3D%22Other%20properties%20of%20the%20text%22%20%2F%3E%3Cbr%3E%20%20%20%20%3C%2FView%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Descriptive%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Emotional%22%20%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%3Cbr%3E%3C%2FView%3E)

3 [taxonomy tag](https://labelstud.io/templates/taxonomy.html)
