### ISSUE TITLE
Undo works unexpectedly in semantic segmentation tasks

### ISSUE THREAD

**Issue by royschwartz2** [heartexlabs/label-studio#1242]
**Describe the bug**
Undo has three problems:
1. It removes the last brush stroke (expected behaviour), but also unchecks the chosen label (unexpected behaviour). This means the user has to re-select the label after each undo action. 
2. Also, if a first annotation was done on an image, this behaviour also leaves the region in the region list, although it's empty. 

**To Reproduce**
Choose a label, annotate, undo (cmd-Z).

**Expected behavior**
See above

**Environment (please complete the following information):**
 - OS: MacOS 11
 - Label Studio Version 1.1

**Additional context**

**Comment by makseq** [comment]
The fix is in the latest master branch.
