### ISSUE TITLE
In semantic segmentation, hiding annotations and submitting/updating task deletes the annotations

### ISSUE THREAD

**Issue by royschwartz2** [heartexlabs/label-studio#1243]
**Describe the bug**
After annotating using the semantic segmentation brush, if you hide the annotations and click submit/update, all annotations are deleted. 

**To Reproduce**
1. Create an annotation
2. Hide it (using the open eye button to change it into a closed eye button)
3. Click submit if new, or update if previously submitted

**Expected behavior**
Annotations should not be deleted

**Environment (please complete the following information):**
 - OS: MacOS 11
 - Label Studio Version 1.1

**Additional context**

**Comment by makseq** [comment]
@royschwartz2 Just checked in the latest LS master, this issue has gone.
