### ISSUE TITLE
Semantic segmentation module becomes sluggish with several regions annotated

### ISSUE THREAD

**Issue by royschwartz2** [heartexlabs/label-studio#1244]
**Describe the bug**
When annotating several regions and labels the program becomes very sluggish. For example, zooming in and out takes a long time, hiding/unhiding annotations takes time. 

**To Reproduce**
Annotate several regions and labels (seems like it's more of a problem with different labels)

**Expected behavior**
According to the release notes this problem was fixed with version 1.1. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS 11
 - Label Studio Version 1.1

**Additional context**

**Comment by makseq** [comment]
Hope this fixed. Feel free to re-open
