### ISSUE TITLE
Hotkey for brush size in semantic segmentation

### ISSUE THREAD

**Issue by royschwartz2** [heartexlabs/label-studio#1247]
**Is your feature request related to a problem? Please describe.**
I work with annotations that require pixel accuracy. Currently changing the brush size is a bit of a drag, since it requires going back to the scrolling brush size element, and doesn't show the actual brush size. 

**Describe the solution you'd like**
A hotkey would be great - to increase/decrease brush size. In addition, it would be great if the actual brush size appeared next to the scrolling element. 

**Describe alternatives you've considered**

**Additional context**

**Comment by nicholasrq** [comment]
take a look at #1453 

we now have <kbd>alt</kbd> + <kbd>[</kbd> and <kbd>alt</kbd> + <kbd>]</kbd> for decreasing/increasing Brush and Eraser size
also you'll find <kbd>alt</kbd> + <kbd>+</kbd> and <kbd>alt</kbd> + <kbd>-</kbd> for zooming in and out

**Comment by royschwartz2** [comment]
Hi. Thanks for the update. However, there are now substantial issues that prevent (at least us) from using version 1.3 of Label Studio:
1. The brush changed functionality pretty drastically. It now no longer allows for pixel-level annotation, as the minimum size is quite large. 
2. Not a deal breaker - the hotkeys for changing brush size (which are, by the way, just [ and ], without alt) don't allow for pixel-level changes - they just jump to a size much larger/smaller, rendering them impractical. 
3. You'd expect the eraser to be affected by the brush size change, but it doesn't seem to be the case. 
We will be sticking with version 1.2 for now.

**Comment by nicholasrq** [comment]
@royschwartz2 yeah, you're right, shortcuts are just [ and ], sorry for a misleading comment

brush size issues (as well as eraser size) were fixed in 1.3.post1

speaking of brush and eraser size to be synced. maybe we can introduce that as an option, but generally speaking those are different tools, so both have their own size settings

**Comment by royschwartz2** [comment]
Thanks @nicholasrq. I actually meant the brush size scrollbar - it doesn't seem to change the eraser size at all (at least on 1.3 before post1).

**Comment by nicholasrq** [comment]
yeah, currently eraser size doesn't depend on brush size. these are different tools that both have their own size property. as I said previously, we can make it an optional setting or something. expect it to be shipped during 1.3 lifecycle. I will also let you know here when it's available

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can label pixels using brushes.
You can change the brush size using command + option + mouse wheel up/down.
RectLabel stores the brush size history.
Brush size 1 means 1px in the image.
https://rectlabel.com/help#create_pixels

![brush_history](https://user-images.githubusercontent.com/1954306/214841155-9a5e293e-9d13-4958-afdc-1dadba0730c9.jpg)

**Comment by Michel-Liao** [comment]
Is there a way to reduce the minimum brush size? I'd like to do pixel-level changes.
