### ISSUE TITLE
Ability to split NER labelling tasks by users

### ISSUE THREAD

**Issue by draganrakas** [heartexlabs/label-studio#126]
**Is your feature request related to a problem? Please describe.**
* We have a small group of people who would like to divide an NER labelling job. We would like to assign the same jobs to multiple users, so we would need a basic notion of 'multi tenancy.' 

**Describe the solution you'd like**
1) I would like the ability to distribute NER tasks to multiple users. It would be great to be able to have a set of 'completed solutions' by each user, as opposed to a global solution set per running instance of label-studio.

2) I saw a button called "AWS Groundtruth" in the UI, but I could not find any docs in the repository documentation on how to integrate this with AWS Groundtruth before (I have also not used Groundtruth before, so unsure how to set this up).

**Describe alternatives you've considered**
* We are considering deploying multiple instances of label-studio, one per person. This is a bit cumbersome, but a workaround for now.
* We are considering looking into AWS Groundtruth integration, but admittedly did not dig too deep into this approach.

**Comment by deppp** [comment]
@draganrakas 

What you describe is available as part of our commercial solution. There is a plan to open-source it, making it possible to do multi-person labeling, but not any set dates for that.

Regarding the ground truth, it's not related to the AWS, but we treat ground truth items as an ultimately labeled correctly, and those can be used to verify the model or annotator's performance. 

I'd love to learn more about what you're working on and show you what've got. Please drop me an email `michael at heartex.net`

**Comment by iqbalfarz** [comment]
What's an update on this,  please? I want the same thing to distribute the tasks to different annotators without using different sessions of LS.

**Comment by makseq** [comment]
@iqbalfarz if you are using LS 1.0.0 and higher, it should be already there.
