### ISSUE TITLE
Get predictions API database error

### ISSUE THREAD

**Issue by mbuet2ner** [heartexlabs/label-studio#1261]
**Describe the bug**
Documented API call for ".../api/predictions/" fails with status code 500. 
There seems to be a database query error for the organization field (see additional context for error message).
However, ".../api/organizations/" returns a valid organization `[{'id': 1, 'title': 'Label Studio'}]`.

**To Reproduce**
GET request at ".../api/predictions/" or ".../api/predictions/{prediction_id}". Look at response JSON.

**Expected behavior**
Should list all predictions.

**Screenshots**
none

**Environment (please complete the following information):**
 - OS: Windows, official Docker Image
 - Label Studio Version 1.1.0

**Additional context**
Full JSON error response:
> {'id': 'df02d48f-8bbb-4c20-a0d9-0821ef4ded8b',
 'status_code': 500,
 'version': '1.1.0',
 'detail': "Cannot resolve keyword 'organization' into field. Choices are: cluster, created_at, id, mislabeling, model_version, neighbors, result, score, task, task_id, updated_at",
 'exc_info': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper\n    return bound_method(*args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/rest_framework/mixins.py", line 38, in list\n    queryset = self.filter_queryset(self.get_queryset())\n  File "/label-studio/label_studio/tasks/api.py", line 323, in get_queryset\n    return Prediction.objects.filter(organization=self.request.user.active_organization)\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 942, in filter\n    return self._filter_or_exclude(False, *args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 962, in _filter_or_exclude\n    clone._filter_or_exclude_inplace(negate, *args, **kwargs)\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace\n    self._query.add_q(Q(*args, **kwargs))\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1358, in add_q\n    clause, _ = self._add_q(q_object, self.used_aliases)\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1377, in _add_q\n    child_clause, needed_inner = self.build_filter(\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1258, in build_filter\n    lookups, parts, reffed_expression = self.solve_lookup_type(arg)\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1084, in solve_lookup_type\n    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())\n  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1481, in names_to_path\n    raise FieldError("Cannot resolve keyword \'%s\' into field. "\ndjango.core.exceptions.FieldError: Cannot resolve keyword \'organization\' into field. Choices are: cluster, created_at, id, mislabeling, model_version, neighbors, result, score, task, task_id, updated_at\n'}

**Comment by yoku2010** [comment]
Hi @mbuet2ner,

It has been fixed in the master branch.

Please check this commit:
https://github.com/heartexlabs/label-studio/commit/508722583d342623834f9e0a63a8ab437fe5bf6a

This code will release soon as you can see it has been merged with the master branch.

If you need a quick fix, so please pull the master branch code.

Thanks

**Comment by mbuet2ner** [comment]
Hi @yoku2010 ,

Thanks for the info 👍 .
Closing it for now then!
