### ISSUE TITLE
For semantic segmentation tasks eraser size is static but should be adjustable 

### ISSUE THREAD

**Issue by royschwartz2** [heartexlabs/label-studio#1262]
**Is your feature request related to a problem? Please describe.**
The current eraser size for semantic segmentation tasks is static and cannot be changed. For tasks requiring pixel-accuracy it's too big. 

**Describe the solution you'd like**
The brush slider should also work for the eraser. Instead, when moving the slider the brush tool is selected again. 

**Describe alternatives you've considered**

**Additional context**

**Comment by smoreface** [comment]
Fixed with [version 1.3.0 release](https://github.com/heartexlabs/label-studio/releases/tag/v1.3.0).
