### ISSUE TITLE
typo in example code from "Evaluating Named Entity Recognition parsers" blog

### ISSUE THREAD

**Issue by tomasohara** [heartexlabs/label-studio#1277]
**Describe the bug**
Typo in sample code from https://labelstud.io/blog/Evaluating-Named-Entity-Recognition-parsers-with-spaCy-and-Label-Studio.html:
>          texts = df['line_test'] 
should be 
>          texts = df['line_text']
That is, the wrong key _line_te**s**t_ is used for data frame column.

**To Reproduce**
Try to run the sample code from the above blog.

**Expected behavior**
After running the script, there should be the the two files tasks.json and lines_clean.csv.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Label Studio Version: 1.1.0

**Additional context**
 - Although technically not part of the code base, this seems to be the best example for doing non-trivial NLP with Label Studio.

**Comment by makseq** [comment]
@smoreface Could you check & fix it please?
