### ISSUE TITLE
Cannot instantiate NER template via command line

### ISSUE THREAD

**Issue by tomasohara** [heartexlabs/label-studio#1278]
**Describe the bug**
Cannot instantiate NER template from the command line as per https://labelstud.io/templates/named_entity.html. Instead an error is reported: 
> $ label-studio init --template=named_entity named_entity_project
> usage: label-studio [-h] [--version] [-b] [-db DATABASE] [--data-dir DATA_DIR] [-d]
> ...
> label-studio: error: unrecognized arguments: --template=named_entity

**To Reproduce**
- Run `label-studio init --template=named_entity named_entity_project`

**Expected behavior**
No error messages.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Label Studio Version: 1.1.0

**Additional context**

**Comment by makseq** [comment]
@tomasohara Since LS 1.0 there is no support for  `--template=<name>` option. You can create a new project with some labeling config using API: https://api.labelstud.io/#operation/api_projects_create

**Comment by tomasohara** [comment]
At the very least this is a documentation bug. Via https://labelstud.io/templates/named_entity.html#Run:
```
label-studio init --template=named_entity named_entity_project
label-studio start named_entity_project
```

Workaround based on Slack:
```
config_path=annotation_templates/natural-language-processing/named-entity-recognition/config.xml
label-studio init --label-config $config_path named_entity_project
```

There are 10 distinct instantiations of this issue:
```
$ grep '\-\-template=' ./docs/source/templates/* | wc -l
10

$ grep '\-\-template=' ./docs/source/templates/*
./docs/source/templates/audio_regions.md:label-studio init --template=audio_regions audio_regions_project
./docs/source/templates/dialogue_analysis.md:label-studio init --template=dialog_analysis dialog_analysis_project
...
./docs/source/templates/transcribe_audio.md:label-studio init --template=transcribe_audio transcribe_audio_project

$ git tag --list | tail -1
v1.2.0
```
Arguably, since this was on the Label Studio website for a while, this feature seems cast in stone. (I had checked the WInternet Archive WayBack machine in case there was a recent change. I had the same issue with earlier versions via pip.)

Note that the --label-config approach is a bit awkward, especially as there are now nearly three dozen templates:

```
$ find label_studio/annotation_templates -name 'config.xml' | wc -l
33

$ find label_studio/annotation_templates -name 'config.xml'
label_studio/annotation_templates/structured-data-parsing/tabular-data/config.xml
label_studio/annotation_templates/structured-data-parsing/html-entity-recognition/config.xml
...
label_studio/annotation_templates/time-series-analysis/signal-quality/config.xml
```

Therefore. re-adding support for --template would be good.

**Comment by makseq** [comment]
@smoreface Please, check the documentation from previous message.

**Comment by makseq** [comment]
@tomasohara Thank you very much for your report!
