### ISSUE TITLE
Duplicates in export json

### ISSUE THREAD

**Issue by HarshSharma12** [heartexlabs/label-studio#1289]
**Describe the bug**
For an object detection task, if the `Total annotations per task` is more than 1 then the export json contains duplicates for all the tasks. The expected number of annotations if the `Total annotations per task` is n would be n but the json contains 2*n items and each of them will have all the annotations. 

**To Reproduce**
1. Create a new project. 
2. Update the labeling interface using the Object Detection template
3. Import new file/files
4. Open an image to annotate. 
5. Draw one or more bounding boxes and click `Submit`
6. Click `Create Copy`
7. Optional: Update the annotations. (It's easier to see the duplicates if the values are different)
8. Click `Submit` again
9. Click `Export` and export as JSON.

The exported JSON file will have a list with 2 objects and both of them are exactly the same. The annotations also contain two objects which correspond to the two copies created above.

**Expected behavior**
The exported JSON should not contain any duplicates. Either the two main objects should be different with each corresponding to the copy of the image or there should be only one object with annotations containing the details about the copies. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2718684/129281590-b64ad8ce-3e96-492a-9dc3-5f7359b0ffae.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version: 1.1.0
```
{
  "label-studio-os-package": {
    "version": "1.1.0",
    "short_version": "1.1",
    "latest_version_from_pypi": "1.1.0",
    "latest_version_upload_time": "2021-06-30T22:55:06",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "1.1 doc updates (#1110)",
    "commit": "536f604d066958ebb00a4f36aed7aed395250dce",
    "date": "2021-06-30 15:44:26 -0700",
    "branch": "master",
    "version": "1.0.2+76.g536f604d"
  },

  "release": "1.1.0",
  "label-studio-frontend": {
    "message": "Improve Labels styles",
    "commit": "5a34b62e57653484bb5d9924cfd821a7b81de996",
    "branch": "master",
    "date": "2021-06-30T20:10:42Z"
  },

  "dm2": {
    "message": "Don't close QuickView by Enter",
    "commit": "d12a691d1e941768c3067ccb15abe5498f8a453b",
    "branch": "master",
    "date": "2021-06-30T16:06:22Z"
  },

  "label-studio-converter": {
    "version": "0.0.29"
  },

  "label-studio-ml": {
    "version": "1.0.0"
  }
}
```

**Additional context**
I found duplicates in JSON and COCO exports. Also, I tested only object detection but this might be a general issue with export.

**Comment by smoreface** [comment]
@HarshSharma12 This has been fixed in version 1.1.1. Thanks!
