### ISSUE TITLE
Sticky selection of Rectangle and polygon Labels 

### ISSUE THREAD

**Issue by suvojit-0x55aa** [heartexlabs/label-studio#1293]
**Is your feature request related to a problem? Please describe.**
It is frustrating to scroll down from the image to select the type of label every time for small object annotations.

**Describe the solution you'd like**
Sticky selection of labels for polygon and rectangles, once selected it'll stay selected until it's deselected or another label is selected.

**Comment by makseq** [comment]
Maybe you are looking for this option? 
![image](https://user-images.githubusercontent.com/501780/129991761-6eb603d7-b3b8-41b8-be5a-2a425465b7ec.png)
![image](https://user-images.githubusercontent.com/501780/129991747-7c4b8f61-b58d-4ccd-9517-959fe9c0f7e6.png)

**Comment by suvojit-0x55aa** [comment]
Yes, thank you. Didn't know the option was there.
