### ISSUE TITLE
Project configuration - multiple save buttons can lose data

### ISSUE THREAD

**Issue by vade** [heartexlabs/label-studio#130]
**Describe the bug**
When configuring a project - each section has a save button. However its common to configure multiple options in multiple sections in 'one go'

Hitting save after doing so may cause one to loose configurations in other sections. 

**To Reproduce**
1. Go to 'Project, configure'
2. Click on 'Collaborators'
3. Configure options in Instruction, Interface and Completions.
4. Click one of the save buttons.
5. Only one of the options configured is saved.

**Expected behavior**
All options are saved.

**Comment by makseq** [comment]
It seems it's not a bug. Each section has own "Save" button. To save anything in section you need to tap corresponding to this section "Save". But yes, it's not very comfortable, in future we'll make an instant saving of options without "Save" buttons.

**Comment by vade** [comment]
I agree it’s not a bug - but it’s a design issue that makes it easy to configure things and then lose the configuration unexpectedly. Thanks for consideration!
