### ISSUE TITLE
Access denied for release 1.2.0

### ISSUE THREAD

**Issue by apohllo** [heartexlabs/label-studio#1319]
**Describe the bug**
I'm trying to access
https://labelstud.io/blog/release-120.html

and I get:

403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: NRKZ7AF5DKG6MZKG
HostId: sV6fnicwbqLp7sw8gRy+MZ3caMhIlLuMpyg2QdEuEuZ3rTdVbshuKJau1jH3Cc/kEOZAPWf/R1I=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: AccessDenied
Message: Access Denied

**Comment by makseq** [comment]
@apohllo Sorry, I think it was a cache from AWS servers. Please, try it again with a full page reload. It must work.

**Comment by apohllo** [comment]
Yes, it works. Thank you!
