### ISSUE TITLE
how to label images in yolo format

### ISSUE THREAD

**Issue by besbesmany** [heartexlabs/label-studio#1320]
I want to label images with yolo format

**Comment by makseq** [comment]
1. Create a project
2. Import your data
3. Setup labeling config with bounding boxes 
4. ![image](https://user-images.githubusercontent.com/501780/129990874-25f1d0bc-0d22-4890-b886-aec966c968c4.png)
4. Annotate images
5. Click Export button on the Data manager page
6. Select YOLO
![image](https://user-images.githubusercontent.com/501780/129990983-1cc24f55-ef88-4922-8ec7-d7e128362f23.png)

Hope this helps!

**Comment by besbesmany** [comment]
thank you
