### ISSUE TITLE
Time Series labelling: X-axis doesn't change when view is expanded in overview channels

### ISSUE THREAD

**Issue by TueLindhart** [heartexlabs/label-studio#1329]
**Describe the bug**
When the grey box is dragged, the x-axis for each of the time-series doesn't change (i.e. the time range stays the same). 

**To Reproduce**
1. Go to a time series labelling task. 
2. Click on a task and expand view in overview channels. 
3. Notice the x-axis for each time-series channel don't change. 

**Expected behavior**
The x-axis should change accordingly to the the dragging of the grey box. 

**Screenshots**
<img width="463" alt="Screenshot 2021-08-19 at 10 48 09" src="https://user-images.githubusercontent.com/52419754/130038660-06e72e46-c8bd-4dda-a2de-41c95c5ff232.png">
<img width="463" alt="Screenshot 2021-08-19 at 10 48 19" src="https://user-images.githubusercontent.com/52419754/130038679-75efc0e7-fb1f-4bdb-b092-2d85d707e7af.png">

**Environment (please complete the following information):**
 - OS: Using heartexlabs latest docker image
 - Label Studio Version 1.2

**Additional context**
Following is the view code: 

```bash
<View>
    <!-- Control tag for region labels -->
    <TimeSeriesLabels name="label" toName="ts">
        <Label value="Anomaly" background="#FFA39E"/>
    </TimeSeriesLabels>
    <!-- Object tag for time series data source -->
    <TimeSeries name="ts" valueType="url" value="$ts" sep="," timeColumn="timestamp" timeFormat="%Y-%m-%d %H:%M:%S" timeDisplayFormat="%Y-%m-%d %H:%M" overviewChannels="Moisture">
        <Channel column="moisture" units="% moisture" displayFormat=",.2f" strokeColor="#1f77b4" legend="Moisture" height="80" fixedScale="true"/>
        <Channel column="humidity" units="Relative humidity" displayFormat=",.2f" strokeColor="#C54B30" legend="Humidity" height="80" fixedScale="true"/>
        <Channel column="temperature" units="Celsius" displayFormat=",.2f" strokeColor="#2FDF41" legend="Temperature" height="80" fixedScale="true"/>
    </TimeSeries>
</View>
```
and here is a snippet from the data:
```bash

timestamp,temperature,humidity,moisture
2021-08-02 00:44:25,25.5955,37.0,9.47716
2021-08-02 04:44:58,24.0814,36.0,9.275624
2021-08-02 08:45:31,22.9358,40.0,9.152367
2021-08-02 12:49:38,23.1361,46.0,9.241283
2021-08-02 16:46:37,24.6288,44.0,9.448731
2021-08-02 20:47:10,25.3685,43.0,9.519965
2021-08-03 00:47:43,24.9653,39.0,9.435855
2021-08-03 04:48:16,24.1695,39.0,9.319768
2021-08-03 08:52:23,23.2776,41.0,9.221717
2021-08-03 12:49:22,23.2856,44.0,9.256682
2021-08-03 16:49:55,23.9826,47.0,9.389549
2021-08-03 20:50:27,24.8157,43.0,9.47716
2021-08-04 00:50:59,24.0814,37.0,9.348224
```

**Comment by pjvalla** [comment]
Any update on this issue -- this has been an issue for a while.

**Comment by hlomzik** [comment]
Sorry, forgot to text you back. We've fixed this some time ago, it is in the LS master, will be included in the next release for sure.

**Comment by pjvalla** [comment]
Thanks for the update.
