### ISSUE TITLE
Time series labelling: Enable default overview channel width

### ISSUE THREAD

**Issue by TueLindhart** [heartexlabs/label-studio#1330]
**Is your feature request related to a problem? Please describe.**
Each time a new time series is shown I need to drag the grey box to show the full time series which becomes frustrating. 

**Describe the solution you'd like**
I would like it is possible to give a default tag in the view-code that enables to show the full time-series. 

**Describe alternatives you've considered**
It doesn't need to be a tag but that it the easiest implementation I can think of. 

**Additional context**
To clarify I would like the default to be: 
<img width="463" alt="Screenshot 2021-08-19 at 10 56 14" src="https://user-images.githubusercontent.com/52419754/130039855-a7e1c55a-f0bd-430c-944b-10933a3266b2.png">

instead of this

<img width="463" alt="Screenshot 2021-08-19 at 10 56 42" src="https://user-images.githubusercontent.com/52419754/130039926-2b312520-09d3-4b9c-a895-bd94ec2dcd2e.png">

**Comment by hlomzik** [comment]
Hi! Yes, we have this in the roadmap, and it's easy to implement, so will be released soon.
For now you can do this by fixing the code — change `times.length >> 2` to `times.length - 1` in Time series.js in LSF and include new build into LS

**Comment by TueLindhart** [comment]
Are you soon implementing this in your next release? :-)

**Comment by TueLindhart** [comment]
??

**Comment by makseq** [comment]
@TueLindhart Could you check it in this PR please? https://github.com/heartexlabs/label-studio/pull/1942

**Comment by makseq** [comment]
Merged in master branch, it will be included to LS 1.4.1.
