### ISSUE TITLE
labeling setup error : Created annotations are incompatible with provided labeling schema, we found:

### ISSUE THREAD

**Issue by maniappan** [heartexlabs/label-studio#1340]
Had setup the labeling with the following code :
[labelcode.txt](https://github.com/heartexlabs/label-studio/files/7026523/labelcode.txt)
``

I was able to annotate a few images and when I went back to add additional labels, I started getting this error : 

Validation error 63d9c9b6-7fd7-4745-ac23-51953361014d
Created annotations are incompatible with provided labeling schema, we found:
9 with from_name=comment, to_name=image, type=textarea

Let me know what has gone wrong.
Environment : version 1.1.0 with pip installation and sqllite in one version and postgresql database in another, both have this issue.

**Comment by makseq** [comment]
@maniappan  could you try to add toName="image" to your TextArea?

**Comment by maniappan** [comment]
Worked, thanks @makseq.

**Comment by ijmiller2** [comment]
Have been troubleshooting a very similar error and [discussing with Sarah and Andrey in Slack](https://label-studio.slack.com/archives/CQ8LYPPJS/p1645115772315399). This ended up resolving my error too.
