### ISSUE TITLE
Export Image Classification Label Data with Images

### ISSUE THREAD

**Issue by Sean12697** [heartexlabs/label-studio#1350]
**Is your feature request related to a problem? Please describe.**
With Image Segmentation labels I have the ability to export as JSON, JSON-MIN, CSV, TSV, COCO, Pascal VOC XML and YOLO, the last few having the ability to export images alongside the label data, with an Image Classification setup I only have the ability to export as JSON, JSON-MIN, CSV and TSV, none of which export images.

**Describe the solution you'd like**
Ideally there would be an additional option to export with images for the main four export types, if it's a toggle or four more options ("JSON with Images", etc).

**Describe alternatives you've considered**
Any alternative that allows me to export the images within a project alongside the labels.

**Additional context**
The closest issue that I have found to mine is #568, although this issue seems to stem from an error being thrown, rather than the lack of a feature.

**Comment by makseq** [comment]
@Sean12697 I'm not sure we will support image downloading in the future for the following reasons: 
1. It's not secure, LS shouldn't have an access to user data. Now data is available only on the client side browsers. 
2. It might take a long time to download large dataset with images/audio/etc. 
3. s3/gcs/etc links must be resolved while downloading, it's very hard to implement, long to resolve links, etc. 

Why can't you place all images next to annotations on your side? What are your difficulties?
Maybe we can look at this problem from a different angle and solve it?

**Comment by Anang1502** [comment]
Hi @makseq 

I was not able to download the image data while exporting the annotation data in coco format while using the label-studio app (while I am able to do this while running locally on 8080 port). In addition to this, the image file names in the result.json are different from the original names of the images at the time of importing in label-studio. Because of this issue, I cannot even use the images in the local directory for training purposes. This issue of file name modification makes your above-mentioned solution copy locally saved files in the image directory kind of futile.

**Comment by KonstantinKorotaev** [comment]
Hi @Anang1502 
Could you please describe the steps you do?
As I understood you have a local instance of Label Studio and serving files as local storage (without importing them), is it correct?

**Comment by Anang1502** [comment]
Hi Konstantin,

I am using the label studio on the app (https://app.heartex.com/user/login/) to label the images. I am importing the image data into the app and then labeling them. While exporting the labeled image data in coco format we get a zip file. Zip file includes the result.json file (with annotations data) and the images directory (which includes all the images used for labeling). The images directory is empty for me. Now I can use the image files which are stored locally but the file names in result.json is changed from the original name as mentioned in my previous comment. This problem of empty images directory does not occur if I use the local instance of label studio on the 8080 port. Please let me know if you need any more details.

**Comment by KonstantinKorotaev** [comment]
Hi @Anang1502 
We have switched off downloading resources for Label Studio Enterprise.
You can map names by deleting uuid4 in filename start and replace space with underscore
