### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by mpomarole** [heartexlabs/label-studio#1353]
**Is your feature request related to a problem? Please describe.**
We need to use label studio in other languages. This feature request is to track the ability to switch languages through the settings panel.

**Describe the solution you'd like**
I want to be able to switch between translations of the strings on the frontend. So labelers can work in their own language.

**Describe alternatives you've considered**
I am considering using [Django's translation middleware](https://docs.djangoproject.com/en/3.2/topics/i18n/translation/).

**Additional context**

**Comment by makseq** [comment]
@mpomarole Thank you for your request. Our frontend is fully using React and you should consider to change React parts:
* Editor - https://github.com/heartexlabs/label-studio-frontend
* Data manager - https://github.com/heartexlabs/dm2
* Other pages - https://github.com/heartexlabs/label-studio/tree/master/label_studio/frontend/src 

This task looks not easy, and I would start with the things that your annotators fail to understand in the first place. Is it editor? Or data manager? Or anything else?
