### ISSUE TITLE
Customize fields in quickview

### ISSUE THREAD

**Issue by AlexRoss-WHS** [heartexlabs/label-studio#1354]
As discussed in [this thread](https://label-studio.slack.com/archives/CQ8LYPPJS/p1629805782143600), it would be good to be able to configure the shown fields in quickview. This used to be possible in older versions. It can still be achived with the api but a dropdown menu, like in the explore-page is missing.

**Comment by johann-petrak** [comment]
That screenshot looks like a browser-only patch, which is not an option with  annotators who are not developers :) 
Would there be a patch directly in the frontend code to achieve the same and could you point out the proper file/location?

**Comment by makseq** [comment]
No, you have to call PATCH /api/views?.... only once on your admin side.

**Comment by makseq** [comment]
Since 1.4.1 you can customize columns in UI.
