### ISSUE TITLE
Filters of separate tabs changing each other

### ISSUE THREAD

**Issue by AlexRoss-WHS** [heartexlabs/label-studio#1357]
**Describe the bug**
When using filters of the same type in multiple tabs of the same project, they affect each other. Changing one filter also changes filters of the same type in other tabs.

**To Reproduce**
1. Go to datamanager
2. Create two tabs
3. Apply a filter to the first tab (e.g. Completed is empty no)
4. Apply filter of same type but different value to other tab (e.g. Completed is empty yes)
5. Switch between tabs a few times

**Expected behavior**
Filters in different tabs should be independent

**Screenshots**

https://user-images.githubusercontent.com/87806894/130771913-0caa2d72-5df9-4184-b456-0266ee2fdc4a.mp4

**Environment (please complete the following information):**
 - OS: LS hosted on Linux and accessed on Windows
 - Label Studio Version 1.2

**Comment by nicholasrq** [comment]
this issue was recently fixed in DM repo, expect a fix to be shipped with the upcoming release
