### ISSUE TITLE
A bug related to audio labeling

### ISSUE THREAD

**Issue by Morgana025** [heartexlabs/label-studio#1358]
**Describe the bug**
When labeling an audio track, the audio pointer does not move where my mouse pointer is but always starts from the beginning. Therefore, it becomes impossible to reproduce only an already labeled region or to listen to a part of the waveform in the middle.

**To Reproduce**
1. Go to 'labeling'
2. Click on waveform
3. See error that the audio playing pointer does not move to the position of my mouse pointer

**Screenshot**

https://user-images.githubusercontent.com/57755529/130823596-839b1619-174a-4f14-82e6-917357f53f9a.mp4

**Expected behavior**
The audio playing pointer moves to the position of my mouse pointer.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Label Studio Version 1.2
 - Python: 3.8.6

**Additional context**
This problem does not exist in the ’interface preview‘ in the ‘Setup’, but it will appear when labeling.

This issue was also mentioned here: #306 and #825

**Comment by makseq** [comment]
@Morgana025 Do you use Local Storages? If yes, try this PR please: https://github.com/heartexlabs/label-studio/pull/1345

**Comment by makseq** [comment]
>  Is there a method to display only one channel for stereo audio?

unfortunately, there is no such method.

**Comment by Morgana025** [comment]
@makseq Thanks for the answers.
I tried both with Local Storage and "direct" import. In the end, what seems to work for me, is to use direct import and mono-waveforms.

**Comment by Morgana025** [comment]
Today, I see this issue too:

"A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown."

I'm not very lucky!

**Comment by Morgana025** [comment]
Little update: The solution for my last problem was to change the browser from Chrome to Firefox

**Comment by makseq** [comment]
Yes, it looks like a browser specific thing.
