### ISSUE TITLE
Reload UI for each task

### ISSUE THREAD

**Issue by DakarXY** [heartexlabs/label-studio#137]
Hi. Your project is awesome. 
Is there any possibility to reload labels for each task? I tried to edit label_config_line in server.py reload_config. But for new labels needed to refresh page. Maybe, you can help me?

**Comment by shevchenkonik** [comment]
@DakarXY 

Hi! What do you mean by config update? Currently, we have one bundle of frontend part to explore mode and react app doesn't update configuration in this mode.

@deppp, do you think this feature will be in future minor versions?

**Comment by DakarXY** [comment]
Yeah. Now it doesn't. It update only task module. 
But, maybe, you can give some advice, how i can rewrite index.js and index.html (maybe so appstore.js, production.js) to get this feature. Needed different labels/choices for different tasks but in SPA. Now i get it worked, but only with page update after new task loading...

**Comment by makseq** [comment]
@DakarXY What way do you add labels to config?

**Comment by deppp** [comment]
@DakarXY There is a way to support that if the number of labels is the same each time, you can use a variable inside the tag's value, here is an example of the config:

```html
<View> 
  <Labels name="lbl" toName="txt">
    <Label value="$val1" />
    <Label value="$val2" />
  </Labels>
  <Text name="txt" value="$text" />
</View>
```

Task data should inlcude *text*, *val1*, *val2* fields, something like this:

```json
{ "text": "Text to be labeled", "val1": "Label value 1", "val2": "Label value 2" }
```

I've not tested the above, though, will do so later this week.
