### ISSUE TITLE
Json fields missing when annotating on Windows [custom fields for quickview]

### ISSUE THREAD

**Issue by royschwartz2** [heartexlabs/label-studio#1387]
**Describe the bug**
Label Studio allows the import of a JSON file for creating tasks with specific fields. This is a great feature that allowed us to create custom behaviour that fits our unique dataset. However, when a task is clicked and the image shown, you'd expect to see the fields on the left, like in the attached screen capture. 

<img width="762" alt="bug report 2" src="https://user-images.githubusercontent.com/51368065/131631650-c98e1e00-6efa-436f-9195-4236a0b1e9c9.png">

However, this seems to work fine in Mac. On the Windows version, the fields don't exist in this view (they do on the general view, without clicking an image for annotation). Apologies for the lower quality screen capture, as for the Windows machine I had to use my phone to capture the screen:

![IMG_6772](https://user-images.githubusercontent.com/51368065/131631171-901b378b-820f-4064-9fc2-621b078e8a25.jpg)
![IMG_6771](https://user-images.githubusercontent.com/51368065/131631196-d6dc909c-f2f4-46a7-a45a-ecf82d4e54d3.jpg)

**To Reproduce**
1. Import tasks using a JSON file to include custom fields
2. Click on a task to get to a view of the image to annotate

**Expected behavior**
All fields should appear in both the main view and the task view. We are working with 3D medical imaging data, and the ability to scroll between sequential images is key to correct annotation. Some of our annotators are working on a Windows environment, so are experiencing this bug. 

**Screenshots**
See above

**Environment (please complete the following information):**
 - OS: Windows
 - Label Studio Version 1.2

**Additional context**

**Comment by makseq** [comment]
@royschwartz2 Looks like you are using a previous version of LS on mac, where the custom fields for quickview were available. We dropped custom fields by mistake in the latest versions. 
We have an issue about it here: https://github.com/heartexlabs/label-studio/issues/1354

**Comment by royschwartz2** [comment]
I actually suspected that, since I first installed the latest version on Windows and the Mac version was earlier. I then checked it by updating the Mac version to 1.2 and, believe it or not, they're still there...

Will await for the fix for Windows. Thanks!

**Comment by makseq** [comment]
We've added a special gear icon in the quickview that controls these fields after v1.4.
