### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ReDeiPirati** [heartexlabs/label-studio#139]
**Describe the bug**

This error occurred during the build time and cannot be dismissed.
```
./src/examples/image_bbox/index.js
Module not found: Can't resolve './completions/1.json' in '/Users/pirate/Developer/label-studio/src/examples/image_bbox'
```
**To Reproduce**

```bash
git clone https://github.com/heartexlabs/label-studio
npm install .
npm run start
```

**Expected behavior**
Loading the app.

**How to fix it**
It looks like that in [the latest commit the `1.json` file has been removed](https://github.com/heartexlabs/label-studio/commit/9c8651fd76ebb2e01bbc99eacc2997071ca0febd#diff-aa0311bdd290b0b0acfe06eaec3e3315). Adding it back, fix the issue. 
I didn't open any PR because I was not sure if it was intentional for a code refactoring or just overlooked.

**Comment by shevchenkonik** [comment]
@ReDeiPirati hey, thank you! Yeap, this one looks like an overlooked.

**Comment by shevchenkonik** [comment]
@makseq need to return the directory `completions` with the file `1.json`. Every tag needed 1 completion to development env.

**Comment by shevchenkonik** [comment]
@makseq This one is a mistake in your git flow because in a global branch (master) you don't have to send a commit, but you need PR with CI.

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio/pull/140

@ReDeiPirati Try it now, I hope I fixed it :)

**Comment by ReDeiPirati** [comment]
Hi @shevchenkonik & @makseq,

Yes, it's fixed. Thanks!
