### ISSUE TITLE
Multiple ML models in single project

### ISSUE THREAD

**Issue by pyturn** [heartexlabs/label-studio#1400]
Hi All, 
As per my project I have to setup multiple ML backends in single project. I have to setup 2 models for NER models and 2 models for Text classification task. I made the changes in the labelling interface to accomodate these multiple tasks. When I am trying to setup the ML backend I faced the following issue - 

**NER Model 1** - Backend was created and server started at `http://10.29.85.3:9090/`. But when I created the backend for NER model 2 (on different terminal) , it again started at  `http://10.29.85.3:9090/`, Means it has overwritten the previous backend. 

Please Let me know how to change the port. I am not using the docker as installing docker is not allowed in my system.

**Comment by KonstantinKorotaev** [comment]
Hi,
You can do that by editing your uwsgi.ini.
Check this line and change port:  
`socket = 0.0.0.0:9090`

**Comment by pyturn** [comment]
Thanks, I was able to do it by using following command while starting the server for other models (Port address can be changed) - 
`label-studio-ml start my_backend --port=9091`
