### ISSUE TITLE
Use regex module instead of re module

### ISSUE THREAD

**Issue by lluissalord** [heartexlabs/label-studio#1408]
**Is your feature request related to a problem? Please describe.**
On Python there are two modules which offers the possibility to use regular expressions `re` (the standard one) and `regex` (improved version which handles better Unicode and several other additional features).

One example that I found interesting is when you want to filter by punctuations which with `regex` module is simple as using `\p{P}` while with `re` module you have to list all the punctuations that come to your mind. This is only one example, but probably there are plenty of them which are better handled with `regex` module.

**Describe the solution you'd like**
In order to migrate from one module to another it would be as easy as replace all `import re` by `import regex as re`

**Describe alternatives you've considered**
Alternatives to that are using complex regex patterns for some searches which could be easier to do with `regex` module

**Additional context**
Here is the link to the PyPI module of `regex` which explains some of the benefits: https://pypi.org/project/regex/

**Comment by makseq** [comment]
Do you use regex in filters? If yes, there is DB regex module and we can't just use another import, it has to be changed on DB level somehow.

**Comment by lluissalord** [comment]
Yes I was meaning for regex in filters

**Comment by makseq** [comment]
Sorry, but I'm not sure we can fix this because it's a DB engine question.
