### ISSUE TITLE
Can't highlight words ending with a . and newline

### ISSUE THREAD

**Issue by swartchris8** [heartexlabs/label-studio#1411]
**Describe the bug**
Can't highlight words ending with a . and newline - could be just highlighting can't end with word with new line

**To Reproduce**
1. example = """Pricing ends -- EBM
Yeah, yeah. But don't understand why that would cause an issue because any way sending out thousands of emails a day well into the hundreds of thousands a month… what would be the ways? And then you wouldn't want to sending that quantity through your platform?
KYLE -- As I mentioned, it has to do with domain health.
Call Setup
"""

2. Try highlighting a segmen "As I mentioned, it has to do with domain health.."
3. Fail

**Expected behavior**
Expected to highlight even with dots and newlines.

**Screenshots**

https://user-images.githubusercontent.com/3592919/132231491-f8d0d0a4-88dc-47eb-a75e-2f7f379e8458.mp4

**Environment (please complete the following information):**
 - OS: Ubuntu
 - label-studio==1.2
 - Python 3.8.9

**Comment by makseq** [comment]
@swartchris8 Thank you for your report, especially for the video. We will discuss it with our frontend team.

**Comment by swartchris8** [comment]
If I had any frontend chops I would try to help with a PR or more of a contribution sadly this is all I can do with such an issue

**Comment by hlomzik** [comment]
Hi! Can you check [current LSF master](https://github.com/heartexlabs/label-studio-frontend/commit/b45a0cbf925d9d1b86d5e916ff4b4e3fd940ce92) directly or [with your LabelStudio](https://labelstud.io/guide/frontend.html#Custom-LSF-LSB-integration)?
I can't reproduce this bug
