### ISSUE TITLE
Recommendations for OCR labeling task

### ISSUE THREAD

**Issue by ReDeiPirati** [heartexlabs/label-studio#142]
Hi label-studio team & community,

I'm actually labeling some data for an OCR pipeline made of 3 tasks:

1. Text Detection
2. Text Recognition
3. NER/Text Classification

Ideally, it would be great to do everything in a single shot but I'm facing some seatbacks. Let me give you more context.

I'm using the object detection template and adding a label to classify/tag the text inside the bbox, in this way I'm able to accomplish steps 1 & 3.  To solve step 2, I tried this workaround: after the creation of a new Entity, I added the `Normalization` field with the text inside the bbox. Unfortunately, this is suboptimal because it's not possible to edit this field from the UI, and if I update the task in a second time, all the previous completed Normalization fields are deleted.

I can certainly split the tasks and adopt [the solution mentioned here](https://github.com/heartexlabs/label-studio/issues/27#issuecomment-522414777) for task 2, but it will make the workflow a bit more cumbersome.

I was wondering if you have any other recommendations for this type of OCR workflow.

**Comment by deppp** [comment]
Hey @ReDeiPirati,

Might one solution be to include a textarea? You can also use relations if you want to connect a particular bbox region to a specific textarea input. Can something like the following work?

```html
<View>
  <Header value="Put bbox around the text" />
  <RectangleLabels name="lbl" toName="img">
    <Label value="Label 1" />
    <Label value="Label 2" />
  </RectangleLabels>
  <Image name="img" value="$img" />
  <Header value="Transcribe each bbox" />
  <TextArea name="txt" />
</View>
```

Also, if you've planning to connect the ML model to help you annotate your dataset faster, it'd be easier to split this up into multiple projects. If you want to go that way depends on your use-case of course as well as the size of your dataset. Hope that helps!

**Comment by ReDeiPirati** [comment]
Hi @deppp,

> You can also use relations if you want to connect a particular bbox region to a specific textarea input. Can something like the following work?

I've tried your solution, but it doesn't seem to work. The textarea is not linked to any particular bbox and I need a text area for each bbox I'll create. With relations I'm only able to connect two bounding boxes, but not the text area. Not to mention that the IDs of the relations seem to be wrong (not the same IDs of the bboxes that I want to relate).

> Also, if you've planning to connect the ML model to help you annotate your dataset faster, it'd be easier to split this up into multiple projects.

Yes, I'm considering to connect a pretrained CTPN model later to help me in this process. Now, I'm focusing my attention to create the data labeling guide.

**Comment by deppp** [comment]
@ReDeiPirati I've just checked, and you're right. Relations were not that well checked on the latest releases. I'll fix that and push with the next release and update you on that. Stay tuned

**Comment by deppp** [comment]
@ReDeiPirati This is fixed now, please check the latest release.

In general, I think OCR type of tasks can be improved in terms of UI, but I've not found anything that works well really to get inspiration from. If you have any pointers or ideas on how the workflow can be improved, please let me know.

Best, Micahel
