### ISSUE TITLE
Export completions incomplete

### ISSUE THREAD

**Issue by JisongXie** [heartexlabs/label-studio#1437]
**Describe the bug**
I use LabelStudio for a text classification task, with 3 class. 
1. The page shows that there are 1964 tasks, while there are 1972 completions.
2. When I export the result in csv format or in json format, there are only 1868 completions，and 9 label are NaN, which is not my preset label.

I go into the docker container, and see that there are 1964 items in the generated `source.json`, while there are only 1868 items in the generated `completions` directory. It seems that something has been missing.

**To Reproduce**
I use config.json to make some configs for label studio service. All labeling tasks are described in tasks.json. And then I run `docker-compose up` to start the service. I limit the memory 8G, and set `restarts` always.

---
The page shows that there are 1964 tasks, while there are 1972 completions.
![image](https://user-images.githubusercontent.com/28192557/133063066-69d859f8-83be-4d44-bc33-52e3e43ce4e3.png)

---
I don't set any filters.
![image](https://user-images.githubusercontent.com/28192557/133063164-b3ecbe16-ba1b-4149-9074-0fb6deec7726.png)

---

**Environment (please complete the following information):**
 - OS: Linux debian 4.9.0-3-amd64
 - docker image: heartexlabs/label-studio:latest, 482d577e4e96
 - docker-compose version: docker-compose version 1.23.2

**Comment by makseq** [comment]
@JisongXie It means you have more than one completion per tasks most likely.

**Comment by makseq** [comment]
It looks like you are using very old version of Label Studio, the latest version is 1.2 and the commit is fb66049089c82636a831034876fb9adf75ecafab.

**Comment by JisongXie** [comment]
@makseq thanks, I take a try with the latest version.

**Comment by makseq** [comment]
Hope the latest LS version fixed this issue.
