### ISSUE TITLE
Label all tasks not working

### ISSUE THREAD

**Issue by arpitkjain10** [heartexlabs/label-studio#1449]
**Describe the bug**
When trying to start labelling all tasks, the screen freezes on loader and next screen is not visible.
Running Label Studio on Cloud Run. Images synced from GCS storage bucket.

**To Reproduce**
1. Run Label Studio on cloud run
2. Create a project and attach GCS bucket.
3. Sync data into Label studio and configure labelling setup.
4. Click on Label all task and screen freezes

**Expected behavior**
Labelling setup screen to be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/41476970/133377319-f1f8726d-dd82-49c6-a5bf-4fbf6b507f78.png)

**Environment (please complete the following information):**
 - GCP Cloud Run
 - Label Studio Version 1.2

**Additional context**

**Comment by makseq** [comment]
@arpitkjain10 could you show LS server logs please? 403 is not used to our codes, probably it happens on your proxy side.

**Comment by arpitkjain10** [comment]
![image](https://user-images.githubusercontent.com/60604406/133574188-9a69dd23-1d6a-4699-a7e4-32eb7a0144c5.png)
Logs from Cloud Run instance.
Note: I am using OOB setup of Label Studio on GCP Cloud Run Instance

**Comment by makseq** [comment]
What is your LS version? Could you upgrade to the latest from the master branch?

**Comment by arpitkjain10** [comment]
using Label Studio Version 1.2

**Comment by makseq** [comment]
@arpitkjain10 Could you switch to the latest master branch? Or wait a little and we will release LS 1.3, I think there won't be this bug.

**Comment by arpitkjain10** [comment]
@makseq Thanks for the feedback. We are using the latest master branch.
Would wait for the new release and test it out.
Is there any timeline for LS 1.3 that you can share?

**Comment by makseq** [comment]
@arpitkjain10 LS 1.3 is already released!

**Comment by arpitkjain10** [comment]
@makseq Thanks for the update. The issue was resolved when using 1.3 release.
Appreciate your constant support on this.
Closing the issue.
