### ISSUE TITLE
Multiple tasks in the same page

### ISSUE THREAD

**Issue by fakyras** [heartexlabs/label-studio#145]
First of all - I found this project to be the best tool out there when it comes to open source, thank you for that!

I am trying to customize it to my needs, but I think it is worth having this idea out there. The task I have at hand actually involves simultaneous labeling of text (named entity type), text sentiment analysis (annotator to give a quality metric of the provided text) and image polygon annotation (given information in text provide polygons on the image). These 3 elements should be displayed on the same screen for annotator's convenience.

I think I am no the only one who is dealing with multi-labeling this way. I am not asking this to be a core feature of this project, but it might be worth having in mind that this possible design can be useful.

**Comment by deppp** [comment]
Hi @fakyras, thanks for the kind words. More is coming before the end of the year!

To your use-case, I think that can be supported out of the box right away? Something like that:

```html
<View>  
  <Header value="Label the text" />
  <Labels name="labels" toName="txt">
    <Label value="Label 1" />
    <Label value="Label 2" />
  </Labels>
  <Text name="txt" value="$text" />
  <Header value="Qualify the text above" />
  <Choices name="sentiment" toName="txt">
    <Choice value="Choice 1" />
    <Choice value="Choice 2" />
  </Choices>
  <Header value="Provide the Polygons" />
  <Polygon name="poly" toName="img" pointSize="small" pointStyle="circle"></Polygon>
  <Image name="img" value="$image" />
</View>
```

You can try it out here https://labelstud.io/playground/

Please let me know if that's what you were thinking about.

**Comment by fakyras** [comment]
@deppp Wow. this just solved all my issues! Really really thank you!
With such easy customization, in my eyes it is already a production ready annotation tool.

**Comment by deppp** [comment]
@fakyras Glad to hear that! 

Well, the open-source version is still a bit edgy in terms of setup, we've open-sourced it not that long ago from our commercial solution. But I expect it to be more polished in the next couple of months! Also, if you have more questions, feel free to join a slack channel.

Best, Michael
