### ISSUE TITLE
typo: selelectWithoutLabel

### ISSUE THREAD

**Issue by kgeis** [heartexlabs/label-studio#146]
**Describe the bug**
The text tag has a parameter `selelectWithoutLabel`. It should be `selectWithoutLabel`. I am hesitant to offer a pull request because a change could break users' existing solutions. A deprecation strategy is suggested, and I'm not sure how to do that with your code.

**To Reproduce**
1. Visit https://labelstud.io/tags/text.html
2. See spelling

**Expected behavior**
The label should be `selectWithoutLabel`.

**Comment by shevchenkonik** [comment]
@kgeis Hi! I'm not sure about default state is _withoutLabel_. 

The main reasons:
1. The logic for all tags should be the same for future HOC.
2. The main task of markup data is to separate different labels & entities.

But I think it's a good idea to create more concise names of parameters for tags. For example change `selectWithoutLabel` to `emptyLabel` (or similar).

**Comment by kgeis** [comment]
@shevchenkonik, I don't understand your comment. I'm just saying that the parameter name has an extra "le" in it. Maybe this makes it more clear: `se<le>lectWithoutLabel`

**Comment by shevchenkonik** [comment]
@kgeis haha I did not notice typos :)

Yes, you are right about deprecation strategy and in the the current version we can leave a `selelectWithoutLabel` and add new one as `selectWithoutLabel` (and add TODO comment):

```javascript
/** TODO */
if (!self.selelectwithoutlabel || !self.selectwithoutlabel) /** ... */;
```

In the next major release, we will update the logic of this tag and will add major release note.

**Comment by deppp** [comment]
@kgeis Thanks for reporting. That was fixed in the latest release
