### ISSUE TITLE
Typo in Callbacks Example Snippet

### ISSUE THREAD

**Issue by cicero19** [heartexlabs/label-studio#147]
onSubmitCompletion: function(result) {
  console.log(result)
}

Should be:

submitCompletion: function(result) {
  console.log(result)
}

**Comment by shevchenkonik** [comment]
@cicero19 what you mean? First of all external functions in the draft & we have `submitCompletion` (https://github.com/heartexlabs/label-studio/blob/master/src/core/External.js#L4)

**Comment by shevchenkonik** [comment]
@cicero19 I close this issue. If you want to create a new functionality then you can create PR from the master branch. Thank you!

**Comment by deppp** [comment]
@cicero19 I see what you mean. I think the website got updated a little bit earlier than the branch got merged in. That's going to be fixed today.
