### ISSUE TITLE
Export of Object Detection Annotations (COCO) ignores images with null annotations

### ISSUE THREAD

**Issue by kielnino** [heartexlabs/label-studio#1470]
**Describe the bug**
In my Object-Detection problem, there are also images with no objects visible. So in label-studio I just clicked "Submit" without annotating any regions on these images. But these images are erroneously omitted in the `images`-block in the export in COCO-format:

**To Reproduce**
1. Set up an object detection project (Object detection with bounding boxes)
2. Click "Submit" on the first task without annotating anything
3. Click Export and choose COCO
4. The json file will have no images listed

```json
{
  "images": [],
  "categories": [
    {
      "id": 0,
      "name": "Airplane"
    },
    {
      "id": 1,
      "name": "Car"
    }
  ],
  "annotations": [],
  "info": {
    "year": 2021,
    "version": "1.0",
    "contributor": "Label Studio"
  }
}
```

**Expected behavior**
I would expect to have the images listed in the annotation-file but without any corresponding entry in the `annotations`-block. (See also https://blog.roboflow.com/missing-and-null-image-annotations/)

**Environment (please complete the following information):**
 - OS: Ubuntu / docker
 - Label Studio Version 1.2

**Comment by makseq** [comment]
@kielnino We are planning to drop image downloading for export, because it's 
* not secure (in theory LS should not access images/audio/media from outside resources)
* slow
* difficult to implement 
? 
As alternative you could copy your images manually to `images` folder. Is it ok for you?

**Comment by kielnino** [comment]
@makseq Thank you for the quick response. However, I didn't mean the images themselves, but their listing in the annotation file. Please apologize for the misunderstanding.

If I want to annotate an empty image (for example only the background), the image should be included in the training data as usual, but just without annotation.

This would mean in COCO data format that the image is listed in the `images`-block of the JSON file, but there is no associated entry in the `annotations`-block (see also the link in my first comment).

**Comment by makseq** [comment]
@kielnino https://github.com/heartexlabs/label-studio-converter/pull/57 could you check this PR, does it solve your problem?

**Comment by lfeldb** [comment]
@makseq 

When dropping the image download support, how would you like to deal with uploaded images?
One could argue that you've already got the images when uploading, however what if a colleague uploads images; or what if images are uploaded twice and renamed by label-studio? (I'm afraid of losing referential integrity)

The coco export solves this.

**Comment by makseq** [comment]
@lfeldb Thanks for this idea, yes, for LS uploaded files it's make sense. 
For storages I'd prefer to download files by myself, because it will be faster and maybe I have a direct storage access.

**Comment by kielnino** [comment]
Probably related to #921

**Comment by kemics** [comment]
Hey everyone, do you have any estimations about bug being fixed? This problem blocks training of object detector in production

**Comment by makseq** [comment]
@kemics Hey, is your problem about ignored null annotations? Could you try this PR - [label-studio-convert PR ](https://github.com/heartexlabs/label-studio-converter/pull/47/files) ?

**Comment by kemics** [comment]
@makseq hey

>is your problem about ignored null annotations?

Yes

>Could you try this PR - label-studio-convert PR ?

Do you mean to test how it works? Or to use it in production?

I wish the bug would be prioritized because this quite common situation to have images with no bounding boxes for object detection training. I came up with workaround on client size, but it is not convenient and slow when number of images is big

**Comment by ALIYoussef** [comment]
I am facing the same issue! and null annotations is not resulting in the exported coco json format (semantic segmentation task)!
Not sure how to use the label-studio-converter! Any suggestion?

**Comment by KonstantinKorotaev** [comment]
@ALIYoussef Could you please check if fix from [57](https://github.com/heartexlabs/label-studio-converter/pull/57) resolves your issue?

**Comment by kielnino** [comment]
@KonstantinKorotaev I've just pulled the latest official label-studio docker container and installed label-studio-converter from the mentioned pull-request (https://github.com/heartexlabs/label-studio-converter/tree/fix/gh1470-coco-images).

With the given steps to reproduced from the initial description of this issue, I still get only the images, where bounding boxes were drawn and not the images without any annotations.

**Comment by ALIYoussef** [comment]
> @ALIYoussef Could you please check if fix from [57](https://github.com/heartexlabs/label-studio-converter/pull/57) resolves your issue?

Thank you for reply.
Using the app and trying the to export annotations is still missing the null annotations images. 
Do I have to pull from a specific branch or directly from the master?

**Comment by KonstantinKorotaev** [comment]
@ALIYoussef 
Could you please install label-studio-converter 0.0.39.dev0 to your environment and check again?

**Comment by kemics** [comment]
@KonstantinKorotaev @makseq sorry, why this issue isn't getting prioritized or at least scheduled? Looks like a major bug and it's 6 month old

**Comment by makseq** [comment]
@kemics https://github.com/heartexlabs/label-studio-converter/ try to use the last commit from the master branch, this issue is fixed there. If you want to have width / height for all images including the images with lacking annotations, you have to call the `api/project/<id>/export?export_type=COCO&download_resources=true` manually.

**Comment by ALIYoussef** [comment]
@makseq  I tried it with version label-studio-converter==0.0.40. It works but not directly from the app (export COCO).
I had to launch the command api/project/<id>/export?export_type=COCO&download_resources=true&download_all_tasks=true.
P.S. the last release 1.4.1 of label studio still using the version 0.0.39 of converter. So, you need to checkout on the develop branch.
Thank you for help!

**Comment by owidler** [comment]
I have the same issue with YOLO export. Could you fix this as well, as its a very important feature. Thanks!

**Comment by KonstantinKorotaev** [comment]
@owidler what version of label studio do you use?

**Comment by makseq** [comment]
@owidler could you check LS 1.5.0 ?

**Comment by hellkrusher** [comment]
Image export is a very important feature for me as well. Roboflow has this feature and it makes it very easy to train in different environments. Currently I'm being forced to use the easy export endpoint: {LABEL_STUDIO_API_URL}/api/projects/{LABEL_STUDIO_PROJECT_ID}/export?exportType=YOLO&download_resources=true&download_all_tasks=false
