### ISSUE TITLE
import data is comfusing?

### ISSUE THREAD

**Issue by lixiepeng** [heartexlabs/label-studio#1483]
1. Does label-studio support json line format?
2. For LocalFilesImportStorage your JSON file must be a dictionary with one task. Does it mean each data with a json file?

**Comment by makseq** [comment]
@lixiepeng 
1. No, LS doesn't yet support json line. 
2. Yes, for all storages LS allows to use only one json per task.

**Comment by leomaurodesenv** [comment]
Thank you @makseq , it worked. Anyway, it is weird as @XiepengLi mentioned. heheh
