### ISSUE TITLE
Update Pydantic requirements

### ISSUE THREAD

**Issue by Ierezell** [heartexlabs/label-studio#1534]
**Describe the bug**
As I also have spacy in my project, which depends on `pydantic>=1.7.4`

Increasing the requirements would fix the problem. 

**Expected behavior**
Be able to install spacy and label-studio

**Other solutions**
Use Docker or launch label-studio from another folder

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Label Studio Version [e.g. 0.8.0] 1.3.post0

Thanks for the tool !
And thanks in advance for this request

Have  a great day

**Comment by makseq** [comment]
Please, check this PR: https://github.com/heartexlabs/label-studio/pull/1535/files

**Comment by Ierezell** [comment]
Thanks a lot for the fast support!
