### ISSUE TITLE
The template does not work.

### ISSUE THREAD

**Issue by fairy-of-9** [heartexlabs/label-studio#1539]
**Describe the bug**
I try [this](https://labelstud.io/playground/?config=%3C!--Labeling%20configuration%20to%20label%20paragraph%20regions%20of%20text%20containing%20dialogue--%3E%3Cbr%3E%3CView%3E%3Cbr%3E%20%20%3CParagraphs%20name%3D%22dialogue-1%22%20value%3D%22%24dialogue%22%20layout%3D%22dialogue%22%20%2F%3E%3Cbr%3E%20%20%3CParagraphLabels%20name%3D%22importance%22%20toName%3D%22dialogue-1%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Important%20content%22%3E%3C%2FLabel%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Random%20talk%22%3E%3C%2FLabel%3E%3Cbr%3E%20%20%3C%2FParagraphLabels%3E%3Cbr%3E%3C%2FView%3E) template.
But, It doesn't work.

**To Reproduce**
1. Create New project
2. import json data
```
{
    "dialogue": [
        {
            "author": "Mia Wallace:",
            "text": "Dont you hate that?"
        },
        {
            "author": "Vincent Vega:",
            "text": "Hate what?"
        },
        {
            "author": "Mia Wallace:",
            "text": "Uncomfortable silences. Why do we feel its necessary to yak about bullshit in order to be comfortable?"
        },
        {
            "author": "Vincent Vega:",
            "text": "I dont know. That is a good question."
        }
    ]
}
```

3. Set Labeling interface
```
<!--Labeling configuration to label paragraph regions of text containing dialogue-->
  <View>
    <Paragraphs name="dialogue-1" value="$dialogue" layout="dialogue"/>
    <ParagraphLabels name="importance" toName="dialogue-1">
      <Label value="Important content"/>
      <Label value="Random talk"/>
    </ParagraphLabels>
  </View>
```

```
Task data (provided as $dialogue) has wrong format.
It should be an array of objects with fields, defined by nameKey ("author" by default) and textKey ("text" by default)
Provided data is not an array
```

**Expected behavior**
I expected to act like the output of the template.

**Screenshots**
![image](https://user-images.githubusercontent.com/37280914/135055941-e6c53404-3898-47e9-8d0f-a7fe4ac1bcb7.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-42-generic x86_64)
 - Label Studio Version: 1.3.post0
 - use conda

**Comment by makseq** [comment]
@fairy-of-9 Please, check the latest LS version from master, we fixed this bug recently. 

![image](https://user-images.githubusercontent.com/501780/135338828-0d01d0fe-d20b-4eb5-ae2c-fd34f6b9c224.png)

**Comment by makseq** [comment]
@liebkne Do you have any examples of what you want to have at final?

**Comment by liebkne** [comment]
@makseq Hi, I'd like combine [this example](https://labelstud.io/playground/?config=%3C!--Labeling%20configuration%20to%20label%20paragraph%20regions%20of%20text%20containing%20dialogue--%3E%3Cbr%3E%3CView%3E%3Cbr%3E%20%20%3CParagraphs%20name=%22dialogue-1%22%20value=%22$dialogue%22%20layout=%22dialogue%22%20/%3E%3Cbr%3E%20%20%3CParagraphLabels%20name=%22importance%22%20toName=%22dialogue-1%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value=%22Important%20content%22%3E%3C/Label%3E%3Cbr%3E%20%20%20%20%3CLabel%20value=%22Random%20talk%22%3E%3C/Label%3E%3Cbr%3E%20%20%3C/ParagraphLabels%3E%3Cbr%3E%3C/View%3E) and something *like* [this](https://labelstud.io/playground/?config=%3C!--Labeling%20configuration%20to%20label%20paragraph%20regions%20of%20text%20containing%20dialogue--%3E%3Cbr%3E%3CView%3E%3Cbr%3E%20%20%3CParagraphs%20name=%22dialogue-1%22%20value=%22$dialogue%22%20layout=%22dialogue%22%20/%3E%3Cbr%3E%20%20%3CParagraphLabels%20name=%22importance%22%20toName=%22dialogue-1%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value=%22Important%20content%22%3E%3C/Label%3E%3Cbr%3E%20%20%20%20%3CLabel%20value=%22Random%20talk%22%3E%3C/Label%3E%3Cbr%3E%20%20%3C/ParagraphLabels%3E%3Cbr%3E%3C/View%3E) but assign a label **for each** utterance instead of for the whole conversation. The output may look like their combination.

**Comment by jdonnell01** [comment]
I am also having issues with the Intent Classification and Slot Filling template. I am on version 1.4 of LabelStudio. I do not see this issue marked against any commits in master: https://github.com/heartexlabs/label-studio/commits/master?after=882547631c14000570ca3793a82f0ed65e8a743f+349&branch=master. Can you please point me to the fix? Thank you

**Comment by nikhbikh** [comment]
Also experiencing the same issue. Running from the top of `develop` @ `061bf559`

**Comment by hlomzik** [comment]
@nikhbikh can you describe this issue? original issue was about sample task for `Paragraphs` tag, and it works all this time, just checked right now to be sure.

**Comment by lpozzan** [comment]
Hello! I am working with the same template and getting the same error that was originally reported. I would appreciate any help with getting this template working again!

**Comment by makseq** [comment]
Start a new project in LS 1.7 and use this labeling config:

```
<View>
  <Paragraphs name="dialogue" value="$humanMachineDialogue" layout="dialogue"/>
  <Header value="CSAT"/>
    <Choices name="resp1" toName="dialogue" required="true">
      <Choice value="very satisfied"/>
      <Choice value="somewhat satisfied"/>
      <Choice value="not satisfied or dissatisfied"/>
      <Choice value="somewhat dissatisfied"/>
      <Choice value="very dissatisfied"/>
    </Choices>
  <Header value="Customer Sentiment"/>
    <Choices name="resp2" toName="dialogue" required="true">
      <Choice value="positive"/>
      <Choice value="neutral"/>
      <Choice value="negative"/>
     </Choices>
  <Header value="Call Resolution"/>
    <Choices name="resp3" toName="dialogue" required="true">
      <Choice value="resolved"/>
      <Choice value="not resolved"/>
      <Choice value="unknown"/>
    </Choices>
</View>
```

And this task data:
```
{"data": {
    "humanMachineDialogue": [
        {
            "author": "Mia Wallace:",
            "text": "Dont you hate that?"
        },
        {
            "author": "Vincent Vega:",
            "text": "Hate what?"
        },
        {
            "author": "Mia Wallace:",
            "text": "Uncomfortable silences. Why do we feel its necessary to yak about bullshit in order to be comfortable?"
        },
        {
            "author": "Vincent Vega:",
            "text": "I dont know. That is a good question."
        }
    ]
  }
}
```

**Comment by lpozzan** [comment]
I tried, and still get: "Task data (provided as $humanMachineDialogue) has
wrong format.
It should be an array of objects with fields, defined by nameKey ("author"
by default) and textKey ("text" by default)

   - Provided data is not an array

:( :( :(

**Comment by NithishBA** [comment]
![Screenshot from 2024-02-20 12-48-32](https://github.com/HumanSignal/label-studio/assets/137524649/7643db09-4e78-4903-826f-072442535918)
![Screenshot from 2024-02-20 12-48-32](https://github.com/HumanSignal/label-studio/assets/137524649/3d138f7e-3c57-402a-bb64-232a53de3f84)
how to fix this issue

**Comment by NithishBA** [comment]
![Screenshot from 2024-02-20 12-48-32](https://github.com/HumanSignal/label-studio/assets/137524649/97b7847b-a48c-446e-9663-a28138973826)

<View>
  <ParagraphLabels name="entity_slot" toName="dialogue">
    <Label value="Person"/>
    <Label value="Organization"/>
    <Label value="Location"/>
    <Label value="Datetime"/>
    <Label value="Quantity"/>
  </ParagraphLabels>
  <Paragraphs name="dialogue" value="$undefined$" layout="dialogue"/>
    <Choices name="intent" toName="dialogue" choice="single" showInLine="true">
        <Choice value="Greeting"/>
        <Choice value="Customer request"/>
        <Choice value="Small talk"/>
    </Choices>
</View>
This is conversational AI template . How to fix it .?

**Comment by NithishBA** [comment]
![Screenshot from 2024-02-20 12-48-32](https://github.com/HumanSignal/label-studio/assets/137524649/a7f0bb48-7374-4f16-b8d3-b78d27d71afa)
This is conversational AI template . How to fix it .? Help me  with which type of data should import to that template

**Comment by volkancirik** [comment]
Hello!

We're having similar issues using the cloud storage:

```
<View>
  <Paragraphs name="dialogue" value="$humanMachineDialogue" layout="dialogue"/>
  <Header value="CSAT"/>
    <Choices name="resp1" toName="dialogue" required="true">
      <Choice value="very satisfied"/>
      <Choice value="somewhat satisfied"/>
      <Choice value="not satisfied or dissatisfied"/>
      <Choice value="somewhat dissatisfied"/>
      <Choice value="very dissatisfied"/>
    </Choices>
  <Header value="Customer Sentiment"/>
    <Choices name="resp2" toName="dialogue" required="true">
      <Choice value="positive"/>
      <Choice value="neutral"/>
      <Choice value="negative"/>
     </Choices>
  <Header value="Call Resolution"/>
    <Choices name="resp3" toName="dialogue" required="true">
      <Choice value="resolved"/>
      <Choice value="not resolved"/>
      <Choice value="unknown"/>
    </Choices>
</View>
```

I tried 4 different data types:

v1 (your suggestion @makseq )
```
{"data": {
    "humanMachineDialogue": [
        {
            "author": "Mia Wallace:",
            "text": "Dont you hate that?"
        },
        {
            "author": "Vincent Vega:",
            "text": "Hate what?"
        },
        {
            "author": "Mia Wallace:",
            "text": "Uncomfortable silences. Why do we feel its necessary to yak about bullshit in order to be comfortable?"
        },
        {
            "author": "Vincent Vega:",
            "text": "I dont know. That is a good question."
        }
    ]
  }
}
```

v2
```
 {
    "humanMachineDialogue": [
        {
            "author": "Mia Wallace:",
            "text": "Dont you hate that?"
        },
        {
            "author": "Vincent Vega:",
            "text": "Hate what?"
        },
        {
            "author": "Mia Wallace:",
            "text": "Uncomfortable silences. Why do we feel its necessary to yak about bullshit in order to be comfortable?"
        },
        {
            "author": "Vincent Vega:",
            "text": "I dont know. That is a good question."
        }
    ]
  }
```
v3
```
 [{
    "humanMachineDialogue": [
        {
            "author": "Mia Wallace:",
            "text": "Dont you hate that?"
        },
        {
            "author": "Vincent Vega:",
            "text": "Hate what?"
        },
        {
            "author": "Mia Wallace:",
            "text": "Uncomfortable silences. Why do we feel its necessary to yak about bullshit in order to be comfortable?"
        },
        {
            "author": "Vincent Vega:",
            "text": "I dont know. That is a good question."
        }
    ]
 }]
```

v4
```
  [
        {
            "author": "Mia Wallace:",
            "text": "Dont you hate that?"
        },
        {
            "author": "Vincent Vega:",
            "text": "Hate what?"
        },
        {
            "author": "Mia Wallace:",
            "text": "Uncomfortable silences. Why do we feel its necessary to yak about bullshit in order to be comfortable?"
        },
        {
            "author": "Vincent Vega:",
            "text": "I dont know. That is a good question."
        }
]
```


All gets the same error:

```
Task data (provided as $dialogue) has wrong format.
It should be an array of objects with fields, defined by nameKey ("author" by default) and textKey ("text" by default)
Provided data is not an array
```

**Comment by makseq** [comment]
v1 and v2 are working, I've just checked it. 
v3 is wrong for the Cloud Storage import, because it's array. 
v4 is wrong totally, because it's missing "humanMachineDialogue" dict. 

![image](https://github.com/HumanSignal/label-studio/assets/501780/428007e9-1130-4ebe-bff7-1e9852376de4)

**Comment by makseq** [comment]
There are 3 important points: 
1. For the import in cloud storages only one task per one json file is allowed and it should be stored as dict ({...}), more info: https://docs.humansignal.com/guide/storage#One-Task-One-JSON-File
2. You must have the save key in the labeling config and in the tasks: dialogue
3. Treat every bucket object as a source file = Off, more info: https://docs.humansignal.com/guide/storage#Off
 
 
Your steps to import tasks from a Cloud Storage should be: 
 
1. Create a new project with this labeling config, pay attention to Paragraphs value="$dialogue": 
```
<View style="display: flex;">
  <View style="width: 600px; padding-left: 1em; margin-right: 1em; background: #ffffff; border-radius: 1px">  
  <Paragraphs name="dialogue" value="$dialogue" layout="dialogue"/>
  </View>
    <View style="height: 800px;width: 320px; padding-left: 1em; margin-right: 1em; background: #f1f1f1; border-radius: 2px;; position: sticky; top: 0; border-radius: 2px; z-index:1">
    <Header value="CoachingAI Questions"/>
  <Text name="text1" value="Did the agent follow up to ensure that both parties were satisfied with the outcome and understood the resolution"/>
  <Choices name="q1" toName="dialogue" choice="single">
    <Choice value="Yes"/>
    <Choice value="No"/>
  </Choices>
  <Text name="text2" value="Did the agent maintain an objective and neutral stance when handling the case?"/>
  <Choices name="q2" toName="dialogue" choice="single">
    <Choice value="Yes"/>
    <Choice value="No"/>
  </Choices>
  <Text name="text3" value="Was the agent familiar with JetBlue's policies related to booking, cancellations, refunds, and resolution procedures?"/>
  <Choices name="q3" toName="dialogue" choice="single">
    <Choice value="Yes"/>
    <Choice value="No"/>
  </Choices>
  <Text name="text4" value="Did the agent assess all provided information correctly?"/>
  <Choices name="q4" toName="dialogue" choice="single">
    <Choice value="Yes"/>
    <Choice value="No"/>
  </Choices>          
  </View>
</View>
```
 
2. Save this JSON file to your storage, keep in mind that the key is dialogue:
```
{
        "id": 1,
        "dialogue" :
        [
            {
                "author": "A",
                "text": "Hello"
            },
            {
                "author": "B",
                "text": "Hi"
            },
            {
                "author": "A",
                "text": "How are you?"
            },
            {
                "author": "B",
                "text": "I'm good, how about you?"
            },
            {
                "author": "A",
                "text": "I'm good too"
            },
            {
                "author": "B",
                "text": "That's great"
            },
            {
                "author": "A",
                "text": "Yes"
            }
        ]
}
```
3. Add Cloud Storage with these settings: 
 
4. Sync your storage. 
 
Now you should see the correct task.

**Comment by Lagstill** [comment]
But for valuetype="url" only the v4 data format works, so how to add the annotation data while importing through cloud storage @makseq

**Comment by sifatullahkarwan** [comment]
Hello I can't  import my own data to conversational AI template on  Response Generation and another template

**Comment by sifatullahkarwan** [comment]
when I import the text data it give this open 
![Screenshot from 2024-07-17 14-37-09](https://github.com/user-attachments/assets/ccde05e1-24df-4ef6-a128-81e1e940e5b5)

**Comment by sifatullahkarwan** [comment]
The it doesn't show me the data content
![Uploading Screenshot from 2024-07-17 14-37-40.png…]()
