### ISSUE TITLE
Copy/Duplicate Label

### ISSUE THREAD

**Issue by dsanders11** [heartexlabs/label-studio#1549]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to copy/duplicate a label. For example, I have a task where the different items to label are all the same size, so I'd like to draw the rectangle once, then duplicate it and change the label on the copy, ensuring that all of the rectangles are identical sizes. CVAT has copy functionality as described.

**Describe the solution you'd like**

A way to copy/duplicate a layer. In CVAT it's called copy, but I think duplicate might be a better word since copy might imply you'll then paste it, rather than immediately creating another label.

**Describe alternatives you've considered**

None.

**Comment by makseq** [comment]
@dsanders11 Since LS 1.3 the selection of multiple regions and ctrl+c/ctrl+v hotkeys are available, have you tried them?

**Comment by dsanders11** [comment]
@makseq, looks like Ctrl+D does exactly what I wanted, thanks! Using Ctrl+C and Ctrl+V was buggy for me, sometimes it worked, sometimes it didn't, and I couldn't figure out why, but Ctrl+D always worked. It seems like Ctrl+C/Ctrl+V did nothing for me when I first switch to an image and click an existing label.

I see now that it's mentioned in the docs, but not in the list of hotkeys in Label Studio itself (at least under Settings), and there doesn't appear to be any way to do it without hotkeys. It would be nice if it was part of the UI so that it was better discoverable, and could be used with only a mouse, as I think a mouse-only workflow can be easier at times.

**Comment by makseq** [comment]
Thank you for your points. So, if we add the duplicate button for regions, will your issue be solved?

**Comment by dsanders11** [comment]
I think so, yea.

**Comment by 0x00023** [comment]
@makseq, I have the same issue with ctrl+c/ctrl+v, sometimes it works, sometimes not. Duplicating isn't work for me, cause I want copy labels from one image to another.

**Comment by makseq** [comment]
@0x00023 yes, new outliner panel with regions was introduced in the latest version of LS 1.6.0. And seems it broke ctrl+c / ctrl+v functionality. I've created a ticket about this, we will fix it soon.

**Comment by fitopassit** [comment]
@makseq  it fixed?

**Comment by makseq** [comment]
@fitopassit not yet

**Comment by nicholasrq** [comment]
@fitopassit hey! this issue was fixed in the latest updated to LS and LS Enterprise. for the open source it's already available in the `develop` branch and will be added to the nearest official LS release

**Comment by weeix** [comment]
I tried running the local development version to explore this feature. It works perfectly and significantly lessens my workload! I hope this reaches the official LS release soon. 😄

For those who tried to run the development version but got 404 errors for static files, try running `python label_studio/manage.py collectstatic --no-input` before `python label_studio/manage.py runserver`

**Comment by makseq** [comment]
Yes, it will be in 1.7.2.
