### ISSUE TITLE
[UI/Frontend, v1.3.0] Parent taxonomy checkbox icon remains the same when child item(s) is selected

### ISSUE THREAD

**Issue by davidheryanto** [heartexlabs/label-studio#1553]
**Describe the bug**
In Label Studio 1.0,
- when one of the child taxonomy is selected, the parent taxonomy has (‒)  icon
  ![image](https://user-images.githubusercontent.com/5300554/135556097-e1c098eb-9ef0-42fd-aaf4-868030105c85.png)
- when all the children taxonomy are selected, the parent taxonomy has (🗸) icon and the parent is **automatically selected**
  ![image](https://user-images.githubusercontent.com/5300554/135557247-8aeb60e1-ed1f-4373-b5d9-aa9d7bed11ff.png)

This really helps to see the current choices when reviewing the taxonomy labels as the parent icon is marked differently when the child is selected.

In Label Studio 1.3, the parent checkbox is unchanged if the child / all the child items are selected.

![image](https://user-images.githubusercontent.com/5300554/135556299-a05344be-a617-4a9f-81fb-6c870b304ef3.png)

Also, when all the child items are selected, the parent is not automatically selected. In v1.0.0, the selection is collapsed to just the parent (since all the children are selected)

![image](https://user-images.githubusercontent.com/5300554/135557461-2a8dd98d-70fd-410d-b04a-d5323767fe01.png)

**To Reproduce**

Example labelling interface from https://labelstud.io/tags/taxonomy.html
```
<View>
  <Taxonomy name="media" toName="text">
    <Choice value="Online">
      <Choice value="UGC" />
      <Choice value="Free" />
      <Choice value="Paywall">
        <Choice value="NY Times" />
        <Choice value="The Wall Street Journal" />
      </Choice>
    </Choice>
    <Choice value="Offline" />
  </Taxonomy>
  <Text name="text" value="You'd never believe what he did to the country" />
</View>
```

1. Import any text
2. Select the child taxonomy label e.g "NY Times"
3. The checkbox icon for parent will remain the same.

**Expected behavior**
Parent checkbox should have different icon when the child / all child items are selected.

**Environment (please complete the following information):**
 - Browser: Chrome 94, Firefox 88
 - Label Studio Version 1.0, 1.3

**Comment by hlomzik** [comment]
Hi! That's fixed in our frontend library and will be released soon in LS. It's already available in the master branch.

**Comment by hlomzik** [comment]
Important note: we removed this "select all childs" behaviour because it's useless in taxonomy labeling, so parent node always in indeterminate state ("–") even if all the childs are selected.
