### ISSUE TITLE
Can you use label-studio for visualising text highlights when the spans are already given? 

### ISSUE THREAD

**Issue by joseberlines** [heartexlabs/label-studio#1562]
I have a text string and a data structure that gives me already the NERs of the text as such:

[{name: 'organization', start:56, lenght: 45},
{name: 'person', start:156, lenght: 23},...]

Can I use label-studio to visualize (not to annotate) that particuar document?
It would sufice an HTML output with the label-studio alike highlighting.

**Comment by smoreface** [comment]
@joseberlines I think what you're asking for is covered by Label Studio's ability to visualize predictions. You can follow the example format in this doc to add your NER labels and the text to Label Studio and visualize it.
https://labelstud.io/guide/predictions.html#Import-pre-annotations-for-text
