### ISSUE TITLE
Cannot render web page within labeling interface

### ISSUE THREAD

**Issue by anferico** [heartexlabs/label-studio#1567]
**Describe the bug**
I have a clickable link (a simple <a> tag rendered through a `HyperText` tag) in my labeling interface which fails to render the corresponding web page (value of the "href" attribute of the <a> tag).

In particular, when I click the link, the embedded web browsers tells me that the web page refused to connect.

Please note that I've installed Label Studio using Docker.

**To Reproduce**
1. Start Label Studio using **Docker**
2. Create a new project
2. Upload some dummy data (see below)
3. Click on a task
4. Click the link contained in the task
5. Experience the error I described

**Expected behavior**
The web page pointed to by the link gets displayed correctly.

**Screenshots**
![refused](https://user-images.githubusercontent.com/30210403/135988944-635fc35a-b8ff-4fb6-89a1-45d84b0cfeb3.png)

**Environment (please complete the following information):**
 - OS: KDE Neon 5.22
 - Label Studio Version 1.2.0

**Additional context**
##### Dummy data
```csv
my_text,my_html
"Sample text 1","<a href=""https://www.google.com"">Visit Google</a>"
"Sample text 2","<a href=""https://www.google.com"">Visit Google</a>"
```
##### Labeling interface template
```xml
<View>
  <Text name="text" value="$my_text"/>
  <HyperText name="html" value="$my_html" clickableLinks="true"/>
  <Choices name="sentiment_class" toName="text">
    <Choice value="Positive"/>
    <Choice value="Neutral"/>
    <Choice value="Negative"/>
  </Choices>
</View>
```

**Comment by makseq** [comment]
@anferico This is a CORS issue, the webpage you are trying to use inside HyperText should allow opening in iframes. You have to properly configure your website/nginx/whatever to enable CORS.
