### ISSUE TITLE
Firewall error while connecting FastAPI model as ML Backend

### ISSUE THREAD

**Issue by NileshSuthar** [heartexlabs/label-studio#1573]
**Describe the bug**
I was trying to connect the FastAPI model to Label Studio for using it as an ML backend service. It shows that health failed and suggested checking if it is up (which it is!). Please help me with how to fix this or where can I get more details about the error?

**Environment (please complete the following information):**
 - MacOS
 - Label Studio Version: 1.3.post0
<img width="716" alt="Screenshot 2021-10-05 at 10 30 03 PM" src="https://user-images.githubusercontent.com/23116691/136068900-0aaac75c-4f73-43ff-b345-ca30eea103c0.png">

**Comment by makseq** [comment]
@NileshSuthar You ML backend should be inherited from LabelStudioMLBase (https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/model.py#L30) and implement `/setup` and `/predict` methods according this framework (/blob/master/label_studio_ml/api.py#L41). 

Also please check this docs: https://labelstud.io/guide/ml_create.html

**Comment by NileshSuthar** [comment]
@makseq Is this a new update? I was using FastAPI in the same fashion as above till the last week and it was working fine. Now it's throwing this error. So is it an upgrade?
Also, the FastAPI main file has its own template so does it mean a model without LabelBase inheritance can't be used for prediction?

**Comment by makseq** [comment]
Sorry, but I don't understand what FastAPI you use. It's not our official way to build ML backends. I mentioned here - https://github.com/heartexlabs/label-studio/issues/1573#issuecomment-935040380 - the main points you should do with FastAPI. We could have changed something, but I don’t remember the big breaking changes.

**Comment by KonstantinKorotaev** [comment]
@NileshSuthar Could you please provide logs from your FastAPI backend?
