### ISSUE TITLE
Feature request: to sync image to AWS S3 after image uploaded to label studio

### ISSUE THREAD

**Issue by zhichao2021** [heartexlabs/label-studio#1595]
**Is your feature request related to a problem? Please describe.**
When deployed Label Studio to cloud server, the storage of container is not consistent, each time the server restart, label studio lost save file on local storage

**Describe the solution you'd like**
Please support sync files directly to AWS s3, then change the ['data']['image'] field to the AWS s3 url

**Comment by makseq** [comment]
@zhichao2021 Thank you for your proposal, but it seems the task is not trivial, because we have to generate presigned task url  each time LS access it. We already have this functionality for LS source storages: https://labelstud.io/guide/storage.html#Amazon-S3
