### ISSUE TITLE
Return added tasks ids when import tasks by API

### ISSUE THREAD

**Issue by bobokvsky** [heartexlabs/label-studio#1598]
At the moment, import tasks returns response with some information, for example `task_count` -- `Number of tasks added`.
But in the response there is no information about id of the new added tasks id.

Could you please add information about tasks id in response of  `https://localhost:8080/api/projects/{id}/import`?

Instead of it, we are trying to get all the tasks (along with their annotations) to determine which newly added tasks have their ID. When there are already a lot of tasks when importing, this operation takes a long time.

**Comment by makseq** [comment]
Duplicated issue: 
https://github.com/heartexlabs/label-studio/issues/1202

Also please check this answer:
https://github.com/heartexlabs/label-studio/issues/1202#issuecomment-900521726

Some solution:
https://github.com/heartexlabs/label-studio/pull/1306

**Comment by makseq** [comment]
You can try this workaround: 
1. Create a tab without any filters (e.g. view-id)
2. Leave only one ID column there 
3. Call this API:

```
curl 'https://develop.dev.heartex.com/api/dm/views/<view-id>/tasks?page=1&page_size=100000000&project=<project-id>' \
   -H Authorization: Token <xxx>'
```
