### ISSUE TITLE
Add column `tasks.updated_at` to tabs (and maybe also `tasks:completed_at` to response of API)

### ISSUE THREAD

**Issue by bobokvsky** [heartexlabs/label-studio#1608]
At the moment, from API there are two useful columns about tasks: 

<html>
<body>

Key | Type | Description
-- | -- | --
tasks.created_at | datetime | Date and time of task creation.
tasks.updated_at | datetime | Date and time of last update to the task.

</body>
</html>

However, in tabs (views) there are possible columns `tasks:created_at` and `tasks:completed_at`:
![image](https://user-images.githubusercontent.com/15606508/137220877-64a96e2f-0c06-43b4-bfdb-a36aa4a98916.png)

Could you please add also column `tasks.updated_at` to tabs (and, maybe, `tasks:completed_at` to response of API for the sake of consistency)?

In my case, I need to get all `tasks.updated_at` from tasks without using heavy API to known which tasks were updated compared to the previous time, and at the moment I use [this solution](https://github.com/heartexlabs/label-studio/issues/1598#issuecomment-941800761) to get all tasks with some metadata. As luck would have it, this particular field is missing.

**Comment by bobokvsky** [comment]
@makseq yes, `update_at` is datetime of last update to the task. The column `completed_at` gives the date-time only for the moment of creation of the new annotation, and when it is modified, this column does not change.

**Comment by makseq** [comment]
This feature was added in the latest develop branch.

**Comment by yellowjs0304** [comment]
@makseq Hi, How can i add that column??
