### ISSUE TITLE
Labeling UI not working correctly for Taxonomy tag

### ISSUE THREAD

**Issue by karelserruys-foodpairing** [heartexlabs/label-studio#1626]
**Describe the bug**
We have created a taxonomy using the [label studio playground](https://labelstud.io/playground/).
When loading this taxonomy our project, the behavior in the UI is different and also a bit confusing for our end users.

In the playground, when we select a certain item in the taxonomy, we can see the checkbox changing in the parent and children of this item. Shown in screenshot 1.
When we do this in our deployed version of label studio, this is not working. Shown in screenshot 2.

**To Reproduce**
1. Setup a project with attached taxonomy.xml label_config.
2. Click on the project
3. Label all tasks
4. When labeling, notice behavior mentioned above.

**Expected behavior**
We expect the behavior of the UI to be in line with the label studio playground.
The taxonomy tag was working fine for us before we upgraded to label studio 1.3.0.

**Screenshots**
Screenshot 1:
![image](https://user-images.githubusercontent.com/79454108/137903396-5a9076f6-c245-4874-bc2f-0fcd3efc3740.png)
Click checkbox indicated in with the red arrow, UI updated checkboxes indicated with grey arrows.

Screenshot 2:
[taxonony.zip](https://github.com/heartexlabs/label-studio/files/7372998/taxonony.zip)
[taxonony.zip](https://github.com/heartexlabs/label-studio/files/7372999/taxonony.zip)

![image](https://user-images.githubusercontent.com/79454108/137903915-210c2ee0-48a8-4f50-8c2c-20029e5b85b3.png)
Click the checkbox indicated with the red arrow, UI is not updating other checkboxes.

**Environment (please complete the following information):**
 - OS: Linux
 - Label Studio Version1.3.0

**Additional context**

**Comment by makseq** [comment]
@karelserruys-foodpairing Could you please show your `/version` page?

**Comment by karelserruys-foodpairing** [comment]
Hey @makseq,
See attached file.
[version.zip](https://github.com/heartexlabs/label-studio/files/7379028/version.zip)

**Comment by vidixha** [comment]
Hi, can taxonomy tag be used with 'Label' tag instead of 'Choice' tag? Is there a provision for this?
