### ISSUE TITLE
Kubernetes deployment can't import GCS object

### ISSUE THREAD

**Issue by anyght** [heartexlabs/label-studio#1637]
**Describe the bug**
I have build in docker the project cloning.
  - I run in local with `docker run`, then sign in browser, add gcs bucket and configuring the labeling interface; the app import bucket object.
  - on Kubernetes, I made the same procedure, and I get an error Access Denied.  
  
![image](https://user-images.githubusercontent.com/59748997/138103872-557d4daa-5256-4683-ad2d-d48b5358f3a6.png)

**To Reproduce**
1. push image on a registry
2. deploy on Kubernetes with service account mounted and set  GOOGLE_APPLICATION_CREDENTIALS=path/of/mount
3. login with the browser to label-studio
4. configure `cloud storage` with `bucket name`, `bucket prefix` and `Google Application Credentials`
5. sync bucket  (is ok  I have the count of task in bucket)
6. configure the labeling interface
7. return to project and the error appear.

with Firefox inspect I can see in local request send to `storage.googleapis.com` domain to get bucket object, and not appear in Kubernetes deployment.

**Comment by farioas** [comment]
> deploy on Kubernetes with service account mounted and set GOOGLE_APPLICATION_CREDENTIALS=path/of/mount

Could you please share your kubernetes manifests?

**Comment by berniwal** [comment]
@anyght what did resolve your issue?
