### ISSUE TITLE
Controlled vocabulary/ontology for Meta info (formally Normalization) for use with NER

### ISSUE THREAD

**Issue by jeffmax** [heartexlabs/label-studio#1646]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to have a user normalize/link a named entity to a term from a controlled vocabulary/dictionary/ontology. This is useful for linking a named entity (say a disease) to a specific term within a medical ontology.

**Describe the solution you'd like**
The ability to upload an ontology file (for example .obo) that can be associated with a specific project. The ontology would then autocomplete for users populating the Meta info attribute of a named entity allowing them to choose only a term from the specific ontology/dictionary.

**Describe alternatives you've considered**
The alternative would be to ask users to complete the Meta info field by searching from an external website and populating with the term. This does not allow the project to enforce that the term come from a specific ontology or properly version the ontology.

**Comment by ogunoz** [comment]
any update?

**Comment by makseq** [comment]
Maybe Taxonomy tag can solve your problem partially?
https://labelstud.io/tags/taxonomy.html

**Comment by ogunoz** [comment]
Thanks for the answer. My use-case is having too many entities (500.000) so i couldn't use them as Label, it made whole application extremely slow because all `<Label>` items are rendered on the screen. That's why I was looking for a knowledge-base-like solution

**Comment by thomasgirault** [comment]
Hello, thank you for your work on Label-Studio! 
I have the same goal for my entity linking task and it would be awesome to annotate a text with large set of labels such as Wikipedia IDs.

Would it be possible to partially retrieve entities in an autocomplete widget from /api/labels ?
In the v1.4.1  and the develop branch, it seems that /api/labels is not enabled yet.
Is there any specific branch to test this feature ?

**Comment by makseq** [comment]
@thomasgirault 

> Would it be possible to partially retrieve entities in an autocomplete widget from /api/labels

yes, it's already dynamically retrievable.

>  In the v1.4.1 and the develop branch, it seems that /api/labels is not enabled yet.

It's in the `develop` branch: 
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/labels_manager/api.py
and most likely in the master branch too.
