### ISSUE TITLE
conversion of Sqlite3 to PostgreSQL fails with inappropriate integrity violation

### ISSUE THREAD

**Issue by tomasohara** [heartexlabs/label-studio#1658]
**Describe the bug**

Using the standard Django sqlite2-to-postgresql conversion steps consistently leads to errors during the load-data step (#6 under https://label-studio.slack.com/archives/CQ8LYPPJS/p1633996896427300). That is, the same error occurs on different hosts with different data and and with different workarounds attempted.) I suspect this is a bug due to django migrations. See the attached log [_convert-to-postgres-20oct21.log.txt](https://github.com/heartexlabs/label-studio/files/7401858/_convert-to-postgres-20oct21.log.txt) for the stack trace and the steps I used.

This leads to following error:
```
django.db.utils.IntegrityError: Problem installing fixture '/tpo/misc/programs/python/label-studio/simple-test-config/hacked-datadump-20oct21.pp.json': Could not load users.User(pk=1): duplicate key value violates unique constraint "authtoken_token_user_id_key"
DETAIL:  Key (user_id)=(1) already exists.
```

To work around the problem, I need to manually remove all but one of the authtoken.token entries from the JSON file:

```
$ diff datadump-20oct21.pp.json hacked-datadump-20oct21.pp.json
2379,2394d2378
<       "pk" : "3d24bdd29c698f6c09de3df9152cfdd4048cee09",
<       "fields" : {
<          "created" : "2021-10-21T00:52:39.157Z",
<          "user" : 2
<       },
<       "model" : "authtoken.token"
<    },
<    {
<       "pk" : "b658b0b1d81f8e8a7a60b4906c6568a3d7df340a",
<       "fields" : {
<          "created" : "2021-10-21T02:14:59.932Z",
<          "user" : 3
<       },
<       "model" : "authtoken.token"
<    },
<    {
```

See attachments: [datadump-20oct21.json.txt](https://github.com/heartexlabs/label-studio/files/7401866/datadump-20oct21.json.txt) and [hacked-datadump-20oct21.pp.json.txt](https://github.com/heartexlabs/label-studio/files/7401867/hacked-datadump-20oct21.pp.json.txt).

**To Reproduce**
This is based on https://gist.github.com/sirodoht/f598d14e9644e2d3909629a41e3522ad (How to migrate Django from SQLite to PostgreSQL)
0. Load Cat/Dog classification from test data [https://github.com/heartexlabs/label-studio/blob/master/label_studio/tests/test_suites/samples/previous_export.json].
   See attachment: 
[datadump-20oct21.json.txt](https://github.com/heartexlabs/label-studio/files/7401877/datadump-20oct21.json.txt)

1. Dump existing data:
     python3 manage.py dumpdata > datadump.json
2. Change settings.py to Postgres backend.
3. Make sure you can connect on PostgreSQL.
4. Then:
     python3 manage.py migrate --run-syncdb
5. Run this on Django shell to exclude contentype data
     python3 manage.py shell
     >>> from django.contrib.contenttypes.models import ContentType
     >>> ContentType.objects.all().delete()
     >>> quit()
6. Finally:
     python3 manage.py loaddata datadump.json

**Expected behavior**
All data from Sqlite3 ported to PostgreSQL, specifically the is-Cat annotation for the sample.

```
$ psql --host=localhost --port=5432 --username=postgres --command='select * from task;'
=>
 id |                                          data                                          |         created_at         |         updated_at         | is_labeled | project_id | meta | overlap | file_upload_id 
----+----------------------------------------------------------------------------------------+----------------------------+----------------------------+------------+------------+------+---------+----------------
  1 | {"image": "https://upload.wikimedia.org/wikipedia/commons/a/a3/June_odd-eyed-cat.jpg"} | 2021-10-20 21:27:36.107-05 | 2021-10-20 21:29:01.287-05 | t          |          1 | {}   |       1 |              5
(1 row)
```

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Label Studio Version 1.3.post0

**Additional context**
See discussion of using standard Django sqlite3-to-postgresql conversion steps under Label-Studio Slack:
    https://label-studio.slack.com/archives/CQ8LYPPJS/p1633996896427300

For our real DB, I had to remove all the auth-related entries to get it to work!

**Comment by makseq** [comment]
Closed as unrelated to the Label Studio issue.
