### ISSUE TITLE
label-studio aborts if problem with django migrations

### ISSUE THREAD

**Issue by tomasohara** [heartexlabs/label-studio#1661]
**Describe the bug**
If django raise an exception during the migration checks, Label Studio will abort. Instead, it should report the error and allow the user to proceed.

**To Reproduce**
1. Attempt a conversion from sqlite3 to postgresql (see example under issue #1658).
2. Introduce integrity error in django migrations to be performed
3. Try to start Label Studio

**Expected behavior**
Label Studio should proceed so that the user can use the UI for diagnostic purposes.

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Label Studio Version 1.3

**Additional context**
This arose during diagnosis of issue #1658.

**Comment by makseq** [comment]
I dived into this idea and I can't say it's a good solution: if the migrations fail, all work must be stopped. Otherwise, it may result in data loss and very bad user experience.
