### ISSUE TITLE
RectangleLabels all bounding box edges resized to fit zoomed in image when adjusting one edge

### ISSUE THREAD

**Issue by Adrian-Rasmussen** [heartexlabs/label-studio#1672]
**Description**
When adjusting the bounds of a bounding box (RectangleLabels) while zoomed in, the entire box will be reset to fit within the currently zoomed size. For example, if shifting the right edge, the left edge will also be moved to be inside the zoomed area

**To Reproduce**
```
<View>
  <RectangleLabels name="labels" toName="image">
    <Label value="Person" />
    <Label value="Animal" />
  </RectangleLabels>
  <Image name="image" value="$image"  zoomControl="true"/>
</View>
```
1. Add RectangleLabel to full size image
![image](https://user-images.githubusercontent.com/5214227/138811247-8fc42564-e525-48ed-874e-56dc921255f6.png)
2. Zoom in such that at least one edge of the bounding box is outside the view
3. Resize one edge of the bounding box
![image](https://user-images.githubusercontent.com/5214227/138811370-f4162e0e-02e5-4492-bc88-80070cca219c.png)
4. See that all edges are now within the zoomed area
![image](https://user-images.githubusercontent.com/5214227/138811412-c3ca0e3f-95cc-4936-b36b-6ade6278d7b7.png)

**Expected behavior**
Only the edge of the box currently being adjusted when zoomed in should be changed. All other edges of the box should be kept in place.

**Environment:**
 - OS: Docker
 - Label Studio Version:
 ```
 {
  "label-studio-os-package": {
    "version": "1.3.post0",
    "short_version": "1.3",
    "latest_version_from_pypi": "1.3.post0",
    "latest_version_upload_time": "2021-09-18T12:52:01",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "[fix] Filter chaining (#1594)",
    "commit": "e2eba82c8858e80479196c265b672ac0e80ff181",
    "date": "2021-10-15 09:24:13 +0300",
    "branch": "master",
    "version": "1.3.0+83.ge2eba82.dirty"
  },

  "release": "1.3.post0",
  "label-studio-frontend": {
    "message": "Add parent annotations, fix styles",
    "commit": "73555b417ab811033c8d0b3bd3c16130e9298f3b",
    "branch": "feature/parent-anno",
    "date": "2021/10/11 23:36:04"
  },

  "dm2": {
    "message": "Form fields fix",
    "commit": "6cc91af181fcc223a4af2ba28d58f1749cae6e3a",
    "branch": "HEAD",
    "date": "2021/10/12 13:17:15"
  },

  "label-studio-converter": {
    "version": "0.0.33rc1"
  }
}
```

**Additional context**
This is not reproducible using the Playground

**Comment by niklub** [comment]
Hi, @Adrian-Rasmussen ! Thanks for pointing out, currently working on it

**Comment by makseq** [comment]
This issue was fixed, please try the latest master.

**Comment by Adrian-Rasmussen** [comment]
Hi @niklub / @makseq unfortunately this issue seems to be happening again in the latest docker version:

```
{
  "release": "1.6.0rc5",
  "label-studio-os-package": {
    "version": "1.6.0rc5",
    "short_version": "1.6",
    "latest_version_from_pypi": "1.6.0",
    "latest_version_upload_time": "2022-09-27T17:09:34",
    "current_version_is_outdated": true
  },

  "label-studio-os-backend": {
    "message": "Bump rc5",
    "commit": "b0df5dd19a5400e8d26fb8269e2add87799af055",
    "date": "2022-09-27 16:32:57 +0100",
    "branch": "HEAD",
    "version": "1.6.0+0.gb0df5dd"
  },

  "label-studio-frontend": {
    "message": "fix: DEV-3510: fix video regions w/o label",
    "commit": "5d4231c2a8b9703f8c43abdf62948ac892d6f742",
    "branch": "master",
    "date": "2022/09/27 13:58:00"
  },

  "dm2": {
    "message": "feat: DEV-3373: Enable video preview (#106)  * Enable video preview  ...",
    "commit": "8374cbfeceb5aa9870278fc5371f0585d452c111",
    "branch": "master",
    "date": "2022-09-27T08:11:03Z"
  },

  "label-studio-converter": {
    "version": "0.0.44"
  }
}
```
