### ISSUE TITLE
Failed to import file in Conversational AI -> Intent Classification and Slot Filling

### ISSUE THREAD

**Issue by yanhuibin315** [heartexlabs/label-studio#1695]
**Describe the bug**
I start label-studio locally, and I want label my conversation data in it. But I got wrong with my import file.

**To Reproduce**
1. Run ```label-studio``` locally.
2. I create a project use label interface that intent classification in conversational AI.
3. I'm created my task like this:
```json
{
    "dialogs1": "<div style=\"max-width: 750px\"><div style=\"clear: both\"><div style=\"float: right; display: inline-block; border: 1px solid #F2F3F4; background-color: #F8F9F9; border-radius: 5px; padding: 7px; margin: 10px 0;\"><p><b>Jules</b>: No no, Mr. Wolfe, it's not like that. Your help is definitely appreciated.</p></div></div><div style=\"clear: both\"><div style=\"float: right; display: inline-block; border: 1px solid #F2F3F4; background-color: #F8F9F9; border-radius: 5px; padding: 7px; margin: 10px 0;\"><p><b>Vincent</b>: Look, Mr. Wolfe, I respect you. I just don't like people barking orders at me, that's all.</p></div></div><div style=\"clear: both\"><div style=\"display: inline-block; border: 1px solid #D5F5E3; background-color: #EAFAF1; border-radius: 5px; padding: 7px; margin: 10px 0;\"><p><b>The Wolf</b>: If I'm curt with you, it's because time is a factor. I think fast, I talk fast, and I need you two guys to act fast if you want to get out of this. So pretty please, with sugar on top, clean the car.</p></div></div></div>",
    "dialogs2": "<div style=\"max-width: 750px\"><div style=\"clear: both\"><div style=\"float: right; display: inline-block; border: 1px solid #F2F3F4; background-color: #F8F9F9; border-radius: 5px; padding: 7px; margin: 10px 0;\"><p><b>Jules</b>: No no, Mr. Wolfe, it's not like that. Your help is definitely appreciated.</p></div></div><div style=\"clear: both\"><div style=\"float: right; display: inline-block; border: 1px solid #F2F3F4; background-color: #F8F9F9; border-radius: 5px; padding: 7px; margin: 10px 0;\"><p><b>Vincent</b>: Look, Mr. Wolfe, I respect you. I just don't like people barking orders at me, that's all.</p></div></div><div style=\"clear: both\"><div style=\"display: inline-block; border: 1px solid #D5F5E3; background-color: #EAFAF1; border-radius: 5px; padding: 7px; margin: 10px 0;\"><p><b>The Wolf</b>: If I'm curt with you, it's because time is a factor. I think fast, I talk fast, and I need you two guys to act fast if you want to get out of this. So pretty please, with sugar on top, clean the car.</p></div></div></div>"
}
```
4. When I imported my data, I got this RUNTIME ERROR:
Validation error
Error at item 0: "dialogs" key is expected in task data [assume: item["data"] = task root with values] :: {'data': {'dialogs1': '

**Screenshots**
Error screenshots:
![image](https://user-images.githubusercontent.com/11473732/140023452-2bcc264c-8521-45d9-82f7-db08eead42af.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - Label Studio Version: 1.2

**Additional context**
And can you give some example data file for this label task? 

Thank you very much.

**Comment by makseq** [comment]
@yanhuibin315 You are using wrong input task data, please [check this example](https://labelstud.io/playground/?config=%3C!--Labeling%20configuration%20to%20label%20paragraph%20regions%20of%20text%20containing%20dialogue--%3E%3Cbr%3E%3CView%3E%3Cbr%3E%20%20%3CParagraphs%20name%3D%22dialogue-1%22%20value%3D%22%24dialogue%22%20layout%3D%22dialogue%22%20%2F%3E%3Cbr%3E%20%20%3CParagraphLabels%20name%3D%22importance%22%20toName%3D%22dialogue-1%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Important%20content%22%3E%3C%2FLabel%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Random%20talk%22%3E%3C%2FLabel%3E%3Cbr%3E%20%20%3C%2FParagraphLabels%3E%3Cbr%3E%3C%2FView%3E).
