### ISSUE TITLE
Brush tool has memory of brush thickness

### ISSUE THREAD

**Issue by jonnyevans3210** [heartexlabs/label-studio#1700]
When using the brush tool, it would be great if the brush automatically set its thickness as the last used thickness when going on to a new image, adding to a recently annotated image (after hitting 'submit') or when changing the brush label. I've spent far too long already guessing what thickness brush I used last.

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can label pixels using brushes.
RectLabel stores the brush size history.
https://rectlabel.com/help#create_pixels

![brush_history](https://user-images.githubusercontent.com/1954306/214841155-9a5e293e-9d13-4958-afdc-1dadba0730c9.jpg)
