### ISSUE TITLE
How to import NER Annotation json file into label-studio to validate the annotation on the data ?

### ISSUE THREAD

**Issue by karndeepsingh** [heartexlabs/label-studio#1734]
Hi,
I have a team that does the annotation for the NER problem. And for this annotation to start we installed label studio on their system. 
So, once they finish the annotation and I want to bring their annotation in JSON file into my system and want to validate the annotation on the data they have annotated. So, my question is how can we validate the annotation on my system by importing there annotation JSON file and Data into the Label studio?

Please, provide suggestion on the validating the annotations. It help us to step up.

Thanks

**Comment by makseq** [comment]
Hi, in Label Studio Teams we have a special review stream & tools for this. 

If you want to use opensource, I would suggest that you use the same labeling config and re-import exported JSON file. However you should extend your labeling config with choices like this:

```
  <Choices name="review" toName="image">
    <Choice value="good"/>
    <Choice value="bad"/>
  </Choices>
```

And use these choices as review marks in Quickview. Hope it helps.

**Comment by karndeepsingh** [comment]
> Hi, in Label Studio Teams we have a special review stream & tools for this.
> 
> If you want to use opensource, I would suggest that you use the same labeling config and re-import exported JSON file. However you should extend your labeling config with choices like this:
> 
> ```
>   <Choices name="review" toName="image">
>     <Choice value="good"/>
>     <Choice value="bad"/>
>   </Choices>
> ```
> 
> And use these choices as review marks in Quickview. Hope it helps.

You mean I need to add these Choice here in the code section as shown below:
![image](https://user-images.githubusercontent.com/49562460/142427781-96915b42-1e24-484b-a292-ef8dbd3ae702.png)

**Comment by makseq** [comment]
@karndeepsingh Yes, just expand your labeling config with Choices before the last </View>.

**Comment by karndeepsingh** [comment]
@makseq So, while exporting the JSON file, I need to add these choices in my config and export it. And then in my new device I have created a project where I have all the Sentences that has been imported already, So, I need to just import this JSON file that I got it exported from other device.
Please, correct me if my understanding is wrong.

Thanks

**Comment by makseq** [comment]
You are right! The main idea is as you described.
