### ISSUE TITLE
Updating the labeling interface control tags deletes tabs

### ISSUE THREAD

**Issue by csaroff** [heartexlabs/label-studio#1744]
**Is your feature request related to a problem? Please describe.**
Adding or removing [control tags](https://labelstud.io/tags/) from a project's labeling interface causes all tabs to be dropped. 

For instance, when I remove a possible [Choice](https://labelstud.io/tags/choice.html) from my config I get this warning:

> Labeling config has essential changes that affect data displaying. Saving the config may lead to deleting all tabs previously created in the Data Manager.

And afterwards all my views are deleted, even though they had nothing to do with that Choice. It's probably a bit tricky to patch this, but having all my views reset every time I make a change isn't great for iteration speed :slightly_smiling_face:

I'd rather have broken tab filters than have every tab get deleted anytime I change my labeling configuration

**Describe the solution you'd like**
Can we make updating the labelling interface less destructive (to the data manager views)?

**Describe alternatives you've considered**
I don't see any good workarounds right now.

**Additional context**
Related [slack conversation](https://label-studio.slack.com/archives/CQ8LYPPJS/p1622213926131700)

**Comment by robhyb19** [comment]
+1

**Comment by makseq** [comment]
[Slack link to similar thread](https://label-studio.slack.com/archives/C01SKFX54QK/p1643227499427679)

**Comment by saskra** [comment]
I have the same problem, out of the blue I can no longer add new Choice blocks without getting this message. And even the existing blocks I can't add any more choices. Only deleting old blocks still works.

**Comment by makseq** [comment]
@saskra what LS version do you use?

**Comment by saskra** [comment]
> @saskra what LS version do you use?

1.6.0rc5

**Comment by yyassi-heartex** [comment]
Hello! @saskra would it be possible to get a video of this issue in action? as it'll help us investigate the issue further

**Comment by saskra** [comment]
In fact, unfortunately, this is now no longer possible: I have since dared to click OK anyway, and fortunately nothing bad has happened, as far as I could tell so far.

**Comment by csaroff** [comment]
Just ran into this again in 1.6.0rc5/(docker tag 1.6.0). In case it's helpful in remediating this, I think you have to actually add or remove a *control tag* in order for it to drop the tabs.

**Comment by yyassi-heartex** [comment]
@csaroff I believe the solution for this problem is slated to be resolved in the coming release. I just double checked the latest and the issue appears to be resolved there

**Comment by yyassi-heartex** [comment]
@csaroff I think this has been resolved so I'll go ahead and close it. Please let us know if the issue re-occurs
