### ISSUE TITLE
fillColor, StrokeColor, opacity, StrokeWidth of Rectangle tag don't work 

### ISSUE THREAD

**Issue by mrtunguyen** [heartexlabs/label-studio#1745]
**Describe the bug**
I tried to change the value of parameters fillColor, opacity, strokeColor, strokeWidth, canRotate of Rectangle tag but nothing works. 

**To Reproduce**
1. Go to [polygon tag playground](https://labelstud.io/playground/?config=%3C!--Basic%20labeling%20configuration%20for%20adding%20rectangular%20bounding%20box%20regions%20to%20an%20image%20--%3E%3Cbr%3E%3CView%3E%3Cbr%3E%20%20%3CRectangle%20name=%22rect-1%22%20toName=%22img-1%22%20/%3E%3Cbr%3E%20%20%3CImage%20name=%22img-1%22%20value=%22$img%22%20/%3E%3Cbr%3E%3C/View%3E)
2. Change fillColor to #29b924
3. Compare with fillColor default, nothing changes.

**Expected behavior**
The Rectangle tab should change behavior whenever we change its value of parameter.

**Screenshots**
fillColor by default
![image](https://user-images.githubusercontent.com/56027282/142147496-01e829ec-88dd-46a1-b29e-20ff009f9e7b.png)

fillColor = "#52c825"
![image](https://user-images.githubusercontent.com/56027282/142147633-d0b78da0-2318-467d-8cf2-fa9b3b524e5e.png)

fillColor = "#9d34a4"
![image](https://user-images.githubusercontent.com/56027282/142147766-c982599c-e60f-4020-8e3b-4617a79fbbae.png)

**Comment by Gondragos** [comment]
Thank you for your vigilance! The playground version doesn't look like the latest one. But it seems that parameters `fillColor`, `opacity`, `strokeColor`, `strokeWidth`  haven't worked for a while.
We're already working on that.

**Comment by makseq** [comment]
The fix is in master branch and will be release in 1.4.1.
