### ISSUE TITLE
IFrame example inside Docker does not work

### ISSUE THREAD

**Issue by chauff** [heartexlabs/label-studio#1746]
**Describe the bug**
I followed the [video classifier](https://labelstud.io/templates/video_classification.html) example to play around with iframes inside Label Studio. Using the Docker setup, the iframe isn't shown, instead an error appears on the console `TypeError: Cannot read properties of null (reading 'dataObj')`.

**To Reproduce**
1. Start Label Studio with Docker
2. Go to http://0.0.0.0:8080/ and create a new project.
3. Use the data and view template from [here](https://labelstud.io/templates/video_classification.html) (the `iframe` example data)
4. Try labeling - the video embed isn't shown.

**Expected behavior**
The video embed should be shown just like in the [online playground](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CChoices%20name=%22type%22%20toName=%22video%22%20choice=%22single-radio%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value=%22Motion%22%3E%3C/Choice%3E%3Cbr%3E%20%20%20%20%3CChoice%20value=%22Stable%22%3E%3C/Choice%3E%3Cbr%3E%20%20%3C/Choices%3E%3Cbr%3E%20%20%3CHyperText%20name=%22video%22%20value=%22$html%22%3E%3C/HyperText%3E%3Cbr%3E%3C/View%3E%3Cbr%3E%3C!--%20%7B%20%22html%22:%20%22%3Ciframe%20src=%27https://www.youtube.com/embed/mf9TKj0NuTQ%27%3E%3C/iframe%3E%22%20%7D%20--%3E)

**Environment (please complete the following information):**
 - MacOS Monterey
 - Label Studio Version 1.3
 - Browsers: latest Chrome/Firefox

**Comment by makseq** [comment]
@chauff Thank you for your report. Please, check this video classifier template again, it's fixed now.
