### ISSUE TITLE
Validation error when updating labelling config

### ISSUE THREAD

**Issue by uriel-tannen** [heartexlabs/label-studio#1757]
I have a config with a number of Choices Labels, and am now trying to update the labels - add some, remove some. As I have some tasks that are already annotated, I'm getting a validation error informing me that there are completed annotations with the choice labels I am trying to remove. I've therefore updated the annotations so that the choice label to be removed is no longer being used in the project. However I am getting the same validation error when attempting to update my config, despite the fact that these labels are no longer contained in any of the annotations.

Screenshot 1: the validation error when updating the config
![image](https://user-images.githubusercontent.com/36728824/142422585-73c89094-cd8d-4951-bb21-4259a276174d.png)

Screenshot 2: as you can see, there are no tasks with annotations containing "Tableware" (which is one of the choice labels with a validation error in screenshot 1)
![image](https://user-images.githubusercontent.com/36728824/142422769-b6a138b0-697a-441e-a325-6c2c00ea8680.png)

LS version 1.0.1

**Comment by uriel-tannen** [comment]
@makseq are you able to confirm if you can reproduce this error on your end, and if you're aware where the issue could be?

Just to give a further example: I'm looking to remove 'Accessories' as a choice label in my config. As you can see from the first image, I can't remove this as it appears that there are 7 tasks already annotated with this choice label. However you can see from the second image that there are no such tasks. In addition, I've used DataGrip to look into my PostgreSQL database and you can see that whilst there are 29 completions containing 'Accessories', none of these are exact matches and they're all either 'Garden Accessories' or 'Curtain Accessories'. I don't therefore understand why I can't remove 'Accessories' as a choice label.

![image](https://user-images.githubusercontent.com/36728824/145021419-bee51b2f-ebcd-474c-82a9-895893af8307.png)
![image](https://user-images.githubusercontent.com/36728824/145021774-5217aa01-9e87-4f2d-820b-4dc440109ad7.png)
![image](https://user-images.githubusercontent.com/36728824/145022021-285b2a6c-4ee6-4f4c-9716-698ec55cede7.png)

**Comment by makseq** [comment]
Please, check LS==1.4.1rc0, there you can save the labeling config with another labels.
