### ISSUE TITLE
How to use the question-answer template i  label-studio

### ISSUE THREAD

**Issue by pushpalatha1405** [heartexlabs/label-studio#1772]
Hi,

I have used the label-studio for annotation in fledge to create custom dataset for my projects.

Now i need to know the steps to use question-answer template in label-studio,which iam not able to use the template appropriately.

Please reply positively as i require this template to create custom annotations.

hoping for positive reply

regards,
Pushpalatha M

**Comment by makseq** [comment]
Hi, what steps do you want to know about question-answer template? Do you have problems with import data? Or labeling?

**Comment by pushpalatha1405** [comment]
hi,

i have problems with labeling.I need to know the steps . 

i have doubts in creating labels....

Usually in QA templates there are labels such as question,answer,is_impossible,context etc...

so pls can u direct me to use the template appropriately if i import any of text file to label using QA template.

also i see in the QA template that additional files need to be imported to use the QA template?
regards,
Pushpalatha M

**Comment by makseq** [comment]
Please try this template:

```
<View>
  <Header value="Please read the passage"/>
  <Text name="text" value="$text" granularity="word"/>
  <Header value="Select a text span answering the following question:"/>
  <Text name="question" value="$question"/>
  <Labels name="answer" toName="text">
    <Label value="Answer" maxUsage="1" background="red"/>
    <Label value="Question" background="#22aa2b"/>
    <Label value="Is impossible" background="#72aafb"/>
    <Label value="Context" background="#f2fa2b"/>
  </Labels>
</View>
```

and this data for import:
```
{"data": { "text": "The boundary of the region from which no escape is possible is called the event horizon. Although the event horizon has an enormous effect on the fate and circumstances of an object crossing it, according to general relativity it has no locally detectable features.[4] In many ways, a black hole acts like an ideal black body, as it reflects no light.[5][6] Moreover, quantum field theory in curved spacetime predicts that event horizons emit Hawking radiation, with the same spectrum as a black body of a temperature inversely proportional to its mass. This temperature is on the order of billionths of a kelvin for black holes of stellar mass, making it essentially impossible to observe directly.", "question": "How could black holes be detected?" }, "annotations": [{"result": [ { "value": { "start": 423, "end": 553, "text": "event horizons emit Hawking radiation, with the same spectrum as a black body of a temperature inversely proportional to its mass.", "labels": [ "Answer" ] }, "id": "b0wKkdnnRc", "from_name": "answer", "to_name": "text", "type": "labels" } ] }] }
```

**Comment by pushpalatha1405** [comment]
hi Max Tkachenko,

Thanks for the reply.

I would try the solution u sent.

regards,
Pushpalatha M

**Comment by Dharmin-Shah** [comment]
Can you please share the steps to import a txt file for question-answering labeling?

Currently I am trying to use it in the following way:

Following is my configuration for template:
```

<View>
  <Header value="Please read the passage" />
  <Text name="text" value="$text" granularity="word" valueType="url"/>
  
  <Header value="Select a text span answering the following question:"/>
  <Text name="question" value="$question"/>

  <Labels name="answer" toName="text">
    <Label value="Answer" maxUsage="1" background="red"/>
  </Labels>

</View>
```
However, I am not able to import any text file as 'Time Series or Whole Text File' and it throws following error:

```
Validation error

    Failed to parse input file upload/13/ccc6c83f-dd1618.txt: [ErrorDetail(string='Your label config has more than one data key and direct file upload supports only one data key. To import data with multiple data keys, use a JSON or CSV file.', code='invalid')]

Version: 1.7.1

```

However, I have noticed that if I remove the entire tag of question, it allows me to import the file.

**Comment by makseq** [comment]
It's not possible to import txt file for this template. It can be JSON or CSV/TSV only. 

JSON example:
```
{
  "text": "The boundary of the region from which no escape", 
  "question": "How could black holes be detected?" }
}
```

CSV example
```
text,question
The boundary of the region from which no escape,How could black holes be detected?
```
