### ISSUE TITLE
Read timed out error for the ML Model

### ISSUE THREAD

**Issue by krnithishkumar** [heartexlabs/label-studio#1773]
For my custom-ML model integration with LS1.4, the model takes more than 4 mins the get the complete output.
Before finishing the inference Label-Studio stops and provides `Read timed out (read timedout=100.0).

Kindly check with the below log.
![image](https://user-images.githubusercontent.com/29236082/142880690-eea480af-8065-43bd-8e17-1908346337dd.png)

Is there any way to configure the LS request timed out settings?

**Comment by makseq** [comment]
According to this docs: https://labelstud.io/guide/ml.html#Get-predictions-from-a-model
you should evaluate ML backend predictions asynchronously and then call POST api/predictions manually. 

> Note: For a large dataset, the HTTP request to retrieve predictions might be interrupted by a timeout. If you want to get all predictions for all tasks in a dataset from connected machine learning backends, make a POST call to the predictions endpoint of the Label Studio API for each task to prompt the machine learning backend to create predictions for the tasks.
