### ISSUE TITLE
Overlapping annotations incorrect and not displayed 

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#178]
When adding an (entity) annotation to text that overlaps an existing one, e.g. starts before and ends after an existing one, an annotation is added that has wrong offsets (start=null, end=0) but no annotation is shown visually.

Correctly dealing with overlapping annotations is important for some tasks.
However if a task explicitly disallowes it, no annotations should get created and an error should get shown.

**Comment by deppp** [comment]
@johann-petrak that was fixed in the latest release, please try it out. I'm closing this issue, feel free to re-open if the issue persists
