### ISSUE TITLE
Docker compose fails in LabelStudio 1.4.0

### ISSUE THREAD

**Issue by bugo99iot** [heartexlabs/label-studio#1788]
**Describe the bug**
Docker compose fails with error "Building labelstudio Cannot locate specified Dockerfile: Dockerfile" in LabelStudio 1.4.0.
The build works correctly in LabelStudio 1.3.0 (I have simply upgraded the version in Docker compose file).

**To Reproduce**
1. Run docker-compose up -d for docker-compose.yml below.
2. See error "Building labelstudio Cannot locate specified Dockerfile: Dockerfile"

**Expected behavior**
The container should stand up.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS
 - Label Studio Version 1.4.0
 - Docker compose version: 2

**Additional context**
My docker-compose.yml file:

version: "2"

networks:
  web:
    external: true
  internal:
    external: false

services:
  labelstudio-postgres:
    image: postgres:13
    container_name: labelstudio-postgres
    restart: unless-stopped
    volumes:
      - /data/labelstudio/postgres:/var/lib/postgresql/data
    env_file:
      - env
    networks:
      - internal
    ports:
      - 5434:5432
    labels:
      - traefik.enable=false
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  labelstudio:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:1.4.0
    expose:
      - "8080"
    container_name: labelstudio-app
    restart: unless-stopped
    networks:
      - web
      - internal
    ports:
      - 8080:8080
    volumes:
      - /data/labelstudio/labelstudio_data:/label-studio/data:rw
    env_file:
      - env
    depends_on:
      - labelstudio-postgres
    labels:
      - traefik.backend=labelstudio
      - traefik.frontend.rule=Host:label.mydomain.com
      - traefik.docker.network=web
      - traefik.port=8080
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

**Comment by farioas** [comment]
The original docker-compose file inside label-studio repository was made for development purposes. That's why it has directives like `build: .` (https://docs.docker.com/compose/compose-file/compose-file-v3/#build). Since you're trying to run the prebuilt image `heartexlabs/label-studio:1.4.0` you have to remove all `build` directives from your docker-compose.yml
