### ISSUE TITLE
Annotations should allow features

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#179]
Rather than just a label from a selection of labels an annotation (a span of text) should be configurable to have additional features. This can serve two purposes: first, some ML tasks involve predicting more than one piece of information per instance and second, annotators can add meta-information about the annotation, e.g. confidence, a remark etc. which could be very useful for adjudication.

**Comment by niklub** [comment]
Hi, @johann-petrak !
Thanks for suggestion. Actually you may find useful to create a label config with multiple annotation tags, i.e. in your case it could look like
```xml
<View>
<Text name="text" value="$text"/>
<Labels name="spans" toName="text">
  <Label value="label_1"/>
  <Label value="label_2"/>
</Labels>
<TextArea name="remark" toName="text"/>
<Rating name="confidence" toName="text"/>
</View>
```
Does it suit for you?

**Comment by deppp** [comment]
I think what @johann-petrak means is the feature where you can assign multiple labels to the same labeled region. 

This is WIP at the moment. Another limitation with the current approach is the inability to edit the labels assigned to the region. I think the whole assign/edit process shall be redone, and ideas about how to do that are welcomed.

**Comment by johann-petrak** [comment]
@niklub  TBH I am not sure: when I try this myself, as soon as I stop selecting the text to annotate, the page goes blank and when I reload I see the same not-annotated text. 
No exception is shown on the console, but nothing seems to get done either. 

But if the desired outcome would be that the entered remark and the rating then are properties of the annotation I create, that is what I want, yes. 

@deppp actually I wanted both :) the overlapping/same region annotations issue is https://github.com/heartexlabs/label-studio/issues/178

**Comment by makseq** [comment]
It seems the most of these features are released:
1. scores per region are now supported
2. conditional and nested labeling makes meta info is available per region 
3. a lot of bugs are fixed
