### ISSUE TITLE
Crosshair movement is amplified when zoomed in

### ISSUE THREAD

**Issue by EliasRas** [heartexlabs/label-studio#1797]
**Describe the bug**
If you zoom in when labeling an image, the movement of the cursor and the crosshair do not match. I haven't tested but the movement of the crosshair seems to be multiplied by the amount of zoom (e.g. 2x distance with 200% zoom).

**To Reproduce**
1. Enable crosshair from labeling interface settings
2. Start labeling
3. Zoom in
4. Move mouse

**Expected behavior**
The crosshair and the cursor would move together.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version 1.4
 - Chrome

**Comment by makseq** [comment]
@EliasRas Thank you for your report, I've created a JIRA ticket for this, hope it will be fixed soon.

**Comment by TrueWodzu** [comment]
A new Label Studio user here. How can I enable a cross hair? I've searched everywhere but can't find it.

**Comment by makseq** [comment]
@TrueWodzu https://labelstud.io/tags/image.html#main --- `crosshair` is an image attribute. 

 <Image crosshair="true" ... >

**Comment by makseq** [comment]
btw this issue has been fixed, most likely in 1.4.1. And 100% in the `develop` branch.

**Comment by TrueWodzu** [comment]
@makseq Thank you, works like a charm.

**Comment by robwijnhoven** [comment]
I am surprised to see that the crosshair is not enabled by default, when drawing boxes you always want that. Is there a specific reason for not enabling it by default?
Also, the crosshair is very poorly visible, how can we change the colors? Seems like the only way now as a user is to try to find the right line in the final .js file...

**Comment by mj026** [comment]
Request to reopen this issue as the crosshair is not properly aligned with the mouse cursor when zooming in:
![image](https://github.com/user-attachments/assets/f9b3e1bb-05b7-420c-aa28-dc637e42e359)
