### ISSUE TITLE
"relation" shortcut doesn't work in v1.4.

### ISSUE THREAD

**Issue by fairy-of-9** [heartexlabs/label-studio#1807]
**Describe the bug**

relation shortcut("r") doesn't work in v1.4.

**To Reproduce**

1. import json data
```
{
    "dialogue": [
        {
            "author": "Mia Wallace:",
            "text": "Dont you hate that?"
        },
        {
            "author": "Vincent Vega:",
            "text": "Hate what?"
        },
        {
            "author": "Mia Wallace:",
            "text": "Uncomfortable silences. Why do we feel its necessary to yak about bullshit in order to be comfortable?"
        },
        {
            "author": "Vincent Vega:",
            "text": "I dont know. That is a good question."
        }
    ]
}
```
2. Set interface
```
  <View>
    <Relations><Relation value="similar"/></Relations>  # In v1.2 it works well whether the code is present or not, and in v1.4 it does not work.
    <ParagraphLabels name="lbl-1" toName="dialogue-1"> 
      <Label value="q"/>
      <Label value="w"/>
    </ParagraphLabels>
    <View>
      <Paragraphs name="dialogue-1" value="$dialogue" layout="dialogue"/>
    </View>
  </View>

```

**Expected behavior**
Relation cannot be annotated.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-42-generic x86_64)
 - abel Studio Version: 1.4
 - use conda

**Comment by makseq** [comment]
Hope this option helps:
![image](https://user-images.githubusercontent.com/501780/144691111-b8128f0f-8ec4-4ec0-b1e4-50c1f91520c8.png)

'r' was moved to 'alt+r'

**Comment by fairy-of-9** [comment]
@makseq 
Thank you for your answer.
Is there any way to change the shortcut to 'r'?

**Comment by makseq** [comment]
@fairy-of-9 Check this please: https://labelstud.io/guide/labeling.html#Customize-hotkeys
