### ISSUE TITLE
Bounding Box overflow on their selection when operating at image width < 100%

### ISSUE THREAD

**Issue by jasdeep06** [heartexlabs/label-studio#1809]
**Describe the bug**
When Image width is set to 50% and bounding box created and selected, they overflow the image area.

**To Reproduce**
1. Change image width(In image tag of labelling interface) to 50%
2. Open an image for labelling.
3. Draw 3 bounding boxes anywhere on the image.
4. Select a bounding box to see the overflow

**Expected behavior**
Bounding box should stay at their places.

**Screenshots**
Adding a gif
![bug](https://user-images.githubusercontent.com/9949388/144646399-36aaf52e-9769-4fb1-a004-7daa75333797.gif)

**Environment (please complete the following information):**
 - Windows 10,Chrome Version 96.0.4664.45 (Official Build) (64-bit)
 - 14 Days teams trial(So its running on your servers)
 - Label Studio Version [whatever is deployed on cloud by LS in their teams trial]

**Comment by makseq** [comment]
@jasdeep06 thank you for your report, I passed this to our frontend team.

**Comment by dvivarelli** [comment]
any  update about this issue?
I have the same problem

**Comment by hlomzik** [comment]
fixed in #1875
