### ISSUE TITLE
Add entitiy on the fly

### ISSUE THREAD

**Issue by tattoodobem** [heartexlabs/label-studio#181]
**Is your feature request related to a problem?
In my project i'd like to have the ability to create entities on the fly instead of having to know them all before. Even if i did know most and one was missing it would mean a rebuild

**Describe the solution you'd like**
The solution would allow to create and manage entities and able to export them

Is this possible to do with some changes?

**Comment by deppp** [comment]
Hey @tattoodobem,

What version are you using? If you're using the latest >0.4.0 and starting the server using `label-studio start`, then you shall have a config edit feature. You can easily update the config on the fly, and it checks the new config for the consistency with the items already labeled. For example, if you label items with the label "Hello" and then try to remove that label, you'd get an error.

Please let me know if that solves your issue.

**Comment by tattoodobem** [comment]
> Hey @tattoodobem,
> 
> What version are you using? If you're using the latest **>=0.4.0** and starting the server using `label-studio start`, then you shall have a config edit feature. You can easily update the config on the fly, and it checks the new config for the consistency with the items already labeled. For example, if you label items with the label "Hello" and then try to remove that label, you'd get an error.
> 
> Please let me know if that solves your issue.

Yeah but the author can't insert new Entities. Imagine you have text to label and want to start from zero. You don't know, from the start, what entities it might have or even labels.

**Comment by deppp** [comment]
@tattoodobem What I mean is, if you go into /setup, you can update the labeling config and insert new `<Label />` tags.

But I agree, it seems to be not optimal at the moment, and it'd be better to have an **Add Label** button that automatically updates the config. I'll think about how to add that. Thanks for the idea!

**Comment by makseq** [comment]
[Taxonomy](https://labelstud.io/templates/taxonomy.html) supports adding labels on the fly since LS ~1.3.
