### ISSUE TITLE
'Cannot read properties of undefined (reading 'map')' when using external data api with TimeSeries

### ISSUE THREAD

**Issue by barthogenes** [heartexlabs/label-studio#1812]
**Describe the bug**
When opening an annotation task that loads data from an external endpoint, this error pops up.

**To Reproduce**
0. Configure a time-series labeling interface.
1. Open an annotation task that loads data from an external endpoint.
2. See error.

**Expected behavior**
The data should load from the external endpoint and display in the time seriescomponent.

**Screenshots**
![image](https://user-images.githubusercontent.com/20557666/144853298-c38f4c06-cfed-4c68-a5c7-f87304bbbeb1.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version: master

**Comment by makseq** [comment]
@barthogenes 
1 Could you clarify please: what do you mean by "external endpoint"? 
2 Could you share a labeling config & sample data to reproduce this issue please?

**Comment by milton-logothetis** [comment]
Same issue, while having imported .csv timeseries from local server.

**Comment by barthogenes** [comment]
> @barthogenes 1 Could you clarify please: what do you mean by "external endpoint"? 2 Could you share a labeling config & sample data to reproduce this issue please?

1 With "external endpoint" I mean my local flask server that serves csv data to label studio.
2 While I was trying to set up a configured fork with my problem, I encountered that I was setting the index like this:
```python
df.set_index("datetime", inplace=True)
```

This drops the column from the Dataframe, which caused the error to occur, because after changing it to the following:
```python
df.set_index("datetime", inplace=True, drop=False)
```
It suddenly started working again!

Maybe you have a similar issue to this @milton-logothetis.

**Comment by milton-logothetis** [comment]
@barthogenes Thank you for the suggestion! It was indeed a formatting issue in my case that was sort of related to yours. In my case I was using the "Visual" UI to import the data which was unable to automatically perform the import and hence getting the above error. I solved it by going into the "Code" UI and manipulating the XML column names and DateTime formats.

**Comment by makseq** [comment]
I can also add that all your samples need to be ordered with an increase in time, otherwise you will have a similar error.

Could we close this issue now?

**Comment by barthogenes** [comment]
Yes, I will do so now.
Thanks for the help!
