### ISSUE TITLE
Requirements clash: prompt-toolkit

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#182]
I am running Python 3.6.8 (Anaconda) and when I pip install label-studio I get this error message:
```
ERROR: jupyter-console 6.0.0 has requirement prompt_toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.14 which is incompatible.
ERROR: ipython 7.11.1 has requirement prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.14 which is incompatible.
```
This then uninstalls prompt-toolkit-3.0.2 and installs prompt-toolkit-1.0.14
After this, ipython and jupyter notebook are unusable and terminate with 
```
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
```

On the other hand if I install ipython properly with the required dependency, label-studio terminates with 
```
from prompt_toolkit.token import Token
```

I guess it would be useful to upgrade to the more recent version of prompt-toolkit as it would be important to be able to use label-studio in the same environment as ipython.

**Comment by niklub** [comment]
Hi, @johann-petrak ! Thanks for reporting this. I believe the issue has gone now. Please try again updating to the latest version `pip install label-studio==0.4.3` and feedback us please if everything is OK so we can close this issue

**Comment by johann-petrak** [comment]
Thanks, this appears to work for me now!

**Comment by pietz** [comment]
Damn, that was quick. Can confirm, work for me too.
