### ISSUE TITLE
Confusing about disabling iframe in HyperText in v1.4.0

### ISSUE THREAD

**Issue by loveychen** [heartexlabs/label-studio#1824]
**Describe the bug**

I updated Label Studio from v1.3.0 to v1.4.0, and I found that HyperText with `valueType="text"` and `value="<iframe src="https://www.baidu.com/">"` cound not work as expected.

As I inspected the source code, I found the `iframe` was replaced by `ls-stub`. And this work was done in `label_studio/frontend/dist/lsf/js/main.js` (a compacted js file), and the formatted js source code came as below:

```javascript
t = t.replace(/(<head.*?>)(.*?)(<\/head>)/, (e, t, n, r) =>
    [
      t,
      n.replace(/<script\b.*?<\/script>/g, "\x3c!--ls-stub></ls-stub--\x3e"),
      r,
    ].join("")
  )
  .replace(/<script\b.*?<\/script>/g, "<ls-stub></ls-stub>")
  .replace(/<iframe\b.*?(?:\/>|<\/iframe>)/g, "<ls-stub></ls-stub>");
```

I would like to know the reason why to disable `iframe` in `HyperText`, does `iframe` cause any security issues? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

**Comment by makseq** [comment]
@loveychen Please, add `inline="true"` to your `<HyperText>` => `<HyperText inline="true" value="<iframe src='https://www.baidu.com/'>">`

**Comment by hlomzik** [comment]
Hi! Actually we did kind of opposite thing — we use `iframe` now by default to make a sandbox for loaded html, so in your case you should use just the "baidu.com" as `value`.
