### ISSUE TITLE
Problem with tutorial MMDetection install

### ISSUE THREAD

**Issue by John-Polo** [heartexlabs/label-studio#1836]
**Describe the bug**
Installation of MMDetection fails on [step 2](https://labelstud.io/tutorials/object-detector.html#Installation) of the Installation section, create and initialize coco-detector. The error message returned:

> 
> Can't import module "mmdetection", reason: No module named "mmdetection". If you are looking for example, you can find a dummy model.py here:
> https://labelstud.io/tutorials/dummy_model.html

**To Reproduce**
conda create --name mmlab
conda activate mmlab
pip install mmcv
conda install pytorch-cpu==1.10.0
conda install torchvision-cpu
git clone https://github.com/open-mmlab/mmdetection.git
cd mmdetection
pip install -r requirements/build.txt
conda install pyyaml
conda inatall requests'<3,>=2.22.0'
conda install urllib3'<1.27,>=1.25.4'
pip install "git+https://github.com/cocodataset/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"
pip install -v -e .
label-studio-ml init coco-detector --from label_studio_ml/examples/mmdetection/mmdet.py
-error message mentioned above returned here-

**Expected behavior**
No error message returned.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Linux (Slackware 15.0)
 - Label Studio Version: 1.4
 
**Additional context**
I don't know what else to include.

**Comment by KonstantinKorotaev** [comment]
@John-Polo could you please check ML backend from [fix/mmdetection-blog](https://github.com/heartexlabs/label-studio-ml-backend/tree/fix/mmdetection-blog)?

**Comment by John-Polo** [comment]
@KonstantinKorotaev Hi. Sorry, I'm a noob with GitHub and ML and everything else. That being the case, it would help me if you wrote explicitly what I should do. In this case, I don't know if I should use "clone" or "checkout". I also don't know how to refer to the branch. I tried this:
`conda create --name mmlab
conda activate mmlab
pip install mmcv
conda install pytorch-cpu==1.10.0
conda install torchvision-cpu
git clone https://github.com/heartexlabs/label-studio-ml-backend.git#egg=mmdetection-blog&subdirectory=fix
`
And this happened:
> fatal: unable to update url base from redirection:
>  asked for: https://github.com/heartexlabs/label-studio-ml-backend.git#egg=mmdetection-blog/info/refs?service=git-upload-pack
   redirect: https://github.com/heartexlabs/label-studio-ml-backend

**Comment by KonstantinKorotaev** [comment]
Try this:  git clone -b fix/mmdetection-blog https://github.com/heartexlabs/labe
l-studio-ml-backend.git

**Comment by John-Polo** [comment]
Thank you, @KonstantinKorotaev. It looks like that mostly worked, but now there is a different error:
```
Installed /home/j/Documents/dogscats/label-studio-ml-backend/mmdetection

Successfully installed mmdet terminaltables-3.1.10

Traceback (most recent call last):

  File "/home/j/miniconda3/envs/mmlab/bin/label-studio-ml", line 33, in <module>
    sys.exit(load_entry_point('label-studio-ml', 'console_scripts', 'label-studio-ml')())

  File "/home/j/Documents/dogscats/label-studio-ml-backend/label_studio_ml/server.py", line 119, in main
    create_dir(args)

  File "/home/j/Documents/dogscats/label-studio-ml-backend/label_studio_ml/server.py", line 79, in create_dir
    model_class = model_classes[0]

IndexError: list index out of range
```

**Comment by KonstantinKorotaev** [comment]
Hi @John-Polo 
Did you modify the example?
If yes, could you please provide the code of your model?

**Comment by John-Polo** [comment]
Hi @KonstantinKorotaev . I did not modify anything. This is all the code I have used so far:

```
# Delete old directory
rm -r mmdetection*

# Delete old environment
conda env remove --name mmlab

conda create --name mmlab

conda activate mmlab

pip install mmcv
# I'm using CPU because I don't have GPU capability
conda install pytorch-cpu==1.10.0

conda install torchvision-cpu

git clone -b fix/mmdetection-blog https://github.com/heartexlabs/label-studio-ml-backend.git

cd label-studio-ml-backend

# Install label-studio-ml and its dependencies
pip install -U -e .

# Install example dependencies
pip install -r label_studio_ml/examples/requirements.txt

git clone https://github.com/open-mmlab/mmdetection.git
# I get the following error here. This is not the error that I mentioned in previous comment.
"ERROR: Could not find a version that satisfies the requirement torch==1.5.0 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1)
ERROR: No matching distribution found for torch==1.5.0"

cd mmdetection

pip install -r requirements/build.txt

conda install pyyaml

conda install requests'<3,>=2.22.0'

conda install urllib3'<1.27,>=1.25.4'

pip install "git+https://github.com/cocodataset/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"

pip install -v -e .

label-studio-ml init coco-detector --from label_studio_ml/examples/mmdetection/mmdetection.py
# Error stacktrace in previous comment shows here.
```

**Comment by KonstantinKorotaev** [comment]
Could you please change **pip install mmcv** to 
pip install mmdet==2.6.0 & mmcv-full==1.2.0
?

**Comment by John-Polo** [comment]
Hi @KonstantinKorotaev . 

I tried two ways. 
First, I used this:
```
#conda env remove --name mmlab
#conda create --name mmlab

conda activate mmlab

pip install mmdet==2.6.0

pip install mmcv-full==1.2.0

conda install pytorch-cpu==1.10.0

conda install torchvision-cpu

git clone -b fix/mmdetection-blog https://github.com/heartexlabs/label-studio-ml-backend.git

cd label-studio-ml-backend

# Install label-studio-ml and its dependencies
pip install -U -e .

# Install example dependencies
pip install -r label_studio_ml/examples/requirements.txt

git clone https://github.com/open-mmlab/mmdetection.git

cd mmdetection

pip install -r requirements/build.txt


pip install "git+https://github.com/cocodataset/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"

pip install -v -e .

label-studio-ml init coco-detector --from label_studio_ml/examples/mmdetection/mmdetection.py
```
and got the error:

> Successfully installed mmdet
> Traceback (most recent call last):
>   File "/home/nightjar/miniconda3/envs/mmlab/bin/label-studio-ml", line 33, in <module>
>     sys.exit(load_entry_point('label-studio-ml', 'console_scripts', 'label-studio-ml')())
>   File "/home/nightjar/Documents/dvc/dogs-vs-cats/label-studio-ml-backend/label_studio_ml/server.py", line 119, in main
>     create_dir(args)
>   File "/home/nightjar/Documents/dvc/dogs-vs-cats/label-studio-ml-backend/label_studio_ml/server.py", line 79, in create_dir
>     model_class = model_classes[0]
> IndexError: list index out of range
> 

I also tried slight different install. I thought the new packages you suggested (mmdet 2.6.0 and mmc-full) were maybe supposed to replace the lines with "##", so those lines were excluded in this attempt:
```
conda create --name mmlab2

conda activate mmlab2

pip install mmdet==2.6.0

pip install mmcv-full==1.2.0

conda install pytorch-cpu==1.10.0

conda install torchvision-cpu

git clone -b fix/mmdetection-blog https://github.com/heartexlabs/label-studio-ml-backend.git

cd label-studio-ml-backend

# Install label-studio-ml and its dependencies
pip install -U -e .

# Install example dependencies
pip install -r label_studio_ml/examples/requirements.txt

##Left these out in this attempt
##git clone https://github.com/open-mmlab/mmdetection.git

##cd mmdetection

##pip install -r requirements/build.txt


pip install "git+https://github.com/cocodataset/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI"

pip install -v -e .

label-studio-ml init coco-detector --from label_studio_ml/examples/mmdetection/mmdetection.py
```
That returns this:

> Successfully installed label-studio-ml
> Can't import module "mmdetection", reason: No module named 'mmcv._ext'.
> If you are looking for examples, you can find a dummy model.py here:
> https://labelstud.io/tutorials/dummy_model.html

**Comment by KonstantinKorotaev** [comment]
Do you have an option to use docker instead of local installation?
Just run **docker-compose up -d** in label_studio_ml/examples/mmdetection/ and you will get ML backend on port 9090.

**Comment by John-Polo** [comment]
@KonstantinKorotaev , thanks for the suggestion. It's been a pain for me to get docker set up on Slackware. I searched and it looks like I can run docker from inside Python. I am going to try to run docker there, because the standalone docker won't install for me.

**Comment by John-Polo** [comment]
HI @KonstantinKorotaev . I tried to install docker, but Slackware says there is a dependency necessary that is not available for the version I'm on, so standalone docker doesn't work for me. I am going to try to run it through Python.

**Comment by John-Polo** [comment]
Happy new year, @KonstantinKorotaev. I got docker to work and it looks like the install works. Thanks for your help.
