### ISSUE TITLE
Video Timeline:- video with no audio 

### ISSUE THREAD

**Issue by NitinKhandelwal1947** [heartexlabs/label-studio#1837]
Want to annotate a video which doesn’t have audio. When we open the task a pop-up error appears with below description .

_Error while loading audio. Check $videoSource field in task.
Technical description: Error decoding audiobuffer_

<img width="468" alt="Screenshot 2021-12-12 at 5 16 37 PM" src="https://user-images.githubusercontent.com/25168555/145711103-138b474b-9c48-4a33-aabf-381cfb3d8a1b.png">

The config we are using is...
<img width="698" alt="Screenshot 2021-12-12 at 5 23 19 PM" src="https://user-images.githubusercontent.com/25168555/145711069-d07ebadf-eb5a-47d9-a9a8-458d18eb2a20.png">

Is there any way to remove the pop-up error.

**Comment by makseq** [comment]
@NitinKhandelwal1947 It's not possible to do segmentation without audio, because this type of labeling is based on the audiowave. The fastest way to fix it is to convert your videos and include silence inside:
```
ffmpeg -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -i video.mov -c:v copy -c:a aac -shortest output.mov
```

btw: we are releasing video labeling soon, so there you will be able to this without audio track.

**Comment by RafayAK** [comment]
> btw: we are releasing video labeling soon, so there you will be able to this without audio track.


Hi, @makseq has this been merged? I can't find any documentation regarding this 

I'm looking to use Label Studio to annotate actions in a video. For example:
```
filename  label(Action)  start_frame  end_frame
vid1.mp4              1                   0           100
vid1.mp4              2                 100         150
vid2.mp4              3                   0           50
```

**Comment by makseq** [comment]
Hi, please check this post: https://labelstud.io/blog/label-studio-1-6-video-object-tracking-and-new-annotation-ui/
