### ISSUE TITLE
Exception in Export to YOLO

### ISSUE THREAD

**Issue by zbyte** [heartexlabs/label-studio#1841]
**Describe the bug**

**To Reproduce**
1. Go to Project
2. Click on Export
3. Select format YOLO
4. After some seconds have exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/data_export/api.py", line 181, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "/label-studio/label_studio/data_export/models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter/converter.py", line 174, in convert
    self.convert_to_yolo(input_data, output_data, output_image_dir=image_dir,
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter/converter.py", line 597, in convert_to_yolo
    category_name = label['rectanglelabels'][0]
IndexError: list index out of range
```

**Expected behavior**
zip file with exported labels downloaded

**Environment (please complete the following information):**
 - OS: docker
 - Label Studio Version 1.4

**Comment by zbyte** [comment]
Export to Pascal VOC XML shutdown to:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/data_export/api.py", line 181, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "/label-studio/label_studio/data_export/models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter/converter.py", line 178, in convert
    self.convert_to_voc(input_data, output_data, output_image_dir=image_dir, is_dir=is_dir)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter/converter.py", line 733, in convert_to_voc
    name = bbox[key][0]
IndexError: list index out of range
```

**Comment by makseq** [comment]
@zbyte This can happen when your annotations have empty labeling results (submitted with empty annotation). However this shouldn't affect the export, you are right. I've created a ticket about this.

**Comment by zbyte** [comment]
How can i delete this annotaions?

**Comment by zbyte** [comment]
i found wrong task, why such a task appeared, I do not know:

```
{
   "cancelled_annotations":0,
   "completed_at":"2021-12-12T20:49:42.232427Z",
   "created_at":"2021-10-26T17:01:13.125405Z",
   "annotations_results":"[{id:O7m_2p1Mcb, type:rectanglelabels, value:{x:44.14, y:9.44, width:6.8, height:17.5, rotation:0, rectanglelabels:[]}, origin:manual, to_name:image, from_name:label, image_rotation:0, original_width:1280, original_height:720},{id:ro4IVnAKfq, type:rectanglelabels, value:{x:43.83, y:10.14, width:8.83, height:19.17, rotation:0, rectanglelabels:[People]}, origin:manual, to_name:image, from_name:label, image_rotation:0, original_width:1280, orig",
   "data":{
      "image":"/data/local-files/?d=educations_images/20210828_1300/v_20211026170001773.png"
   },
   "id":14287,
   "predictions_results":"",
   "predictions_score":"None",
   "total_annotations":1,
   "total_predictions":0,
   "annotations_ids":"16762",
   "annotations":[
      {
         "id":16762,
         "created_username":" vvictorov@itgroup42.com, 5",
         "created_ago":"1\\xa0day, 13\\xa0hours",
         "result":[
            {
               "id":"O7m_2p1Mcb",
               "type":"rectanglelabels",
               "value":{
                  "x":44.140625,
                  "y":9.444444444444445,
                  "width":6.796874999999998,
                  "height":17.5,
                  "rotation":0,
                  "rectanglelabels":[
                     
                  ]
               },
               "origin":"manual",
               "to_name":"image",
               "from_name":"label",
               "image_rotation":0,
               "original_width":1280,
               "original_height":720
            },
            {
               "id":"ro4IVnAKfq",
               "type":"rectanglelabels",
               "value":{
                  "x":43.828125,
                  "y":10.13888888888889,
                  "width":8.828125,
                  "height":19.166666666666668,
                  "rotation":0,
                  "rectanglelabels":[
                     "People"
                  ]
               },
               "origin":"manual",
               "to_name":"image",
               "from_name":"label",
               "image_rotation":0,
               "original_width":1280,
               "original_height":720
            },
            {
               "id":"FQ3XVPjZ2Y",
               "type":"rectanglelabels",
               "value":{
                  "x":86.25,
                  "y":0,
                  "width":7.265625000000002,
                  "height":35.69444444444444,
                  "rotation":0,
                  "rectanglelabels":[
                     "People"
                  ]
               },
               "origin":"manual",
               "to_name":"image",
               "from_name":"label",
               "image_rotation":0,
               "original_width":1280,
               "original_height":720
            },
            {
               "id":"1Lko1j7WiU",
               "type":"rectanglelabels",
               "value":{
                  "x":6.25,
                  "y":9.583333333333334,
                  "width":5.390625,
                  "height":21.38888888888889,
                  "rotation":0,
                  "rectanglelabels":[
                     "People"
                  ]
               },
               "origin":"manual",
               "to_name":"image",
               "from_name":"label",
               "image_rotation":0,
               "original_width":1280,
               "original_height":720
            },
            {
               "id":"lb8_0enwC2",
               "type":"rectanglelabels",
               "value":{
                  "x":0,
                  "y":20.416666666666668,
                  "width":5.625,
                  "height":22.5,
                  "rotation":0,
                  "rectanglelabels":[
                     "People"
                  ]
               },
               "origin":"manual",
               "to_name":"image",
               "from_name":"label",
               "image_rotation":0,
               "original_width":1280,
               "original_height":720
            },
            {
               "id":"vXXpS65yw8",
               "type":"rectanglelabels",
               "value":{
                  "x":2.8125,
                  "y":10.555555555555555,
                  "width":3.203124999999999,
                  "height":7.2222222222222205,
                  "rotation":0,
                  "rectanglelabels":[
                     "People"
                  ]
               },
               "origin":"manual",
               "to_name":"image",
               "from_name":"label",
               "image_rotation":0,
               "original_width":1280,
               "original_height":720
            }
         ],
         "was_cancelled":false,
         "ground_truth":false,
         "created_at":"2021-12-12T20:49:42.232427Z",
         "updated_at":"2021-12-12T20:49:42.232441Z",
         "lead_time":30.832,
         "task":14287,
         "completed_by":5,
         "parent_prediction":"None",
         "parent_annotation":"None"
      }
   ],
   "predictions":[
      
   ],
   "drafts":[
      
   ],
   "file_upload":"None",
   "annotators":[
      5
   ],
   "project":1,
   "predictions_model_versions":""
}
```

**Comment by makseq** [comment]
@zbyte could you share your labeling config?

**Comment by zbyte** [comment]
config:

```
<View>
  <Image name="image" value="$image" maxWidth="100%" zoom="true" crosshair="true"/>
  <RectangleLabels name="label" toName="image">
    <Label value="People" background="#ff0000"/>
    <Label value="Basket" background="#00ff40"/>
    <Label value="Bag" background="#0000e1"/>
  </RectangleLabels>
</View>
```

**Comment by zbyte** [comment]
config not edited after we start labeling. New Label classes not deleted/added.

**Comment by 759852125** [comment]
I also had this export problem

> 我们开始标记后未编辑配置。未删除/添加新标签类别。

**Comment by 759852125** [comment]
> @zbyte你能分享你的标签配置吗？

@makseq 

I have also encountered this problem, currently unable to export, please solve this as soon as possible, if you need remote assistance to understand the problem, you can provide your contact information, I provide remote information for you to remotely understand the problem or debug

**Comment by makseq** [comment]
@759852125 Do you know how to create an annotation with empty "rectanglelabels"?

**Comment by 759852125** [comment]
> @759852125你知道如何用空的“矩形标签”创建注释吗？

Sorry i don't know
@makseq

**Comment by 759852125** [comment]
> @759852125你知道如何用空的“矩形标签”创建注释吗？

According to my investigation, I found in \Lib\site-packages\label_studio_converter\converter.py that the error location is about line 602 code: category_name = label['rectanglelabels'][0], the subscript is out of bounds, according to The sequence number at the end of the abnormal file name is: 13
So I went to /projects/1/data?tab=1&task=13 to check my tag label and found that there was no problem

![image](https://user-images.githubusercontent.com/54934866/147367837-230fded0-9921-4690-adc7-7a9446c0653d.png)
![image](https://user-images.githubusercontent.com/54934866/147367873-bb0eb32a-a9bb-44b6-882d-fa7527b08038.png)
![image](https://user-images.githubusercontent.com/54934866/147367881-9f97722f-22ba-474d-bd45-8fee5269b716.png)

The guess may be that there is a small problem with the db storage, this is just my guess

in addition 
https://browser.sentry-cdn.com/5.17.0/bundle.min.js
Please use the local path instead. This domain name does not seem to be very friendly to mainland China, which will make the localhost:8080 access very slow

The above content is translated from Google Translate to English, and the translation may be improper and inaccurate.


@makseq

**Comment by makseq** [comment]
@759852125 Thank your for your investigation! You are right, the final error happened in the place you showed. However the origin problem happens somewhere in the frontend (`"rectanglelabels": [ ]`) and we don't know how to reproduce this problem.

**Comment by 759852125** [comment]
> @759852125感谢您的调查！你是对的，最后的错误发生在你展示的地方。然而，起源问题发生在前端的某个地方（`"rectanglelabels": [ ]`- 结果中没有标签），我们不知道如何重现这个问题。

I can provide you with a data set, do you need it? @makseq

**Comment by 759852125** [comment]
> @759852125感谢您的调查！你是对的，最后一个错误发生在你展示的地方。然而，起源问题发生在前端的某个地方（`"rectanglelabels": [ ]`- 结果中没有标签），我们不知道如何重现这个问题。

I provide you with my archive, Stored in AppData\Local\label-studio @makseq 
[label-studio.zip](https://github.com/heartexlabs/label-studio/files/7775549/label-studio.zip)

**Comment by 759852125** [comment]
> @759852125感谢您的调查！你是对的，最后一个错误发生在你展示的地方。然而，起源问题发生在前端的某个地方（`"rectanglelabels": [ ]`- 结果中没有标签），我们不知道如何重现这个问题。

![image](https://user-images.githubusercontent.com/54934866/147379505-a4006576-3a59-4940-acf7-1cd4638fd487.png)
I found something that seemed to be missing when producing json in the label studio. It may have been concluded that there was an error in producing the json file. @makseq

**Comment by 759852125** [comment]
> @759852125感谢您的调查！你是对的，最后一个错误发生在你展示的地方。然而，起源问题发生在前端的某个地方（`"rectanglelabels": [ ]`- 结果中没有标签），我们不知道如何重现这个问题。

![image](https://user-images.githubusercontent.com/54934866/147379629-338fcfba-3141-4365-b9f5-c30095daeb1b.png)
@makseq  In the sql repository, it is found that Json is no problem, so it may be caused by json generation.

**Comment by 759852125** [comment]
> @759852125感谢您的调查！你是对的，最后一个错误发生在你展示的地方。然而，起源问题发生在前端的某个地方（`"rectanglelabels": [ ]`- 结果中没有标签），我们不知道如何重现这个问题。
@makseq 
![image](https://user-images.githubusercontent.com/54934866/147380054-7b8051fe-04cf-4eb7-b72e-96a40d9cc3c0.png)
The following figure shows the json in the database is eight normal tags
After comparison, I only have eight labels in this picture, but when the Json file is generated
(From label_studio/data_export/api.py: about 175 [tasks += ExportDataSerializer(self.get_task_queryset(query.filter(id__in=_task_ids)), many=True,expand=['drafts']).data])
Nine labels are generated, and the extra label is "rectanglelabels": []

**Comment by 759852125** [comment]
> > @759852125感谢您的调查！你是对的，最后一个错误发生在你展示的地方。然而，起源问题发生在前端的某个地方（`"rectanglelabels": [ ]`- 结果中没有标签），我们不知道如何重现这个问题。
> > @makseq
> > ![图片](https://user-images.githubusercontent.com/54934866/147380054-7b8051fe-04cf-4eb7-b72e-96a40d9cc3c0.png)
> > The following figure shows the json in the database is eight normal tags
> > After comparison, I only have eight labels in this picture, but when the Json file is generated
> > (From label_studio/data_export/api.py: about 175 [tasks += ExportDataSerializer(self.get_task_queryset(query.filter(id__in=_task_ids)), many=True,expand=['drafts']).data])
> > Nine labels are generated, and the extra label is "rectanglelabels": []

The number I marked is also eight tags
![image](https://user-images.githubusercontent.com/54934866/147380102-383c49bc-a3e5-4190-8dec-311b5b02b57b.png)

**Comment by 759852125** [comment]
![image](https://user-images.githubusercontent.com/54934866/147380137-12d4def6-d9ab-4304-b54e-582a71d16768.png)
This picture shows that the number of Json generated is nine labels, one of which is an incorrect empty label @makseq

**Comment by 759852125** [comment]
According to my recollection, there may be an inaccurate label in the box position that was removed at the time, and then a new box label was redrawn. It may be that the deletion of the label caused this problem. @makseq

**Comment by 759852125** [comment]
it turns out that it is a useless label, so I temporarily added a judgment to deal with my own export problem first, but please your check the root cause in more detail. I am not a suitable programmer.
![image](https://user-images.githubusercontent.com/54934866/147380266-b1476f28-ab47-414a-a41b-c5240c5c094b.png)

**Comment by makseq** [comment]
I've tried to reproduce this due to label deletion, but not luck yet.. If you find steps how to repeat this bug, please share their asap!

**Comment by 759852125** [comment]
> 由于标签删除，我已尝试重现此问题，但还没有运气。如果您找到如何重复此错误的步骤，请尽快分享！

![image](https://user-images.githubusercontent.com/54934866/147538190-60dc5762-7193-413e-80f6-9bc5c8d85b2a.png)
You download this file and put it in the specified path to reproduce the problem of exporting my data set @makseq

**Comment by makseq** [comment]
This is not a root of the problem. We have to reproduce it in the labeling editor during the labeling process.

**Comment by 759852125** [comment]
> 不幸的是，这不是问题的根源。我们必须在标注过程中在标注编辑器中重现它。

Unfortunately, this may be a probability problem, and I don't even know how to trigger it. @makseq      May not help you

**Comment by thehappy1** [comment]
Hey I experienced the same issue. 
How did you fix that? 
I can't find the empty annotation result in my data.

**Comment by 759852125** [comment]
> 嘿，我遇到了同样的问题。 你是怎么解决的？ 我在数据中找不到空注释结果。

https://github.com/heartexlabs/label-studio/issues/1841#issuecomment-1000986987


Please check my reply and modify the code I marked

**Comment by thehappy1** [comment]
Thank you. With that I could bypass the exception.

**Comment by makseq** [comment]
I've added a very similar [checks to the converter](https://github.com/heartexlabs/label-studio-converter/commit/f620dfb42b7958d98044c5ceab5abf7da55552a0) like in #1841 (comment). It should help.

**Comment by jaredswanson** [comment]
I had the same issue exporting a COCO file. Solved it pretty quick with a ruby script. Hope this helps.
Note: you will need to have Ruby installed.

Export the broken list as JSON-MIN
![image](https://user-images.githubusercontent.com/38188491/152164432-df916668-3309-4ebe-9adc-5b9201ea6d3c.png)

Drop this ruby script in the same directory as the exported json file (name it find_empty_rectanglelabels.rb)
```
require 'json'

json_files = Dir.glob(Dir.pwd + "/*.json")
file = json_files.first
images = JSON.parse(File.read(file))

images.each do |image|
  labels = image["label"]
  labels.each do |label|
    if label["rectanglelabels"] == "" || label["rectanglelabels"].empty?
      p "Empty rectangle labels found in image: #{image["id"]}"
    end
  end
end
```

Run the script
`ruby find_empty_rectanglelabels.rb`
-> Spits out the ID of the offending rectangle
![image](https://user-images.githubusercontent.com/38188491/152166635-e2e3cf66-0b73-4b2c-9ef1-060d66b091e9.png)

Search for the image by ID
![image](https://user-images.githubusercontent.com/38188491/152165248-9a3b633e-6f85-4e6d-86eb-c143bf2d1af1.png)

Open the image in Label Studio

Look down the Regions/Labels bar for an empty label
![image](https://user-images.githubusercontent.com/38188491/152165543-bfeed7d3-e176-479c-ba77-ace9804c175a.png)

Click on the empty label (to select) > Backspace (to delete)

Scan the list again to make sure you deleted all of the empty labels.

Try exporting again.

**Comment by sanatsingh** [comment]
A python version of the same script incase you don't have R

```
import json
import pandas as pd
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Script to find Annotation IDs with bugs in label studio. Prereq: Export annotations as CSV')
    parser.add_argument('-f','--file_path', help='File path of CSV file', required=True)
    args = vars(parser.parse_args())

    df = pd.read_csv(args['file_path'])
    
    print('Annotation ID\'s with bugged out empty labels:-')
    for idx, row in df.iterrows():
        annot_l = json.loads(row['label'])
        for annot in annot_l:
            if annot["rectanglelabels"] == []:
                print(row['id'])
```
Run using:-
```
python .\<scriptfile> -f <csv_file path>
```

**Comment by makseq** [comment]
Please try to use `label-studio==1.4.1rc1`, this issues must be fixed starting from this LS version.
