### ISSUE TITLE
Option for Train-Validation-Test Split

### ISSUE THREAD

**Issue by GeorgeVJose** [heartexlabs/label-studio#1845]
It would be nice if I can set dataset split percents in the UI and the exporting takes care of it.

**Comment by rgaiacs** [comment]
Any update on this?

**Comment by makseq** [comment]
@GeorgeVJose @rgaiacs 
I've implemented `Add or Modify Data Field` action for the Data Manager:
https://github.com/heartexlabs/label-studio/pull/2558

1. Install LS from the latest develop branch.

2. Run LS with environment variable EXPERIMENTAL_FEATURES=1:
```
EXPERIMENTAL_FEATURES=1 label-studio
```

3. Now you can select all tasks and run `Add or Modify Data Field` action, then use 
```
choices(['train', 'test', 'valid'], [0.9, 0.05, 0.05]) 
```
as the expression. 

![image](https://user-images.githubusercontent.com/501780/175720466-8ab376c1-252d-4123-818c-2b16e7b8d27c.png)

**Comment by luccahuguet** [comment]
hi is this still an experimental feature?

**Comment by 1andDone** [comment]
@makseq does this still work?

**Comment by monurcevik** [comment]
For anyone struggling with the filtering not working or showing inconsistent results, try going to managers.py and passing the "only_undefined_field" parameter as False on preprocess_field_name() function calls. It normally grabs it from the project and I noticed that mine was always True so it was ignoring other custom data fields and filtering on the original "data" field.

**Comment by samuelyys** [comment]
Is there any (simple) way to change the split value (e.g. from "train" to "valid") for a particular task?

**Comment by wegerhoff** [comment]
Works fine for me. Why is this feature still experimental?
