### ISSUE TITLE
Data manager crashes when audio file has duration Infinity

### ISSUE THREAD

**Issue by simonlsk** [heartexlabs/label-studio#1846]
**Describe the bug**
Data manager crashes when trying to play audio inline (without entering the label-studio-frontend). This happens when the file is served without support for range requests for example.

**To Reproduce**
A bit hard to reproduce without a special setup. But it can be simulated.
In dm2:
Call `<Duration>` in `AudioPlayer` while passing `Infinity` as the duration.

**Expected behavior**
The inline audio player loads the audio and plays it

**Environment (please complete the following information):**
 - OS: MacOS
 - Label Studio Version 1.4

**Comment by simonlsk** [comment]
Open PR - https://github.com/heartexlabs/dm2/pull/27

**Comment by nicholasrq** [comment]
the PR in Data Manager is merged, thank you for the fix. it'll be added to Label Studio soon
