### ISSUE TITLE
Video timeline: On clicking Play button only audio wave is playing not the video in video-player

### ISSUE THREAD

**Issue by NitinKhandelwal1947** [heartexlabs/label-studio#1850]
On clicking Play button only audio wave is playing not the video in video-player.
<img width="1002" alt="Screenshot 2021-12-16 at 11 38 18 AM" src="https://user-images.githubusercontent.com/25168555/146317598-83a7ba42-54fd-44de-ac1e-ec06344ca346.png">

We are using **0.7.5** version of label studio and we are using config like below...

<img width="682" alt="Screenshot 2021-12-16 at 11 40 17 AM" src="https://user-images.githubusercontent.com/25168555/146317798-544592ae-1ef8-4afd-84cb-ba85ba15a3c5.png">

And the Input Preview is like below...

```
{
    "video": "<video src='https://app.heartex.ai/static/samples/opossum_snow.mp4' width=100% muted /><img src onerror=\"$=n=>document.getElementsByTagName(n)[0];a=$('audio');v=$('video');a.onseeked=()=>{v.currentTime=a.currentTime};a.onplay=()=>v.play();a.onpause=()=>v.pause()\" />",
    "videoSource": "https://app.heartex.ai/static/samples/opossum_snow.mp4"
}
```

**Comment by makseq** [comment]
This version of LS is very old and is not supported. 

Usually this problem happened when video is not fully loaded.
