### ISSUE TITLE
What kind of export method is the data set format of this folder form?

### ISSUE THREAD

**Issue by 759852125** [heartexlabs/label-studio#1851]
![image](https://user-images.githubusercontent.com/54934866/146358438-cafe89af-cbeb-415d-a888-0137def73aa1.png)
![image](https://user-images.githubusercontent.com/54934866/146358560-91e28400-4cb1-4bdf-9fd4-6961aebf0880.png)

![image](https://user-images.githubusercontent.com/54934866/146358591-6798817e-86bf-45a2-8713-ca6188b3ea6e.png)

**Comment by makseq** [comment]
@759852125 Could you show what is inside of JSON? It could be JSON, JSON-MIN, COCO. 
If you see "annotations", "data", "predictions" keys that are dicts, it should be JSON.

**Comment by 759852125** [comment]
> @759852125你能展示一下 JSON 里面有什么吗？它可以是 JSON、JSON-MIN、COCO。 如果您看到作为字典的“注释”、“数据”、“预测”键，则它应该是 JSON。

![image](https://user-images.githubusercontent.com/54934866/146528268-8f77ee89-5331-456b-9663-189c5e223a95.png)
![image](https://user-images.githubusercontent.com/54934866/146528282-d9596836-bac5-498b-b0ef-9328bb44f183.png)

**Comment by makseq** [comment]
This is a COCO format.

**Comment by 759852125** [comment]
1
