### ISSUE TITLE
Docker build fails on MacOS and docker 20.10.11

### ISSUE THREAD

**Issue by simonlsk** [heartexlabs/label-studio#1859]
**Describe the bug**
Docker build fails on a fresh cloned directory of label-studio. 

**To Reproduce**
1. Clone label-studio from github
2. Run from directory: `docker build --tag label-studio .`

**Expected behavior**
docker build succeeds

**Screenshots**
Output of docker build:
```
 => [stage-0 7/9] COPY . /label-studio                                                                                                                                          0.0s
 => ERROR [stage-0 8/9] RUN python3.8 setup.py develop                                                                                                                          0.4s
------
 > [stage-0 8/9] RUN python3.8 setup.py develop:
#16 0.401 Traceback (most recent call last):
#16 0.401   File "setup.py", line 18, in <module>
#16 0.401     print(label_studio.package_name, label_studio.__version__)
#16 0.401 AttributeError: module 'label_studio' has no attribute 'package_name'
------
error: failed to solve: executor failed running [/bin/sh -c python3.8 setup.py develop]: exit code: 1
```

**Environment (please complete the following information):**
 - OS: MacOS 12.0.1 (intel)
 - Label Studio Version: 1.4
 - Docker version: 20.10.11, build dea9396

**More context**
Seems like `.dockerignore` is preventing docker from copying `label_studio`'s directory content. This might be a docker issue, in such a case, it would be nice to have a compatibility requirement in the readme.

**Comment by makseq** [comment]
@simonlsk Could you please pull the latest LS master and try to build docker again?

**Comment by simonlsk** [comment]
Hey, thanks for the quick response and fix!
I still need to do the following change in `.dockerignore`:
`!label_studio` => `!label_studio/**`
But this time it works! 

As far as I am concerned you can close the issue.
Thanks again!

**Comment by makseq** [comment]
@simonlsk Thanks for the feedback! We checked your notes about dockerignore and we couldn't reproduce this problems.

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio/pull/1868#pullrequestreview-838913993

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio/pull/1868/files
