### ISSUE TITLE
Text Labeling. Updating a task removes all newlines from labeled text

### ISSUE THREAD

**Issue by aristizabal95** [heartexlabs/label-studio#1863]
**Describe the bug**
When working on a text labeling project, the task source keeps a record of the text that accompanies a label. When a task is labeled for the first time, this portion of text retains newlines. But, when doing any update to the task (even an update with no changes) then newlines are removed from all labeled substrings

**To Reproduce**
1. Add and annotate a text labeling task
2. Check the task source and see that newlines are kept inside labeled text
3. Open the task and click update
4. Check the task source again. Now labeled text has no newlines

**Expected behavior**
Text should retain newlines after any update. Blank updates should not modify the task source in any way.

**Screenshots**
[Comparison of task source output before/after udpate](https://imgur.com/a/QgzGTMk)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version 1.4

**Additional context**
This could be related to #487

**Comment by superdev808** [comment]
@aristizabal95 The above issue is resolved in latest master branch. Please test it again. Thanks
