### ISSUE TITLE
Pairwise image labeling only allows right selection

### ISSUE THREAD

**Issue by rvandevijver** [heartexlabs/label-studio#1864]
**Problem**
When trying pairwise image comparison on the playground, only the right image can be selected.

**Minimal example of the labeling config**
```
<View>
  <Pairwise name="pw" toName="txt-1,txt-2" />
  <Image name="txt-1" value="$text1" />
  <Image name="txt-2" value="$text2" />
</View>
```
Or in the playground using [this link](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CPairwise%20name%3D%22pw%22%20toName%3D%22txt-1%2Ctxt-2%22%20%2F%3E%3Cbr%3E%20%20%3CImage%20name%3D%22txt-1%22%20value%3D%22%24text1%22%20%2F%3E%3Cbr%3E%20%20%3CImage%20name%3D%22txt-2%22%20value%3D%22%24text2%22%20%2F%3E%3Cbr%3E%3C%2FView%3E)
Anyone any idea what could be the cause of this and how it could be solved? Thanks!

**Comment by makseq** [comment]
@rvandevijver The playground uses a very ancient version of LS. In the LS 1.4 I couldn't reproduce this bug.

**Comment by makseq** [comment]
Feel free to re-open if you can reproduce it in LS 1.4.
