### ISSUE TITLE
Local storage import sync getting timed out

### ISSUE THREAD

**Issue by shreyjasuja** [heartexlabs/label-studio#1873]
**local import storage is not getting synced**

I mounted the local storage I tried to run it for 500 tasks it worked successfully but when I put in like 1,500,000 tasks in the same folder the sync is getting failed.

**Comment by makseq** [comment]
@shreyjasuja LS doesn't use any background process to scan the local storage. You should prepare import JSON file [according this recommendation](https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references) manually.

**Comment by makseq** [comment]
Also I recommend to switch to the latest master from github, because we've fixed critical issue with Local Storages there.

**Comment by makseq** [comment]
Feel free to reopen this issue if the issue persists.
