### ISSUE TITLE
Order by image option

### ISSUE THREAD

**Issue by magicaltoast** [heartexlabs/label-studio#1883]
**Describe the bug**
Ability to order by image, what even means order by image. 
How to compare if a image is greater or less than another image

**To Reproduce**
1. Import any image data
2. Go to task viewer

**Expected behavior**
Don't show the image as a sorting option or describe how ordering by image works

**Screenshots**
![Screenshot from 2021-12-29 00-26-05](https://user-images.githubusercontent.com/68669235/147614442-041ded74-6532-4f7a-8e89-559cb06d151d.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version 1.4

**Comment by makseq** [comment]
This ordering is done by the data column from your imported tasks. The data manager displays images here instead of strings for your convenience, so I'm not sure if we would like to change this...

How would you suggest to fix it?
