### ISSUE TITLE
[bug] LocalStorage becomes query string instead of absolute path

### ISSUE THREAD

**Issue by nickvazz** [heartexlabs/label-studio#1886]
**Describe the bug**
Video path changes when using local storage to query string?

**Expected behavior**
It should use the absolute path of the uploaded "cloud" data source

**Screenshots**
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/8573886/147795818-4114b4ec-28ae-4e48-b217-61fa8eb3857f.png">

<img width="628" alt="image" src="https://user-images.githubusercontent.com/8573886/147795837-64f0b417-35d1-4a9c-9647-5005f1164204.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/8573886/147795862-9b9fd64a-df70-4cc0-8fda-07c314b862d6.png">

```bash
sudo docker run -itd -p 8080:8080 -v `pwd`/data:/label-studio/stuff --env LOCAL_FILES_DOCUMENT_ROOT=/label-studio/stuff/ --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true heartexlabs/label-studio:latest label-studio
```

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8573886/147795905-f979858e-8612-442f-a032-24d27ffd11cc.png">

**Environment (please complete the following information):**
 - OS: Docker on linux
 - Label Studio Version 1.4

**Comment by nickvazz** [comment]
@makseq any idea what is going on?

**Comment by triklozoid** [comment]
Can you share your label config, please? 
And can you try open manually url with file? Should be http://localhost:8080/data/local-files/?d=video_chunks/Am_Scramble_2018_Video_output_0019.mp4

**Comment by nickvazz** [comment]
Did not appear to fix the issue :/

**Comment by makseq** [comment]
@nickvazz if you are talking about spaces in "Absolute local path", then yes, spaces could affect it.
