### ISSUE TITLE
--host parameter causes a web page 404 error

### ISSUE THREAD

**Issue by luxiangx** [heartexlabs/label-studio#1889]
**Describe the bug**
Due to project requirements, different prefixes need to be used to distinguish different services. After reading the label studio document, we have tried to use the -- host parameter or LABLE_ STUDIO_ HOST environment, such as -- host http://127.0.0.1:8081/label-studio. However, the label studio background does not recognize the URL request, and return 404 error.

**To Reproduce**
1. run server.py with --host parameter.
2. Open label-studio url page

**Screenshots**
<img width="578" alt="image" src="https://user-images.githubusercontent.com/21304579/147932739-8416e19d-f27b-45e8-a398-c106de08ff48.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/21304579/147933228-ab99677e-af25-4069-a7de-574ef2e35b15.png">
<img width="920" alt="image" src="https://user-images.githubusercontent.com/21304579/147933330-daeeaf99-adff-432a-9fb9-ff229268cf8c.png">

**Environment (please complete the following information):**
 - MacOS
 - Label Studio Version [maser]

**Additional context**
We also tried to use nginx configuration, but it didn't work.

**Comment by makseq** [comment]
@luxiangx you should run LS using docker, because there must be properly configure Nginx over LS

**Comment by lfoppiano** [comment]
@makseq I'm trying to run LS using docker, and then configure a reverse proxy on top of it, however I don't manage to get the LABEL_STUDIO_HOST to be taken in account. I tried: 

```
[Luca@falcon label-studio]$ LABEL_STUDIO_HOST=http://falcon.nims.go.jp/label-studio docker run -it -p 8087:8080 -v `pwd`/data:/label-studio/data heartexlabs/label-studio:latest
./deploy/docker-entrypoint.sh: Looking for init scripts in /label-studio/deploy/docker-entrypoint.d/
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/10-copy-static-data.sh
=> Skipping copy data.
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/20-wait-for-db.sh
=> Skipping wait for database.
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/30-run-db-migrations.sh
=> Skipping run db migrations.
./deploy/docker-entrypoint.sh: Configuration complete; ready for start up
=> Database and media directory: /label-studio/data
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 43122
Performing system checks...

System check identified no issues (0 silenced).
January 06, 2022 - 06:08:33
Django version 3.1.14, using settings 'core.settings.label_studio'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
```

however the root path is still / which makes it impossible to use behind a reverse proxy. Same happens if I export the env var before. 

Anything I'm missing?

**Comment by farioas** [comment]
The correct command syntax is:
```
$ docker run -it -p 8087:8080 -e LABEL_STUDIO_HOST=http://falcon.nims.go.jp/label-studio -v `pwd`/data:/label-studio/data heartexlabs/label-studio:latest
./deploy/docker-entrypoint.sh: Looking for init scripts in /label-studio/deploy/docker-entrypoint.d/
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/10-copy-static-data.sh
=> Skipping copy data.
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/20-wait-for-db.sh
=> Skipping wait for database.
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/30-run-db-migrations.sh
=> Skipping run db migrations.
./deploy/docker-entrypoint.sh: Configuration complete; ready for start up
=> Hostname correctly is set to: http://falcon.nims.go.jp/label-studio
```

**Comment by farioas** [comment]
Btw, it will only works with docker-compose and nginx, like it stated in the documentation:
https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-with-a-host-and-sub-path

**Comment by lfoppiano** [comment]
thanks!

**Comment by luxiangx** [comment]
thanks, run docker-compose command works.
