### ISSUE TITLE
the annotation result coordinate/ratio not match the actual ones

### ISSUE THREAD

**Issue by floyddcn** [heartexlabs/label-studio#1897]
**Describe the bug**
the annotation results coordinate/ratio not match the actual ones.
Is all the coords in  result  are ratio value(i guess)? 
Where can i find the document explaining the meaning of the annotation result?

**To Reproduce**
1. annotate some picture
2. click 'show task source' button on the task list page
3. u will see following json not match the pic,and you can just caculate the ratio 0.089(x in result) vs 0.044(ratio by my screen snapshot caculation,and also its the same ratio value in my original PDF file)
`{
  "id": 9,
  "data": {
    "image": "/data/upload/4/624cb493-page1.png"
  },
  "annotations": [
    {
      "id": 4,
      "created_username": " floyddcn@163.com, 1",
      "created_ago": "0 minutes",
      "result": [
        {
          "original_width": 1240,
          "original_height": 1754,
          "image_rotation": 0,
          "value": {
            "x": 8.933333333333332,
            "y": 9.42507068803016,
            "width": 12.133333333333333,
            "height": 3.204524033930255,
 .....
}`
 
![image](https://user-images.githubusercontent.com/48442748/148549490-7e36d4c7-0d7b-4d4c-809f-7b3e29cdb10f.png)

**Expected behavior**
Coordinates in result should be the same as orignal position

**Environment (please complete the following information):**
 - OS: Linux floyd-ubt 5.13.0-16-generic #16-Ubuntu SMP Fri Sep 3 14:53:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 - Label Studio Version 
 `{
  "release": "1.4",
  "label-studio-os-package": {
    "version": "1.4",
    "short_version": "1.4",
    "latest_version_from_pypi": "1.4",
    "latest_version_upload_time": "2021-11-19T15:56:02",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "[workflows] Disable stale@issues. Bump actions versions.",
    "commit": "a5a0a86b76bd93cb9622a5c57c9ad997e632c5c1",
    "date": "2021-11-30 11:27:32 +0400",
    "branch": "master",
    "version": "1.4.0+20.ga5a0a86.dirty"
  },

  "label-studio-frontend": {
    "message": "[fix] keep label selected; order after ctrl+z (#358)  - keep label sel ...",
    "commit": "6494ffaf3cdaf5c2564371a66d809aa50ea3bda0",
    "branch": "master",
    "date": "2021-11-26T16:39:40Z"
  },

  "dm2": {
    "message": "DEV-609: Load task data from server (#22)  * Load task data from serve ...",
    "commit": "feb9f1db923039b098fd0122f3d6a87bdc224a79",
    "branch": "master",
    "date": "2021-11-18T20:01:55Z"
  },

  "label-studio-converter": {
    "version": "0.0.36"
  }
}`

**Other try**
i have tried do export by csv,yolo v3 format,etc.. and the result seem to be the same as 'source'.

**Comment by makseq** [comment]
Check this docs please
https://labelstud.io/guide/export.html#Units-of-image-annotations

**Comment by makseq** [comment]
@floyddcn Do you mean that original_width and original_height are swapped?

**Comment by floyddcn** [comment]
> 

swapped? original width and height is all right(totally same as my uploaded picture). 
But when i caculcate the acutal position in original pic and then draw the bounding box according to your annotation result , the region seems to be inconsistent with the selection in annotation interface. 
Besides,can you give me some clue about the other questions i mentioned before 
`Where can i find the document explaining the meaning of the annotation result? is that a ratio value?(acutal _x_value=x*original_width?) ` Till now,i just figure out all the meaning of the value by myself...

**Comment by smoreface** [comment]
@floyddcn check here: https://labelstud.io/guide/export.html#Units-of-image-annotations

**Comment by floyddcn** [comment]
> @floyddcn check here: https://labelstud.io/guide/export.html#Units-of-image-annotations

As for question 1. i calculdated again,and your result is ok,maybe there is something wrong with my origianl pdf position calculation,sorry for bothering u.

question 2, i'll check it out,thx a lot.

**Comment by ivanlengyel** [comment]
I am having the same issue. Exported values are inconsistent.
#3149
