### ISSUE TITLE
Sequence of labels not maintained 

### ISSUE THREAD

**Issue by ritikajha** [heartexlabs/label-studio#1901]
I have a huge labeling project so I have made multiple projects to complete tasks in parts.
The labels created in each project are same and in the same sequence, but when exported in YOLO format, the sequence in classes.txt file get changed and doesnt remain in a particular sequence.
How can I fix the sequence of labels  while exporting in YOLO format.

**Comment by KonstantinKorotaev** [comment]
Fixed in [1871](https://github.com/heartexlabs/label-studio/issues/1871)
