### ISSUE TITLE
Display the original resolution of the uploaded image

### ISSUE THREAD

**Issue by DimaVinnitsa** [heartexlabs/label-studio#1904]
**Display the original resolution of the uploaded image**

I need to work with the full quality of the picture that I'm uploaded for labeling. 
As I can see this program downgraded the resolution.

**Comment by makseq** [comment]
@DimaVinnitsa Maybe you may use a zoom functionality? 

https://labelstud.io/tags/image.html#main
```
 <Image name="image" value="$url" zoomControl="true"></Image>
```

**Comment by DimaVinnitsa** [comment]
Thank you for your answer.  I've already used zoomControl setting. But it doesn't mean that the quality of the picture will change with this functionality. If you look into the properties of the file before import the image and after - you will see a difference (attached screenshot)
So I need to have image with the same quality as before import it into Labael-studio application. 
Could you help me with it?
![image](https://user-images.githubusercontent.com/45112709/149916846-df64e91f-7447-4cc6-862b-28371d983b04.png)

**Comment by hlomzik** [comment]
Hi, @DimaVinnitsa! We don't do anything with the picture itself, so resolution is the same, sizes on your screenshot is just a styles to fit image to our working area. And that's not the image, that's canvas to display regions, image is in another div.
First of all you should remove our `max-width` limit (`<Image ... maxWidth="auto" />`), we'll fix this in master soon.
Currently we can't display image bigger than viewport, but when you zoom in you'll get the original quality, you can check it in Elements panel (look for `img` tag).
Also you can try to add `<Style>img[alt=LS]{image-rendering: pixelated}</Style>` to config to remove browser's antialiasing on zoom.

**Comment by startjava** [comment]
> maxWidth="auto"

my code：
```
<View>
  <Image name="image" value="$myImageURL" maxWidth="auto"/>
  <Choices name="gender" toName="image" choice="single-radio" layout="inline">
    <Choice alias="1" value="男"/>
    <Choice alias="0" value="女" selected="true"/>
  </Choices>
</View>
```

my jpg width 15000px ,  show result like "fit", why ? i want full quality
