### ISSUE TITLE
Route `/api/storages/export/s3/validate` returns empty body and does nothing

### ISSUE THREAD

**Issue by Fkawala** [heartexlabs/label-studio#1913]
**Describe the bug**
- Route `/api/storages/export/s3/validate` returns empty body / does nothing. The route can be called with wrong credentials but won't raise any exception. To sync the broken storage will fail with a 403 error as expected.

**To Reproduce**
1. Create a s3 export storage from UI or API with wrong credentials
2. Call the /api/storages/export/s3/validate, it'll returns empty body
3. Try to synchronize the same storage, it'll fail

**Expected behavior**
To call `/api/storages/export/s3/validate` with wrong credentials should fails

**Environment (please complete the following information):**
- Official docker image (tag:latest)
- Result of the `/api/version` route

```json{
    "release": "1.4",
    "label-studio-os-package": {
        "version": "1.4",
        "short_version": "1.4",
        "latest_version_from_pypi": "1.4",
        "latest_version_upload_time": "2021-11-19T15:56:02",
        "current_version_is_outdated": false
    },
    "label-studio-os-backend": {
        "message": "[docs] Add tabs support (DEV-1382) (#1872)",
        "commit": "f9d743f669264df706cf5d23cc208326281bc457",
        "date": "2021-12-27 01:46:40 +0300",
        "branch": "master",
        "version": "1.4.0+65.gf9d743f.dirty"
    },
    "label-studio-frontend": {
        "message": "DEV-1312: Fix relations restoration (#389)\n\n* Fix regions tree assembl ...",
        "commit": "d886b810bae4ee0bff3bac884838cae2c1b6f8aa",
        "branch": "master",
        "date": "2021-12-13T15:40:57Z"
    },
    "dm2": {
        "message": "DEV-609: Load task data from server (#22)\n\n* Load task data from serve ...",
        "commit": "feb9f1db923039b098fd0122f3d6a87bdc224a79",
        "branch": "master",
        "date": "2021-11-18T20:01:55Z"
    },
    "label-studio-converter": {
        "version": "0.0.37"
    }
}
```

**Comment by makseq** [comment]
Max Tkachenko commented: test

**Comment by makseq** [comment]
Fixed in https://github.com/heartexlabs/label-studio/pull/4059/files, will be merged soon.
