### ISSUE TITLE
redis and google-api-core version conflict

### ISSUE THREAD

**Issue by ebayo** [heartexlabs/label-studio#1915]
**Describe the bug**
When installing label-studio I get conflicting requirements versions for redis and google-api-core

**To Reproduce**

Just following the pip installation guide from the [documentation](https://labelstud.io/guide/install.html#Install-with-pip)
1. Create virtual environment
```python3 -m venv ~/venv/label-studio-venv/```
2. Activate it
```source ~/venv/label-studio-venv/bin/activate```
3. And install label studio using pip
```pip install label-studio```
4. I see the error:
```
ERROR: django-redis-cache 3.0.0 has requirement redis<4.0, but you'll have redis 4.1.0 which is incompatible.
ERROR: google-cloud-core 1.7.2 has requirement google-api-core<2.0.0dev,>=1.21.0, but you'll have google-api-core 2.4.0 which is incompatible.
```
When trying a compatible version of redis (version 3.3.11) for django-redis-cache 3.0.0, then I get the error: 
```
ERROR: rq 1.10.0 has requirement redis>=3.5.0, but you'll have redis 3.3.11 which is incompatible.
ERROR: label-studio 1.4 has requirement redis>=3.5.0, but you'll have redis 3.3.11 which is incompatible.
```
Label-studio works with this error, but label-studio-ml-backend (following the steps in the [github](https://github.com/heartexlabs/label-studio-ml-backend#quickstart)) doesn't.

When trying ```label-studio-ml init yolov5-backend --script ~/Projects/yolov5-backend/``` I get the error: ```pkg_resources.ContextualVersionConflict: (redis 4.1.0 (~/venv/label-studio-venv/lib/python3.8/site-packages), Requirement.parse('redis<4.0'), {'django-redis-cache'})```

**Expected behavior**
label-studio-ml-backend inits successfully

**Environment (please complete the following information):**
 - Ubuntu 20.04
 - Label Studio Version 1.4

**Comment by KonstantinKorotaev** [comment]
Hi @ebayo 
Could you please try ML backend from [branch fix/HTX-2224-no-ls](https://github.com/heartexlabs/label-studio-ml-backend/tree/fix/HTX-2224-no-ls)?

**Comment by ebayo** [comment]
Hi @KonstantinKorotaev
Using the stated branch I'm able to start the ML backend

**Comment by makseq** [comment]
@ebayo If you problem is solved, please close this issue :slightly_smiling_face:
