### ISSUE TITLE
audio regions sample failing

### ISSUE THREAD

**Issue by saikrishb** [heartexlabs/label-studio#192]
I see the following error message when I submit an [audio regions](https://labelstud.io/templates/audio_regions.html) task. 

> Traceback (most recent call last):
>   File "... /lib/python3.7/site-packages/label_studio/utils/misc.py", line 88, in exception_f
>     return f(*args, **kwargs)
>   File "... /lib/python3.7/site-packages/label_studio/server.py", line 503, in api_completions
>     completion_id = project.save_completion(task_id, completion)
>   File "... lib/python3.7/site-packages/label_studio/project.py", line 435, in save_completion
>     self._update_derived_output_schema(completion)
>   File "... lib/python3.7/site-packages/label_studio/project.py", line 134, in _update_derived_output_schema
>     for label in result['value'][result['type']]:
> KeyError: 'region'

Here is the completion JSON.  
```
completion : [{
    "lead_time": 14.64,
    "result": [
        {
            "id": "NUxI0c4i-5",
            "from_name": "choice",
            "to_name": "audio",
            "type": "choices",
            "value": {
                "choices": [
                    "Pop"
                ]
            }
        },
        {
            "id": "fp_DJje3w_",
            "from_name": "audio",
            "to_name": "audio",
            "source": "$url",
            "type": "region",
            "value": {
                "start": 0.7166073312820513,
                "end": 1.2284697107692306
            }
        }
    ],
    "id": 1001
}]
```

Is this a known issue? 
Would be nice to have an error message pop up in the browser when a submission fails.

**Comment by makseq** [comment]
@deppp can you add popup for error displaying in lsb.js, i think. And I will discover backend bug.

**Comment by saikrishb** [comment]
This might be related to #179. 
I was trying to do something similar. Select regions of audio and transcribe it using the AudioPlus and TextArea views.

**Comment by niklub** [comment]
@saikrishb ,
please update to the latest Label Studio v0.4.7
`pip install label-studio==0.4.7`
this problem should be resolved

**Comment by niklub** [comment]
Please reopen this issue if the problem remains
