### ISSUE TITLE
SDK : import tasks  does not import the images 

### ISSUE THREAD

**Issue by rydka** [heartexlabs/label-studio#1920]
Hello, 

I am writing about an issue that occurs when trying to insert tasks into a project. 
Here is the code used : 
 ```
for file_ in files :
    #predict = model.predict(file_)
    parts = file_.parts
    file_ = Path("/data" + "".join("/"+elem for elem in parts[4:]))
    task = {"id" : i, 
            "data" : {
                "image":str(file_),
                "Source filename" : file_.name,
                "value":"$image"
                },
            "annotations" : [],
            "predictions" : [{
                "result" : [
                    {
                        "value": "predict[0]"
                    }
                ],
                "score" : "predict[2][predict[1].item()].item()"
            }
            ]}
    ++i
    tasks.append(task)

project.import_tasks(tasks)
```

On label-studio UI when I try to display the image in the project it the value shown is DATA instead of the mini representation of the file.

Here is a capture : 
![image](https://user-images.githubusercontent.com/74670829/149419302-a1e2006e-cd8a-4a97-91cc-29ccbbccbd1a.png)

The project Labelling Interface has been set to Image Classification.

Thank you for your help

**Comment by makseq** [comment]
Please, check this docs about Local Storage: https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references

**Comment by rydka** [comment]
Thank you for the reply.
I already added the variable to the environment and I am able to connect the local storage files.


![image](https://user-images.githubusercontent.com/74670829/149538062-550dd69d-3e2d-4a2f-8267-4443e2250c4f.png)

However using the SDK keeps with the same phenomenon the image returning only "Data"

The code as been updated : 
```
for file_ in files :
    #predict = model.predict(file_)
    parts = file_.parts
    file_ = Path("/data/local-files/?d="+ "".join("/"+elem for elem in parts))
    task = {"id" : i, 
            "data" : {
                "image":str(file_),
                "Source filename" : file_.name,
                "value":"$image"
                },
            "annotations" : [],
            "predictions" : [{
                "result" : [
                    {
                        "value": "predict[0]"
                    }
                ],
                "score" : "predict[2][predict[1].item()].item()"
            }
            ]}
    ++i
    tasks.append(task)

project.import_tasks(tasks)
```

**Comment by makseq** [comment]
@rydka Are you using the latest LS master branch?

**Comment by rydka** [comment]
I am working on the 1.4 label-studio version

**Comment by makseq** [comment]
@rydka LS 1.4 has critical bugs in Local storage, recommend to switch to the latest master.

**Comment by rydka** [comment]
Thank you for your answer I will proceed switching to master.

I managed to import the images in label studio by creating the webservice retrieving the images in my repository and a script inserting them in label studio.

![image](https://user-images.githubusercontent.com/74670829/149905096-21f27bf5-987a-42a6-ba7d-551d5a366daf.png)


Now I have an issue when I try to enter the Annotation UI  the following error issues :

![image](https://user-images.githubusercontent.com/74670829/149905483-ac1f3ed2-8fc6-45b2-91c6-2675e80e1dc0.png)

Do you have any insights?

**Comment by rydka** [comment]
The issue comes from the syntax of the predictions. The choices coming from the predictions have to be lists.

**Comment by makseq** [comment]
@rydka Yes, your above code looks weird: 
```
 "predictions" : [{
                "result" : [
                    {
                        "value": "predict[0]"
                    }
                ],
                "score" : "predict[2][predict[1].item()].item()"
            }
            ]}
```

I would recommend that you check this docs: https://labelstud.io/guide/predictions.html#Import-pre-annotations-for-images

**Comment by makseq** [comment]
@rydka Have you solved this issue?

**Comment by rydka** [comment]
Yes thank you. The issue came from an invalid JSON format for my tasks.

**Comment by leonardoandresgaray** [comment]
Hey!

There is a workaround, jsut upload the file first, and the look for the task itsefl

project.import_tasks(os.path.join('C:\\Users\\.....\\images\\1280', 'IMG_20230422_105651.jpg'))
