### ISSUE TITLE
img url not use LABEL_STUDIO_HOST

### ISSUE THREAD

**Issue by lppsuixn** [heartexlabs/label-studio#1924]
**Describe the bug**
the img url not add sub-path 
like
![image](https://user-images.githubusercontent.com/12748339/149496942-1fe37dec-9c16-4933-9e68-009e54c12ba6.png)

**Expected behavior**
img url with sub-path 

**Environment (please complete the following information):**
 - OS:  windows
 - Label Studio Version : docker newest

**Comment by farioas** [comment]
sub-path override is supported only in docker-compose deployment

**Comment by lfoppiano** [comment]
@lppsuixn somehow I managed to get it work, see [here](https://github.com/heartexlabs/label-studio/issues/1889#issuecomment-1006310399). 

However, as @farioas said it's offically only supported in the compose deployment. 

Actaully I wonder whether would be possible to make it available for the docker image as well?

**Comment by makseq** [comment]
You have to configure your outside nginx properly:
check this patch - https://github.com/heartexlabs/label-studio/blob/master/deploy/nginx/scripts/90-replace-subpath.sh#L11

but it won't work without this nginx.
