### ISSUE TITLE
Tif format not supported

### ISSUE THREAD

**Issue by rydka** [heartexlabs/label-studio#1929]
Hello 

**Is your feature request related to a problem? Please describe.**
When trying to display images with the tif extension in the annotation the message "TypeError: r.type is undefined"

**Describe the solution you'd like**
I would like a solution which would enable us to work directly with tif images

**Describe alternatives you've considered**
We considered transforming our tifs into jpg before importing them in label-studio

Thank you

**Comment by makseq** [comment]
Please, check that your browser supports tiff - https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support.

**Comment by frafra** [comment]
What about including https://geotiffjs.github.io/?

**Comment by frafra** [comment]
@makseq would you be open to add support for TIFF if someone proposes a PR?

https://github.com/photopea/UTIF.js could also be considered.
