### ISSUE TITLE
Named entity recognition granularity is not reflected correctly in exported data

### ISSUE THREAD

**Issue by markcheeky** [heartexlabs/label-studio#1931]
**Describe the bug**
Option `granularity="word"` in named entity recognition is not reflected in exported data.

**To Reproduce**
1. create new project, select NER template and check "Select text by words"
1. import 1 task from a json file listed below 
1. click on the task to annotate it
1. annotate `mple tex` as ORG. Label studio automatically expands annotation to whole words, so `simple text` is annotated.
1. export data as json (the relevant part is listed below)

json input data:
```
{
  "data": {
    "text": "Some simple text with explanations"
  }	    
}
```

json output data:
```
{
  "value": {
      "start": 5,
      "end": 16,
      "text": "ple tex",
      "labels": [ "ORG" ]
  }
}
```

**Expected behavior**
The field `text` should contain `simple text` instead of `ple tex`
Notice however that `start` and `end` fields correspond to `simple text`, so at least those are correct.

**Environment (please complete the following information):**
 - OS version: Ubuntu 18.04.4 LTS
 - Label Studio Version: 1.4

**Comment by makseq** [comment]
Thank you for your report, we've created a ticket about this bug. We will write you when it's done.

**Comment by hlomzik** [comment]
Sorry, this issue was missed, just fixed it in LSF, will be released soon. Or you can use custom build right now.

**Comment by dhirajsuvarna** [comment]
when is the next release?

**Comment by makseq** [comment]
@dhirajsuvarna on the next week.
