### ISSUE TITLE
Questions on uploading local images using API

### ISSUE THREAD

**Issue by seyiqi** [heartexlabs/label-studio#1933]
Hi there,

Thanks so much for this awesome tool! I am working on a multi-modal reasoning problem in which each task contains both image and text. I would like to use the [Label Studio API](https://labelstud.io/api#operation/api_projects_import_create) to programmatically create tasks. The image field was set up as the following:
```
  <Image name="image" value="$image"/>
```

The label studio server was hosted on a Linux machine (port 8080). I have started up a server on the same machine to serve local files (port 8888), [following this guidline](https://labelstud.io/guide/tasks.html#Run-a-web-server-to-generate-URLs-to-local-files).

I have the following Python code creating new tasks:
```
url = "http://localhost:8080/api/projects/xxx/import"
authorization_token = {"Authorization": "Token xxxx", 'Content-Type': 'application/json'}
data_dict = {"image":"http://localhost:8888/000.png", "text":"some text", "meta":"some meta"}
r = requests.post(url, headers=authorization_token, data=json.dumps(data_dict))
```

While I am able to create the task, the image won't display:
![bug_screenshot](https://user-images.githubusercontent.com/6496413/150001300-7d89ef93-068a-4f1d-8146-3aa4ed4169c8.png)

It seems that the server was not able to access the image. However, I was able to add the image using exactly the same url:
![img1](https://user-images.githubusercontent.com/6496413/150001669-935fdcfc-ac7c-4089-b78b-b3dea3246227.png)
![img2](https://user-images.githubusercontent.com/6496413/150001673-cda7c221-5da3-4248-b5a4-6648f79713bd.png)

In addition, if I replace the image url with some public image url (e.g. https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Haematopus_finschi_-_Point_Chevalier.jpg/1280px-Haematopus_finschi_-_Point_Chevalier.jpg), the API worked and I can see the image on Label Studio.

I am wondering which step I did wrong. Any help is greatly appreciated! 

Best,
Artie

**Comment by makseq** [comment]
@seyiqi Hi! 

In first case your browser tries to open the image and there is a CORS issue, because your server with this image can't send it by its security settings (see more about this here - https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems).

In the second case the Label Studio Backend downloads this image and your server can send it, because it's not a browser. 

So, you should configure your server with images correctly.

**Comment by seyiqi** [comment]
Hi @makseq ,

Thanks so much for your help. I appreciate it if you could take a look at my server setting and provide some insights. The image server is hosted on the same machine as Label Studio using the following commands:

```
npm install http-server -g
http-server -p 8888 --cors
```

I think the cors is on. This is a screenshot on the server's side:
![server_screeshot](https://user-images.githubusercontent.com/6496413/150430632-7b85092e-6f92-486e-99b3-1e8c0141025a.png)

On the Label Studio side, I see the following error on the console: 
![img1](https://user-images.githubusercontent.com/6496413/150430932-3e87049c-1cba-41e5-8426-083af6181db0.png)

I understand that there is something wrong that forbids Label Studio to access the image server but I am not sure exactly what went wrong. I really appreciate it if you could provide some guidance on how to troubleshoot this issue!

Best,
Artie

**Comment by makseq** [comment]
I'm not familiar with npm http-server, but your can google something like "npm http-server enable cors":

https://stackoverflow.com/questions/63297822/enable-cors-for-local-http-server

**Comment by seyiqi** [comment]
Thanks, @makseq . One last question. Is there a way to refer to a local file using the Label Studio import API rather than refer to an URL? Eg:

```
url = "http://localhost:8080/api/projects/xxx/import"
authorization_token = {"Authorization": "Token xxxx", 'Content-Type': 'application/json'}
data_dict = {"image":"/some/local/path.png", "text":"some text", "meta":"some meta"}
r = requests.post(url, headers=authorization_token, data=json.dumps(data_dict))
```

**Comment by makseq** [comment]
You have to setup the Local Storage and then you can use links like 

```
{  "image": "/data/local-files/?d=dataset1/1.jpg" }
```

https://labelstud.io/guide/storage.html#Local-storage
