### ISSUE TITLE
Doc fix 

### ISSUE THREAD

**Issue by Fkawala** [heartexlabs/label-studio#1938]
Howdy,

The API doc for the `/api/project/{id}/import` is wrong or at least very misleading ([link](https://labelstud.io/api#operation/api_projects_import_create))

In the "PATH PARAMETERS" section, the `id` param is described as follows :
> A unique integer value identifying this task.

Whereas it should read: 
>  A unique integer value identifying the **project to whom this task belongs**.

Have a nice day !

**Comment by smoreface** [comment]
@makseq please redeploy the API docs to fix this. It's correct in the code: https://github.com/heartexlabs/label-studio/blob/master/label_studio/data_import/api.py

Thanks for reporting this, @Fkawala!

**Comment by makseq** [comment]
done!
