### ISSUE TITLE
AudioPlus wave form never renders on external URLs

### ISSUE THREAD

**Issue by cnewton** [heartexlabs/label-studio#194]
Using the following tasks.json in the `Audioplus` view, label-studio never seems to load the waveform view:

`[
    {"url": "https://www2.cs.uic.edu/~i101/SoundFiles/CantinaBand3.wav"}
]`

`config.xml` is set to the  `AudioPlus` view with `<AudioPlus name="audio" value="$url"></AudioPlus>`

The waveform view renders blank, but otherwise works fine:

![image](https://user-images.githubusercontent.com/2302559/72746760-ef9b3380-3b80-11ea-85c4-6474cb76a163.png)

Loading from the local HTTP server (e.g., the `/static/samples` directory) works fine.

**Comment by shevchenkonik** [comment]
@cnewton Yes, this is a bug with CORS on the server (`https://www2.cs.uic.edu/`). You need to update CORS settings on the server or use your proxy server.
