### ISSUE TITLE
Playing wave form rendering scales overlay with play position in AudioPlus

### ISSUE THREAD

**Issue by cnewton** [heartexlabs/label-studio#195]
The wave form rendering view seems to scale the wave form against the current time position, which results in an odd looking play experience:

![waveformRendering](https://user-images.githubusercontent.com/2302559/72746945-620c1380-3b81-11ea-803d-96c4e2ca8bc5.gif)

Audio pictured is `/static/samples/game.wav`.

Reproducible in both Firefox 72 and Chrome 79 on Windows.

**Comment by iCorv** [comment]
experiencing the same problem with safari
