### ISSUE TITLE
label-studio 1.4.0 requires python packages with critical and high sev vulnerabilities

### ISSUE THREAD

**Issue by bblankrot-virta** [heartexlabs/label-studio#1959]
**Describe the bug**
The python package `label-studio==1.4.0` (newest release) requires `Django==3.1.13` which contains this high severity vulnerability: https://github.com/advisories/GHSA-v6rh-hp5x-86rv (FWIW Django considers this lower severity)

It also requires `label-studio-converter` which in turn requires `Pillow==8.3.2` (3 **critical** severity vulnerabilities, [here's one](https://github.com/advisories/GHSA-8vj2-vxx3-667w)) and `nltk==3.5` ([high severity vulnerability](https://github.com/advisories/GHSA-rqjh-jp2r-59cj)).

Could these versions get bumped?

**To Reproduce**
1. Create repo with `label-studio` in its requirements.txt
2. Enable dependabot

**Expected behavior**
No critical/high severity alerts

**Environment (please complete the following information):**
 - Label Studio 1.4.0

**Additional context**
It seems the `master` branch of this repo already bumped Django to 3.1.14, but there has not been a release since then

https://github.com/heartexlabs/label-studio-converter/pull/76
https://github.com/heartexlabs/label-studio-converter/pull/77

**Comment by makseq** [comment]
@bblankrot-virta Please, use LS from the latest master commit, these issues are fixed there.

**Comment by bblankrot-virta** [comment]
Hi, I'd like to reopen this because that master commit is not working for me - the formatting of the pages is all wrong and there are 404 errors in the console. Logs show errors such as
```
Not Found: /static/fonts/roboto/roboto-v20-latin_cyrillic-500.ttf
```
and
```
[ldclient.util::all_flags_state::367] [WARNING] all_flags_state() called, but client is in offline mode. Returning empty state
```

Perhaps this version requires a connection to LaunchDarkly which we do not allow? Is it possible to create a release that doesn't require LaunchDarkly, similar to 1.4.0?

**Comment by makseq** [comment]
LaunchDarkly can be blocked totally. 

Please, do
```
label_studio/python manage.py collectstatic
```

and then run LS again
```
label-studio
```
