### ISSUE TITLE
base64 encoded PDFs won't display

### ISSUE THREAD

**Issue by epetrovski** [heartexlabs/label-studio#1969]
Not sure if this is a bug, but should PDFs not be displayed when base64 encoded?

I know there's a similar issue #1155 and that PDFs are not officially supported. But I'm closely following the PDF example in the playground except I'm supplying the actual base64 encoded file rather than a link.

Here is my task:
```
<View>
    <HyperText name="pdf" value="$pdf"/>
    <Choices name="label" toName="pdf">
        <Choice value="Skat"/>
        <Choice value="ID"/>
    </Choices>
</View>
```

And here is my input:
```
{'pdf': "<embed src='data:application/pdf;base64,JVBERi0xLjUNJeLjz9MN...' width='100%' height='600px'/>"}
```

**Comment by makseq** [comment]
1. It's not recommended usage of LS task data because all these base64 strings will be stored in the DB and this might lead to significant performance degradation.

2. not all browsers support this. e.g. this example doesn't work for me in google chrome: 
https://jsfiddle.net/yLx2W/1/
