### ISSUE TITLE
Polygon labels not saved & error on the setup page

### ISSUE THREAD

**Issue by pietz** [heartexlabs/label-studio#197]
**Describe the bug**
- Labeled tasks are not shown and not saved on disk
- The setup page shows an error I can't quite grasp after I've labeled an image

```
You've already completed some tasks, but some of them couldn't be loaded with this config: name=img, toName=img, type=polygon are expected
```
**To Reproduce**

1. Setup a minimal Polygon interface

```
<View>
  <Polygon name="poly" toName="img" value="Add Rectangle"></Polygon>
  <Image name="img" value="$image"></Image>
</View>
```
2. Import a dataset per .csv upload

```
image
https://images.unsplash.com/photo-1516383740770-fbcc5ccbece0
https://images.unsplash.com/photo-1516383740770-fbcc5ccbece0
https://images.unsplash.com/photo-1516383740770-fbcc5ccbece0
```

3. Label the image by creating a 4 point BB
4. Click Submit

**Expected behavior**

1. 1 task is shown as completed
2. no errors on the setup page

**Environment (please complete the following information):**
 - OS: Server: Ubuntu - Browser: macOS 10.14.6
 - Browser Chrome 79

EDIT: This problem only seems to appear with the Polygon object and not with the PolygonLabel object. However, since I only have 1 class, I dont need the labels option.

**Comment by niklub** [comment]
Hi, @pietz ! This error should be fixed since v0.4.7

**Comment by niklub** [comment]
Please reopen this issue if the problem remains

**Comment by Vikt0riia** [comment]
I have error in the setup page
You've already completed some tasks, but some of them couldn't be loaded with this config: name=max_value, toName=max_value, type=textarea are expected
How to fix it?

**Comment by makseq** [comment]
@Vikt0riia Where do you use LS? Is it app.labelstud.io? Or you use it locally.

**Comment by Vikt0riia** [comment]
@makseq locally
I annotate one image. Then I understand, that I forgot some objects to add. I wanted add then, but error appears.

**Comment by Vikt0riia** [comment]
@makseq Do you know how to solve?
Because we are changing continuously: add/delete objects and each time I create new project as I cant modify setup at all.

**Comment by makseq** [comment]
@Vikt0riia what ls version do you use?

**Comment by Vikt0riia** [comment]
@makseq 0.7.4.post0

**Comment by makseq** [comment]
What setup changes do you do?

**Comment by Vikt0riia** [comment]
I used conda in windows

**Comment by makseq** [comment]
No, I mean what changes do you want to do on setup page?

**Comment by Vikt0riia** [comment]
I would like to add some new items.
For example, I had this:
<View>
  <Image name="image" value="$image" zoom="true" zoomControl="true"/>
  <KeyPointLabels name="tag2" toName="image"
                  strokewidth="2" opacity = "1" >
    <Label value="center" background="red"/>
  </KeyPointLabels>
  <PolygonLabels name="label" toName="image"
                 strokeWidth="2" pointSize="small"
                 opacity="0.9">
    <Label value="Line" background="orange"/>
  </PolygonLabels>
   <EllipseLabels name="tag1" toName="image" strokewidth="2" fillOpacity="0">
    <Label value="ellipse" background="magenta"/>
  </EllipseLabels>
  <RectangleLabels name="tag3" toName="image" strokewidth="2" fillOpacity="0">
    <Label value="roiXYWH" background="green"/>
    <Label value="roi_ell" background="red"/>
  </RectangleLabels>
  <Header value="Enter min value"></Header>
  <TextArea name="min_value"></TextArea>
  <Header value="Enter max value"></Header>
  <TextArea name="max_value"></TextArea>
  <Header value="Enter id"></Header>
  <TextArea name="id"></TextArea>
</View>

And I would like to add:
  <Header value="Choose type"/>
  <Choices name="type" toName="image"
           choice="single" showInLine="true">
    <Choice value="basic"/>
    <Choice value="advances"/>
  </Choices>

**Comment by makseq** [comment]
It's specially limited LS behavior because you can

**Comment by makseq** [comment]
Nevertheless you can do some tricks to avoid this behavior

**Comment by Vikt0riia** [comment]
@makseq Ok thanks a lot !

**Comment by makseq** [comment]
@Vikt0riia you can try to change labeling config.xml at the project directory via filesystem. But remember you can corrupt your labeling.
