### ISSUE TITLE
Display images referenced in a s3

### ISSUE THREAD

**Issue by rydka** [heartexlabs/label-studio#1970]
Hello,

I am using a s3 which is sync with my project label studio and stores my resources (texts and images).

I there a way to directly use images from s3 with a json looking something alike :
```
{ data : 
   { image : "s3://path_to_resource}
}
```

Thank you

**Comment by makseq** [comment]
@rydka Yes, your example should work. I would recommend that you use the latest master commit from LS github, because we fixed some bugs about this today. 

You can even write like this (it works only in the latest master commits): 

```
{ 
"data" : 
   { "html" : "<embed src='s3://path_to_resource/1.html' />" }
}
```
