### ISSUE TITLE
Place string into editable text area from json

### ISSUE THREAD

**Issue by MatteoSid** [heartexlabs/label-studio#1979]
Hi all,

as suggested in the title we would like to put a string into an editable TextArea directly from a JSON that we will import into label studio.
Currently the JSON that we are importing is structured like this:

```json
[
  {
    "data": {
      "image": "some-image-name"
    },
    "predictions": [
      {
        "result": [
          {
            "editable": true,
            "value": {
              "text": [
                "mario rossi"
              ]
            },
            "id": "cbe3ef93-cceb-4141-a834-26c2a4b72510",
            "from_name": "question",
            "to_name": "image",
            "type": "textarea"
          }
        ]
      }
    ]
  }
]
```

And on LabelStudio we get something like this:

![immagine](https://user-images.githubusercontent.com/26544399/151533689-7877b2e1-c519-40d4-9259-573564f62857.png)

but we want something like this:

![immagine](https://user-images.githubusercontent.com/26544399/151534279-f3b12246-e94d-4bee-9cef-3c11f999e8a8.png)

Currently our HTML template is as shown below:

```html
<View>
  <Choices name="handwritten" toName="handwritten" choice="single-radio" showInLine="true">
    <Choice value="Maiuscolo" selected="true" hotkey="q"/>
    <Choice value="Minuscolo" hotkey="w"/>
  </Choices>
  <TextArea name="question" toName="image" placeholder="Enter description here..." value=""/>
  <Image name="image" value="$image"/>
</View>
```

We have looked at documentation several times but we didn't manage to find anything that can relate to this. Actually we don't know if it is something possible to do. Thanks in advices.

**Comment by smoreface** [comment]
@MatteoSid I suggest using variables in the data rather than predictions to get the behavior you describe.

For example:
```json
  [
  {
    "data": {
      "image": "/data/upload/47/fa12d6c8-dialogue-analysis.png",
      "text" : "mario rossi"
    }
  }
]
```

Then use a labeling config like this:
```xml
<View>
  <Choices name="handwritten" toName="handwritten" choice="single-radio" showInLine="true">
    <Choice value="Maiuscolo" selected="true" hotkey="q"/>
    <Choice value="Minuscolo" hotkey="w"/>
  </Choices>
  <TextArea name="question" toName="image" value="$text" editable="true"/>
  <Image name="image" value="$image"/>
</View>
```

NOTE: If you try to update the labeling config while some task data contains just the image data and not also the text data, you won't be able to save your changes. Let me know if this is an issue for you and I can share my workaround. 

more about variables here: https://labelstud.io/tags/index.html#Variables

**Comment by MatteoSid** [comment]
It works perfectly, it was exactly what I was looking for. Thank you very much.

**Comment by PExplorer** [comment]
Hi @MatteoSid Thanks for posting the request. I am trying to do the same for large number of images. I need help with the following: Once I upload the images, image name is changing with additional token added to the image name in the dash board and when I upload json, new entry being is created with two different columns image and text. My issue is.. How can I upload predictions from UI once I upload the images? Thank you for your time. If there is better approach, please let me know to display predictions and corresponding images. Thank you

**Comment by makseq** [comment]
@PExplorer You can retrieve all tasks from the project and then you will know tasks' URLs - https://labelstud.io/sdk/project.html#label_studio_sdk.project.Project.tasks. 
Then you can use https://labelstud.io/sdk/project.html#label_studio_sdk.project.Project.create_predictions to import predictions, just pass the task id to the prediction: { "task": <id>, "result": [...]}

**Comment by reveur-code** [comment]
> NOTE: If you try to update the labeling config while some task data contains just the image data and not also the text data, you won't be able to save your changes.

This is an issue for me. I would able to change the value and should able to update new data. can you please help @smoreface  @makseq
