### ISSUE TITLE
A method to keep annotation labels visible when annotating a large body of text.

### ISSUE THREAD

**Issue by bentrevett** [heartexlabs/label-studio#1996]
When performing NER annotations on a long piece of input text, I'd like some way to always keep the annotation labels visible, so I can always see the relevant hotkeys.

Screenshot 1: Annotation labels (PERSON, ORGANIZATION and LOCATION) and hotkeys show at the top of the screen at the beginning of text.

<img width="1440" alt="Screenshot 2022-02-03 at 09 19 54" src="https://user-images.githubusercontent.com/8006479/152315034-fe99e955-a633-483b-9d0f-596b338f681d.png">

Screenshot 2: When scrolling down, I can no longer see the annotation labels and to be reminded of the hotkeys, I need to manually scroll up -- this becomes an issue when we have a lot of different annotations and/or a large body of text across many lines.

![Screenshot 2022-02-03 at 09 19 54 2](https://user-images.githubusercontent.com/8006479/152315160-b718431e-38d0-41d1-8a1e-fc05eeb53df9.png)

**Comment by makseq** [comment]
Please [check this sticky labels labeling config](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CView%20style%3D%22padding%3A%200%201em%3B%20margin%3A%201em%200%3B%20background%3A%20%23f1f1f1%3B%20position%3A%20sticky%3B%20top%3A%200%3B%20border-radius%3A%203px%22%3E%3Cbr%3E%20%20%20%20%3CLabels%20name%3D%22label%22%20toName%3D%22text%22%20showInline%3D%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%3CLabel%20value%3D%22Person%22%20%2F%3E%3Cbr%3E%20%20%20%20%20%20%3CLabel%20value%3D%22Organization%22%20%2F%3E%3Cbr%3E%20%20%20%20%3C%2FLabels%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%20%20%3CView%3E%3Cbr%3E%20%20%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%20%2F%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E%3Cbr%3E).

**Comment by bentrevett** [comment]
That config did not fix my issue. The labels do follow the user as they scroll, but are not completely visible. I have 10 labels, so they usually get split across two rows on my monitor.

See:
![Screenshot 2022-02-04 at 09 39 39 (2)](https://user-images.githubusercontent.com/8006479/152506696-3d5d4e4e-ad26-461e-a1eb-53f9f6bdc03d.png)

**Comment by makseq** [comment]
Maybe [this config](https://labelstud.io/playground/?config=%3CView%20style%3D%22display%3A%20flex%3B%22%3E%3Cbr%3E%20%20%3CView%20style%3D%22padding%3A%200em%201em%3B%20background%3A%20%23f1f1f1%3B%20margin-right%3A%201em%3B%20border-radius%3A%203px%22%3E%3Cbr%3E%20%20%20%20%3CView%20style%3D%22position%3A%20sticky%3B%20top%3A%200%3B%20margin-top%3A%2050px%3B%20max-width%3A150px%22%3E%3Cbr%3E%20%20%20%20%20%20%3CLabels%20name%3D%22label%22%20toName%3D%22text%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Person%22%20%2F%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Organization%22%20%2F%3E%3Cbr%3E%20%20%20%20%20%20%3C%2FLabels%3E%3Cbr%3E%20%20%20%20%3C%2FView%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%20%20%3CView%3E%3Cbr%3E%20%20%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%20%2F%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E) will work better? 

Try to adjust `margin-top: ...` to avoid this intersection with the top panel.
