### ISSUE TITLE
Note with various anatodators

### ISSUE THREAD

**Issue by Edresson** [heartexlabs/label-studio#20]
Hello,
Annotation tasks are usually performed by many annotators, after these annotations are evaluated.

I wonder if the tool supports multiple simultaneous annotators?

 Does the tool have any way of comparing the annotations of several annotators?

It is possible to export the annotations to a text file (this is thinking of text segmentation, so it would be possible to easily compare the segmentation of several annotators).

Thank you in advance for your attention

**Comment by deppp** [comment]
Hey Edresson,

While on the frontend data structures and views level there is support for more than one annotator (check [CompletionStore](https://github.com/heartexlabs/label-studio/blob/master/src/stores/CompletionStore.js#L263) and [Completions](https://github.com/heartexlabs/label-studio/blob/master/src/components/Completions/Completions.js))  we haven't built support for that on the backend that is distributed with Label Studio. There is a different product (not open sourced) that we're working on that includes support for multiple annotators out of the box.

Our current focus is on supporting as many data types as possible. Plus finalizing the labeling format and creating converters from that to ML libs.

We will re-iterate on LS backend shortly to have that support. Meanwhile, you can either extend it yourself or lunch multiple instances of the LS and distribute it across annotators and compare the results from each instance.

**Comment by shevchenkonik** [comment]
@Edresson If you have any suggestions, please reopen this issue. Thank you!
