### ISSUE TITLE
Label offsets incorrect, end offset goes beyond end of text

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#2007]
**Describe the bug**

In rare cases, the offsets recorded for a label annotation end up being one larger than they should. This was only noticed because the end offset was actually one beyon the length of the text annotated. 

This happens in a context were arabic text, mixed with latin words and emojis was annotated. The view for the text was styled with "direction: rtl;"  to show the arabic text correctly. The label was created for an arabic (RTL) portion of the text, right at the end. 

What is really weird is that the label annotation, when checking within label-studio, is shown starting at one character beyond where it was intended to start. 

**To Reproduce**

Unfortunately, we could not find a way to deliberately reproduce this yet. The annotations were created by an arabic language linguist who did not notice this problem during the annotation process, it was only discovered afterwards when processing the exported JSON and noticing an offset that is larger than the length of the text.

**Environment (please complete the following information):**
 - OS:  Ubuntu 18.04
 - Label Studio Version: 1.4

**Comment by johann-petrak** [comment]
Actually when we compare the text stored for the annotated label with the substring of the annotated text corresponding to the offsets stored with the label, almost none of the offsets seem to be correct! 
We used the label-studio release 1.4 from pypi, assuming that this would work in a released version :/

**Comment by johann-petrak** [comment]
Digging into this a bit deeper I noticed another issue which may be related to this:

The exported annotations JSON file contains the original data as the "data" key. In the original data I had a "text" field that contained the (Arabic) text to annotate.

HOWEVER: the "text" field in the exported JSON file in the "data" map contains ADDITIONAL characters from the unicode U+0080 to U+008F range!!!! 

So it seems while the documentation says that this should just be a copy, it is actually getting modified by label-studio which would imply that the offsets do not correspond to the original text from the imported JSON?

NOTE: for the problem reported above, I use the text as I got it from the data map, not the original text, so I did not initially realize that apparently, the text gets modified! 

Is this correct? Are offsets meant to refer to the original text or the modfiied text in data? I really did not expect this and I think it would be a HUGE problem if offsets do not refer to the offsets in the original text!

**Comment by makseq** [comment]
Possible duplicate: https://github.com/heartexlabs/label-studio/issues/1888

**Comment by makseq** [comment]
Could you try to use this LS version `pip install label-studio==1.4.1rc0`?

**Comment by johann-petrak** [comment]
Not sure if this is a duplicate of #1888 as we deliberately styled the view using "direction: rtl;" to make sure the label and original text words are shown in correct order. 
Also #1888 does not really address the issues I detected later which may or not be related but are definitely a problem: that the text in the data section is different from the original and contains those control characters which seem to indicate that label-studio does not correctly deal with the original unicode codepoints.  (even then, the copies of the data fields should NOT change at all but the label text stored for the annotations themselves also contain those control characters.)

I can test whether the same thing happens with 1.4.1rc0 but the problem is that all the annotated examples are now messed up. So the question would be if there is maybe some automatic way to correct the incorrect data? Which would require that we first understand what actually went wrong. From just looking at the date I was not able to figure that out.

**Comment by johann-petrak** [comment]
I installed label-studio==1.4.1rc0

1) tried to export the data from the existing database using this version to see if the problem is maybe just introduced on export, but no
2) set up a mini project with for items. Used the same interface definition as before, annotated the last word in the text and tried to export

For this I get an error when doing the export:

```
Traceback (most recent call last):
  File "/home/johann/software/anaconda/envs/fcdo/lib/python3.9/site-packages/label_studio_converter/utils.py", line 200, in parse_config
    xml_tree = etree.fromstring(config_string)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1912, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/johann/software/anaconda/envs/fcdo/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/johann/software/anaconda/envs/fcdo/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/johann/software/anaconda/envs/fcdo/lib/python3.9/site-packages/label_studio/data_export/api.py", line 63, in get
    formats = DataExport.get_export_formats(project)
  File "/home/johann/software/anaconda/envs/fcdo/lib/python3.9/site-packages/label_studio/data_export/models.py", line 133, in get_export_formats
    converter = Converter(config=project.get_parsed_config(), project_dir=None)
  File "/home/johann/software/anaconda/envs/fcdo/lib/python3.9/site-packages/label_studio_converter/converter.py", line 146, in __init__
    self._schema = parse_config(config_string)
  File "/home/johann/software/anaconda/envs/fcdo/lib/python3.9/site-packages/label_studio_converter/utils.py", line 202, in parse_config
    raise ValueError(str(e))
ValueError: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)
```

**Comment by johann-petrak** [comment]
OK, so I looked at this closer and there are at least 3 different issues here, in the data created with version 1.4:

1) I got output json where definitely the end offset for a marked label is one larger than the length of the text. The text stored with the label corresponds to the actual marked characters. So if the end offset gets reset to the length of the text, this is corrected.

2) in a number of other cases, the offsets for the labels are shifted. It becomes apparent that the offsets are shifted by a number that corresponds to the number of emojis that appear before the label. So if there are 4 emojis before the label, then instead of offset x, the correct offset would be x-4 (both the start and end offsets are shifted like that)

3) the label text stored with the label is wrong if what is marked is something like "asdf     dfdfdf" (i.e. there is more than one space between two words) - in that case, the label text stored contains a single space instead of multiple spaces. This *may* happen on purpose but I would probably rather leave such normalizations to postprocessing.

Of course, there is the known issue that if a substring of the word is marked, the offsets correspond to the whole word, but the recorded label text is just the marked substring. Often the recorded substring is an actual substring of the text span between the recorded offsets but in cases 2) and 3) this is not the case. Also it would not be possible to find the correct marked substring if the recorded label text occurs more than once in the recorded offset span. 

Again, all the above applies to the output I got from running the annotation task with version 1.4.

Is it known which of the above problems may be fixed in 1.4.1rc0?

**Comment by makseq** [comment]
> I can privately share the data to reproduce the original offset beyond end of text problem and for reproducing the problem above, maybe via Slack?

yes, write me there. 

> ValueError: Start tag expected, '<' not found, line 1, column 1 (<string>, line 1)

this error looks more like you have a mistake in your labeling config.

**Comment by johann-petrak** [comment]
The browser used was Microsoft Edge on Windows.

**Comment by johann-petrak** [comment]
We did not hit any instances of this problem any more. 
So overall looks good, closing.
