### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by samirbr** [heartexlabs/label-studio#201]
**Is your feature request related to a problem? Please describe.**
To delete bounding boxes or classify an image I'm required to click on a button. Is faster and easier to use keyboard shortcuts when labeling large volumes of data.

**Describe the solution you'd like**
I would love to be able to add shortcuts to the labels (i.e. press "A" for "Car", "B" for "aircraft").
Also would be nice to have some more standard shortcuts, for example, to press DELETE and delete a bounding box, keypoint or other drawable.

A suggestion for class shortcuts:
```
<Choices name="choice" toName="img" showInLine="true">
    <Choice value="Car" background="red" key="A"/>
    <Choice value="Aircraft" background="yellow" key="B"/>
  </Choices>
```

**Describe alternatives you've considered**
Click on the delete button, or click on the class label.

**Comment by deppp** [comment]
Hey @samirbr , thanks for posting this. 

By default, the hotkeys are assigned to every label and that little `[A]` (or any other letter) near the label name shows you the hotkey that was automatically assigned. To delete you can hit "Backspace". 

Also if you want to define your own hotkey just pass a `hotkey=""` param to `<Label />` tag, like `<Label value="car" hotkey="ctrl+1">`.

Hope that helps, let me know if you have any other questions.

**Comment by samirbr** [comment]
Hi @deppp, thank you. Just found `Backspace` key deletes the drawable.

**Comment by makseq** [comment]
@owos do you use NUM PAD section on your keyboard? Could you record a video please?

**Comment by owos** [comment]
I figured the NUM PAD doesn't work, do I used the one beneath the function keys instead.
-------- Original message --------From: Max Tkachenko ***@***.***> Date: 18/10/2021  22:05  (GMT+01:00) To: heartexlabs/label-studio ***@***.***> Cc: Abraham Owodunni ***@***.***>, Mention ***@***.***> Subject: Re: [heartexlabs/label-studio] Keyboard Shortcuts (#201) 
@owos do you use NUM PAD section on your keyboard? Could you record a video please?
