### ISSUE TITLE
Access the labelling data from the postgres sql 

### ISSUE THREAD

**Issue by sachin-singh-12** [heartexlabs/label-studio#2010]
Hi, I am trying to access the annotation data i.e. the bounding box information from the postgres server. But I could not find any table having that data. I am using the default docker-compose configuration provided here - https://github.com/heartexlabs/label-studio/blob/master/docker-compose.yml to run the label studio. Can someone point me to the table I should look into?

**Comment by makseq** [comment]
@sachin-singh-12 This table name is `task_completion`, it has the `result` field. It's a JSON dict. Hope it helps.

**Comment by sachin-singh-12** [comment]
Yeah, that's all I needed, Thanks @makseq
