### ISSUE TITLE
Importing images from S3

### ISSUE THREAD

**Issue by anabia-alam** [heartexlabs/label-studio#2016]
Hi, 
I have created the project through Label Studio's python api. After creating task lists through the format, 
{ data : 
   { image : "s3://path_to_resource}
}
I am importing tasks through import_tasks() command. My question is,

- Even after running import_tasks(), the cloud storage option shows 'Never Synced' option. Are these same, import and sync? Because if they are why is 'never synced' showing in cloud storage despite importing it.
![image](https://user-images.githubusercontent.com/97160469/153544855-289cbf8e-a459-4474-ac87-f8c0fc793799.png)

- Second question, is there a way to ensure the same tasks do not get imported(synced?) twice when using import_tasks? Can a check be introduced that only unique tasks get synced?

**Comment by anuj018** [comment]
Any updates? Did you figure out how to do this?
