### ISSUE TITLE
API  method api/projects/validate/  -  how to send the project number? 

### ISSUE THREAD

**Issue by DimIsaev** [heartexlabs/label-studio#2027]
there is only one line in the documentation with label config
how to send the project number?

```
{
  "label_config": "string"
}
```

**Comment by makseq** [comment]
@DimIsaev Just use `/api/projects/<project-id>/validate/` with 

```
{
  "label_config": "string"
}
```

**Comment by DimIsaev** [comment]
> 
it doesn't seem to work
```
validate = {
    "label_config": """
<View>
  <Labels name="label" toName="text">
    <Label value="ITEM" background="red"/>
    <Label value="AMOUNT" background="darkorange"/>
    <Label value="UNIT" background="#59a72f"/>
  </Labels>
  <Text name="text" value="$text" granularity="word"/>
</View>
    """
}
```

```
result = requests.post(
    f'http://{url}:{port}/api/projects/{id_project}/validate/',
    headers={'Authorization': f'Token {token}'},
    json=validate
)
result
```
>> <Response [404]>

**Comment by makseq** [comment]
Just remove the last trailing slash 

http://{url}:{port}/api/projects/{id_project}/validate/
=>
http://{url}:{port}/api/projects/{id_project}/validate

**Comment by DimIsaev** [comment]
> Just remove the last trailing slash
> 
> http://{url}:{port}/api/projects/{id_project}/validate/ => http://{url}:{port}/api/projects/{id_project}/validate

the request worked, but the configuration remained unchanged

answer
```
{'config_essential_data_has_changed': None}
```
log:
![image](https://user-images.githubusercontent.com/11172642/154412497-36eb5230-965f-4430-8a5f-5ba8899854be.png)

**Comment by makseq** [comment]
What is your original project config and the new one you are trying to validate?

**Comment by DimIsaev** [comment]
> What is your original project config and the new one you are trying to validate?

source 
![image](https://user-images.githubusercontent.com/11172642/154440023-a9b5eed6-5f48-42bd-a127-e4ecc6f3d826.png)

validate
![image](https://user-images.githubusercontent.com/11172642/154440161-5d4c7f98-3d00-40c5-ba2c-76fa908d8205.png)

**Comment by DimIsaev** [comment]
> In this case validation should say 200. Everything works as expected.
> 
> ```
> {'config_essential_data_has_changed': None} 
> ```
> 
> this field will be not None when you try to destructively change a labeling config, e.g. remove labels, change names for already existing tags, etc.


You do not hear me ?
Yes answer 200

but the configuration does not change!

I'm sending
![image](https://user-images.githubusercontent.com/11172642/154647311-7a27b83b-489e-4c59-bfd0-26493f42dfbe.png)

answer 200 
'''
{'config_essential_data_has_changed': None}
'''
![image](https://user-images.githubusercontent.com/11172642/154647525-b1c5b785-c41a-49f5-9540-8b9cdf9b7858.png)

But the config doesn't change.

![image](https://user-images.githubusercontent.com/11172642/154648226-fa22cd0e-7e63-426d-8301-e4d07b29f77d.png)

**Comment by DimIsaev** [comment]
thanks, this is working to me
