### ISSUE TITLE
Doesn't support python 3.8 because of Pillow

### ISSUE THREAD

**Issue by pilipenok** [heartexlabs/label-studio#203]
(Win 10, Python 3.8.1)
> pip install label-studio
...
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
... Pillow\setup.py:28: RuntimeWarning: Pillow does not yet support Python 3.8 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows.

**Comment by deppp** [comment]
Thanks for the report @pilipenok we will handle that with the next release

**Comment by niklub** [comment]
Hi, @pilipenok ! Try to update `pip install label-studio==0.4.7`

**Comment by niklub** [comment]
Please reopen this issue if the problem remains
