### ISSUE TITLE
[WARNING] all_flags_state() called, but client is in offline mode. Returning empty state

### ISSUE THREAD

**Issue by tcexeexe** [heartexlabs/label-studio#2031]
**Describe the bug**
when l run
`python label_studio/manage.py runserver`
l always see the warning  `[WARNING] all_flags_state() called, but client is in offline mode. Returning empty state`in the log, Although it doesn't bother me in terms of usage. But I wonder what causes this, and how do I eliminate it?

**Screenshots**
![1644980726(1)](https://user-images.githubusercontent.com/28287196/154188359-6fbc8c1e-5bab-4353-98a9-7891b7a79caa.png)

**Environment (please complete the following information):**
-anaconda virtual environment——Python 3.8.12
-Ubuntu 20.04.3 LTS
-label studio 1.4

**Comment by makseq** [comment]
@tcexeexe We use launchdarkly for feature flags management, and it is turned off by default. The launchdarkly client writes that it can't retrieve feature flags. Most likely it's not important for your right now :)

**Comment by makseq** [comment]
@MSalehiA Could you please record a video with this problem?

**Comment by MSalehiA** [comment]
Hello, 
thank you for the prompt response. Unfortunately cannot do a video, but here are the steps to re-create the issue.  I have also attached the LS log in two cases of using URL vs clicking from the browser, which I think would help.

Steps to reproduce the behavior:
1. Create a project
2. Upload some images through file sync, etc. (let's say 500 to be a large number)
3. Add some predictions for objects on the image, from pre-annotations or from a model, through the api (api/predictions)
4. In the browser try to load the image by directly using a link for images that have a prediction (can be verified using api/tasks/), as http://ip:port/projects/{prj_id}/data?task=250 (assuming there is a large number than the first 30, etc.)

Environment:
- OS: debian-11 (gcp)  
- LS compiled from the source on github

The impact is that the blue progress bar shows up in the right panel, but no image is loaded. However, if you go find task 250 (or whatever number) and click on it, the image shows up along with predictions on it. It seems different APIs are called by the backend for each of these cases, please see the log file payload.

[LS_log.txt](https://github.com/heartexlabs/label-studio/files/8659300/LS_log.txt)

**Comment by makseq** [comment]
@MSalehiA Are you sure that task with ID=250 exists in your project?

**Comment by MSalehiA** [comment]
> 
Yes, it does, and if I find the task by scrolling down, and click on it, the image and predictions shows up on it. 
in some instances the browser console logs the following error:

![image_2022_05_13T03_33_44_814Z](https://user-images.githubusercontent.com/77166334/168206437-5b854b36-b9a4-4cc1-8798-e0ea819401e8.png)
