### ISSUE TITLE
YOLO import issue

### ISSUE THREAD

**Issue by tulbureandreit** [heartexlabs/label-studio#2036]
Hello,

I recently tried to import YOLO format into label studio. I convert them with label-studio-converter.

I always get this error and the image does not display in the tasks tab. Just the annotations.

```
There was an issue loading URL from $image value

Things to look out for:

    URL is valid
    URL scheme matches the service scheme, i.e. https and https
    The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)

Technical description:
URL: [/data/local-files/?d=/0fdb2623-25997_5.jpg](http://localhost:8081/data/local-files/?d=/0fdb2623-25997_5.jpg)
```

To specify, I set up local storage correctly, exactly like in the tutorial: https://labelstud.io/guide/storage.html#Local-storage
And the problem is that the path to the image is messed up.

**Comment by makseq** [comment]
1. What paths do you have? (any examples)
2. What LS version do you use?

**Comment by tulbureandreit** [comment]
@makseq So I have my ls-config.json in: /home/user/Desktop/data

My images and labels folders, classes.txt are in the same folder, thus /home/user/Desktop/data/images, /home/user/Desktop/data/labels, /home/user/Desktop/data/classes.txt.

I followed the guide from https://github.com/heartexlabs/label-studio-converter/pull/46, to convert my annotations.

I have the images and labels folder also in this folder.

I have the latest label studio version=1.4.1

**Comment by tulbureandreit** [comment]
@makseq what I see is that in the ls-config.json, the images paths are messed up. If I add the correct path there manually, then everything works fine.
eg.
This is what I get by default in the ls-config.json.

```
[{"annotations":
.
.
 "data": {"image": "/data/local-files/?d=/0fdb2623-25997_5.jpg"}}]
```

This is what I need in the ls-config.json.

```
[{"annotations":
.
.
 "data": {"image": "/data/local-files/?d=Desktop/data/images/0fdb2623-25997_5.jpg"}}]
```

**Comment by makseq** [comment]
> Moreover, can you convertttttt directly from Azure blob storage into YOLO format?
yes, but you have to specify correctly all paths to azure storage + setup azure storage in LS.

**Comment by makseq** [comment]
@tulbureandreit You have to specify `--image-root-url` correctly, e.g. 

```
label-studio-converter import yolo .... --image-root-url Desktop/data/images
```

**Comment by Sodek93** [comment]
> @tulbureandreit You have to specify `--image-root-url` correctly, e.g.
> 
> ```
> label-studio-converter import yolo .... --image-root-url Desktop/data/images
> ```

How does the same work for coco? I also have a issue with messed up image path in my imports...
When i use --image-root-url it say i have to use YOLO as this seems to be a YOLO only arg.
Any Idea? :-)
