### ISSUE TITLE
Exporting only annotated images

### ISSUE THREAD

**Issue by anabia-alam** [heartexlabs/label-studio#2042]
Hi, 
Currently, LS exports all the images, is there a feature to only export annotated images and not the ones that have been skipped though LS SDK?

**Comment by makseq** [comment]
Hello, this feature is not yet supported in SDK, but you can call a direct API request: 
https://labelstud.io/guide/export.html#Export-snapshots-using-the-API

**Comment by anabia-alam** [comment]
Thank you for your prompt response. Is the process still the same if I want to sync/export annotations to S3? 
I only want to export annotated/completed images to S3.

**Comment by makseq** [comment]
No, S3 export via Target Storages is a different process. Annotations are stored in separated json files and updated on each Submit/Update click. 
Check this for more information: https://labelstud.io/guide/storage.html#Target-storages
