### ISSUE TITLE
"Rate PDF" example from "playground" does not show pdf

### ISSUE THREAD

**Issue by whwang299** [heartexlabs/label-studio#2049]
**Describe the bug**
"Rate PDF" example from "playground" does not show the pdf.

**To Reproduce**
1. Install `label-studio-1.4.1` via `pip` on `conda` (`python3.8.11`) on `Ubuntu-20.04`.
2. Run label-studio by typing `label-studio start --nobrowser`.
3. Access the server from labtop.
4. Setup labeling config following (https://labelstud.io/playground/)
```
<View>
  <HyperText name="pdf" value="$pdf"/>

  <Header value="Rate this article"/>
  <Rating name="rating" toName="pdf" maxRating="10" icon="star" size="medium" />

  <Choices name="choices" choice="single-radio" toName="pdf" showInline="true">
    <Choice value="Important article"/>
    <Choice value="Yellow press"/>
  </Choices>
</View>
```

5. Make `example.json`
```
{
    "pdf": "<embed src='https://app.heartex.ai/static/samples/sample.pdf' width='100%' height='600px'/>"
}
```
6. Start labeling

**Expected behavior**
The pdf should be shown.

**Screenshots**
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/11023071/154829211-8987cc36-8b80-45b3-879f-023640c23697.png">

**Environment (please complete the following information):**
 - OS: (client, macOS 12.1, chrome or safari), (server: ubuntu 20.04 x86)
 - Label Studio Version [e.g. 1.4.1]

**Additional context**
The method above works fine on `label-studio-1.1` with `safari` browser.

**Comment by makseq** [comment]
@whwang299 Please, try to use <HyperText name="pdf" value="$pdf" **inline="true"** />

**Comment by whwang299** [comment]
Thanks!
