### ISSUE TITLE
Local Storage referencing documentation is unclear

### ISSUE THREAD

**Issue by tilusnet** [heartexlabs/label-studio#2057]
Specifically, https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references exemplifies magic `/data/local-files/?d=dataset1` path prefixes out of the blue.

Is the `/data/local-files/?d=` prefix a to be hardcoded part of a [LS JSON Task file](https://labelstud.io/guide/tasks.html#Basic-Label-Studio-JSON-format)'s value fields?

What does `dataset1` mean? 
Is it somehow related to the Storage Title [and a connection is needed](https://labelstud.io/guide/storage.html#Set-up-connection-in-the-Label-Studio-UI-4)?      
Is it perhaps the suffix of the Local path in that dialog box? 

What is my dataset "name" if eg.:
* `LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files/foo`
* Storage Title = "This is a funny title with "£$%"
* Absolute local path = `/label-studio/files/foo/bar/baz`

Is it a normalised "This is a funny title with "£$%", is it `bar/baz`, `barbaz` or perhaps something entirely different?

For context, I am running LS via Docker with locally mapped directories.

**Comment by tilusnet** [comment]
> ([Source](https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references)) In those cases, you can add local storage without syncing (to avoid automatic task creation from storage files) and specify the local files in your data values.

I don't think this works. 

My local files only start to become accessible once I sync.
If I plainly import a manually crafted task json file, the files are not shown.

**Comment by tilusnet** [comment]
I created #2058 for what I believe it's a bug.

**Comment by pa-mc** [comment]
> I created #2058 for what I believe it's a bug.

I believe so, I think the problem is that the logic to consider `LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT` is not in the necessary label_studio_tools repo. 

I had a custom ml backend, I could load & sync the local images in the label-studio UI. However, whenever I click on a image that's been synced to UI, it would give me an error suggesting that file does not exist. 

```
File "/opt/anaconda3/envs/layoutlm/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py", line 59, in get_local_path
    raise FileNotFoundError(filepath)
FileNotFoundError: images/0001438955.png/local-files/
```

Here is the task id. I think one of the culprit is the `?d=images/` part. It seems that it did not use the full `LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT` path.

```
[{'id': 1129, 'data': {'image': '/data/local-files/?d=images/0001438955.png'}, 'meta': {}, 'created_at': '2022-02-22T18:02:12.876394Z', 'updated_at': '2022-02-22T18:02:12.876408Z', 'is_labeled': False, 'overlap': 1, 'project': 7, 'file_upload': None, 'annotations': [], 'predictions': []}]
```

Also, I do wonder, even if it did, would it work... because the logic in `label_studio_tools/core/utils/io.py`

```
def get_local_path(url,
                   cache_dir=None,
                   project_dir=None,
                   hostname=None,
                   image_dir=None,
                   access_token=None,
                   download_resources=True):
    """
    Get local path for url
    :param url: File url
    :param cache_dir: Cache directory to download or copy files
    :param project_dir: Project directory
    :param hostname: Hostname for external resource
    :param image_dir: Image directory
    :param access_token: Access token for external resource (e.g. LS backend)
    :param download_resources: Download external files
    :return: filepath
    """
    is_local_file = url.startswith('/data/') and '?d=' in url
    is_uploaded_file = url.startswith('/data/upload')
    if image_dir is None:
        upload_dir = os.path.join(get_data_dir(), 'media', 'upload')
        image_dir = project_dir and os.path.join(project_dir, 'upload') or upload_dir

    # File reference created with --allow-serving-local-files option
    if is_local_file:
        filename, dir_path = url.split('/data/')[1].split('?d=')
        dir_path = str(urllib.parse.unquote(dir_path))
        filepath = os.path.join(dir_path, filename)
        if not os.path.exists(filepath):
            raise FileNotFoundError(filepath)
        return filepath
```

I don't think the following gives you the right `filepath`, because it will always give you something like: `YourActualPathToImage.png/local-files/`

```
        filename, dir_path = url.split('/data/')[1].split('?d=')
        dir_path = str(urllib.parse.unquote(dir_path))
        filepath = os.path.join(dir_path, filename)
```

**Comment by makseq** [comment]
Does this video help?
https://www.youtube.com/watch?v=lo6ncQajbdU

**Comment by pa-mc** [comment]
> @tilusnet Does this video tutorial help? https://www.youtube.com/watch?v=lo6ncQajbdU
> 
> Are you sure you using LS 1.4.1? because LS 1.4.0 had a lot of problems with Local storage like you are describing here.

Hi @makseq thank you for sharing the video clip. I did use the latest version of label-studio. However, I did not use the `.json` file as the data source, but rather the actual file directory path as source & target. 

```
label-studio              1.4.1.post1              pypi_0    pypi
label-studio-converter    0.0.39                   pypi_0    pypi
label-studio-ml           1.0.6                     dev_0    <develop>
label-studio-tools        0.0.0.dev11              pypi_0    pypi
```

I will give it a try at some point with local storage, but I've moved on to use Azure blob store, which worked like a charm ;)

**Comment by MrNightSky** [comment]
Hi,
I have solve the same problem and described it [here](https://github.com/heartexlabs/label-studio/issues/2086#issuecomment-1080668206)
