### ISSUE TITLE
Tasks with local storage file references do not load files unless explicitly synced

### ISSUE THREAD

**Issue by tilusnet** [heartexlabs/label-studio#2058]
**Describe the bug**
Description at [Tasks with local storage file references](https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references) does not hold. Quote:

>  In cases where your tasks have multiple or complex input sources, such as multiple object tags in the labeling config or a HyperText tag with custom data values, you must prepare tasks manually.
**In those cases, you can add local storage without syncing** (to avoid automatic task creation from storage files) and specify the local files in your data values.

One cannot add a local storage like that.  
The files don't show.

I only managed to display files once I explicitly sync via adding Source Storage -> Local Files -> Sync.
This obviously creates unwanted duplicate tasks from the raw media files.

**To Reproduce**
1. [Run Label Studio on Docker and use local storage](https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-and-use-local-storage)
2. Create a single task json file with file references as illustrated in [Tasks with local storage file references](https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references) 
3. Create a project in LS and Import the aformentioned json file
4. Tasks are loaded, but media files referenced are not shown

The referenced media files are correctly accessible in the docker container. 

**Expected behavior**
Honour documentation at [Tasks with local storage file references](https://labelstud.io/guide/storage.html#Tasks-with-local-storage-file-references).

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version 1.4.1

**Comment by makseq** [comment]
@tilusnet Could you please show your 
1. env variables (LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED & LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT)
2. screenshot of how you setup Local Storage in LS settings
3. example of import json
