### ISSUE TITLE
Custom Hotkey for Submit

### ISSUE THREAD

**Issue by dernat71** [heartexlabs/label-studio#208]
**Is your feature request related to a problem? Please describe.**
I am an AZERTY user. The current hotkey for Submit is [ctrl+Enter] which is not convenient at all in our keyboards.

**Describe the solution you'd like**
It would be super cool to be able to customise the Submit hotkey the same way we can do it for Labels

Thaanks :-)

**Comment by tramanh06** [comment]
Is there update for this? It would be great if we can customize the Submit and Update hotkeys just like we can for Labels

**Comment by makseq** [comment]
@tramanh06 Unfortunately not. We are working on a big UX update with all shortcuts.

**Comment by filippo82** [comment]
Dear @makseq 

is there any temporary fix for this issue? I assume the current hotkey (`ctrl+enter`) is hardcoded somewhere in the code. Would it be possible to temporary change that?

Thanks.

**Comment by hlomzik** [comment]
Hi all here! 
The temporary fix is easy.
1. Change hotkey in `AppStore.js`: https://github.com/heartexlabs/label-studio-frontend/blob/7350e8c800c4d531d0a2b52a03217c7e6998789b/src/stores/AppStore.js#L162
2. Build LSF and include the new version to LS: https://labelstud.io/guide/frontend.html#Custom-LSF-LSB-integration

Also you can change it in runtime with something like that for `ctrl+S`:
```document.addEventListener('keypress', e => e.ctrlKey && e.key === "s" && Htx.submitCompletion())```

You can put this code to your initialization code or pass it via `onLabelStudioLoad` parameter on LSF initialization.

**Comment by makseq** [comment]
@dernat71 we implemented customizable hotkeys, you can check them there https://labelstud.io/guide/labeling.html#Customize-hotkeys

**Comment by filippo82** [comment]
Great news 🥳 thank you.

**Comment by boscacci** [comment]
What about a customizable hotkey for zoom control for image labeling? I'm using a mac and I can't get the default keybindings to work for zoom in/out on images.
