### ISSUE TITLE
Custom template

### ISSUE THREAD

**Issue by tatiana-iazykova** [heartexlabs/label-studio#2087]
Hello!
I was wondering how to create a template for BBox labeling on html with multiple jpg or if it's possible, on pdf, since basically I need to markup multi-page documents with BBoxes.
I couldn't find any suitable templates or hints, so I decided to reach out for your help.

Thank you in advance!

**Comment by makseq** [comment]
Hello, 

BBoxes are available only for images (jpg, png, gif), so you should save all your pages as different images. If you need multiple pages, you can use different `<Image value="$image1">` in the same labeling config.

**Comment by tatiana-iazykova** [comment]
Okay... Got it. Will the solution with different `<Image value="$image1"> <Image value="$image2">` work if the number of images is not determined?

**Comment by makseq** [comment]
You can try another way - the Repeater tag - https://github.com/heartexlabs/label-studio-frontend/pull/346/files#diff-418690bbcabf557b26554241aa68cee610c402d10c44528307f14367bed94871R4 , it works, but it's not fully supported.

**Comment by tatiana-iazykova** [comment]
Looks promising, but I don't fully understand how to use it to unify images, for example, from the same folder. Imagine the following structure of the data with uploading through sync (local storage) where each file is divided into pages and those pages are in one folder. Could you please run me through through the process of creating config for that structure?

**Comment by makseq** [comment]
@tatiana-iazykova You have to use custom task files in JSON format to describe this folder structure in Label Studio. Storage sync won't work here.
