### ISSUE TITLE
3D-based annotations?

### ISSUE THREAD

**Issue by klintan** [heartexlabs/label-studio#210]
**Describe the solution you'd like**
Would love to be able to annotate 3D bounding boxes for pointcloud data. Do you have any plans for this? 

**Describe alternatives you've considered**
https://github.com/springzfx/point-cloud-annotation-tool
https://github.com/bernwang/latte
https://github.com/yzrobot/cloud_annotation_tool

**Comment by deppp** [comment]
Hey @klintan, probably not till the next couple of versions. We have time-series & videos next. Then 3d. But thanks for the references!

**Comment by davodogster** [comment]
@deppp Hi Michael! I saw your post here about TIME SERIES labelling https://datascience.stackexchange.com/questions/38080/interactive-labeling-annotating-of-time-series-data. I'd love to give this a go! How do I set it up? Best Regards, Sam
