### ISSUE TITLE
Validation error - These fields are not present in the data: image

### ISSUE THREAD

**Issue by ijmiller2** [heartexlabs/label-studio#2102]
**Describe the bug**

I’m stuck on another validation error, which I believe to be some kind of bug. I have had previous issues with validation errors (e.g., re: issue #1620 where @triklozoid was able to resolve the issue, although I think somewhat manually), which effectively block my ability to use the Labeling Interface any further. But this time the error refers to a missing “image” field, yet I’m not seeing any tasks in this project without an image. Even if I export all of the data and look for tasks missing the "image" data field, I find none; all appear to be present and contain valid URLs. And this hasn’t been an issue in this project previously. It seems to have cropped up somewhat spontaneously and I have no way of tracking down its source. Deleting tasks that were created prior to the appearance of this bug did not appear to resolve it. However, copying the config and all of the data into a new project seems to resolve it (although this approach is not a viable or sustainable solution for our use case). Sarah Moir (who has kindly helped me troubleshoot in Slack) was able to use this same labeling config and data with a new project and noted that it "worked perfectly with no errors, so I’m wondering if maybe label studio is just confused somehow?"

**To Reproduce**
1. Go to Enterprise project (9619)
2. Click on "Settings" > "Labeling Interface"
3. See error

**Expected behavior**
It would be helpful to troubleshoot these validation errors if some offending task id(s) were listed somewhere in the error message. Otherwise it’s quite difficult / impossible to find the source of the error and the labelling interface remains locked to any changes / updates.

Our live app (we have data coming in live from a mobile app [and we're using Label Studio for a human-in-the-loop strategy]) is attached to this project, so having to create a whole new project every time we encounter a validation error is not really sustainable. We would have to continuously update our backend code that responds to the Label Studio webhook and lose the "created at" timestamps - which are quite helpful to us - if we were to reimport everything to a new project each time we hit a validation error like this. So it seems like the simplest or at least most robust solution would be to update the validation logic to be a bit more tolerant of dynamic data and/or clarify the source of the error so that it can be rectified.

**Screenshots**
![image](https://user-images.githubusercontent.com/8560151/157270899-6c80bac4-b39b-4ece-b11c-6e0d459cdbc9.png)

**Environment (please complete the following information):**
 - Enterprise version
 - Label Studio Version 1.4.1post1:
 
 ```json
{"release": "2.1", "label-studio-os-package": {"version": "1.4.1post1", "short_version": "1.4", "latest_version_from_pypi": null, "latest_version_upload_time": null, "current_version_is_outdated": false}, "label-studio-os-backend": {"message": "feat: DEV-1238: Add video object detection template", "commit": "d170a762cb8b4d42a8040753348c934840fdf3bf", "date": "2022-03-03 14:38:17 +0300", "branch": "develop", "version": "20220303.113901-release-d170a762"}, "label-studio-frontend": {"message": "fix: DEV-1784: Fix drawing hanging when region is tiny (#516) CHANGELO ...", "commit": "9f7d62", "branch": "HEAD", "date": "2022/03/02 11:56:56"}, "dm2": {"message": "feat: DEV-1621: Add usage of new method to create annotation (#34) COD ...", "commit": "48ac59", "branch": "HEAD", "date": "2022/02/16 19:59:52"}, "label-studio-converter": {"version": "0.0.39"}, "label-studio-enterprise-backend": {"message": "feat: DEV-1238: Add video object detection template", "commit": "d170a762cb8b4d42a8040753348c934840fdf3bf", "date": "2022-03-03 14:38:17 +0300", "branch": "develop", "version": "20220303.113901-release-d170a762"}, "label-studio-enterprise-package": {"version": "20220303.113901-release-d170a762"}, "label-studio-react-app": {"message": "Migrate api (#97) Co-authored-by: Max Tkachenko <makseq@gmail.com>", "commit": "a0b44e12d28dcb4d1f2a781ea6cd8c6786983e55", "branch": "HEAD", "date": "2022/02/18 04:27:52"}, "lsf": {"message": "fix: DEV-1784: Fix drawing hanging when region is tiny (#516) CHANGELO ...", "commit": "9f7d62", "branch": "HEAD", "date": "2022/03/02 11:56:56"}, "backend": {"commit": "d170a7"}}
```

**Additional context**
I have corresponded with Sarah Moir in Slack, both in the "general" channel [here](https://label-studio.slack.com/archives/CQ8LYPPJS/p1645753191924519) and in DM.

**Comment by ijmiller2** [comment]
FYI, just trying to read through some similar issues for any overlap. I think this error might be related to #1683. However, even if I clear all instances of `required="true"` from the config, I still get this error.

**Comment by makseq** [comment]
@ijmiller2 Hi, we had some bug fixes regarding required=true, if you could check the `develop` branch of github LS, it would be perfect!

**Comment by ijmiller2** [comment]
Hey @makseq, thanks for the heads up! We're using the enterprise version and the error message went away when we started a new project with the same template and exported dataset (not an ideal solution but a temporary workaround). So not sure if I'd have any good way to test it even if I used the `develop` branch locally.

Looks like the error still shows up in the old project. Here's the version info: 
```
{"release": "2.2.7", "label-studio-os-package": {"version": "1.4.1post1", "short_version": "1.4", "latest_version_from_pypi": null, "latest_version_upload_time": null, "current_version_is_outdated": false}, "label-studio-os-backend": {"message": "fix: DEV-2354: Fix skip queue (#2439)", "commit": "18e40e161eb886917fb40908ecd78ecf4399f944", "date": "2022-05-11 17:55:21 +0400", "branch": "HEAD", "version": "2.2.7-hotfix.2"}, "label-studio-frontend": {"message": "fix: DEV-2300: Wrong readonly resolution in Result (#606)", "commit": "22750c52268ce7220d01692657f3b7e21c167766", "branch": "fix/dev-1642/region-textarea-copy", "date": "2022/05/04 17:53:41"}, "dm2": {"message": "fix: DEV-2266: no comments with toggle off (#53)", "commit": "0129979a0f6bb9010c472d3da90ee22b8154aa62", "branch": "release/2.2.7", "date": "2022/04/29 16:26:17"}, "label-studio-converter": {"version": "0.0.40"}, "label-studio-enterprise-backend": {"message": "fix: DEV-2354: Fix skip queue (#2439)", "commit": "18e40e161eb886917fb40908ecd78ecf4399f944", "date": "2022-05-11 17:55:21 +0400", "branch": "HEAD", "version": "2.2.7-hotfix.2"}, "label-studio-enterprise-package": {"version": "2.2.7-hotfix.2"}, "label-studio-react-app": {"message": "fix: DEV-1711: Add requeue toggle for annotators (#141)", "commit": "b4644a5f8fcb276c0d4f7180883ecc6dead04a89", "branch": "DEV-1823", "date": "2022/05/02 16:13:47"}}
```

**Comment by makseq** [comment]
Oh, sorry, I missed `"release": "2.2.7"` :-)

**Comment by makseq** [comment]
@ijmiller2 please let me know a project number where I can reproduce this issue (if you are on app.heartex.com).

**Comment by ijmiller2** [comment]
https://app.heartex.com/projects/9619/

**Comment by makseq** [comment]
@ijmiller2 Sorry for the delay. I fixed this issue.

**Comment by ijmiller2** [comment]
Oh great, thank you! Looks like that validation error is gone from the project.
