### ISSUE TITLE
Changing the label of an existing (image) annotation

### ISSUE THREAD

**Issue by ncryer** [heartexlabs/label-studio#213]
**Is your feature request related to a problem? Please describe.**

Currently the only way to change the label of an (image bbox) annotation is to delete it and create a new one. 

**Describe the solution you'd like** 

If you have pre-existing annotations, e.g. bounding boxes, but would like to re-label them, it should be possible to simply click the RectRegion object, click on a Label button, and press `Update`.

**Additional context**
I've only tested this for the image bbox task.

**Comment by deppp** [comment]
Fixed in the latest 0.5.0 release
