### ISSUE TITLE
import data from url and file seems behaving differently 

### ISSUE THREAD

**Issue by lfoppiano** [heartexlabs/label-studio#2131]
**Describe the bug**
I'm trying to import the data to be annotated using an URL which point to an application that automatically generate the correct json format for label studio. 

When I import via the URL the data is imported as a single empty file: 

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/15426/158293342-ec5460e0-d2f8-41b7-ae99-0bf5666dad4a.png">

however if I save the same content that is provided via the URL as a json file and import it, it works. 

I'm attaching a sample: 
[new.json.zip](https://github.com/heartexlabs/label-studio/files/8249644/new.json.zip)

**To Reproduce**
1. Go to import
2. choose a url that provide the data in attachment
3. click on import
4. you will see just one entry in the task list

**Expected behavior**
I expect that several tasks are imported 

**Environment (please complete the following information):**
 - OS: MacOs Mojave
 - Label Studio Version 1.4

```json
{
  "release": "1.4.1post1",
  "label-studio-os-package": {
    "version": "1.4.1post1",
    "short_version": "1.4",
    "latest_version_from_pypi": "1.4.1.post1",
    "latest_version_upload_time": "2022-02-12T00:44:06",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "DEV-1889: support r/o root file system (#2126)",
    "commit": "80f689813f95831f4d0e32d89626f0cbb93e7ea0",
    "date": "2022-03-14 15:02:45 +0400",
    "branch": "master",
    "version": "80f6898"
  },

  "label-studio-frontend": {
    "message": "DEV-1373: Fix relations over brushes (#398)  * Add test for relations  ...",
    "commit": "3116fcb2a73c4e53b6375abcdff8a095479e08db",
    "branch": "master",
    "date": "2022-03-11T13:00:34Z"
  },

  "dm2": {
    "message": "feat: DEV-1621:  Add usage of new method to create annotation",
    "commit": "8975918038340887dbe42096c17e2df06aab2152",
    "branch": "feat/DEV-1621/interactive_mode",
    "date": "2022-02-15T19:29:50Z"
  },

  "label-studio-converter": {
    "version": "0.0.39"
  }
}
```

**Additional context**

**Comment by makseq** [comment]
You should add valueType="url" to your <Text> tag.

**Comment by lfoppiano** [comment]
Sorry, @makseq which tag are you talking about? I did not get it

**Comment by makseq** [comment]
What is your labeling config?

**Comment by lfoppiano** [comment]
You mean this? 

```xml
<View>
  <Labels name="label" toName="text">
  <Label value="material" background="#FFA39E"/><Label value="pressure" background="#D4380D"/><Label value="tcValue" background="#FFC069"/><Label value="me_method" background="#AD8B00"/><Label value="tc" background="#D3F261"/><Label value="class" background="#389E0D"/></Labels>

  <Text name="text" value="$text"/>
</View>
```

**Comment by makseq** [comment]
Let's try to use this:

```
<View>
  <Labels name="label" toName="text">
  <Label value="material" background="#FFA39E"/><Label value="pressure" background="#D4380D"/><Label value="tcValue" background="#FFC069"/><Label value="me_method" background="#AD8B00"/><Label value="tc" background="#D3F261"/><Label value="class" background="#389E0D"/></Labels>

  <Text name="text" value="$text" valueType="url"/>
</View>
```

**Comment by lfoppiano** [comment]
Thanks. 

I tried, it's better as I can see the data, but it is not parsed: 

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/15426/158718150-16206df0-3131-4eee-abf4-3abecf7a3488.png">

**Comment by makseq** [comment]
Ok, I see that you need to import this file directly to LS and use this config:

```
<View>
  <Labels name="label" toName="text">
  <Label value="material" background="#FFA39E"/><Label value="pressure" background="#D4380D"/><Label value="tcValue" background="#FFC069"/><Label value="me_method" background="#AD8B00"/><Label value="tc" background="#D3F261"/><Label value="class" background="#389E0D"/></Labels>

  <Text name="text" value="$text" />
</View>
```

**Comment by lfoppiano** [comment]
Yes but I want to import the data from an URL as here: 
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/15426/158924480-7649e61a-a7b7-496e-81b4-19e6ec33edaa.png">

Why is not working? What should I change to make it work?

**Comment by lfoppiano** [comment]
@makseq any idea about this issue?

**Comment by makseq** [comment]
@lfoppiano I used this labeling config

```
<View>
  <Labels name="label" toName="text">
  <Label value="material" background="#FFA39E"/>
    <Label value="pressure" background="#D4380D"/>
    <Label value="tcValue" background="#FFC069"/>
    <Label value="me_method" background="#AD8B00"/>
    <Label value="tc" background="#D3F261"/>
    <Label value="class" background="#389E0D"/>
  </Labels>

  <Text name="text" value="$text"/>
</View>
```

and your file https://github.com/heartexlabs/label-studio/files/8249644/new.json.zip and it works.

However, you have a problem with region ids there, they must be strings, e.g.:

```
{"id": 0, "from_name": "label", "to_name": "text", "type": "labels", "value": {"start": 38
```
=>
```
{"id": "0", "from_name": "label", "to_name": "text", "type": "labels", "value": {"start": 38
```

**Comment by makseq** [comment]
https://user-images.githubusercontent.com/501780/160943666-4ea65eee-05eb-4d42-b0d1-a31e5738e351.mp4
