### ISSUE TITLE
中文支持？

### ISSUE THREAD

**Issue by Colton34** [heartexlabs/label-studio#2136]
有中文支持吗？如果可以的话 我可以参与翻译工作？

**Comment by makseq** [comment]
Unfortunately no, but we had some tries from our contributors - https://github.com/heartexlabs/label-studio/pull/1409.

**Comment by joshuafc** [comment]
@ghplvh 我创建了一个新的PR, #2421 , 在 #1409 的基础上，增加了机翻版本的中文支持，你最近有时间参与翻译工作吗？

**Comment by ghplvh** [comment]
哈哈哈，可以呀，但是好像不给合并进去？

**Comment by lizheng419** [comment]
> 哈，可以呀，但是想要不给合并通道？

请问汉化弄好了吗

**Comment by niuma147** [comment]
Is there a Chinese version available now?

**Comment by Keekuun** [comment]
only Editor i18n：https://github.com/Keekuun/label-studio/tree/i18n
