### ISSUE TITLE
Python 3.5.3 compatibility issue

### ISSUE THREAD

**Issue by hachreak** [heartexlabs/label-studio#214]
**Describe the bug**
Hi at all,
I'm working on Debian 9 with Python 3.5.3.
It looks like there is a issue with python < 3.6 with the [json module](https://github.com/heartexlabs/label-studio/blob/master/label_studio/utils/uploader.py#L39).

**To Reproduce**
1. Go to 'Import' page
2. Click on 'Import' button after select a json file.
3. `TypeError: the JSON object must be str, not 'bytes'`

**Expected behavior**
Import json file.

**Screenshots**
![import_error](https://user-images.githubusercontent.com/377047/74343086-c5691a00-4daa-11ea-87bb-53e2e5b0d49b.jpg)

**Environment (please complete the following information):**
 - OS: Debian
 - Browser chromium
 - Version [73.0.3683.75 ]
 - python version: 3.5.3

For python 3.5.3 this code works:

```python
def tasks_from_file(filename, file):
    try:
        if filename.endswith('.csv'):
            tasks = pd.read_csv(file).fillna('').to_dict('records')
            tasks = [{'data': task} for task in tasks]
        elif filename.endswith('.tsv'):
            tasks = pd.read_csv(file, sep='\t').fillna('').to_dict('records')
            tasks = [{'data': task} for task in tasks]
        elif filename.endswith('.txt'):
            lines = file.read().splitlines()
            tasks = [{'data': {settings.UPLOAD_DATA_UNDEFINED_NAME: line.decode('utf-8')}} for line in lines]
        elif filename.endswith('.json'):
            # [FIX]
            raw_data = file.read()
            tasks = json.loads(raw_data.decode('utf8'))
            # [/FIX]
            #  tasks = json.load(file)  # try simple json
        else:
            raise ValueError('Unsupported input file format')
    except Exception as exc:
        raise ValidationError('Failed to parse input file ' + filename + ': ' + exc)
...
```

**Comment by niklub** [comment]
Hi, @hachreak ! Thanks for reporting this and your suggestion about the fix. We have included this in latest release v0.4.7 - please, try to update `pip install label-studio` and check whether the error disappears
