### ISSUE TITLE
API export to json with "download_all_tasks" flag doesn't work

### ISSUE THREAD

**Issue by wojnarabc** [heartexlabs/label-studio#2150]
**Describe the bug**
When trying to export all content from our project with:
`curl -X GET http://localhost:8080/api/projects/2/export?exportType=JSON&download_all_tasks=true -H 'Authorization: Token tokenid ' -o 'annotations_api.json'`
i'm getting "no matches found: http://localhost:8080/api/projects/2/export?exportType=JSON" error
This one works fine: `curl -X GET http://localhost:8080/api/projects/2/export -H 'Authorization: Token tokenid ' -o 'annotations_api.json'`

Some context: i have ml backend running underneath and would like to export all project content, not just annotated samples. According to https://labelstud.io/api#operation/api_projects_export_read is should be possible with call constructed as above. 

**To Reproduce**
1. Go to Label Studio frontend and create a Named Entity Recognition project
2. Annotate some texts 
3. Export annotations with API call mentioned above

**Expected behavior**
According to documentation it should export all tasks, including skipped tasks and others without annotations

**Screenshots**
Not applicable - just a terminal error

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Label Studio Version [checked with 1.4.1 and 1.4.1.post1 ]

**Additional context**
-

**Comment by makseq** [comment]
Do you have more logs?

**Comment by makseq** [comment]
Try to call this: 
```
curl -X GET "http://localhost:8080/api/projects/2/export?exportType=JSON&download_all_tasks=true" -H 'Authorization: Token tokenid ' -o 'annotations_api.json'
```

**Comment by wojnarabc** [comment]
works well with quotation marks, thanks @makseq
