### ISSUE TITLE
Clone (duplicate) project

### ISSUE THREAD

**Issue by tilusnet** [heartexlabs/label-studio#2160]
**Describe the solution you'd like**
It's occasionally useful to start off a copy of an existing project, eg. for experimenting. 

**Describe alternatives you've considered**
Setting up a complex identical project is laborious and prone to human errors.

**Comment by makseq** [comment]
Thank you for your feedback and idea. We are working on this feature. As a workaround you can export your dataset into JSON file and then re-import it in a new project with the same labeling config.

**Comment by tilusnet** [comment]
I didn't think of that, thanks for the tip.
