### ISSUE TITLE
Exported records are not consistent with tasks in current tab

### ISSUE THREAD

**Issue by tilusnet** [heartexlabs/label-studio#2164]
**Describe the bug**
I have 3-4 tabs active in the project, each having a different filter set. This results in a different number of tasks listed in each tab, as expected.
If I Export, I'd expect the exported json file to contain the same number of records as tasks seen in the tab I exported from. This is not the case: I always get the same, apparently random number of records exported, regardless of the tab I export from.

In my case:
tab 1 = 19 tasks
tab 2 = 1 task
tab 3 = 1,745 tasks
tab 4 = 682 tasks

No matter which tab I export from, I get the same 683 records in the JSON file. 
Notice that no tab contains 683 tasks! I have no idea which 683 tasks I am getting.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a number of tabs for your project, each resulting a different  number of tasks (eg. use filters). Assume tab 1 has 10 tasks, tab 2 has 20.
2. Select tab 2 and click Export -> JSON
3. Select tab 1 and click Export -> JSON
4. The two exported files do not reflect the number of tasks in their respective tabs, 20 and 10, respectively, but some other number.

**Expected behavior**
Number of records exported should reflect the number of tasks in the tab where the export was executed from.

**Environment (please complete the following information):**
 - OS: Ubuntu 64-bit (Docker)
 - Label Studio Version 1.4.1post1

**Comment by makseq** [comment]
The export doesn't take into account tabs. It exports only labeled tasks. So, this number - 683 tasks - is amount of tasks with annotations. 

If you want to export tasks from tabs, you can try use API or SDK with snapshots:
https://labelstud.io/sdk/project.html#label_studio_sdk.project.Project.export_snapshot_create

**Comment by tilusnet** [comment]
Hmm, I see.

Though my example got 682 annotated tasks, as per the filter "Where Annotations > 0".
Close, but still not accurate?

**Comment by makseq** [comment]
also cancelled annotation won't be taken into account

**Comment by tilusnet** [comment]
Ah, it has to do with cancelled tasks indeed, but it's the other way around:
tasks with cancelled annotation will be added to the exported annotated tasks.
Hence I got 682 annotated + 1 cancelled annotation = 683 exported records in total.

@makseq would you mind documenting these important details:
* export will always include annotated tasks only regardless of filters set
* cancelled annotation tasks will be included in the exported result 

Thanks.

**Comment by tilusnet** [comment]
also in line with the logic implemented, the UI could become more intuitive:
move the Export button outside of the tabs, so that it is clear that its context is not tab (and filter) bound.

**Comment by makseq** [comment]
@tilusnet Thank you for your suggestions! I've updated docs.
