### ISSUE TITLE
Labelling page does not work with HTTPS redirect

### ISSUE THREAD

**Issue by guneemwelloeux** [heartexlabs/label-studio#217]
**Describe the bug**
After deploying the app behind a HTTPS-redirecting proxy, the Labelling page does not work anymore.

**To Reproduce**
1. Deploy the app behind NGINX, configured to redirect HTTP to HTTPS requests
2. Go to Labelling
3. See error in console: 
`Mixed Content: The page at 'https://label.mydomain.dev/' was loaded over HTTPS, but requested an insecure resource 'http://label.mydomain.dev/api/projects/1/next/'. This request has been blocked; the content must be served over HTTPS.`

**Expected behavior**
The app should follow all the redirects and the api call should succeed, the scheme being conserved at each step of the way.

**Environment (please complete the following information):**
 - OS: macOS
 - Browser Chrome 
 - Version 80.0.3987.87

**Additional context**
I believe the redirect issued by label-studio upon calling "api/projects/1/next" is not taking the scheme into account, when it should

**Comment by niklub** [comment]
There is no easy way to support HTTPS in Label Studio. I suggest you may try to do the following modifications in `server.py` file:

1. SSLify flask app using
```python
from flask_sslify import SSLify
...
sslify = SSLify(app, permanent=True)
```

2. Add certificates to SSL context while running app, i.e. when app.run is launched, add
```python
app.run(
            host='0.0.0.0',
            port=input_args.port,
            debug=input_args.debug,
            ssl_context=(
                'fullchain.pem',
                'privkey.pem'
            )
        )
```

Hope this helps!

**Comment by rverma-jm** [comment]
This solution may work when we do ssl termination at the app, what if we want to do the ssl termination at loadbalancer?

**Comment by vincenzomanzoni** [comment]
The solution proposed by @niklub works when the app does the SSL termination. However, since in my case is behind a reverse proxy (traefik), the optimal soution would be to conserve the scheme for every call. Any suggestions?

**Comment by kretes** [comment]
I did a try on getting https work using: https://github.com/kretes/label-studio/tree/https#this-fork-just-contains-a-try-to-get-https-working-in-docker-compose-removed-postgres-btw by changing the nginx configuration. Any comments welcome.

Labelling works over https with this approach.
