### ISSUE TITLE
Automatic login 

### ISSUE THREAD

**Issue by kaysagit** [heartexlabs/label-studio#2181]
In a closed issue a user reported that with this command the login is automatic and must not be done in the GUI

label-studio start --username <username> --password <password>

However when I run this command, it just says that the user already exists and brings me back to the login screen. I want that the users of my application do not see the login screen.

Am I missing something?

**Comment by makseq** [comment]
Please check this docs
https://labelstud.io/guide/signup.html#Create-an-account

This options (--username / --password) only create a new user, it's not for auto login.
