### ISSUE TITLE
To Add supporting html and hocr format for ocr converted scanned images

### ISSUE THREAD

**Issue by navdeep1604** [heartexlabs/label-studio#219]
**Is your feature request related to a problem? 

I have lot of scan pdf, I pass through kcr which gives hocr or html format. I need to import those format to do annotation

**Describe the solution you'd like

I want the tool to support html and hocr format in order to support ocr output files

**Describe alternatives you've considered**

**Additional context**

**Comment by deppp** [comment]
The HTML format labeling is supported, please consult the documentation. HOCR will not be supported anytime soon, but we'd be happy to see your contributions! :-)
