### ISSUE TITLE
Cannot Deploy on Google Cloud.

### ISSUE THREAD

**Issue by bbreton3** [heartexlabs/label-studio#2191]
**Describe the bug**
I tried clicking on the "deploy to Google Cloud button, but it doesn't seem to work"
**To Reproduce**
1. Go to the Readme
2. Cupy the URL of the repo
3. Click on the "Deploy to Google Cloud" button
4. Paste the url of the repo

**Expected behavior**
I extected the deployment to start

**Screenshots**
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/16150165/161337672-5e81720e-e706-43b9-91ae-1eebf756ead8.png">

After cloning the repo, I get this error:
```bash
Error: error attempting to read the app.json from the cloned repository: failed to parse app.json file: failed to parse app.json: json: unknown field "addons"
```

**Environment (please complete the following information):**
 - Google Cloud Platform

**Additional context**
I think the app.json is a Heroku file that has been mistaken for an Google App Engine configuration.
Has anyone figured out a way to deploy on GCP ?

**Comment by farioas** [comment]
Hi @bbreton3, thanks for the report!

Looks like it is a known issue with Cloud Run and Heroku single-click manifests, as they both uses the same app.json: https://github.com/GoogleCloudPlatform/cloud-run-button/issues/112

Currently I'm working on the fix

**Comment by farioas** [comment]
Fixed. Please try to click on the button again.
