### ISSUE TITLE
How to apply HyperTextLabels to multiple HyperText elements?

### ISSUE THREAD

**Issue by BruceStayHungry** [heartexlabs/label-studio#2207]
**Describe the bug**
How to apply HyperTextLabels to multiple HyperText elements?

**To Reproduce**
I have tried to use the comma to add multiple HyperText names into the `toname` attribution of the HyperTextLabel, but it seems not to work.
`<HyperTextLabels name="ner" toName="text1,text2">`
    `    <Label value="Person" background="#00faf6"/>`
    `    <Label value="Location" background="#0dd353"/>`
`</HyperTextLabels>`

`<HyperText name="text1" value="$sentence1"/>`
`<HyperText name="text2" value="$sentence2"/>`

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Label Studio Version 1.4.1

I would be deeply grateful for your help.

**Comment by makseq** [comment]
You have to use different labels for different HyperTexts:

```
<HyperTextLabels name="ner1" toName="text1">
<Label value="Person" background="#00faf6"/>
<Label value="Location" background="#0dd353"/>
</HyperTextLabels>
<HyperText name="text1" value="$sentence1"/>

<HyperTextLabels name="ner2" toName="text2">
<Label value="Person" background="#00faf6"/>
<Label value="Location" background="#0dd353"/>
</HyperTextLabels>
<HyperText name="text2" value="$sentence2"/>
```
