### ISSUE TITLE
Floats and integers are not interpreted accordingly when imported from JSON

### ISSUE THREAD

**Issue by tilusnet** [heartexlabs/label-studio#2212]
**Is your feature request related to a problem? Please describe.**
When I import my data in [basic JSON format](https://labelstud.io/guide/tasks.html#Basic-Label-Studio-JSON-format), I cannot make LS interpret integers or floats. Eg.:
```
...
"data": {
   "my_proba": 0.456
   "my_int": 12
   ...
}
...
```
Ideally I'd also like to be able to _filter_ on these values using _operators_ like >= etc.

**Describe the solution you'd like**
Diversify data type interpretation when importing from JSON format.

**Comment by makseq** [comment]
Please, see this little tutorial: 
https://user-images.githubusercontent.com/501780/162335009-03a2d6e7-a089-4952-8f16-f47b3657177a.mp4
