### ISSUE TITLE
How to run on macbook m1 pro?

### ISSUE THREAD

**Issue by santhoshnumberone** [heartexlabs/label-studio#2218]
How to run `label-studio` locally on macbook m1 pro?

**Comment by KevinQuiring** [comment]
Hi @santhoshnumberone, can you elaborate a bit more on what issues you are experiencing running label-studio on arm and how you are running the project?

I can confirm that running the latest development branch via docker-compose produces the following error:

`The chromium binary is not available for arm64. `

If this is what you are experiencing, you can try adding these lines to your dockerfile https://github.com/heartexlabs/label-studio/pull/2226/files which allows me to build the latest branch locally via docker-compose.  

Let me know if this helps.

**Comment by santhoshnumberone** [comment]
`Docker` working on `macbook m1`

Followed this link [heartexlabs/label-studio](https://hub.docker.com/r/heartexlabs/label-studio#install-locally-with-docker)

```
docker pull heartexlabs/label-studio:latest
docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:latest
```

Ran on browser
`http://localhost:8080`
