### ISSUE TITLE
Threads setting and significance

### ISSUE THREAD

**Issue by amitbcp** [heartexlabs/label-studio#2220]
While starting Label Studio I am getting the following message : 

`Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Initializing database..`

What does NumExpr does ? it is threads for DB connection or multiple annotation projects connection ?

**Comment by makseq** [comment]
Most likely you are not using virtualenv for LS, and you have installed numexpr library there. It's not related to DB.
