### ISSUE TITLE
width and maxWidth tags in safari don't work as expected

### ISSUE THREAD

**Issue by agrigoriev** [heartexlabs/label-studio#2222]
When using width option like in this configuration:

```
<View>
  <Image name="image" value="$image" zoom="true" zoomControl="true" width="200%"/>
  <View><Filter toName="label" minlength="0" name="filter"/><RectangleLabels name="label" toName="image">
  <Label value="Tree" background="#c3d117"/></RectangleLabels></View>
</View>
```

<img width="1440" alt="Screen Shot 2022-04-11 at 20 52 11" src="https://user-images.githubusercontent.com/232081/162790925-b3eac56e-813c-4081-be2e-fa4204777982.png">

The canvas is limited to the original image width, zooming the image and cropping its part.
maxWidth option doesn't make situation better - I was trying to us both "maxWidth=200%" and fixed pixel width, but it doesn't change anything.

**Comment by hlomzik** [comment]
Hi, Alexey! Sadly, current image size and scaling calculations are far from perfect. And also `width` is used for initial image width, but it can't be higher than 100%. And `maxWidth` is basically useless. You can use `maxHeight=""` or `maxHeight="auto"` to not limit image height, so the width will be 100%, but image can be higher than the screen.

We are working on much better version, you can check it in [LSF branch](https://github.com/heartexlabs/label-studio-frontend/pull/531). For this image on your screenshot it'll not change anything on the start. But it'll not crop image on zoom, which is good.
