### ISSUE TITLE
v1.4.1: Image URLs are broken in docker-compose when using sub-paths

### ISSUE THREAD

**Issue by ferenc-hechler** [heartexlabs/label-studio#2230]
**Describe the bug**
I tested a local docker-compose installation with a sub-path configured as described in https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-with-a-host-and-sub-path
The applications works fine but uploaded images are broken, because the URL is missing the sub-path prefix. Using the version 1.4.0 works fine, but when using v1.4.1 (or latest) Image URLs are broken.

**To Reproduce**
1. git clone https://github.com/heartexlabs/label-studio.git 
2. cd label-studio
3. LABEL_STUDIO_HOST=http://localhost:8080/foo docker-compose up -d
4. Open URL in browser: http://localhost:8080/foo
5. sign up
6. create new project
7. go to "Labelling Setup" and select a "Computer Vision" template
8. go to "Data Import" and upload an image file
9. click on "import"
10. the image is not visible (broken) in the table
11. click on the image, an error appears which has a link to the image
12. the link is "http://localhost:8080/data/upload/1/image.png", the sub-path "/foo/" is missing
13. Manually opening the url "http://localhost:8080/foo/data/upload/1/image.png" shows the uploaded image

**Expected behavior**
Image URLs should have the "/foo" sub-path 

**Screenshots**
-

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version v1.4.1

**Additional context**
-

**Comment by makseq** [comment]
@ferenc-hechler Could you please check this branch https://github.com/heartexlabs/label-studio/pull/2254 ? You should import images from the scratch again.

**Comment by ferenc-hechler** [comment]
I did a docker build in branch "fix/issue-2230" and used this image in a completely new deployment.
I created a new project, uploaded two files and the image urls are as expected.
Thanks for the fix.   :-)

We currently work with the version 1.4.0 to work around the problems. 
Can I upgrade to the fixed version and the image URLs uploaded with v1.4.0 are still correct?

**Comment by makseq** [comment]
@ferenc-hechler Thanks you for your feedback. This branch is merged and will be included to the upcoming release (1.4.2).
