### ISSUE TITLE
Format URL links in annotation interface

### ISSUE THREAD

**Issue by RadionBik** [heartexlabs/label-studio#2236]
**Is your feature request related to a problem? Please describe.**
I have tried to find any hints in the docs on how to enable support for URL link formatting in a custom annotation interface, but without any success.

Let's say, I have a file identifier field `file_id` within `data` dict that is being imported to LS. I want to format this identifier as a clickable URL link, e.g. file_id = 123qwezxc for a given task and I want to be able to click on the generated link: 
https://someconstlink.com/123qwezxc

I have attempted to do something like this:
```
  <Style> .url-field { color: blue; text-align: left; margin: 20px}</Style>
  <View className="url-field">
  	<Text name="link" value="https://someconstlink.com/$file_id"/>
  </View>
```  
But it doesn't seem to work, i.e. it doesn't save the interface code when I add this formatting.
Moreover, there is no option to make it clickable as well.
 
**Describe the solution you'd like**

An .xml key explicitly converting information to a URL, like
```
<URL name="link" value="https://someconstlink.com/$file_id"/>
```

**Comment by hlomzik** [comment]
Hi! `Text` is made for text so I don't know why do you expect it to show html %)
For html we have `HyperText`, so you can use it like this:
```xml
<HyperText clickableLinks="true" name="link" value="&lt;a href=https://google.com/q=$value>Link&lt;/a>" />
```
but we can't guarantee it will work for any data.

**Comment by hlomzik** [comment]
Important things to know:
- `clickableLinks` to make them clickable, we suppress this by default for labeling
- escape `<` as `&lt;`, also this may be required for quotes and other chars
- we render html in iframe by default, so it will open links only inside it by default; you can click with Ctrl/Cmd to open in new window, or you can add `inline="true"` to embed this html directly to the page, and you can use `target=_blank` in this case

**Comment by RadionBik** [comment]
I have tried copying the string you provided and modified at in various ways, but the config doesn't seem to persist. Every time I modify it and click the Save button no changes remain, after I go and check the tasks. 

Moreover, I am unable to recreate the examples I provided above, it resets the value field to "value=$file_id", stripping the URL part.

Is it a bug or feature? How do I circumvent it?

**Comment by RadionBik** [comment]
Sorry for asking stupid questions, I have never dealt with HTML and etc.
I have got updates, this is the configuration that has been saved and it renders the path at least, but the link is still unclickable 
```
  <View>
    <HyperText name="p1" clickableLinks="true" inline="true" target="_blank">
      <p>https://someconstlink.com/files?files=$file_id</p>
    </HyperText>
  </View>
```

**Comment by makseq** [comment]
@RadionBik please, try this one:
```
<View>
    <HyperText name="p1" clickableLinks="true" inline="true" target="_blank">
      <a>https://someconstlink.com/files?files=$file_id</a>
    </HyperText>
  </View>
```

**Comment by RadionBik** [comment]
Thank you!
Now it is highlighted like a URL, I can click on it but nothing happens, i.e. the resource is not being opened in a new or current tab :(

**Comment by makseq** [comment]
another try:
```
<View>
    <HyperText name="p1" clickableLinks="true" inline="true" target="_blank">
      <a href="https://someconstlink.com/files?files=$file_id">https://someconstlink.com/files?files=$file_id</a>
    </HyperText>
  </View>
```

**Comment by RadionBik** [comment]
great, it works! although opens the link in the same tab, but it is way better than nothing :)

**Comment by makseq** [comment]
```
<View>
    <HyperText name="p1" clickableLinks="true" inline="true" target="_blank">
      <a target="_blank" href="https://someconstlink.com/files?files=$file_id">https://someconstlink.com/files?files=$file_id</a>
    </HyperText>
  </View>
```

**Comment by RadionBik** [comment]
thank you, it works!
