### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by cri5Castro** [heartexlabs/label-studio#224]
hello im getting the following error  yesterday was ok , after cloning again i get this error 

pkg_resources.DistributionNotFound: The 'label-studio' distribution was not found and is required by the application

and in the browser 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by niklub** [comment]
Hi, @cri5Castro !

Could you please give us more details about what you've done:
- How do you install label-studio, which OS environment do you use
- What's the version where the error reproduces (`pip freeze | grep label-studio`)
- Exact launch command
