### ISSUE TITLE
Label-studio will not start in previously working environment

### ISSUE THREAD

**Issue by dvwright** [heartexlabs/label-studio#2245]
**Describe the bug**
Label-studio has been installed and in a working state. Then 'out of nowhere' it will not start.

**To Reproduce**
1. python label_studio/manage.py runserver

**Expected behavior**
starts and runs as expected

**Environment (please complete the following information):**
 - OS: `Mac OSX Monterey 12.3.1 M1`
 - Label Studio Version `1.4.1post1`

**Additional context**
Label-studio will not start from previously working setup

* is properly set up and running
* stop server, then will not start anymore
* no code changes have been made

```
python label_studio/manage.py runserver
...
Performing system checks...
...
Exception in thread django-main-thread:
...
...
...
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'data_manager.actions.'
```

Issue:
`data_manager/actions/__init__.py` tries to import python modules on start
if a non python file appears in the path, it triggers the module not found exception (in my case `.next.py.swp`) 

Attaching PR

after PR applied:

``` 
python label_studio/manage.py runserver
...
...
Performing system checks...

No module named 'data_manager.actions.__pycache_'
No module named 'data_manager.actions.tag'
System check identified no issues (1 silenced).
...
...
Django version 3.1.14, using settings 'core.settings.label_studio'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
```

**Comment by yangboz** [comment]
> **Describe the bug** Label-studio has been installed and in a working state. Then 'out of nowhere' it will not start.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. python label_studio/manage.py runserver
> 
> **Expected behavior** starts and runs as expected
> 
> **Environment (please complete the following information):**
> 
> * OS: `Mac OSX Monterey 12.3.1 M1`
> * Label Studio Version `1.4.1post1`
> 
> **Additional context** Label-studio will not start from previously working setup
> 
> * is properly set up and running
> * stop server, then will not start anymore
> * no code changes have been made
> 
> ```
> python label_studio/manage.py runserver
> ...
> Performing system checks...
> ...
> Exception in thread django-main-thread:
> ...
> ...
> ...
>     return _bootstrap._gcd_import(name[level:], package, level)
> ModuleNotFoundError: No module named 'data_manager.actions.'
> ```
> 
> Issue: `data_manager/actions/__init__.py` tries to import python modules on start if a non python file appears in the path, it triggers the module not found exception (in my case `.next.py.swp`)
> 
> Attaching PR
> 
> after PR applied:
> 
> ```
> python label_studio/manage.py runserver
> ...
> ...
> Performing system checks...
> 
> No module named 'data_manager.actions.__pycache_'
> No module named 'data_manager.actions.tag'
> System check identified no issues (1 silenced).
> ...
> ...
> Django version 3.1.14, using settings 'core.settings.label_studio'
> Starting development server at http://127.0.0.1:8080/
> Quit the server with CONTROL-C.
> ```

I also tried the docker version, and verified the docker-compose within pSQL, tables ready, but the docker or runserver version used sqlite, maybe the table not initialized.

**Comment by khlaifiabilel** [comment]
Greetings 

I had a similar problem in Ubuntu 20.04 LTS, I had to install "net-tools" using the command :  `sudo apt install net-tools`, then run `sudo netstat -lpn |grep :8080` to list all info you need, then all you had to do is to kill `kill -9 ID`.

I think that will be the same for Mac OS
