### ISSUE TITLE
Question: Is there any upper limit for NER task?

### ISSUE THREAD

**Issue by teohsinyee** [heartexlabs/label-studio#2255]
I need to annotate around 100k lines of text under 1 project. is it possible?

![image](https://user-images.githubusercontent.com/56106630/163916096-c524c357-1cda-48bb-bb80-a8c9bd7cecd3.png)

**Comment by makseq** [comment]
@teohsinyee yes, it's possible, LS doesn't have any task or annotation limits. Everything is limited by your hardware and database performance.
