### ISSUE TITLE
PROJECT_CREATED webhook doesn't work

### ISSUE THREAD

**Issue by MSalehiA** [heartexlabs/label-studio#2260]
**Describe the bug**
Hi, according to this [guide](https://labelstud.io/guide/webhook_reference.html#Project-Created), label studio can send a request to the configured webhook url when a new project is created. but we can not receive it and there is no _**Project created**_ option in label studio webhook settings for **_Send Payload for_** options. while for other options (_**Project updated**_, _**Task created**_, ...) we can successfully receive the correct request from label studio. I also run `LABEL_STUDIO_ALLOW_ORGANIZATION_WEBHOOKS=true` command to [enable-organization-level-webhooks](https://labelstud.io/guide/webhooks.html#Enable-organization-level-webhooks) but it doesn't work.
Do you have any solution to receive the request when a new project is created in label studio?

Thank you

**To Reproduce**
1. Go to Project Settings
2. Click on Webhooks
3. Click on Add Webhook
4. Switch the **_Send for all actions_** toggle button off

**Environment (please complete the following information):**
 - OS: Debian10, python 3.7
 - Label Studio Version 1.4.1post1

**Comment by makseq** [comment]
Hi, LABEL_STUDIO_ALLOW_ORGANIZATION_WEBHOOKS is available only in the Enterprise version of LS.
