### ISSUE TITLE
Prediction score is not shown after prediction update

### ISSUE THREAD

**Issue by RadionBik** [heartexlabs/label-studio#2263]
**Describe the bug**
At first I uploaded via GUI a json with tasks that contained annotation and prediction fields. I used the sorting feature of the GUI to label examples with the lowest score first.
Then I downloaded the results and re-trained my model, thus, producing new predictions (i.e. `model_version`, `result` and `score` fields), which I uploaded to the LabelStudio via PUT method as described here:
https://labelstud.io/api#operation/api_predictions_update

Having done that, I realized that prediction scores are not visible in the GUI anymore and sorting doesn't work. The screenshot below illustrates the problem. Moreover, here is the `source` field content for a task with visible scores:
```
{
  "id": 22291,
  "data": {
    "file_id": "74d0703c-88c0-48a0-a61a-9dd752aa1241",
    "ocr_text": "...."
  },
  "annotations": [],
  "predictions": [
    {
      "id": 13857,
      "model_version": "8d87422ae53b05e1fa9646818cce4e47a45777b9",
      "created_ago": "1 week, 1 day",
      "result": [
        {
          "type": "choices",
          "value": {
            "choices": [
              "insurance"
            ]
          },
          "to_name": "ocr_text",
          "from_name": "category"
        }
      ],
      "score": 0.996641939367222,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-04-13T14:13:13.645239Z",
      "updated_at": "2022-04-13T14:13:13.645243Z",
      "task": 22291
    }
  ]
}
```
and a task without ones:

```
{
  "id": 21179,
  "data": {
    "file_id": "c7f6761c-6827-4e37-b06c-400ca1c7bbd3",
    "ocr_text": "..."
  },
  "annotations": [],
  "predictions": [
    {
      "id": 12745,
      "model_version": "evidence_doc_classifier: 2022-04-21 (unlabeled sample)",
      "created_ago": "1 week, 1 day",
      "result": [
        {
          "type": "choices",
          "value": {
            "choices": [
              "insurance"
            ]
          },
          "to_name": "ocr_text",
          "from_name": "category"
        }
      ],
      "score": 0.995402899639829,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-04-13T14:13:13.567808Z",
      "updated_at": "2022-04-21T13:15:33.556165Z",
      "task": 21179
    }
  ]
}
```
so I conclude that the structure is identical, so it is not clear why LS doesn't recognize the `score` field.  

**Expected behavior**
I expect after sending PUT request for an existing prediction ID to have their attributes properly handled by LS.

**Screenshots**
As you see, the updated entries have new `model_version` value, but not the score :( 
<img width="893" alt="image" src="https://user-images.githubusercontent.com/19979628/164480740-028268d8-3e23-45db-8233-92dddc24548b.png">

**Environment (please complete the following information):**
 - OS: linux-based in kubernetes env
 - Label Studio Version v.1.4.1

**Comment by makseq** [comment]
@RadionBik This score column depends (as I remember) on Project Settings => Machine Learning => Model dropdown. 
Please, try to switch it to another version. 
![image](https://user-images.githubusercontent.com/501780/164573066-3144935d-f2dc-4726-818c-39982d6657f4.png)

**Comment by RadionBik** [comment]
thank you! I didn't see this info in docs, when developed my scripts :( 
When I submitted this issue found similar discussion in slack https://label-studio.slack.com/archives/C01VBREDGAY/p1646619819498819

Not sure what the best place is, but it would be great if this info is mentioned somewhere in the API part as well
