### ISSUE TITLE
NER annotation page

### ISSUE THREAD

**Issue by manishiitg** [heartexlabs/label-studio#227]
**Is your feature request related to a problem? Please describe.**
Is there any way to go to next task or next sentence. i don't want to go back every time and then click on the next sentence 

![image](https://user-images.githubusercontent.com/1370315/75623680-7c023280-5bd2-11ea-99e0-3eea92515401.png)

**Describe the solution you'd like**
Can there be a simple next/previous link to go back and forward between sentences

**Comment by magistermilitum** [comment]
I'm wondering the same. Navigation arrows can be really useful in this case. Moreover tool will be a rapid annotation tool, so navigation arrow inside collections are a great advantage.

**Comment by niklub** [comment]
@manishiitg and @magistermilitum !
What do you think about adding a skip button with sequential sampling mode like proposed in https://github.com/heartexlabs/label-studio/issues/240 - will it enhance your workflow too?

**Comment by deppp** [comment]
@makseq Lets consider adding next/previous buttons with hotkeys for the next release.

**Comment by makseq** [comment]
Added in release/0.7.3.

**Comment by flavienbwk** [comment]
> @makseq Lets consider adding next/previous buttons with hotkeys for the next release.

Is it possible now ? I don't find any hotkey for "next" image to label

**Comment by makseq** [comment]
@flavienbwk if you press blue Label button on Data manager, then on ctrl + enter you will be moved to the next task.

**Comment by flavienbwk** [comment]
Ah yea thanks! I was missing the blue button
