### ISSUE TITLE
Consider adding Dependabot to repo

### ISSUE THREAD

**Issue by adriantre** [heartexlabs/label-studio#228]
Dependabot helps keeping dependencies up to date.
https://dependabot.com/python/

Getting the following Errors when installing label-studio with pipy:
```
ERROR: label-studio-converter 0.0.11 has requirement Pillow==6.2.1, but you'll have pillow 7.0.0 which is incompatible.
ERROR: label-studio 0.4.8 has requirement attrs==19.1.0, but you'll have attrs 19.3.0 which is incompatible.
ERROR: label-studio 0.4.8 has requirement Jinja2==2.10.3, but you'll have jinja2 2.11.1 which is incompatible.
ERROR: label-studio 0.4.8 has requirement numpy==1.17.4, but you'll have numpy 1.18.1 which is incompatible.
ERROR: label-studio 0.4.8 has requirement six==1.12.0, but you'll have six 1.14.0 which is incompatible.
ERROR: label-studio 0.4.8 has requirement tqdm==4.40.2, but you'll have tqdm 4.42.1 which is incompatible.
```

**Comment by deppp** [comment]
@niklub Please look into that when you have a minute

@adriantre Thanks for the pointer

**Comment by makseq** [comment]
We recommend to use virtualenv to use labe studio: 

```
virtualenv -p python3 env3
source env3/bin/activate
pip install label-studio 
```

This approach will isolate your global python configuration and it will help to avoid the package compatibility problems. Dependabot is cool, but we need a lot of time to test LS with such a big amount of updated packages.
