### ISSUE TITLE
expand documentation with concrete examples of data import

### ISSUE THREAD

**Issue by mutantbob** [heartexlabs/label-studio#2287]
I would like to use LabelStudio to put rectangles around objects in a set of images available via a URL, but I was unable to find an explanation of the actual data import process.

https://labelstud.io/guide/tasks.html#Import-data-from-the-Label-Studio-UI  references http://localhost:8080/import which appears to not exist.

The Create Project web wizard's Data Import screen is the opposite of informative.  It has no description of what should be in the files, nor does it have a link to a web page explaining what the file should look like

**Describe the solution you'd like**

It would be nice if the Data Import wizard had a link to a web page explaining how to import data, especially if that web page had some concrete working examples that can serve as a starting point for adapting to a project's needs.  Perhaps https://labelstud.io/guide/tasks.html can be expanded with examples.

**Comment by makseq** [comment]
Thank you for your feedback, this link `http://localhost:8080/import` is outdated for our latest LS versions. I[ have fixed it in our docs](https://labelstud.io/guide/tasks.html#Import-data-from-the-Label-Studio-UI).

We have very similar links to the docs in the bottom of import dialog:
![image](https://user-images.githubusercontent.com/501780/166081066-66808524-b26a-4fc4-8c3a-70ed95340fa1.png)

![image](https://user-images.githubusercontent.com/501780/166081074-b3e5854a-593e-4541-b463-6c23a815c766.png)

But yes, probably we need to add more links there, e.g. this one 
https://labelstud.io/guide/tasks.html#Example-JSON-format

I would recommend that you check this pages from the beginning:
https://labelstud.io/guide/tasks.html
especially this section:
https://labelstud.io/guide/tasks.html#Basic-Label-Studio-JSON-format

---

For your case you should use the `Object Detection with Bounding Boxes` template and URLs for your images can be listed in txt file, e.g. `import.txt`:
```
http://example.com/1.jpg
http://example.com/2.jpg
http://example.com/3.jpg
```
