### ISSUE TITLE
GPS location classification

### ISSUE THREAD

**Issue by ellaroyce** [heartexlabs/label-studio#2300]
I was wondering if It is possible to add a gps map into cross channel [view](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Build%20relations%20among%20regions%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20from%20different%20channels%22%20size%3D%226%22%2F%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3C!--%20First%20TimeSeries%20with%20Sensor%201%20--%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Sensor%201%20labels%22%20size%3D%226%22%2F%3E%3Cbr%3E%20%20%20%20%3CTimeSeriesLabels%20name%3D%22labels1%22%20toName%3D%22ts1%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Run%22%20background%3D%22%23a4a%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Walk%22%20background%3D%22%23aa4%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FTimeSeriesLabels%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3CTimeSeries%20name%3D%22ts1%22%20valueType%3D%22url%22%20value%3D%22%24csv1%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sep%3D%22%2C%22%20timeColumn%3D%22time%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20overviewChannels%3D%22sensor1%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CChannel%20column%3D%22sensor1%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20displayName%3D%22Sensor%201%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20strokeColor%3D%22%2327b%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FTimeSeries%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3C!--%20Second%20TimeSeries%20with%20Sensor%202%20--%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Sensor%202%20labels%22%20size%3D%226%22%2F%3E%3Cbr%3E%20%20%20%20%3CTimeSeriesLabels%20name%3D%22labels2%22%20toName%3D%22ts2%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22On%22%20background%3D%22green%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CLabel%20value%3D%22Off%22%20background%3D%22red%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FTimeSeriesLabels%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3CTimeSeries%20name%3D%22ts2%22%20valueType%3D%22url%22%20value%3D%22%24csv2%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20timeColumn%3D%220%22%20separator%3D%22%2C%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20overviewChannels%3D%221%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CChannel%20column%3D%222%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20displayName%3D%22Sensor%202%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20strokeColor%3D%22%23f80%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FTimeSeries%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E%3Cbr%3E%3Cbr%3E%3C!--%3Cbr%3E%20%20%20%20This%20is%20the%20completion%3Cbr%3E%20%20%20%20for%20the%20result%20preview%3Cbr%3E%20%20%20%20on%20Setup%20page%20only%3Cbr%3E--%3E%3Cbr%3E%3Cbr%3E%3Cbr%3E%3C!--%20%7B%3Cbr%3E%20%20%22completions%22%3A%20%5B%3Cbr%3E%20%20%20%20%7B%3Cbr%3E%3Cbr%3E%20%20%20%20%20%20%22result%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22labels2%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%225b6brspcdS%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22ts2%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22timeserieslabels%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%206%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22instant%22%3A%20false%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%202%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22timeserieslabels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22On%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%7D%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22labels1%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%22jX-vuDiFf5%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22ts1%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22timeserieslabels%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%2012%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22instant%22%3A%20false%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%207%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22timeserieslabels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22Run%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%7D%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22labels2%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%22dhTSo03_2_%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22ts2%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22timeserieslabels%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%2017%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22instant%22%3A%20false%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%2013%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22timeserieslabels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22Off%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%7D%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22from_name%22%3A%20%22labels1%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22id%22%3A%20%22fjIgsxMM4Y%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22to_name%22%3A%20%22ts1%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22timeserieslabels%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22value%22%3A%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22end%22%3A%2025%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22instant%22%3A%20false%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22start%22%3A%2021%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%22timeserieslabels%22%3A%20%5B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22Walk%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%7D%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22direction%22%3A%20%22right%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22from_id%22%3A%20%225b6brspcdS%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22to_id%22%3A%20%22jX-vuDiFf5%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22relation%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%2C%3Cbr%3E%20%20%20%20%20%20%20%20%7B%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22direction%22%3A%20%22right%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22from_id%22%3A%20%22dhTSo03_2_%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22to_id%22%3A%20%22fjIgsxMM4Y%22%2C%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%22type%22%3A%20%22relation%22%3Cbr%3E%20%20%20%20%20%20%20%20%7D%3Cbr%3E%20%20%20%20%20%20%5D%3Cbr%3E%20%20%20%20%7D%3Cbr%3E%20%20%5D%3Cbr%3E%7D%20--%3E)

so it is possible to label gps, timeseries and text in the same group?

**Comment by makseq** [comment]
@ellaroyce If you don't need to label a gps map - you can add <HyperText> and include there an iframe with the map. However this won't work if you want to put some points on the map.
