### ISSUE TITLE
Current state of custom frontend integration

### ISSUE THREAD

**Issue by waahlstrand** [heartexlabs/label-studio#2301]
**Describe the bug**
I am trying to implement changes in the frontend library, and would like to integrate these changes with Label Studio. Unfortunately, the [documentation](https://labelstud.io/guide/frontend_reference.html) seems quite dated, or at least not detailed when it comes to versions and releases.

Current releases no longer have a `static/editor` directory as described in the guide.

**To Reproduce**
Build relevant the `main.js` and `main.css` files in the LSF library and attempt to copy them to the `static/editor/{css,js}` directories.

This will fail since releases after 0.9.1 no longer have a `static/editor` directory. It is thus impossible to completely follow the guide.

I have also tried copying the files to the `frontend/build/static/{css,js}` directories without success.

**Expected behavior**
A new instruction on how to implement custom frontend integration, either via the pip build or the source build.

**Environment (please complete the following information):**
 - OS: Linux
 - Label Studio Version 1.0.1+

**Comment by faroit** [comment]
:+1:

**Comment by makseq** [comment]
Please check this video:
https://labelstud.io/guide/frontend.html#Custom-LSF-in-Label-Studio
