### ISSUE TITLE
Local Storage files return 403 even with access token

### ISSUE THREAD

**Issue by jentzheng** [heartexlabs/label-studio#2320]
**To Reproduce**
1. Install App through Docker and use LocalStorage
2. Sync Storage
4. It can display image on website, cookie validated is a possibility
5. It returns 403 through curl with auth token

```
curl -H 'Authorization: Token ***' 'http://localhost/data/local-files?d=mybucket/test.jpg'
```

Then it works as expected when visit a uploaded file via web UI
```
curl -H 'Authorization: Token ***' 'http://localhost/data/upload/1/test.jpg'
```

**Comment by makseq** [comment]
I've checked it on my LS 1.4.1post1 and it works perfectly with this command:

```
curl -H 'Authorization: Token <token>' http://localhost:8000/data/local-files/?d=dataset1/1.jpg --output image-local.jpg
```

**Comment by MRasch** [comment]
Today i ran into the same problem. 
Accessing the images through the web frontend is no problem, but when I try to access the images through our client it throws a `403 Forbidden`. Although token is set in the header. 

I have installed Label Studio on our server and it is reachable through the path: https://myserver.com/labeling/
The paths to the images look like this: `https://myserver.com/labeling/data/local-files/?d=labeling-dataset/zzw1o3L5.jpg`

I have no idea where to start looking why it fails. 
The log message only tells me that there is a problem: `django.request::log_response::224 Forbidden: /labeling/data/local-files/`

FYI: I moved the project to a subdomain: `https://labeling.myserver.com` and get the same error message.

**Comment by makseq** [comment]
All logic for this endpoint can be found here:
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/core/views.py#L179

If this is working when you access it via browser, it means 99% that you make a wrong API request, probably token is bad. Try to call another api endpoints from this project to check if this token is ok.

**Comment by Yakuho** [comment]
I also meet the same problem like that... and I try change login account to switch diff Token, It fail too.Importantly, It work yesterday!!  :-(
```python
HOSTNAME = "http://192.168.7.188:8802"
APIKEY = "c9524eca2db027d71d4f1d2cb5b1a5e3d6b72183"

import requests
import numpy as np
import cv2


def url2image(url, hostname, access_token) -> np.ndarray:
    headers = {'Authorization': 'Token ' + access_token}
    r = requests.request("GET", url=hostname + url, headers=headers)
    r.raise_for_status()
    image = cv2.imdecode(np.frombuffer(r.content, np.uint8), cv2.IMREAD_COLOR)
    assert image is not None, "image is None"
    return image


frame = url2image("/data/local-files/?d=project/000003.jpg", HOSTNAME, APIKEY)
```

**Comment by Yakuho** [comment]
I'm sure this happens when you load image files using local storage, and it's normal to load image files using upload

**Comment by flynet** [comment]
Has the same issue, 403 error for call with auth tocken

**Comment by DimIsaev** [comment]
6 months have passed and the problem is still not solved

**Comment by DimIsaev** [comment]
Change 2  rows
from this  https://github.com/HumanSignal/label-studio/pull/4698/files/ee05d93856637cbd7673c723af29d6f3dafdcf0c
