### ISSUE TITLE
Variable number of TextArea Boxes

### ISSUE THREAD

**Issue by nehasrikn** [heartexlabs/label-studio#2338]
Hi! 

I am building a custom task where I'm asking annotators to enter a variable number of sentence annotations per example. I'd like to start with a single TextArea component, and if the annotator needs to add another TextArea (depending on the particular data example),  they can click a button to add another. Is there support for this?

One limited solution I can think of is a table (but I'm assuming I need to predefine the number of rows and columns for this).

**Comment by makseq** [comment]
Hey, 

![image](https://user-images.githubusercontent.com/501780/167739471-da098caa-5cbf-4c67-9c36-11714dd16e46.png)

TextArea can have multiple answers, but it can't be added dynamically.

**Comment by nehasrikn** [comment]
Gotcha, thanks!
