### ISSUE TITLE
Audio Waveform not displayed 

### ISSUE THREAD

**Issue by lakshmi-speak** [heartexlabs/label-studio#2348]
**Describe the bug**
Audio Waveform not displayed for Automatic Speech Recognition using Segments template 

**To Reproduce**
1. Deploy label-studio via docker 
2. Create a new project using Automatic Speech Recognition using Segments template 
3. If audio source is a PCM 16 bit wav file, audio waveform is not displayed.

**Expected behavior**
Preview of audio waveform visible, like in the template.

**Screenshot**
![Screen Shot 2022-05-11 at 4 45 48 PM](https://user-images.githubusercontent.com/102545420/167965081-65c6d1e2-7138-48a9-b60d-72289f029a06.png)

**Environment (please complete the following information):**
 - Docker running on 64bit Amazon Linux 2 in ElasticBeanStalk
 - Label Studio Version - latest docker image sha256:ff5507c8d823df227d32f09a84ae6e52114dfaaf1ee755025ca0fda98dfe52ff

**Comment by makseq** [comment]
@lakshmi-speak Could you add here an audio wave file example?

**Comment by lakshmi-speak** [comment]
[sample.wav.zip](https://github.com/heartexlabs/label-studio/files/8674429/sample.wav.zip)
The same audio works fine when I launch label-studio installed via pip on a local machine.

**Comment by makseq** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/501780/168190178-e79bbb9f-eb33-436c-a76a-efc2a11b8a31.png)

It might depend on the browser you are using. I'm on Chrome 96.0.

**Comment by lakshmi-speak** [comment]
Reading the audio from cloud storage does not work, but uploading the file works.

**Comment by jeroenboeye** [comment]
I have the exact same issue with an Azure cloud storage setup. I've tried some CORS settings but no luck so far.

**Comment by makseq** [comment]
Maybe this guide will help you more: https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services

**Comment by jeroenboeye** [comment]
Thanks @makseq, I can confirm the waveform is displayed correctly when CORS is configured correctly on Azure blob storage.
