### ISSUE TITLE
Labelling for  instance segmentation

### ISSUE THREAD

**Issue by tommyvtran97** [heartexlabs/label-studio#2353]
Hi all,

I was wondering whether there is a feature within Label Studio that allows for instance segmentation using polygons.

**Comment by makseq** [comment]
Hi, 

Please check this template
https://labelstud.io/templates/image_polygons.html

**Comment by coelho-k** [comment]
From this link, does each polygon mask represent a separate instance within a class?
And can the instance segmentation masks be exported in COCO format?
