### ISSUE TITLE
Image extension not included in exported Pascal VOC XML files

### ISSUE THREAD

**Issue by jvence** [heartexlabs/label-studio#2360]
**Describe the bug**
When exporting PascalVOC, XML does not include file extension in <filename>brick-front</filename>

**To Reproduce**
Try exporting to PascalVoC and look at all generated XMLs

**Expected behavior**
File extension should be included

 - OS: Mac OS
 - Label Studio Version: 1.4.1post1

**Comment by makseq** [comment]
It's fixed here, but not yet release:
https://github.com/heartexlabs/label-studio-converter/pull/100
