### ISSUE TITLE
LABEL_STUDIO_HOST not work 

### ISSUE THREAD

**Issue by safehumeng** [heartexlabs/label-studio#2378]
LABEL_STUDIO_HOST=http://localhost:8080/sub_path1/sub_path2 docker-compose up -d
<img width="175" alt="image" src="https://user-images.githubusercontent.com/16226299/169532741-80e085d2-daa8-4e08-a420-4e88e62a165c.png">
get url is "http://localhost:8080/data/upload/2/019a8871-3649666.wav", not found "sub_path1/sub_path2"

**Comment by safehumeng** [comment]
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/16226299/169772150-1044cb4c-5d2c-4c11-bb68-0171589df014.png">
this button position

**Comment by farioas** [comment]
<img width="1056" alt="Screenshot 2022-05-23 at 20 46 21" src="https://user-images.githubusercontent.com/2744993/169868668-6b16f599-5cd9-49c1-af5a-c6ca6eeafe09.png">
Cannot reproduce

Note: already uploaded files will preserve their old urls, LABEL_STUDIO_HOST override have to be used only for fresh instances

**Comment by safehumeng** [comment]
thanks！

**Comment by UmairAhmadBaltoro** [comment]
@safehumeng hey, how are you able to run with subpath, I'm trying the same with docker-compose command but it's not working.. is there any configurations you changed in docker-compose file

**Comment by safehumeng** [comment]
> @safehumeng hey, how are you able to run with subpath, I'm trying the same with docker-compose command but it's not working.. is there any configurations you changed in docker-compose file

no change in docker-compose file

**Comment by makseq** [comment]
@safehumeng what problem exactly do you have? screenshots, logs? Is it with upload file paths?

**Comment by safehumeng** [comment]
> what problem exactly do you have? screenshots, logs? Is it with upload file paths?

The problem was solved a long time ago
the issue mark “closed”
@UmairAhmadBaltoro have an other problem

**Comment by UmairAhmadBaltoro** [comment]
Thanks, @safehumeng  @makseq my problem has been solved. I downloaded the Release 1.7 build locally and ran it using the 'docker compose' command. It works. However, I am not able to change the subpath and run the container using the *'docker run'* command.

`docker run -it -p 9000:9000 -p 8000:8000 -u 1000 -e LABEL_STUDIO_PORT=9000 -e LABEL_STUDIO_HOST=http://localhost:9000/subpath/subpath/  -v /home/ubuntu/mydata5:/label-studio/data heartexlabs/label-studio`

**Comment by farioas** [comment]
It was never stated than you can run subpath with just simple docker command.
https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-with-a-host-and-sub-path
