### ISSUE TITLE
TaskListAPI (data-manager) isn't displaying some parameters

### ISSUE THREAD

**Issue by anoirak** [heartexlabs/label-studio#2381]
**Describe the bug**
Response for a get request to `/api/tasks?project={id}`  doesn't include some parameters even though they exist on the db 
- annotations_results
- annotations_ids
- annotators
- predictions_results
- predictions_score

**Expected behavior**
Get request to `api/tasks/<task_id>` is working correctly

**Comment by makseq** [comment]
Adding of `&fields=all` should help. 
```
/api/tasks?project={id}&fields=all
```
