### ISSUE TITLE
Object detection: Metadata for each object

### ISSUE THREAD

**Issue by AbdallahNasir** [heartexlabs/label-studio#239]
Greetings,

I am wondering if it is possible to enable metadata for each bounding box that is drawn on images.
For Example: 
We have the following classes:
* Car
* Person
The labeler will draw a box around every car and every person. 
After labeling each car, and each person, here comes the new feature. It would be great if the labeler can assign values for each box drawn in a table or anything, like the following features.
* Cars
  * Color
  * Manufacturer
  * Model
* People
  * Gender
  * Age range: Adult or child for example
Some of these values may be finite or continuous, which makes it very hard to create a labeling class for each one of them.

Please advise,

**Comment by niklub** [comment]
Hi, @AbdallahNasir ! Currently there is no way to add structured metadata per each labeled object. We'll keep in mind it. For now, you can use "Create Normalization" button to add any textual meta related to your bounding box
![image](https://user-images.githubusercontent.com/6087484/77309531-e27bfb80-6d0d-11ea-90ff-9e62fe190488.png)

**Comment by AbdallahNasir** [comment]
Hi @niklub , 
Thank you so much for the suggestion. It will be perfect and more than enough.

Thank you

**Comment by imadcat** [comment]
> Hi, @AbdallahNasir ! Currently there is no way to add structured metadata per each labeled object. We'll keep in mind it. For now, you can use "Create Normalization" button to add any textual meta related to your bounding box
> ![image](https://user-images.githubusercontent.com/6087484/77309531-e27bfb80-6d0d-11ea-90ff-9e62fe190488.png)

this add normalization function works in a confusing way:
- first the labelling and task interface will never display the normalization field, even when you have just added a normalization (I was doing polygon labelling)
- second the normalization data generated by label-studio-ml prediction will be totally lost when the task is humanly labelled and submitted
