### ISSUE TITLE
Labeling tasks in order based on Task ID & skipping or removing a single task

### ISSUE THREAD

**Issue by tonyliangli** [heartexlabs/label-studio#240]
**Is your feature request related to a problem? Please describe.**
1. Labeling can only be performed based on random Task IDs. 
2. If the current Task ID is not what I desire to label (maybe some dirty data), it cannot be skipped or deleted

**Describe the solution you'd like**
1. Settings or config to set labeling mode in Task ID order
2. Provide an option to skip or delete this current task id

**Describe alternatives you've considered**
To achive the two features described above in the current version, I can try these two methods:
1. Use preview mode to label and change task_id=XXX from the url to change tasks.
2. In labeling mode, remove all completions from a single task and refresh the page, this task will be skipped for the moment. Or just leave an empty completion and submit, process the output file with empty results later.

**Additional context**
Please consider these two suggestions, may be really helpful in certain occasions. Thanks!

**Comment by niklub** [comment]
Hi, @tonyliangli !

1. You can change the default uniform sampling behavior by editing config file `your-project/config.json` under the parameter `"sampling": "sequential"`. We'll  definitely make this setting clearer in the next release.

2. Considering skip option - what do you expect when skipping a task? Should it be marked as skipped and never going back to the labeling stream, or you want to just postpone it to the end ?

**Comment by tonyliangli** [comment]
Thanks for your reply. I really appreciate the work of label studio, it really helped me a lot. Thanks for the amazing work.

As for skipping, I think deleting or putting the task at the bottom is both fine. I just don't want an empty completion left in the task I'm willing to skip.

During my labeling work, I found out two more things: 

1. In labeling mode, once I click submit, it will jump to another task. But sometimes I still need to add a second or third compeletion (multiple completion groups of labels) on this task. I think there should be a manual way (may be another 'next task' button) to trigger task switching separatly.
2. In browse mode, when I browse a task, an empty completion will be automatically added. But somehow I just want to view results, I don't want to label anything. So I have to remove the empty completion manually. I think this could also also be a part of the configuration, whether creating a completion automatically or manually.

Now I'm still using browse mode to label data and change taskids in the URL to switch tasks. By using browse mode, I'm able to do three things which labeling mode cannot offer:

1. I,m able to add multiple completions at once without skipping to the next task after the first completion is submitted
2. I'm able to skip the current task by removing all completions and switch to the next task by changing the URL.
3. I'm able to label tasks in sequence by changing taskid in order from the URL (Now I know how to do that, thanks).

**Comment by niklub** [comment]
Hi, @tonyliangli !

We've just updated Label Studio to **v0.5.1** with added functionality for 
- skipping tasks in a label stream mode 
- selecting the tasks sampling way (sequential ordered by id or random)

So I guess 2 an 3 could be solved now. 

About automatic completion creation in browse mode - actually you don't need to manually remove this completion since it is not created until you press "Update" button, so you can just ignore this.

Adding multiple completions in label stream is that we are going to think about in the future releases. Please create a separate feature request for this.
