### ISSUE TITLE
Label Studio app - change the hourglass

### ISSUE THREAD

**Issue by LizSebban** [heartexlabs/label-studio#2405]
Hi, 
there is a sort of weird creepy animal used as "hourglass" on Label studio. 
Could you please change it to something cute? I'm on the tool a lot and it freaks me out. 
thank you in advance. 
![image](https://user-images.githubusercontent.com/106329249/170509101-f16e2a93-4dea-4703-a63a-638cca68d65a.png)

Liz

**Comment by makseq** [comment]
This. Is. the [Virginia Opossum](https://en.wikipedia.org/wiki/Virginia_opossum).

https://labelstud.io/blog/Whats-With-The-Label-Studio-Opossums.html

![image](https://user-images.githubusercontent.com/501780/170604432-a1d1cc83-f6b6-4225-96d1-e8d9146f5893.png)

**Comment by LizSebban** [comment]
Ah! Sorry, I meant no offense.

Best Regards,

Elisabeth Sebban
Data manager, Auditing team

[Related image]www.ebay.co.il/rnd/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ebay.co.il%2Frnd%2F&data=04%7C01%7Cesebban%40ebay.com%7Cc1c211c3b4f5464598db08da16cd27fc%7C46326bff992841a0baca17c16c94ea99%7C0%7C0%7C637847367790202570%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2ByjM2mUGnIV3G9Zs3fz2%2BRVRBkE%2FX0boTMeKZlf5JdI%3D&reserved=0>

[logo_new_mail]

**Comment by makseq** [comment]
@LizSebban btw in our Enterprise edition we use another spinner with a strong square like Heartex logo.
