### ISSUE TITLE
Error in exporting to YOLO format

### ISSUE THREAD

**Issue by thehappy1** [heartexlabs/label-studio#2419]
Hi, 
I tried to export my large labeled dataset with aprox. 3000 images into YOLO format. During that the process get stuck while I tried to wait 4-5 hours - nothing happens. Therefore I wanna try it out with the API of label-studio. 

I could not find the exact documentation for my problem. But I found a starting point. I altered the giving command from here: https://labelstud.io/api#tag/Export
`curl -X GET http://localhost:9001/api/projects/7/export?exportType=YOLO -H 'Authorization: Token *censored*' `

Unfortunatly this is not working. Is there something missing in the command ?
Thanks for your help! :-)

**Comment by makseq** [comment]
@thehappy1 Hi, LS Community edition doesn't use background jobs, but the export operation can take a lot of time and it could be broken by timeout. As a workaround you can export images by batches:

```
http://localhost:8080/api/projects/30/export?exportType=YOLO&ids[]=<id1>&ids[]=<id2>&...
```

**Comment by thehappy1** [comment]
Thank you for your help. I was able to export the project with the help of the API. And I think you're right, it has something to do with a timeout or something...
