### ISSUE TITLE
Changed port in config.json but app still launches on port 8200

### ISSUE THREAD

**Issue by javadba** [heartexlabs/label-studio#244]
Here is my updated config.json:

{
  "title": "Label Studio",
  "port":12345,
  "debug": false,
  "label_config": "config.xml",
  "input_path": "tasks.json",
  "output_dir": "completions",
  "instruction": "Type some <b>hypertext</b> for label experts!",
  "allow_delete_completions": true,
  "templates_dir": "examples",
  "editor": {
    "debug": false
  },
  "sampling": "uniform"
}

But the app launched on 8200 anyways.  Ideas?

**Comment by niklub** [comment]
@javadba use `--port 12345` cmd argument for that, don't modify config.json
