### ISSUE TITLE
The front-end problems

### ISSUE THREAD

**Issue by iioufogood** [heartexlabs/label-studio#2458]
label-studio/label_studio/frontend/dist/dm
label-studio/label_studio/frontend/dist/lsf

How are the files in these two files generated？
Where is the source file?

**Comment by makseq** [comment]
There are two different repositories:
LSF = https://github.com/heartexlabs/label-studio-frontend#development
DM = https://github.com/heartexlabs/dm2#development

You should build these modules and copy the result files.
