### ISSUE TITLE
Keyboard shortcuts / hotkeys for all choices options

### ISSUE THREAD

**Issue by nicmer** [heartexlabs/label-studio#246]
**Is your feature request related to a problem? Please describe.**
In the Choices component, keyboard shortcuts are only displayed in the "single-radio" option. And not in the multi or single options (see screenshot).

**Describe the solution you'd like**
Automatic shortcuts should be generated and displayed for the single and multiple option similar to how it works with single-radio option. 

**Describe alternatives you've considered**
Alternatively (or additionally), if the custom shortcuts that are generated with the "hotkey" argument were somehow displayed in the Choices option, that would also be good.

**Additional context**
![image](https://user-images.githubusercontent.com/5261439/78138373-14d0db80-7427-11ea-834d-07e17211c123.png)

**Comment by nicmer** [comment]
Seems like this issue only exists in the playground. When I create the scheme elsewhere,  the hotkeys are correctly displayed.

**Comment by makseq** [comment]
Fixed in release/0.7.3.
