### ISSUE TITLE
The front-end problems

### ISSUE THREAD

**Issue by iioufogood** [heartexlabs/label-studio#2478]
After the project https://github.com/heartexlabs/label-studio-frontend#development is packaged, replace the packaged code with label-studio/label_studio/frontend/dist/ lsf；
Label-studio local development error；
![image](https://user-images.githubusercontent.com/31815016/172606670-5ac8bc5f-1f50-4391-9415-17dad3b471ea.png)

How is the label-studio/label_studio/frontend/dist/ lsf code developed locally for this project 

Am I using the wrong version?
![image](https://user-images.githubusercontent.com/31815016/172609918-4d777ada-4326-4494-8cf4-97f84689118e.png)

**Comment by iioufogood** [comment]
Resolved, version problem caused

**Comment by makseq** [comment]
Thank you for you report!
