### ISSUE TITLE
Route `api/storages/azure` does not exist

### ISSUE THREAD

**Issue by jpavel** [heartexlabs/label-studio#2490]
**Describe the bug**
At least one of the API routes described in the documentation does not exist. Namely it is the command to list all storages on Azure: `api/storages/azure`. Nevertheless, direct call to storage by its ID (e.g. `http://localhost:8080/api/storages/azure/1`) works as expected 

**To Reproduce**
1. Go to `http://localhost:8080/api/storages/azure` (for local deployment)
2. See `404 Not found`

**Expected behavior**
Response including the list of storages as described in the documentation.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version 1.4.1

**Comment by makseq** [comment]
Thank you for pointing us to this issue, we've created a ticket. This endpoint is not fully implemented.

**Comment by addisonklinke** [comment]
Also affecting `api/storages/s3`

**Comment by triklozoid** [comment]
Try to add `project` parameter. 
```
api/storages/s3?project=YOUR_PROJECT_ID
```

**Comment by jpavel** [comment]
Thanks @triklozoid ! This indeed works as expected. I can also see it in the documentation for API in 1.5.0post0. As a closing suggestion, you might perhaps indicate that the project id is a compulsory query parameter and show it in the example (https://labelstud.io/api#operation/api_storages_azure_list).

From my point of view, the issue is resolved, thus closing it.
