### ISSUE TITLE
Can you give an example about the imported data format on Conversational AI/Slot Filling and Intent Classification?

### ISSUE THREAD

**Issue by YpLarryWang** [heartexlabs/label-studio#2499]
I try to import data to this module but always failed. I have tried the following format:
1. `JSON`
```
[
	{
		"author": "Human",
		"text": "Hi, Robot!"
	}
	{
		"author": "Robot",
		"text": "Nice to meet you, man! Tell me what you want."
	}
]
```
it raised `[73c4adce-99f5-4742-848f-ec7fba836235] Validation error (Failed to parse input file upload/13/8028ed8f-bot_conversation.json: Unexpected character found when decoding array value (2))`.

2. `CSV`
```
Human,Robot
"Hi, Robot!","Nice to meet you, man! Tell me what you want."
```
it raised `[Validation error] Error at item 0: "humanMachineDialogue" key is expected in task data [assume: item["data"] = task root with values] :: {'data': {'Human': 'Hi, Robot!', 'Robot': 'Nice to meet you, man! Tell me what you want.'}, 'file_upload_id': 50}`

-------

**Can u plz give an example of `.json` file rather than rendered style to help me with this? THX a lot!**

**Comment by makseq** [comment]
You can get example of input using the network panel of your browser:
![image](https://user-images.githubusercontent.com/501780/173962971-d30b8fc3-47ea-4fd0-b3bf-7a956e66f5fb.png)

You should use this task structure:
```
{
    "humanMachineDialogue": [
        {
            "author": "Human",
            "text": "Hi, Robot!"
        },
        {
            "author": "Robot",
            "text": "Nice to meet you, man! Tell me what you want."
        },
        {
            "author": "Human",
            "text": "Order me a pizza from Golden Boy at Green Street "
        },
        {
            "author": "Robot",
            "text": "Done. When do you want to get the order?"
        },
        {
            "author": "Human",
            "text": "At 3am in the morning, please"
        }
    ]
}
```

**Comment by failable** [comment]
@makseq How to annotate each utterance's label?
