### ISSUE TITLE
Text Classfication - Add Dropdown instead of Choices

### ISSUE THREAD

**Issue by JaredChung** [heartexlabs/label-studio#250]
Hello,
I want to customise the text classification to have multiple drop-down menu's instead of the "Choices". What would be the best way to incorporate this?

Cheers,

Jared

**Comment by deppp** [comment]
Hey Jared,

That to me would look like a new tag that is based on Choices tag. I'd even consider reusing the same mobx model for that and just providing a new custom react view. Take a look at the implementation of the Choice tag here: https://github.com/heartexlabs/label-studio-frontend/blob/master/src/tags/control/Choices.js and feel free to ping me in our Slack channel if you need more help with that. Oh, and please contribute back :-)
