### ISSUE TITLE
request to provide RBAC

### ISSUE THREAD

**Issue by boofazel** [heartexlabs/label-studio#2504]
Hi Dear, I need to use your Good code for picture labeling and I need RBAC(rule base access control)

I also think that this can be solve by superadmin feature. can you do this?

my english level is not good, excuse me.

Thanks for your attention.

**Comment by makseq** [comment]
Hello, RBAC is available in our Label Studio Enterprise at 
https://app.heartex.com.

**Comment by boofazel** [comment]
hi again, thanks, Good luck

**Comment by boofazel** [comment]
Can we buy this enterprise version and deploy that in our local server?

**Comment by makseq** [comment]
@boofazel Sure. We call it on-premise deployment. Also we have helm charts if you use k8s.
