### ISSUE TITLE
Mixed annotations with Polygons and Rectangles.

### ISSUE THREAD

**Issue by IsCoelacanth** [heartexlabs/label-studio#251]
**Describe the bug**
One of my labeling tasks requires a bbox rough annotations and crisper polygons inside. right now if I add a polygon field after the rectangle only the polygon works.

**To Reproduce**
1. Go to https://labelstud.io/playground/
2. Paste in LabelConfig.
```
<View>
  <Image name="img" value="$image"/>
  
  <RectangleLabels name="bbox" toName="img">
   <Label value="bbox1" background="green"/>
   <Label value="bbox2" background="blue"/>
  </RectangleLabels>
  
  <PolygonLabelsname="poly" toName="img">
   <Label value="ppoly1" background="red"/>
   <Label value="ppoly2" background="yellow"/>
  </PolygonLabels>
</View>
```
3. Polygons work, rectangle don't

**Expected behavior**
Both, polygon and rectangle should work.

**Environment (please complete the following information):**
 - OS: Windows 10, 1909, Build 18363
 - Browser Chrome
 - Version 80

**Additional context**
looks similar to #202 

_Edit: content in fields_

**Comment by makseq** [comment]
Right now LS doesn't support double control tags connected to one source images. 
We are planning to add this feature in next releases.
