### ISSUE TITLE
Completed annotation file extension missing when exporting using Target Cloud Storage sync

### ISSUE THREAD

**Issue by Adrian-Rasmussen** [heartexlabs/label-studio#2512]
**Describe the bug**
The automatically exported annotations don't get given a file extension when pressing Sync or when annotating and pressing Submit/Update for  any Target Cloud Storage except local (i.e. S3, GCS, etc).
The same annotations get a .json extension when instead using local storage for the Target.

**To Reproduce**
1. Enable FUTURE_SAVE_TASK_TO_STORAGE
2. Create a project
3. Add images and annotations
4. Add Target Storage with any non-local option (in my case, AWS S3 with the endpoint configured to point to a MinIO instance)
5. Click Sync Storage button (or Submit/Update on individual annotation)
6. Go to the storage location, observe that the completed annotations are there but missing .json extension

**Expected behavior**
Synced tasks should have the .json extension

**Environment (please complete the following information):**
MinIO S3 instance for Target Cloud Storage
Docker
```
{
  "release": "1.4.1post1",
  "label-studio-os-package": {
    "version": "1.4.1post1",
    "short_version": "1.4",
    "latest_version_from_pypi": "1.4.1.post1",
    "latest_version_upload_time": "2022-02-12T00:44:06",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "Merge Develop + LSE hotfix/2.2.7-hotfix.1: Return 404 for api/project/ ...",
    "commit": "3239a3d04e65c2cd0091568aa0439d103be2970c",
    "date": "2022-05-11 16:05:40 +0300",
    "branch": "master",
    "version": "3239a3d"
  },

  "label-studio-frontend": {
    "message": "fix: DEV-2100: Fix preselected choices (#584)  - working with empty an ...",
    "commit": "ee38e771760e1ce57ac62dc1556ddd0718f62487",
    "branch": "master",
    "date": "2022-04-27T11:55:50Z"
  },

  "dm2": {
    "message": "Fix tasks selection (#44)",
    "commit": "97e33ac0a9b0ea09398b00d7916671ca76cf2a71",
    "branch": "master",
    "date": "2022-04-13T13:55:17Z"
  },

  "label-studio-converter": {
    "version": "0.0.40"
  }
}
```

**Additional context**
It seems like the cloud ones would need the extension added in a similar way to the implementation for local storage:
https://github.com/heartexlabs/label-studio/blob/f8db7469b0cde347a53967b8bbfac185bebd83bf/label_studio/io_storages/localfiles/models.py#L105
vs https://github.com/heartexlabs/label-studio/blob/f8db7469b0cde347a53967b8bbfac185bebd83bf/label_studio/io_storages/s3/models.py#L179
In particular:
https://github.com/heartexlabs/label-studio/blob/f8db7469b0cde347a53967b8bbfac185bebd83bf/label_studio/io_storages/s3/models.py#L182 might need to have .json added to give it the extension, as key is just the task id (with FUTURE_SAVE_TASK_TO_STORAGE enabled)

**Comment by triklozoid** [comment]
@Adrian-Rasmussen changing this is not very safe now, because it can break already exported annotations. I think we can add environment variable with extension to let everyone control it for own label-studio instance. And set default value to empty string for backward compatility. Will it solve your problem?

**Comment by Adrian-Rasmussen** [comment]
@triklozoid that sounds reasonable to me and should resolve my issue. Another option would be having it as a config option on the Edit Target Storage page to allow per-project customisation, but I don't have a use-case for that so an environment variable would suffice.

**Comment by triklozoid** [comment]
@Adrian-Rasmussen ok, I'll add it to our development pipeline and we'll implement it soon.

**Comment by APCG** [comment]
Is it already implemented? I also don't see annotations being export to S3 (Ceph storage). Is it a bug?

**Comment by makseq** [comment]
@APCG No, unfortunately we haven't fixed it yet. 

Could you write more info about Ceph storage and what is not working there?

**Comment by teebu** [comment]
Seeing the same in s3 bucket.  Target Storage outputs files 
![image](https://user-images.githubusercontent.com/5531844/203673277-c30b8357-fc8b-4b8d-8ca3-864ebbe7d8c8.png)

**Comment by peterdays** [comment]
up! Any news on this?

**Comment by makseq** [comment]
@cuesy @APCG @Adrian-Rasmussen please, try the latest develop branch now. 
Note: `FUTURE_SAVE_TASK_TO_STORAGE` should be `1`

**Comment by WillieMaddox** [comment]
@makseq I observed the same issue after upgrading label-studio from version `1.6.0` to `1.7.2`. However, when I restart with `FUTURE_SAVE_TASK_TO_STORAGE=1` and sync target storage,
1. Target files are saved using the task id (not the annotation id) as the filename stem.
2. The format (or schema?) of the target file contents is different.

For example, a target file with filename `1217` and contents,
```json
{
  "id": 1217,
  "created_username": "user1_First user1_Last user1@gmail.com, 1",
  "created_ago": "0\u00a0minutes",
  "completed_by": {
    "id": 1,
    "first_name": "user1_First",
    "last_name": "user1_Last",
    "email": "user1@gmail.com"
  },
  "task": {
    "id": 2799,
    "data": {
      "image": "/data/local-files/?d=SinglePlanes2/images/DTW2_bing_230205_20_72066093_99417487.png",
    },
    "meta": {},
    "created_at": "2023-03-25T04:01:21.742662Z",
    "updated_at": "2023-03-25T04:01:21.765065Z",
    "is_labeled": true,
    "overlap": 1,
    "inner_id": 121,
    "total_annotations": 1,
    "cancelled_annotations": 0,
    "total_predictions": 1,
    "comment_count": 0,
    "unresolved_comment_count": 0,
    "last_comment_updated_at": null,
    "project": 8,
    "updated_by": 1,
    "file_upload": null,
    "comment_authors": []
  },
  "result": [
    {
      "original_width": 276,
      "original_height": 330,
      "image_rotation": 0,
      "value": {
        "points": [
          [
            25.07135010755499,
            84.10911930981985
          ],
          [
            83.92536957608543,
            53.38449522768531
          ],
          [
            62.53845920517987,
            20.247217327373573
          ],
          [
            19.356735371444135,
            24.28428397416679
          ]
        ],
        "closed": true,
        "polygonlabels": [
          "airplane"
        ]
      },
      "id": "zcpRj4WiTX",
      "from_name": "label",
      "to_name": "image",
      "type": "polygonlabels",
      "origin": "prediction",
      "score": 0.9718799289971847
    }
  ],
  "was_cancelled": false,
  "ground_truth": false,
  "created_at": "2023-03-25T04:06:59.447992Z",
  "updated_at": "2023-03-25T04:06:59.448018Z",
  "lead_time": 37.87,
  "last_action": null,
  "project": 8,
  "updated_by": 1,
  "parent_prediction": 2708,
  "parent_annotation": null,
  "last_created_by": null
}
```
becomes `2799.json` with contents,
```json
{
  "id": 2799,
  "annotations": [
    {
      "id": 1217,
      "completed_by": 1,
      "result": [
        {
          "id": "zcpRj4WiTX",
          "type": "polygonlabels",
          "score": 0.9718799289971847,
          "value": {
            "closed": true,
            "points": [
              [
                25.07135010755499,
                84.10911930981985
              ],
              [
                83.92536957608543,
                53.38449522768531
              ],
              [
                62.53845920517987,
                20.247217327373573
              ],
              [
                19.356735371444135,
                24.28428397416679
              ]
            ],
            "polygonlabels": [
              "airplane"
            ]
          },
          "origin": "prediction",
          "to_name": "image",
          "from_name": "label",
          "image_rotation": 0,
          "original_width": 276,
          "original_height": 330
        }
      ],
      "was_cancelled": false,
      "ground_truth": false,
      "created_at": "2023-03-25T04:06:59.447992Z",
      "updated_at": "2023-03-25T04:06:59.448018Z",
      "lead_time": 37.87,
      "prediction": {
        "id": 2708,
        "task": 2799,
        "score": 0.971879928997185,
        "result": [
          {
            "type": "polygonlabels",
            "score": 0.9718799289971847,
            "value": {
              "points": [
                [
                  25.0,
                  83.33333333333333
                ],
                [
                  80.07246376811594,
                  56.666666666666664
                ],
                [
                  62.68115942028985,
                  16.666666666666668
                ],
                [
                  19.92753623188406,
                  26.96969696969697
                ]
              ],
              "polygonlabels": [
                "airplane"
              ]
            },
            "to_name": "image",
            "from_name": "label"
          }
        ],
        "cluster": null,
        "neighbors": null,
        "created_at": "2023-03-25T04:01:21.770425Z",
        "updated_at": "2023-03-25T04:01:21.770445Z",
        "created_ago": "5\u00a0minutes",
        "mislabeling": 0.0,
        "model_version": ""
      },
      "result_count": 0,
      "unique_id": "7a394bef-3700-46f0-ae06-3194b25bfef2",
      "last_action": null,
      "task": 2799,
      "project": 8,
      "updated_by": 1,
      "parent_prediction": 2708,
      "parent_annotation": null,
      "last_created_by": null
    }
  ],
  "drafts": [],
  "predictions": [
    2708
  ],
  "data": {
    "image": "/data/local-files/?d=SinglePlanes2/images/DTW2_bing_230205_20_72066093_99417487.png",
  },
  "meta": {},
  "created_at": "2023-03-25T04:01:21.742662Z",
  "updated_at": "2023-03-25T04:06:59.509027Z",
  "inner_id": 121,
  "total_annotations": 1,
  "cancelled_annotations": 0,
  "total_predictions": 1,
  "comment_count": 0,
  "unresolved_comment_count": 0,
  "last_comment_updated_at": null,
  "project": 8,
  "updated_by": 1,
  "comment_authors": []
}
```
Is there a solution that JUST fixes the extension issue?

**Comment by makseq** [comment]
@WillieMaddox oh, I see. Unfortunately there is not supereasy solution, however, you can patch LS easily on this line:
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/io_storages/base_models.py#L345

I believe it's better to use the task format of exported labeling instead of the annotation format, because it's a standard LS format for import, so you can easily re-import tasks even using LS Import dialog.
