### ISSUE TITLE
Video annotation format not outputting interpolated frames.

### ISSUE THREAD

**Issue by abdulazizab2** [heartexlabs/label-studio#2539]
Hey folks,

I am liking the flexibility of this tool.

I am following the tutorial this tutorial from [youtube](https://www.youtube.com/watch?v=Grp6UB_zB0Y&t=2036s) with its custom template as its suitable for spatio-temporal action detection. However, after making the annotations and exporting the files. Only the keyframes are in the JSON file and not the interpolated frames within the keyframes. How to get the output to contain all the frames for the bbox?

**Comment by abdulazizab2** [comment]
Fixed from help in official slack channel by manually adding interpolate_key_frames=1 in the export API.

**Comment by lchunleo** [comment]
Can i check how to do the video annotation? i can't find instructions how to even import the video. Please advise. thank you

**Comment by makseq** [comment]
You can check this url with label config and task examples: https://data.heartex.net/pathtrack/demo/%21import/

However video is not officially released yet.

**Comment by abdulazizab2** [comment]
> Can i check how to do the video annotation? i can't find instructions how to even import the video. Please advise. thank you

Check out this video tutorial on YouTube
https://youtu.be/Grp6UB_zB0Y
it does video bounding box.
Follow its instruction and try a toy example to export the annotations and see if it fits your needs.

For me, the exported annotation was not enough so I had to manually export it using the API docs.

**Comment by 52doho** [comment]
> You can check this url with label config and task examples: https://data.heartex.net/pathtrack/demo/%21import/
> 
> However video is not officially released yet.

@makseq hello, thanks for this great tool.

when will video annotation features be released?
