### ISSUE TITLE
Cant load local files

### ISSUE THREAD

**Issue by PasaImage** [heartexlabs/label-studio#2548]
I've tried to convert my `yolo` data set with `label-studio-converter` with this command:
`label-studio-converter import yolo -i /mnt/Codes/Projects/Python/ObjectDetection/f2net-v61fl/quad2a/label_studio -o ls-tasks.json --image-root-url /mnt/Codes/Projects/Python/ObjectDetection/f2net-v61fl/quad2a/label_studio/images`

and json file is like :
`[{"annotations": [{"result": [{"id": "acd78f289a", "type": "rectanglelabels", "value": {"x": 48.7109, "y": 54.71879583333333, "width": 2.5782, "height": 2.2290749999999995, "rotation": 0, "rectanglelabels": ["drone"]}, "to_name": "image", "from_name": "label", "image_rotation": 0, "original_width": 640, "original_height": 480}], "ground_truth": false}], "data": {"image": "/mnt/Codes/Projects/Python/ObjectDetection/f2net-v61fl/quad2a/label_studio/images/11_gopr5846_005900.png"}}, ...`

but always get error like :

![image](https://user-images.githubusercontent.com/106461271/174815329-0dd4da92-ba32-41ea-9a31-e40b1dfa20f6.png)

![image](https://user-images.githubusercontent.com/106461271/174815665-3df05e8d-2876-49bd-9306-e67c362a4636.png)

please help me !
thanks.

**Comment by makseq** [comment]
Have you followed this step instruction? 
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/imports/yolo.py#L141
