### ISSUE TITLE
Duplicate labels on the same text, highlights more than the selected text

### ISSUE THREAD

**Issue by MAliNaqvi** [heartexlabs/label-studio#256]
**Describe the bug**
Duplicate labels on the same text, highlights more than the selected text

**To Reproduce**
1. Create a "Named Entity Recognition" project
2. Add a task
3. Select a label and highlight a text
4. Select another label and highlight the same text
5. Press submit button
6. For one of the labels the highlight will appear from beginning of line till the end of selected block

**Expected behavior**
Submitting two labels to one block of text should highlight selected text only.  

**Screenshots**
Before clicking submit/update button
![image](https://user-images.githubusercontent.com/13531332/79114668-dc4bce80-7d51-11ea-87c0-efa4e756121c.png)
After clicking submit/update button
![image](https://user-images.githubusercontent.com/13531332/79114724-fdacba80-7d51-11ea-836c-5bf110413239.png)

**Environment:**
 - OS: macOS, ubuntu
 - Browser: chrome, firefox
 - Labelstudio Version: 0.5.0

**Comment by MAliNaqvi** [comment]
Not in the latest version. Thank you!

**Comment by nabinkhadka** [comment]
https://github.com/heartexlabs/label-studio-frontend/issues/117

**Comment by nabinkhadka** [comment]
@hlomzik Can you please check [this](https://github.com/heartexlabs/label-studio-frontend/issues/117) and open this issue?
