### ISSUE TITLE
Issue import text data for ner

### ISSUE THREAD

**Issue by jonnyjohnson1** [heartexlabs/label-studio#258]
**Describe the bug**
When I drag a .txt file on the import tasks box, I get the error:

(I can load the tasks by clicking the import box and going through the uploader screens.)

"Error: can't upload/process file on server side. Reasons:
Critical error, see console for more description"

The terminal says:

"raise ValidationError('load_tasks: No data found in DATA or in FILES')
label_studio.utils.exceptions.ValidationError: load_tasks: No data found in DATA or in FILES
[2020-04-13 23:31:02,175] [werkzeug] [INFO] 127.0.0.1 - - [13/Apr/2020 23:31:02] "POST /api/import HTTP/1.1" 500 -"

**To Reproduce**
1. Go to 'import' tab.
2. Drag and drop a text file
3. See error

**Expected behavior**
The file should load, and tasks should appear in the tasks.json file.

**Environment (please complete the following information):**
 - OS: iOS
 - Browser: Chrome and Brave
 - Python Version: Python 3.6.2
 - I ran pip install label-studio to get the latest version

**Additional context**
I can upload the document by clicking the upload box instead of dragging and dropping the file.

**Comment by niklub** [comment]
Hi, @jonnyjohnson1 !  Could you please provide me an example of that file so I can reproduce an error?

**Comment by makseq** [comment]
I checked it with the last version (0.7.0) of LS, no errors were detected.

**Comment by jonnyjohnson1** [comment]
Alright...I'm sorry I didn't respond. The issue was happening seemingly randomly, I put off checking why and just didn't get back to you.

**Comment by makseq** [comment]
Don't worry, feel free and reopen this issue if you still have this error.
