### ISSUE TITLE
Importing txt from local storage results as links only

### ISSUE THREAD

**Issue by topl0305** [heartexlabs/label-studio#2589]
Maybe it's my fault, but i have no idea how to solve it atm.

System setup is linux + docker + local storage.
Label studio version 1.5.0
Configuration looks alright. 
I'm using directories /mydata for  /label-studio/data and /mydata/pranesimai for /label-studio/files
Docker started more or less OK, the only problem is updates from pypi (so, doesn't matter)

In directory /pranesimai i have a lot of txt files i need to label.
So i setup it as in this picture
<img width="550" alt="setup" src="https://user-images.githubusercontent.com/58388770/176677792-9131da33-fb33-4f27-ac50-d2099e8c1d7c.png">

After syncing i got a list of files, but instead of content i can see only links and no text.
<img width="1308" alt="links" src="https://user-images.githubusercontent.com/58388770/176678233-d85b6dd3-b7a7-404e-8d6e-436f8862a679.png">

Similar behaviour i get when i'm trying to import txt file manually.
Import -> drag and drop txt file -> Treat CSV/TSV as TimeSeries -> Import

What i find strange, when importing txt files is why i'm forced to choose that Treat CSV/TSV option? It's plain text file!

Any ideas how to solve it?

**Comment by makseq** [comment]
Add `valueType="url"` to your Text tag in the Labeling config.
