### ISSUE TITLE
Text highlight for Labels tag does not highlight the last character

### ISSUE THREAD

**Issue by ftesser** [heartexlabs/label-studio#259]
**Describe the bug**
Versions 0.5.0 and 0.5.1 show different behaviors on text highlights for Labels tag with respect to version 0.4.8.

Taking as an example the prediction stored in file `label_studio/examples/text_named_entity/tasks.json`, where the following chunk of json is relevant:
```json
"value": {
                            "end": 353,
                            "labels": [
                                "Date"
                            ],
                            "start": 343,
                            "text": "February 22"
                        }
```

Using version 0.4.8 the highlight text is correctly the text from char 343 to char 353 (included) so the text `February 22` is all highlighted (see Screenshot 1).
Using version 0.5.1 (and also 0.5.0) the highlight text miss the last char so only `February 2` is highlighted (see Screenshot 2).

**To Reproduce**

```
label-studio start --init --force test_path -l label_studio/examples/text_named_entity/config.xml -i label_studio/examples/text_named_entity/tasks.json --input-format json
```

**Expected behavior**
Version 0.4.8 had the correct behavior.

**Screenshots**
***Screenshot 1***
version 0.4.8
![image](https://user-images.githubusercontent.com/983665/79255426-917fa300-7e86-11ea-86f7-bbcdc7843e57.png)
***Screenshot 2***
version 0.5.1
![image](https://user-images.githubusercontent.com/983665/79255534-b7a54300-7e86-11ea-8a43-fed5483b95f2.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Mozilla 75.0
 - Version 0.5.1 

**Additional context**

**Comment by hlomzik** [comment]
Hi! Sorry for late reply and this sudden inconvenience.
But actually that was a fix and current behaviour is correct. `text` in the serialised data was captured in previous version and we don't use it during deserialisation, just displaying it.
Length of captured data should be equal the difference between start and end positions. As it is in current version.

**Comment by ftesser** [comment]
Hi @hlomzik, I just make the same test with version 0.7.1 but there is something that I dont understand.

I have just modified the label_studio/examples/text_named_entity/tasks.json as following to be compatible with the new name:

```diff
diff --git a/label_studio/examples/text_named_entity/tasks.json b/label_studio/examples/text_named_entity/tasks.json
index 47df8e0..9c680ee 100644
--- a/label_studio/examples/text_named_entity/tasks.json
+++ b/label_studio/examples/text_named_entity/tasks.json
@@ -9,7 +9,7 @@
                 "created_ago": "2 weeks, 6 days",
                 "result": [
                     {
-                        "from_name": "ner",
+                        "from_name": "label",
                         "id": "beFiQTT1cU",
                         "source": "$text",
                         "to_name": "text",
```

and then again:
```
label-studio start --init --force test_path -l label_studio/examples/text_named_entity/config.xml -i label_studio/examples/text_named_entity/tasks.json --input-format json
```

The result is that the last char is not highlited.
If I try to delete the label and select  again `February 22` with the browser and save the task, I see that the endchar is now:
```json
"end": 354,
```

So whats the right behaviur  for this example that is in the repository?
Is it correct to have `"end": 354`  or `"end": 353`?
If it is correct to have "end": 354, shoudl be better to updated the examples.
