### ISSUE TITLE
Problem with loading data with cloud storage (AWS S3)

### ISSUE THREAD

**Issue by inzamamsafi** [heartexlabs/label-studio#2595]
**Describe the bug**
Link got uploaded instead of CSV file while loading data with cloud storage.

**Screenshots**
![image](https://user-images.githubusercontent.com/80524710/177106888-bea534e9-8f81-497f-bafb-8e57403ee092.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Label Studio Version 1.5.0

**Comment by makseq** [comment]
You need to use `valueType="url"` inside of your <Text> (or whatever) tag.
