### ISSUE TITLE
Remove headers

### ISSUE THREAD

**Issue by pietrolesci** [heartexlabs/label-studio#2596]
Hi there,

I am trying to embed the label studio UI via iframe and I receive the following error: `'X-Frame-Options' set to 'deny'` which I think is related to the header. Would it be possible to allow for embedding the UI by removing this type of header?

Thanks a lot in advance for your consideration

**Comment by robert-s-lee** [comment]
@makseq and @nikitabelonogov reopening this as setting X-Frame-Options works on a laptop but does not work when running in the cloud.   working with @danbider on integrating label studio in an app built using https://lightning.ai/ app.  

Any thoughts on making the change on the Django side so that x-frame-options are removed? 

The setup in Django is https://docs.djangoproject.com/en/4.0/ref/clickjacking/

```from django.http import HttpResponse
from django.views.decorators.clickjacking import xframe_options_exempt

@xframe_options_exempt
def ok_to_load_in_a_frame(request):
    return HttpResponse("This page is safe to load in a frame on any site.")
```

**Comment by makseq** [comment]
Do you mean we need to include this middleware into label studio?

**Comment by robert-s-lee** [comment]
@makseq yes that is what Django doc is suggesting in order to remove X_FRAME_OPTIONS

**Comment by farioas** [comment]
`ALLOW-FROM` directive is not supported by Chrome and Safari, it works only for localhost.

`SAMEORIGIN` is supported by all browsers, you can safely use it

**Comment by S0PEX** [comment]
I ran into to the same issue yesterday and would like to inform you that there is no need to modify the src or container image.
When you are serving your services through a reverse proxy you can just rewrite the `X-Frame-Options` field in the header.

This basically works on all common proxies
E.g `header_down` for Caddy (https://caddyserver.com/docs/caddyfile/directives/reverse_proxy)
```
reverse_proxy {
    header_down X-Frame-Options "allow-from https://your-domain.gg"
}
```

Analogous in `nginx` using `proxy_hide_header` (https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_hide_header).

Same exists in `traefik` and etc.

**Comment by robert-s-lee** [comment]
TY @S0PEX   I cross-linked to https://github.com/Lightning-AI/lightning/issues/14218

**Comment by farioas** [comment]
Okay guys, I've managed it. 

Starting from commit a26e4bd6cf592240df7266ab13b363c1826c908c there is no more X-Frame-Options header on App level.

So, in order to expose label-studio without nginx in front you have to add the following env variables:

```
SESSION_COOKIE_SAMESITE=None
CSRF_COOKIE_SAMESITE=None
SESSION_COOKIE_SECURE=1
USE_ENFORCE_CSRF_CHECKS=0
```

**Comment by themattinthehatt** [comment]
@farioas do you know when these updates will be available from the pip-installed version of label studio?

**Comment by farioas** [comment]
These changes were released in `1.7.2`. You have to install it, set env variables from my previous message and run `label-studio` command. Or you can test it on https://huggingface.co/

**Comment by themattinthehatt** [comment]
Great thanks for the info! I'm trying to run this locally at the moment; I'm working on a lightning app with @robert-s-lee, and we previously had label studio running with nginx. Does this update mean that I can totally remove all nginx commands, as long as the above environment variables are set? Or just that I don't also need to remove the x-frame-options through nginx? Sorry for the simple questions, I'm not well-versed in the UI world.

**Comment by farioas** [comment]
You don't need nginx anymore in front, x-frame-options was removed from app level.

You can use this [Dockerfile.hgface](https://github.com/heartexlabs/label-studio/blob/develop/Dockerfile.hgface) as a reference how to configure `label-studio` for IFRAME usage.
