### ISSUE TITLE
Object Detection with Bounding Boxes - Export image without bounding box

### ISSUE THREAD

**Issue by maxstrobel** [heartexlabs/label-studio#2597]
**Describe the bug**
Export of images without annotations fail for YOLO & COCO.

**To Reproduce**

1. Setup a project for "Object Detection with Bounding Boxes"
```
<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="Car" background="blue"/>
  </RectangleLabels>
</View>
```
2. Import an image.
3. Submit the image without a bounding box
4. Export as YOLO or COCO.
5. The image will not be exported.

**Expected behavior**
Images without bounding boxes are exported.

**Screenshots**

![image](https://user-images.githubusercontent.com/34747372/177163285-4a265540-7b57-4f46-9503-4e6e33da9a75.png)
![image](https://user-images.githubusercontent.com/34747372/177163401-baf378a0-d99c-456f-8c0c-9c6db10a6137.png)

**Environment (please complete the following information):**
 - Label Studio Docker container: `heartexlabs/label-studio:latest`
 - Label Studio Version:

```
{
  "release": "1.5.0",
  "label-studio-os-package": {
    "version": "1.5.0",
    "short_version": "1.5",
    "latest_version_from_pypi": "1.5.0",
    "latest_version_upload_time": "2022-06-16T15:13:28",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "Update version to 1.5.0",
    "commit": "be324a94eee5c9950889d9c06f5c2153088adfd9",
    "date": "2022-06-16 17:21:53 +0300",
    "branch": "HEAD",
    "version": "1.5.0+0.gbe324a9"
  },

  "label-studio-frontend": {
    "message": "Merge pull request #685 from heartexlabs/fb-dev-1975/support-long-unbo ...",
    "commit": "1bdc91ca6c321358f92099103cc4464dad4ff6a0",
    "branch": "master",
    "date": "2022-06-07T22:39:08Z"
  },

  "dm2": {
    "message": "ci: DEV-2445: Set concurrency for PR Sync (#72)",
    "commit": "fef23777df2832daec664ace96bee9bcc399dd4d",
    "branch": "master",
    "date": "2022-06-07T11:28:06Z"
  },

  "label-studio-converter": {
    "version": "0.0.40"
  }
}
```

**Comment by KonstantinKorotaev** [comment]
Hi @maxstrobel 
Could you please update your label-studio-converter to 0.0.42rc1 and check one more time?

**Comment by makseq** [comment]
@maxstrobel could you please show the version page here: `/version` ?

**Comment by maxstrobel** [comment]
@makseq - Here's the version page:
```
{
  "release": "1.5.0",
  "label-studio-os-package": {
    "version": "1.5.0",
    "short_version": "1.5",
    "latest_version_from_pypi": "1.5.0.post0",
    "latest_version_upload_time": "2022-07-13T16:52:40",
    "current_version_is_outdated": true
  },

  "label-studio-os-backend": {},

  "label-studio-frontend": {
    "message": "Merge pull request #685 from heartexlabs/fb-dev-1975/support-long-unbo ...",
    "commit": "1bdc91ca6c321358f92099103cc4464dad4ff6a0",
    "branch": "master",
    "date": "2022-06-07T22:39:08Z"
  },

  "dm2": {
    "message": "ci: DEV-2445: Set concurrency for PR Sync (#72)",
    "commit": "fef23777df2832daec664ace96bee9bcc399dd4d",
    "branch": "master",
    "date": "2022-06-07T11:28:06Z"
  },

  "label-studio-converter": {
    "version": "0.0.42rc0"
  }
}
```


I did the following steps:

1. Pull & run a bash in the latest docker image.
2. Clone the repo & checkout v1.5.0.
3. Change in `deploy/requirements.txt` label-studio-converter to 0.0.42rc0.
4. Run labelstudio & do the export.

Still the same behavior. Images without annotations are not exported as YOLO dataset.

**Comment by maxstrobel** [comment]
@KonstantinKorotaev, sorry by mistake I took rc0.

rc1 seems to solve the issue 🎉

**Comment by KonstantinKorotaev** [comment]
Good to hear
