### ISSUE TITLE
runtime error when trying to delete an annotation if sorting is not default

### ISSUE THREAD

**Issue by nadjet** [heartexlabs/label-studio#2604]
**Describe the bug**
After sorting the items in the project by some data field, I select a row and select "Delete annotation": I get a runtime error: "Cannot resolve keyword 'ordering_field' into field (see attached screenshot).

**To Reproduce**
![photo_2022-07-05_15-13-13](https://user-images.githubusercontent.com/8031067/177343787-1be58228-18a8-4f48-8d1f-af278850dcf6.jpg)

1. Order the items in your project by some data field
2. Select an item with a completed annotation in your project (tick the ID)
3. Select "DELETE ANNOTATIONS" under the "Task" dropdown to delete the annotation you selected
4. You should get an error like in the attached screenshot
5.  To enable deletion, you should reverse to Default order, then the error disappears.

**Comment by triklozoid** [comment]
@nadjet can you share your task example? I tested on this one and didn't see the error: 
```
[
  {
    "data": {
      "text": "Calif. wildfires signal the arrival of a planetary fire age https://t.co/Vvo9noqQfA"
    }
  }
]
```

Also full traceback would be helpful.

**Comment by makseq** [comment]
@nadjet are you using LS from github repo? or from pip? Please try the latest version (1.5.0post0) from pip.

**Comment by WillieMaddox** [comment]
Same problem here. Ubuntu 20.04, Python v3.8, pip install into fresh virtualenv, LS v1.6.0. 

For me, it's happening when I try to delete the image prediction.

**Comment by makseq** [comment]
@WillieMaddox Could you show the screenshot with the error? And also logs from your console. 
I couldn't reproduce it with the latest develop branch.

**Comment by WillieMaddox** [comment]
Upgraded to v1.7.0 last week and have not been able to reproduce the error since.

**Comment by makseq** [comment]
As I remember we've fixed it some time ago.
