### ISSUE TITLE
Unable to load image when specified in task as an S3 url

### ISSUE THREAD

**Issue by hazel-erickson** [heartexlabs/label-studio#2607]
I have noticed label studio provides the functionality to

- Use an S3 bucket as target storage and sync image files from s3
- Use an S3 bucket as target storage and sync json 'task' files from s3

My images and tasks need to be hosted on S3 securely. However when I sync task files from S3, the image does not load as this is also stored in s3 but I believe label studio does not have permission to load the image.

Although I am providing the IAM access key and secret access key for both the tasks and the images, label studio only uses it to load the tasks. Is there a way to configure this to use the IAM key and secret access to load the image specified in the task as well?

![Error Message](https://user-images.githubusercontent.com/79285021/177449347-3c003388-6e13-420d-a212-8c47c5bcd8d9.PNG)

**Comment by makseq** [comment]
@hazel-erickson 
1) You need to use Source Storage for task importing, not Target Storage.
2) Just use `s3://` links in you `task.json` files, e.g.: 

```
{"image": "s3://my-storage/x.jpg"}
```

LS will resolve s3:// links automatically.
