### ISSUE TITLE
<Shortcut/> Tag write text twice

### ISSUE THREAD

**Issue by lxtadhamnawito** [heartexlabs/label-studio#2617]
**Describe the bug**
On using <Shortcut /> with <TextArea /> the text provided bt shortcut always is displayed twice not only once.
ex: if shortcut is writing word "Hello", on using shortcut it will write in textarea "HelloHello"

This is the xml configuration I used to reproduce the above issue
```
<View>
  <Labels name="labels" toName="audio">
    <Label value="Speaker 1" />
    <Label value="Speaker 2" />
  </Labels>
  <AudioPlus name="audio" value="$audio"/>

  <View visibleWhen="region-selected">
    <Header value="Provide Transcription" />
  </View>

  <TextArea name="transcription" toName="audio"
            rows="2" editable="true"
            perRegion="true" required="true" >
    <Shortcut alias="Silence" value="SILENCE" hotkey="ctrl+q" background="#3333333" />
  </TextArea>
</View>

```

**Steps to reproduce the behavior:**
1. Go to playground and copy past above configuration
2. Click on shortcut hotkey "ctrl+q"
3. You will see "SilenceSilence" in textarea

**Expected behavior**
It should only add the text in shortcut once.

**Screenshots**
![image](https://user-images.githubusercontent.com/66368677/177773418-f9756124-4bc9-4db7-80ca-3e25fc34d384.png)

I went through the code of TextArea and checked the function 
```
    onShortcut(value) {
      self.setValue(self._value + value);
    }
```

because of the concatenation it always displayed it twice because self_value is populated from onChange and Value which comes from shortcut is concatenated on it. 
I hope that this might help if my investigation was correct.

**Comment by lxtadhamnawito** [comment]
@makseq I'm using version 0.8.0 which is an old one, but the screenshot from playground.

idk if the code I'm sharing is updated or not on latest versions of label-studio.
I managed to solve it on my side by doing this, but again I think this might be old code for newer versions, 
I hope this might help again :)

```
    onShortcut(value) {
      self.setValue(self._value + value)
      self.addText(self._value)
    },
```

**Comment by juliosgarbi** [comment]
@lxtadhamnawito check the latest develop version of LS from the develop branch, it should be fixed there.

**Comment by lxtadhamnawito** [comment]
@makseq How to upgrade my current one ?

**Comment by makseq** [comment]
pip install -U label-studio
label-studio start project-name

After this LS will migrate your old data to the new DB. Old projects continue working with old version too. 
I recommend to create a fresh python environment for the new LS version.
