### ISSUE TITLE
Support for Translation use-case

### ISSUE THREAD

**Issue by GokulNC** [heartexlabs/label-studio#262]
**Is your feature request related to a problem? Please describe.**
Machine Translation is a task which is of greater importance in NLP. It'd be great if annotations for translation is supported.

**Describe the solution you'd like**
Something similar to Text Summarization, with options like ability to provide multiple translations for a given input sentence. Disabling multi-line text, and adding support for dynamically providing N number of translations using a '+' button, and the ability to remove a translation field by 'x' button.

**Optional features that might make the tool better**

- Specifying source and destination language for each translation use-case.

**Describe alternatives you've considered**
For now, it may be fine to use the Text Summarization use-case itself, with each translation in new line. 

**Additional context**
For example, [Doccano](http://doccano.herokuapp.com/demo/translation/) supports this.

One can also consider a similar task called transliteration annotation, and hence probably name this use-case task in a generalized way.

**Comment by makseq** [comment]
It seems LS provides this functionality quite a long time ago. The key is in maxSubmissions="100"  and editable="true". Try this config: 

```
<View>
  <Header value="Please read the text" />
  <Text name="text" value="$text" />

  <Header value="Provide one sentence summary" />
  <TextArea name="answer" toName="text"
            showSubmitButton="true" maxSubmissions="100" editable="true"
            required="true" />
</View>
```

To remove submission use the panel Results on the right. 

[Try it on the playground](https://labelstud.io/playground?config=%3CView%3E%3Cbr%3E%20%20%3CHeader%20value%3D%22Please%20read%20the%20text%22%20%2F%3E%3Cbr%3E%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%20%2F%3E%3Cbr%3E%3Cbr%3E%20%20%3CHeader%20value%3D%22Provide%20one%20sentence%20summary%22%20%2F%3E%3Cbr%3E%20%20%3CTextArea%20name%3D%22answer%22%20toName%3D%22text%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20showSubmitButton%3D%22true%22%20maxSubmissions%3D%22100%22%20editable%3D%22true%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20required%3D%22true%22%20%2F%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E)
