### ISSUE TITLE
Not able to load the project

### ISSUE THREAD

**Issue by ZhongyuYin** [heartexlabs/label-studio#2625]
Hi, I'm a newbie to Label Studio and I just installed it today. When I create a new project and save it, it seems that I just stuck at the interface below. I just have no idea how to fix this error. Could anybody help me with that? Thanks very much!
![image](https://user-images.githubusercontent.com/107917125/177957639-7a676134-96bf-42f1-978f-3adc629b03e6.png)

**Comment by makseq** [comment]
@ZhongyuYin Could you please check `pip install label-studio==1.4.1post1` or switch to Google Chrome?

**Comment by ZhongyuYin** [comment]
Thanks a lot! Switching to Google Chrome has perfectly solved my problem.

**Comment by makseq** [comment]
@ZhongyuYin btw we release a fix today, upgrade your LS to 1.5.0post0.

**Comment by rath321** [comment]
Hi @makseq I have tried pip install label-studio==1.4.1post1 using this but the problem is still persisting
need help
