### ISSUE TITLE
Possible to prevent multiple completions?

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#263]
The labeling interface shows "Completions" "Predictions" "Results" on the right, and it is easy for anyone to add more that one completion.

This is often not wanted, would it be possible to disallow having more than one completion? If a user changes the annotation, it would just replace the current completion? 

Also would it be possible to just suppress all that information shown on the right (Completions, Predictions, Results), this only confuses annotators for simple tasks like text classification.

**Comment by johann-petrak** [comment]
A workaround is to manually patch the javascript to not include some of the UI elements here:
https://github.com/heartexlabs/label-studio/blob/master/label_studio/static/js/lsb.js#L180

**Comment by deppp** [comment]
Thanks @johann-petrak for mentioning the workaround. I think we can close that for now. As a side note, we will be working on making that configuration easier, probably close to the `0.9.0` version, right now we're at `0.7.0`
