### ISSUE TITLE
How create dataset format FUNSD ?

### ISSUE THREAD

**Issue by DimIsaev** [heartexlabs/label-studio#2634]
example format:

```
        {
        "form": [
        {
            "id": 0,
            "text": "Registration No.",
            "box": [94,169,191,186],
            "linking": [
                [0,1]
            ],
            "label": "question",
            "words": [
                {
                    "text": "Registration",
                    "box": [94,169,168,186]
                },
                {
                    "text": "No.",
                    "box": [170,169,191,183]
                }
            ]
        },
        {
            "id": 1,
            "text": "533",
            "box": [209,169,236,182],
            "label": "answer",
            "words": [
                {
                    "box": [209,169,236,182
                    ],
                    "text": "533"
                }
            ],
            "linking": [
                [0,1]
            ]
        }
    ]
    }
```

**Comment by makseq** [comment]
You need to construct a labeling config first, then it will be much easier to understand what you need.

**Comment by makseq** [comment]
It looks like standard OCR task, check this labeling config please, will it work for you? 

```
<View>
  <Image name="image" value="$ocr"/>

  <Labels name="label" toName="image">
    <Label value="Text" background="green"/>
    <Label value="Handwriting" background="blue"/>
  </Labels>

  <Rectangle name="bbox" toName="image" strokeWidth="3"/>
  <Polygon name="poly" toName="image" strokeWidth="3"/>

  <TextArea name="transcription" toName="image"
            editable="true"
            perRegion="true"
            required="true"
            maxSubmissions="1"
            rows="5"
            placeholder="Recognized Text"
            displayMode="region-list"
            />
</View>
```

**Comment by DimIsaev** [comment]
> It looks like a standard OCR task, check this labeling config please, will it work for you?
> 


It doesn't seem to solve the link issue.  
this part dataset

```
            "linking": [
                [0,1]
            ]
```

**Comment by makseq** [comment]
It this link between bboxes?

**Comment by DimIsaev** [comment]
> It this link between bboxes?

yes
this example 
![download](https://user-images.githubusercontent.com/11172642/178440756-ee1b623b-f975-456e-8487-eaba22755f3a.png)

**Comment by WaterKnight1998** [comment]
@DimIsaev did you solve this in the end? Or you used another tool?

**Comment by DimIsaev** [comment]
> @DimIsaev did you solve this in the end? Or you used another tool?

project  paused
I'll be back later

**Comment by makseq** [comment]
As workaround you can follow this way:

1. you can go to console where you run LS and call there:
```
label-studio shell
```
it will run LS shell (Django shell_plus) and you will be able to execute Django ORM commands

2. In shell plus: 
```
from tasks.serializers import TaskWithAnnotationsSerializer

tasks = Task.objects.filter(project=<ID>)
export_json_data = TaskWithAnnotationsSerializer(tasks, many=True).data
```

3. Optionally:
```
import json 
with open('export.json', 'w') as f:
  json.dump(export_json_data, f)
```

**Comment by MercyPrasanna** [comment]
I am also having to label something like this.

The labeling tool should use auto OCR so that it becomes easy to work for these cases.

**Comment by WaterKnight1998** [comment]
> I am also having to label something like this.
> 
> The labeling tool should use auto OCR so that it becomes easy to work for these cases.

They added a new feature for this https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/examples/tesseract ![image](https://user-images.githubusercontent.com/17755198/165186574-05f0236f-a5f2-4179-ac90-ef11123927bc.gif)

**Comment by knowrohit** [comment]
@makseq can we connect on slack? I have an urgent query to be solved. Related to the same issue regarding output format for OCR into funsd dataset.

**Comment by makseq** [comment]
Check this PR: https://github.com/heartexlabs/label-studio-converter/pull/127

Unfortunately we can't make 100% compatible conversion to FUNSD format, because it has root bboxes and words bboxes and LS doesn't build root bboxes automatically. So, this converter creates one root bbox with one word inside of it.

**Comment by wujushan** [comment]
> > I am also having to label something like this.
> > The labeling tool should use auto OCR so that it becomes easy to work for these cases.
> 
> They added a new feature for this https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/examples/tesseract 

Hi, @WaterKnight1998, I had a try by following readme. In step 4, setup Tesseract ML backend: 
> pip install -r label_studio_ml/examples/tesseract/requirements.txt
> label-studio-ml init my-ml-backend --from label_studio_ml/examples/tesseract/ner_ml_backend.py --force
> label-studio-ml start my-ml-backend -d -p=9090 --debug

But I cannot find the file label_studio_ml/examples/tesseract/ner_ml_backend.py.

**Comment by knowrohit** [comment]
The ner_ml_backend.py is now the tesseract.py file boss

**Comment by JSv4** [comment]
@DimIsaev, @wujushan, I wanted to suggest another possibility here too. I'm working on an open source tool that can export directly in FUNSD. It's called [OpenContracts](https://github.com/JSv4/OpenContracts/tree/v1.2.0). Check it out. Feedback welcome!

**Comment by MonaMamdouh66** [comment]
> Check this PR: [HumanSignal/label-studio-converter#127](https://github.com/HumanSignal/label-studio-converter/pull/127). Now you can export to FUNSD using this script.
> 
> Unfortunately we can't make 100% compatible conversion to FUNSD format, because it has root bboxes and words bboxes and LS doesn't build root bboxes automatically. So, this converter creates one root bbox with one word inside of it.

this script doesn't support the linking[] how to do it?
