### ISSUE TITLE
Question: identify user/annotator?

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#264]
Would it be possible to allow several different people to annotate the same task on different computers and track which user or IP or session key created the annotation? 
I am thinking doing this with the "start" command in the same project, not with start-multi-session.

What I find confusing is that the "Completions" area in the labeling screen says something like "Created undefined by Admin" - where does that user name "Admin" come from? Apparently wherever it comes from, it is not actually stored with the completions data though?

I am thinking some very simple way to assign user names for now, no login or similar, just allow the user to e.g. store his username in a cookie when the config requires a name.

**Comment by makseq** [comment]
Right now LS doesn't support different users. If you want you can implement the simple version of user account via flask & browser sessions and write them to completions on save.
