### ISSUE TITLE
No auto-annotation was shown after ML backend successfully ran

### ISSUE THREAD

**Issue by pinecho** [heartexlabs/label-studio#2643]
Hello,

I am using detecron2 as the backend to do auto-annotate. **The model runs successfully** and generates output as expected.
However, **no auto-annotation was shown** in Label Studio.

Could you please help check the problem? Thank you.

1. This is the log of the backend, the model successfully read the image and detected 13 instances.
```
[2022-07-11 15:28:07,077] [INFO] [werkzeug::_log::225] 10.74.1.90 - - [11/Jul/2022 15:28:07] "POST /setup HTTP/1.1" 200 -
###【Loading model...】
###【Finish Loading model from label_studio_ml/examples/mask_segmentation/mask_rcnn_R_50_FPN_3x.yaml label_studio_ml/examples/mask_segmentation/mask_rcnn_R_50_FPN_3x.yaml 】
Get the image_url from task: /data/upload/4/b46cd960-input.jpg
Get the image_url when predict： /data/upload/4/b46cd960-input.jpg
/home/mike/miniconda3/envs/Label-Studio/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
End of prediction, detected  13  instances.
```

2. This is my labelling configuration:
```
<View>
  <Image name="image" value="$image" valueType="url" zoom="true"/>
  <BrushLabels name="tag" toName="image">
    <Label value="airplane" predicted_values="airplane" background="rgba(255, 0, 0, 0.7)"/>
    <Label value="car" predicted_values="car" background="rgba(0, 0, 255, 0.7)"/>
    <Label value="person" predicted_values="person" background="#FFA39E"/>
    <Label value="horse" predicted_values="horse" background="#D4380D"/>
    <Label value="umbrella" predicted_values="umbrella" background="#FFC069"/>
    <Label value="apple" predicted_values="apple" background="#AD8B00"/>
  </BrushLabels>
</View>
```

3. There was no auto-annotation in Label Studio as follows:
![image](https://user-images.githubusercontent.com/37013626/178295842-c4f04e50-35aa-4058-bbc2-30db8b6f22aa.png)

4.  the `predict()` will return `output_task` in following format:
```
            results = []
            results.append({
                    #"id": str(uuid.uuid4())[0:8], task_id
                    "original_width": img_width,
                    "original_height":img_height,
                    "image_rotation": 0,
                    "value": {
                        "format": "rle",
                        "rle": output_rle,
                        "brushlabels": [output_label],
                        },
                    "from_name": self.from_name,
                    "to_name": self.to_name,
                    "type": "brushlabels",
                    "origin": "detetron2",
                })
```

```
        output_task = {
                #"id":xxx
                "data":{
                    "image":image_url
                    },
                "predictions":[
                    {
                        #"id":xxx
                        "created_ago": "1 minute",
                        "result":results,
                        #"was_cancelled": False,
                        #"ground_truth": False,
                        "completed_by": 1,
                    }
                ],
                "model_version":"v1.0",
                "annotations": []
        }
```
5. This is the `output_task` which would be returned to Label Studio

`{'data': {'image': '/data/upload/4/422eebb5-cartest.webp'}, 'predictions': [{'created_ago': '1 minute', 'result': [{'original_width': 1200, 'original_height': 800, 'image_rotation': 0, 'value': {'format': 'rle', 'rle': [0, 58, 152,... 194, 224, 0], 'brushlabels': ['person']}, 'from_name': 'tag', 'to_name': 'image', 'type': 'brushlabels', 'origin': 'detetron2'},..........], 'completed_by': 1}], 'model_version': 'v1.0', 'annotations': []}`

**Comment by pinecho** [comment]
@KonstantinKorotaev

**Comment by pinecho** [comment]
@KonstantinKorotaev Could you please help check this problem, thank you:)

**Comment by KonstantinKorotaev** [comment]
Hi @pinecho 
In the predict method you should return list in format of predictions, check example in [ml backend  examples](https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/simple_text_classifier/simple_text_classifier.py#L80).

**Comment by pinecho** [comment]
Hi @KonstantinKorotaev 
**Thank you so so much, it works. You save a lot of my time!**

Could I ask you one more question?
Why does it show only one auto-annotation?
![image](https://user-images.githubusercontent.com/37013626/178331133-40e27992-5c95-4e65-9a59-b79bc4430752.png)
I checked the backend log; the model detected 13 instances and returned a list `prediction` with all 13 instances to Label Studio. 
Here is the return:
`[{'result': [{'original_width': 425, 'original_height': 369, 'image_rotation': 0, 'value': {'format': 'rle', 'rle': [0, 9, 146, ... 244, 182, 0], 'brushlabels': ['person']}, 'from_name': 'tag', 'to_name': 'image', 'type': 'brushlabels', 'origin': 'detetron2'}]}, {'result': [{'original_width': 425, 'original_height': 369, 'image_rotation': 0, 'value': {'format': 'rle', 'rle': [0, 9, 146, ..., 39, 128, 0], 'brushlabels': ['person']}, 'from_name': 'tag', 'to_name': 'image', 'type': 'brushlabels', 'origin': 'detetron2'}]}, {'result': [{'original_width': 425, 'original_height': 369, 'image_rotation': 0, 'value': {'format': 'rle', 'rle': [0, 9, 146, ... 126, 28, 0], 'brushlabels': ['person']}, 'from_name': 'tag', 'to_name': 'image', 'type': 'brushlabels', 'origin': 'detetron2'}]}, {'result': [{'original_width': 425, 'original_height': 369, 'image_rotation': 0, 'value': {'format': 'rle', 'rle': [0, 9, 146,... 88, 176, 0], 'brushlabels': ['person']}, 'from_name': 'tag', 'to_name': 'image', 'type': 'brushlabels', 'origin': 'detetron2'}]},`

**Thank you again for your kind help!**

**Comment by pinecho** [comment]
Hi, I found the solution and listed it blow in case someone maybe needed when he is working on instance auto-annotation:
the return of the `predict()` function should be:
```
results = [] 
for i in range(len(result_scores)):
            # loop body
            results.append({
                    #"id": str(uuid.uuid4())[0:8], task_id
                    "original_width": img_width,
                    "original_height":img_height,
                    "image_rotation": 0,
                    "value": {
                        "format": "rle",
                        "rle": output_rle,
                        "brushlabels": [output_label],
                        },
                    "from_name": self.from_name,
                    "to_name": self.to_name,
                    "type": "brushlabels",
                    "origin": "detetron2",
                    'score': output_score,
                })
return [{"result":results}]
```

**Comment by jehanjen** [comment]
i have the same error but i cant fix it,could you please help me
