### ISSUE TITLE
Question: What is the difference between Choices/Choice and Labels/Label?

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#266]
I set up the same text classification task, once using Choices/Choice in the config and another time with Labels/Label (everything else being the same) and it seems this gets presented in exactly the same way to the annotator. Is there any difference between those?

Hmm after trying to modify the config in the GUI, when I try to save I get the error message
`{"label_config":["'int' object is not iterable"]}` but I have no idea what that means.

This is what the complete config looks like:
```
<View>
  <Header value="x"></Header>
  <Text name="text" value="$text"></Text>
  <View style="box-shadow: 2px 2px 5px #999;                padding: 20px; margin-top: 2em;                border-radius: 5px;">
    <Header value="Choose one of the class labels for tweet "></Header>
    <Labels name="label" toName="text" choice="single" showInLine="true">
      <Label value="Yes"></Label>
      <Label value="No"></Label>
      <Label value="Honestly, do not know"></Label>
    </Labels>   
    <Header>Confidence:</Header>
    <Rating name="rating" toName="text" maxRating="10" icon="star" size="medium" />
    <Header>Remark (optional)</Header>
    <TextArea name="remark" toName="text"></TextArea>
  </View>
</View>
```

**Comment by makseq** [comment]
@johann-petrak Hello, sorry for a long answer. We've released a new version on LS 0.7.0. I've checked your config in it, it works well. 

Choice is a checkbox. 
![image](https://user-images.githubusercontent.com/501780/83438563-4c213000-a44a-11ea-8c33-ede1ee01637b.png)

Label is a region. 
![image](https://user-images.githubusercontent.com/501780/83438650-7246d000-a44a-11ea-8b47-780d02402f55.png)
