### ISSUE TITLE
When the amount of data is large, exporting data will be very slow. Is there any solution?

### ISSUE THREAD

**Issue by LBZHK** [heartexlabs/label-studio#2663]
thank you!

**Comment by makseq** [comment]
@LBZHK are you talking about timeouts? If yes, please try to use snapshots via SDK: 

https://labelstud.io/sdk/project.html#label_studio_sdk.project.Project.export_snapshot_create

https://labelstud.io/guide/export.html#Export-snapshots-using-the-API

**Comment by yangboz** [comment]
> @LBZHK are you talking about timeouts? If yes, please try to use snapshots via SDK:
> 
> https://labelstud.io/sdk/project.html#label_studio_sdk.project.Project.export_snapshot_create
> 
> https://labelstud.io/guide/export.html#Export-snapshots-using-the-API

and any updated docker version to support that?

**Comment by makseq** [comment]
@yangboz yes, we has been supporting export snapshots for a long time.

**Comment by ntakouris** [comment]
For full hd images, takes about 5 minutes for 300 of them (3-4 bounding boxes each). That's a LOT of time.

**Comment by makseq** [comment]
@ntakouris 

As a workaround, you can follow this

1. go to console where you run LS and call there:
```
label-studio shell
```
  it will run LS shell (Django shell_plus) and you will be able to execute Django ORM commands

2. In shell plus: 
```
from tasks.serializers import TaskWithAnnotationsSerializer

tasks = Task.objects.filter(project=<ID>)
export_json_data = TaskWithAnnotationsSerializer(tasks, many=True).data
```

3. Optionally:
```
import json 
with open('export.json', 'w') as f:
  json.dump(export_json_data, f)
```

**Comment by LBZHK** [comment]
Roger that. I'll try it over here. Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heartexlabs/label-studio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月9日(星期二) 上午7:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [heartexlabs/label-studio] When the amount of data is large, exporting data will be very slow. Is there any solution? (Issue #2663)





 
@ntakouris
 
As a workaround, you can follow this
  
go to console where you run LS and call there:
  label-studio shell  
it will run LS shell (Django shell_plus) and you will be able to execute Django ORM commands
  
In shell plus:
  from tasks.serializers import TaskWithAnnotationsSerializer tasks = Task.objects.filter(project=<ID&gt;) export_json_data = TaskWithAnnotationsSerializer(tasks, many=True).data   
Optionally:
  import json  with open('export.json', 'w') as f:   json.dump(export_json_data, f)

**Comment by makseq** [comment]
Also you can use this console command: 
https://labelstud.io/guide/export.html#Export-using-console-command
