### ISSUE TITLE
Separate task deletion

### ISSUE THREAD

**Issue by AlphaCaprice** [heartexlabs/label-studio#267]
As I understand, there is no way to delete separate task, only all tasks toghether.
So it would be nice if there is a feauture to delete task, like it is with **delete completion** in the table.
Does it make sense?

**Comment by slavakurilyak** [comment]
# User Story

As a data labeler, I want to individual delete tasks that are irrelevant to a project.

# Suggested User Experience

![VgRPCc](https://user-images.githubusercontent.com/6625584/81508440-fb8a3d00-92b8-11ea-9082-17db3c937056.jpg)

**Comment by himan2411** [comment]
Is is removed in version 1.0.1? I can't find it.

**Comment by makseq** [comment]
You can do similar on Data manager via actions. Please, select tasks you want to delete, then you will see a list of actions to perform with the selected tasks.
