### ISSUE TITLE
How to enlarge the image size automatically rather than zoom handly？

### ISSUE THREAD

**Issue by Fuyubai** [heartexlabs/label-studio#2671]
**Label Studio version: 1.5.0**

I get the image like this
![image](https://user-images.githubusercontent.com/49471258/179142275-82027618-0bde-44d0-b622-76ab3778c2a7.png)
and I want to make the image full of screen automaticlly like this (below example is zoomed handly)
![image](https://user-images.githubusercontent.com/49471258/179142301-45edb39a-a2ad-480b-adef-41a56ee721c3.png)

I try to set "width" and "maxwidth" like #1146 , but it seems didn't work, there is my setting
```
<View>
  <Image name="image" value="$imgage" width="1000%" maxWidth="1500px"/>
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="Car" background="blue"/>
  </RectangleLabels>
</View>
```

**Comment by hlomzik** [comment]
Hi! We finally [fixed this issue](https://github.com/heartexlabs/label-studio/pull/2654) and also improved zoom control. You can check this in develop.
Just be sure that `fflag-feat-frontend-dev-2504-image-enhancements-zoom-center` is enabled.

**Comment by makseq** [comment]
We will release some fixes tomorrow regarding `fflag-feat-frontend-dev-2504-image-enhancements-zoom-center` flag, so I would recommend that you wait a little and use the day-after-tomorrow build of LS (from 27 July).
