### ISSUE TITLE
Clicking a HTML link not possible within HyperText for text classification

### ISSUE THREAD

**Issue by johann-petrak** [heartexlabs/label-studio#268]
For a text classification task I wanted to prepare a HTML document that shows various bits of information (in addition to the actual text), including a link that is intended to show more information related to the text. 
The link is present in the HyperText as `<a href="http://some.adress.com/" target="_blank">some link text</a>` and the link gets shown as a link the cursor changes as it should when moved over the link, but clicking the link does nothing. The only way to open the link is to right-click and choose one of the open options. 

I think this may be caused by the javascript code that normally handles the interaction for span annotations as for NER. For text classification that code is not needed though.

I think in general, even for NER, if something is a link, it should be clickable. If the annotation task is about annotating the URL or link text, then it can be presented as normal text.

**Comment by makseq** [comment]
This is not really a bug. It will be uncomfortable to select regions on the text if anchor clicks are enabled. But we definitely need to have some popup to open the anchor link. I hope we'll add it in the nearest release.
