### ISSUE TITLE
Can't see images in tasks when import files(jpg) through GCP's GCS sync

### ISSUE THREAD

**Issue by jzhan6688** [heartexlabs/label-studio#2721]
**Describe the bug**
Hello team - We wanted to import images into Label Studio from GCP GCS bucket by using Label Studio's Cloud Storage featue.
I set up the settings according to Label Studio's instruction [doc](https://labelstud.io/guide/storage.html#Set-up-connection-in-the-Label-Studio-UI-1). But after I sync images into LabelStudio, I can't see the images shown and got error as below:

```
There was an issue loading URL from $image value

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)
Technical description:
URL:
```

I set CORS for our GCS bucket, but still couldn't see the images. I am pasting all details in screenshots as below.

**Expected behavior**
I am expecting to see images showing up in Label Studio tasks after syncing from GCS bucket

**Screenshots**
Error I saw(image file is in jpg format and not showing up in tasks):
![image](https://user-images.githubusercontent.com/101445799/180697096-4858f75b-9c74-4d45-a337-8954b7865b58.png)

Source Cloud Storage setting I have (no permission issue I found - as result data can be exported to target bucket)
![Screen Shot 2022-07-24 at 9 11 53 PM](https://user-images.githubusercontent.com/101445799/180697526-84cbf88c-fa24-4cf3-bb7a-2891b5218d4c.png)

CORS policy I am having:

```
[
    {
      "origin": ["https://label-studio-xxx-xxx-xxx-xxx-xxxxxxxx-uc.a.run.app"],
      "method": ["GET", "PUT"],
      "responseHeader": ["Content-Type"],
      "maxAgeSeconds": 3600
    }
]
```

Javascript console:
![image](https://user-images.githubusercontent.com/101445799/180697823-f05efc6c-4bfc-4805-adc2-ce95104ee999.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - Label Studio Version [latest-1.5.0]

**Comment by berniwal** [comment]
Have you set the Service Account Role "roles/iam.serviceAccountTokenCreator" to the Service Account you are using? For me the problem was that I gave the permissions to the wrong Service Account, after I have applied the Role to the correct one it worked. 
I found the name of the Service Account labelstudio was using in the Error displayed in the DEBUG logs, you can enable them using the "--log-level DEBUG" Flag in the "label-studio start" command.

**Comment by jzhan6688** [comment]
> serviceAccountTokenCreator

@berniwal It worked after I tried your suggestion! Thank you so much for help! 

@makseq I think this is worthy to add in the LS documentation [here](https://labelstud.io/guide/storage.html#I-can%E2%80%99t-see-the-data-in-my-tasks)

**Comment by makseq** [comment]
@jzhan6688 sure, we will handle this! @anithamuthu2022  please help ;-)
