### ISSUE TITLE
LDAP : anonymous with TLS certificates ?

### ISSUE THREAD

**Issue by alnhk** [heartexlabs/label-studio#2739]
Hi All - we are evaluating the label studio with openLDAP integration, before we do that, did go thru the article - https://labelstud.io/guide/auth_setup.html ...question mark..we are using  anonymous access (TLS enabled with certificate).. so, is there any suggestions to be included in order to achieve the anonymous access with TLS certificates to be passed ? Please provide an example on how we can include in the label studio (docker-compose or kubernetes)?  Below is an example we set in all windows+linux host (sssd.conf) ..please provide an example means provide the lines as to how to achieve anonymous access with TLS (certificate), below lines are mandatory..

```
ldap_uri = ldap://ldap.example.com:389
ldap_default_bind_dn = cn=sssd,dc=example,dc=com
ldap_search_base = dc=example,dc=com
ldap_id_use_start_tls = true
ldap_tls_reqcert = hard
ldap_tls_cacert = /etc/pki/tls/CA/ldap.ca
```

**Comment by farioas** [comment]
Try to use this configuration
```
AUTH_LDAP_ENABLED=1
AUTH_LDAP_SERVER_URI=ldap://ldap.example.com:389
AUTH_LDAP_BIND_DN=cn=sssd,dc=example,dc=com
AUTH_LDAP_USER_SEARCH_BASES=dc=example,dc=com
AUTH_LDAP_BIND_PASSWORD=""
AUTH_LDAP_START_TLS=1
AUTH_LDAP_CONNECTION_OPTIONS=OPT_X_TLS_CACERTFILE=/path/to/ca.pem;OPT_X_TLS_REQUIRE_CERT=OPT_X_TLS_HARD
```
