### ISSUE TITLE
Bug report on annotation experience

### ISSUE THREAD

**Issue by paulineChav** [heartexlabs/label-studio#2770]
**Describe the bug**
Hi,

For a NER tasks,
labels : A and B
Sentence to annotate: "hello world"

1. I annotate "hello" as A
2. I add a metadata to the previous annotation
3. I annotate "world" as B.
4. bug: "Hello" label also becomes B, because annotation of "hello" was still selected.

Temporary fix :
after adding a metadata, press "ESC" to unselect annotation of "hello"

Ideal Solution:
after adding a metadata, click elsewhere to unselect annotation of "hello"

https://user-images.githubusercontent.com/29196330/182107878-2b77545c-75df-41cc-bc02-862fdb4bb96c.mov

**Comment by makseq** [comment]
Looks like you should check this option and deselect it:

![image](https://user-images.githubusercontent.com/501780/182473979-4aa6e748-e1c1-4985-8886-51250316371a.png)

![image](https://user-images.githubusercontent.com/501780/182473756-b32097b6-2e11-4b71-8a48-35ee60ad836c.png)
