### ISSUE TITLE
Import and Sync image from local storage Label Studio

### ISSUE THREAD

**Issue by AnelorG** [heartexlabs/label-studio#2775]
Hi,

**Describe the bug**
I would like to sync my dataset (only .jpg) that is localized on a local server and Label Studio.
This dataset is updated with new images every day.
I'm new in Label Studio.
First step for me is to import (fake) image from local repository (my desktop for example) to LS.
And... I get trouble !

I have made this
LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
in my anaconda prompt and then run label-studio

I have created new SOURCE STORAGE in LS :
storage type : local files
absolute path : C:/Users/anne-/Desktop/test1
filter : .*jpg
Treat every bucket object as a source file : checked

Connexion is a success but when I go to the project I have my 3 files but images are not uploaded.
icon broken image/Data
My cmd displays 
```
test1\0003_0009_000026_001.jpg does not match uri regex ([\"'])(?P<uri>(?P<storage>{})://[^\1=]*)\1
[2022-08-02 15:28:45,389] [io_storages.utils::get_uri_via_regex::25] [WARNING] /data/local-files/?d=Users\anne-\Desktop\test1\0003_0009_000028_001.jpg does not match uri regex ([\"'])(?P<uri>(?P<storage>{})://[^\1=]*)\1
[2022-08-02 15:28:45,391] [io_storages.utils::get_uri_via_regex::25] [WARNING] /data/local-files/?d=Users\anne-\Desktop\test1\0003_0009_000043_001.jpg does not match uri regex ([\"'])(?P<uri>(?P<storage>{})://[^\1=]*)\1
[02/Aug/2022 15:28:45] "GET /api/tasks?page=1&page_size=30&view=7&project=3 HTTP/1.1" 200 1604
[2022-08-02 15:28:45,449] [django.request::log_response::224] [WARNING] Not Found: /data/local-files/
[2022-08-02 15:28:45,450] [django.request::log_response::224] [WARNING] Not Found: /data/local-files/
[02/Aug/2022 15:28:45] "GET /data/local-files/?d=Users\anne-\Desktop\test1\0003_0009_000028_001.jpg HTTP/1.1" 404 0
[02/Aug/2022 15:28:45] "GET /data/local-files/?d=Users\anne-\Desktop\test1\0003_0009_000043_001.jpg HTTP/1.1" 404 0
[2022-08-02 15:28:45,456] [django.request::log_response::224] [WARNING] Not Found: /data/local-files/
[02/Aug/2022 15:28:45] "GET /data/local-files/?d=Users\anne-\Desktop\test1\0003_0009_000026_001.jpg HTTP/1.1" 404 0
``` 

When I click on an image I have this :
There was an issue loading URL from $image value
![image](https://user-images.githubusercontent.com/47145000/182388000-6b44d980-9ca7-42cf-8a4c-ea04f0b6ac10.png)

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)
Technical description:
URL: [/data/local-files/?d=Users\anne-\Desktop\test1\0003_0009_000026_001.jpg](http://localhost:8080/data/local-files/?d=Users\anne-\Desktop\test1\0003_0009_000026_001.jpg)

**Environment (please complete the following information):**
 - OS: WINDOWS 11
 - Label Studio 

Thanks a lot, 

AL

**Comment by makseq** [comment]
@AnelorG Could you please check this video tutorial: https://www.youtube.com/watch?v=lo6ncQajbdU
It's for more complex cases when your data has more than one image, however it shows how to connect Local Storage correctly. Hope it'll help.

**Comment by AnelorG** [comment]
Thanks for your response.
So I have this (after config my json task):
![image](https://user-images.githubusercontent.com/47145000/183058622-bb1c5ba7-768d-4b11-9634-fdabc44c5802.png)

How to delete the first 6 raws that come when I import my txt file ?

**Comment by makseq** [comment]
select them with checkboxes and delete using actions
![Uploading image.png…]()

**Comment by AnelorG** [comment]
Thanks @makseq 
I have solved with your solution when my folder is in my machine but when I try to import photo from local server it failed. I have the same image icon broken, even if I import a json file containing the name of the image.

My local storage is successfully connected. The image are imported in LS but it's impossible to see and label these image (icon broken).

Have you faced this problem before?

Thanks

**Comment by AnelorG** [comment]
Perhapas, I've found a solution but how do you import multiple images ? We should import mutliple json file ??? Each of them containing 
{
"data": {
"image": "/data/local-files/?d=dataset1/0001_0001_000068_001.jpg"
}
}

**Comment by AnelorG** [comment]
I've solved using txt files instead of json :)

**Comment by makseq** [comment]
Why didn't you click Sync button on Source Storage dialog?

**Comment by mechmehmet** [comment]
I tried to click sync button and it looked succesfully synced but the images are not visible. I think url does not work somehow. 

 @AnelorG how did you managed to solve this problem.

**Comment by ratbunch** [comment]
Super old but this the most helpful link on Google so figured I'd make it a little more helpful.

You don't need json like the video. You can import a text file that list all the files in the same way as the string in the video. For your convenience here is a bash one liner that'll make a .txt file from all the files in the current directory. Set RELATIVE_PATH as the same path string you did after ?d= in the url.

`RELATIVE_PATH="/home/user/dataset1/"`
`find "$PWD" -type f -exec basename {} \; | sed "s|^|/data/local-files/?d=$RELATIVE_PATH|" > paths.txt`

I had to select "list of tasks" as my option when I imported it. Worked out perfect. Amazing its this annoying to get local files working still after 2 years.

**Comment by Santhosshe** [comment]
Iam getting runtime error when trying to check connection for export storage using S3 but the syncing is working for same credential
