### ISSUE TITLE
Can't adjust the width of the taxonomy dropdown

### ISSUE THREAD

**Issue by lance0108** [heartexlabs/label-studio#2776]
**Describe the bug**
The width of the taxonomy dropdown is too small. The texts cannot be displayed in one line and is wrapped to the next line, overlapping with the text in the next line. 
Adjusting the width in the html does not help. 
<Taxonomy name="media" toName="title" maxUsages="1" leafsOnly="true" minWidth="300px" maxWidth="auto">

Version 1.4 does not have this issue with exactly the same labeling configuration.

**Expected behavior**
No text overlapping should happen.

**Screenshots**
<img width="182" alt="image" src="https://user-images.githubusercontent.com/5000621/182483231-d185f055-9551-4a44-befc-39fe8fa82cbd.png">

**Environment (please complete the following information):**
 - OS: ubuntu
 - Label Studio Version  
label-studio                   1.5.0.post0
label-studio-converter         0.0.40
label-studio-tools             0.0.0.dev14

**Additional context**

**Comment by hlomzik** [comment]
We have fix for this and it had to get to the release, but as I can see it's only in develop right now. So you can use it from the repo. Or you can use `Taxonomy minWidth="200px"` or any other size which works for you.
If the bug is still there, reopen issue, please! Thank you!
