### ISSUE TITLE
Show Annotation and Prediction panel settings do not appear to be working

### ISSUE THREAD

**Issue by drc-kkonz** [heartexlabs/label-studio#2784]
Annotation settings for "Show Annotation Panel" and "Show Prediction Panel" do not appear to be working.

**To Reproduce**
* Open any of the open preview options, such as the ones found on this page:
https://labelstud.io/tags/audio.html
* Click on the settings and toggle either the show annotations or show predictions panels

**Expected behavior**
* I would expect, if I am understanding the intended use correctly, these checkboxes would display/remove the results panel.

**Additional context**
The behavior of the checkbox appears to be the same in the playground, local install, and the enterprise managed service.

**Comment by makseq** [comment]
Thank you for your feedback. The current documentation uses a pretty old version of Label Studio Engine. We are working on a big update regarding Playground and Previews in our documentation, all these moments should be improved there.
