### ISSUE TITLE
Exported completions to CoNLL results in incomplete labelling

### ISSUE THREAD

**Issue by Ziinc** [heartexlabs/label-studio#279]
**Describe the bug**
Exporting completions results in ~~skipped~~ empty completions being exported as well.

~~This is mainly an issue regarding with the [converter library](https://github.com/heartexlabs/label-studio-converter).~~

**To Reproduce**
Using the `Converter` class exposed in `label-studio-converter`,

```

conv = Converter("my_config.xml")
conv.convert_to_conll2003('completions', 'tmp/completions')
```

The resulting `result.conll` file contains the ~~skipped~~ empty completions.

~~Looking at the src code, this bug would translate across the different formats, as the completions folder path is passed to the converter directly and the converter does not filter the completions by the `skipped` key.~~

**Environment :**
 - Version: Tested on v0.6.0 branch, but main bug is in `label-studio-converter` src.

**slightly tangential comment**
It is also rather puzzling why skipped tasks (that have not had any input to the document) records a completion. There does not seem to be any benefit for doing so, as it makes it impossible to find skipped tasks in the `Tasks` tab.

**Comment by Ziinc** [comment]
Did a bit more investigating and realized that you've already added the skipped task filtering in this commit:
https://github.com/heartexlabs/label-studio-converter/commit/83ff059a1257cf600559c09a3459483d54073f81

Turns out that this bug is caused by creating a completion based on a model prediction.

This can be replicated as follows:
1. Import an empty task
2. open task, will show predictions from ML backend
3. check that there are no completions
4. make modifications
5. observe two completions saved. One is blank, and the other is with the edited predictions.

![image](https://user-images.githubusercontent.com/22714384/81104275-de660f00-8f44-11ea-87c2-a12eb4a3b158.png)

**Comment by Ziinc** [comment]
Did even more investigating. 

I've mostly figured out that it comes from the converter function, since the data in the UI and completion JSON are correct.

For some reason, on export to CoNLL2003 format, the tags suddenly get cut off.

In this attached example, all entities are marked as INGREDIENTS in the UI  and json, but are not labelled in the conll file:

![image](https://user-images.githubusercontent.com/22714384/81107352-9b5a6a80-8f49-11ea-829c-b0d97b9af519.png)

![image](https://user-images.githubusercontent.com/22714384/81107682-23407480-8f4a-11ea-829f-d62902152630.png)


I've tracked down the code that most likely causes this bug:
https://github.com/heartexlabs/label-studio-converter/blob/83ff059a1257cf600559c09a3459483d54073f81/label_studio_converter/utils.py#L27

I'm not too familiar with the implementation of this fn though, so I can't identify which part is causing the issue. Do point me in the right direction, I might be able to figure out a PR for this issue.

**Comment by Ziinc** [comment]
@niklub @deppp Fix for this issue is in https://github.com/heartexlabs/label-studio-converter/pull/4

**Comment by MattHag** [comment]
That's also an issue in Label Studio 1.8.2.post1. I only discovered it, because my training results were so bad. There are 200 recently created labels missing in the CONLL export, which shows up in the JSON export.

It seems this happens, when an annotated data gets and updated and is then exported.
