### ISSUE TITLE
HTML display from S3 source doesn't show

### ISSUE THREAD

**Issue by rydka** [heartexlabs/label-studio#2791]
**Describe the bug**
After setting the source storage to specify the path to my HTML files, when trying to display a file for annotation only the address of the file is displayed.
Ex : http://path_to_my_file.
The key and password to access the s3 have been set and the file displays correctly if open in another tab.

**To Reproduce**
1. Go to Cloud Storage and set an s3
2. Click on a task which have the s3 path for task[data][html]
3. Try to annotate

**Expected behavior**
The HTML is displayed correctly

**Environment (please complete the following information):**
 - Label Studio Version master branch

Thank for your time !
Rydka

**Comment by makseq** [comment]
@rydka You have to change your label config:
```
<HyperText value="$html">
=>
<HyperText valueType="url" value="$html"
```
