### ISSUE TITLE
HTML renderer for NER tagging causes completions to become internally out of sync

### ISSUE THREAD

**Issue by Ziinc** [heartexlabs/label-studio#280]
This bug is related to the text renderer for NER tagging. In v0.6.0 branch, it is currently using the html renderer by default. This results in the completion text becoming out of sync with the character start/end values.

In this example, a <strong> tag is rendered, causing the text in the results box going out of sync with the character start/end numbers. On hover over the "onta" result, "Talc" is highlighted instead.

![image](https://user-images.githubusercontent.com/22714384/81107989-9c3fcc00-8f4a-11ea-929c-17aaae987e42.png)

This does not impact exports, which are based on the char start/end (which are correct). 

This bug would affect downstream code that relies on the "text" key of the completion, such as the front

**Comment by hlomzik** [comment]
Hi, @Ziinc!
I could not reproduce this bug on my side, but we found some similar bugs and fixed them in new version 0.7.1. Could you please check it in your project?
I hope it works now, but if not, it would be very helpful to see your config and some part of your data to take a look at HTML structure.
