### ISSUE TITLE
Relations among entities - label disorder

### ISSUE THREAD

**Issue by Wigithub1201** [heartexlabs/label-studio#2800]
Hi， Under this page ‘’https://labelstud.io/playground/‘’，When a text is clicked multiple times, the associated label becomes confused
![image](https://user-images.githubusercontent.com/27763586/183617108-1596cd64-1550-4c2d-8196-6a4abbb9d23b.png)
![image](https://user-images.githubusercontent.com/27763586/183617364-7fb90a10-4bf0-4987-b9c8-ed71ddaae495.png)

**Comment by makseq** [comment]
@Wigithub1201 Hi, Playground uses outdated version of LS engine. Could you please check this issue in the latest LS?

**Comment by Wigithub1201** [comment]
@makseq Hi, yes, I installed the latest version in the project using the NPM install command. The version number for
"label-studio": "^1.0.1"

**Comment by makseq** [comment]
Sorry, I meant pip version, npm is slightly outdated too.. 
The last pip version is 1.5.0post0.

**Comment by hlomzik** [comment]
Anyway that's not about relations, that's our way to label text — if you have label selected (and related label is always selected when region is selected), then any text selection produces new region with this selected label. So when you double-click some region, the first click selects this region and related label, second one selects the word, creating a region on this word.
If you want to just select a text without creating a region, you have to unselect region first (`u` hotkey). It won't change double-click behaviour though...
