### ISSUE TITLE
Possible outdated documentation

### ISSUE THREAD

**Issue by MarioOurcart** [heartexlabs/label-studio#2803]
Hello everyone,

I've just started using your label studio and I must say it is great, thank you for your work and for keeping it open source.

I'm getting myself familiar with your API and I was searching through the documentation when I stumbled upon [validate label config endpoint](https://labelstud.io/api#operation/api_projects_validate_create), it is stated that when validation is successful status code 200 will be returned, BUT I keep getting 204 when I try to validate (hopefully) a valid label config.

I can see that I receive 400 when I try to validate an invalid label config so my question would be is the documentation outdated since documentation states that 200 will be returned on successful validation or I'm missing something here?

Thank you for your time.

**Comment by makseq** [comment]
@MarioOurcart Thank you for your report! Yes, API docs is outdated. This PR https://github.com/heartexlabs/label-studio/pull/2816 will fix it soon!
