### ISSUE TITLE
YOLO pre-annotated image imported shows misaligned bounding boxes

### ISSUE THREAD

**Issue by tayyabmujahid** [heartexlabs/label-studio#2809]
**Describe the bug**
When a pre-annotated json for YOLO is uploaded the bounding boxes are not aligned but display with a slight shift, the width and height remain the same. When looking at the imported data.The x, y, width and height seems to be imported alright (this is verified by looking at the "Show task source" button right of the image thumbnail of the task row. 

Now when the same imported data is exported in yolo format the x and y change (but not widht and height)

**Expected behavior**
The imported pre-annotated object detection bounding boxes must not be misaligned while displayed and the same data if exported   must be the same as it was imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/7406534/183932862-963414f1-43e7-4c01-827f-87281ddc70df.png)

![image](https://user-images.githubusercontent.com/7406534/183933515-187c7a3a-6d85-4cda-a338-adac78dc6405.png)
screen shot of the data from the "Show task source" button (these coordinates are correct)

![image](https://user-images.githubusercontent.com/7406534/183935123-1fbc9c91-081d-4f06-a1e4-975fc679af75.png)
screenshot of the corresponding entry from the exported .txt file  (that shows the normalized values of x,y,w,h). If back converted to label studio format by multiplying by 100 then the x and y coordinates(high lighted one) don't match

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Label Studio Version  - 1.5.0post0

**Comment by makseq** [comment]
@tayyabmujahid how do you import yolo annotators?

**Comment by tayyabmujahid** [comment]
@makseq 

Steps that i follow to import manually(this is just a test to see how importing pre-annotations works before i could use other methods to import in bulk from cloud storage)
1. import the image using the import button
2. copy the file path(to "data" key) to the pre-annotations JSON file 
3. upload the JSON file manually using the import button

PS: i use labelstudio on my local machine

**Comment by makseq** [comment]
@tayyabmujahid how do you convert YOLO to LS JSON ?

**Comment by makseq** [comment]
Although it looks like you converted it manually. Please use label-studio-converter for this: https://github.com/heartexlabs/label-studio-converter/pull/46
Most likely you incorrectly calculated coordinates, the correct code is here: https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/imports/yolo.py#L85

**Comment by tayyabmujahid** [comment]
Yes it worked for me now.I have changed my conversion formula to the one used [here](https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/imports/yolo.py#L85)

Thanks a lot

**Comment by jelalsultanov** [comment]
Hello, I have same issue but with Faster RCNN

My boudning boxes are visualized correctly with OpenCV but when I import these annotions to LS, i have incorrect boxes. I used conversion formula from LS's official website

![Annotation 2023-02-27 225555](https://user-images.githubusercontent.com/122475049/221802190-807b5997-59bd-4826-a0d0-4db4d465e4e4.png)
![asdasd](https://user-images.githubusercontent.com/122475049/221802197-fa3e2d93-8ceb-4c37-9bae-76630f1a6a29.png)

**Comment by makseq** [comment]
Try to use this coordinates for one bbox: 
```
                    "x": 25.0,
                    "y": 25.0,
                    "width": 50.0,
                    "height": 50.0,
```
You should be able to see the bbox in the center of you screen. It will be easier to debug everything with this example.
