### ISSUE TITLE
Error occurred while export results with more than one completions

### ISSUE THREAD

**Issue by alanwang93** [heartexlabs/label-studio#281]
After finished my demo task with on multiple-choice and two completions, I tried to export the results. The `JSON` format export works but `JSON_MIN`, `TSV`, and `CSV` formats throw this error: `Error occurred while export`.

It seems that this occurs when one task has more than one completions because the other three formats only allow one annotation.

Currently, every time I explore the tasks after finishing, a new empty completion will be automatically created, and then only `JSON` format can work.

**Comment by makseq** [comment]
I checked it, now it's working.
