### ISSUE TITLE
text not keeping at top.

### ISSUE THREAD

**Issue by kajyuuen** [heartexlabs/label-studio#2817]
**Describe the bug**
Text is not fixed. However, Text is properly fixed on the Labeling Interface's UI Preview.

**To Reproduce**
The template:

```
<View>
  <Style>
    .center-choices { text-align: center; }
    .target_text {
    	position: sticky;
	    top: 0px;
    }
  </Style>
  <View className="target_text">
    <Text name="text" value="$text"/>
  </View>
  <View style="height: 1000px;"/>
  <Choices name="a" toName="text" showInLine="true">
    <Choice value="ok"/>
  </Choices>
</View>
```

**Expected behavior**
The behavior in the Labeling Interface's UI Preview and the actual UI should match and text should be fixed.

**Screenshots**

UI Preview:
![image](https://user-images.githubusercontent.com/15792784/184277247-570decfe-068a-4474-81fb-547c389fc303.png)

UI:

![image](https://user-images.githubusercontent.com/15792784/184277395-5710994e-d129-4b56-a3ad-bda96f76a39c.png)

**Environment (please complete the following information):**
label-studio                   1.4.1.post1
label-studio-converter         0.0.39
label-studio-tools             0.0.0.dev11

**Comment by hlomzik** [comment]
`sticky` is very tricky, there are some requirement to container and nesting at least. In your case I'd use `position: fixed` without any coordinates, so it will stuck at the same place.

**Comment by kajyuuen** [comment]
Thanks!
