### ISSUE TITLE
Can't remove OCR relations

### ISSUE THREAD

**Issue by mike-grayhat** [heartexlabs/label-studio#2818]
**Remove button of OCR relations isn't working**

**To Reproduce**
1. Select an ocr region
2. Add a relation to another region
3. Go to label relations section
4. Click relation delete button
5. The relation stays

**Expected behavior**
Relation disappears

**Environment:**
 - OS: docker hub image
 - Label Studio Version >=1.4

**Comment by juliosgarbi** [comment]
@mike-grayhat check the latest version of LS, it should be fixed there. The current one is 1.5.0, please switch to it.

**Comment by mike-grayhat** [comment]
@juliosgarbi yeah, I tried it and it doesn't work

**Comment by juliosgarbi** [comment]
@mike-grayhat so try to use the latest version of LS from the develop branch, it's working and you can use this version until the next release

**Comment by mike-grayhat** [comment]
oh, I checked it now by installing it through pip and it works, thank you! By some reason seems there's an app version mismatch in docker hub images - I definitely tried 1.5 version, or maybe I messed them up somehow with local builds
