### ISSUE TITLE
Allow Label Stream Mode on Selected Tasks

### ISSUE THREAD

**Issue by hardianlawi** [heartexlabs/label-studio#2829]
**Is your feature request related to a problem? Please describe.**

I would like to go through the tasks that I have submitted to review them e.g. some tasks are more difficult and I would like to double-check my annotation. I expect that manually selecting all these tasks and clicking on `Label x tasks` would allow me to do this but it seems that they would always be filtered out from the queue.

**Describe the solution you'd like**

I expect that manually selecting all these tasks and clicking on `Label x tasks` would allow me to go through the completed tasks and skip through the ones that do not need to be updated. This would need another button to `skip without updating the state` of the task but it seems reasonable to me to have that button.

**Comment by makseq** [comment]
You can review these tasks in Quickview mode. Tasks that have annotations won't be passed to Label X Tasks stream, it's against the main app logic. 

In Enterprise edition we have a special Review All Tasks mode, it does what you want. Also we have a postpone action there, when users are able to postpone a task without a creation of an annotation.
