### ISSUE TITLE
Authentication when deployed on a VM.

### ISSUE THREAD

**Issue by rishabmps** [heartexlabs/label-studio#283]
**Is your feature request related to a problem? Please describe.**
An authentication token or username/password for the label studio server is required when deployed on a remote VM. This is to protect unauthorized access on the portal.
**Describe the solution you'd like**
The authentication mechanism of token like jupyter notebook or username, password-based authentication.
**Describe alternatives you've considered**
Making a VNC server and creating label studio server inside it. Authorization was added to the VNC server.

**Comment by makseq** [comment]
@rishabmps do you use nginx with LS?

**Comment by rishabmps** [comment]
Not yet, but I wish I knew how to configure it :)

**Comment by makseq** [comment]
Nginx is the fastest solution of your problem. 
Install nginx, apache2-utils (for htpasswd generation), open nginx.conf: 

```
# on ubuntu:
sudo apt install apache2-utils
sudo nano /etc/nginx/nginx.conf
```

Add to nginx.conf
```
server {
        server_name  0.0.0.0;  # or your domain, e.g.: test.com

        location / {
                proxy_pass http://localhost:8080;  # here is LS port
                auth_basic "Restricted Content";
                auth_basic_user_file /etc/nginx/.htpasswd;
        }
}
```
Generate .htpasswd file with user/passwords:

```
sudo htpasswd -c /etc/nginx/.htpasswd <username>
```

Restart nginx
```
sudo services restart nginx 
```


Read more here: 
https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04

**Comment by makseq** [comment]
Basic http auth added in release/0.7.3: 
https://labelstud.io/guide/#Auth-with-login-and-password
