### ISSUE TITLE
Mandate the sub-label/sub-choices in Conditional Classification

### ISSUE THREAD

**Issue by iqbalfarz** [heartexlabs/label-studio#2842]
This is my custom template below:

```
<View>
  <Header value="Listen the audio"/> 
  <Audio name="audio" value="$audio"/> 
  <Choices name="ontology" toName="audio" zoom="true" showInLine="true" hotkey="ctrl+enter" choice="multiple">
    <Choice value="domestic_sound" />
    <Choice value="speech" />
  </Choices>


    <View visibleWhen="choice-selected" whenTagName="ontology" whenChoiceValue="domestic_sound">
       <Header value="Select a Choice below for domestic_sound"/>
        <Choices name="domestic_sound_choice" toName="audio" showInLine="true" hotkey="ctrl+enter" choice="multiple" required="true"> 
        <Choice value="CLICKING" />
        <Choice value="WOOD" />
        <Choice value="FRYING" />
        <Choice value="SHUFFLING_CARDS" />
        </Choices>
    </View>
```

This is the template for conditional classification.

I want to make the sub-classes mandatory if and only if the corresponding choice is selected in main labels.

main labels are below:
```
<Choices name="**main_choices**" toName="audio" zoom="true" showInLine="true" hotkey="ctrl+enter" choice="multiple">
    <Choice value="domestic_sound" />
    <Choice value="speech" />
  </Choices>
```

So, If I select `domestic_sound` in the above choices, then only sub-choices under `domestic_sound` should be mandatory.

When I am adding `required=" true"` in the ``domestic_sound`` choices, It mandates the choices under `domestic_sound` without even selecting it in the main labels.

Can anyone please help me to get this functionality or behavior?
Thanks!

**Comment by iqbalfarz** [comment]
Hi @makseq, did you understand my question? I need an urgent solution. I really appreciate any help you can provide.

**Comment by makseq** [comment]
@iqbalfarz Hi, some time ago we've fixed similar problem. What LS version do you use? is it 1.5.0post0?

**Comment by iqbalfarz** [comment]
Because of some reason, I am using ``label-studio = "0.9.1.post1"``. But, can you give me a hint that what to add to the config file?
 OR 
the config file is OK, just to update the label-studio version?

I had another question, Why did you revoke the support of loading audio files using the command line with and after `1.0.0`?

**Comment by Gondragos** [comment]
Hi @iqbalfarz! I think there is a problem with the value of the `whenTagName` parameter. There should be a link to the tag that we need to control the visibility. So in this case you should use `whenTagName="**main_choices**"`, 'cause you have used  `**main_choices**` as a name.

**Comment by iqbalfarz** [comment]
> Hi @iqbalfarz! I think there is a problem with the value of the `whenTagName` parameter. There should be a link to the tag that we need to control the visibility. So in this case you should use `whenTagName="**main_choices**"`, 'cause you have used `**main_choices**` as a name.

Sorry, @Gondragos, It was a typo, I have updated the template.

**Comment by iqbalfarz** [comment]
Hi @makseq, It's working in the latest version of LS. Thanks!

**Comment by iqbalfarz** [comment]
> do you mean - loading of folder with audio files? If yes, we implemented another approach: https://labelstud.io/guide/storage.html#Local-storage

I mean loading the `tasks.json` file using the `--input-path` command.

For my current project, I am creating tasks, then creating sessions for each annotator differently. So, while creating the session earlier I was using the `--input-path` command to load the tasks as JSON files. But, `--input_path` is not working now in the latest version. So, how would I load my tasks.json file?

**Comment by makseq** [comment]
You can try to do it using SDK: https://labelstud.io/guide/sdk.html#Import-tasks-with-the-Label-Studio-Python-SDK
