### ISSUE TITLE
Only one prediction being displayed for time series 

### ISSUE THREAD

**Issue by harrymander** [heartexlabs/label-studio#2843]
**Describe the bug**

When adding multiple predictions for the same label to a time series, only the last prediction is displayed in the annotation view.

**To Reproduce**

1. Add time series task with a time series label
2. Add multiple predictions for the same label to the task
3. Go to annotation view for that task

**Expected behavior**
The time series plot should display highlights for each label prediction. Instead, it just displays the last one.

**Screenshots**

The single green `swallow` label is shown on the right of the plot: 
![Screenshot from 2022-08-18 23-42-37](https://user-images.githubusercontent.com/41089556/185387075-6e278dfa-74ff-40f3-9cf1-1a605e554baa.png)

There should be two other regions labelled earlier. The task has the following source:

```json
{
  "id": 25,
  "data": {
    "csv": "/data/local-files/?d=Y2xpY2stdGVzdGluZw-1/0020-kr012-obs.csv"
  },
  "annotations": [],
  "predictions": [
    {
      "id": 217,
      "model_version": "",
      "created_ago": "9 minutes",
      "result": [
        {
          "from_name": "label",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 9889,
            "end": 10308,
            "instant": false,
            "timeserieslabels": [
              "swallow"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-08-18T11:36:39.892102Z",
      "updated_at": "2022-08-18T11:36:39.892126Z",
      "task": 25
    },
    {
      "id": 218,
      "model_version": "",
      "created_ago": "9 minutes",
      "result": [
        {
          "from_name": "label",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 21994,
            "end": 22313,
            "instant": false,
            "timeserieslabels": [
              "swallow"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-08-18T11:36:39.929823Z",
      "updated_at": "2022-08-18T11:36:39.929842Z",
      "task": 25
    },
    {
      "id": 219,
      "model_version": "",
      "created_ago": "9 minutes",
      "result": [
        {
          "from_name": "label",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 33493,
            "end": 33959,
            "instant": false,
            "timeserieslabels": [
              "swallow"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-08-18T11:36:39.958756Z",
      "updated_at": "2022-08-18T11:36:39.958772Z",
      "task": 25
    }
  ]
}
```

(From this you can see there should be two other predictions at t = 9889 and t = 21994, however only the one at t = 33493 is displayed.)

Note that in the task view, the `Total predictions per task` column correctly displays that there are 3 predictions:

![Screenshot from 2022-08-18 23-55-46](https://user-images.githubusercontent.com/41089556/185388932-8ed9f19c-a6ab-40ce-8d9d-9aee38f3f32f.png)

My label config is as follows:

```xml
<View>
    <!-- Control tag for region labels -->
    <TimeSeriesLabels name="label" toName="ts">
        <Label value="swallow" background="green" hotkey="f" choice="multiple"/>
    </TimeSeriesLabels>

    <!-- Object tag for time series data source -->
    <TimeSeries name="ts" valueType="url" value="$csv" sep="," timeColumn="millis" overviewChannels="flow,ear">
        <Channel column="flow" units="L/m" displayFormat=",.1f" strokeColor="#1f77b4" legend="Flow rate"/>
        <Channel column="ear" strokeColor="#ff7f0e" legend="Ear audio"/>
    </TimeSeries>
</View>
```

**Environment (please complete the following information):**
  
- OS: Ubuntu 20.04
- Label Studio Version v1.5.0.post0 (Docker)
- Browser; Chrome 104.0.5112.79

**Additional context**

Predictions were added using `label_studio_sdk.project.create_prediction`.

**Comment by bmartel** [comment]
Hey @harrymander, the predictions are essentially treated as an annotation candidate, these should be selectable from the dropdown here:

![Screen Shot 2022-08-29 at 10 30 48 AM](https://user-images.githubusercontent.com/2242258/187238639-2c108e4b-0650-4dbe-b9ca-991ef8020230.png)

**Comment by harrymander** [comment]
Thanks @bmartel - I can see the predictions now. However, they are marked as 'read only' - is there a way to convert each prediction into an annotation (with appropriate editing of the start/end times as needed)?

**Comment by makseq** [comment]
@harrymander all predictions are read-only, you can copy them as annotations using this button: 
![image](https://user-images.githubusercontent.com/501780/188540060-e2b067a5-53c1-4ac0-8d19-9a7e412ed5c5.png)
![image](https://user-images.githubusercontent.com/501780/188540084-25ec9148-91b4-434e-9733-e54d0a6543de.png)
