### ISSUE TITLE
Exported CONLL format non standard?

### ISSUE THREAD

**Issue by tilusnet** [heartexlabs/label-studio#2845]
Hi,

Is the LS CONLL format export implementing any particular CONLL standard?
If so, which one? 

I notice for instance that plain punctuation is not segmented apart -- this is highly unusual from my admittedly limited experience.

Ref: https://universaldependencies.org/format.html

**Comment by KonstantinKorotaev** [comment]
Hi @tilusnet 
We are using CONL2003 format but without POS

**Comment by tilusnet** [comment]
Thanks.

Do you know why punctuation is not separated from words?
I haven't seen that elsewhere.

**Comment by KonstantinKorotaev** [comment]
We have a fix for it in [PR](https://github.com/heartexlabs/label-studio-converter/pull/92).
You can pull label-studio-converter from this branch and punctuation will be separated.

**Comment by tilusnet** [comment]
Thanks @KonstantinKorotaev

**Comment by makseq** [comment]
@tilusnet please write us a feedback about the fix!
Does it work for you?
