### ISSUE TITLE
Importing HTML Pages as Public URLs

### ISSUE THREAD

**Issue by slavakurilyak** [heartexlabs/label-studio#285]
**Is your feature request related to a problem? Please describe.**
When pasting a public URL of an HTM or HTML page, I see the following error:

```
Error: can't upload/process file on server side. Reasons:

int() argument must be a string, a bytes-like object or a number, not 'NoneType'

[object Object]

[object Object]

500
```

**Describe the solution you'd like**
As a data labeler, I would like to paste URLs of public pages, so I am not forced to manually copy HTML pages. 

As a data labeler, I expect Label Studio to automatically create a local copy of a public URL.

**Describe alternatives you've considered**
Uploading an HTML file locally

**Additional context**
Here are the steps I took to replicate my flow:

1. Go to [http://localhost:8080/import](http://localhost:8080/import)

2. Type: https://www.sec.gov/ix?doc=/Archives/edgar/data/1800/000110465920053384/abt-20200331x10q.htm

![WLW5jK](https://user-images.githubusercontent.com/6625584/81512408-43b75880-92d5-11ea-805f-74d5bc14d5dc.jpg)

3. Click "import"

![GfzxcI](https://user-images.githubusercontent.com/6625584/81512412-4914a300-92d5-11ea-992b-b321a75f515e.jpg)

**Comment by makseq** [comment]
added in https://github.com/heartexlabs/label-studio/pull/320
