### ISSUE TITLE
Label Studio AssertionError while Submitting Annotation [label_studio_ml.model::get_result::58]

### ISSUE THREAD

**Issue by askgitqa** [heartexlabs/label-studio#2850]
Hi,
I have implemented a `text classification` task with two class classifications and connected `label-studio-ml-backend` with the `label-studio`. The `Training` and `Prediction Retrieval` task is being done correctly. The only issue is is retraining after each annotation submission. 
It is throwing the following error
```
[2022-08-21 01:20:41,152] [ERROR] [label_studio_ml.model::get_result::58] 
Traceback (most recent call last):
  File "...\anaconda3\envs\ls\lib\site-packages\label_studio_ml\model.py", line 56, in get_result
    job_result = self.get_result_from_job_id(model_version)
  File "...\anaconda3\envs\ls\lib\site-packages\label_studio_ml\model.py", line 110, in get_result_from_job_id
    assert isinstance(result, dict)
```
ML Model Setting is as follows
<img width="873" alt="image" src="https://user-images.githubusercontent.com/111660659/185765169-eba501da-6649-41d2-8fb5-e01938654366.png">

Seems like `get_result` method  in `JobManager` [Class ](https://github.com/heartexlabs/label-studio-ml-backend/blob/d6e72f9e9b48129173df16a8ee5dc4a148f30f5c/label_studio_ml/model.py#L48) is not able to get the annotation result. 

This is also sending empty data in ` fit(self, completions, workdir=None, **kwargs)` method as shown below. I have used print statements to print these on the console for debugging.
```
***************-------FIT -----***********
completions -> ()
***************-------END-----***********

Label set has been changed:[]

***************-------FIT -----***********
input_text []
output_labels []
output_labels_idx []
***************-------END-----***********
```

Since input data is empty therefore fit is throwing the following error while doing `model.fit()`
```
ValueError: empty vocabulary; perhaps the documents only contain stop words
```

Any word of advice would be appreciable!

**Comment by jrdalenberg** [comment]
Looks like the same issue as https://github.com/heartexlabs/label-studio-ml-backend/issues/117

**Comment by KonstantinKorotaev** [comment]
Hi @jrdalenberg 
Do you use active learning?
If not - disable webhooks in your project and errors will disappear.

**Comment by askgitqa** [comment]
yes. I need to retrain the model after a certain time not every label submit.

**Comment by KonstantinKorotaev** [comment]
Hi @askgitqa 
When you are using active learning your fit method get only an event that you shoud handle.
Check this [example](https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/simple_text_classifier/simple_text_classifier.py#L105).

**Comment by askgitqa** [comment]
This issue is still unresolved `[label_studio_ml.model::get_result::58]`

**Comment by KonstantinKorotaev** [comment]
> This issue is still unresolved [label_studio_ml.model::get_result::58]

This issue is not connected with train issue, it tells that some of your training sessions ended without result and can't be used as checkpoint.

**Comment by shiva-kumarj** [comment]
I'm facing the same issue, even after turning off webhooks. I am using a custom ml backend.[label-studio-spacy]( https://github.com/tim-smart/label-studio-spacy). This error is popping up even before training has begun. 

```
[2023-07-13 16:34:05,734] [ERROR] [label_studio_ml.model::get_result_from_last_job::131] 1689178131 job returns exception:
Traceback (most recent call last):
  File "C:\Users\blahb\anaconda3\lib\site-packages\label_studio_ml\model.py", line 129, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "C:\Users\blahb\anaconda3\lib\site-packages\label_studio_ml\model.py", line 111, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
```

I've also tried the suggestion by @KonstantinKorotaev to handle the 'data' event. here is what my code looks like
```

def fit(self, annotations, workdir=None, **kwargs):
        """ This is where training happens: train your model given list of annotations, 
            then returns dict with created links and resources
        """
        if kwargs.get('data'):
            project_id = kwargs['data']['project']['id']
            tasks = self._get_annotated_dataset(project_id)
        else:
            **Rest of the code**
```

is there something else you recommend I try?

**Comment by KonstantinKorotaev** [comment]
@shiva-kumarj 

>  This error is popping up even before training has begun.

 
 Could  you please update to the latest ML backend package?

**Comment by shiva-kumarj** [comment]
I've tried that too, but the same error happens when submitting an annotated task. 
Here is what my virtual environment looks like

**conda packages**
```

# packages in environment at C:\Users\blahb\anaconda3\envs\label-studio:
#
# Name                    Version                   Build  Channel
libpq                     12.9                 hb652d5d_3    anaconda
vc                        14.2                 h21ff451_1    anaconda
vs2015_runtime            14.27.29016          h5e58377_2    anaconda
zlib                      1.2.13               h8cc25b3_0    anaconda
```

**label-studio packages**
```
label-studio                      1.8.0
label-studio-converter            0.0.53
label-studio-ml                   1.0.9           c:\users\blahb\anaconda3\lib\site-packages
label-studio-tools                0.0.0.dev11
```

In parallel, I am also running the simple text classifier ml backend that comes as part of the examples and seems to be working without problems.

Here's the error again

```
AssertionError
[2023-07-14 22:41:17,072] [ERROR] [label_studio_ml.model::get_result_from_last_job::131] 1689353507 job returns exception:
Traceback (most recent call last):
  File "C:\Users\blahb\anaconda3\lib\site-packages\label_studio_ml\model.py", line 129, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "C:\Users\blahb\anaconda3\lib\site-packages\label_studio_ml\model.py", line 111, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
[2023-07-14 22:41:17,073] [INFO] [model::__init__::55] MODEL CHECKPOINT: fallback
```

**Comment by shiva-kumarj** [comment]
quick question. will this ml backend only work for NER using spacy? I'm trying to run a text classification use case. Yes, I made the necessary configuration changes to config.cfg for **multilabel textcat** type usecase.

**Comment by nadinator** [comment]
Any updates on this? I'm getting a similar error:

```
[2023-08-15 10:17:45,525] [INFO] [werkzeug::_log::225] 192.168.8.181 - - [15/Aug/2023 10:17:45] "GET /health HTTP/1.1" 200 -
[2023-08-15 10:18:09,414] [ERROR] [label_studio_ml.model::get_result_from_last_job::131] 1692083863 job returns exception:
Traceback (most recent call last):
  File "C:\Users\Nadim\.conda\envs\label-studio-cp39\lib\site-packages\label_studio_ml\model.py", line 129, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "C:\Users\Nadim\.conda\envs\label-studio-cp39\lib\site-packages\label_studio_ml\model.py", line 111, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
```

Once this error happens, the ML backend disconnects form my project. If I then go into the shell where the backend is running and hit Enter, the backend continues running but doesn't reconnect. Then if I go into the data view of my project, the backend predicts everything just fine. So this bug doesn't kill anything, it's just weird and annoying because I manually have to go into the shell and hit Enter to fix it. I also have no idea how it just reconnected itself.
