### ISSUE TITLE
Attempting to write read-only database

### ISSUE THREAD

**Issue by Scolymus** [heartexlabs/label-studio#2855]
Sometime ago I was working with label-studio locally and it was working fine. Now I entered again and I still can see my data, but I cannot modify it. I'm having the following error:

`django.db.utils.OperationalError: attempt to write a readonly database`

I looked for the sql.lite file and I change its permissions to 777 just in case (~/.local/share/label-studio/label_studio.sqlite3). However, the error is still there. What can I do?

**Comment by farioas** [comment]
What is your backend filesystem?

**Comment by nikitabelonogov** [comment]
Sometimes it is also required writing rights to the directory in which your sqlite database is stored
Does the user that you running label-studio changed?

**Comment by Scolymus** [comment]
It is a local hard drive. Someone changed permissions, and I did a 777 chmod on sqlite file but wasn't working. Now I did it to the entire folder ~/.local/share/label-studio and it's working. Thanks!
