### ISSUE TITLE
Trying to import CSV file into label studio

### ISSUE THREAD

**Issue by Cheaterraptor** [heartexlabs/label-studio#2859]
Hello, I just discovered label-studio today and I am currently stuck.

I have a csv file with the columns = [col1, col2, ..., col13] and about 36000 rows. Now, each row needs to get classified based on the values in the columns (either pass or fail). The cell values are all either text or boolean. I read through the docs but couldnt really find how to do that. I tried adding each column as a text field, but I think the interpretation in label-studio of columns is different (Not sure though, I don't really understand the docs there). Everytime I tried using a template or custom template I get an sql- too many variables error.

I hope somebody can help me, thank you all so much :)

**Comment by makseq** [comment]
@Cheaterraptor Hello, please show your labeling config and sample of CSV data.

**Comment by Cheaterraptor** [comment]
Thank you for your answer :)

A sample of the csv data is:
[sample.csv](https://github.com/heartexlabs/label-studio/files/9496825/sample.csv)

I don't have a labeling config because I did not manage to import it the way I wanted to. I just want each row as a task and then display the different values in a table. If I see the information of the row (task) to label it either 1 (accept) or 0 (decline).

**Comment by makseq** [comment]
Looks a little bit weird. 

It works well with your sample.csv and this labeling config:
```
<View>
  ,,identity verified,keywords,budget_min,budget_max,type,upgrades,bid_count,bid_avg,status
  
  <Text name="text1" value="$rating"/>
  <Text name="text2" value="$payment verified"/>
  <Text name="text3" value="$identity verified"/>
  <Text name="text4" value="$keywords"/>
  <Text name="text5" value="$budget_min"/>
  <Text name="text6" value="$budget_max"/>
  <Text name="text7" value="$type"/>
  <Text name="text8" value="$upgrades"/>
  <Text name="text9" value="$bid_count"/>
  <Text name="text10" value="$bid_avg"/>
  <Text name="text11" value="$status"/>
  
  <View style="box-shadow: 2px 2px 5px #999;                padding: 20px; margin-top: 2em;                border-radius: 5px;">
    <Choices name="sentiment" toName="text1" choice="single" showInLine="true">
      <Choice value="Positive"/>
      <Choice value="Negative"/>
      <Choice value="Neutral"/>
    </Choices>
  </View>
</View>
```

If you have this error only using a large import file, it might mean two things:
* your file is corrupted
* you need to use postgres instead of sqlite (https://labelstud.io/guide/storedata.html#PostgreSQL-database)

**Comment by Cheaterraptor** [comment]
Wow, that works perfectly. Thank you so much!! I think my fault was that my file was too big :)
