### ISSUE TITLE
cant seem to get docker image to run locally 

### ISSUE THREAD

**Issue by nickvazz** [heartexlabs/label-studio#287]
` docker run --rm -p 8080:8080 -v `pwd`/my_project:/label-studio/my_project --name label-studio heartexlabs/label-studio:latest label-studio start my_project --init` starts a docker container, but the webserver does not seem to be loading. Is there another command I am missing?

**Comment by niklub** [comment]
Hi, @nickvazz ! Thank's for revealing the issue. Indeed, the default host has been changed, consider running docker by appending 0.0.0.0 host:
```
docker run --rm -p 8080:8080 -v `pwd`/my_project:/label-studio/my_project --name label-studio heartexlabs/label-studio:latest label-studio start my_project --init --host 0.0.0.0
```

We'll change the doc now and rollback the default host in the future releases.

**Comment by nickvazz** [comment]
Ahh thank you! I figured it out with your help! 😄
