### ISSUE TITLE
Relations among entities about the reset Event

### ISSUE THREAD

**Issue by Wigithub1201** [heartexlabs/label-studio#2870]
Hi，

After initialization, enter the page and directly click reset. The content in the list of Regions on the right will disappear, as shown in the figure. What is the reason？
![1661483739(1)](https://user-images.githubusercontent.com/27763586/186810201-947aedbb-1764-4170-844c-97df5078aaef.jpg)

**Comment by makseq** [comment]
@Wigithub1201 Hi, it's very old version of LS, please try the latest one (e.g. v1.5.0post0)
