### ISSUE TITLE
The "data" dict in source contains 2 kinds of keys "image" and "images"

### ISSUE THREAD

**Issue by pinecho** [heartexlabs/label-studio#2877]
Hi, I just found that the "data" dict in the source (also in the output JSON file )contains "**image**" and "**images**", which are all auto-generated by Label-Studio.
I do not know its pattern, so I encountered bugs when I tried to use the JSON file.

Could you please check what problem it is, thank you.

![image](https://user-images.githubusercontent.com/37013626/186991160-034602b8-7a89-41f1-af31-86cdcf1def23.png)

![image](https://user-images.githubusercontent.com/37013626/186990913-4bd412f1-0ba2-4129-9e02-bd5acee3caac.png)

![image](https://user-images.githubusercontent.com/37013626/186990805-58df84f7-e6c1-48c2-8fc2-2947fd5dcd01.png)

**Comment by makseq** [comment]
@pinecho it might have happened because you changed your labeling config at some moment. At the beginning it was `image`, then `images`.

**Comment by pinecho** [comment]
oooh, I found it. Thanks so much!
