### ISSUE TITLE
Uploading HTML Pages

### ISSUE THREAD

**Issue by slavakurilyak** [heartexlabs/label-studio#288]
**Describe the bug**
When I drag and drop an HTML file into the 'import' tab, I see that the task is not properly imported. When I click on the 'task', I see the following details:

```
/upload/09fc3dc24b5bd1feef4db15787cc026a-Mannatech.html
```

**To Reproduce**

1. Go to 'import' tab.
2. Drag and drop an HTML file ([example](https://www.sec.gov/Archives/edgar/data/1056358/000105635820000038/mtex0331202010-q.htm))
3. Go to 'tasks' tab.
4. Click on latest task.
5. See task details. 

**Expected behavior**
When I drag an HTML file, I expect the importer to properly show HTML contents and not a relative URL.

**Screenshots**
![screen](https://user-images.githubusercontent.com/6625584/81705348-cea66900-9423-11ea-8d5d-2f5661254692.jpg)

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.4 (19E287)
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
None

**Comment by slavakurilyak** [comment]
As a data labeler, I would like to import HTML files and not be forced to use JSON.

One way to accomplish this is to convert the HTML file into a minified HTML (removing whitespaces), then add the HTML contents to a JSON file.

```
{
    "text": {Minified HTML goes here}
}
```

**Comment by makseq** [comment]
Hi, @slavakurilyak. I'd like to say it's not bug but rather a feature request.
LS has support to url in <Text> tag, but not yet in <HyperText>. I think we will add it soon. 
Do you use HyperText? 

Right now it's better to use json-files upload with converted html pages to json field.

**Comment by slavakurilyak** [comment]
@makseq I use HyperText for named entity recognition of HTML documents. Importing HTML files as URLs will save data labelers a lot of time. I look forward to seeing this feature request implemented at Label Studio. Thanks in advance!

**Comment by slavakurilyak** [comment]
@makseq Thanks to [html-minifier](https://github.com/kangax/html-minifier), it's possible to minify HTML pages in order to convert HTML to JSON. 🎉

To remove whitespace in HTML files, type:

`$ html-minifier --collapse-whitespace`

To change all attributes double quotes to single quotes, type:

`$ html-minifier --quote-character "'"`

To create a minified HTML page, type:

`$ html-minifier --collapse-whitespace --quote-character "'"`

To convert HTML to JSON, create a script that does the following:

```
{
    "text": "Minified HTML Goes Here"
}
```

**Comment by makseq** [comment]
Hi, @slavakurilyak. I've added html upload to https://github.com/heartexlabs/label-studio/pull/320. Can you test this PR and tell about your experience?

**Comment by slavakurilyak** [comment]
@makseq Thank you for including this amazing feature!

Here is my feedback:

1. I added `htmlmin==0.1.12` to `requirements.txt` to make sure the new dependency on [htmlmin](https://pypi.org/project/htmlmin/) is included.
2. I successfully imported an HTML page ([example](https://www.sec.gov/Archives/edgar/data/1056358/000105635820000038/mtex0331202010-q.htm)). Unfortunately, I was unable to find the associated task on the task list. Here are two screenshots of what I see:

![Kw30Zy](https://user-images.githubusercontent.com/6625584/84807587-51d75380-afbc-11ea-8f0d-23fd5183dfa0.jpg)

![DLABP9](https://user-images.githubusercontent.com/6625584/84807604-57cd3480-afbc-11ea-8aff-c91383ae8675.jpg)

**Comment by makseq** [comment]
@slavakurilyak try to import task again. It's another bug in this PR with import.

**Comment by makseq** [comment]
@slavakurilyak make git pull origin release/0.7.3, try the latest fix of bug above.

**Comment by slavakurilyak** [comment]
@makseq The bug is gone. Thanks!
