### ISSUE TITLE
It is not possible to delete the relation (RE and NER annotation)

### ISSUE THREAD

**Issue by aliceinland** [heartexlabs/label-studio#2880]
**Describe the bug**
When trying to delete the relationship, the bin button does not work.

**To Reproduce**
1. Open a NER and RE project
1. Insert the first entity
2. Insert the second entity
3. Create a relation between the two entities
4. Press the bin button to delete the relationship

**Expected behaviour**
When pressing the bin button, I expect to see the relation disappear because it has been deleted. When I try to remove it, I receive no response. 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version [1.5.0]

**Comment by makseq** [comment]
@aliceinland Just checked it 
![image](https://user-images.githubusercontent.com/501780/187556815-eac9d108-25ad-46e4-9029-ff87cad1d687.png)
and it works well. 

Could you please create a video?

**Comment by makseq** [comment]
Closed as unanswered.
