### ISSUE TITLE
Exported classes are not following the same order as they are defined

### ISSUE THREAD

**Issue by olokos** [heartexlabs/label-studio#2886]
**Describe the bug**
My classes are defined with
```
number_plate
0
1
...
```
but when I export as YOLO they are exported as 
```
0
1
...
number_plate
```
**To Reproduce**
1. Create any project
2. Add classes with custom name first and then numbers
3. Export as yolo
4. See the problem

**Expected behavior**
The classes should be exported in the same order as defined in `Labeling interface` and follow the same order as defined when exporting.

**Screenshots**
![image](https://user-images.githubusercontent.com/1755581/187753161-a70b27c7-3465-476e-bd85-884e2756f08f.png)
![image](https://user-images.githubusercontent.com/1755581/187754321-50c0062b-89fe-480e-91d0-27f8fc3e8dac.png)
![image](https://user-images.githubusercontent.com/1755581/187754379-4793b5cc-eabe-4308-b764-8b6d609647af.png)

**Environment (please complete the following information):**
 - OS: Windows 11, python 3.8 latest release, no venv
 - Label Studio 1.5.0post0

**Additional context**
I checked the code template and it shows `number_plate` as object 0, but it's still exported as the last object anyway.
![image](https://user-images.githubusercontent.com/1755581/187755698-e7b5b32c-0a41-4088-b697-2f89579085f0.png)

I need to keep the exact same order as originally defined, not have it forcibly sorted on export.

**Comment by KonstantinKorotaev** [comment]
Hi @olokos 
It's expected behavior by default as labels are being sorted.
You can override this behavior by adding tag category to your labels like that:
`<Label value="number_plate" category="0"/>`

**Comment by makseq** [comment]
Related:
https://github.com/heartexlabs/label-studio/issues/3653
https://github.com/heartexlabs/label-studio/issues/3324
https://github.com/heartexlabs/label-studio/issues/2886
https://github.com/heartexlabs/label-studio/issues/1115
https://github.com/heartexlabs/label-studio/issues/737
