### ISSUE TITLE
HTML Text Classification

### ISSUE THREAD

**Issue by slavakurilyak** [heartexlabs/label-studio#289]
**Is your feature request related to a problem? Please describe.**
Every page on the world wide web (WWW) is an HTML page, which offers the potential to use tags as metadata. Today, data labelers are forced to rely on text when performing text classification.

**Describe the solution you'd like**
As a data labeler, I would like to perform text classification on HTML files, similar to [HTML NER Tagging](https://labelstud.io/templates/html_document.html).

**Describe alternatives you've considered**
I'm assuming that NER models are similar to text classification models

**Additional context**
None

**Comment by niklub** [comment]
Hi, @slavakurilyak !

You can easily do an HTML classification by applying the following config
```xml
<View>
  <Choices name="choice" toName="text">
    <Choice value="Class A"></Choice>
    <Choice value="Class B"></Choice>
  </Choices>
  <HyperText name="text" value="$text"></HyperText>
</View>
```

Do you suggest it should be added to the templates list?

**Comment by slavakurilyak** [comment]
@niklub Yes, please do! 

Tracking clicks and views on [templates](https://labelstud.io/templates) and [playground](https://labelstud.io/playground) will allow the Heartex Labs to better understand the popularity of this template.
