### ISSUE TITLE
Containerization

### ISSUE THREAD

**Issue by davebulaval** [heartexlabs/label-studio#29]
It would be interesting to have a container image of the _app_. This way I would be able to launch a container on a remote desktop and ping the host address.

Something like Docker.

**Comment by JStumpp** [comment]
I can provide a dockerized version, if you are interested.

**Comment by makseq** [comment]
Yes, you may create PR with docker :)

**Comment by shevchenkonik** [comment]
Hello guys! Thank you for your interest!

@davebulaval Yes, we thought about this possibility and expected to implement it in the future versions. But now our current focus is on supporting as many data types as possible in Label Studio.

@JStumpp We are interested in it. If you do PR, we will certainly implement this functionality in the project.

**Comment by davebulaval** [comment]
@JStumpp I cannot help much but I can at least valide the build of the container and if the functionnality work.

**Comment by JStumpp** [comment]
@davebulaval no problem, I am on it. Should be ready tomorrow.

**Comment by JStumpp** [comment]
The dockerization is ready, see the pull request https://github.com/heartexlabs/label-studio/pull/31

Give it a try:
```bash
docker run -p 8200:8200 -t -i amaigmbh/label-studio -c config.json -l ../examples/chatbot_analysis/config.xml -i ../examples/chatbot_analysis/tasks.json -o output
```

or mount a folder with your custom configuration files
```bash
docker run -p 8200:8200 -t -i -v C:\docker\custom:/app/examples/audio_regions amaigmbh/label-studio
```

**Comment by davebulaval** [comment]
First one work well. Second I have a invalid mode error.

**Comment by JStumpp** [comment]
@davebulaval can you post the exact error? Are you running on windows and did you create the path C:\docker\custom with files from an example?

**Comment by shevchenkonik** [comment]
@JStumpp @davebulaval First one works well, yes. But I can't reproduce with this instruction the second one.
```bash
docker run -p 8200:8200 -t -i -v C:\docker\custom:/app/examples/audio_regions amaigmbh/label-studio
```
Could u expand the instruction? When I started LS using an example from the local path, Docker did not find the config outside directory. And the LS starts with default config `audio_regions`

My version (_my environment is macOS_):
```bash
docker run -p 8200:8200 -t -i -v /Users/shevchenkonik/named_entity:/app/examples/named_entity amaigmbh/label-studio
```
