### ISSUE TITLE
Pinning the labels area

### ISSUE THREAD

**Issue by prakhar21** [heartexlabs/label-studio#2903]
Hello, I was wondering if there is any provision in the Label studio community edition to pin or have a floating labels area? It gets really difficult to go top-down to select the labels when labeling long documents.

Thanks

**Comment by makseq** [comment]
@prakhar21 please check (this labeling config)[https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CView%20style%3D%22padding%3A%200%201em%3B%20margin%3A%201em%200%3B%20background%3A%20%23f1f1f1%3B%20position%3A%20sticky%3B%20top%3A%200%3B%20border-radius%3A%203px%3B%20z-index%3A%20100%22%3E%3Cbr%3E%20%20%20%20%3CLabels%20name%3D%22label%22%20toName%3D%22text%22%20showInline%3D%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%3CLabel%20value%3D%22Person%22%20%2F%3E%3Cbr%3E%20%20%20%20%20%20%3CLabel%20value%3D%22Organization%22%20%2F%3E%3Cbr%3E%20%20%20%20%3C%2FLabels%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%20%20%3CView%3E%3Cbr%3E%20%20%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%20%2F%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E]
