### ISSUE TITLE
crash error 500 when uploading a zip of PNGs

### ISSUE THREAD

**Issue by EMCP** [heartexlabs/label-studio#292]
**Describe the bug**
I begin to attempt to upload a zip of PNG files into the tool, and get a crash 500 error

**To Reproduce**
1. Start the project, set Object Detection config
2. Click on Import 
3. Click and drag a .zip file made on MacOS with 160 PNGS in it

**Expected behavior**
It should upload the files and let me start tagging them

**Screenshots**

![image](https://user-images.githubusercontent.com/3691722/81860076-80e64980-9566-11ea-88fc-1ba00e130445.png)

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version master as of todays date

**Additional context**

**Comment by niklub** [comment]
Hi, @EMCP ! Unfortunately, this import format is not supported yet. Check available options here https://labelstud.io/guide/tasks.html#Import-formats
Specifically, if you want to import images from directory, create labeling project by using
```
label-studio start --init --input-path /path/to/image/dir --input-format image-dir
```
