### ISSUE TITLE
Total annotation count stuck at 1

### ISSUE THREAD

**Issue by jaioneB** [heartexlabs/label-studio#2922]
**Describe the bug**
When annotating more than one series, the total annotation count is still 1. 

**To Reproduce**
1. I create a new project. In my case, the question-answer template. 
2. I annotate multiple spans in a task. 
3. The total annotation count is still 1. 

**Expected behavior**
It should update so that all annotation instances are counted here. 

**Screenshots**
![image](https://user-images.githubusercontent.com/90573989/189594570-938fba37-5972-45cd-9358-2179bcc68cc1.png)

**Environment:**
 - OS: Ubuntu 20.04
 - Label Studio Version: 1.5.0

**Additional info**
This is the code of the template Label Studio offers:

` \<View>
  \<Header value="Please read the passage"/>
  \<Text name="text" value="$text" granularity="word"/>
  \<Header value="Select a text span answering the following question:"/>
  \<Text name="question" value="$question"/>

  \<Labels name="answer" toName="text">
    
  \<Label value="What do they eat?" background="#FFA39E"/><Label value="What?" background="#73d216"/></Labels>

\</View>
\`

**Comment by makseq** [comment]
@jaioneB This counter shows how many annotations you performed, not spans. 
![image](https://user-images.githubusercontent.com/501780/189790820-d5db12c2-d6a1-46fc-b9b5-7dec336aa950.png)
