### ISSUE TITLE
Data Snapshot Exporter task finished filter error

### ISSUE THREAD

**Issue by drreddy** [heartexlabs/label-studio#2926]
**Describe the bug**
When I want to create a snapshot to export project data, if the param finished for task_filter_options is given the export is failing with error `django.core.exceptions.FieldError: Cannot resolve keyword 'is_labled' into field. Choices are: annotations, cancelled_annotations, created_at, data, drafts, file_upload, file_upload_id, id, inner_id, io_storages_azureblobimportstoragelink, io_storages_gcsimportstoragelink, io_storages_localfilesimportstoragelink, io_storages_redisimportstoragelink, io_storages_s3importstoragelink, is_labeled, locks, meta, overlap, predictions, project, project_id, total_annotations, total_predictions, updated_at, updated_by, updated_by_id`. On checking the code it looks like the place where the tasks are filtered the name of the column seemed to be misspelled.

**To Reproduce**
1. Create a sample project.
2. Hit the rest endpoint for snapshot export with the payload `{"task_filter_options": {"finished": "only"}}`.
3. The above error would be present in the log and the export task would have failed.

**Expected behavior**
The export should go through without failure.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS 
 - Label Studio Version: 1.5.0

**Additional context**
I checked the code the problem seems to the be in the mixin.py file in the data_export module ([code_line](https://github.com/heartexlabs/label-studio/blob/8c657fce5928886f9da025ef271c96ececa6bbf4/label_studio/data_export/mixins.py#L78)) where the column name seems to be misspelled.

**Comment by drreddy** [comment]
Sorry, This is my first issue let me know if I need to add any more info, also I could raise a PR fixing the column name in the above mentioned file.

**Comment by makseq** [comment]
@drreddy thank you for your findings! 
There is a fix: https://github.com/heartexlabs/label-studio/pull/2929
Could you please check if it works?

**Comment by drreddy** [comment]
I've verified the above fix it works.
