### ISSUE TITLE
Remove HTML File Size Requirements

### ISSUE THREAD

**Issue by slavakurilyak** [heartexlabs/label-studio#293]
**Describe the bug**
When uploading an HTML file larger than 1 MB, I receive a server error 413 "Request Entity Too Large".

**To Reproduce**
1. Go to 'import' via [LabelStudio Web App](https://app.labelstud.io/import)
2. Drag and drop an HTML file (example [here](https://www.sec.gov/ix?doc=/Archives/edgar/data/1800/000110465920053384/abt-20200331x10q.htm))
3. See server error

**Expected behavior**
When I upload an HTML file of any file size, I expect Label Studio to work

**Screenshots**
![screen](https://user-images.githubusercontent.com/6625584/81883727-d3197180-954a-11ea-8db0-cffed6700058.jpg)

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.4 (19E287)
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

**Additional context**
None

**Comment by makseq** [comment]
Hi, @slavakurilyak, can you try it now? We have changed upload file size to 50mb.

**Comment by slavakurilyak** [comment]
@makseq Thanks!
