### ISSUE TITLE
Import CSV to do NER labeling,but can not get correct value.

### ISSUE THREAD

**Issue by hantongyou** [heartexlabs/label-studio#2933]
**Describe the bug**

**To Reproduce**
1. Import A csv file with headers, it seems like this:
![image](https://user-images.githubusercontent.com/46136463/189954441-ed994719-6588-479c-ba4e-2973e933464c.png)

2. Then I did the setup for NER task:
The configuration is :
```xml
<View>
  <Labels name="label" toName="text">
    
    
    
    
  <Label value="设备" background="#FFA39E"/>
    <Label value="故障" background="#D4380D"/>
    <Label value="现象" background="#FFC069"/>
    <Label value="不相关" background="#AD8B00"/>
  </Labels>

  <Text name="text" value="$技术支持故障描述"/>

</View>
```
3. It supposed to work, but when I get into labeling, there was nothing else but the $column name in the label interface.
![image](https://user-images.githubusercontent.com/46136463/189955447-e831289c-5bf3-4009-a2f4-ea7aba545590.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Label Studio Version latest

**Additional context**

**Comment by makseq** [comment]
I am not sure it's allowed to use non-latin characters in value="..." and other system attributes.
