### ISSUE TITLE
Url links do not work as expected

### ISSUE THREAD

**Issue by henrykironde** [heartexlabs/label-studio#2939]
Links in the file https://github.com/heartexlabs/label-studio/blob/develop/docs/source/guide/tasks.md, starting from the header,  **Add the file directory as source storage in the Label Studio UI**, do not seem top work.

Examples:
See [Run Label Studio on Docker and use local storage](url)

See the [API documentation for importing tasks](https).

**Comment by makseq** [comment]
Documentation is here 
https://labelstud.io/guide/tasks.html#Add-the-file-directory-as-source-storage-in-the-Label-Studio-UI

The files you are seeing is not compiled pages of the documentation.
