### ISSUE TITLE
Could not find "default_configs" error when create ML backend

### ISSUE THREAD

**Issue by lamthuy** [heartexlabs/label-studio#294]
Hi I got this issue when trying to create an example ML back-end
`
OSError: Could not find "default_configs" at package "/Users/lt/opt/anaconda3/lib/python3.7/site-packages/label_studio"
`

I followed the tutorial to create ML backend:
`
label-studio-ml init my_ml_backend --script label-studio/ml/examples/simple_text_classifier.py
`
Do you have any idea?

**Comment by niklub** [comment]
Hi, could you please tell how did you install label studio within anaconda env ?

**Comment by lamthuy** [comment]
Hi Niklub, 
Thank you for your response! had anaconda (3, python 3.7 on MAC OS) in my machine before I started install label-studio.
I used:
`
pip install label-studio
`
To install label-studio.

**Comment by lamthuy** [comment]
It seems that when I install from source code it works. There should be issue with pip instalation when anaconda is present

**Comment by niklub** [comment]
Ok, we gonna check anaconda installation soon. Thanks reporting this issue!
