### ISSUE TITLE
Issue importing YOLO to Label-Studio

### ISSUE THREAD

**Issue by Sodek93** [heartexlabs/label-studio#2945]
I am trying to convert my coco labels to make them importable into label-studio.
Currently i have the problem, that my images path after importing to Label-Studio are broken so the annotations (generated with label-studio-converter import yolo -i -o --image-dir) don't find the correct images in my LS-Project. The Images get this Path:"image": "/data/upload/39/a3cc06f3-000001.jpg"
and are imported from: /home/dedudel/projects/ki_blenderproc/ProjectReforged/AutomaticGeneratedData/foldername

![ls_1](https://user-images.githubusercontent.com/76853252/190348359-71991f29-804c-4164-9b78-a4bea6850e6d.png)

When adding a local source storage to LS-project i get the error: 

Validation error

    [ErrorDetail(string='Path /home/dedudel/projects/ki_blenderproc/ProjectReforged/ does not exist', code='invalid')]

Version: 1.4
I also added the Path to venv as described in: https://labelstud.io/guide/start.html#Set-environment-variables
![ls_2](https://user-images.githubusercontent.com/76853252/190355270-59af21c3-172a-4ddf-b5be-10174c232eac.png)

The Issue persists.

Any ideas how to fix this?

**Comment by makseq** [comment]
It seems you are trying to import images using GUI - "The Images get this Path:"image": "/data/upload/39/a3cc06f3-000001.jpg"".
When you use Local Storage, you don't need to import images manually. 

Please check this video about how to use Local Storage - https://www.youtube.com/watch?v=lo6ncQajbdU
It's advanced, but you will see how to setup its basic.

**Comment by Sodek93** [comment]
> It seems you are trying to import images using GUI - "The Images get this Path:"image": "/data/upload/39/a3cc06f3-000001.jpg"". When you use Local Storage, you don't need to import images manually.
> 
> Please check this video about how to use Local Storage - https://www.youtube.com/watch?v=lo6ncQajbdU It's advanced, but you will see how to setup its basic.

I have it running on a server so LocalStorage from my device won't work - my bad.

**Comment by makseq** [comment]
@Sodek93 you can try to use s3/gcs storages.

**Comment by Sodek93** [comment]
Thank you for your support @makseq !

I am using a local running label-studio instance now.

I can indeed import pictures and annotations but when i look on the pictures the annotations have no class assigned. So all i see are the Annotation-Boxes as a white box with no class and color.

I check a different Project where the annotations work fine and the annotations have the exact same style as in the working project - also i checked the Annotation Config and it looks good too.

Do you have any idea why i might have this issue?

**Comment by Sodek93** [comment]
I found the place where the issue happens:
When importing the Label-Studio Labels i generated from my Yolov5 Labels with label-studio-converter i found thatthe rectanglelabels key+value is missing. When maunally assigning the class of the box i can see in the picture the key rectanglelabels got added (e.g. "rectanglelabels": ["bowl"])
```
{
  "id": 138,
  "data": {
    "image": "data/local-files/?d=AutomaticGeneratedData/2022-09-12_11_05_42_LS/images/000024.jpg"
  },
  "annotations": [
    {
      "id": 3,
      "created_username": " arne.dudel@miele.com, 1",
      "created_ago": "23 hours, 47 minutes",
      "result": [
        {
          "original_width": 960,
          "original_height": 1280,
          "image_rotation": 0,
          "value": {
            "x": 4.270799999999998,
            "y": 41.5625,
            "width": 95.7292,
            "height": 5,
            "rotation": 0
          },
          "id": "5f558cd22f",
          "from_name": "label_rectangles",
          "to_name": "image",
          "type": "rectanglelabels",
          "origin": "manual"
        },
        {
          "original_width": 960,
          "original_height": 1280,
          "image_rotation": 0,
          "value": {
            "x": 11.979149999999999,
            "y": 83.9062,
            "width": 81.4583,
            "height": 11.25,
            "rotation": 0
          },
          "id": "9807bb95d3",
          "from_name": "label_rectangles",
          "to_name": "image",
          "type": "rectanglelabels",
          "origin": "manual"
        },
        {
          "original_width": 960,
          "original_height": 1280,
          "image_rotation": 0,
          "value": {
            "x": 0.00005000000000143778,
            "y": 0,
            "width": 30.208299999999998,
            "height": 33.5938,
            "rotation": 0,
            **_"rectanglelabels": [
              "bowl"
            ]_**
          },
          "id": "8974a890d7",
          "from_name": "label_rectangles",
          "to_name": "image",
          "type": "rectanglelabels",
          "origin": "manual"
        }
      ],
```

How can i fix this issue?
