### ISSUE TITLE
Can the platform support ipad labeling?

### ISSUE THREAD

**Issue by yuminzhe** [heartexlabs/label-studio#2949]
It's inconvenient when I use the mouse to annotate semantic segmentation items, so I want to try annotating on the iPad with the iPad Pencil. At that time, the ipad could only open the start interface and could not load it into a specific project.So I hope that label-studio can support ipad for labeling to adapt to complex labeling such as semantic segmentation projects.

**Comment by makseq** [comment]
@yuminzhe Partially it supports mobile device labeling, but it highly depends on labeling type (brush, bbox, polygon, etc).
