### ISSUE TITLE
Text classification using `<Labels>` tag not exporting multiple annotations when `choice="multiple"` (but `<Choices>` does)

### ISSUE THREAD

**Issue by averdones** [heartexlabs/label-studio#2954]
**Describe the bug**
When doing Text Classification with multiple options using the tags `<Labels>` and `<Label>`, the exported annotations file doesn't show the annotated labels.

However, when I use the tags `<Choices>` and `<Choice>`, the annotated choices are correctly exported.

I am trying to use `Labels` instead of `Choices` because it looks better and also because options are filtered when used along with the tag `<Filter>`.

Am I using the `Labels` tag in an unsupported way?

**To Reproduce**
1. Create a new project
2. In the section Data Import, import a simple CSV file that looks like this:

```
text
this is an some text
this is more text
third text
```

3. In the section Labeling Setup, use this XML file:

```python
<View>
  <Text name="text" value="$text"/>
  <View style="box-shadow: 2px 2px 5px #999;                padding: 20px; margin-top: 2em;                border-radius: 5px;">
    <Header value="Choose text sentiment"/>
    <Labels name="sentiment" toName="text" choice="multiple" showInLine="true">
      <Label value="Positive"/>
      <Label value="Negative"/>
      <Label value="Neutral"/>
    </Labels>
  </View>
</View>
```

This is the same as the default template but changing Choices and Choice for Labels and Label, and adding the option `choice="multiple"`

4. Annotate one example
5. Export annotations as CSV
6. The exported CSV file doesn't have the annotations (when using Choices tag, the CSV file would correctly have a column named `sentiment`)

**Expected behavior**
The exported CSV file should have the multiple annotations.

**Environment:**
 - OS: Windows 10
 - Label Studio Version 1.5.0

**Comment by makseq** [comment]
Please use JSON format, CSV is not yet supported here.

**Comment by averdones** [comment]
The JSON format doesn't work either. The `result` field inside `annotations` is empty when using **\<Labels\>**:

```json
"result":
[]
```

However, when using **\<Choices\>**, the `result` field works as expected:

```json
"result":
[
    {
        "value":
        {
            "choices":
            [
                "Degenerative disc disease",
                "Gout",
                "Hemophilia"
            ]
        },
        "id": "X-2Uk9VPVe",
        "from_name": "impression",
        "to_name": "text",
        "type": "choices",
        "origin": "manual"
    }
]
```

After debugging this, I found that the issue is in the frontend: when clicking on Submit, the http response doesn't return anything inside `result`. I have tried to fix this but I am not familiar with React.

Is this a functionality expected to be working for my use case?

**Comment by makseq** [comment]
Sorry for the delay, I've just checked it with LS 1.6, it works well there.
https://youtu.be/ZQholb1Xz5o

**Comment by averdones** [comment]
Thank you for taking the time to record the video.

I can replicate your behavior. However, my use case is different: I would like to do text classification (not NER) where I just click on the label and click Submit. It seems that with the <Labels> tag, it is necessary to also click somewhere on the text to make results appear.

It would be very nice to have this feature in <Labels> because it is more visually pleasing than <Choices>, but also the <Filter> works. But I will stick to <Choices> for now.

**Comment by makseq** [comment]
@averdones could you please record a video? It will be easier to discuss with the team when there is a video.

**Comment by averdones** [comment]
Here is a video where first I show the desired behavior that doesn't work (`result` is empty). And after, I show how to make `result` return something, but with an undesired behavior (it basically replicates the actions in your video):

[https://youtu.be/oJxQ2nXfpQc](https://youtu.be/oJxQ2nXfpQc)

Ideally, I would like the first way to work. However, I understand that it might be complicate, since `<Labels>` tag seems to expect an interaction with the input text. But perhaps there is a way for `<Labels>` to mimic `<Choices>`'s behavior.

**Comment by hlomzik** [comment]
Hi, @averdones!
You want to use classification, so we have tag specifically created for this — `Choices` :)
`Labels` are absolutelly different tag, so no reason to touch them here.
Your concerns is about filtering and look:
1. `Filter` should work with `Choices` also, that's a known bug, we'll fix it soon. Also you can try to use `Taxonomy` as a temporary workaround.
2. Look can be changed by styling, just add `Style` tag and play around with class names:
   
    ```
    <Style>
    .ant-checkbox-wrapper .ant-checkbox { display: none }
    .ant-checkbox-wrapper-checked {
      outline: 1px solid grey;
    }
    </Style>
    ```
