### ISSUE TITLE
Impossible to join via slack invite : Website + app

### ISSUE THREAD

**Issue by maximeB42** [heartexlabs/label-studio#2962]
**Describe the bug**
The links for the slack invites in both the website and the app are not effective anymore

**To Reproduce**
1 - Click on the slack invite at https://labelstud.io/
2 - Click the slack invite link in the label studio app

**Expected behaviour**
Join the slack of Label studio

**Screenshots**
<img width="828" alt="image" src="https://user-images.githubusercontent.com/109660876/191211987-8844b89b-dd96-4f08-bbe5-8a851e14119a.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Web Browser: ChromeOS
 - Label Studio Version [e.g. 1.5.0]

**Additional context**
I would love to contribute and share with the member of this project

**Comment by makseq** [comment]
Hi, thank you for your attention, this was fixed rather quickly.
