### ISSUE TITLE
Problem with saving cyrrilic symbols

### ISSUE THREAD

**Issue by 32r81b** [heartexlabs/label-studio#297]
Hi, peolple. Thans for your great tool.

I'm trying to use label-studio, but I faced problem with saving cyrrilic symbols. For exampl I type all cyrrilic symbols within TextArea and they looks greate:

![image](https://user-images.githubusercontent.com/8361949/82245863-8c21e680-9965-11ea-901c-58ebaddc28c3.png)

But when I perform export to JSON_MIN I see that all CAPSED symbols corupted. And symbol 'я' was saved as '¤'. 

"йцукенгшщзхъэждлорпавыф¤чсмитьбю ёЅ№“»ћ—„яЁ∆ƒЋќ–ѕј¬џ‘…÷” ≈Ќ√Ўў«’"

![image](https://user-images.githubusercontent.com/8361949/82246400-6e08b600-9966-11ea-81e7-b4f9d4e6da05.png)

I use windows 10. How I can fix this problem?

**Comment by 32r81b** [comment]
My config file:

<View>

  <Labels name="labels" toName="audio">

    <Label selected="true" value="Клиент" />

    <Label value="Менеджер" />

  </Labels>

  <AudioPlus name="audio" value="$audio"/>

  <View visibleWhen="region-selected">

    <Header value="Введите текст выделенной фразы" />

  </View>

  <TextArea name="transcription" toName="audio"

            rows="2" editable="true"

            perRegion="true" required="true" />

</View>

**Comment by niklub** [comment]
Hi, Ruslan, thanks for reporting the issue. Could you please tell which Label Studio version do you use? I can't reproduce from the latest 0.6.1 however haven't checked it under Windows.

**Comment by 32r81b** [comment]
I install my version last week.  pip freeze shows:

`ppdirs==1.4.3
attrs==19.1.0
blis==0.4.1
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cymem==2.0.3
Flask==1.1.1
Flask-API==2.0
idna==2.8
importlib-metadata==1.6.0
itsdangerous==1.1.0
Jinja2==2.10.3
jsonschema==3.2.0
**label-studio==0.6.0
label-studio-converter==0.0.16**
lxml==4.5.0
MarkupSafe==1.1.1
mixpanel==4.4.0
numpy==1.17.4
orjson==3.0.0
pandas==1.0.3
Pillow==6.2.1
pyrsistent==0.16.0
python-dateutil==2.8.1
pytz==2019.3
rarfile==3.1
redis==3.5.2
requests==2.22.0
rq==1.0
six==1.12.0
srsly==0.2.0
tqdm==4.40.2
urllib3==1.25.7
wasabi==0.4.2
Werkzeug==0.16.0
xmljson==0.2.0
zipp==3.1.0
`
I use russian version of windows 10.

**Comment by 32r81b** [comment]
I have instaled label-studio on linux docker container and now all save without errors. I think errors happend because I use russian localisation WIndows.

**Comment by makseq** [comment]
Hi, @32r81b. 

If you have time try this PR for Label Studio please: 
https://github.com/heartexlabs/label-studio/pull/300

and this for label-studio-converter:
https://github.com/heartexlabs/label-studio-converter/pull/5
