### ISSUE TITLE
The database reports an error when marking the MySQL database data

### ISSUE THREAD

**Issue by xuhuasong** [heartexlabs/label-studio#3009]
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DISTINCT `task_completion`.`result` ) AS `annotations_results`, ARRAY_AGG(DISTIN' at line 1")

**Comment by makseq** [comment]
LS doesn't support mysql officially. However you can try to rewrite/remove all array_agg calls here:
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/data_manager/managers.py
