### ISSUE TITLE
Speaker Segmentation timeline play **Delay**

### ISSUE THREAD

**Issue by moroclash** [heartexlabs/label-studio#3010]
In speaker segmentation, in the timeline of record, it works the first time perfectly. Still, when moving the cursor back and pressing play again, there is a delay happening, the voice itself starts to appear after the position it had to appear in, and each time moving back the cursor, the delay increase.

the person has to start talking here,
<img width="712" alt="Screen Shot 2022-09-27 at 1 58 04 PM" src="https://user-images.githubusercontent.com/17504739/192519185-32ec5244-5427-4fcd-88ca-4f0fccda3831.png">

but after moving back to start from the previous point, it starts talking from here
<img width="712" alt="Screen Shot 2022-09-27 at 1 59 18 PM" src="https://user-images.githubusercontent.com/17504739/192519423-bdfe7585-d82a-4230-911b-d7a28eba78e4.png">

**Comment by CrisRodriguez** [comment]
Hello,

I experienced the same issue but mostly when audios are long (more than 20 minutes), for MP3 stereo audios at 8KHz (bitrate < 64kbits) In label studio version 1.5.0.

Thanks,

Cristian

**Comment by makseq** [comment]
@CrisRodriguez you can try LS 1.7.0, we released a new audio engine there, it should work better with long duration files.

**Comment by CrisRodriguez** [comment]
> @CrisRodriguez you can try LS 1.7.0, we released a new audio engine there, it should work better with long duration files.


Hello @makseq 

Thanks for your answer. I've switched to this version and it is far more stable, thanks for the sugesstion.

However, for Stereo MP3 audios I cannot see both channels waveforms as in version 1.5.0. is there anyway to enable it ? I cannot find this info in the doc.

![image](https://user-images.githubusercontent.com/28490239/215057855-e1898735-530a-4ccc-b16e-cecfeb7048ba.png)


Thanks,

Cristian

P.S. Waveform (I confirm I can listen each channel through Left/Rigth speaker, then the loaded audio is stereo) : 
![image](https://user-images.githubusercontent.com/28490239/215045841-8e6c1ad8-9174-4a3a-a5e6-a354f1111943.png)

**Comment by makseq** [comment]
@CrisRodriguez yes, we are working on stereo waveforms, it's pretty popular request.

**Comment by CrisRodriguez** [comment]
> @CrisRodriguez yes, we are working on stereo waveforms, it's pretty popular request.

Thanks !
