### ISSUE TITLE
Endless exporting

### ISSUE THREAD

**Issue by ScouTy747** [heartexlabs/label-studio#3024]
**Describe the bug**
Export project to COCO format. Endless (i waited 24 hours) exporting without downloading.

**To Reproduce**
1. Go to project
2. Click on Export, chose COCO format
3. Click on Export button.
4. I don't see any error

**Expected behavior**
I wanted to download the COCO format from the project.

**Screenshots**
![image](https://user-images.githubusercontent.com/73474180/192773478-4906f6e9-083c-4879-9cdb-3fd08aa899bf.png)
![image](https://user-images.githubusercontent.com/73474180/192773394-e59b3cc4-a1ee-431b-b1a2-2f4dd26c7a5c.png)

**Environment (please complete the following information):**
 - OS: Win10
 - Label Studio Version [1.6.0]

**Additional context**
As long as I didn't use the labels to the images, I could export the COCO format....

Thank you guys for reply ! :)

**Comment by makseq** [comment]
Please try to use this command:
https://labelstud.io/guide/export.html#Export-using-console-command
"Export using console command"
