### ISSUE TITLE
NER tagging: In v0.6.1, the highlighting text is different from the completion text in region.

### ISSUE THREAD

**Issue by L-seven7** [heartexlabs/label-studio#304]
**Describe the bug**
When I label the nested NER, the highlighting text is different from
 the results text in region. But when I label them separately, they are all right.

**Screenshots**
I label the enhanced salt and enhanced salt tolerance. The results in regions is right, but the highlighting text is different from the results.
<img width="1127" alt="截屏2020-05-30 上午9 51 58" src="https://user-images.githubusercontent.com/28668388/83316884-37cb1080-a25b-11ea-99cc-e53dd42c6c17.png">
When I label them separately, they are all right.
<img width="1138" alt="截屏2020-05-30 上午9 55 52" src="https://user-images.githubusercontent.com/28668388/83316939-c2ac0b00-a25b-11ea-884f-9232f544f812.png">
<img width="1137" alt="截屏2020-05-30 上午9 56 39" src="https://user-images.githubusercontent.com/28668388/83316957-de171600-a25b-11ea-8b35-459a4b844bde.png">

**Comment by makseq** [comment]
@L-seven7 Can you provide your label config, task and completion examples?

**Comment by L-seven7** [comment]
label config:
<View>
  <Labels name="ner" toName="text">
    <Label value="phe" background="red"/>
    <Label value="ge" background="darkorange"/>
  </Labels>
  <TextArea name="comments" toName="text" editable="true" placeholder="Add comments"></TextArea>
  <Text name="text" value="$text"/>
</View>

task and completion:
[task&completion.zip](https://github.com/heartexlabs/label-studio/files/4711244/task.completion.zip)

**Comment by L-seven7** [comment]
@makseq Thank you for your prompt reply. This is the examples.
[label&task&completion.zip](https://github.com/heartexlabs/label-studio/files/4711268/label.task.completion.zip)

**Comment by makseq** [comment]
Can you check this bug in the latest LS version 0.7.0? We can't reproduce it..

**Comment by L-seven7** [comment]
@makseq This bug still exists in the latest LS version 0.7.0
<img width="1146" alt="截屏2020-06-02 下午6 07 24" src="https://user-images.githubusercontent.com/28668388/83508015-ec835d00-a4fb-11ea-9217-19de8b7dd0fd.png">

**Comment by makseq** [comment]
Thank you. We will inspect it. 
@hlomzik

**Comment by hlomzik** [comment]
Thank you for a good capture! We've fixed this bug and testing it right now. It will go inside 0.7.1 release soon. You can check frontend part right now if you are curious [#label-studio-frontend/102](https://github.com/heartexlabs/label-studio-frontend/pull/102). But your case works well in there.

**Comment by hlomzik** [comment]
@L-seven7 
Version 0.7.1 just released and this bug was fixed along with other sad bugs with text labelling. Thanks for reporting!
