### ISSUE TITLE
JSONDecode Error on Empty file

### ISSUE THREAD

**Issue by hsethi2709** [heartexlabs/label-studio#305]
**Describe the bug**
If there is an empty completion file where there is no labelling and you happen to restart the docker container, the project is not loaded even on using --force flag as it throws JSONDecodeError Error on an empty file.
 
**To Reproduce**
1. Submit an empty file without labelling
2. Restart the docker container
3. The project fails to load due to JSONDecodeError on the empty file

**Expected behavior**
It should skip the empty file without trying to read it in JSON and load the existing project. 

**Environment (please complete the following information):**
 - Ubuntu

I am happy to fix this bug and create a pull request.

**Comment by makseq** [comment]
@hsethi2709 Hi! We are happy to take a look at your fix :wink:

**Comment by hsethi2709** [comment]
Apologies for the late response. I upgraded to the latest version 0.7.0 and this problem seems to have been resolved. Thanks for that! I fixed it in the previous version for my project but it's not required now :) I am closing the issue.
