### ISSUE TITLE
A bug in audio related task

### ISSUE THREAD

**Issue by RenJinan** [heartexlabs/label-studio#306]
**Describe the bug**
In the audio task, when I click the audio waveform, the audio playing pointer does not move to the position of my mouse pointer, resulting in that every time I want to listen to a part in the middle, I always listen from the beginning.

**To Reproduce**
1. Go to 'labeling'
2. Click on waveform
3. See error that the audio playing pointer does not move to the position of my mouse pointer

**Expected behavior**
 the audio playing pointer move to  the position of my mouse pointer.

**Environment:**
 - OS: Windows 10
 - Browser: chrome
 - Version: 0.7.0

**Additional context**
This problem does not exist in the ’interface preview‘ in the ‘Setup’, but it will appear when labeling.

**Comment by makseq** [comment]
@hlomzik

**Comment by hlomzik** [comment]
Hey, @RenJinan! It sounds strange, especially if it works in preview. Could you please provide your config? How long is your audio? And what the error do you see? Screenshots or browser console output would be very helpful.

**Comment by RenJinan** [comment]
Thank you very much for your reply! My configuration file is the same as the official sample, but the problem still exists. I made a GIF to show this problem and look forward to your help.
![example](https://user-images.githubusercontent.com/50946537/83935225-33b66a00-a7ea-11ea-9ed8-5a51168bd23e.gif)


> Hey, @RenJinan! It sounds strange, especially if it works in preview. Could you please provide your config? How long is your audio? And what the error do you see? Screenshots or browser console output would be very helpful.

**Comment by makseq** [comment]
@hlomzik have you any ideas?

**Comment by hlomzik** [comment]
No ideas sadly :(
@renjinan do you have errors in browser console?
I checked this config in LSF, it works well. I'll check in LS soon.

**Comment by makseq** [comment]
@RenJinan have you tried to use AudioPlus tag?

**Comment by makseq** [comment]
I hope it's fixed after 0.7.3 release.
