### ISSUE TITLE
Cannot set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT

### ISSUE THREAD

**Issue by SjoerdBraaksma** [heartexlabs/label-studio#3065]
So I'm trying to set up local file usage, but after installing label-studio I try to set the local files root, but somehow this doesn't work.

Error received is: 'LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT' is not recognized as an internal or external command,
operable program or batch file.

This, while I CAN enable LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true.

The documentation isn't very clear on what needs to be set for using local files, as the documentation for each level of settings (environment variables, JSON formatting, XML project settings) is in different locations.

**Comment by makseq** [comment]
@SjoerdBraaksma are you on windows? if yes, you need to use `set`:
```
set LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=c:\xxx
```

Also check this video:
https://www.youtube.com/watch?v=lo6ncQajbdU&t=2s

**Comment by SjoerdBraaksma** [comment]
This worked! and the video really helped too. Thanks!
