### ISSUE TITLE
Loading a tab that filters on the task id takes 42 seconds.

### ISSUE THREAD

**Issue by csaroff** [heartexlabs/label-studio#3071]
**Describe the bug**
Loading a tab that filters on the task id takes 42 seconds.

`/api/tasks?page=1&page_size=30&view=513&project=8`

![image](https://user-images.githubusercontent.com/7225723/195010179-08096e26-6ba7-46d7-97fb-15a87bac0c98.png)

![image](https://user-images.githubusercontent.com/7225723/195010222-40cb9140-ec7b-4bcd-8d72-2eb669f46b79.png)

**Environment (please complete the following information):**
 - Docker container running in kubernetes
 - Label Studio Version 1.6.0
 - GCP managed postgresql 13.7

Idk if this is helpful, but I checked GCP query insights and it appears that this single api call is responsible for 30 different queries, each which take ~1 second.

20 that looks like this:

```sql
SELECT
  "task"."id",
  "task"."data",
  "task"."meta",
  "task"."project_id",
  "task"."created_at",
  "task"."updated_at",
  "task"."updated_by_id",
  "task"."is_labeled",
  "task"."overlap",
  "task"."file_upload_id",
  "task"."inner_id",
  "task"."total_annotations",
  "task"."cancelled_annotations",
  "task"."total_predictions",
  "task"."comment_count",
  "task"."unresolved_comment_count",
  "task"."last_comment_updated_at"
FROM
  "task"
WHERE
  "task"."project_id" = $1
ORDER BY
  "task"."updated_at" DESC
```

and 10 that look like this:

```sql
SELECT
  "task"."id",
  "task"."data",
  "task"."meta",
  "task"."project_id",
  "task"."created_at",
  "task"."updated_at",
  "task"."updated_by_id",
  "task"."is_labeled",
  "task"."overlap",
  "task"."file_upload_id",
  "task"."inner_id",
  "task"."total_annotations",
  "task"."cancelled_annotations",
  "task"."total_predictions",
  "task"."comment_count",
  "task"."unresolved_comment_count",
  "task"."last_comment_updated_at"
FROM
  "task"
INNER JOIN
  "task_completion"
ON
  ("task"."id" = "task_completion"."task_id")
WHERE
  ("task"."project_id" = $1
    AND "task_completion"."id" IS NOT NULL)
ORDER BY
  "task"."updated_at" DESC
```

I'm not sure why it queries for all tasks 30 times, but that seems like a major cause of the cause of the slowness.

**Comment by csaroff** [comment]
Yeah, we have the same behavior in other projects. 

We're using gcs for storage(and have multiple storages configured for each project.)

Here are the columns shown:

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/7225723/195475864-6fd6847f-a29d-4e41-9f66-e79f20a62af9.png">
<img width="207" alt="image" src="https://user-images.githubusercontent.com/7225723/195475898-8bd68131-45ac-4735-b267-49b3dc409222.png">
<img width="208" alt="image" src="https://user-images.githubusercontent.com/7225723/195475928-edbe5738-5b88-47d8-8b73-1637c384f2da.png">

I don't feel like we've really done much out of the ordinary. Let me know if you need any other info

**Comment by makseq** [comment]
1. What filter do you use?
2. How many tasks do you have in the project? 
3. If you remove storages, will it work faster?

**Comment by csaroff** [comment]
So it turns out that I hadn't specified a specific RAM allocation when deploying labelstudio to kubernetes. After adjusting the RAM allocations, things are much snapper.

Sorry for the noise. Closing
