### ISSUE TITLE
Fail to load huge image for labeling

### ISSUE THREAD

**Issue by zhaoyukoon** [heartexlabs/label-studio#3072]
I try to create a label task for image segmentation. An image with size of 200M is imported successfuly. However, when i try to start labeling, I got following error:
![45BE90E6-BE6F-4406-9CB9-967D852CD6DB](https://user-images.githubusercontent.com/64603707/195040832-ecb6b7ed-3b06-471c-b0fb-c890f0e174b5.png)

The error repeates under different format (tiff, jpg) and browsers(Chrome, EDGE)

**Comment by makseq** [comment]
This huge images (and tiff) are not supported by browsers.

**Comment by zhaoyukoon** [comment]
can label-sudio integrate with omero, which can display huge image on browser

**Comment by makseq** [comment]
@zhaoyukoon no, LS doesn't support this.
