### ISSUE TITLE
How do I link a new app

### ISSUE THREAD

**Issue by bunyaminbingol** [heartexlabs/label-studio#3077]
hello, I installed label-studio on my own computer and created a new application in it 
`python manage.py startapp MyApp`
How do I link this application in core/"urls.py". I want to make this link and create it as `http://127.0.0.1:8080/MyApp` and design this page specially, how do I do this.

how do i create this url link, error comes out as shown below

![image](https://user-images.githubusercontent.com/73272512/195151957-bc605e28-c82c-4009-a6d8-2cc1126eca56.png)

**Comment by makseq** [comment]
You have to add it here:
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/core/urls.py#L66

As an example you can use the User Account page:
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/users/urls.py#L21

Also check django docs:
https://docs.djangoproject.com/en/4.1/intro/tutorial01/
