### ISSUE TITLE
How disable text processing?

### ISSUE THREAD

**Issue by AlekseySh** [heartexlabs/label-studio#308]
All my links in the format <http.somesite.com> from the source file disappeared in the labelling interface. Is it possible to turning of such behaviour?

**Comment by makseq** [comment]
Can you show screenshot, label config and json task example?

**Comment by deppp** [comment]
Fixed in the latest release and was confirmed by @AlekseySh in the Slack channel. Thanks for reporting, and all the other excellent feedback!
