### ISSUE TITLE
Label studio crashing again and again. Runtime error

### ISSUE THREAD

**Issue by mehadi92** [heartexlabs/label-studio#3086]
**Describe the bug**
I deploy the label studio using the `Run on Google Cloud` button provided in the readme section of this repository. It successfully installs in the google cloud run. When I try to create a project or add data to a project it gives me the error that I attach as a screenshot. And this error gave me a random way. Sometimes It also automatically logout. Sometimes it's deleting the created project that I created.

By clicking the `Run on Google Cloud` it installs label-studio version `1.6.0rc5`

**Screenshots**
![Screenshot from 2022-10-13 17-40-25](https://user-images.githubusercontent.com/104126711/195587362-d90373e2-4e22-4b46-bd09-2eae3395804a.png)

**Environment (please complete the following information):**
 - Google Cloud Run
 - Label Studio Version `1.6.0rc5`

Is there anything that I'm missing

Thanks

**Comment by Erin-Boehmer** [comment]
Running into the same issue running `heartexlabs/label-studio:1.6.0` on k8s with Postgres running in AWS. 
<img width="1260" alt="Screen Shot 2022-10-24 at 11 49 42 AM" src="https://user-images.githubusercontent.com/3460589/197570100-7402aae9-3a3d-4614-8123-85fcee0744e8.png">
<img width="254" alt="Screen Shot 2022-10-24 at 11 50 12 AM" src="https://user-images.githubusercontent.com/3460589/197570101-3d74229b-2742-432d-8848-a161b02c7a27.png">

**Comment by farioas** [comment]
I was unable to reproduce this issue.

Without logs it's really hard to troubleshoot something.

**Comment by mehadi92** [comment]
@farioas, In  my case, click on `Run on Google Cloud` reproduce this issue
![Screenshot from 2022-10-26 11-13-35](https://user-images.githubusercontent.com/104126711/197940617-7103f2e8-99dd-49f7-b7e0-007f13e0648b.png)

**Comment by farioas** [comment]
After clicking on the link I have working instance
<img width="1616" alt="Screenshot 2022-10-25 at 19 43 43" src="https://user-images.githubusercontent.com/2744993/198106298-ba4959e0-25b6-494b-8b22-e4182ed0d4a7.png">
