### ISSUE TITLE
I can't see the images when using synced local files.

### ISSUE THREAD

**Issue by huihui-v** [heartexlabs/label-studio#3088]
I've deployed the label-studio with docker and created the labeling task. Then I added my data path in as source storage, but no image can be seen in the project. The error code of browser is 404, tells me that the resource is not found. (http://xxx.xxx.xxx.xxx/data/local-files/?d=target/to/image)

![image](https://user-images.githubusercontent.com/22081393/195838335-8f66ddd6-1d21-4ac7-9049-d464aa474a52.png)

What should i do now and thank you for providing such amazing open-source labeling tool.

**Comment by huihui-v** [comment]
![image](https://user-images.githubusercontent.com/22081393/195839386-886a5058-e1bd-4697-b38f-6a11fb5977ae.png)
The LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED is set true, and there're some images from other projects that can be viewed, so I regard this problem as something unrelated to my settings :(

**Comment by makseq** [comment]
It looks like incorrect paths. Please try to check this video tutorial: https://labelstud.io/guide/storage.html#Local-Storage-with-Custom-Task-Format, hope it will help.
