### ISSUE TITLE
Unable to install labelstudio in Windows 10 using docker

### ISSUE THREAD

**Issue by ganesh3** [heartexlabs/label-studio#3090]
**Describe the bug**
As given on github, I ran the command : `docker pull heartexlabs/label-studio:latest` and it worked fine and then running the `docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:latest` leads to the below error:

```
docker: Error response from daemon: create `pwd`/mydata: "`pwd`/mydata" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

**To Reproduce**
1. Go to 'cmd/windows terminal'
2. Run docker pull heartexlabs/label-studio:latest
3. The run docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:latest
4. See error: docker: Error response from daemon: create `pwd`/mydata: "`pwd`/mydata" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.

**Expected behavior**
The docker installation should run smoothly and label studio should be available on localhost

**Screenshots**
None
**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version [e.g. 0.8.0]: 1.6.0 via docker pull

**Additional context**

**Comment by makseq** [comment]
@ganesh3 as I remember windows doesn't know about `pwd` command. You should provide the full absolute paths everywhere instead of using `pwd`.
