### ISSUE TITLE
Accessing image URLs by authentication. 

### ISSUE THREAD

**Issue by rtgunti** [heartexlabs/label-studio#3095]
Hi!

I have configured the Source Cloud Storage with Azure. But I do not want to add all the images from the container to the project.
What's the easiest way to load only selected images from an Azure container?

With the Source cloud storage configuration in place, I tried to import the images using a JSON file with the image URLs. But that failed with an error message, "Can't parse task.data to match URI. Reason: Match is not found."

Thanks!

**Comment by makseq** [comment]
@rtgunti Most likely you used an incorrect scheme name. Azure links should start with azure-blob:
```
azure-blob://aaa/bbb/c.jpg
```

**Comment by rtgunti** [comment]
Thank you @makseq. That was the problem. I changed the starting of URL from `http` to  `azure-blob` and that just worked.
