### ISSUE TITLE
Multiple predictions not showing in 'Label all tasks' view

### ISSUE THREAD

**Issue by harrymander** [heartexlabs/label-studio#3104]
**Describe the bug**

Multiple time series predictions are not shown in the 'Label all tasks' view. Similar to my previous issue (https://github.com/heartexlabs/label-studio/issues/2843); however, I can't view the different annotation candidates in this view as I could by directly clicking on the task in the project view.

(Also, partially related: the time series data I am using is relatively large [~570,000 points], but it loads significantly faster when opened from the 'Label All Tasks' button than when opened directly from the project view.)

**To Reproduce**

1. Upload task
2. Add multiple predictions for a single time series label
3. Open task from the 'Label All Tasks' button
4. Observe that only one of the predictions is visible

Task source:

```json
{
  "id": 315,
  "data": {
    "csv": "/data/local-files/?d=projects/4/24T1TB3.CSV",
    "record_version": "v0.4-0-g0487e5a",
    "original_filename": "24T1TB3.CSV"
  },
  "annotations": [],
  "predictions": [
    {
      "id": 244,
      "model_version": "",
      "created_ago": "1 day",
      "result": [
        {
          "from_name": "ts-labels",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 144266,
            "end": 144591,
            "instant": false,
            "timeserieslabels": [
              "event"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-10-16T21:15:37.279827Z",
      "updated_at": "2022-10-16T21:15:37.279877Z",
      "task": 315
    },
    {
      "id": 245,
      "model_version": "",
      "created_ago": "1 day",
      "result": [
        {
          "from_name": "ts-labels",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 185570,
            "end": 185985,
            "instant": false,
            "timeserieslabels": [
              "event"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-10-16T21:15:37.500085Z",
      "updated_at": "2022-10-16T21:15:37.500165Z",
      "task": 315
    },
    {
      "id": 246,
      "model_version": "",
      "created_ago": "1 day",
      "result": [
        {
          "from_name": "ts-labels",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 225874,
            "end": 226571,
            "instant": false,
            "timeserieslabels": [
              "event"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-10-16T21:15:37.718408Z",
      "updated_at": "2022-10-16T21:15:37.718484Z",
      "task": 315
    },
    {
      "id": 247,
      "model_version": "",
      "created_ago": "1 day",
      "result": [
        {
          "from_name": "ts-labels",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 263310,
            "end": 263722,
            "instant": false,
            "timeserieslabels": [
              "event"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-10-16T21:15:37.877145Z",
      "updated_at": "2022-10-16T21:15:37.877193Z",
      "task": 315
    },
    {
      "id": 248,
      "model_version": "",
      "created_ago": "1 day",
      "result": [
        {
          "from_name": "ts-labels",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 301464,
            "end": 301928,
            "instant": false,
            "timeserieslabels": [
              "event"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-10-16T21:15:38.045502Z",
      "updated_at": "2022-10-16T21:15:38.045588Z",
      "task": 315
    },
    {
      "id": 249,
      "model_version": "",
      "created_ago": "1 day",
      "result": [
        {
          "from_name": "ts-labels",
          "to_name": "ts",
          "type": "timeserieslabels",
          "value": {
            "start": 411806,
            "end": 412371,
            "instant": false,
            "timeserieslabels": [
              "event"
            ]
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-10-16T21:15:38.219173Z",
      "updated_at": "2022-10-16T21:15:38.219260Z",
      "task": 315
    }
  ]
}
```

**Expected behavior**

All the predictions are visible, selectable in the outliner sidebar, or selectable from a dropdown menu as when opened directly from the project view.

**Screenshots**

Label all tasks view:

![image](https://user-images.githubusercontent.com/41089556/196289900-73d4d567-f7af-4e9b-84d9-24bbe7be6371.png)

The same task when opened directly by clicking on it in the projects view, showing multiple predictions as annotation candidates:

![image](https://user-images.githubusercontent.com/41089556/196290585-d66edd30-e115-420c-8663-2e6d934c36e4.png)

**Environment (please complete the following information):**

 - OS: Ubuntu 22.04, Docker version 20.10.19, build d85ef84
 - Label Studio Version 1.6.0rc5 (from `heartexlabs/label-studio:latest` Docker image)

**Comment by makseq** [comment]
`Label all tasks` displays only one prediction by design, you can select which one on the Machine Learning in the Project Settings. 

> but it loads significantly faster when opened from the 'Label All Tasks'

Most likely this happens because LS doesn't pre-load all predictions, so if you have all predictions there, it will slow down again.

**Comment by harrymander** [comment]
Ideally, I'd like all the predictions to appear in a single view since they aren't really 'predictions' per se, more like rough guides to help the annotator find the feature in the time series to annotate more accurately.

I suppose the best way to achieve this would be to add *annotations* (rather than predictions) via the API?

**Comment by harrymander** [comment]
Re: the loading speed - the speed difference is seen even when loading tasks with no predictions or single prediction. In the case of this large time series, the difference is several seconds.

**Comment by makseq** [comment]
Prediction will be copied to annotation automatically if you are using Label all tasks mode. It's not allowed to see annotations in Label all tasks mode.

I still don't understand why you need to have multiple predictions in Label all tasks. I would prepare one good-looking prediction for Label all tasks by combining the best parts of others.

**Comment by harrymander** [comment]
Re the difference in loading speed between label all tasks and direct task open view, the issue seems to be the same as in https://github.com/heartexlabs/label-studio/issues/3094, i.e. I get the same mobx-state-tree error.
