### ISSUE TITLE
REST API docs seem to be out-of-date

### ISSUE THREAD

**Issue by Ben-Epstein** [heartexlabs/label-studio#3112]
**Describe the bug**

**To Reproduce**
1. Go to https://labelstud.io/api#tag/Storage:S3
2. Click on the URL: `http://api.labelstud.io/api/storages/export/s3`
3. Try to use that from the python SDK
```
from label_studio_sdk import Client


LABEL_STUDIO_URL = "http://localhost:8080"
ls = Client(url=LABEL_STUDIO_URL, api_key=API_KEY)
ls.check_connection()

# Get storages 
ls.make_request("GET", "/api/storages/export/s3").json()  # 404
```

**Expected behavior**
a list of my S3 storages

**Screenshots**
API docs:
![image](https://user-images.githubusercontent.com/22605641/196546349-bb55baf4-c26b-4834-a2f0-9c87c33daa57.png)

Trying to hit that endpoint
![image](https://user-images.githubusercontent.com/22605641/196546388-08b26b94-3d82-4afb-8d0f-24b1a0044833.png)

Some work, some don't. Some work that aren't documents (for example `/api/storages` seems to be valid, although returns an empty list even though I have storages set up). Am I doing something wrong here?

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Label Studio Version [e.g. 0.8.0] `0.0.15`

**Comment by Ben-Epstein** [comment]
I tried this via curl too

API
![image](https://user-images.githubusercontent.com/22605641/196547398-a39c6b6b-4a64-4cdb-904b-3ffdde813c3e.png)
curl
```
curl -X GET http://localhost:8080/api/storages/s3 -H 'Authorization: Token XXX'
{"id":"3f2bb135-bfd8-47ef-83ff-7901f059b55e","status_code":404,"version":"1.6.0","detail":"Not found.","exc_info":null}%
```

**Comment by makseq** [comment]
Yeh, it's quite popular problem with API docs. 
You need to call /api/storages/?project=<project_id> to get all import storages.

**Comment by makseq** [comment]
Sure, we need to fix this miss in API docs.

**Comment by makseq** [comment]
https://api.labelstud.io/#operation/api_storages_list --- hope this docs helps now.

**Comment by Ben-Epstein** [comment]
@makseq it seems that the API for `/storage/s3` still exists. Should that be removed before closing this? https://api.labelstud.io/#operation/api_storages_export_s3_list
