### ISSUE TITLE
Unable to load labeling menu of a picture, infinite loading.

### ISSUE THREAD

**Issue by jerkhouri** [heartexlabs/label-studio#3125]
**Describe the bug**
Unable to load picture annotation, infinite loading.

**To Reproduce**
1. Build with docker-compose with image : v1.6.0rc8
2. In the project page, click on one.
3. Open labelling menu in one of pictures.
4. The picture is loading forrever. ![Capture](https://user-images.githubusercontent.com/39912632/197193749-b0400d6b-999e-41ae-a336-e0eb5d074843.PNG)
6. In the app logs (docker-compose logs => app): 
![Capture2](https://user-images.githubusercontent.com/39912632/197194210-a8fa0246-a968-49a9-8087-75b144c786f6.PNG)
note this message can be ignored => https://github.com/heartexlabs/label-studio/issues/1455

**Expected behavior**
See the picture with anotation.

**Environment (please complete the following information):**
 - OS: Docker redhat7
 - Label Studio Version: 1.6.0
 - I'm in a private network without acces to internet.

**Additional context**
Info message in the loading of the program => docker-compose logs => app.
![Capture3](https://user-images.githubusercontent.com/39912632/197221188-3302a500-ed62-44d6-a188-86ce32106f31.PNG)

Thanks for the help,

**Comment by makseq** [comment]
Please share your labeling config and sample data to reproduce this issue.

**Comment by makseq** [comment]
Weird. Just checked it, everything works ok. What browser do you use? 

https://user-images.githubusercontent.com/501780/198160347-72c7b0dd-7805-48b8-a9bc-d17577fa76cb.mp4

**Comment by jerkhouri** [comment]
Hey makseq, 

Thanks for your answer. After a few hours of testing in my environment, I choose to create a new one from scratch with the V1.6.0 release, and I've put the database into. That seems to work now. 

But I don't understand why I've got these problems in the old version…
