### ISSUE TITLE
Can't escape after creating a normalization in a NER task.

### ISSUE THREAD

**Issue by bkemmer** [heartexlabs/label-studio#313]
**Description**
The annotator reported that he cannot escape after creating a normalization, the label keeps been selected and if you change the class (to annotate another type of entity), it will change the class of the previous item. You can click outside the "Regions box" or press ESC and it will continue with the entity selected. Also, if you select another text, it will create another annotation of the same class.
Which in this case, is an undesired behavior.

**To Reproduce**
1. Create a task to be annotated.
2. Select a class and the text.
3. In the regions box, select the entity
4. Click in the plus icon, and create a normalization
5. Try to escape to annotate another class of entity

**Expected behavior**
I expect to click outside the box, stop selecting the entity, the same behavior when pressing ESC.

**Environment:**
 - Linux and Windows
 - Browsers tested: Chrome and Firefox

**Comment by makseq** [comment]
@hlomzik

**Comment by bkemmer** [comment]
@

> Hi, @bkemmer! Sorry for such a long response and this inconvenience.
> But actually everything you describe is expected behaviour. I think you have enabled "Keep label selected after creating a region" in Settings, so after creating one region the app just wait for you to create another one. You can click on the label to unselect it or click on Unselect button in the Regions list (hotkey `u`).
> You are right, `Esc` should do the same — bring the app back to default unselected state. I think we'll do this soon.
> @deppp your thoughts about making this more obvious/usable?

Thank you for the reply!
I just tested and the hotkey "u" worked fine. However, I asked an annotator to do this task and she couldn't escape neither do I. So, it wasn't obvious for us.
Maybe with a message saying to "press <key> to unselect" or at least for me "ESC" is an universal escape key.
Btw awesome software, I took the time to write the issue to help it become even better.

**Comment by bkemmer** [comment]
![Screenshot_20200619_102829](https://user-images.githubusercontent.com/7491603/85137462-a75b6c80-b217-11ea-96a0-b4b099bc0a1f.png)
I just checked and the "Keep label selected after creating a region" is not enabled.

The issue arises after selecting the label then I can't unselect if I don't press "u". My intuition tried to click outside to unselect.

**Comment by hlomzik** [comment]
Thank you for your time! The unselect is not that obvious and we have to do something with this, you are right.
I'll add `Esc` hotkey for this. Also there is hotkey tab in the "settings", but "Unselect [u]" not mentioned there, I'll fix it also.
And maybe we should add some text about it or maybe highlight "Unselect" button in the Regions panel (did you notice it?).
But I afraid that we can not unselect label on any click somewhere, because inside the text we need it, and outside the text there are lot of controls. Also the labelling is the main activity, so it's better to hold on it, but also it should be obvious how to escape from it.

**Comment by bkemmer** [comment]
@hlomzik In your first reply you said "I think you have enabled "Keep label selected after creating a region" in Settings". 
I looked in the settings (as you can see from my last print screen) and the box wasn't selected.
