### ISSUE TITLE
forgot my label studio password

### ISSUE THREAD

**Issue by Gulka15** [heartexlabs/label-studio#3130]
Hello. I forgot my password for label studio and there is no "forgot password" button when i am trying to sign in. Thats why i can't reset my password. How can i do that? Thanks a lot

**Comment by makseq** [comment]
Please check this docs: https://labelstud.io/guide/signup.html#Reset-password

**Comment by Gulka15** [comment]
I didn't install the label studio to my computer, thats why i cannot reset
my password like that. I am entering to label studio through the site
itself. Is there any other way to do that? Thank you!

вт, 25 окт. 2022 г., 4:24 Max Tkachenko ***@***.***>:

**Comment by makseq** [comment]
Without admin access it's not possible. But you can easily register a new account.

**Comment by yanwenjie1** [comment]
If i do not want to reset_password, i just want to see what my password is,how can i do?
I find it in label_studio.sqlite3.htx_user.password,but i got the encrypted result like pbkdf2_sha256$260000$pI6beKfMXj1v9YR7udkRPm$WNf4tCG0BVIjKdW***********************************.
If this project is encrypted with SHA256, please ignore me

**Comment by makseq** [comment]
It's not possible to see your old password, it's hashed in the DB.
