### ISSUE TITLE
 yolo format export problem

### ISSUE THREAD

**Issue by yuminzhe** [heartexlabs/label-studio#3140]
When I try to export the data in yolo format, the following error is reported, but there is no problem in exporting data in coco format.

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/label_studio/data_export/api.py", line 184, in get
    project, tasks, export_type, download_resources, request.GET
  File "/root/anaconda3/lib/python3.7/site-packages/label_studio/data_export/models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/root/anaconda3/lib/python3.7/site-packages/label_studio_converter/converter.py", line 177, in convert
    output_label_dir=label_dir, is_dir=is_dir)
  File "/root/anaconda3/lib/python3.7/site-packages/label_studio_converter/converter.py", line 657, in convert_to_yolo
    label["rotation"],
KeyError: 'rotation'

![image](https://user-images.githubusercontent.com/24829854/197715286-42a0a809-ebf3-47dc-b347-337a79c36688.png)

**Comment by KonstantinKorotaev** [comment]
Hi @yuminzhe 
Could you please share your label config and sample annotation?

**Comment by yuminzhe** [comment]
> Hi @yuminzhe Could you please share your label config and sample annotation?

Thank you for your help.

Here is my Labeling Interface：

`<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
  <Label value="U盘" background="#0000ff"/></RectangleLabels>
</View>
`


Here are the two examples I annotated：

`
{
  "id": 1589,
  "data": {
    "image": "/data/upload/18/0f6142fb-100_21.jpg"
  },
  "annotations": [
    {
      "id": 10563,
      "created_username": " taotao@cai-inc.com, 3",
      "created_ago": "2 months, 2 weeks",
      "completed_by": {
        "id": 3,
        "first_name": "",
        "last_name": "",
        "avatar": null,
        "email": "taotao@cai-inc.com",
        "initials": "ta"
      },
      "result": [
        {
          "original_width": 800,
          "original_height": 800,
          "image_rotation": 0,
          "value": {
            "x": 16.3677871180938,
            "y": 96.17628384254151,
            "width": 52.96047307090268,
            "height": -60.72944286625309,
            "rotation": 0,
            "rectanglelabels": [
              "U盘"
            ]
          },
          "id": "YKhsh44ARh",
          "from_name": "label",
          "to_name": "image",
          "type": "rectanglelabels",
          "origin": "prediction-changed",
          "score": 59
        }
      ],
      "was_cancelled": false,
      "ground_truth": false,
      "created_at": "2022-08-13T07:25:01.364360Z",
      "updated_at": "2022-08-13T07:25:01.364389Z",
      "lead_time": 11.121,
      "task": 1589,
      "parent_prediction": 6229,
      "parent_annotation": null
    }
  ],
  "predictions": [
    {
      "id": 5954,
      "model_version": "1660030616",
      "created_ago": "2 months, 2 weeks",
      "result": [
        {
          "from_name": "label",
          "score": 59,
          "to_name": "image",
          "type": "rectanglelabels",
          "value": {
            "height": -70,
            "rectanglelabels": [
              "U盘"
            ],
            "width": 56,
            "x": 15,
            "y": 98
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-08-09T07:54:35.072490Z",
      "updated_at": "2022-08-09T07:54:35.072557Z",
      "task": 1589
    },
    {
      "id": 6229,
      "model_version": "1660034263",
      "created_ago": "2 months, 2 weeks",
      "result": [
        {
          "from_name": "label",
          "score": 59,
          "to_name": "image",
          "type": "rectanglelabels",
          "value": {
            "height": -70,
            "rectanglelabels": [
              "U盘"
            ],
            "width": 56,
            "x": 15,
            "y": 98
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-08-09T08:43:38.731953Z",
      "updated_at": "2022-08-09T08:43:38.732008Z",
      "task": 1589
    }
  ]
}
`


`
{
  "id": 1588,
  "data": {
    "image": "/data/upload/18/d540b374-100_16.jpg"
  },
  "annotations": [
    {
      "id": 10568,
      "created_username": " taotao@cai-inc.com, 3",
      "created_ago": "2 months, 2 weeks",
      "completed_by": {
        "id": 3,
        "first_name": "",
        "last_name": "",
        "avatar": null,
        "email": "taotao@cai-inc.com",
        "initials": "ta"
      },
      "result": [
        {
          "original_width": 800,
          "original_height": 800,
          "image_rotation": 0,
          "value": {
            "x": 54.000000000000014,
            "y": 81.15197634645489,
            "width": 41.215810771638935,
            "height": -57.15197634645486,
            "rotation": 0,
            "rectanglelabels": [
              "U盘"
            ]
          },
          "id": "V3-Q1wfEmj",
          "from_name": "label",
          "to_name": "image",
          "type": "rectanglelabels",
          "origin": "prediction-changed",
          "score": 95
        }
      ],
      "was_cancelled": false,
      "ground_truth": false,
      "created_at": "2022-08-13T07:26:20.685263Z",
      "updated_at": "2022-08-13T07:26:20.685295Z",
      "lead_time": 4.336,
      "task": 1588,
      "parent_prediction": 6230,
      "parent_annotation": null
    }
  ],
  "predictions": [
    {
      "id": 5957,
      "model_version": "1660030616",
      "created_ago": "2 months, 2 weeks",
      "result": [],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-08-09T07:54:50.860660Z",
      "updated_at": "2022-08-09T07:54:50.860727Z",
      "task": 1588
    },
    {
      "id": 6230,
      "model_version": "1660034263",
      "created_ago": "2 months, 2 weeks",
      "result": [
        {
          "from_name": "label",
          "score": 95,
          "to_name": "image",
          "type": "rectanglelabels",
          "value": {
            "height": -57,
            "rectanglelabels": [
              "U盘"
            ],
            "width": 40,
            "x": 54,
            "y": 81
          }
        }
      ],
      "score": 0,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2022-08-09T08:43:41.262208Z",
      "updated_at": "2022-08-09T08:43:41.262288Z",
      "task": 1588
    }
  ]
}
`

**Comment by KonstantinKorotaev** [comment]
What LS version do you use?

**Comment by makseq** [comment]
Fixed in the latest master commits in label-studio-converter lib.
https://github.com/heartexlabs/label-studio-converter/commit/06f02fde20268913a28821d546bb30fb78407fb8 
[ticket is LSDV-4807]
