### ISSUE TITLE
How can I pull the right version?

### ISSUE THREAD

**Issue by schoenfbe** [heartexlabs/label-studio#3141]
No matter if I deploy it locally, or on our kubernetes cluster, if I pull "heartexlabs/label-studio:1.6.0", I'll end up with "1.6.0rc5" instead, and it tells me to upgrade.

How do I get the correct version?

**Comment by makseq** [comment]
Sorry for this inconvenience, but rc5 is ok for 1.6.0, it's a bug with naming.
