### ISSUE TITLE
issue with named entity recognition

### ISSUE THREAD

**Issue by ziyad00** [heartexlabs/label-studio#3146]
**Describe the bug**
there is an issue with named entity recognition in nlp in when importing data as csv it only show the task of the first row even when switching to any other task to label.
i tried to trace it and found out that the frontend request is correct and the backend response but it seems the front end does not handle the response to show different task also when i looked for the code it was
![4](https://user-images.githubusercontent.com/20027707/198031684-c8220c06-7263-434b-ae3c-8d60608c192d.jpeg)
containing the first row of the csv file and when i changed it to 
![3](https://user-images.githubusercontent.com/20027707/198031767-c20a7f45-5cfb-4bf6-9aa0-2834363bb60d.jpeg)
it worked but i need to do it each time
**To Reproduce**
1. import csv file
2. choose named entity recognition
3. label any task all of them will be the same

**Expected behavior**
it should have different row based on the task
**Environment (please complete the following information):**
 - OS: windows

**Comment by makseq** [comment]
1. it's not allowed to use spaces inside of `value`.
2. when you import CSV, you should select that this csv is a list of tasks (NOT time series or text).
