### ISSUE TITLE
Generatable Task URLs are broken in labelstudio 1.6.0

### ISSUE THREAD

**Issue by csaroff** [heartexlabs/label-studio#3151]
**Describe the bug**
Prior to labelstudio 1.6.0, given a task id and a project id, I used to be able to generate a valid url that opens up that task in labelstudio.

```
https://<labelstudio_url>/projects/<project_id>/data?task=<task_id>
```

This redirects to:
```
https://<labelstudio_url>/projects/<project_id>/data?task=<task_id>&tab=<lowest tab id in this project>
```

And the task is just blank. :(

![image](https://user-images.githubusercontent.com/7225723/198150982-8d3420cc-3e3e-43cb-8ddf-8719ee7e161a.png)

In our case, tab 363 doesn’t have any filters so I’m not sure why it shows as blank anyway.

**Expected behavior**
The task/image loads normally.

**Environment (please complete the following information):**
 - Client OS: macOS
 - Client Browser: Brave | 1.45.113 Chromium: 107.0.5304.62 (Official Build) (arm64)
 - Label Studio Version: heartexlabs/label-studio:1.6.0

**Additional context**
Ideally we'd like to avoid workarounds that involve fetching the proper task id(if that's even possible), because calling the labelstudio api for each task will be time-consuming and the urls won't work once that tab is removed.

Here's the [related conversation](https://label-studio.slack.com/archives/CQ8LYPPJS/p1666128583350369) in labelstudio's slack workspace

**Comment by makseq** [comment]
It's a bug, I've created a ticket, hope we will fix it soon.

**Comment by makseq** [comment]
Please check there latest develop branch, it should be fixed there.
