### ISSUE TITLE
File Import from VM

### ISSUE THREAD

**Issue by saadtariqaddo** [heartexlabs/label-studio#3152]
My goal is to run label studio on Virtual Machine and import files from there. For this purpose i am using following command

`docker run -it -p 8080:8080 -v $(pwd)/audio-train/audios:/label-studio/data --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true --env LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files -v $(pwd)/audio-train/audios:/label-studio/files heartexlabs/label-studio:latest label-studio`

The issue i am facing is label studio is importing files from local drive not from VM. I want label studio to import files directly from VM instead of local

**Comment by makseq** [comment]
Try to remove this part:
```
-v $(pwd)/audio-train/audios:/label-studio/files
```
