### ISSUE TITLE
Getting error "An error occurred (InvalidToken) when calling the ListObjectsV2 operation: The provided token is malformed or otherwise invalid." when syncing S3 with label studio. But, the connection was successful

### ISSUE THREAD

**Issue by Kaushik55** [heartexlabs/label-studio#3157]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

**Comment by makseq** [comment]
You are using a bad token. Please provide the correct one.
