### ISSUE TITLE
No labels

### ISSUE THREAD

**Issue by topl0305** [heartexlabs/label-studio#3159]
When opening task to annotate text there are no labels shown (first image).
Reason unknown - similar file is opened without problems (second image).

The only possible hint is message in logs:
[io_storages.utils::get_uri_via_regex::25] [WARNING] ........ does not match uri regex ([\"'])(?P<uri>(?P<storage>{})://[^\1=]*)\1

But this message is shown for both files in images

**To Reproduce**
Not possible at the moment. Maybe culprit is malformed txt file, but that shouldn't be a problem.

**Environment (please complete the following information):**
 - OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
 - Label Studio Version - 1.5.0

**Additional context**
<img width="1458" alt="no_labels_1" src="https://user-images.githubusercontent.com/58388770/198526205-43697f70-9203-4748-b767-39f9be09d9c1.png">
<img width="1214" alt="no_labels_2" src="https://user-images.githubusercontent.com/58388770/198526233-cc4af09e-3f8d-4a58-8e5c-a736577da1d7.png">

**Comment by makseq** [comment]
Looks like your text is too wide and it moves your labels right. 
Try to place labels in the top or bottom relative to the text.
