### ISSUE TITLE
Remove point from polygon

### ISSUE THREAD

**Issue by trieuduc** [heartexlabs/label-studio#318]
**Is your feature request related to a problem? Please describe.**
How can I remove the point from polygon? I tried double-click, hold ctrl and click, etc..

**Describe the solution you'd like**
I want to remove point polygon when double-clicking into point or ctrl+click

**Comment by deppp** [comment]
Hey @trieuduc thanks for reporting. This is in the roadmap, I'll comment again when we release that.

**Comment by hlomzik** [comment]
fixed by https://github.com/heartexlabs/label-studio-frontend/pull/166 some time ago
now you can delete polygon point with double click
