### ISSUE TITLE
Copying an annotation from one photo to another

### ISSUE THREAD

**Issue by fitopassit** [heartexlabs/label-studio#3196]
How can I copy all annotations from one photo to another?

**Comment by makseq** [comment]
In LS 1.5.0 and earlier ctrl + c / ctrl + v worked. However we have a bug in LS 1.6.0, this functionality doesn't work, we are fixing it now.

**Comment by tommyvtran97** [comment]
Is there an approximate date when this will be fixed?

**Comment by hazcoper** [comment]
i checked the following branch and it does not seem to be working. Out of 10 or so attempts, one randomly worked

**Comment by DavidMRGomes** [comment]
Did not work for me as well. A fix for this would be awesome!

**Comment by makseq** [comment]
Work is still in progress unfortunately: https://github.com/heartexlabs/label-studio/pull/3341 
If you want you can check it too.

**Comment by Berttwm** [comment]
Hi, I have a need to copy annotations across different annotators and have faced this same issue. It randomly works and sometimes I have to do either of selecting and unselecting the region to copy or refreshing the page hoping this would work. Has this issue been fixed? 

Are there other ways to copy and paste which are currently stable and working?

**Comment by makseq** [comment]
@Berttwm are you on the latest develop branch of LS? it should have been fixed there since January.
