### ISSUE TITLE
Error at importing many images at the same time

### ISSUE THREAD

**Issue by DaniiSalas** [heartexlabs/label-studio#3203]
**Description of the bug**
Hi, im trying to import 200 images at the same time, in a batch, through the interface. Then, an error occurs and all the images loading   (in a column of images names) disappear. I have noticed that if the weight of each image is about 400 kB it allows me to import 500 images at the same time (aprox.). If the weight of each one is about 2MB, it allows me to import 150 images (aprox.).
Does it have a limit on the numbrer of images to import at once or the total weight of them?
In that case, could be possible to remove or raise that limit up?

**To Reproduce**
To reproduce this error just click on the import botton placed on the top right zone at the interface. Then try to upload a quite big batch of images at the same time.

**Expected behavior**
It is expected to, suddenly, the column of images names that were loading vanish.

**Environment (please complete the following information):**
 - Label Studio Version 1.6.1dev

Thank you for the assistance.

**Comment by makseq** [comment]
@DaniiSalas please use Storages for import of big amount resources.
https://labelstud.io/guide/storage.html#How-external-storage-connections-and-sync-work

Import through the interface was implemented only for toy-test project, LS doesn't provide production level hosting for files.

**Comment by ZhangYuef** [comment]
> 

@makseq I am wondering why this error happend. Could you please help to analyse  the cause of the issue？
