### ISSUE TITLE
Multiple Images for a task

### ISSUE THREAD

**Issue by Rusteam** [heartexlabs/label-studio#321]
**Is your feature request related to a problem? Please describe.**
I want to set a class label for a multiple images at once. This will increase labelling speed since within one task you label multiple images

**Describe the solution you'd like**
A new tag that will take an array of image paths to display them together.

**Describe alternatives you've considered**
Iterating over all images one-by-one.

**Additional context**
I'm collecting data from various sources, there're hundreds and thousands class names but they don't have a unified standard for naming. That's why I need to go into a class, see all images and assign one unified class label.

**Comment by Rusteam** [comment]
I was able to get around by using a plain html with the HyperText tag

**Comment by makseq** [comment]
If you have a fixed number of images you can use multiple <Image> tags in one config.

**Comment by Rusteam** [comment]
> If you have a fixed number of images you can use multiple  tags in one config.

no, the number of images per class varies a lot

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio-frontend/pull/164#issuecomment-827503253 check this PR please
