### ISSUE TITLE
unable to load the label-studio after installation using pip

### ISSUE THREAD

**Issue by paavan28** [heartexlabs/label-studio#3211]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/59466645/200117880-94fa299d-b9f6-4d60-9e79-ae6ceed42c62.png">
<img width="700" alt="image" src="https://user-images.githubusercontent.com/59466645/200117898-43287e80-ba9a-478e-93eb-2b12bdbca429.png">

I used Python 3.8 for installation and added to the path just in the first phases nonetheless, I am unable to load the server in Jupyter notebook using the given command label-studio.
Please resolve this issue.

Thank you very much.

**Comment by makseq** [comment]
Please check how to use jupiter with terminal commands
https://stackoverflow.com/questions/38694081/executing-terminal-commands-in-jupyter-notebook
