### ISSUE TITLE
Anotate the property of each label?

### ISSUE THREAD

**Issue by JYL67** [heartexlabs/label-studio#3217]
Are methods available to achieve this? I couldnt achieve that used rectangle, Labels, Choies... 

eg: The labels are "vehicle" and "human".
Properties of "vehicle" are "color"(green, blue) and "type"(car, bicycle...)
Properties of "human" are "gender"(male, female), "age"(60, 50...)
My anatation:
The label of Rectangle1 is "vehicle".  Property-color is "green", Property-type is "car".
The label of Rectangle2 is "human".  Property-gender is "male", Property-age is "60".

**Comment by makseq** [comment]
[Check this labeling config](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CHeader%20value%3D%22Select%20bbox%20after%20creation%20to%20go%20next%22%2F%3E%3Cbr%3E%20%20%3CImage%20name%3D%22image%22%20value%3D%22%24image%22%2F%3E%3Cbr%3E%3Cbr%3E%20%20%3CRectangleLabels%20name%3D%22label%22%20toName%3D%22image%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22vehicle%22%20background%3D%22green%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22human%22%20background%3D%22blue%22%2F%3E%3Cbr%3E%20%20%3C%2FRectangleLabels%3E%3Cbr%3E%3Cbr%3E%20%20%3CView%20visibleWhen%3D%22region-selected%22%20whenLabelValue%3D%22vehicle%22%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Vehicle%20color%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoices%20name%3D%22vehicle_color%22%20toName%3D%22image%22%20perRegion%3D%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%22green%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%22blue%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FChoices%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Vehicle%20type%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoices%20name%3D%22vehicle_type%22%20toName%3D%22image%22%20perRegion%3D%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%22car%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%22bicycle%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FChoices%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%20%20%3Cbr%3E%20%20%3CView%20visibleWhen%3D%22region-selected%22%20whenLabelValue%3D%22human%22%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Human%20gender%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoices%20name%3D%22human_gender%22%20toName%3D%22image%22%20perRegion%3D%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%22male%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%22female%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FChoices%3E%3Cbr%3E%20%20%20%20%3CHeader%20value%3D%22Human%20age%22%20%2F%3E%3Cbr%3E%20%20%20%20%3CChoices%20name%3D%22human_age%22%20toName%3D%22image%22%20perRegion%3D%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%2250%22%2F%3E%3Cbr%3E%20%20%20%20%20%20%3CChoice%20value%3D%2260%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FChoices%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E)

```
<View>
  <Header value="Select bbox after creation to go next"/>
  <Image name="image" value="$image"/>

  <RectangleLabels name="label" toName="image">
    <Label value="vehicle" background="green"/>
    <Label value="human" background="blue"/>
  </RectangleLabels>

  <View visibleWhen="region-selected" whenLabelValue="vehicle">
    <Header value="Vehicle color" />
    <Choices name="vehicle_color" toName="image" perRegion="true">
      <Choice value="green"/>
      <Choice value="blue"/>
    </Choices>
    <Header value="Vehicle type" />
    <Choices name="vehicle_type" toName="image" perRegion="true">
      <Choice value="car"/>
      <Choice value="bicycle"/>
    </Choices>
  </View>
  
  <View visibleWhen="region-selected" whenLabelValue="human">
    <Header value="Human gender" />
    <Choices name="human_gender" toName="image" perRegion="true">
      <Choice value="male"/>
      <Choice value="female"/>
    </Choices>
    <Header value="Human age" />
    <Choices name="human_age" toName="image" perRegion="true">
      <Choice value="50"/>
      <Choice value="60"/>
    </Choices>
  </View>

</View>
```
