### ISSUE TITLE
Paragraphs colud add multi choices control for every sentence labelling

### ISSUE THREAD

**Issue by mingminyu** [heartexlabs/label-studio#3224]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Label Studio provides choices for labelling a whole dialogue, but we all know the key sentence actually decides the intents of the dialogue, so I think if `intent classification and slots filling` can choose the intent for every sentence, will help lots of developers and complete nlp model more useful.

**Describe alternatives you've considered**
I think it will be bertter if the right dialogue is replaced by dropdown multi choices, like Taxonomy(I had tried this tag into Paragraphs, it does not work).

**Additional context**
![image](https://user-images.githubusercontent.com/29671236/200735837-cc174b6a-6124-4130-8817-18c8295dc07a.png)

I had to split a dialogue into two, the left for labeling slots filling, and the right for labeling intents, this is so bad...

**Comment by makseq** [comment]
@mingminyu You should check Repeater tag:
https://labelstud.io/tags/repeater.html#Example-1

You can use Taxonomy inside of the repeater.

**Comment by buptygz** [comment]
@makseq why not repeater tag ?

**Comment by failable** [comment]
@makseq The link has become 404
