### ISSUE TITLE
How to integrate Django ORM shell commands into python script?

### ISSUE THREAD

**Issue by youyuge34** [heartexlabs/label-studio#3227]
I want to integrate the following shell commands in my python scripts without using shell, is there a solution? 

-------------------------------------------------------------------------------------

@ntakouris 

As a workaround, you can follow this

1. go to console where you run LS and call there:
```
label-studio shell
```
  it will run LS shell (Django shell_plus) and you will be able to execute Django ORM commands

2. In shell plus: 
```
from tasks.serializers import TaskWithAnnotationsSerializer

tasks = Task.objects.filter(project=<ID>)
export_json_data = TaskWithAnnotationsSerializer(tasks, many=True).data
```

3. Optionally:
```
import json 
with open('export.json', 'w') as f:
  json.dump(export_json_data, f)
```

_Originally posted by @makseq in https://github.com/heartexlabs/label-studio/issues/2663#issuecomment-1208715799_

**Comment by youyuge34** [comment]
@makseq 
Is there a way to integrate these shell codes into a single python script file `.py`? THX a lot

**Comment by ntakouris** [comment]
Somewhat equivalent of SQL/"STORED_PROCEDURE"?

**Comment by makseq** [comment]
@youyuge34 @ntakouris if you are looking for a way how to export annotations, we have a special console command now:
https://labelstud.io/guide/export.html#Export-using-console-command

If you want to have a single python script:

```
import os
import json
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "htx.settings.label_studio")
django.setup()
import logging

from tasks.serializers import TaskWithAnnotationsSerializer

logger = logging.getLogger(__name__)

if __name__ == '__main__':
  project_id = 123
  tasks = Task.objects.filter(project=project_id)
  export_json_data = TaskWithAnnotationsSerializer(tasks, many=True).data
  with open('export.json', 'w') as f:
    json.dump(export_json_data, f)
```
