### ISSUE TITLE
Multimodal information extraction

### ISSUE THREAD

**Issue by tianchiguaixia** [heartexlabs/label-studio#3228]
Can you refer to the UBIAI tool design to export xfund and funsd datasets

https://ubiai.tools/NLP/

![image](https://user-images.githubusercontent.com/29837553/201005263-b28ca02e-acf9-40f7-81b5-0db15dde84ac.png)

**Comment by makseq** [comment]
@tianchiguaixia please check this comment and this issue:
https://github.com/heartexlabs/label-studio/issues/2634#issuecomment-1251648670

**Comment by makseq** [comment]
Also check this PR in the LS converter:
https://github.com/heartexlabs/label-studio-converter/pull/127#issue-1378594350
