### ISSUE TITLE
How to connect the ocr tool to the backend

### ISSUE THREAD

**Issue by tianchiguaixia** [heartexlabs/label-studio#3229]
How to connect the ocr tool to the backend about optical character recognization

![image](https://user-images.githubusercontent.com/29837553/201005592-45815942-903c-4117-99e5-242d3952ecaf.png)

**Comment by haiderasad** [comment]
refer to the boiler plate code provided by https://github.com/heartexlabs/label-studio-ml-backend and add your backend model just as in examples folder

**Comment by makseq** [comment]
Also check this readme and this tesseract model:
https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/examples/tesseract
