### ISSUE TITLE
Slow loading time of project's tasks

### ISSUE THREAD

**Issue by AndreaBrg** [heartexlabs/label-studio#3242]
Hi, I'd like to use Label Studio to annotate around 150 images (or even more). Unfortunately, my connection is sometimes pretty slow, and loading all the project's tasks takes quite some time (5 to 10 minutes).
I've seen that the API call asks for loading 30 images `http://xxx.xxx.xxx.xxx:yyyy/api/tasks?page=1&page_size=30&view=2&project=1`. Is there a way to reduce this number or speed up the task-loading page?

Thanks.

**Comment by makseq** [comment]
Hi, 
```
ff_front_dev_1470_dm_pagination_010422_short=1 label-studio
```
please try this, you will see pagination where you can set 10 tasks per page.

**Comment by AndreaBrg** [comment]
@makseq, thanks for the suggestion, but I'm having trouble understanding how to implement it.

I'm using Docker to run Label Studio:
`docker run -d -p 8085:8080 --name label-studio-new --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true --env LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files --env LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true --env LABEL_STUDIO_PASSWORD=xxx --env LABEL_STUDIO_USERNAME=xxx -v /data/label-studio-new:/label-studio/data -v /data/label-studio-new/local-data:/label-studio/files label-studio`

Where should I put `ff_front_dev_1470_dm_pagination_010422_short=1`?

**Comment by AndreaBrg** [comment]
Thanks @makseq , it works. I've noticed that the first time the project is opened, the requester page_size is still 30. When a new page is selected, it correctly asks for 10.
Any way to force 10 elements also for the first load?

**Comment by makseq** [comment]
I think there is no way :( only rebuild the frontend..

**Comment by RobinFrcd** [comment]
Hi,
I tried this in docker but I get `./deploy/docker-entrypoint.sh: 54: exec: ff_front_dev_1470_dm_pagination_010422_short=1: not found`. Is there a way to disable pagination when using the app with docker ?

Thanks !

**Comment by makseq** [comment]
You should add this variable to docker's environment vars.

**Comment by RobinFrcd** [comment]
Oh, damn, I guess it was getting late, sorry for the dumb question ! Thanks !

**Comment by alete89** [comment]
`ff_front_dev_1470_dm_pagination_010422_short` env stopped working after upgrading from 1.7 to 1.12. I'm guessing it just changed the name, I want to believe the option wasn't simply removed. Is there anywhere where this is documented?

**Comment by cod3r0k** [comment]
Is there any way to reduce the response time of the API? I’ve increased the CPU and RAM, but it hasn’t improved the performance.
