### ISSUE TITLE
editable label support

### ISSUE THREAD

**Issue by yangboz** [heartexlabs/label-studio#3246]
after labeling some task,  there is no way to edit the labels, for example , change the label name,color...

**Describe the solution you'd like**
currently, edit way depends on delete older one, then create new.

**Describe alternatives you've considered**
to save time efforts. 

**Additional context**
after editing ,  automatically cascade update ?

**Comment by makseq** [comment]
You can try this approach: 
https://github.com/heartexlabs/label-studio/pull/2055#issue-1146317495

Also in the latest develop we allowed to edit the labeling config without hard restrictions.
