### ISSUE TITLE
HyperText tag does not embed PDFs

### ISSUE THREAD

**Issue by wpm** [heartexlabs/label-studio#3252]
I created a project with a labeling interface copied from the "Rate PDF" example in the [playground](https://labelstud.io/playground/). 

```
<View>
  <HyperText name="pdf" value="$pdf" inline="true"/>

  <Header value="Rate this article"/>
  <Rating name="rating" toName="pdf" maxRating="10" icon="star" size="medium"/>

  <Choices name="choices" choice="single-radio" toName="pdf" showInline="true">
    <Choice value="Important article"/>
    <Choice value="Yellow press"/>
  </Choices>
</View>
```

I gave it the following data file.

```
[
  {
    "data": {
      "pdf": "https://arxiv.org/pdf/2211.06712.pdf"
    }
  }
]
```

When I launch the task, the PDF url is rendered as text instead of an embedded PDF as I would expect.

<img width="1763" alt="label-studio-pdf-not-displayed" src="https://user-images.githubusercontent.com/141456/201994412-6d0fcbbf-9c48-413d-a466-9c7abded00f8.png">

This is Label Studio version 1.6.0rc5 installed from [the Docker image](https://labelstud.io/guide/install.html#Install-with-Docker). OS X 12.6.1. Same behavior on both Chrome 107.0.5304.110 and Safari 16.0.

[Issue 2049](https://github.com/heartexlabs/label-studio/issues/2049) describes the same behavior. In that case the problem was a missing `inline="true"` in the `HyperText` tag. That is not the case here.

**Comment by wpm** [comment]
Now I'm trying everything I can think of to get an embedded PDF. Changing the HyperText tag to this

```
<HyperText name="pdf" inline="true">
  <iframe src="$pdf"/>
</HyperText>
```
does not work. Nothing is displayed. Though if I put other HTML inside that tag (e.g. `<h1>$pdf</h1>`) that is displayed.

I also verified that the `iframe` tag works for PDFs in my browser.

**Comment by wpm** [comment]
It works if I change the data file to

```
{
  "data": {
    "pdf": "<embed src='https://arxiv.org/pdf/2211.06712.pdf' width='100%' height='600px'/>"
  }
```

An embedding PDF is displayed when I try to do the annotation task.

It appears only works if I write the `embed` command in explicitly instead of requiring the `HyperText` tag to figure it out.

If I replace `embed` in the data file above with `iframe` a PDF is not displayed when doing the task.

**Comment by wpm** [comment]
Is this expected behavior?

If it is, I was confused by the [PDF Classification](https://labelstud.io/templates/pdf_classification.html) page in the documentation. That shows `<HyperText src="$pdf">` without specifying that `$pdf` needs to be an embed tag and not just as URL. There is an XML comment in that illustrates this, but it would be helpful to have it in the documentation too.

I'm still surprised that `iframe` doesn't work.

**Comment by makseq** [comment]
Sorry for this confusion, the documentation is not very clear there, I've fixed it now. 

If you [go to the Playground](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%20%20%3CHeader%20value=%22Rate%20this%20article%22/%3E%3Cbr%3E%20%20%20%20%3CRating%20name=%22rating%22%20toName=%22pdf%22%20maxRating=%2210%22%20icon=%22star%22%20size=%22medium%22%20/%3E%3Cbr%3E%20%20%20%20%20%3CChoices%20name=%22choices%22%20choice=%22single-radio%22%20toName=%22pdf%22%20showInline=%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CChoice%20value=%22Important%20article%22/%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CChoice%20value=%22Yellow%20press%22/%3E%3Cbr%3E%20%20%20%20%3C/Choices%3E%3Cbr%3E%20%20%20%20%3CHyperText%20name=%22pdf%22%20value=%22$pdf%22%20inline=%22true%22/%3E%3Cbr%3E%3C/View%3E) and see to Input data, there will be highlighted `<embed ...>`. 

Now I've fixed the PDF classification template, hope it looks more clear now:
https://labelstud.io/templates/pdf_classification.html

**Comment by binhpageai** [comment]
@makseq  Can I set embed src = presigned url ?
