### ISSUE TITLE
Diversity Sampling

### ISSUE THREAD

**Issue by david-waterworth** [heartexlabs/label-studio#3256]
**Is your feature request related to a problem? Please describe.**
I've not used label-studio much, but I've evaluated a couple of other similar interfaces that implement uncertainty sampling for active learning. For my dataset, it is no better than random sampling. The issue is I have lots of similar short strings, so at each interaction, almost all of the most uncertain samples are very similar. What works much better is diversity sampling.

**Describe the solution you'd like**
I'm looking for an annotation interface that allows me to implement diversity sampling. The dataset is split into two pools, "labelled" and "unlabelled". At each iteration, a sample is drawn from the "unlabelled" dataset such that it is dissimilar to all the examples in the "labelled" dataset. Similarity is model dependent - I'm using text (ner) and generally a CountVectoriser and cosine difference works well.

**Describe alternatives you've considered**
So far I've been unable to find a suitable active learning framework that works effectively with my dataset. I'm wondering if I could manipulate the scores returned from a ml model - i.e. instead of returning the actual confidence from the model, return the distance to the closest labelled point?

**Comment by makseq** [comment]
Sure, you can return whatever you want from the ML backend. However, it sounds like after the each new labeled task you need to recalculate similarity score for the whole dataset (or its random subset) and show the next most relevant sample for labeling. You can update scores in predictions using `PATCH api/predictions/<id>` {"score": 0.5}

**Comment by david-waterworth** [comment]
Thanks, yes, the similarity scores between the labelled and unlabelled datasets need to be updated on each iteration - there's a google library that includes some sampling methods (https://github.com/google/active-learning) that I've been experimenting with. The `kcenter_greedy` works well for text (when combined with an sklearn vectrizer as it requires numeric feature vectors). Internally it uses sklearns `pairwise_distances` with two arguments (the arrays of labelled and unlabelled examples).

So I guess I need to implement the prediction API so that it returns the next batch and internally tracks the status of every point in the dataset (i.e. if it's been returned in a batch, it's treated as labelled, otherwise, treat it as unlabelled)?

It's this pool-based approach with labelled/unlabelled pools that I've found hard to integrate into the interfaces I've reviewed to date.

**Comment by makseq** [comment]
Yes, your ideas make sense ;-) 

Probably you would be interested in this kind of sampling with clusters: 
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/projects/functions/next_task.py#L93

To enable this sampling you should call `PATCH api/projects/<id>` with { 'sampling': ''Uncertainty sampling''} and assign cluster numbers in predictions, so your predictions should have {'cluster': 123, 'score': 0.5}.
