### ISSUE TITLE
When I deploy to the server, it is wrong to open the web page.

### ISSUE THREAD

**Issue by Hui-Sir** [heartexlabs/label-studio#3269]
![P2 U6OQ8KTR@NJCUA4SXR1T](https://user-images.githubusercontent.com/57337554/202754383-16234606-24f2-479b-9562-3d3994989113.png)

**Comment by Hui-Sir** [comment]
![1669024644629](https://user-images.githubusercontent.com/57337554/203021161-7eb8a4cb-9e32-4bef-be94-395f42bbaac9.jpg)

**Comment by makseq** [comment]
It's very unclear how you deploy. Please write full description for this issue.

**Comment by YuchaoLau** [comment]
I have the same problem.  Install from source. 
Start command:  label-studio start --port 8089

![image](https://user-images.githubusercontent.com/54919837/203216538-bd904a67-f8b0-4f2b-9599-6c76fa07187c.png)

**Comment by Hui-Sir** [comment]
> 目前还不清楚你是如何部署的。请写下这个问题的完整描述。

The problem has been solved. I added a port to the domain name yesterday.

**Comment by Hui-Sir** [comment]
> 
The problem has been solved. I added a port to the domain name yesterday.

**Comment by YuchaoLau** [comment]
> > 
> 
> The problem has been solved. I added a port to the domain name yesterday.
Where did you add it？

**Comment by Hui-Sir** [comment]
> 

Do you know how to delete users?
