### ISSUE TITLE
Unable to mark polygon regions

### ISSUE THREAD

**Issue by azure31** [heartexlabs/label-studio#327]
Hi, I'm trying to label classes and mark polygons regions in images. I'm able to do this in the label studio playground, but when I try running the same locally, the polygon region marker tooltip doesn't appear at all. What could be the issue? Any help or suggestions would be appreciated.

**Comment by makseq** [comment]
What LS version do you use?
Please, show you label config here.

**Comment by azure31** [comment]
Hi, I was able to solve this. I had a nested hierarchy to pick the labels and rearranging the tag levels worked for me. Thanks!
