### ISSUE TITLE
Prediction id causes completions not to load

### ISSUE THREAD

**Issue by shubh4solanki** [heartexlabs/label-studio#328]
**Describe the bug**
When I import prediction and create completions based on that prediction it causes completions not to load when reloading a page and it gives this error in console.

```
Uncaught Error: [mobx-state-tree] Cannot resolve a reference to type 'Completion' with id: '1' unambigously, there are multiple candidates: /completionStore/predictions/0, /completionStore/completions/0
    at be (mobx-state-tree.module.js:3662)
    at e.resolve (mobx-state-tree.module.js:3369)
    at e.updateResolvedReference (mobx-state-tree.module.js:6996)
    at e.get [as resolvedValue] (mobx-state-tree.module.js:7011)
    at t.getValue (mobx-state-tree.module.js:7233)
    at t.get [as value] (mobx-state-tree.module.js:1128)
    at t.unbox (mobx-state-tree.module.js:1796)
    at t.dehanceValue (mobx.module.js:1206)
    at t.get (mobx.module.js:1266)
    at e.read (mobx.module.js:4573)
```

**To Reproduce**
1. Create a "Named Entity Recognition" project
2. Import a prediction.
```
[
  {
    "predictions": [
      {
        "id": 1,
        "lead_time": 3.739,
        "result": [
          {
            "from_name": "label",
            "id": "fmXOJEDi3e",
            "source": "$text",
            "to_name": "text",
            "type": "labels",
            "value": {
              "end": 47,
              "labels": [
                "Ordinal"
              ],
              "start": 42,
              "text": "water"
            }
          }
        ]
      }
    ],
    "data": {
      "text": "To have faith is to trust yourself to the water"
    },
    "id": 0
  }
]
```
3. Create completions based on prediction.
4. Reload the page and check the error in the console.

**Expected behavior**
It should allow creating completions based on imported prediction(s).

**Video**
The video below is very useful for reproducing the error

![id_bug](https://user-images.githubusercontent.com/29801996/85280003-f5d16b00-b4a4-11ea-82e7-81de21dc0099.gif)

**Environment (please complete the following information):**
 - OS: macOS, ubuntu
 - Browser Chrome, Firefox
 - Label studio frontend version: 0.7.0

**Comment by makseq** [comment]
Can you try the lastest version of LS?

**Comment by shubh4solanki** [comment]
Yes, I tried. Prediction is not being loaded.

**Comment by makseq** [comment]
@hlomzik

**Comment by hlomzik** [comment]
Hi, @shubh4solanki, sorry for long response. Do you still encounter the issue?
We fixed some problems with relations in previous release, but I found some other issues and they'll be fixed soon, we need to remanage work with ids.

**Comment by makseq** [comment]
Fixed in https://github.com/heartexlabs/label-studio/releases/tag/v0.7.4
