### ISSUE TITLE
Wrong link opened in case of changing port

### ISSUE THREAD

**Issue by johngull** [heartexlabs/label-studio#329]
**Describe the bug**
In my situation port 8080 was bonded by another process and label-studio gracefully took port 8081 during the start command. And in the text description label-studio correctly shown http://localhost:8081, but opened page was http://localhost:8080.

**To Reproduce**
1. Run any other server on 8080 port
2. Start label-studio
3. Check opened page

**Comment by makseq** [comment]
Thank you for the report, we will fix it in release 0.7.3

**Comment by makseq** [comment]
I fixed this problem in this PR: https://github.com/heartexlabs/label-studio/pull/320
it will be great If you test :slightly_smiling_face:
