### ISSUE TITLE
Merging multiple annotations + images

### ISSUE THREAD

**Issue by mhyeonsoo** [heartexlabs/label-studio#3290]
**Describe the bug**

**To Reproduce**
1. Do annotation separately by multiple people
2. Export each json file from their local
3. Make new project
4. Import multiple json file (or sync with the local path)
5. We could see the json file uploaded annotations but there is no image along with that.

**Expected behavior**
images and annotations are both uploaded and linked automatically.

**Screenshots**
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/32179857/203470666-406cacee-e6bd-4aff-bce5-c215f2c810b1.png">

**Environment (please complete the following information):**
 - OS: iOS
 - Label Studio Version  1.6.0

**Additional context**
I tried to follow #2775  and #2086 but both did not work well.

**Comment by mhyeonsoo** [comment]
solved by editing json file path!

**Comment by HouseWay** [comment]
> solved by editing json file path!

should I edit the json file path on by one ?

**Comment by waiwai-2** [comment]
> 通过编辑JSON文件路径解决了！
Hello, could you please tell me how to modify the JSON file specifically?
