### ISSUE TITLE
Can't export completion as csv

### ISSUE THREAD

**Issue by johngull** [heartexlabs/label-studio#330]
**Describe the bug**
When I try to export results as CSV, I got Chrome message "undefined". And it seems that real reason is an internal error in the server on `"GET /api/export?format=CSV HTTP/1.1" 500 -`

**Screenshots**
![image](https://user-images.githubusercontent.com/1451797/85391262-9a5db680-b552-11ea-80f3-3138cc91af7a.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome 83
 - Label-studio 0.7.2

**Comment by makseq** [comment]
Can you show your label config?

**Comment by johngull** [comment]
Here is it:

```
<View>
  <Image name="img" value="$image"></Image>
  <Choices name="tag" toName="img" choice="single-radio">
    <Choice value="Overview"></Choice>
    <Choice value="Close view"></Choice>
    <Choice value="Cuted"></Choice>
    <Choice value="Garbage"></Choice>
  </Choices>
</View>
```

**Comment by makseq** [comment]
I checked this config, everything is ok. Can you send sample of imported tasks?
Probably the problem is in tasks (maybe any encoding problems?)

**Comment by hsethi2709** [comment]
I have faced similar issues due to multiple completions on a given task. When I deleted the extra completions on a task and just kept one, exporting CSV was successful. Can you confirm if you have multiple completions as well?

**Comment by johngull** [comment]
@hsethi2709 How to verify this?

**Comment by hsethi2709** [comment]
I checked it in the logs and could see errors that said "Currently only one completion can be added per task - we can't convert more than one completions, but 2 completions found in item:" Here the whole task used to be present along with its ID. So you can go to that task and remove that completion. 

I am not sure how you can look for multiple completions without checking the log.

I can also see in the converter that they do not support multiple completions for exporting to CSV. I have attached the screenshot of the label-studio-converter that is used for this purpose. 
<img width="890" alt="Screen Shot 2020-06-26 at 5 31 50 pm" src="https://user-images.githubusercontent.com/18085024/85832614-c3d94500-b7d3-11ea-85a7-ab2b102e4415.png">

**Comment by johngull** [comment]
@hsethi2709 I verified result.json and you are right there is repeating of one of the tasks. Thank you for the tip.

@makseq At least it will be nice if UI will show some clear message about this.
And that is strange that I did nothing for repeating the same task. Is it possible to check repeats and remove them in UI?

**Comment by johngull** [comment]
@makseq By parsing json in a more verbose way, found that there is one image with the missed result and one image with the 2 results. In the same time UI says that all tasks completed.

**Comment by makseq** [comment]
@hsethi2709 thank you very much! 

@johngull Yes, I will add this in the nearest release. But you can use JSON instead of JSON_MIN, it must work with multiple completions. 

![image](https://user-images.githubusercontent.com/501780/85854225-a8af0b00-b7bc-11ea-98f4-204cc14195d8.png)
