### ISSUE TITLE
Can't Hit localhost when running via Docker Compose

### ISSUE THREAD

**Issue by JMcConahie** [heartexlabs/label-studio#3308]
I pulled down the source and attempted to run via docker-compose up command. The container seems to be running fine, but nothing happens when I hit localhost:8080. I've attached the full logs, but I only see two warnings:
`!!! no internal routing support, rebuild with pcre support !!!`
and
`*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***`

Any help would be appreciated.
[Full Log.txt](https://github.com/heartexlabs/label-studio/files/10087508/Full.Log.txt)

**Comment by farioas** [comment]
This is just warning, not exception.
Show the response for `docker ps` command.

**Comment by JMcConahie** [comment]
![image](https://user-images.githubusercontent.com/22197636/204919159-0e85db16-61bd-4047-a315-41bef34e3c52.png)

**Comment by farioas** [comment]
You're running on Windows, that's the problem :) 

There are 2 possible solution:
1. Try to replace localhost with 127.0.0.1, so open your browser and go to `http://127.0.0.1:8080`
2. Find an IP of container and reach it directly:
```
docker inspect -f "{{ .NetworkSettings.Networks.nat.IPAddress }}" labelstudio-nginx-1
```
And go to `http://ip_from_the_step_above:8080`

**Comment by JMcConahie** [comment]
127.0.01 doesn't seem to work. I get <no value> with that docker command.
I tried 
`docker inspect <container_id> | findstr "IPAddress" `
and was able to get a result from that, but when I try to hit that address, it just times out.

**Comment by farioas** [comment]
I see no problems with LabelStudio itself, it's rather configuration issue of your Windows host.
You can open a ticket for Docker Win here: https://github.com/docker/for-win/issues

Closing this ticket, as LabelStudio working fine.

**Comment by JMcConahie** [comment]
So after some digging, I figured out the problem. The ports section of the docker-compose.yml file was mapping port 8080 to 8085. I changed it to map 8080 to port 80 and it started working. Maybe this helps a future windows user.

` - "8080:8085"`

changed to:

` - "8080:80"`

**Comment by farioas** [comment]
That's wrong solution, because 8085 port exposed by nginx and it's required to cache images and django responses:

https://github.com/heartexlabs/label-studio/blob/develop/deploy/default.conf#L93
