### ISSUE TITLE
Can't access static resources and response 404

### ISSUE THREAD

**Issue by Sakura-del** [heartexlabs/label-studio#3316]
I install the label-studio with ubuntu 20.4, and run it with
`python label_studio/manage.py migrate`
`python label_studio/manage.py runserver`
But I can't access static resources and the server response 404 like:
`[2022-11-28 08:12:01,281] [django.server::log_message::161] [WARNING] "GET /static/ HTTP/1.1" 404 1325`
I want to know how to start label-studio locally.
Any help would be appreciated.

**Comment by makseq** [comment]
@Sakura-del sorry, it was outdated docs, please recheck them again:
https://labelstud.io/guide/install.html#Install-from-source

there is a new line 
```
python label_studio/manage.py collectstatic
```
