### ISSUE TITLE
How to modify different class label order of the export yolo format classes.txt ?

### ISSUE THREAD

**Issue by Digital2Slave** [heartexlabs/label-studio#3324]
RT. How to modify different class label order of the export yolo format `classes.txt` ?

for example, the default different class label order for `classes.txt`:

```
clash
crack
crush
```

what i want the different class label order for `classes.txt` is as following:

```
crack
crush
clash
```

**Comment by KonstantinKorotaev** [comment]
Hi @JohnTian 
You need to modify your local version of label-studio-converter [_get_labels method](https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/converter.py#L877). `categories `list contains classes names with indexes - you can modify it to get different order.

**Comment by JohnTian** [comment]
> Hi @JohnTian You need to modify your local version of label-studio-converter [_get_labels method](https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/converter.py#L877). `categories `list contains classes names with indexes - you can modify it to get different order.

Thanks a lot. I will check it later.

**Comment by makseq** [comment]
Related:
https://github.com/heartexlabs/label-studio/issues/3653
https://github.com/heartexlabs/label-studio/issues/3324
https://github.com/heartexlabs/label-studio/issues/2886
https://github.com/heartexlabs/label-studio/issues/1115
https://github.com/heartexlabs/label-studio/issues/737

**Comment by Digital2Slave** [comment]
https://github.com/heartexlabs/label-studio/issues/2886#issuecomment-1238008483

**Comment by TrueWodzu** [comment]
@makseq I am afraid this still does not work (version 1.7.2)

```
<View>
  <Image name="image" value="$image" zoom="true" zoomControl="true"/>
  <RectangleLabels name="label" toName="image">
    
    
  <Label value="person" category="0" background="#0000FF"/><Label value="head" category="1" background="#FF0000"/></RectangleLabels>
</View>
```

But the generated file classes.txt has its content like this:
```
head
person
```

My understanding is that because category=0 is for person, person should be first class in classes.txt file.

**Comment by Digital2Slave** [comment]
@TrueWodzu It work for version 1.7.3 dev
 
![image](https://user-images.githubusercontent.com/7224107/232660158-2de10e99-752d-47a2-a127-d03617570211.png)



![image](https://user-images.githubusercontent.com/7224107/232660037-df2e886a-146b-44f9-a575-41dd6e6aeadd.png)

**Comment by TrueWodzu** [comment]
Perfect, will wait for the official release. Thank you.

**Comment by john-** [comment]
Did this ever work for you?  I am using v1.15.0 and it does not.

It is doing something I just cannot figure what that is or how to get the order I need.

UPDATE:  It looks like the notes.json and labels/*.txt have the correct id number.  Only the classes.txt is incorrect order.  Maybe this can be manually modified as part of workflow.

**Comment by Digital2Slave** [comment]
> Did this ever work for you? I am using v1.15.0 and it does not.
> 
> It is doing something I just cannot figure what that is or how to get the order I need.
> 
> UPDATE: It looks like the notes.json and labels/*.txt have the correct id number. Only the classes.txt is incorrect order. Maybe this can be manually modified as part of workflow.

I am not check v1.15.0. v1.13.1 work for me.

**Comment by brandons209** [comment]
As of v1.16.0 the issue still persists. As @john- mentioned, the label categories are correct and follow what is specified using the `category` tag for each of the labels in the configuration, but the `classes.txt` is not mapped properly, requiring manual fixing. Is there something we are missing or is it a bug?

**Comment by john-** [comment]
In my case I already had plenty of post processing so it was straightforward of to ignore classes.txt and instead use class names/id in notes.json for subsequent steps.  Of course that might not work for you.

I do think it is a bug as I recall the class names in classes.txt sorted by length of the name.
