### ISSUE TITLE
Image Segmentation Multiple Lables

### ISSUE THREAD

**Issue by mcombalia** [heartexlabs/label-studio#333]
I am not able to label the image using the brush with multiple labels. When I switch to the second label, it changes the label of the painted region.

**Comment by makseq** [comment]
You need to unselect the current path first. Press 'u' to do it or button on "Results" panel. 
![image](https://user-images.githubusercontent.com/501780/85851849-26244c80-b7b8-11ea-86d9-68c073dac97c.png)

**Comment by mcombalia** [comment]
Thank you so much! My fault.
