### ISSUE TITLE
which address should I visit with docker compose

### ISSUE THREAD

**Issue by wbz5087** [heartexlabs/label-studio#3338]
I have started the project with docker  compose. All the three containers were running. I didn't change the docker-compose.yml. With lsof -i:8080, the port was used for listening. But I cannot visit http://localhost:8080 or http://ip:8080. So  which address can be used?

**Comment by farioas** [comment]
Please provide more information: OS, docker version

**Comment by wbz5087** [comment]
> Please provide more information: OS, docker version

OS: centos 7.9, docker version: 20.10.21

**Comment by farioas** [comment]
LabelStudio is up and running. The problem somewhere with your network configuration. Probably you have a firewall or network ACL rules so you have to allow connection to port 8080 from 0.0.0.0/0.

Closed the ticket since the issue is not related to LabelStudio itself.
