### ISSUE TITLE
Progress Bar when importing data

### ISSUE THREAD

**Issue by mcombalia** [heartexlabs/label-studio#335]
It would be very nice if we could have a progress bar when we are importing data. With large amounts of data (several images for example) we have no reference if the import process is working.

**Comment by makseq** [comment]
Are you talking about S3/GSC storages or Local storage?

**Comment by mcombalia** [comment]
In this case I am talking specifically of local storage, but I don't know if that is also the case for S3/GSC storage.

**Comment by makseq** [comment]
How many tasks do you try to import? Do you use LS on your local machine?

**Comment by mcombalia** [comment]
I was trying to import 8000 images more or less.

**Comment by makseq** [comment]
Ok. Do you import them as a task json file?

**Comment by mcombalia** [comment]
I was dragging them to the browser window (the image files). At the end I decided to import them as csv and it worksbetter, but I think it would still benefit from a Progress Bar.

**Comment by makseq** [comment]
When you use a lot of images it is better to import them over console at
label studio start:
https://labelstud.io/guide/tasks.html#Directory-with-image-files

**Comment by mcombalia** [comment]
Thanks that was very useful! It worked fine. However, still I think maybe a future feature could be the inclusion of a progress bar.

Thanks :)

**Comment by makseq** [comment]
@mcombalia Can you check importing speed with the last commit in the branch release/0.7.4 ? I hope progress bar is not necessary now.
