### ISSUE TITLE
Documentation for Active Learning

### ISSUE THREAD

**Issue by mcombalia** [heartexlabs/label-studio#336]
Is there any documentation to use this awesome tool for active learning?

Thanks!

**Comment by makseq** [comment]
There are 3 ways to start to use an active learning. 
The fastest are 1 & 2. The most integrated to LS is 3. 

1 import tasks with ready predictions.
2 change <your_project>/tasks.json manually and add/rewrite your prediction manually.
3 add ml backend with your model: https://labelstud.io/guide/ml.html

For 1 & 2: 
The task json has the field "predictions": []. They are the very similar to completions.
You can import your tasks with predictions. Each prediction must have {..., "score": 0.5, ...}.

After you add your predictions to tasks enable the proper sampling in the project config.json (or using console at LS start):
https://labelstud.io/guide/tasks.html?from_search=sampling#Sampling

**Comment by mcombalia** [comment]
This is amazing thank you so much great initiative!

**Comment by makseq** [comment]
@mcombalia Welcome! If you have any questions more open new issues or enjoy our slack :)
