### ISSUE TITLE
Mark on the picture and display it in the text

### ISSUE THREAD

**Issue by tianchiguaixia** [heartexlabs/label-studio#3360]
I would like to ask how I can design labelstudio to mark entities on my uploaded pictures, and automatically display the corresponding entities on my text. final exported ner text

![image](https://user-images.githubusercontent.com/29837553/205428133-abc719f8-8e68-4cd2-af87-f9a6045095c7.png)

**Comment by tianchiguaixia** [comment]
I really hope to get your reply

**Comment by makseq** [comment]
@tianchiguaixia sorry for the long answer. Unfortunately there is not simple way to do it. 

You should [implement your own interactive ML backend](https://labelstud.io/guide/ml_create.html) that will do:
1. As input it should accept 
    * Label Studio task with an **image** url and **text**
    * bounding box drawn by user ([LS interactive mode](https://labelstud.io/guide/ml.html#Get-interactive-preannotations))
3. Run inference for some OCR model and get the **recognized text** from the image + bounding box
4. Scan the input text, find recognized text utterances and make it NER labeling in LS format
5. Return the resulting NER labeling back to LS from your ML model.

**Comment by tianchiguaixia** [comment]
If I lower my requirements, I choose the template of relation extraction, but when labeling, I want to put the corresponding image under the text. How to write this templates, and how to import text data and image data

**Comment by makseq** [comment]
Can you show any example of how it might look?

**Comment by tianchiguaixia** [comment]
![image](https://user-images.githubusercontent.com/29837553/223037536-68064a6c-3e0d-4f24-899c-71c9e673b76d.png)

The red box area shows the image corresponding to this text

**Comment by makseq** [comment]
It should be something [like this](https://labelstud.io/playground?config=%3CView%3E%3Cbr%3E%20%20%3CLabels%20name%3D%22label%22%20toName%3D%22text%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Person%22%20background%3D%22red%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Organization%22%20background%3D%22darkorange%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Fact%22%20background%3D%22orange%22%2F%3E%3Cbr%3E%20%20%3C%2FLabels%3E%3Cbr%3E%20%20%3Cbr%3E%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%2F%3E%3Cbr%3E%20%20%3Cbr%3E%20%20%3CImage%20value%3D%22%24image%22%20name%3D%22image%22%2F%3E%3Cbr%3E%20%3Cbr%3E%3C%2FView%3E%3Cbr%3E%20).
