### ISSUE TITLE
Assigning multiple labels to a single text for NER/COREF Annotation

### ISSUE THREAD

**Issue by Tanmay98** [heartexlabs/label-studio#3365]
**Is your feature request related to a problem? Please describe.**
I am trying to assign multiple entities label to a text for NER and Coreference, for example I want to assign "The Arms Act" to entities: 
  - ACT
  - PROP
  - COREF
  
**Describe the solution you'd like**
Right now if i highlight "ACT" to the required text and then "PROP" then it overwrites the label. Is it possible to assign without overwriting? 

**Describe alternatives you've considered**
Right now I include whitespace or punctuations or some workaround to make the text differentitate.
"The Arms Act"  - ACT
"The Arms Act " - PROP
" The Arms Act" - COREF

**Comment by makseq** [comment]
Add `choice="multiple"` to your Labels tag.
