### ISSUE TITLE
Security Login for Label Studio

### ISSUE THREAD

**Issue by hsethi2709** [heartexlabs/label-studio#338]
I think it will be great to have a security mechanism for entering into the label studio like a simple username and password which we can set during the setup phase or deployment phase. 

I think when we deploy the studio and start using it on a server, it is open on the web and people dealing with sensitive data can have a problem there. It will be great to have an option to enable a login feature for the studio.

**Comment by makseq** [comment]
Added in https://github.com/heartexlabs/label-studio/pull/320

**Comment by makseq** [comment]
@hsethi2709 It will be cool if you check it and write feedback :slightly_smiling_face: 

From new docs: 
```
### Auth with login and password
You can restrict the access for LS instance with the basic HTTP auth.

label-studio start my_labeling_project --username user --password pwd 

Or put `username` and `password` in the project config.json.
{ 
 ...
 "username": "user", 
 "password": "pwd",
 ...
}

It will be the same username and password for all the users.  
```

**Comment by hsethi2709** [comment]
My Apologies! However, I didn't find this anywhere in the published guide ([https://labelstud.io/guide/]). It should be included in the project setup page.

**Comment by makseq** [comment]
We haven't released this feature yet. It's only in PR of release 0.7.3
right now.
