### ISSUE TITLE
MOT16 Type Annotation

### ISSUE THREAD

**Issue by ozayr** [heartexlabs/label-studio#3381]
Hi,

I have been looking for a labelling solution to evaluate an object tracking algorithm that I am developing against a custom data set. Amazingly I cannot find a single tool that can produce labels in MOT16 or the likes format ie where each object has the object id and other usual meta attached.

I would like a tool which allows me to annotate objects as well as assign/correct the object IDs over a video/frame sequence.

I have looked at other open source and paid labelling tools, none allow me to use a model or my detection and tracking model to assist in the labelling as well as correct the id and/or object errors and then save the labels In MOT16 format.

I belive label-studio has the ability to support this easily if it does not already.

**Comment by ozayr** [comment]
I have just seen the new video annotation feature, I also had a thought that if one could add multiple classes to a single image eg the object category as a class and the object id as a class then we might be able to acheive the desired output.

if I use my current model I get back the bounding boxes as well as the object IDs and it works easier then the interpolation feature currently available. specifically I'm using StronSORT to do the tracking. 

The requirement is to allow correct of the IDs as the object detector already does quite a good job at detection.

**Comment by makseq** [comment]
Seems like meta is something you are looking for: 
![image](https://user-images.githubusercontent.com/501780/207224808-f5eba5bb-5d46-45c8-9461-fa9f9e998f65.png)
![image](https://user-images.githubusercontent.com/501780/207224839-030a3b7c-ea38-44a7-be34-f8879c19820a.png)
![image](https://user-images.githubusercontent.com/501780/207224929-fb58f195-f7b7-431f-b1d7-a1ac03221b3e.png)
![image](https://user-images.githubusercontent.com/501780/207224964-5dcaee62-487b-4885-b9e9-fbfc6f7198d2.png)
