### ISSUE TITLE
Error in README for local development

### ISSUE THREAD

**Issue by Lucas-Mc** [heartexlabs/label-studio#339]
**The Bug**
When attempting to clone the repo and start my own project, I encountered an error in the following step:
```
# Start the server at http://localhost:8080
python label-studio/server.py start labeling_project --init
```
After running that snippet of code, I received the following error:
```
/Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'label-studio/server.py': [Errno 2] No such file or directory
```
I believe this is because of an incorrect folder name, so the solution seems to be:
```
# Start the server at http://localhost:8080
python label_studio/server.py start labeling_project --init
```

**Screenshots**
Here is a screenshot of the repo in its current state (note the folder being named `label_studio` instead of `label-studio`:
![Screen Shot 2020-07-01 at 12 36 18 PM](https://user-images.githubusercontent.com/39505798/86269415-b935fb80-bb97-11ea-97bf-9afc53893392.png)
![Screen Shot 2020-07-01 at 12 37 31 PM](https://user-images.githubusercontent.com/39505798/86269426-baffbf00-bb97-11ea-9ed6-b5e60fa064ee.png)

**Comment by makseq** [comment]
You are right! 
Fixed in https://github.com/heartexlabs/label-studio/pull/320.

**Comment by makseq** [comment]
But I think it's not the correct usage of LS. You need to run the following command in the label-studio repo root directory (where the setup.py is placed):
```
pip install -e .
```
and then call it using
```
label-studio start my_project --init 
```
