### ISSUE TITLE
Cannot install label-studio under Python 3.11

### ISSUE THREAD

**Issue by zhimin-z** [heartexlabs/label-studio#3392]
**Describe the bug**
I cannot install label-studio on my local machine.

**To Reproduce**
1. open a cmd terminal
2. Run "pip install -U label-studio"

**Expected behavior**
label-studio is installed

**Screenshots**
<img width="1208" alt="1670474480(1)" src="https://user-images.githubusercontent.com/8592144/206358239-a0c2217e-4f7f-48d3-a3b3-91d25c28e7f7.png">
<img width="1201" alt="1670474501(1)" src="https://user-images.githubusercontent.com/8592144/206358275-0c306a60-337d-476f-9c2c-138d4813dd8f.png">

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python: 3.11.1
 - Pip: 22.3.1
 - Label Studio Version: 1.6.0

**Additional context**

**Comment by makseq** [comment]
Try to use Anaconda python. Your python doesn't have prebuilt binaries for postgres. Or maybe gholke builds will help - https://www.lfd.uci.edu/~gohlke/pythonlibs/ - check Psycopg there.

**Comment by zhimin-z** [comment]
> Try to use Anaconda python. Your python doesn't have prebuilt binaries for postgres. Or maybe gholke builds will help - https://www.lfd.uci.edu/~gohlke/pythonlibs/ - check Psycopg there.

Sorry, I cannot really find the prerequisite to use Anaconda python in your webpage: https://labelstud.io/
Would you mind adding the note in the page lest someone like me cannot install it without Anaconda?

**Comment by zhimin-z** [comment]
> Try to use Anaconda python. Your python doesn't have prebuilt binaries for postgres. Or maybe gholke builds will help - https://www.lfd.uci.edu/~gohlke/pythonlibs/ - check Psycopg there.

How to use this link for me?
