### ISSUE TITLE
Cannot install label-studio using pip

### ISSUE THREAD

**Issue by zhimin-z** [heartexlabs/label-studio#3393]
**Describe the bug**
This is a bug report which extends issue [#3392](https://github.com/heartexlabs/label-studio/issues/3392)

**Additional context**
I am a new user of label-studio but find really frustrated when people suggested that "You need to try Anaconda installation instead" when the two lines of code for pip installation fail:
![image](https://user-images.githubusercontent.com/8592144/206361537-df194c34-547c-4651-804e-5c2b7910c6b7.png)
If this does not work at all, why should we write this way as if it can magically work under any new python release?
My laptop Windows 10 is newly installed and I have only installed python 3.11.1 on it but it still fails automatically.
I did not see any notes on the official website saying you need a prebuilt Postgres/gholke for installation. It is really so, why not make a note or integrate Postgres/gholke installation process into the package?

**Comment by zhimin-z** [comment]
I uninstall Python 3.11.1 and then reinstall Python 3.9.15 instead, and everything fixes automatically without doing anything else. That indeed indicates current label-studio release is incompatible with Python 3.11.1 @makseq

**Comment by makseq** [comment]
We haven't tried LS with python 3.11. LS uses lots of libraries and it doesn't make sense for us support the latest pythons, because all these libraries are not prebuilt for it yet and we can't solve this issue nohow, just wait until other vendors release fully working versions of their libs.
