### ISSUE TITLE
Wrong information in the docs on ml backend

### ISSUE THREAD

**Issue by chorus12** [heartexlabs/label-studio#3396]
The [doc](https://labelstud.io/tutorials/object-detector.html) states that for the GPU support one should provide a parameter `device=gpu:0` - it's incorrect as of version 1.6 - should be `device=cuda:0`
Also there is no information of changing the default port 9090. 
Should be like this `label-studio-ml start coco-detector --port 6006 --with \ ...`

**Comment by makseq** [comment]
Done here - https://github.com/heartexlabs/label-studio/pull/3874/files
