### ISSUE TITLE
Tasks display only "TypeError: n.filter is not a function"

### ISSUE THREAD

**Issue by erickrf** [heartexlabs/label-studio#3404]
**Describe the bug**
When I select any task in my project, it only displays the message `TypeError: n.filter is not a function` as in the picture.

**To Reproduce**
I created a MWE project with the following configuration:

```
<View>
  <Labels name="label" toName="text">
    <Label value="A"/>
    <Label value="B"/>
  </Labels>
  <Text name="text" value="$text"/>
</View>
```

And imported a task with the following json:

```
[
    {
        "data": {
            "text": "This is a test."
        },
        "predictions": [
            {
                "model_version": "2022-10-24",
                "result": [
                    {
                        "value": {
                            "start": 8,
                            "end": 9,
                            "text": "a",
                            "labels": "test"
                        },
                        "from_name": "label",
                        "to_name": "text",
                        "type": "labels"
                    }
                ]
            }
        ]
    }
]
```

**Expected behavior**
I expected the task to be correctly displayed or at least a helpful error message.

**Screenshots**
![Screenshot 2022-12-09 at 11 44 35](https://user-images.githubusercontent.com/294483/206684856-f47b696e-40ff-467c-99e0-ab8a5c6cef37.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Label Studio Version 1.4

**Additional context**
This seems related to https://github.com/heartexlabs/label-studio/issues/1192, but that was supposedly already fixed before 1.4.

**Comment by makseq** [comment]
Try to add "id": "random123" to the dict in prediction.result.

**Comment by erickrf** [comment]
That didn't help, but I then realized that `result.values.labels` must be a list. Still, some better error message would help 🙂
