### ISSUE TITLE
ML backend. Audio regions. Only one region is displayed

### ISSUE THREAD

**Issue by ptJexio** [heartexlabs/label-studio#341]
I am trying to annotate multiclass audio regions using ml backend. For some reason, only one region is displayed.
This is how I fill the return value.

`segments_result.append(
                        {
                            "from_name": self.from_name,
                            "to_name": self.to_name,
                            "type": "labels",
                            "value": {"start": round(segment.start / 1000, 2),
                                      "end": round(segment.end / 1000, 2),
                                      "labels": ["Other"]}
                        }
                    )

results.append({"result": segments_result})`

**Comment by makseq** [comment]
Can you show the final task json?

**Comment by ptJexio** [comment]
This is my mistake. I've returned a list of lists.
Here is the correct version [pastebin](https://pastebin.com/e10VqsU1)

**Comment by makseq** [comment]
Nice! Is this issue resolved?

**Comment by ptJexio** [comment]
Yes, this issue resolved and sorry for bothering you :(
