### ISSUE TITLE
Provide an option to reset the task queue

### ISSUE THREAD

**Issue by WillieMaddox** [heartexlabs/label-studio#3415]
Don't know if this feature exists or not but it would be nice if I could somehow reset the queue so I could go back and annotate skipped tasks or tasks that got arrowed over.

Two possible solutions might be:
 1. Reset (or delete) the skipped/cancelled metadata
 2. Add an option to the `Label XXX Tasks` dropdown to force labeling all checked tasks. See screenshot below.

![Screenshot from 2022-12-12 23-10-46](https://user-images.githubusercontent.com/10588718/207231973-384c0fb7-5375-4db3-84ab-88422addc0cb.png)

**Comment by makseq** [comment]
@WillieMaddox You can filter by cancelled annotations and remove them via data manager actions. Does it work for you?

**Comment by WillieMaddox** [comment]
Yes that works, but I can't delete the cancelled flag on a batch of tasks like I can delete Annotations and Predictions.

It's as if there should be a `Delete Cancelled Flag` option between `Delete Annotations` and `Delete Predictions` in the dropdown shown below.

![image](https://user-images.githubusercontent.com/10588718/208203574-dd043fdd-2946-4cd7-a4ef-6a82b0260195.png)

**Comment by makseq** [comment]
@WillieMaddox Why can't you simply filter by cancelled annotation > 0 and then select all annotations and remove them?

**Comment by WillieMaddox** [comment]
Ok, that did work.  I was associating the purple column (see below) with `Delete Predictions` and *only* the blue column with `Delete Annotations`.

![Screenshot from 2022-12-25 21-11-50](https://user-images.githubusercontent.com/10588718/209495589-96178739-dac2-40ef-8d5d-69c62d461b79.png)

This resolves my issue

**Comment by pmarkun** [comment]
Hi there,

I'm in the need for a similar feature; I've created bounding boxes in all the images and now I changed the Labeling interface so that I can select a specific Choice for each region. It's working flawlessly, but since the Task was already submited I cannot use the Label Tasks interface.

Any ideas? If I delete the Annotation I lose the bounding box.
