### ISSUE TITLE
Tip - how to run the app and keep tasks in sync

### ISSUE THREAD

**Issue by GabrielFerrante** [heartexlabs/label-studio#3456]
A recurring problem that I noticed running Anaconda with LS, is that every time you close the terminal running the program, LS resets the local-storage settings to false.

Therefore, to run correctly every time, you need to set the parameters again and run in the same terminal

LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT= path images

How would you maintain synchronization even after closing the app? When installed using git clone, it's easy to configure directly in settings.py. However, when installed by Anaconda, this modification is not so intuitive.

Thanks !

**Comment by makseq** [comment]
Just write a simple bash script like 

``` run.sh
export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
export LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=<path images>
label-studio 
```
and then run it
```
bash run.sh
```
