### ISSUE TITLE
Export to yolov5 polygon segmentation  

### ISSUE THREAD

**Issue by yangboz** [heartexlabs/label-studio#3457]
**Is your feature request related to a problem? Please describe.**

currently, the export has COCO dataset compatible segmentation option, but after exporting , you need to hand craft the convert staff, based on JSON to YOLO format. code base  here.https://github.com/ultralytics/JSON2YOLO

if possible? a new feature can cover this funs support?   

**Describe the solution you'd like**

a new export option to simply this feature it will help us a lot.

**Describe alternatives you've considered**
manually to convert the exported project . then execute python JSON2YOLO/general_json2yolo.py with debugging.

**Additional context**
any tutorials to contribute this part?

**Comment by makseq** [comment]
@yangboz What kind of segmentation do you mean? PolygonLabels or BrushLabels? 
As I remember yolov4 didn't support segmentations.. does yolov5 do it?

**Comment by yangboz** [comment]
> @yangboz What kind of segmentation do you mean? PolygonLabels or BrushLabels?
> As I remember yolov4 didn't support segmentations.. does yolov5 do it?

semantic segmentation with polygons or should I choose semantic segmentation with Masks?

**Comment by KonstantinKorotaev** [comment]
Hi @yangboz 
Could you please show your labeling config?

**Comment by yangboz** [comment]
> Hi @yangboz
> Could you please show your labeling config?

Currently it is coco segmentation.

**Comment by KonstantinKorotaev** [comment]
> Currently it is coco segmentation.

Do you mean Semantic Segmentation with Polygons?
![image](https://user-images.githubusercontent.com/42615530/211281740-9e4ee579-0362-460a-a566-ee112bea5320.png)

**Comment by yangboz** [comment]
> > Currently it is coco segmentation.
> 
> Do you mean Semantic Segmentation with Polygons? ![image](https://user-images.githubusercontent.com/42615530/211281740-9e4ee579-0362-460a-a566-ee112bea5320.png)

yes, I am wondering  if possible has a YOLO segmentation export option?
thanks.

**Comment by KonstantinKorotaev** [comment]
@yangboz 
What do you mean by YOLO segmentation? 
Could you please show an example?

**Comment by Digital2Slave** [comment]
> 



> @yangboz What do you mean by YOLO segmentation? Could you please show an example?

Relate issue: the dataset formats for yolov5-seg models don't need a lot of points? 

https://github.com/ultralytics/yolov5/issues/10347#issuecomment-1347700359

**Comment by yangboz** [comment]
> @yangboz What kind of segmentation do you mean? PolygonLabels or BrushLabels?
> As I remember yolov4 didn't support segmentations.. does yolov5 do it?

yolov5 did't support either.

**Comment by ryouchinsa** [comment]
RectLabel is an offline image annotation tool for object detection and segmentation.
Although this is not an open source program, with RectLabel you can read/write/export the YOLO segmentation format.
https://rectlabel.com/help#xml_to_yolo
```
class_index x1 y1 x2 y2 x3 y3 ...
0 0.180027 0.287930 0.181324 0.280698 0.183726 0.270573 ...
```
![yolo_polygon](https://user-images.githubusercontent.com/1954306/214472214-a9c2775d-247a-4bd1-87f6-9d90818ef8ff.jpg)

**Comment by yangboz** [comment]
thanks for your information,let me have a try .

**Comment by makseq** [comment]
Relative: https://github.com/heartexlabs/label-studio/issues/3562

**Comment by makseq** [comment]
Added to LS in the latest develop commits, will be delivered in v1.7.2. 
https://github.com/heartexlabs/label-studio/pull/3628

**Comment by kawamucho** [comment]
We RectLabel team apologize that we answered to your issues from your users comparing with our product. 
We removed all comments which did not have any responses from your team.
Currently our comments are only in these 2 issues.
https://github.com/heartexlabs/label-studio/issues/3457
https://github.com/heartexlabs/label-studio/issues/3562

But for these 2 issues, your team added the YOLOv5 segmentation format, so that we believe that we could contribute to your community.
Currently @ryouchinsa is marked a spam account by your team.
Could you turn off the spam setting?
Please let us know your opinion. 

Best regards,
Ryo

**Comment by DimIsaev** [comment]
> @yangboz What kind of segmentation do you mean? PolygonLabels or BrushLabels? As I remember yolov4 didn't support segmentations.. does yolov5 do it?

**YOLOv5 SOTA Realtime Instance Segmentation**
https://github.com/ultralytics/yolov5/releases/v7.0

**Comment by Glaadiss** [comment]
Is it planned to add a similar feature for import (allow importing from yolo to polygon segmentation)?

**Comment by makseq** [comment]
Not yet planned, but it would be a great contribution:
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/imports/yolo.py#L113

**Comment by ODAncona** [comment]
The primary problem lies in exporting the COCO format, which requires the use of polygon labels. If you only have brush labels, the export won't function properly...
