### ISSUE TITLE
Export button does not export filtered tasks

### ISSUE THREAD

**Issue by shayantabatabaee** [heartexlabs/label-studio#3458]
**Is your feature request related to a problem? Please describe.**
I've noticed that if any filter is set in DataManager, the export button export all tasks regardless of filter. So I added an ability to read ids[] from DataManager and send to export service to export only filtered data. However if no filter is set, export button works like before. Also I added `from_creation_date` and `to_creation_date` to export service. This will help people who want to export data with scheduler like daily scheduler. 

**Describe the solution you'd like**
I get ids[] from DataManager and send to export service, so export button only exports filtered tasks

**Comment by makseq** [comment]
Sorry but filters are supported in the export snapshots (you can specify the data manager tab that will be used in the export):
https://labelstud.io/guide/export.html#Export-snapshots-using-the-API
You can use it via SDK or API. Probably we will add GUI for this, right now the GUI available in enterprise only.

**Comment by shayantabatabaee** [comment]
Thank you for your response, so I close the issue and the pr.

**Comment by makseq** [comment]
Thanks for your understanding.
