### ISSUE TITLE
Collaboration efficiency, need local filters to help data manager to assign tasks in a team   

### ISSUE THREAD

**Issue by JimmieWong** [heartexlabs/label-studio#3464]
The current global filter settings will affect other team members and can only be used to quickly find search scenarios.

I plan to assign work to different members by adding local filtering functions, so that each person can get their own tasks from the filtering conditions given by the data manager. **Otherwise, members do not know their task scope or each task will be repeated by different members.**

Is my understanding correct for task assign scenario? Or how does the current community version allocate tasks in the multi person collaboration mode?

**Comment by makseq** [comment]
@JimmieWong If you use Label All Tasks (we call it `Label Stream` mode), Label Studio automatically distributes all tasks across all projects with overlap = 1. So, only 1 annotation will be completed per 1 task by 1 annotator.

**Comment by JimmieWong** [comment]
@makseq how can I assign tasks to multiple members in the community version? same question.

**Comment by makseq** [comment]
The default overlap in community version is 1 annotation per task. Tasks will be assigned automatically if you use Label All Tasks.
