### ISSUE TITLE
Skip behaves differently than expected

### ISSUE THREAD

**Issue by RasmusEdvardsen** [heartexlabs/label-studio#347]
**Is your feature request related to a problem? Please describe.**
I expect "Skip" to not complete the specific task.

**Describe the solution you'd like**
I would like to just go to the next task, with no change to the previous task, when pressing "Skip"

**Describe alternatives you've considered**
Adding a third option for doing what I expect "Skip" to do instead.

**Comment by makseq** [comment]
Have you checked LS 0.7.3 release branch?

**Comment by RasmusEdvardsen** [comment]
No, sadly I still get the getaddrinfo bug from #346 when running it.

Regardless, upon further thought I can tell this will be quite an extensive change.

What I would think would happen is that when I click skip, that task is untouched (not completed), and I continue to the next in the sequence. When I am done, I will only get the non skipped completions exported, and I can then go back and continue labelling.

This seems messy for sequential labelling, but for random task picking, this would work well.

Do you agree with this, or am I wrong in my reasoning?

**Comment by makseq** [comment]
In the current realization: 

1 Skipped completions are not shown in the labeling stream 

2 If you need to resolve the skipped completion you can order completions by skipped column in Tasks and go to label manually by the eye icon 
![image](https://user-images.githubusercontent.com/501780/86911075-59a19800-c123-11ea-87ae-80354e108181.png)

3 At export you will have skipped completions included inside, but they have "skipped": true flag.

**Comment by RasmusEdvardsen** [comment]
This makes sense, I will close this and await 0.7.3 - thanks 😄

**Comment by makseq** [comment]
Note: when you press "Skip" in labeling - the completion is skipped. If you press Update - the skipped completion will be resumed to regular submitted completion.

**Comment by RasmusEdvardsen** [comment]
Yea, and again, that definitely behaves as it should - because you update the task, the state should change appropriately 👍
