### ISSUE TITLE
What is the best practice for stopping label studio?

### ISSUE THREAD

**Issue by b-niu** [heartexlabs/label-studio#3474]
Dear contributors, I use Docker Desktop to run label studio in the Windows 10 WSL2 environment.
Can you tell me what is the best practice for closing label studio? I checked the documents and found no relevant content.
At present, I close the Docker container directly by clicking the Stop button. I wonder if there is any harm in doing so?

![image](https://user-images.githubusercontent.com/32410912/209089447-ff65d90e-ac27-4312-ad04-944ee33346cf.png)

**Comment by nikitabelonogov** [comment]
Hi @b-niu 
yes, that is ok 
But make sure you are following https://labelstud.io/guide/storedata.html#Persist-data-with-Docker to not to lose your data accidentally
