### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jingsongliujing** [heartexlabs/label-studio#3488]
Hi,I have successfully installed, but use the command: label studio
The following error occurred:
![image](https://user-images.githubusercontent.com/45508593/209490547-1f90116b-e50c-49f8-acce-44325a4a57f1.png)
![image](https://user-images.githubusercontent.com/45508593/209490600-b9a01b1c-6e0d-4059-ae93-3f619260a9f1.png)

**Comment by makseq** [comment]
Please use virtual environments like venv or conda. 
https://docs.python.org/3/library/venv.html
