### ISSUE TITLE
Saving annotations performance

### ISSUE THREAD

**Issue by paulakeen** [heartexlabs/label-studio#349]
I get frustrated when saving my annotations, it take a certain amount of time that, added to the time of annotating, is quite boring/desperating.

Can't you reduce the time it takes to save?

**Comment by deppp** [comment]
Hey @paulakeen 

Would be great to get more details about that. What type of labeling do you perform and what how many regions do you create before saving? Thanks!

**Comment by paulakeen** [comment]
I need to apologise about my comment. I’m reaching the conclusion that the problems lies in my machine, not in your design/development.  Still checking.

**Comment by makseq** [comment]
Ok! We are waiting for your checks.
