### ISSUE TITLE
Installing label studio and label studio ml leads to version conflict

### ISSUE THREAD

**Issue by mbspng** [heartexlabs/label-studio#3499]
**Describe the bug**

Installing label studio and label studio ml leads to version conflict. According to docu, both packages are required for running ml backend. (https://labelstud.io/guide/ml_create.html)

```
Because no versions of label-studio match >1.7.0,<2.0.0
 and label-studio (1.7.0) depends on label-studio-converter (0.0.48rc0), label-studio (>=1.7.0,<2.0.0) requires label-studio-converter (0.0.48rc0).
And because label-studio-converter (0.0.48rc0) depends on label-studio-tools (0.0.1), label-studio (>=1.7.0,<2.0.0) requires label-studio-tools (0.0.1).
And because label-studio-ml (1.0.8) depends on label-studio-tools (0.0.0.dev11)
 and no versions of label-studio-ml match >1.0.8,<2.0.0, label-studio (>=1.7.0,<2.0.0) is incompatible with label-studio-ml (>=1.0.8,<2.0.0).
So, because <my module> depends on both label-studio-ml (^1.0.8) and label-studio (^1.7.0), version solving failed.
```

**To Reproduce**
`poetry add label-studio-ml`
`poetry add label-studio`

**Expected behavior**
Modules should be compatible.

**Environment (please complete the following information):**
 - OS: Linux
 - label-studio-ml (1.0.8)

**Comment by KonstantinKorotaev** [comment]
Hi @mbspng 
Could you please update label-studio-ml to 1.0.9 and try one more time?

**Comment by makseq** [comment]
Closed as unanswered.
