### ISSUE TITLE
Pass an argument to api_generate_next_task

### ISSUE THREAD

**Issue by Rusteam** [heartexlabs/label-studio#35]
Hi there,

Great tool.

I'm currently writing a plugin for daily human-in-the-loop computer vision task. 
I added Image_classification to examples and write results to a database.

However I struggle to find how to pass an argument to a `api_generate_next_task` because I can't find where it is called. I know for sure it is called from index page when `task_id is None`. Also, I need to pass this argument to a next image when clicking submit. 

P.S. The reason I need this argument is that my images are split by dates and I need to label them separately.

**Comment by makseq** [comment]
@Rusteam Are you talking about where it's called from JavaScript?

**Comment by Rusteam** [comment]
I see, thanks.

However, I'm not familiar with JS at all. 
Solved temporarily with `global` variable in server.py.

Thanks again!
