### ISSUE TITLE
KeyPointLabels tag color conflict with Label tag

### ISSUE THREAD

**Issue by aderwinwg** [heartexlabs/label-studio#3501]
**Describe the bug**
color conflict when using "KeyPointLabels" tag and "Label" tag

**To Reproduce**
1. Go to Settings --> Labeling Interface
2. Use the following labeling configuration as an example:     
```
<View>
  <KeyPointLabels name="highest point" toName="img-1" strokeWidth="20" stokeColor="yellow" fillColor="black">
    <Label value="Face" />
  </KeyPointLabels>
  <KeyPoint name="highest point1" toName="img-1" strokeWidth="10" fillColor="black" strokeColor="yellow"/>
  <Image name="img-1" value="$img" />
</View>
```

3. "KeyPoint" tag show color with expected result but "KeyPointLabels" tag resulted in color not functioning
4. "Label" tag and "KeyPointLabels" is treated as independent

**Expected behavior**
Label tag color customizable for point labeling 

**Screenshots**
![image_2022_12_30T03_14_52_831Z](https://user-images.githubusercontent.com/109452770/210032578-85595847-5d12-430d-a5af-0da42f22da54.png)
![image_2022_12_30T03_15_04_136Z](https://user-images.githubusercontent.com/109452770/210032600-a8a50f39-412f-4ae6-a9f5-a5a3b6cceff4.png)
KeyPoint and KeyPointLabels same parameter for color pointer but It doesn't work on KeyPointLabels 
![image_2022_12_30T03_19_00_914Z](https://user-images.githubusercontent.com/109452770/210032652-ad08a571-144f-40aa-88aa-2fdf29fe14b5.png)

**Comment by hlomzik** [comment]
Thank you for pointing this out!
These parameters were not used, I [removed them from docs](https://github.com/heartexlabs/label-studio-frontend/pull/1139). (also there was a typo)

`*Labels` tags use colors from respective `Label` and they always have a color either set by `background` parameter or automatically assigned. So in your case you can use `<Label value="Face" background="yellow" />`, but currently it allows you to set only one color for `KeyPoint`.

Also try to use just a separate `Labels` tag along with `KeyPoint` tag — that allows you to create generic key points and assign labels to them if needed. To fix empty hole inside them use `opacity="0.9"` in `Labels` tag.

Later we'll go through all the parameters and make some improvements and unifications.
