### ISSUE TITLE
Converting from LabelStudio JSON Format to YOLO 

### ISSUE THREAD

**Issue by TimbusCalin** [heartexlabs/label-studio#3502]
Hello,

I tried downloading all the images&annotations from LabelStudio but looking at : https://github.com/heartexlabs/label-studio/issues/3212 I understand why this is a problem. I have 2000 images with their corresponding annotations and every time I try to use the export function, randomly between 300-400 images and 600-700 annotations are being downloaded.

To still solve this issue, I exported the dataset using the "JSON" export type (Label Studio Common Format).

However, I am having a hard time understanding the LabelStudio JSON format and how to convert it to YOLO.

In : https://labelstud.io/guide/export.html I can see how to convert from JSON format to "pixel", but I thought that would give me the absolute coordinates, which it doesn't.

How to convert from JSON to YOLO given that I only have the labels and (to the best of my knowledge) label studio converter scripts need a configuration file and the source image data as folder? (remember I only have the .JSON annotation).

Thanks in advance!

PS:

I started actually to use these two lines of code in order to do the parsing (lines 676-678) from converter.py (convert_to_yolo function) from label_studio_converter, but I am not sure this is the only thing that needs to be done:

              if "rectanglelabels" in label or 'labels' in label:
                        x, y, w, h = self.rotated_rectangle(label)
                        annotations.append([category_id, (x + w / 2) / 100, (y + h / 2) / 100, w / 100, h / 100])

**Comment by TimbusCalin** [comment]
Thank you @makseq . Unfortunately the server I am working is not locally (I cannot restart it since multiple projects are under way nor is it Enterprise Edition as far as I can infer). I managed to workaround that, downloaded the .JSON annotation in LS format, adapted the code like specified above and created a mapping between the local name of the images and their name on LS.

**Comment by makseq** [comment]
Did you try snapshot API ?

**Comment by TimbusCalin** [comment]
Thank you @makseq . I will try the Snapshot soon. According to the docs, I can see Snapshot feature is available in the Enterprise Edition, which the current setup doesn't benefit from.

PS: I just checked now, the UI doesn't provide me with the snapshot option, only several COCO/YOLO/JSON/JSONMIN options. It's also important to note that the current version of LS is 1.4.0.

**Comment by makseq** [comment]
Snapshot API is available everywhere.

**Comment by TimbusCalin** [comment]
I bet it is, probably it's an older version (1.4.0) and it doesn't show up. The only EXPORT options in my case are these ones.
![example](https://user-images.githubusercontent.com/23454613/210802081-9bff28ae-851a-46c5-92c8-61194d7820ae.jpg)

**Comment by makseq** [comment]
>  I try to use the export function, randomly between 300-400 images and 600-700 annotations are being downloaded

how does it look? you got zip file and there are only 300-400 images inside?

**Comment by TimbusCalin** [comment]
> > I try to use the export function, randomly between 300-400 images and 600-700 annotations are being downloaded
> 
> how does it look? you got zip file and there is only 300-400 images are inside?

Exactly,  300-400 images inside and more annotations (my hunch is that's easier to zip the .txt prior to timeout issue).

**Comment by makseq** [comment]
You can try to use export_snapshots_create with filter from 0 to 300th image:
https://labelstud.io/sdk/project.html#label_studio_sdk.project.Project.export_snapshot_create
then from 300 to 600th, 
etc.
