### ISSUE TITLE
sqlite3.OperationalError: attempt to write a readonly database

### ISSUE THREAD

**Issue by gauravjadhav-1997** [heartexlabs/label-studio#3505]
After updating label-studio to latest version(1.7), When I am restarting  label-studio with docker , I am always getting this error
![error1](https://user-images.githubusercontent.com/121705773/210125521-93698038-9da4-49ca-a6b7-ebfb4b432337.PNG)

**Comment by farioas** [comment]
Please check section `Breaking changes` in Release Notes for 1.7.0:
https://github.com/heartexlabs/label-studio/releases/tag/1.7.0

**Comment by makseq** [comment]
=> 
**Breaking changes**
Starting with this release, the application will run using a non-root docker user with ID 1001.

If you encounter any permission issues when running the application in a docker container, you can fix them by changing the ownership of the relevant files and directories to 1001.

```
docker run -it --user root -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:1.7.0 chown -R 1001:root /label-studio/data/
```
