### ISSUE TITLE
How to associate images annotated in other software with lable, and then implement re annotation

### ISSUE THREAD

**Issue by KingBoomBoom** [heartexlabs/label-studio#3506]
How to associate images annotated in other software with lable, and then implement re annotation

![image](https://user-images.githubusercontent.com/52889218/210319696-0adc4372-f6b7-4432-af59-b7e028c5b75a.png) to 
![image](https://user-images.githubusercontent.com/52889218/210319837-c6e1a0b8-f637-432b-bd7e-ca0e0a44f7c6.png)

**Comment by makseq** [comment]
Seems you should use this OCR template: 
https://labelstud.io/templates/optical_character_recognition.html

And also check how to import pre-annotations:
https://labelstud.io/guide/predictions.html#Import-OCR-pre-annotations

Probably, you need to implement the converter from your label format to Label Studio JSON format.
