### ISSUE TITLE
Show labels inside the regions of bouding boxes

### ISSUE THREAD

**Issue by g0lemXIV** [heartexlabs/label-studio#3507]
I've searched through documentation and GitHub issues but have yet to find a similar question and answer. Can the bounding box labels be shown on the image for the object detection task? We currently have multiple objects with pre-annotations; the problem is that colours start to blend, and it is hard for annotators to distinguish between classes of objects even if the opacity for RectangleLabels is set to 0.8/0.9. 

Many thanks for your response!

**Comment by makseq** [comment]
You should go to Label Studio Frontend settings by clicking this button:
![image](https://user-images.githubusercontent.com/501780/211697190-77a40a20-07ef-4b42-845b-98138a8ce4f8.png)

and then use the following checkbox:
![image](https://user-images.githubusercontent.com/501780/211697106-82d563be-0ecf-4d57-bb76-849df0301e32.png)

**Comment by g0lemXIV** [comment]
@makseq I didn't come up with it... Thank you!

**Comment by makseq** [comment]
@anithamuthu2022 I would add this into our documentation 
somewhere here - https://labelstud.io/guide/labeling.html#Customize-the-labeling-interface
