### ISSUE TITLE
Selected brush regions are unselected when changing tools

### ISSUE THREAD

**Issue by cameronbronstein** [heartexlabs/label-studio#3510]
**Describe the bug**
When working with Brush Labels, the region/layer selection does not persist when toggling between tools like brush, erase, pan, etc. This makes it difficult to annotate, because each change to the tool requires an extra manual step to re-select the layer/region I was previously working with.

This seems to be a new behavior since 1.6.0, and is also present in 1.7.0. In version 1.5.0, this was not the behavior, though appear to be several changes to the brush regions since 1.5.0.

**To Reproduce**
1. Set up a project with Brush Labels
2. Start labeling part of the image
3. Change the tool (e.g. brush to pan, brush to erase, then back to brush)
4. See error - a new region will be created or the region selection will not persist with the change of tool.

**Expected behavior**
The layer selection persists regardless of what tool is being used, or if the tool is changed. Layers should only be deselected if:
- the annotation is updated
- another layer is selected by clicking
- the layer is manually unselected (another click, or esc)

**Screen Recording**
Google drive file (too big for github): https://drive.google.com/file/d/1ST2QkjMMQnTb8ovkH8tWJPYGqvB1414x/view?usp=sharing

**Environment (please complete the following information):**
- OS: hosted on Linux VM, viewing on MacOS/Chrome.
- Label Studio Version: 1.7.0

**Comment by makseq** [comment]
@cameronbronstein Could you run LS with this env variable: 
```
ff_front_1170_outliner_030222_short=false label-studio
```
and check the brush behaviour again?

**Comment by cameronbronstein** [comment]
@makseq I tried that out and noticed that the frontend changed back to the older style, with regions/layers appearing on the right of the images.
![Screen Shot 2023-01-11 at 9 47 20 AM](https://user-images.githubusercontent.com/44240251/211880130-778cf529-5461-498e-ac34-da5c0ad6702f.png)

However, the brush behavior is similar. I select a layer first and then select the brush tool, the layer is immediately unselected. I can toggle from brush to erase or brush to pan while maintaining selection. So it seems that selecting the brush tool is paired with region deselection.

**Comment by BradNeuberg** [comment]
Broken:
* Select the Brush tool, draw a brush, pan, then draw the brush again - Brush tool incorrectly adds a new region when it should have collapsed into existing region.
* Select the Brush tool, draw a brush, erase, then draw the brush again - Same, breaks and adds a new brush region
* Select a class, do the magic wand, then do brush, then do magic wand (this correctly stacks with the older magic wand), then do the brush again - brush incorrectly does not stack with earlier brush region.

My plan is to address these three problems, as well as add integration tests to prevent this from regressing again.
