### ISSUE TITLE
Checking the annotated audio waveform

### ISSUE THREAD

**Issue by Ayush-TCIN** [heartexlabs/label-studio#3511]
I am performing audio data labeling task for **Speaker Diarization** (who spoke when) where the annotation includes labeling the speaker corresponding to a particular segment of audio.   
<img width="837" alt="Screenshot 2023-01-04 at 10 25 30 AM" src="https://user-images.githubusercontent.com/78065003/210487109-d31a2c2f-e031-44f6-8a97-debea50a6691.png">

We are following _maker and checker_ concept for data annotation. Somebody has already annotated the data, thus I want to upload both audio waveform and annotation file (`.csv`) simultaneously in order to perform the labeling check operation.   
Is it possible in `Label Studio` to upload the files mentioned above and obtain the annotated regions over waveform for checking and editing purposes? Once done I will push the changes to `PostgreSQL` for further downstream ops.   
Kindly guide me on how can I achieve the objective.  

PS: If some other format for annotated information is required then I will convert it to the required one.

**Comment by makseq** [comment]
Seems like you need to use pre-annotations:
https://labelstud.io/guide/predictions.html#Format-pre-annotations-for-Label-Studio
