### ISSUE TITLE
Allow me to easily paint over ambigious areas in images

### ISSUE THREAD

**Issue by CySlider** [heartexlabs/label-studio#3516]
**Is your feature request related to a problem? Please describe.**
Sometimes an image has great training examples, but also some ambiguous ones, where not even I am sure, if this should be a detection or not. I would like an easy way to exclude this area from the training data

**Describe the solution you'd like**
I would like to be able to quickly draw a black box over parts of the image that will actually alter the image data on export, so that the area in that image is blackened

**Describe alternatives you've considered**
Alternatively I have to load this specific image into an image editing tool, do this there, then re-import it. But this is cumbersome

**Comment by makseq** [comment]
Seems like you should add [RectangleLabels](https://labelstud.io/tags/rectanglelabels.html) to your labeling config and use them as"black box over parts of the image".
