### ISSUE TITLE
Navigating backwards and forwards between completed tasks

### ISSUE THREAD

**Issue by paulakeen** [heartexlabs/label-studio#352]
**Is your feature request related to a problem? Please describe.**

If I want to go back to a task and complete it or correct it, I don’t see the way, except going to the Tasks list, but that is very time consuming.

**Describe the solution you'd like**

Below the annotation window, i’d like to see a previous button that brings me back to previous task and I could see what I’ve done and correct it. Specially If I enter a task from the Tasks list menu.

**Describe alternatives you've considered**
A way of specfying a “range” of tasks (completions?) that i could re-edit.

**Additional context**
None.

**Comment by makseq** [comment]
Have you checked 0.7.3 release? There are prev/next buttons in the labeling mode.

**Comment by makseq** [comment]
@paulakeen
