### ISSUE TITLE
Validation Error for Local files data upload

### ISSUE THREAD

**Issue by Ayush-TCIN** [heartexlabs/label-studio#3521]
I am trying to load the audio data from local file system. Thus, checked on LS > Settings > Cloud Storage > Local files for instructions.
I referred to document [this](https://labelstud.io/guide/start.html#Set-environment-variables) and [this](https://labelstud.io/guide/storage.html#Local-storage) for setting up the environment variables and entering the data root.

Despite of me entering the correct data path and file formats, I am getting Validation error. Can you please guide me on how to make it right?

OS: MacOS
LS version: 1.7.0
Environment variables:
      1. `$ export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true`
      2. `$ export LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/Users/abc/Downloads/custom_data/`

<img width="582" alt="Screenshot 2023-01-06 at 11 48 48 AM" src="https://user-images.githubusercontent.com/78065003/210942162-85ca2794-57c1-4bb9-858b-b1721140ea35.png">

**Comment by Ayush-TCIN** [comment]
@makseq Kindly have a look

**Comment by makseq** [comment]
What type of LS deployment do you have? pip install? or docker? 
Are you 100% sure this path is existing?

**Comment by makseq** [comment]
Closed as unanswered.
