### ISSUE TITLE
Documentation missing: Accessing (Azure blob storage) files from task

### ISSUE THREAD

**Issue by mbspng** [heartexlabs/label-studio#3523]
I connected an Azure blob storage via the SDK. I can sync the data via the SDK as well:

```python
    response = project.connect_azure_import_storage(
        **load_config(AZURE_STORAGE_CONFIG)["import"], **load_config(AZURE_STORAGE_CREDENTIALS_FILE)
    )
    client.sync_storage(*itemgetter("type", "id")(response))
```
Works fine. When I implement a derived class for `label_studio_ml.model.LabelStudioMLBase` the path to the image under `task["data"]["image"]` to run pre-labelig on has a prefix of `"azure-blob://<path/on/storage>"`. I spent 4 days now trying to figure out how I can access the file under "path/on/storage". Of course, I could download it AGAIN via the azure blob-storage SDK. But obviously it has already been downloaded, because the image is displayed in the label studio browser UI after syncing the storage.

```python
class Labeler(LabelStudioMLBase):
    ...

    def predict(self, tasks, **kwargs):
        predictions = []
        for task in tasks:
            logger.trace("task:\n" + json.dumps(task, indent=2))
            path = task["data"][self.value]  # will be "azure-blob://<path/on/storage>"
            ...
```

So, how do I get the locally stored image under `path`? Documentation does not mention this at all! Or it is really well hidden!

I also looked through examples like these:

https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/pytorch_transfer_learning/pytorch_transfer_learning.py
https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/examples/tesseract/tesseract.py

Did not help answer this either.

**Comment by makseq** [comment]
https://labelstud.io/guide/export.html#Accessing-task-data-outside-of-Label-Studio-instance
Does this docs section help?

**Comment by wadhah101** [comment]
Did you find any solution ? Suffering from the same problem

**Comment by mbspng** [comment]
@wadhah101 No, I ended up with the manual re-download.

**Comment by makseq** [comment]
@mbspng @wadhah101 

> But obviously it has already been downloaded, because the image is displayed in the label studio browser UI after syncing the storage.

It's not true. LS doesn't touch user data by security reasons. LS requests your storage to create pre-sign https urls only, they are loaded by your browser and the LS backend stores nothing on the disk. 

So, there is only one way - to download resources using Azure SDK in your ML backend.

**Comment by mbspng** [comment]
@makseq  How does that make sense? I can see the images in the browser. And THEN I am re-downloading them. So they HAVE to be on my machine somewhere already.

**Comment by makseq** [comment]
@mbspng Check image links in your browser - they are from azure servers directly.
