### ISSUE TITLE
Large images don't render in Chrome

### ISSUE THREAD

**Issue by khazit** [heartexlabs/label-studio#354]
**Describe the bug**
Large images (in this case 20000 x 20000) don't render in Chrome, but they do in Edge.
I don't know if it's an issue on the browser side or on LS side, but maybe this behavior should be documented somewhere as I spent quit a bit of time thinking that something was wrong with my configuration.

**To Reproduce**
Import large images

**Expected behavior**
Images should render on both browsers

**Screenshots**
![chrome](https://user-images.githubusercontent.com/43420058/87284800-136b8080-c4f7-11ea-9ead-52c5c3a3494b.png)
Using Google Chrome

![edge](https://user-images.githubusercontent.com/43420058/87284850-20886f80-c4f7-11ea-8c21-014b43e963f6.png)
Using Edge

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Edge
 - Version: Chrome 83

**Comment by makseq** [comment]
Can you send us any huge image which has this behavior?
But it seems the problem is in browser.

**Comment by khazit** [comment]
You're right @makseq. It was an image format problem, not related to the size : Chrome doesn't support TIFF. https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

Thanks for you help ! I'm closing this issue.
