### ISSUE TITLE
Enable zoom for Speaker segmentation task

### ISSUE THREAD

**Issue by Ayush-TCIN** [heartexlabs/label-studio#3543]
I am performing Speaker segmentation task in Label Studio (LS) for audio data. The demo as presented [here](https://labelstud.io/templates/speaker_segmentation.html) shows that we can zoom the audio waveform in x-axis i.e. time axis as well. But even when I copied the same configuration to my use case, the feature does not work. The audio clips I am dealing with are more than 10mins long; when loaded to LS the waveform looks very dense making the annotation virtually impossible and also making (time/ x-axis) zoom a must have feature for my use case.

Here are my configurations:
```
<View>
  <Labels name="label" toName="audio" zoom="true" hotkey="ctrl+enter">
    
    
  <Label value="spk_0" background="#0eb4f1"/>
  <Label value="spk_1" background="#D4380D"/>
  <Label value="spk_2" background="#aef12b"/>
  <Label value="spk_3" background="#7f1ac3"/>
  </Labels>
  
  <Audio name="audio" value="$audio"/>
  
 
  <Header value="Confirmation"></Header>
  <Text name="text" value="Are the annotations reviewed?"></Text>
  <Choices name="choices" toName="text" choice="single" showInLine="true">
    <Choice value="Yes" />
    <Choice value="No" />
    <Choice value="Pending" />
  </Choices>
</View>
```

I also tried using `AudioPlus` tag ([link](https://labelstud.io/tags/audioplus.html)) instead of `Audio` but the issue still persists.  
 Attaching UI Preview for reference.

<img width="585" alt="Screenshot 2023-01-11 at 4 19 54 PM" src="https://user-images.githubusercontent.com/78065003/211787517-78b93e8e-fe43-4c4a-bdef-e76b1fae5f3a.png">

OS: MacOS
LS version: `1.7.0`

Is there anything I am missing out to bring the zooming feature for audio waveform? Kindly guide me on this.

**Comment by Ayush-TCIN** [comment]
@makseq kindly help!

**Comment by bmartel** [comment]
Hey @Ayush-TCIN 👋. Zoom in the x-axis is controlled by either cmd + scroll wheel (if using mac os and a mouse), ctrl + scroll wheel (if using windows, or linux and a mouse). If using a laptop with a multitouch trackpad you can also pinch to zoom as well. Hopefully that works for you, let me know if it doesn't.

**Comment by Ayush-TCIN** [comment]
Yes, it worked! 
Thanks @bmartel
