### ISSUE TITLE
Pass filter to PrepareParams

### ISSUE THREAD

**Issue by Developertexteditor** [heartexlabs/label-studio#3554]
Hello there! 

I'm using your product which is great, but I'm trying to add some functionality that meets my requests. 
I'm trying to filter annotations from Task so it will only show the annotations being made for the past 7 days.
I figured out that the needed QuerySet is being prepared here:
```
return self.prefetch(
            Task.prepared.get_queryset(
                prepare_params=PrepareParams(project=project, selectedItems=selected, request=self.request),
                **kwargs
            ))
```
But I can't figure out or google anything on how to pass the filter to this class:

```
class PrepareParams(BaseModel):
    project: int
    ordering: List[str] = []
    selectedItems: Optional[SelectedItems] = None
    filters: Optional[Filters] = None
    data: Optional[dict] = None
    request: Optional[Any] = None
```

Could you please provide an example how to pass filter to PrepareParams in the correct way? 
Thanks in advance, sorry if the question is dumb tho

**Comment by makseq** [comment]
@Developertexteditor it's unclear your final goal. Do you want to calculate how many annotation were made in some time range? Or you want to exclude all other annotations from data manager and quickview? Or something else. 

Anyway you should know that data manager filters work with Tasks only and Annotations are considered as JOINs. It means that 
=> if one task has two annotations and 
.  => the first annotation satisfies by the filter condition, 
.  => but the second annotation doesn't,
=> anyway this task will be returned and these two annotations will be taken into account and calculated together. 

However, maybe it's not so important for community LS, because in most cases there is only 1 annotation per 1 task. And it means you simply & most likely can use Completed filter for your request: 

![image](https://user-images.githubusercontent.com/501780/212227364-eea1b8c0-6bfc-4308-a131-9e88b0872722.png)

**Comment by Developertexteditor** [comment]
First of all, thank you for such a quick response, I appreciate!

>However, maybe it's not so important for community LS, because in most cases there is only 1 annotation per 1 task. And it means you simply & most likely can use Completed filter for your request:

Yes, community LS has only 1 annotation per 1 task by default but since my project is not in the state yet when we can afford enterprise version (had a call with your sales and the cheapest option was way out of budget) I decided to make some changes by my own so it can cover my minimum needs for now until we can afford enterprise, and more than one annotations per 1 task is one of them. 

>Or you want to exclude all other annotations from data manager and quickview?

Yes, that's what I actually trying to do. My annotators going to create semantic segmentations on images and I will take average of them as a result. But since there will be around 10 annotations per 1 task I want to only display those that were made for the past 7 days (and also hide those that were made by me from the total pool actually). 

>Anyway you should know that data manager filters work with Tasks only and Annotations are considered as JOINs. It means that
=> if one task has two annotations and
. => the first annotation satisfies by the filter condition,
. => but the second annotation doesn't,
=> anyway this task will be returned and these two annotations will be taken into account and calculated together.

That's a nice catch, thank you. I dive deep in the QuerySet and it has this SQL statement inside:
```
SELECT task.id, task.data, task.meta, task.project_id, task.created_at, task.updated_at, task.updated_by_id, task.is_labeled, task.overlap, task.file_upload_id, task.inner_id, 
task.total_annotations, task.cancelled_annotations, task.total_predictions, task.comment_count, task.unresolved_comment_count, task.last_comment_updated_at, 
AVG(task_completion.lead_time) AS avg_lead_time, 
CASE WHEN task.is_labeled THEN (SELECT U0.created_at FROM task_completion U0 WHERE U0.task_id = task.id ORDER BY U0.id DESC LIMIT 1) ELSE NULL END AS completed_at,
COALESCE(GROUP_CONCAT(task_completion.result), "") AS annotations_results,
COALESCE(GROUP_CONCAT(prediction.result), "") AS predictions_results, 
GROUP_CONCAT(prediction.model_version) AS predictions_model_versions,
GROUP_CONCAT((SELECT completed_by_id FROM task_completion WHERE task_completion.task_id = task.id AND task_completion.completed_by_id = 2)) AS annotators,
/*COALESCE(GROUP_CONCAT(task_completion.completed_by_id), "") FILTER (WHERE task_completion.completed_by_id = 2) AS annotators,*/
GROUP_CONCAT(task_completion.id) AS annotations_ids,
data_import_fileupload.file AS file_upload_field FROM task
LEFT OUTER JOIN task_completion ON (task.id = task_completion.task_id)
LEFT OUTER JOIN prediction ON (task.id = prediction.task_id)
LEFT OUTER JOIN data_import_fileupload ON (task.file_upload_id = data_import_fileupload.id)
WHERE (task.project_id = 6 AND task.id IN (20))
GROUP BY task.id, task.data, task.meta, task.project_id, task.created_at, task.updated_at, task.updated_by_id, task.is_labeled, task.overlap, task.file_upload_id, task.inner_id, task.total_annotations, task.cancelled_annotations, task.total_predictions, task.comment_count, task.unresolved_comment_count, task.last_comment_updated_at,
CASE WHEN task.is_labeled THEN (SELECT U0.created_at FROM task_completion U0 WHERE U0.task_id = task.id ORDER BY U0.id DESC LIMIT 1) ELSE NULL END, 
data_import_fileupload.file ORDER BY task.id ASC
```

So I thought that some kind of filtering in these places going to help with my problem:
```
COALESCE(GROUP_CONCAT(task_completion.result), "") AS annotations_results,
GROUP_CONCAT((SELECT completed_by_id FROM task_completion WHERE task_completion.task_id = task.id AND task_completion.completed_by_id = 2)) AS annotators,
```

But I can't figure out how to make it using query_set in your project

**Comment by Developertexteditor** [comment]
I guess I forgot to tag you back in my answer @makseq

**Comment by makseq** [comment]
> I want to only display those that were made for the past 7 days

Filters won't help you. You need to change task serializers:
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/data_manager/serializers.py#L164
