### ISSUE TITLE
Label studio does not create account when hosted via wsgi 

### ISSUE THREAD

**Issue by fvdnabee** [heartexlabs/label-studio#3557]
**Describe the bug**
When hosting label studio using the official docker image (`heartexlabs/label-studio:1.7.0`) via wsgi, a default user is not created despite setting `LABEL_STUDIO_USERNAME` and `LABEL_STUDIO_PASSWORD` as documented under [Restrict signup for cloud deployments](https://labelstud.io/guide/signup.html#Restrict-signup-for-cloud-deployments).

**To Reproduce**
Reproduce via docker compose:
1. Apply the following patch to docker-compose.yml:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index a41437c3..77562e2f 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -25,8 +25,8 @@ services:
   app:
     stdin_open: true
     tty: true
-    build: .
-    image: heartexlabs/label-studio:latest
+    image: heartexlabs/label-studio:1.7.0
+    user: root
     expose:
       - "8000"
     depends_on:
@@ -40,6 +40,9 @@ services:
       - POSTGRE_HOST=db
       - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
       - JSON_LOG=1
+      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
+      - LABEL_STUDIO_USERNAME=default_user@localhost
+      - LABEL_STUDIO_PASSWORD=njMu2fnoUkZwmW9u
 #      - LOG_LEVEL=DEBUG
     volumes:
       - ./mydata:/label-studio/data:rw

```
2. `docker-compose down -v `
3. `sudo rm -rf postgres-data mydata`
4. `docker-compose up`
5. Surf to http://localhost:8080/ and try to login as `default_user@localhost` `njMu2fnoUkZwmW9u`
6. Login fails as the account was not created.

**Expected behavior**
The account show be created and login should succeed.

**Environment (please complete the following information):**
 - Label Studio Version: 1.7.0

**Additional context**
Running `label-studio start` in the running container is a work-around; but is cumbersome in cloud deployments.

**Comment by makseq** [comment]
@fvdnabee could you try LS from the latest develop branch builds? We've fixed it today.

**Comment by fvdnabee** [comment]
Tested on 8a1c76b0fe55434b6cfbe1a98508d1aa1d017ca7 and I see `=> Run label-studio init...`  in the logs and logging in is working now. Thanks a bunch!
