### ISSUE TITLE
redirect to /welcome behind a reverse proxy doesn't work

### ISSUE THREAD

**Issue by devonkinghorn** [heartexlabs/label-studio#356]
**Describe the bug**
We use labelstudio behind traefik and rewrite the path. So users go to <dns name>/prefix/* When there are no tasks, the home page redirects to <dns name>/welcome not <dns name>/prefix/welcome

**To Reproduce**
1. setup like https://github.com/heartexlabs/label-studio/issues/273
2. have no tasks
3. go to the base url

**Expected behavior**
should redirect to /prefix/welcome

**Environment (please complete the following information):**
 - OS: aws-linux (eks 1.14)
 - Browser: all

Should be an easy fix.
just need to add a configuration for the redirect
https://github.com/heartexlabs/label-studio/blob/0c686176510c91a2c7ec7bc7ed0a77af964f9624/label_studio/server.py#L169

**Comment by makseq** [comment]
Can you try this PR https://github.com/heartexlabs/label-studio/pull/350 ?

**Comment by makseq** [comment]
I hope you found my fixes are working :-)

**Comment by devonkinghorn** [comment]
It does work. Thank you.

I work with Adam Guymon, he has been communicating with you on your slack channel about a few requests. Thank you for being responsive there.
