### ISSUE TITLE
PROBLEM: Label annotation values overwrites tasks cells on Export

### ISSUE THREAD

**Issue by aspanasiou** [heartexlabs/label-studio#3569]
**Bug**: 
On TSV export, label values overwrites column values because the label has the same name of the column from imported data, making the annotation results useless without the texts which imported.

The label has two text values to annotate tasks, the column has the text to be annotated in its task. So on Export I need both column and annotation values. Could I rename the label, without delete the annotations? Could I migrate the data with other column names?

**Comment by makseq** [comment]
You can try to enable experimental features and rename label using data manager actions:
https://github.com/heartexlabs/label-studio/pull/2055

Or if you are talking about `from_name` field in the labeling config, it's easier to export to LS JSON, then replace all `from_name` fields and you need and export this JSON to TSV using label-studio-converter.
