### ISSUE TITLE
use relative 'href' tags when using 'base href'

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#358]
**Describe the bug**
I am using 'base href' because the host changes in every deployment.

Some of label-studio's html 'href' tags are using static links instead of relative links.  When using 'base href', the other 'href' links should NOT start with a "/" (or else they become static links).

**For example, to reproduce** 
1. go to "Import" page
2. drag a file on to the page for import
3. Look at the links for "Start Labeling" and "Tasks" they are static (they begin with a slash) they are not relative.
This is a problem when using 'base href'.

**Expected behavior**
All links should be relative. So in the above example

`href="/">Start Labeling<` **should be** `href".">Start Labeling<`   (note dot in stead of slash)
and
`href="/tasks">Explore Tasks<` **should be**  `href="tasks">Explore Tasks<` (note link does not start with slash)

**Additional context**
This issue is probably in other places as well.

**Comment by makseq** [comment]
Fixed in 
https://github.com/heartexlabs/label-studio/pull/350

**Comment by laynr** [comment]
> 
> 
> Fixed in
> #350

Confirmed PR #350 resolved issue.
