### ISSUE TITLE
Task page errors - resources not found

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#359]
**Describe the bug**
I am using 'base href' because the host changes in every deployment.

When navigating to 'Tasks' page I get alert box's warning that the following can not be found:

- /api/project - Project loading error
- /api/project/storage-settings - Error while get api for <storage_settings_all>
-/api/tasks - Tasks loading error

This **maybe** similar to issue #358, where the solution is to remove the leading "/"

**Comment by makseq** [comment]
It was fixed in this PR:
https://github.com/heartexlabs/label-studio/pull/350

Please, try it.

**Comment by laynr** [comment]
Sorry, I am only using docker and I've pulled 'docker pull heartexlabs/label-studio:latest' but it doesn't appear to have #350 in it. But the code definitively looks better for issue #358 .  Thanks!

Do you prefer issues/bug reports or PR's?   Because the latest version of  
label-studio/label_studio/utils/schema/data_examples.json could be change to relative paths (this would help my use case), replace all `<HOSTNAME>/static` with  `static`

**Comment by makseq** [comment]
I'm not sure that it's a good idea to exclude HOSTNAME from there. Because if you use ML backend or other external tools then they will not be able to find resource files. So, the better way is to change "host" in config to hostname you use.

**Comment by makseq** [comment]
Otherside it's just examples..

**Comment by laynr** [comment]
> 
> 
> It was fixed in this PR:
> #350
> 
> Please, try it.

Confirmed PR #350 resolved issue.
