### ISSUE TITLE
Docker mkdir permission error

### ISSUE THREAD

**Issue by rutrum** [heartexlabs/label-studio#3595]
**Describe the bug**
Following the example docker run command in the README errors: "PermissionError: [Errno 13] Permission denied: '/label-studio/data/media'"

**To Reproduce**
docker pull heartexlabs/label-studio:latest
docker run -it -p 8080:8080 -v $(pwd)/mydata:/label-studio/data heartexlabs/label-studio:latest

**Expected behavior**
Shouldn't error

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version: heartexlabs/label-studio:latest

**Additional context**
Current version on docker looks like release v1.7.0

**Comment by farioas** [comment]
![Kapture 2023-01-25 at 14 30 01](https://user-images.githubusercontent.com/2744993/214590315-14e65938-e855-4c1d-80db-d9014cd28713.gif)

Cannot reproduce

**Comment by patrickwasp** [comment]
I have a possibly related issue when I use `docker compose up` in 1.7.0. `mydata` was owned by `root` user and group. Running `sudo chown -R name:name mydata` and `chmod -R 777 mydata` fixes the issue. Whether it's a good idea to have mydata with those permissions is uncertain. 

```
label-studio-170-app-1    | => Postgres is up.
label-studio-170-app-1    | ./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/app/30-run-db-migrations.sh
label-studio-170-app-1    | => Do database migrations...
label-studio-170-app-1    | => Database and media directory: /label-studio/data
label-studio-170-app-1    | => Static URL is set to: /static/
label-studio-170-app-1    | Traceback (most recent call last):
label-studio-170-app-1    |   File "/label-studio/label_studio/manage.py", line 14, in <module>
label-studio-170-app-1    |     runserver.default_port = settings.INTERNAL_PORT
label-studio-170-app-1    |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 82, in __getattr__
label-studio-170-app-1    |     self._setup(name)
label-studio-170-app-1    |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 69, in _setup
label-studio-170-app-1    |     self._wrapped = Settings(settings_module)
label-studio-170-app-1    |   File "/usr/local/lib/python3.10/dist-packages/django/conf/__init__.py", line 170, in __init__
label-studio-170-app-1    |     mod = importlib.import_module(self.SETTINGS_MODULE)
label-studio-170-app-1    |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
label-studio-170-app-1    |     return _bootstrap._gcd_import(name[level:], package, level)
label-studio-170-app-1    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
label-studio-170-app-1    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
label-studio-170-app-1    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
label-studio-170-app-1    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
label-studio-170-app-1    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
label-studio-170-app-1    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
label-studio-170-app-1    |   File "/label-studio/label_studio/core/settings/label_studio.py", line 6, in <module>
label-studio-170-app-1    |     from core.settings.base import *
label-studio-170-app-1    |   File "/label-studio/label_studio/core/settings/base.py", line 399, in <module>
label-studio-170-app-1    |     os.makedirs(MEDIA_ROOT, exist_ok=True)
label-studio-170-app-1    |   File "/usr/lib/python3.10/os.py", line 225, in makedirs
label-studio-170-app-1    |     mkdir(name, mode)
label-studio-170-app-1    | PermissionError: [Errno 13] Permission denied: '/label-studio/data/media'
label-studio-170-app-1 exited with code 1
```

**Comment by farioas** [comment]
No, it's not a good idea. Please check the changelog before upgrade to a new version:
<img width="1484" alt="image" src="https://user-images.githubusercontent.com/2744993/215085885-a09a1099-f768-49cc-9550-2a75ced73925.png">

**Comment by patrickwasp** [comment]
> No, it's not a good idea. Please check the changelog before upgrade to a new version:
> <img width="1484" alt="image" src="https://user-images.githubusercontent.com/2744993/215085885-a09a1099-f768-49cc-9550-2a75ced73925.png">
> 

Hmm, I didn't upgrade, this is my first time trying out label studio. I tried 1.6 after and docker compose had the same issue when running on Ubuntu 22.04 and using docker compose.

**Comment by JojoDevel** [comment]
Got same problems after fresh install, but the command fixes it :+1:

**Comment by thistleknot** [comment]
Same (I also tried the default {pwd}
![image](https://user-images.githubusercontent.com/5154106/235049315-1a276906-5604-4c27-8f9a-1effa9d4b6e5.png)

**Comment by farioas** [comment]
https://labelstud.io/guide/install.html#PermissionError-Errno-13-Permission-denied-label-studio-data-media

**Comment by DavidAdamczyk** [comment]
> ![Kapture 2023-01-25 at 14 30 01](https://user-images.githubusercontent.com/2744993/214590315-14e65938-e855-4c1d-80db-d9014cd28713.gif) [ ![Kapture 2023-01-25 at 14 30 01](https://user-images.githubusercontent.com/2744993/214590315-14e65938-e855-4c1d-80db-d9014cd28713.gif) ](https://user-images.githubusercontent.com/2744993/214590315-14e65938-e855-4c1d-80db-d9014cd28713.gif) [ ](https://user-images.githubusercontent.com/2744993/214590315-14e65938-e855-4c1d-80db-d9014cd28713.gif)
> 
> Cannot reproduce

I can reproduce so this issue is still relevant. So the main problem is you can't reproduce this issue because you doesnt read issue description?
