### ISSUE TITLE
Firefox not playing wav files

### ISSUE THREAD

**Issue by mcrisafu** [heartexlabs/label-studio#3598]
**Describe the bug**
Thank you for your work! It is an amazing tool. Today i played around with some audio (wav files). On Firefox only 2 out of 20 work. On the Edge browser they all work. I do not have any error messages besides a warning about "An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.".

**To Reproduce**
1. Create a project (Automatic Speech Recognition Template)
2. Upload some wav files (also does not work if the files are in S3)
3. Click on play
4. Most do not play also the wave is shown flat

**Expected behavior**
The files should play in Firefox as they do in Edge

**Screenshots**
![image](https://user-images.githubusercontent.com/23549529/214438574-f5ddcb44-e17f-46ba-ba3f-5a754539af7c.png)

**Environment (please complete the following information):**
 - OS: Windows with Firefox 109 and Edge 109.0.1518.61
 - Label Studio Version 1.7.0

Thank you very much in advance!
Regards,

**Comment by makseq** [comment]
@mcrisafu could you please show codec info for these files? 
On unix you can use soxi for this:

```
soxi file.wav
```

**Comment by mcrisafu** [comment]
@makseq of course:
```
Input File     : '4142b7515fa53ddafa65cbde617d3636.wav'
Channels       : 1
Sample Rate    : 22050
Precision      : 32-bit
Duration       : 00:00:05.09 = 112279 samples ~ 381.901 CDDA sectors
File Size      : 449k
Bit Rate       : 706k
Sample Encoding: 32-bit Signed Integer PCM
```

**Comment by makseq** [comment]
Probably the problem is in 32 bit. Could you try to resave it as 16 bits? Btw can you play it in Chrome? Firefox is not recommended browser for LS.

**Comment by mcrisafu** [comment]
@makseq Indeed 16 bits works. I did not test Chrome but as it uses the same engine as Edge I would assume it works. A lot of user use Firefox. I would really appreciate if you could look into this but i totally understand if this has no priority :) Thank you for your help and keep up the awesome work!

**Comment by makseq** [comment]
Thank you for your kind words! 

>  if you could look into this

I'am afraid it's a browser issue, because we use a standard browser audio engine.. if a browser doesn't support it, LS doesn't support it too.

**Comment by bmartel** [comment]
Hey @mcrisafu 👋. I have another branch which might possibly solve this for firefox, would you be able to share a file which did not work in firefox that we could test against?

**Comment by mcrisafu** [comment]
Hey @bmartel 👋. Thank you but unfortunately I am not allowed to share the files.
