### ISSUE TITLE
I can't draw a rotated box.

### ISSUE THREAD

**Issue by hi-one-gg** [heartexlabs/label-studio#3605]
I want to draw a rotated box.
That is well explained here : https://labelstud.io/templates/image_bbox.html#Create-a-rotated-bounding-box

> "As an annotator, you can also create a rotated bounding box with the “three point click” or “two point click” feature to annotate images."

However, the "three point click" feature cannot be found in the latest version.

Please help me..

**Comment by makseq** [comment]
Unfortunately it's supported only for video. BBoxes on images are inside of images only.

**Comment by Travis1282** [comment]
Hey, we are looking into this. Could you do us a favor and shoot us a quick screen capture of what you're experiencing? Would also like to get you unblocked, what are you trying to accomplish?

**Comment by hi-one-gg** [comment]
What I want to accomplish is **to draw a rotated box**.

The guide document said, _**"You can draw a rotated box using three points."**_ at here : https://labelstud.io/templates/image_bbox.html#Create-a-rotated-bounding-box.
However, as I said at the beginning, there is no function to draw a rotated box using three points.

(Please wait the screenshot)

**Comment by Travis1282** [comment]
You are correct, this seems to be a regression on our end, we are working to get it resolved as soon as possible. In the interim you can draw the box, click away, reselect, and hover close to one of the corner handles, you should get a rotation cursor so you can click and drag to rotate from there. Sorry for the inconvenience.

**Comment by hi-one-gg** [comment]
> You are correct, this seems to be a regression on our end, we are working to get it resolved as soon as possible. In the interim you can draw the box, click away, reselect, and hover close to one of the corner handles, you should get a rotation cursor so you can click and drag to rotate from there. Sorry for the inconvenience.

Aha, thank you for your confirmation🙂

**Comment by Travis1282** [comment]
Ticket: LSDV-4656

**Comment by jaydeboer** [comment]
Did the three point click option ever get added back? I cannot seem to locate that functionality in the current latest UI.

**Comment by blakespace** [comment]
Is there any update on this?  Or can someone point to the label-studio version where this worked?

**Comment by LMaiorano** [comment]
+1 Any update on this? Still not available in v1.13.1

**Comment by ogencoglu** [comment]
Can a rotated bbox be created with 3 clicks?

**Comment by lukaskotik** [comment]
What is the status of this issue? Is there a plan to have feature for faster labeling using 3 clicks rotated boxes for rectangleLabels (fixing this issue) or this feature is not planned to be supported in Label Studio?

The issue is closed for about 3 years but yet it is not possible to use 3 clicks bbox for rectanbleLabels in 1.23.0.
