### ISSUE TITLE
Filter images in S3 bucket

### ISSUE THREAD

**Issue by maxstrobel** [heartexlabs/label-studio#3608]
Hello,

I've a S3 bucket with a lot of images with random hashes as file names in a flat structure:
~~~
0a1cce8ea0954bd7a76e4f254aa9e39b
0a4ce4b98976408a9d54a17ed3053cc2
0a8fda330de5436295ce293f2b75fc76
...
~~~

I was successfully able to add the S3 bucket to LS & to sync all images inside the bucket.

However I'd need to filter out some images & have only a subset in LS - is there a way to define e.g. a list with files to import (regex will not work, because of the random hashes & flat structure).

**Comment by makseq** [comment]
Hello, you have two options:
1. Filter tasks in the Data Manager using task url fields (you will have lots of OR filters)
2. Don't sync your bucket, just add it and then import JSON file with tasks you need, like:
```
[
 { "url": "s3://bucket/0a1cce8ea0954bd7a76e4f254aa9e39b.jpg"},
 { "url": "s3://bucket/0a4ce4b98976408a9d54a17ed3053cc2.jpg"},
 { "url": "s3://bucket/0a8fda330de5436295ce293f2b75fc76.jpg"}
 ...
]
```
