### ISSUE TITLE
coco import

### ISSUE THREAD

**Issue by xuhuasong** [heartexlabs/label-studio#3619]
An error occurred when importing result.json into the coco dataset:
Error at item 0: "image" key is expected in task data [assume: item["data"] = task root with values]

**Comment by makseq** [comment]
LS doesn't support imports from COCO format directly. You should convert COCO JSON to LS JSON first. 
It works very similar to YOLO import, check this - https://github.com/heartexlabs/label-studio-converter/pull/46
