### ISSUE TITLE
"Prev" Button Unresponsive

### ISSUE THREAD

**Issue by daduk** [heartexlabs/label-studio#362]
**Describe the bug**
It is not possible to go back to a labelled task using the "Prev" button : it appears unresponsive.

**To Reproduce**
1. Load https://app.labelstud.io/
2. Set up Text classification config (equally buggy with another type of labelling)
3. Import tasks (I used default dataset from Heartex Datasets)
4. Label one task and click submit
5. Press "Prev" => nothing happens

DevTools Console properly reports an error : 
Mixed Content: The page at 'https://app.labelstud.io/' was loaded over HTTPS, but requested an insecure resource 'http://app.labelstud.io/api/tasks/0/'. This request has been blocked; the content must be served over HTTPS.
app.labelstud.io/:1 Uncaught (in promise) TypeError: Failed to fetch
lsf-sdk.js:352 Uncaught TypeError: Cannot read property 'task_id' of undefined
    at Object.prevButtonClick (lsf-sdk.js:352)
    at HTMLButtonElement.onclick ((index):1)
o227124.ingest.sentry.io/api/5285295/store/?sentry_key=f24f3e8da54c4a16a1ce9bef30ea9c30&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
**3lsf-sdk.js:352 Uncaught TypeError: Cannot read property 'task_id' of undefined
    at Object.prevButtonClick (lsf-sdk.js:352)
    at HTMLButtonElement.onclick ((index):1)**
(index):1 Mixed Content: The page at 'https://app.labelstud.io/' was loaded over HTTPS, but requested an insecure resource 'http://app.labelstud.io/api/tasks/3/'. This request has been blocked; the content must be served over HTTPS.
app.labelstud.io/:1 Uncaught (in promise) TypeError: Failed to fetch
DevTools failed to load SourceMap: Could not load content for https://app.labelstud.io/static/js/tippy-bundle.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://app.labelstud.io/static/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Expected behavior**
Be able to navigate backward to a completed task.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Win10
 - Browser: chrome 
 - Version: 83.0.4103.116 (64bits)

**Comment by makseq** [comment]
Thanks for your report. This bug appears on https domains only (like https://app.labelstud.io). If you try to start LS locally over https there won't be same problem. But we are working on it and fix it soon as possible.

**Comment by makseq** [comment]
I hope it's fixed in the last version of LS.
