### ISSUE TITLE
Export fails with urls with long file names

### ISSUE THREAD

**Issue by bindestriche** [heartexlabs/label-studio#3638]
**Describe the bug**
Export to Yolo Fails.

`Traceback (most recent call last):
[minimal_example.zip](https://github.com/heartexlabs/label-studio/files/10569694/minimal_example.zip)

  File "C:\Users\xx\PycharmProjects\label1\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\xx\PycharmProjects\label1\venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\xx\PycharmProjects\label1\venv\lib\site-packages\label_studio\data_export\api.py", line 183, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "C:\Users\xx\PycharmProjects\label1\venv\lib\site-packages\label_studio\data_export\models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "C:\Users\xx\PycharmProjects\label1\venv\lib\site-packages\label_studio_converter\converter.py", line 183, in convert
    self.convert_to_yolo(input_data, output_data, output_image_dir=image_dir,
  File "C:\Users\xx\PycharmProjects\label1\venv\lib\site-packages\label_studio_converter\converter.py", line 690, in convert_to_yolo
    with open(label_path, 'w') as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\xx\\AppData\\Local\\Temp\\tmpj4cxw0_d\\labels\\WW2_Norway._Recruitment_brochure_pamphlet_for_Frontkjemper_%28Norwegian_Waffen-SS_volunteer%29_%2C_tent_pegs_Zeltbahn%2C_Gebirgsj%C3%A4ger_Edelweiss_emblem%2C_East_Front_Medal%2C_compass%2C_Ost-Front_newspaper%2C_etc._Lofoten_krigsminnemuseum_2019_09964.txt'`

I suspect this is due to the filename being too long.

**To Reproduce**
import this json and try to export to yolo
`[{"id":1116,"annotations":[{"id":854,"completed_by":1,"result":[{"original_width":2016,"original_height":1512,
"image_rotation":0,"value":{"x":38.425925925925924,"y":39.18571009582702,"width":2.625600137174213,"height":3.283546769583874,"rotation":0,
"rectanglelabels":["car"]},"id":"L28xt4qPQ1","from_name":"label","to_name":"image","type":"rectanglelabels"},
{"original_width":2016,"original_height":1512,"image_rotation":0,
"value":{"x":87.40140603566529,"y":41.18439073818244,"width":2.5184327846364947,"height":3.2121653180711784,"rotation":0,"rectanglelabels":["car"]},
"id":"25mzEMfK8V","from_name":"label","to_name":"image","type":"rectanglelabels"},
{"original_width":2016,"original_height":1512,"image_rotation":0,"value":{"x":84.67217721650388,"y":58.148946708793396,"width":2.077607818294979,
"height":2.685066173799212,"rotation":0,"rectanglelabels":["car"]},"id":"d_-dGsICWf","from_name":"label","to_name":"image","type":"rectanglelabels"},
{"original_width":2016,"original_height":1512,"image_rotation":0,"value":{"x":75.58124396687498,"y":84.12512563346968,"width":2.4187076093583375,"height":2.8089923048976493,
"rotation":0,"rectanglelabels":["car"]},"id":"FvCqr0oqMG","from_name":"label","to_name":"image","type":"rectanglelabels"}],
"was_cancelled":false,"ground_truth":false,"created_at":"2023-02-02T13:23:57.248133Z","updated_at":"2023-02-02T13:23:57.248133Z","lead_time":1963.3,"prediction":{},
"result_count":0,"task":1116,"project":6,"parent_prediction":null,"parent_annotation":null}],"file_upload":"91c670d5-project-7-at-2023-02-02-11-23-5e809630.json","drafts":[],
"predictions":[],"data":{"pageid":113577757,
"filename":"File:ЗНАКИ РАЗЛИЧИЯ ГЕРМАНСКОЙ АРМИИ (СССР 1941 год) 06-07 Wehrmacht Abzeichen WW2 German insignia Heer army infantry (USSR) Scribd No known copyright.jpg",
"license":"CC BY-SA 4.0","attribution":"Unknown; uncredited illustrator\/designer of descriptive illustrations of German uniform insignia. Booklet published by the People's Commissariat of Defense of the Soviet Union (Народный комиссариат обороны СССР) and the USSR People's Commissariat for Industry and Trade in Moscow in 1941. No known copyright restrictions.","image":"https:\/\/upload.wikimedia.org\/wikipedia\/commons\/9\/95\/%D0%97%D0%9D%D0%90%D0%9A%D0%98_%D0%A0%D0%90%D0%97%D0%9B%D0%98%D0%A7%D0%98%D0%AF_%D0%93%D0%95%D0%A0%D0%9C%D0%90%D0%9D%D0%A1%D0%9A%D0%9E%D0%99_%D0%90%D0%A0%D0%9C%D0%98%D0%98_%28%D0%A1%D0%A1%D0%A1%D0%A0_1941_%D0%B3%D0%BE%D0%B4%29_06-07_Wehrmacht_Abzeichen_WW2_German_insignia_Heer_army_infantry_%28USSR%29_Scribd_No_known_copyright.jpg","timestamp":"2021-12-23 00:45:04"},
"meta":{},"created_at":"2023-02-02T13:23:57.185624Z","updated_at":"2023-02-02T13:23:57.185624Z","inner_id":11,"total_annotations":1,"cancelled_annotations":0,"total_predictions":0,"comment_count":0,"unresolved_comment_count":0,
"last_comment_updated_at":null,"project":6,"updated_by":null,"comment_authors":[]}]`

labeling interface
`<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="car" background="blue"/>
</RectangleLabels>
</View>`

**Comment by makseq** [comment]
The issue is solved in https://github.com/heartexlabs/label-studio-converter/commit/3c71c95e4c91e92d25721dcf360f1978efd8a7ca of label-studio-converter repo, it will be delivered in upcoming releases (after LS 1.7.2). 

However, users should prepare their files before labeling: download them, save in more safety storages, have more like id-names.
