### ISSUE TITLE
Incorrect display projects per page after selecting a number greater than 30

### ISSUE THREAD

**Issue by JN426206** [heartexlabs/label-studio#3649]
**Describe the bug**
If we have more than 30 projects and we choose in the tool to display more than 30 projects per page, only 30 are displayed. However, the number of pages will decrease and some projects will not be displayed.

**To Reproduce**

    Add more than 100 projects
    Choose 50 or 100 projects per page in projects list view
    Count the number of projects (quantity is wrong)
    Change to next page (you can see that the sum of the number of projects is less than 100)

**Expected behavior**
The page should display the same number of projects as selected per page. The number of projects on all pages should be the same as the number of all projects.

**Screenshots**
n/a -- can provide if really needed

**Environment**

    OS: Mint
    Label Studio Version Release 1.7.1

**Additional context**

In this line `page_size` should be passed as parameter.
 
https://github.com/heartexlabs/label-studio/blob/9308125b3633997d2546a26a7855804c850cc32a/label_studio/frontend/src/pages/Projects/Projects.js#L70

I found the error together with @mikbuch

**Comment by mikbuch** [comment]
The same issue applies to macOS Big Sur 11.7.2

**Comment by makseq** [comment]
The fix is in develop.

**Comment by mikbuch** [comment]
Great, thank you!
