### ISSUE TITLE
Client.sync does not do actual syncing, but downloading, which produces duplicates.

### ISSUE THREAD

**Issue by mbspng** [heartexlabs/label-studio#3651]
**Describe the bug**
Calling `Client.sync_storage` does not sync. It downloads the data from the storage and produces duplicates when called more than once. That is not syncing!

**To Reproduce**
```python
from label_studio_sdk import Client, Project

def import_tasks_from_remote_storage(client: Client, project: Project):

    logger.info("Connecting Azure import storage...")
    response = project.connect_azure_import_storage(
        **load_config(AZURE_STORAGE_CONFIG)["import"], **load_config(AZURE_STORAGE_CREDENTIALS_FILE)
    )
    logger.info("Syncing Azure import storage...")
    client.sync_storage(*itemgetter("type", "id")(response))
    logger.info("Syncing Azure import storage complete.")
```

**Expected behavior**
Function should do actual syncing: only download data that is not yet on local machine.

**Environment (please complete the following information):**
 - OS: Linux
```
label-studio                   1.7.0
label-studio-converter         0.0.48rc0
label-studio-ml                1.0.9
label-studio-sdk               0.0.16
label-studio-tools             0.0.1
```

**Comment by triklozoid** [comment]
@mbspng did you call all attached snippet? It's important, because every call of `response = project.connect_azure_import_storage(**load_config(AZURE_STORAGE_CONFIG)["import"], **load_config(AZURE_STORAGE_CREDENTIALS_FILE))` will create separate storage. If you want to run sync, you need to make second `client.sync_storage` call with the same storage id.

**Comment by mbspng** [comment]
> @mbspng did you call all attached snippet? It's important, because every call of `response = project.connect_azure_import_storage(**load_config(AZURE_STORAGE_CONFIG)["import"], **load_config(AZURE_STORAGE_CREDENTIALS_FILE))` will create separate storage. If you want to run sync, you need to make second `client.sync_storage` call with the same storage id.
 @triklozoid  I don't understand. Why would I need a second call when the first call already downloads the duplicate data?

**Comment by triklozoid** [comment]
@mbspng 

`project.connect_azure_import_storage` - create storage connection and sync
`client.sync_storage` - run sync on already created storage connection

**Comment by mbspng** [comment]
@triklozoid 

But that is what I am doing. I don't understand what you are trying to say.

**Comment by triklozoid** [comment]
@mbspng I just want to clarify your scenario, did you call `project.connect_azure_import_storage` every time or just once?

**Comment by mbspng** [comment]
@triklozoid every time. So you are saying I should call that only once and after that only use `client.sync_storage`? How do I check if the storage has already been connected so that I can use only `client.sync_storage` in that case?

**Comment by mbspng** [comment]
Ok, I solved it like this (can be improved of course, but works in principle)

```python
def import_tasks_from_remote_storage(client: Client, project: Project):

    connected_storages = get_import_storages(client, project)

    import_storage_config = load_config(AZURE_STORAGE_CONFIG)["import"]

    if not any(partial(matches_storage_specification, import_storage_config), connected_storages):

        logger.info("Connecting Azure import storage...")
        response = project.connect_azure_import_storage(
            **import_storage_config, **load_config(AZURE_STORAGE_CREDENTIALS_FILE)
        )
        storage_type, storage_id = itemgetter("type", "id")(response)
    else:
        storage_type, storage_id = itemgetter("type", "id")(first(connected_storages))

    logger.info("Syncing Azure import storage...")
    client.sync_storage(storage_type, storage_id)
    logger.info("Syncing Azure import storage complete.")


def get_import_storages(client: Client, project: Project) -> List[dict]:
    """
    http://api.labelstud.io/api/storages/

    curl -X GET "http://localhost:8080/api/storages/?project=<project id>" -H 'Authorization: Token abc123'
    """
    logger.info(f"Querying import storages for project {project.id}...")
    response = requests.get(
        headers={"Authorization": f"Token {client.api_key}"},
        url=client.get_url(f"/api/storages/?project={project.id}"),
    )
    response.raise_for_status()
    return response.json()


def matches_storage_specification(specification: dict, storage: dict) -> bool:
    return all(specification[key] == storage[key] for key in ("container", "prefix"))
```

**Comment by makseq** [comment]
Yes, you have to connect a storage only once, then you can call sync many times.
