### ISSUE TITLE
Customizable category ID for COCO JSON

### ISSUE THREAD

**Issue by john-tseng-710** [heartexlabs/label-studio#3653]
**Current**: Category ID is automatically defined by alphabetical order in exported COCO JSON

**New Feature**: Option to allow self-defined category ID

**Comment by makseq** [comment]
@john-tseng-710 Do you have any examples of how would it be?

**Comment by makseq** [comment]
Could you also try adding `category="123"` into your Labels?

**Comment by makseq** [comment]
Related:
https://github.com/heartexlabs/label-studio/issues/3653
https://github.com/heartexlabs/label-studio/issues/3324
https://github.com/heartexlabs/label-studio/issues/2886
https://github.com/heartexlabs/label-studio/issues/1115
https://github.com/heartexlabs/label-studio/issues/737

**Comment by Digital2Slave** [comment]
https://github.com/heartexlabs/label-studio/issues/2886#issuecomment-1238008483 

```
It's expected behavior by default as labels are being sorted.
You can override this behavior by adding tag category to your labels like that:
<Label value="number_plate" category="0"/>
```

**Comment by makseq** [comment]
Solution from the docs:
https://labelstud.io/guide/export.html#Question-3-How-to-modify-order-of-categories-for-COCO-and-YOLO-exports

**Comment by john-tseng-710** [comment]
@makseq @Digital2Slave 
Sorry for my late response.
Appreciate!
