### ISSUE TITLE
Grid layout 

### ISSUE THREAD

**Issue by kateob** [heartexlabs/label-studio#3654]
Hello, a previous question asked for a way to display the full image in the grid view. The response was to edit the lsf. I'd like to know more about how this can be done when deploying to azure? I'd also like to be able to see mask annotations in the grid view. Thanks, kate

**Comment by makseq** [comment]
@kateob Hello, 

1. Could you please refer to the response? 

2. 
    > How this can be done when deploying to azure

    In a nutshell: 
      2.1. You have to go here - https://github.com/heartexlabs/label-studio-frontend, download this repo, fix the code you need (you should be familiar with React).
      2.2. Make a new build of LS. 
      2.3. Then you need to clone LS - https://github.com/heartexlabs/label-studio - insert your build into label_studio/frontend/dist/lsf.
      2.4. Build your own docker image and upload it to dockerhub.
      2.5. Edit https://github.com/heartexlabs/label-studio/blob/develop/azuredeploy.json#L131 and specify your dockerhub account and LS image instead of heartexlabs/label-studio. 

3. It's a super hard task, you should be very advanced in React
