### ISSUE TITLE
Configure s3 credentials to use the API to create the task in bulk using s3:// links

### ISSUE THREAD

**Issue by erinmikailstaples** [heartexlabs/label-studio#3658]
_This feature request is from **Alejandro Dini** in the Slack Community 😄 _

**Is your feature request related to a problem? Please describe.**
Alejandro found the process of creating the json tasks, uploading one file per task (potentially hundreds of thousands), and triggering the sync more complex and slow than necessary, so he's explored the API.

**Describe the solution you'd like**
Wouldn't it be great if we were able to configure our s3 credentials and then use the API to create tasks in bulk using s3:// links? 

**Describe alternatives you've considered**
With the API, I was able to create about 8k tasks in a single request that took less than 2s 🥳 but going to the point, I've found that I can't create tasks using S3 URIs (s3://<bucket>/path/file), these are not directly supported to load the video, the external s3 sync takes care of creating pre-signed links and keeping them updated (refreshing them) for me, but the API (or the server, after) doesn't. I could send the task with a pre-signed link I created myself, but the max expiration is only one week, which is not enough for my use case.

**Thank you to Alejandro for submitting this feature request in the [Label Studio Community Slack.](https://join.slack.com/t/label-studio/shared_invite/zt-1mrucvyf7-Ds927l2N8fD7X9icBzPBoQ)**

**Comment by makseq** [comment]
LS works exactly the same way as you described in the solution: you can add an s3 cloud storage and then upload tasks in JSON via LS GUI (or import API) with s3:// links. LS will resolve them on the fly in `api/tasks`.

**Comment by alete89** [comment]
You're right @makseq ! thanks for pointing that out. From the docs it looks like the only way you have to take advantage of the Cloud Storage integration is through syncing tasks from s3, but it's clearly not. It seems like in my tests I forgot to check the presign option when configuring the integration.
Now I was able to load tasks in bulk using the API with s3:// links :partying_face:  Thanks!!!
