### ISSUE TITLE
[API] Updating a task data with PATCH deletes fields not included in body

### ISSUE THREAD

**Issue by alete89** [heartexlabs/label-studio#3659]
**Describe the bug**
Updating a task data field using PATCH replaces everything under `data`

**To Reproduce**
1. Have a task with some fields under `data`
2. use the API to partially update a task data field, eg:
```
PATCH /api/tasks/{taskId}/
{
  data: {
    newField: 'aValue'
  }
}
```
4. check your task again, you now only have `newField` under data, previous values are gone.

**Expected behavior**
PATCH should not delete previous fields.

**Environment (please complete the following information):**
 - Label Studio Version: 1.7.0

**Comment by makseq** [comment]
`data` field is stored as Django JSONField in the DB and it is considered as an atomic JSON field in Django. It's not a trivial task to make a real patch for this field. You can retrieve a task data using `api/tasks/<id>` before and then calculate the difference and the result on your side.

**Comment by alete89** [comment]
Thanks @makseq , that was my workaround. I'd love a brief mention to this in the docs :sweat_smile:

**Comment by makseq** [comment]
Added it here:
![image](https://user-images.githubusercontent.com/501780/217139871-3b5c64f5-02d9-458e-bcaa-4ca1456dcd1d.png)

It will appear in the next versions of LS.
