### ISSUE TITLE
`pip install` of `label-studio` and `label-studio-sdk` can't be resolved

### ISSUE THREAD

**Issue by strickvl** [heartexlabs/label-studio#3662]
**Describe the bug**
It's currently impossible to install the latest versions of `label-studio` and `label-studio-sdk` packages at the same time.

**To Reproduce**
```shell
pip install "label-studio==1.7.1" "label-studio-sdk==0.0.18"
```

**Expected behavior**
I expect to be able to install the latest versions of your Python pip packages together.

**Screenshots**
Terminal messages are as follows:

```shell
ERROR: Cannot install label-studio-sdk==0.0.18 and label-studio==1.7.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    label-studio 1.7.1 depends on pydantic<=1.8.2 and >=1.7.3
    label-studio-sdk 0.0.18 depends on pydantic~=1.10

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS 13.2
 - Label Studio Version [e.g. 0.8.0] 1.7.1, but I also tried with 1.6.0.

**Additional context**
This particular problem seems to revolve around pydantic (which our project also uses and that clashes with the version you have pinned in the `label-studio` package, but aside from this, whenever I install label_studio I find I have *lots* of dependency conflicts. If the team were able to relax the dependency pinning a bit I think it could benefit lots of people.

**Comment by makseq** [comment]
@strickvl please try `label-studio-sdk==0.0.19`.

**Comment by strickvl** [comment]
@makseq thank you for the quick response. I am now able to install those two label studio packages together.

Unfortunately, [our library](https://github.com/zenml-io/zenml) requires a version of Pydantic greater than that allowed by Label Studio. 

I try: 

```shell
pip install "pydantic<1.11,>=1.9.0" "label-studio==1.7.1" "label-studio-sdk==0.0.19"
```

and I get:

```shell
ERROR: Cannot install label-studio==1.7.1 and pydantic<1.11 and >=1.9.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic<1.11 and >=1.9.0
    label-studio 1.7.1 depends on pydantic<=1.8.2 and >=1.7.3
```

I couldn't find in the Label Studio codebase where pydantic is pinned to `pydantic<=1.8.2 and >=1.7.3`. In fact, in your `requirements.txt` it seems that things are a lot looser. Is there somewhere else where this more narrow range is specified, and would you be open to relaxing it, if so?

**Comment by makseq** [comment]
It's here:
https://github.com/heartexlabs/label-studio/blob/develop/deploy/requirements.txt#L51 - it was updated last month, so you can try to install LS from the develop branch instead of using 1.7.1. 

and here in SDK:
https://github.com/heartexlabs/label-studio-sdk/blob/master/requirements.txt#L3

why do you use the save env for all your projects? Better to split it and have separate envs for different things.

**Comment by strickvl** [comment]
I work on an open-source MLOps framework ([ZenML](https://github.com/zenml-io/zenml)) where we integrate with Label Studio as part of a full end-to-end ML cycle. ([Here's an example](https://github.com/zenml-io/zenml/tree/main/examples/label_studio_annotation) of how we use it.) This requires Label Studio to be installed in the same environment as ZenML as an integration, but currently (on account of the pydantic restrictions mentioned above) it's not possible to install ZenML and Label Studio at the same time.

There's a workaround which is to install Label Studio, and then to separately bump Pydantic back up to >1.9.0 with a pip install in order to make ZenML work again, but we'd rather not have to ask users to do this.

Both the requirements files look good to me + compatible with ZenML as they are written, just 1.7.1 `label-studio` seems to have an older version perhaps? (Or maybe I'm misunderstanding something completely about how this all interacts).

**Comment by makseq** [comment]
Wow, sounds cool! @hogepodge this topic is definitely for you ;-) 

Yes, the next LS versions will include the new dependencies as I've shown.
