### ISSUE TITLE
Import labeled mask for semantic segmentation

### ISSUE THREAD

**Issue by simonMadec** [heartexlabs/label-studio#3664]
I am currently working on binary semantic segmentation and I need a solution to import a previously labeled mask. I would appreciate a solution that would allow me to correct the mask.

Thank you

**Comment by makseq** [comment]
Please check this docs: 
https://labelstud.io/guide/predictions.html#Import-brush-segmentation-pre-annotations-in-RLE-format

**Comment by simonMadec** [comment]
Thanks a lot @makseq but how to import this rle mask to label-studio ?

**Comment by makseq** [comment]
Please check this docs thoroughly:
https://github.com/heartexlabs/label-studio-converter/blob/master/tests/test_brush.py#L26

You have to create LS JSON file and import it to the LS project with the specified labeling config in the example.

**Comment by simonMadec** [comment]
I am sorry @makseq  but I don't how to import it in the LS project ?

**Comment by makseq** [comment]
Go to Data Manager and click Import button.

**Comment by simonMadec** [comment]
Ok I found.
The trick was to not load the images and json with the same import (I am working with local files) also I have to give path name with linux filesystem Standard. Thank you really. Great tool :)

**Comment by makseq** [comment]
btw maybe this tutorial about local storage usage will be helpful:
https://labelstud.io/guide/storage.html#Local-Storage-with-Custom-Task-Format

**Comment by mfkeles** [comment]
thanks for the info! I am a bit confused and struggling. I first save numpy masks as images and then use image2annotation to generate a json file. I import the json and then import the images. I am passing the image filename when generating json so that when I import the image it will be attached to it. Yet the imported images and annotations do not match in my project. What am I missing?

```def generate_task_object(original_image_path, mask_image_path, label_name, from_name, to_name):
    # Generate annotation using the mask image path
    annotation = image2annotation(
        mask_image_path,  # This is the path to the saved mask image
        label_name=label_name,
        from_name=from_name,
        to_name=to_name,
        model_version=None,
        score=None,
    )

    # Use the original image filename for the task data
    original_image_filename = os.path.basename(original_image_path)
    
    task = {
        'data': {'image': original_image_filename},  # Reference the original image here
        'predictions': [annotation],
    }
    
    return task
```
