### ISSUE TITLE
Adding support to run server over HTTPS

### ISSUE THREAD

**Issue by abduhbm** [heartexlabs/label-studio#367]
**Is your feature request related to a problem? Please describe.**
There is no option in CLI to run server over HTTPS. This can be a valid security requirement in some environments.  

**Describe the solution you'd like**
Adding two optional arguments in CLI to provide paths for certificate and key files in order to run server over HTTPs. 

Thanks,

**Comment by makseq** [comment]
LS uses Flask web server by default. And it's not recommended to have it in production. So, we recommend to use uwsgi + nginx. 
With nginx there is no problem to setup https. Or you can use flask as is + nginx. Why don't you use nginx?

**Comment by abduhbm** [comment]
@makseq This is intended for strict development environments where data API calls are only allowed over HTTPs. It would be easier to enable this from Flask development server.

**Comment by makseq** [comment]
Added in https://github.com/heartexlabs/label-studio/pull/350.
