### ISSUE TITLE
ml backend predictions are read-only

### ISSUE THREAD

**Issue by Gaurvish** [heartexlabs/label-studio#3670]
**Describe the bug**
after taking predictions from ml backend model , the predictions are not editable. Is there any setting or tag to be added in results json for it? 

**Expected behavior**
Predictions from ml backend should be editable.

**Screenshots**
![image](https://user-images.githubusercontent.com/70942478/217759964-9689d121-7e91-4b2e-9311-bbdaf14f672f.png)

**Environment (please complete the following information):**
 - OS:Ubuntu 20.04
 - Label Studio Version 1.7.1

**Comment by makseq** [comment]
@Gaurvish you have to click 
![image](https://user-images.githubusercontent.com/501780/217880740-f117d674-40ca-45a9-ac19-2cb9a23bf16e.png)
this button will create a new annotation and copy the prediction there. Then you will be able to edit it.
