### ISSUE TITLE
Label Studio - Create new Project [ ERROR ] 

### ISSUE THREAD

**Issue by MateuszUlan** [heartexlabs/label-studio#3678]
**Describe the bug**

**To Reproduce**
1. Go to LabelStudio 
2. Click on 'Create Project"
4. See error " Runtime error Database error during project creation. Try again. "

**Expected behavior**
Create new empty project 

**Screenshots**
![obraz](https://user-images.githubusercontent.com/125041310/218110421-e7352a08-65c0-41b8-b781-ea1fa7924989.png)

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu Linux ( 20.04 LTS ) Docker version 20.10.8, build 3967b7d 
 - Label Studio Version [1.2]

**Additional context**

**Comment by makseq** [comment]
@MateuszUlan please switch to the latest LS version (1.7.1 at this moment), it should be fixed there.
