### ISSUE TITLE
Draw a bounding box cutting the image edge?

### ISSUE THREAD

**Issue by SkygirlLuna** [heartexlabs/label-studio#3681]
How can I draw a rectangle bounding box cutting the image edge?

**Comment by makseq** [comment]
Unfortunately it's supported only for video. BBoxes on images are inside of images only.

**Comment by SkygirlLuna** [comment]
Thanks for the fast response.
Thats a very unfortunately info for my project :-(

**Comment by makseq** [comment]
Yes, it's a popular request, we are working on new LSF engine, hope this behaviour will be implemented there.

**Comment by SkygirlLuna** [comment]
that's great :-)
