### ISSUE TITLE
When exporting video object tracking, frames with toggle interplating points are exported. How to get  annotations that are in between??

### ISSUE THREAD

**Issue by DongLiu001** [heartexlabs/label-studio#3683]

**Comment by makseq** [comment]
You can do it using easy export API (https://api.labelstud.io/#operation/api_projects_export_read):
```
curl -X GET [http://localhost:8080/api/projects/{project_id}/export?ids[]={task_id}](http://localhost:8080/api/projects/%7Bproject_id%7D/export?ids[]={task_id}) -H 'Authorization: Token abc123' --output '/path/to/output/annotations.json' -d '{"serialization_options: {"interpolate_key_frames": true}}'
```
or using export snapshots API
https://api.labelstud.io/#operation/api_projects_exports_create (check serialization options).

or using SDK and export snapshots:
```
int_snapshot_id = export_snapshot_create(title, interpolate_key_frames=True)
export_snapshot_download(int_snapshot_id)
```
Snapshot SDK example: https://github.com/heartexlabs/label-studio-sdk/blob/master/examples/export_snapshots.py
More about SDK: https://labelstud.io/sdk/project.html

**Comment by passerbythesun** [comment]
Actually, I failed with all APIs, but command line tool works, since default value of `interpolate_key_frames` is True.

`label-studio export --host http://localhost:8080 --user-token {token} {project_id} JSON`. exported data lies in directory`data/export`
