### ISSUE TITLE
UBIAI NLP annotation tools simulatio 

### ISSUE THREAD

**Issue by juhonkang** [heartexlabs/label-studio#3684]
**Is your feature request related to a problem? Please describe.**
How I can make buttons on pdf files

**Describe the solution you'd like**
FUNDS format data export?

**Describe alternatives you've considered**

**Additional context**

**Comment by makseq** [comment]
Check this comment in the relative issue:
https://github.com/heartexlabs/label-studio/issues/2634#issuecomment-1251648670
