### ISSUE TITLE
[feature request] Guiding lines for first click accuracy

### ISSUE THREAD

**Issue by S7eezy** [heartexlabs/label-studio#3686]
Hello !
I'm suggesting a little feature I've seen on other labeling tools : _Guiding lines_

**Issue**
First click accuracy while creating a bounding box is quite random without guiding lines.

**Solution**
Adding guiding lines following mouse cursor would make labeling faster because the first click wouldn't need to be re-adjusted.

**Example**
Here is an example with a 2px wide guiding line with 60% opacity :
![guidelines_example](https://user-images.githubusercontent.com/53881150/218415107-6fc78421-9c3d-4254-a914-1e0fd27cd578.png)

Thanks you for reading this,
Valentin

**Comment by makseq** [comment]
@S7eezy we call this feature `crosshair` and it can be enabled in the `<Image>` tag:

```
<View>
  <Image name="image" value="$url" crosshair="true"></Image>
</View>
```
