### ISSUE TITLE
Button to show image / Choices with images or html hypertext

### ISSUE THREAD

**Issue by nghiakvnvsd** [heartexlabs/label-studio#3694]
Hi label-studio,

I'm trying to create a link between a label and an image. When I choose that option, the image will show up as I want. Sorry, I'm not a front-end developer so a code suggestion would be great for me.

For example:
Before labeling:
![image](https://user-images.githubusercontent.com/68639058/218794821-78d14f7e-659d-44ca-bd20-04dc2585521c.png)

After labeling the eyes image (02) I would like to see an image like:
![image](https://user-images.githubusercontent.com/68639058/218793775-561426d4-fe97-44cc-aa29-d93579b74b32.png)

Sorry if my English is too bad.

Thank you!!!

**Comment by makseq** [comment]
Try this example:

```
<View>
  <Image name="image" value="$image"/>
  <Choices name="sentiment" toName="image" choice="single" value="$options">
  </Choices>
</View>

<!-- {"data": 
  {
    "image": "https://labelstud.io/images/logo.png",
    "options": [
      {"value": "1", "html": "<img src='https://labelstud.io/images/logo.png'>"}, 
      {"value": "2", "html": "<h1>hypertext h1 header</h1>"}
    ]
  }
} -->
```

![image](https://user-images.githubusercontent.com/501780/220500007-36df9ceb-a1b7-4bfe-a973-4640ab9466b9.png)

You should place choice options in task data.
