### ISSUE TITLE
Semantic segmentation labeling using brush: for one image annotation with multiple class, export multiple masks, can we just get one mask? 

### ISSUE THREAD

**Issue by chuanzhidong** [heartexlabs/label-studio#3697]
**Is your feature request related to a problem? Please describe.**
yes. Semantic segmentation labeling using brush: for one image annotation with multiple class, when I export by using brush labels to PNG, it gives multiple mask png files. can we just get one mask png file? 

![image](https://user-images.githubusercontent.com/9843463/218845268-0ba7b7f1-151a-45ef-91c6-5f6e569deda3.png)
![image](https://user-images.githubusercontent.com/9843463/218846836-b5dccec6-1401-4e5c-912b-7b1928d74a93.png)

**Comment by makseq** [comment]
@chuanzhidong In case of one image - how will you distinguish which grey level is mapped to which label? What if there are more than 255 labels?

**Comment by chuanzhidong** [comment]
> 

thanks @makseq . yes, it is hard to handle the case by just using one mask file when we have more than 255 labels.
