### ISSUE TITLE
Multiple complementations per task

### ISSUE THREAD

**Issue by mrijken** [heartexlabs/label-studio#37]
De completion json contains an array with the results. Hower, I can not manage to add multiple results. In the frontend I can add a new completion, but that complementation overwrites the previous one.

**Comment by makseq** [comment]
Label studio supports multiple completions per task. But the backend server.py is not supported it, because we planned it as a lightweight server. If you want you can add a such functionality to server.py and send PR to label-studio.

**Comment by makseq** [comment]
I looked for a quick solution. Now it's in master, file db is supporting multiple completions per task. Go to task list and then view (icon with the eye) the task with ID. In this mode you are able to have multiple completions.

**Comment by shevchenkonik** [comment]
@mrijken Please check ``master`` branch. If you have any questions about multiple completions, then you can reopen this issue.

**Comment by mrijken** [comment]
Thanx!
