### ISSUE TITLE
Outliner shows "No label" for Rectangle and cannot reassign a label

### ISSUE THREAD

**Issue by luuzk** [heartexlabs/label-studio#3700]
**Describe the bug**
When drawing a labeled rectangle (bounding box) with additional `perRegion` attributes you can deselect its label (`RectangleLabel`) by either clicking on the label in the bottom box or using the appropriate hotkey. Then the outliner and details display "No label"  but you cannot reassign any label to this rectangle and need to remove the region completely. The deselection also occurs on other unknown events by uninformed annotators. This bug is very annoying for correcting those unlabeled regions since they need to be reannotated.

**To Reproduce**
1. Create a project with the following labeling interface
```xml
<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
    <Label value="car" background="blue"/>
  </RectangleLabels>

  <Choices name="choices" toName="image" perRegion="true">
    <Choice value="wheels"/>
  </Choices>
</View>
```
2. Draw a bounding box, select it, and check "wheels"
3. Click on "car" or use the hotkey "1"
4. Now you have only checked "wheels" but cannot selected "car" again or use hotkey "1". Outliner and details show "No label" for this region and its grayed out.

**Expected behavior**
You can click on "car" or use hotkey "1" in 4. to assign "car" to the region.

**Screenshots**
Cannot upload them.

**Environment (please complete the following information):**
 - OS: MacOS 13.1, Ubuntu 22.04
 - Label Studio Version 1.7.0

**Additional context**
None.

**Comment by makseq** [comment]
@luuzk Could you try to use LS from the latest develop branch in github? We've fixed a similar problem there several days ago.

**Comment by luuzk** [comment]
I can try this. What is the associated PR?

**Comment by hlomzik** [comment]
https://github.com/heartexlabs/label-studio-frontend/pull/1168 for LSF and https://github.com/heartexlabs/label-studio/pull/3613 for LS
