### ISSUE TITLE
Adding volume mount to dockerfile command not working

### ISSUE THREAD

**Issue by SjoerdBraaksma** [heartexlabs/label-studio#3701]
**Describe the bug**
Hello! 
When I run the Dockerfile provided in the github repo with some additional commands in windows:

```
ENTRYPOINT ["./deploy/docker-entrypoint.sh"]
CMD ["label-studio","start", "test", "-l", "/mnt/settings/label_studio_ui.xml", \
    "--init", "--username", "test@test.nl", "--password", "123456"]
```

And then in docker console in windows add the optional setting to add a volume mount, everything works perfectly. it sees the settings automatically and starts the test project.

However, when i want to deploy it with the volume mount set in the Dockerfile like so: 

```
ENTRYPOINT ["./deploy/docker-entrypoint.sh"]
CMD ["label-studio","-v", "C:/mnt:/mnt", "start", "test", "-l", "/mnt/settings/label_studio_ui.xml", \
    "--init", "--username", "test@test.nl", "--password", "123456"]
```
The -v argument is not recognized. My question is: Am i doing something wrong, or is label-studio expecting something else? Where does docker on windows add the volume mount as an argument?

I've been racking my brain over this for 2 hours now, any help would be greatly appreciated!

**Comment by nikitabelonogov** [comment]
Hi @SjoerdBraaksma 
`-v` argument is a Docker argument not a Label-Studio argument 

so your docker run command should look similar to: 
```shell
docker run -it -p 8080:8080 -v "C:/mnt:/mnt" heartexlabs/label-studio:latest label-studio start test -l "/mnt/settings/label_studio_ui.xml" --init --username "test@test.nl" --password "123456"
```
