### ISSUE TITLE
Add Choice information to RectangleLabels 

### ISSUE THREAD

**Issue by Mast3rChief** [heartexlabs/label-studio#3706]
**Is your feature request related to a problem? Please describe.**
When I want to label data and add properties this is not possible for every instance of a label. I can not create a label template for rectangle or segmentation and add a custom property to it. The UI does not provide a way of doing it.

**Describe the solution you'd like**
As a user I would like to add a additional information to BoundingBox based labeling. When I add a Rectangle label  or a segmentation label for a car I want to also add if that "car" label is in "good" or "bad" condition. Therefore I need a way to add label/instance based additional information. This additional property should be added in an easy way in the UI.

**Describe alternatives you've considered**
Adding additional labels to the same region -> not nice
Adding various labels that contain properties in the label name -> not efficient

**Additional context**
This helps al lot for using your tool for classification of object conditions.

**Comment by erinmikailstaples** [comment]
Thanks for sharing @Mast3rChief — and I can see where it could come in handy.  Appreciate the detailed usecase.

**Comment by frankiert** [comment]
We had the same demand - thanks for bringing it up @Mast3rChief - and we tried to dig in.

From what I learned, I believe this is already possible (tested with 1.6.0). One example can be seen on the Label Studio Slack [here](https://label-studio.slack.com/archives/CQ8LYQ0J2/p1673952034158329).

You can define, e.g. `RectangleLabels`, then add a `Choices` tag to the Labeling Interface and set its `perRegion` attribute to true. With the `<View whenLabelValue="vehicle">` tag and attribute, you can make these Choices appear whenever the corresponding RectangleLabel of the appropriate category is selected. In the task source, the annotated Choices are refering to their respective RectangleLabels via some created id. This should also work with other annotated regions.

See the related [Slack thread](https://label-studio.slack.com/archives/CQ8LYQ0J2/p1673952034158329) for a short screencast and an example labeling configuration.

So, what exactly is the missing feature from your perspective @Mast3rChief ? (Hope this helps.)

**Comment by Mast3rChief** [comment]
Thanks for your fast reply. 

I just had a look at the Slack thread. It seems to do the trick on the UI part but an export of this is not possible.

When I export the Label with an attribute the export neglects it or stores two different labels at the same position

Here is an example where I've create two labels with additional information from "choice" and "Text". It creates 4 labels out of it.

```json
[
    {
        "id": 985373,
        "annotations": [
            {
                "id": 4359,
                "completed_by": 1,
                "result": [
                    {
                        "original_width": 2048,
                        "original_height": 2048,
                        "image_rotation": 0,
                        "value": {
                            "x": 16.834170854271356,
                            "y": 36.93467336683416,
                            "width": 13.5678391959799,
                            "height": 7.788944723618091,
                            "rotation": 0,
                            "rectanglelabels": [
                                "vehicle"
                            ]
                        },
                        "id": "Eo45zmFRWU",
                        "from_name": "track_id_img1",
                        "to_name": "img1",
                        "type": "rectanglelabels",
                        "origin": "manual"
                    },
                    {
                        "original_width": 2048,
                        "original_height": 2048,
                        "image_rotation": 0,
                        "value": {
                            "x": 16.834170854271356,
                            "y": 36.93467336683416,
                            "width": 13.5678391959799,
                            "height": 7.788944723618091,
                            "rotation": 0,
                            "choices": [
                                "white"
                            ]
                        },
                        "id": "Eo45zmFRWU",
                        "from_name": "class-img1",
                        "to_name": "img1",
                        "type": "choices",
                        "origin": "manual"
                    },
                    {
                        "original_width": 2048,
                        "original_height": 2048,
                        "image_rotation": 0,
                        "value": {
                            "x": 45.47738693467337,
                            "y": 49.49748743718592,
                            "width": 10.804020100502512,
                            "height": 10.05025125628141,
                            "rotation": 0,
                            "rectanglelabels": [
                                "license_plate"
                            ]
                        },
                        "id": "xoigdCyj-Z",
                        "from_name": "track_id_img1",
                        "to_name": "img1",
                        "type": "rectanglelabels",
                        "origin": "manual"
                    },
                    {
                        "original_width": 2048,
                        "original_height": 2048,
                        "image_rotation": 0,
                        "value": {
                            "x": 45.47738693467337,
                            "y": 49.49748743718592,
                            "width": 10.804020100502512,
                            "height": 10.05025125628141,
                            "rotation": 0,
                            "text": [
                                "abc"
                            ]
                        },
                        "id": "xoigdCyj-Z",
                        "from_name": "answer2",
                        "to_name": "img1",
                        "type": "textarea",
                        "origin": "manual"
                    }
                ],
                "was_cancelled": false,
                "ground_truth": false,
                "created_at": "2023-02-18T12:19:55.272390Z",
                "updated_at": "2023-02-18T12:19:55.272420Z",
                "lead_time": 65.887,
                "prediction": {},
                "result_count": 0,
                "task": 985373,
                "project": 18,
                "parent_prediction": null,
                "parent_annotation": null
            }
        ],
        "file_upload": "000006.jpg",
        "drafts": [],
        "predictions": [],
        "data": {
            "image1": "/data/upload/18/000006.jpg"
        },
        "meta": {},
        "created_at": "2023-02-18T12:18:43.754559Z",
        "updated_at": "2023-02-18T12:19:55.333409Z",
        "inner_id": 3,
        "total_annotations": 1,
        "cancelled_annotations": 0,
        "total_predictions": 0,
        "comment_count": 0,
        "unresolved_comment_count": 0,
        "last_comment_updated_at": null,
        "project": 18,
        "updated_by": 1,
        "comment_authors": []
    }
]
```

**Comment by frankiert** [comment]
Yes, we do see this as well in our setup. Still it can be processed as follows:

In your example there are two regions of type `rectanglelabels`. Each one has an `id` attribute, e.g. `"id": "Eo45zmFRWU"` for the first one. The related `choices` and `textarea` annotations can be associated with their respective region through their `id` attribute. Accordingly, the annotation of type `choices` belongs to the first rectangle, as it bears the same id.

At least that is our working hypothesis while we are also just starting with that kind of setup.  
Can you (or anyone) confirm this? ... And would that satisfy your request, i.e. this issue?

**Comment by Mast3rChief** [comment]
I see. But this way does not work with the COCO data export. Here this information is completely discarded. If I now want to use the same mechanism to get the "truncated" or
"difficult" information it fails. Here it is important to have the additional information not in two labels but one. More like an attribute of the original label.

```xml
<?xml version="1.0" encoding="utf-8"?>
<annotation>
<folder>images</folder>
<filename>000006.jpg</filename>
<source>
<database>MyDatabase</database>
<annotation>COCO2017</annotation>
<image>flickr</image>
<flickrid>NULL</flickrid>
<annotator>1</annotator>
</source>
<owner>
<flickrid>NULL</flickrid>
<name>Label Studio</name>
</owner>
<size>
<width>2048</width>
<height>2048</height>
<depth>3</depth>
</size>
<segmented>0</segmented>
<object>
    <name>vehicle</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
    <xmin>344</xmin>
    <ymin>756</ymin>
    <xmax>621</xmax>
    <ymax>915</ymax>
    </bndbox>
</object>
<object>
    <name>license_plate</name>
    <pose>Unspecified</pose>
    <truncated>0</truncated>
    <difficult>0</difficult>
    <bndbox>
    <xmin>931</xmin>
    <ymin>1013</ymin>
    <xmax>1152</xmax>
    <ymax>1218</ymax>
</bndbox>
</object>
</annotation>
```

**Comment by frankiert** [comment]
Ok, thanks for the clarification. To sum up, it looks as follows:

- the LabelStudio UI does already support what you need, i.e. assigning properties (here `choices`) to labeled regions via the `perRegion` attribute
- such associations between labels and choices are currently modeled via equal id attributes in LabelStudio's task source (maybe there is a better way to do that?)
- But more importantly, the currenty data export to COCO (and other formats?) does not correctly map such (subordinate) relations into coherent object annotations. Such `choices` need to be modeled as attributes to the annotated objects - which is currently not the case. Correct?

If that resembles your demand, would it be beneficial to reframe this issue accordingly? Then maybe someone will take this further. :-) Kind regards!

**Comment by Mast3rChief** [comment]
Ok, I'll reframe it. Summary sounds about right.

**Comment by makseq** [comment]
Seems the original question is solved, I am going close this issue. Feel free to open another issue regarding export.

**Comment by mihow** [comment]
@frankiert or @Mast3rChief is it possible to share you labeling configuration? The Slack thread mentioned above is no longer available. 

I have a perRegion tag working, but the selected values don't appear in the sidebar (like the way the value of regular Label tags do). Our annotators have no way of seeing a summary of everything they have annotated in an image. Thanks for any suggestions you might have!

![image](https://github.com/HumanSignal/label-studio/assets/158175/f7f36d28-49fd-4a0d-a33f-cdae2c3b8019)

**Comment by manoadamro** [comment]
@mihow 

I have something working with this:
```
<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="Car" background="blue">
    </Label>
  </RectangleLabels>
  <Choices name="choice" toName="image" perRegion="true" whenLabelValue="Airplane">
    <Choice value="Commercial"/>
    <Choice value="Military" />
    <Choice value="Hobby" />
  </Choices> 
</View>
```

But to be honest, it's pretty annoying to actually use in the editor.
