### ISSUE TITLE
Pre-prod link in blog post

### ISSUE THREAD

**Issue by smoreface** [heartexlabs/label-studio#3709]
**Describe the bug**

Hi friends!! In the latest great blog post published by y'all, there is a deploy-preview link instead of a link to labelstud.io

https://labelstud.io/blog/labeling-audio-data-with-label-studio/

> New to Label Studio or data labeling? [Check out this blog post here to get started!](https://deploy-preview-29--label-studio-website.netlify.app/blog/zero-to-one-with-label-studio/)

**To Reproduce**
1. Go to the blog post
3. Scroll down to New to Label Studio or data labeling?
4. Click the link and observe that it goes to deploy-preview etc.

**Expected behavior**
A link to https://labelstud.io/blog/zero-to-one-getting-started-with-label-studio/ instead

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

I'm familiar with this problem because I also use Netlify to deploy my blog :)

**Comment by erinmikailstaples** [comment]
Oh — hey @smoreface — I've heard some absolutely lovely things about you from the team about you (wink @lsell)

Good catch here! I'll handle this one!

**Comment by smoreface** [comment]
glad to hear it! have been enjoying the content lately, keep up the great work!

**Comment by makseq** [comment]
@smoreface Dear Sarah! Thank you for your fix! You know we love you sooo much and we are still missing you around here!

@erinmikailstaples could you please follow up to make sure this fix is done? Close this issue at the end!

**Comment by makseq** [comment]
@erinmikailstaples please close this issue when it's fixed.
