### ISSUE TITLE
Create template for Hugging Face Hub Spaces?

### ISSUE THREAD

**Issue by nbroad1881** [heartexlabs/label-studio#3713]
Hugging Face Hub Spaces now allow for Docker containers to be deployed. There is already one for [Argilla](https://huggingface.co/docs/hub/spaces-sdks-docker-argilla), and I'm wondering if your team would make one. I tried but I was unsuccessful, and since you already have one-click deploy options, I figure you could come up with something relatively easily. Having Label Studio in the HF Hub would be cool and useful for using the tool in a free manner.

**Comment by hogepodge** [comment]
@nbroad1881 We're working on this right now, and will be releasing soon!

**Comment by nbroad1881** [comment]
I just discovered the existing collaboration channel on slack between label studio and HF. Glad to see it happening! Sorry for the redundancy

**Comment by hogepodge** [comment]
Nothing to worry about! We're really excited about getting it ready to launch.

**Comment by nbroad1881** [comment]
https://huggingface.co/spaces/LabelStudio/LabelStudio 

👀
