### ISSUE TITLE
Repeater component is not working with GCS data

### ISSUE THREAD

**Issue by MarioProjects** [heartexlabs/label-studio#3716]
**Repeater component is not working with GCS data**
When I use the Repeater component with data loaded by Cloud Storage, specifically GCS, an error occurs, and no images are displayed (in this case, images).

**Tests performed:**
1. I have tried to create a task WITHOUT Repeater with those same paths to GCS, and the images load.
2. I have tested the same view with `local-files,` and it works. The images are loaded.
3. I have tried that same json loading from step 2 with the URLs from step 1, and it produces the error.

**To Reproduce**
1. Create a task with a Repeater.
```xml
<View>
  <Repeater on="$fichero" indexFlag="{{idx}}" mode="pagination">
    <Header value="Página {{idx}}"/>
    <Header value="Selecciona la clase" />
    <Filter name="filter_clase_{{idx}}" toName="clase_pagina_{{idx}}"
          hotkey="shift+f" minlength="0"
          placeholder="Filtro" />
    <Choices name="clase_pagina_{{idx}}" showInline="true" required="true" toName="pagina_{{idx}}">
      <Choice value="33_IVAAnual_555"/>
      <Choice value="25_IRPFTrimestral_F69" />
      <Choice value="111_Declaracion_anual_347" />
      <Choice value="Otro_documento" />
    </Choices>
    
    <Header value="Selecciona el documento lógico" />
    <Choices name="documento_pagina_{{idx}}" showInline="true" required="true" toName="pagina_{{idx}}">
	    <Repeater on="$fichero" indexFlag="{{didx}}">
	          <Choice value="{{didx}}"/>
	    </Repeater>    
    </Choices>
    
    <Image name="pagina_{{idx}}" value="$fichero[{{idx}}].pagina"/>
  </Repeater>
</View>
```
2. Connect your source storage to your GCS.
3. Create a json payload for the task using GCS.
```json
[
  {
    "data": {
      "fichero": [
        {
          "pagina": "gs://your_bucket_name/tmp/pool.jpg"
        },
        {
          "pagina": "gs://your_bucket_name/tmp/pool.jpg"
        }
      ]
    }
  },
  {
    "data": {
      "fichero": [
        {
          "pagina": "gs://your_bucket_name/tmp/modelo-347.png"
        },
        {
          "pagina": "gs://your_bucket_name/tmp/modelo-347.png"
        },
        {
          "pagina": "gs://your_bucket_name/tmp/modelo-347.png"
        },
        {
          "pagina": "gs://your_bucket_name/tmp/modelo-347.png"
        }
      ]
    }
  }
]

```
4. Try to label a case.

**Expected behavior**
That the images loaded by GCS in the Repeater component work.

**Screenshots**
- Server logs.
![image](https://user-images.githubusercontent.com/23385329/219851467-ecf3a82b-62be-4dc4-bbf5-175b350b65c3.png)

- Label Studio Error. 
![image](https://user-images.githubusercontent.com/23385329/219851399-09248795-15d1-46c4-8153-3dbac5e3aaec.png)

**Environment (please complete the following information):**
 - OS: `Ubuntu 20.04.5 LTS`
 - Label Studio Version: `v1.4.1post1` & `v1.7.0`

**Additional context**
None.

**Comment by makseq** [comment]
@MarioProjects 

1. Switch to the latest LS develop branch 
2. put into the root of your task data any URI with storage, e.g.:
```
{
    "data": {
      ===> "pagina": "gs://your_bucket_name/tmp/pool.jpg",  <===
      "fichero": [
        {
          "pagina": "gs://your_bucket_name/tmp/pool.jpg"
        },
        {
          "pagina": "gs://your_bucket_name/tmp/pool.jpg"
        }
      ]
    }
  }
```

Now the resolving should work.

**Comment by makseq** [comment]
We're going to support it in a more convenient way where you don't need to put a storage link at the root level.
