### ISSUE TITLE
Predictions for pre-annotation received but not populated frontend without page refresh 

### ISSUE THREAD

**Issue by nlassaux** [heartexlabs/label-studio#3717]
**Describe the bug**
After opening a task and receiving a prediction in order to pre-annotate, the UI doesn't populate the predictions.

**To Reproduce**
1. Click on a task
2. Wait for the call to /predict to happen
3. The loader disappears, prediction received (can check the task's data, predictions are there)
4. The checkboxes, in my case, aren't being populated
5. There is a console log coming with it

**Expected behavior**
The prediction appears

**Screenshots**
<img width="1792" alt="Screenshot 2023-02-19 at 00 24 45 (1)" src="https://user-images.githubusercontent.com/1917120/219904165-1186177a-6303-4c43-bd2f-cd30196b46e3.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome 109.0.5414.119 (Official Build) (x86_64)
 - Label Studio Version: The one hosted in Enterprise mode

**Comment by makseq** [comment]
@nlassaux please show
1 your labeling config
2 task and prediction code in json

**Comment by nlassaux** [comment]
Hi!

Here is the config:

```
<View>
  <Image name="image" value="$image" rotateControl="false"/>
  <Header value="Pick the features that apply to this picture"></Header>
  <Choices name="choice" toName="image" choice="multiple" showInLine="true">
  	<Choice value="fireplace"/>
    <Choice value="hardwood_floor"/>
    <Choice value="lots_of_light"/>
    <Choice value="stainless_steel_appliances"/>
    <Choice value="large_room"/>
    <Choice value="view_on_city"/>
    <Choice value="floor_to_ceiling_windows"/>
    <Choice value="kitchen_island"/>
    <Choice value="large_window"/>
    <Choice value="laminate_wood_floor"/>
    <Choice value="stone_countertops"/>
    <Choice value="ceramic_tile_floor"/>
    <Choice value="view_on_backyard"/>
    <Choice value="crown_moudling"/>
    <Choice value="quartz_countertops"/>
    <Choice value="vaulted_ceiling"/>
    <Choice value="high_ceilings"/>
  	<Choice value="ceramic_tub_surround"/>
    <Choice value="walk_in_shower"/>
    <Choice value="balcony"/>
    <Choice value="built_in_shelves"/>
    <Choice value="corner_unit"/>
    <Choice value="custom_wood_archway"/>
    <Choice value="finished_basement"/>
    <Choice value="floor_to_ceiling_cabinets"/>
    <Choice value="french_doors"/>
    <Choice value="master_bedroom"/>
    <Choice value="nothing"/>
    <Choice value="patio"/>
    <Choice value="sliding_barn_door"/>
    <Choice value="sliding_glass_door"/>
    <Choice value="stainless_steel_range_hood"/>
    <Choice value="tray_ceiling"/>
    <Choice value="view_on_lake"/>
    <Choice value="view_on_ocean"/>
    <Choice value="walk_in_closet"/>
  </Choices>
</View>
```

And for the tasks and prediction code:

```

{
  "id": 38678539,
  "data": {
    "image": "https://storage.googleapis.com/hello-data-ai-datastudio/pictures-to-features/pictures/64495c27462d9310b3b8217b3ee22e3f-uncropped_scaled_within_1536_1152.webp?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=label-studio%40hello-data-ai.iam.gserviceaccount.com%2F20230221%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230221T211228Z&X-Goog-Expires=600&X-Goog-SignedHeaders=host&X-Goog-Signature=6a16b68853d5b9f6448df25a29cfc1dd5f6686131446759070983551f32bd3a4b2743c14222f0abdf2ae0a8dca94188d3fe928668d915bfb3d4034d6609f855c639cf85dd70ba6a091cb7a04d4018ca48f71a9124cf745775257d724c7be70d5f07eacd87b4995256fe85d806fa3701339874effe5348dbce1d724823ab0a4f95d63f162d6b5ea8ba702bc74c5a13556033d852ad49ab594612ac52594219532d6285a386a8cc2137109e34c0307e2cdaa5d58f93cd7cd79e0d5f9578467f8a996ffd62c1caee3cf421943d5c3e7eb8c134c2e1bfc5f28aaacd7b4a769259bb785ade7d55a2e5d261abbecff109d8ae5a75387889ecbe2934dc876261ca25bb2"
  },
  "annotations": [],
  "predictions": [
    {
      "id": 8583078,
      "model_version": "INITIAL",
      "created_ago": "0 minutes",
      "result": [
        {
          "type": "choices",
          "score": 1,
          "value": {
            "choices": [
              "lots_of_light",
              "stainless_steel_appliances",
              "laminate_wood_floor"
            ]
          },
          "to_name": "image",
          "from_name": "choice"
        }
      ],
      "score": 1,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2023-02-21T21:12:25.309592Z",
      "updated_at": "2023-02-21T21:12:25.309606Z",
      "task": 38678539
    }
  ]
}
```

**Comment by nlassaux** [comment]
I forgot to mention: 

- if I hard-refresh the page, the prediction appears, so it's probably correctly formatted
- it works for a random number of tasks (2, 3), and then breaks again and I can't see any prediction until I hard-refresh again

**Comment by jdixosnd** [comment]
I am also facing a similar issue with NER and Object detection. After getting the prediction result it won't highlight or populate the predicted data. I have to switch the task or reload the page to make it work.

**Comment by makseq** [comment]
@nlassaux @jdixosnd 
1 you see a new prediction in the dropdown, but when you select it - aren't there populated labeling for your task? 
OR 
2 you don't see a prediction and you have to refresh the task (or the page)

(2) - is normal behaviour, LS doesn't refresh task state on the fly, the state is triggered by task switching.

**Comment by nlassaux** [comment]
- What dropdown are you referring to?
- What I see happening seems to be 2), you are right
- Although, after refreshing, if I go to a new task without any prediction, it gets the prediction and displays it on the fly after the loading bar disappears. So, would _that_ be the bug? It shouldn't do that at all, and makes 2) look like the bug?
- IMO being able to see predictions without having to switch to another task and come back is really a better experience

**Comment by makseq** [comment]
I meant a dropdown with the annotation list in the quickview mode:
![image](https://user-images.githubusercontent.com/501780/221735873-fe922f6a-e86a-42ac-a09f-feb84cfccc55.png)

**Comment by NaumanHSA** [comment]
So it happens to me also. When I load a new task, it takes time for the predictions to be made and I can see in the console too but the prediction wouldn't render on the front-end page. Also, nothing in the dropdown menu (@makseq has showed above). When I click on submit button after loading, the predictions appears in the dropdown menu. This should has to be rendered on its own without page refresh/hit submit button.

Another problem with me is when I switch to another task without clicking the submit button, I can't load the same task again. It would go to infinite loading screen which cannot be resolved even by refreshing. This is a serious bug. I'm using label-studio version 1.7.1 and Windows 10.

**Comment by nlassaux** [comment]
I can confirm, I cannot see anything in the dropdown

**Comment by makseq** [comment]
Should be fixed in the latest develop.
