### ISSUE TITLE
Display information by the model without saving it as data

### ISSUE THREAD

**Issue by Colanim** [heartexlabs/label-studio#372]
I need to display some information to the annotator. This information is computed (like pre-labeling) by a model, and displayed to the annotator for easier labeling. 

But I don't want to save this information in the labels.

---

**Is there anyway to have data computed by a model and displayed to the user without saving it as label ?**

**Comment by makseq** [comment]
Is it textual information? Have you an example?

**Comment by Colanim** [comment]
Basically I just want to show the number of tokens in a text.

So the unlabeled data is just text, I would like to display the number of tokens in this text (so, run some code to tokenize the input data and count the number of tokens). Then the user can see this information and label the data. 
This information should not be saved as label though.

**Comment by makseq** [comment]
Can you describe more detailed why don't you want to use label config for this info? 
For example [this way](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CHeader%20value%3D%22%24header%22%2F%3E%3Cbr%3E%20%20%3Cbr%3E%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%2F%3E%3Cbr%3E%20%20%3Cbr%3E%20%20%3CChoices%20name%3D%22sentiment%22%20toName%3D%22text%22%20choice%3D%22single%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Correct%22%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Wrong%22%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E%3Cbr%3E%3C!--%20%7B%20%22header%22%3A%20%22Token%20count%20%3D%2010%22%2C%20%22text%22%3A%20%221%202%203%204%205%206%207%208%209%200%22%7D%20--%3E%3Cbr%3E).

**Comment by Colanim** [comment]
Thank you ! That seems perfect for my use case. However I don't understand where the number of tokens is computed ?

**Comment by makseq** [comment]
It's a little bit different. Sorry to confuse you.

For this label config:
```
<View>
  <Header value="$**header**"/>
  
  <Text name="text" value="$**text**"/>
  
  <Choices name="sentiment" toName="text" choice="single">
    <Choice value="Correct"/>
    <Choice value="Wrong"/>
  </Choices>
</View>
```

Your tasks json for import to LS will be: 
```
[
  { "header": "Token count = 3", "text": "1 2 3"}, 
  { "header": "Token count = 4", "text": "1 2 3 4"}
]
```

So, you need to calculate token count before import. Is it ok for you? 

Example in python: 
```
import json 

texts = ['1 2 3', '1 2 3 4']
import_tasks = []
for text in texts: 
  task = {
    'header': 'Token count = ' + str(len(text.split())),
    'text': text
  }
  import_tasks.append(task)
  json.dump(import_tasks, open('import_tasks.json', 'w'))
```

**Comment by Colanim** [comment]
Thanks for the detailed answer !

I would be interested in the ML backend, but as far as I understood, ML backend can predict only labels, am I right ?

Can it predict something else ? (the content of `header` in my case) So it would not be saved as labels.

**Comment by makseq** [comment]
ML can predict every tag that has name=xxx attribute. The prediction format will use these names as output keys in json results. And predictions are very similar to completions. Read more about predictions in the docs: 
https://labelstud.io/guide/tasks.html#Basic-format

**Comment by makseq** [comment]
So, you can have <TextArea name="textarea"> and than use "textarea" key in prediction dict.
