### ISSUE TITLE
Search project by name/filter

### ISSUE THREAD

**Issue by Raven888888** [heartexlabs/label-studio#3721]
**Is your feature request related to a problem? Please describe.**
When I have many projects in label studio, I want to be able to quickly search the project by name or some filters.
![image](https://user-images.githubusercontent.com/58241952/220268527-db47f0d4-2da8-4030-83c7-38c0a5357928.png)

**Describe the solution you'd like**
A search bar with some addition filters (by creation date, creator, etc) on projects page.

**Describe alternatives you've considered**
No other way to search the project.

**Additional context**
Labelstudio v1.7

**Comment by ghost** [comment]
@Raven888888 thanks for your feedback, while I don't have an exact timeline, it's something we are planning on delivering in early Q2

**Comment by Raven888888** [comment]
@skim1000 Glad to hear that! Please ping me in this ticket when it is ready, happy to try it out!

**Comment by Raven888888** [comment]
@skim1000 @makseq Any update to this small feature?

**Comment by makseq** [comment]
@Raven888888 yes, this feature was added in our enterprise/saas solutions. You can try it here: https://app.humansignal.com/user/trial

**Comment by Raven888888** [comment]
When will it be available on the community version?
