### ISSUE TITLE
v1.7.1 version tag incorrect in __init__.py

### ISSUE THREAD

**Issue by 35grain** [heartexlabs/label-studio#3727]
**Describe the bug**
I was close to pulling my hair seeing the version didn't update when updating my Docker image, but turns out the version tag was never updated for the `__init__.py` file: https://github.com/heartexlabs/label-studio/blob/1.7.1/label_studio/__init__.py

**To Reproduce**
1. Update to 1.7.1
2. Check the web application for version number

**Expected behavior**
Displayed version should be 1.7.1.

**Screenshots**
![pilt](https://user-images.githubusercontent.com/7030797/220697657-928dd4b0-7e70-4234-8f1c-3d88384594e6.png)

**Environment (please complete the following information):**
 - OS: Docker image
 - Label Studio Version 1.7.1/latest

**Comment by makseq** [comment]
Thank you for your feedback. Unfortunately we can't fix it for already released versions of LS, however the new versions should have the correct version numbers.
