### ISSUE TITLE
Multiple TextArea controls

### ISSUE THREAD

**Issue by nikhilxb** [heartexlabs/label-studio#373]
**Is your feature request related to a problem? Please describe.**
For each data point, I need to add multiple `TextArea` controls. Right now it seems like only a single `TextArea` is allowed, and on submission (pressing enter), only that field is submitted along with any other `Choices` that happen to be selected

**Describe the solution you'd like**
Multiple `TextArea` are all submitted in batch with other tags (e.g. `Choices`) by clicking a single submit button.

**Comment by makseq** [comment]
> Right now it seems like only a single TextArea is allowed

LS can have multiple TextAreas, check this example: 

```
<View>
  <Header value="Please read the text" />
  <Text name="text" value="$text" />

  <Header value="Question 1" />
  
  <TextArea name="answer1" toName="text" 
            showSubmitButton="true" maxSubmissions="1" editable="true"
            required="true" />
  
  <Header value="Question 2" />
  
  <TextArea name="answer2" toName="text"
            showSubmitButton="true" maxSubmissions="1" editable="true"
            required="true" />
</View>
```
But you need to press Enter on each TextArea to save the value before press Submit.

> Multiple TextArea are all submitted in batch
It's a good point, I will discuss it with our front-end team.

**Comment by hlomzik** [comment]
Hi, @nikhilxb! I checked different configurations with TextAreas and they all works well! Even submit works as you expected — you don't even have to add values from textareas by Enter actually. And if you have perRegion textareas they work as well.
Could you please provide us with your config and more details about interactions? I'm a bit confused of "on submission (pressing enter)" phrase — on Enter you'll just add text from textarea but not submit all the task.
