### ISSUE TITLE
Import inefficiencies

### ISSUE THREAD

**Issue by anishnag** [heartexlabs/label-studio#3731]
We have annotated 300k tasks out of 500k tasks. When we attempt to import a single additional task, the request times out because of some backend logic that updates each existing annotated audio with an `is_labeled` attribute.

Upon a import request, the `create` function of `ImportAPI` in the `data_import` folder ultimately calls `bulk_update_stats_project_tasks(self.tasks.filter(Q(annotations__isnull=False)))` since `tasks_number_changed=True` upon an attempted import. This function iterates through all annotations and marks them as `is_labeled`.

Is this necessary to do upon an import? It seems like those other records don't need to be touched. If it is necessary, is there not a more efficient way of doing this as to avoid iterating through the annotations each time?

**Comment by makseq** [comment]
Thank you for your investigations.

For opensource it makes sense, but we use it extensively in enterprise version. 
If you prepare a PR with fix, we can consider it. Something like:

```
if settings.VERSION_EDITION != 'Community':
  bulk_update_stats_project_tasks(...)
```
