### ISSUE TITLE
import yolo format pre-annotated images

### ISSUE THREAD

**Issue by dasrocky** [heartexlabs/label-studio#3740]
Hello,
I have been trying to import yolo format annotated images for a while. Sadly nothing works, i followed links from [official guide  local-storage](https://labelstud.io/guide/storage.html#Local-storage), [YOLO import issue](https://github.com/heartexlabs/label-studio/issues/2036#issue-1140332032), [Load pre-annotated data error](https://github.com/heartexlabs/label-studio/discussions/3327), [labelling issue](https://github.com/heartexlabs/label-studio/discussions/3711). 

The weird thing is that although the **file link from json import is correct it still doesnt show the images on label studio**
![image](https://user-images.githubusercontent.com/61043834/221539779-066f0b4b-2ff2-486a-97f6-0f94c9e29192.png)
I tried modifying the class json import file that was created from label-studio-convertor by adding `/data/local-files/?d=/home/anon/sample/images/abcdefg.jpg`
![image](https://user-images.githubusercontent.com/61043834/221540527-cfae2f45-1112-4acf-9cba-7f84e6918fd6.png)

i tried so many iteration or modification still doesn't work. Always with same error and the image does not display in the tasks tab but the annotation does.

**File Structure**
-> /home/anon/sample
inside the folder: 
- images
- labels
- classes.label_config.xml
- classes.json
- classes.txt
- data.yaml

**Steps taken:*
1. First ran the command `LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/home/anon/sample/ label-studio`
2. then converted existing yolo formats using label-studio-convertor `label-studio-converter import yolo -i /home/anon/sample/ --image-root-url /home/anon/sample -o /home/anon/sample/classes.json`
3. Created new project
4. skipped import
5. In labelling setup, code copied from "classes.label_config.xml" and save.
6. Open the project
7. Create local storage, location `/home/anon/sample/` (screenshot attached)
8. then import the json

Tried with different steps:
1. same repeated steps 1 till 7
2. then click sync storage
3. finally import the json

**Environment:**
 - OS: Ubuntu 22.04
 - Browser: Brave and chrome both tried
 - Label Studio Version: 1.7.1
 - Python: 3.10.9
 - Yolo version: yolov5

**Screenshots**
- Files structure
![Screenshot](https://user-images.githubusercontent.com/61043834/221542305-4b930076-5f66-4d52-bc3f-b2bf36830629.png)
- **Command to start Label Studio**
![Screenshot](https://user-images.githubusercontent.com/61043834/221543195-c067fa47-7a88-415c-a367-50b1769afbec.png)
- Command to import pre-annotated yolo images
![Screenshot](https://user-images.githubusercontent.com/61043834/221543410-78ff69c5-92be-47e5-98bd-81a1763c2061.png)
- Labelling setup - from xml generated
![Screenshot](https://user-images.githubusercontent.com/61043834/221543818-0df15837-6229-4bd4-9422-5ec0eb5793d4.png)
- Cloud Storage - Local Files
![Screenshot](https://user-images.githubusercontent.com/61043834/221543018-614e1dc6-4718-4f7a-97a4-e7173378d175.png)
- The problem
![Screenshot](https://user-images.githubusercontent.com/61043834/221543746-653f358b-5f55-431c-88f2-d4992699b854.png)
![image](https://user-images.githubusercontent.com/61043834/221544402-bfcc62e2-e756-4112-a6f4-13ffd684f106.png)

Not sure is this bug or something else. please help, coz am not sure what am doing wrong. I tried browsing about it more unfortunately no results.

**Comment by makseq** [comment]
@dasrocky LS doesn't support direct import for YOLO format. You have to convert it to LS JSON format: 
https://github.com/heartexlabs/label-studio-converter/pull/46

**Comment by dasrocky** [comment]
> @dasrocky LS doesn't support direct import for YOLO format. You have to convert it to LS JSON format: [heartexlabs/label-studio-converter#46](https://github.com/heartexlabs/label-studio-converter/pull/46)

I have done this on step 2 mentioned above, only difference from the code suggested `label-studio-converter import yolo -i /home/anon/sample/ --image-root-url /home/anon/sample -o /home/anon/sample/classes.json`, only difference in code was i created `classes.json` rather than `ls-tasks.json`. Is this the mistake am doing?

**Comment by makseq** [comment]
Try this, without classes.json:

label-studio-converter import yolo -i /home/anon/sample/ --image-root-url /home/anon/sample -o /home/anon/sample/

**Comment by dasrocky** [comment]
> Try this, without classes.json:
> 
> label-studio-converter import yolo -i /home/anon/sample/ --image-root-url /home/anon/sample -o /home/anon/sample/

sorry for late reply, it gives an error saying it is directory. So i tried this instead of classes.json `label-studio-converter import yolo -i /home/anon/sample/ --image-root-url /home/anon/sample -o /home/anon/sample/ls-tasks.json` but still the same error
![Screenshot from 2023-03-07 17-42-42](https://user-images.githubusercontent.com/61043834/223439923-bfe2c796-054c-47de-b25c-78c0d8be2524.png)

**Comment by makseq** [comment]
Sorry, my previous message was with mistake, try this
```
label-studio-converter import yolo -i /home/anon/sample/ -o /home/anon/sample/
```
your `--image-root-url` is incorrect and you don't need to modify it if you are using the local storage.

**Comment by dasrocky** [comment]
> `label-studio-converter import yolo -i /home/anon/sample/ -o /home/anon/sample/`

still the same error `IsADirectoryError: [Errno 21] Is a directory: '/home/anon/sample'. code doesn't allow us to add only directory it needs a json file name. 
![image](https://user-images.githubusercontent.com/61043834/223656704-7d01d3ab-fc5b-4afa-b783-03d1ef021aed.png)

on another note, i have noticed a lot of issues regarding importing yolo pre-annotated dataset. it would be better to have an example of such process(video or each steps etc.) on the documentation website. what do you think of this idea? also am old user of labelimg, just recently came across label-studio  btw. Maybe i can make a video later and share it here if the problem is fixed.

**Comment by biqiongyu** [comment]
Same issue here. I managed to fix it by setting `--image-root-url /data/local-files/?d=images/` The default path missing 'images/'

**Comment by makseq** [comment]
@dasrocky sorry again, I missed another mistake in your call, let's use this:
```
label-studio-converter import yolo -i /home/anon/sample/ -o /home/anon/output.json --image-root-url "/data/local-files/?d=images/"
```

So, you have to set environment variables 

```
LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/home/anon/sample/
```

for Label Studio run and add a Local Storage in the Project Settings 
with `Absolute local path` = `/home/anon/sample/images`.

You can check the tutorial here:
https://github.com/HumanSignal/label-studio-converter/tree/docs-yolo-import?tab=readme-ov-file#yolo-to-label-studio-converter

**Comment by makseq** [comment]
@biqiongyu it depends on how you setup your local storage: if you point it to /image folder directly, you don't need to use `images/` in image-root-url

**Comment by PawelKinczyk** [comment]
@dasrocky did you fix that? i have the same problem. In my case the image pope for 1/2 seconds and then i get error. But i have one more question.

[Edit] I work around this by adding url like in this video https://www.youtube.com/watch?v=lo6ncQajbdU for my dataset:
`label-studio-converter import yolo -i /home/pan_pawel/Documents/GitHub/AECVision/import_prediction_images/ --image-root-url /data/local-files/?d=dataset1 -o podejsciedatasetrootNEW.json
`

**Comment by patcharees** [comment]
@makseq Does LS support YOLO segmentation (polygon)? How to import and export?

**Comment by nadinator** [comment]
Why has this issue been marked as closed @makseq ? It's clearly still a problem, and I'm running into it myself now with no solution found. Even the workarounds others have specified didn't work for me.

**Comment by nadinator** [comment]
@PawelKinczyk can you share what your Cloud Storage settings looks like? This workaround isn't working for me.

**Comment by Sakthiprian** [comment]
I have setup local storage with document root as C:/yolo/datasets. I was planning on using this datasets folder to organise all my projects. I have one folder named "one" where i stored images,labels,classes.txt. label studio converter gave a config file. I setup local storage by giving absolute path C:/yolo/datasets/one/images and toggled on "Treat every bucket object as a source file". Labelling interface is also set by copying the XML which was generated by label-studio-converter. On importing config json file, the images are successfully pulled into label-studio.

Now the problem is, if i follow the exact same steps, Im not able to pull images from C:/yolo/datasets/two/images. I have ensured correct label-studio-converter arguments including "--image-root-url". Does anyone know how to solve this. I dont want to point document root directly to this new project everytime to make it work.

**Comment by aurexav** [comment]
Windows users, please check https://github.com/HumanSignal/label-studio/issues/6173!!!

**Comment by peterpresti** [comment]
We struggled on this failing with no annotations imported and discovered that the extension is case sensitive.  If your images are .JPG, then leaving the default or specifying .jpg will fail.  Adding "--image-ext .JPG" to the command line solved the import problem.
