### ISSUE TITLE
Documentation of Multi page annotation doesn't correspond to the template

### ISSUE THREAD

**Issue by AmineDjeghri** [heartexlabs/label-studio#3746]
My issue concerns the documentation website of [Multi page annotation](https://labelstud.io/templates/multi-page-document-annotation.html) : 
The docs show that we need to use this importing data : 
```
[{
  "data": {
    "pages": [{
      "image": "image-1-url"
    }, {
      "image": "image-2-url"
    }, {
      "image": "image-3-url"
    }]
  }
}]
```
but the The template contains in the application shows that we need to use this :

```
 {
"document": [
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0001.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0002.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0003.jpg"
    }
  ]
} 
``` 
```
<View>
  <Repeater on="$document" indexFlag="{{idx}}" mode="pagination">
      <Image name="page_{{idx}}" value="$document[{{idx}}].page" inline="true"/>
      <RectangleLabels name="labels_{{idx}}" toName="page_{{idx}}">
        <Label value="Title" background="green" />
        <Label value="Date" background="blue" />
        <Label value="Author" background="yellow"/>
        <Label value="Organization" background="orange"/>
        <Label value="Amount" background="red"/>
      </RectangleLabels>
      <View style="display: flex; justify-content: center;">
        <Header value="Rate this page:"/>
        <Rating name="rating_{{idx}}" toName="page_{{idx}}"/>
      </View>
  </Repeater>
</View>


<!-- {
"document": [
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0001.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0002.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0003.jpg"
    }
  ]
} -->
```

**Comment by makseq** [comment]
Sorry, we are going to remove the Repeater tag at all. It can't work with big number of entities :-( So, we just remove this page entirely soon.

**Comment by sloth2012** [comment]
So will you design an alternative like Repeater that supports multi-page documents?

**Comment by makseq** [comment]
Yes, for images we have Multi Image seGmentation (MIG). You can try it from the latest develop branch, you have to run LS this way `feat_front_lsdv_4583_multi_image_segmentation_short=1 label-studio` and use <Image valueList="$images"> where images are array.

**Comment by philippeboyd** [comment]
@makseq any news on this? Has the feature been released? I'm trying to figure out if we keep using the `Repeater` tag or not.

**Comment by CrisRodriguez** [comment]
Hello @makseq,

I would like to know if u have any news on this. We do not know whether Repeater will be deprecated soon. Can u please give us some visibility?

Thanks,
