### ISSUE TITLE
Mark on the picture, corresponding to the text

### ISSUE THREAD

**Issue by tianchiguaixia** [heartexlabs/label-studio#3751]
![image](https://user-images.githubusercontent.com/29837553/221806704-cbb70f7f-99f2-4d55-98ed-6823753fdf4a.png)
Hello, please tell me how to configure my templates so that I can mark on the image and automatically export the text entity. As I showed in my picture, after I marked the picture, I exported the text and corresponding entities of the whole picture analysis

**Comment by makseq** [comment]
Hello, this functionality is not supported, you can't label just entered text in the same task. To achieve this, you have to setup 2 projects: the first one for image => text extraction, the second one for text => NER labeling.
