### ISSUE TITLE
can't install on mac m1 pro

### ISSUE THREAD

**Issue by JasonChenJC** [heartexlabs/label-studio#3775]
It cannot be installed on Mac M1 Pro because the required package psycopg2-binary==2.9.1 does not support the Apple M1 Pro chip even if psycopg2-binary==2.9.5 has already been installed.

How can I solve this problem

**Comment by goonhoon** [comment]
Same issue on WIndows 10 on Python 3.11

**Comment by makseq** [comment]
@JasonChenJC Install LS using brew
```
brew install label-studio
```

@goonhoon 
Try to use Anaconda python. As I remember not all packages are built for python 3.11. Also you can switch to 3.10.

**Comment by JasonChenJC** [comment]
> @JasonChenJC Install LS using brew
> 
> ```
> brew install label-studio
> ```
> 
> @goonhoon Try to use Anaconda python. As I remember not all packages are built for python 3.11. Also you can switch to 3.10.

I have tried it before but it didn't work, and the same problem cannot be avoided.

But i fix this problem flow this:
clone source code and change psycopg2-binary version in requirments. 
then Install all package dependencies by "pip install -e ."

**Comment by makseq** [comment]
which psycopg2-binary version do you use now?

**Comment by JasonChenJC** [comment]
> which psycopg2-binary version do you use now?

The latest vesion, 2.9.5

**Comment by makseq** [comment]
Ok, we upgraded the psycopg2 version in the latest develop commits.
