### ISSUE TITLE
ImportError: No module named label_studio.ml

### ISSUE THREAD

**Issue by rotorooter101** [heartexlabs/label-studio#378]
Hi, I'm following the instructions to start up a model backend without docker, and when I run:

label-studio-ml start ~/Projects/myProject/my_first_backend

I get the following error:

Traceback (most recent call last):
  File "/home/user/Projects/myProject/my_first_backend/_wsgi.py", line 5, in <module>
    from label_studio.ml import init_app
ImportError: No module named label_studio.ml

however I have no trouble importing label_studio in a typical python session. Could I get a hint on how to solve this path error?

**Comment by makseq** [comment]
What LS version do you use?

**Comment by makseq** [comment]
@rotorooter101 up

**Comment by nabinkhadka** [comment]
`pip install -e .` ?

**Comment by makseq** [comment]
I hope nabinkhadka solution will work for you.

**Comment by iasoon** [comment]
I also ran into this issue, I believe the cause was the use of the 'python' command here: https://github.com/heartexlabs/label-studio/blob/master/label_studio/ml/server.py#L96 .

I'm using a legacy system where python still refers to python 2. For working around this, I think you can just manually run the _wsgi.py file in your backend directory?

**Comment by ranch-hands** [comment]
hi. when I type : 
`from label_studio_ml.app import create_app'
`
I get this error: `ModuleNotFoundError: No module named 'label_studio_ml.app`
label-studio-ml Version: 1.0.9
could you help?

**Comment by anjanavellali03** [comment]
File "/home/anna/hybrid1/label-studio-ml-backend/my_ml_backend/model.py", line 9, in <module>
    from label_studio_ml.model import ModelResponse
ImportError: cannot import name 'ModelResponse' from 'label_studio_ml.model' (/home/anna/hybrid1/label-studio-ml-backend/my_ml_backend/venv/lib/python3.10/site-packages/label_studio_ml/model.py) does anyone know the solution
