### ISSUE TITLE
Change color of selected item

### ISSUE THREAD

**Issue by barney2074** [heartexlabs/label-studio#3788]
Hello

Is it possible to change the color of the highlighted current item in the left pane ?- the very light blue is quite difficult to see
thank you

Andrew
![Screenshot from 2023-03-07 16-17-06](https://user-images.githubusercontent.com/25944617/223331796-a5eddbf4-9148-480f-b0a3-2590f84467b3.png)

**Comment by makseq** [comment]
@barney2074 this possible only if you rebuild data manager and modify this color there. 
It's here: https://github.com/heartexlabs/dm2/blob/0f704d7c7a8ab5182fe7cd957c07bf8425c802a3/src/components/Common/Table/Table.styl#L62
