### ISSUE TITLE
Mobile support for NER

### ISSUE THREAD

**Issue by mabounassif** [heartexlabs/label-studio#379]
**Describe the bug**
Visit https://app.labelstud.io/setup on iOS safari. Try to tag using the NER. Selecting text and then tapping category does not label the text

**To Reproduce**
1. Go to 'https://app.labelstud.io/setup' via mobile safari
2. Click on NER task
3. Select text
4. Select category
5. No event registered

**Expected behavior**
I expect that the text I highlighted via the iOS keyboard gets categorized properly

**Screenshots**

**Environment (please complete the following information):**
 - OS: iOS
 - Browser safari

**Comment by makseq** [comment]
Yes, it's not obviously, but there is a such way to label NERs on iOS: 

1. Select category (this step is first always on all devices)
2. Select text
3. After you see iOS menu with "Copy" "Find" "Share" (etc) - double click on the outside rest of the text (not fast double click!)

4. (optionally) if you selected some region and want to escape of selection - press "unselect" button on Result panel.

**Comment by makseq** [comment]
@mabounassif up :slightly_smiling_face:

**Comment by mabounassif** [comment]
It worked! As you said, wasn't intuitive at the beginning, but it grew on me. I wonder if it can be a more snappy experience. I am integrating the front-end and I am learning the ropes, will let you know as soon as I would be able to provide a PR with an enhancement. We can probably close this issue otherwise.

**Comment by makseq** [comment]
PR will be awesome! Thanks.
