### ISSUE TITLE
Tasks per user

### ISSUE THREAD

**Issue by mrijken** [heartexlabs/label-studio#38]
**Is your feature request related to a problem? Please describe.**
We want multiple experts to label one item/task.

**Describe the solution you'd like**
In the frontend we want to select a user (for this moment authentication is not required), so the user can walk through his own task list. The results of all users will be stored in the same completion json as an array of results.

**Describe alternatives you've considered**
We can run an instance per user, but that is not scalable.

**Additional context**
n/a

**Comment by deppp** [comment]
Hey @mrijken 

As of right now, label studio is intended to be a simple one person per labeling project. We have a commercial offering where you can distribute the same task to multiple experts. Check it out and let me know if that's something interesting to you.

**Comment by doantientai** [comment]
The capacity to assign tasks to users will be very useful!

**Comment by makseq** [comment]
@doantientai it's done in the enterprise version of LS.
