### ISSUE TITLE
Setup labeling config using API

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#380]
For consistency and convenience request ability to upload labeling config using an **API** 
Just like you can:

- [Import using API](https://labelstud.io/guide/tasks.html#Import-using-API)
- [Retrieve tasks using API](https://labelstud.io/guide/tasks.html#Retrieve-tasks-using-API)
- [Export using API](https://labelstud.io/guide/export.html#Export-using-API)

If API already available please document at https://labelstud.io/guide/setup.html#Labeling-config

**Comment by makseq** [comment]
https://labelstud.io/guide/tasks.html#Import-using-API
Check import and retrieve api here.

Export api you can find using web interface. It's not documented but it's very simple.

**Comment by makseq** [comment]
Right now you can use API in a such way:


Save labeling config for the project using API: 
```
POST api/save-config/api/save-config
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Form Data: label_config=%3CView%3E%0D%0A%20%20%3CLabels%20nam…ue%3D%22%24text%22%2F%3E%0D%0A%3C%2FView%3E%0D%0A
```

The backend should return status 201 if config is valid and saved. 
If errors occur the backend returns status 400 and response body will be JSON dict: 
```
{
  "label_config": ["error 1 description", " error 2 description", ...]
}
```

But I think it's not very comfortable to use Form Data as request data. So, I've added json data as input to this API in release/0.7.4 branch. Can you check it?

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio/pull/350

**Comment by makseq** [comment]
@laynr

**Comment by laynr** [comment]
@makseq yes, the Form Data api worked - thank you! Currently I am not in a place I can check JSON - sorry. looking forward to 0.7.4 - good work!

**Comment by laynr** [comment]
@makseq on further thought what do you think of allowing "application/xml" as the label config is in xml?  I image most people will save their configs as XML files and then will want to post the XML via the api.  so in python something like:

xml = """<View>

  <Header value="Select label and start to click on image"></Header>
  <Image name="image" value="$image"></Image>

  <PolygonLabels name="label" toName="image" strokeWidth="3" pointSize="small" opacity="0.9">
    <Label value="Airplane" background="red"></Label>
    <Label value="Car" background="blue"></Label>
  </PolygonLabels>

</View>"""
headers = {'Content-Type': 'application/xml'}
requests.post('...api/save-config/api/save-config', data=xml, headers=headers)

**Comment by makseq** [comment]
@laynr It's a good idea, but I think we make it not soon. You may contribute and make a PR :)

**Comment by laynr** [comment]
@makseq as request submitted a PR (https://github.com/heartexlabs/label-studio/pull/586) to enable uploading configs via the API  as XML files.
