### ISSUE TITLE
API route to get a list all export storage connections not functionning

### ISSUE THREAD

**Issue by remicuingnet** [heartexlabs/label-studio#3806]
**Describe the bug**
When calling the api  `api/storages/export/gcs` as detailed in https://labelstud.io/api#operation/api_storages_export_gcs_list
the obtained response is 
```
{"id":"cf1ac7c9-2891-4a7c-bb03-efd1d589ba7e","status_code":404,"version":"1.7.1","detail":"Not found.","exc_info":null}
```

Similar behavior with  `api/storages/export/s3` and `api/storages/export/azure`, 

**To Reproduce**
call with `curl`

**Expected behavior**
the response should contain the list of all existing storage connections.

**Environment (please complete the following information):**
 - OS: ubuntu
 - Label Studio Version 1.7.1

Thanks

**Comment by makseq** [comment]
Your forgot to add ?project=<id>: 
```
api/storages/export/gcs?project=<id>
```

**Comment by remicuingnet** [comment]
Sorry I thought I had tried that.
Many thanks!
