### ISSUE TITLE
bad request when try to retrieve s3 file

### ISSUE THREAD

**Issue by jedzill4** [heartexlabs/label-studio#381]
**Describe the bug**
Bad request 400 when try to retrieve from external source (s3 bucket)

**To Reproduce**
* s3/ec2 setups:
  1. Setup CORS on s3 bucket to grant GET permission from ec2 instance
  2. Grant ec2 permission to access s3 bucket (AWS security roles)
* web
  1. setup s3 source on Tasks
  2. Start labeling

**Expected behavior**
Retrieve and display audio file

**Screenshots**
![ss](https://user-images.githubusercontent.com/13605417/88948595-7e8fb380-d268-11ea-90aa-1bdb6f4c7724.png)

**Environment (please complete the following information):**
 - OS: docker image running on ubuntu 20.04 aws server. Archlinux as client
 - Browser Firefox/Chrome
 - Version docker latest (0.7.3)

**Additional context**
By default, the bucket is blocking all public request, but i tested if making it public solve the issue but it persists

**Comment by jedzill4** [comment]
I think it relates with the signature parameter on the generated url.  The structure is:

https://**BUCKET**.s3.amazonaws.com/path/to/file/filename?AWSAccessKeyId=**AWS_ACCESS_KEY_ID**&Signature=**SIGNATURE**&Expires=**EXPIRATION**

When I remove it, it works (now I'm testing using my bucket public, so maybe it's not required?). Could it be that the signature generation has something wrong?

Here are the signature and url generation docs: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

**Comment by wdvr** [comment]
Had the same issue. Turns out it is indeed the default boto signature generation that doesn't work on all regions (new regions, introduced after 2014). 

Way to reproduce: use a bucket in e.g. eu-central. Images do not load as a result.

I submitted a merge request with the change that fixed it for me: https://github.com/heartexlabs/label-studio/pull/402. 
Additionally, you may have to create a `~/.aws/config` file to set the region the bucket is in. 

Example:
```
[default]
region=eu-central-1
```

**Comment by maximveksler** [comment]
> Had the same issue. Turns out it is indeed the default boto signature generation that doesn't work on all regions (new regions, introduced after 2014).
> 
> Way to reproduce: use a bucket in e.g. eu-central. Images do not load as a result.
> 
> I submitted a merge request with the change that fixed it for me: #402.
> Additionally, you may have to create a `~/.aws/config` file to set the region the bucket is in.
> 
> Example:
> 
> ```
> [default]
> region=eu-central-1
> ```

Thank you for the fix, I was having the same issues.

I checkout out release/0.7.5 and it kept failing for me.

Only after setting .aws/config file it finally started showing images.


My config file looks as follows

```
maxim@maxim-ThinkPad-E480:~$ cat ~/.aws/config 
[default]
region=us-east-2
```

**Comment by maximveksler** [comment]
I wonder if label-studio should recommend setting this as best practice, I'd be a bit cautious here as it's a system-wide setting that might break other stuff for the user.

Maybe a better option would be to automatically retrieve the location and then apply the region for a newly established AWS connection?

https://stackoverflow.com/a/34811723

**Comment by makseq** [comment]
@maximveksler May you create a PR with auto region selection?

**Comment by makseq** [comment]
We described possible solutions here: 
https://labelstud.io/guide/storage.html#CORS-and-access-problems
