### ISSUE TITLE
Where can i get the annotation id on DOM?

### ISSUE THREAD

**Issue by 404b** [heartexlabs/label-studio#3810]
I'm trying to automate a project where i'll the annotation with a fetch `POST` request.
But i'm not able to find the task/annotation id on DOM to prepare the payload. Anyone can help?

![image](https://user-images.githubusercontent.com/38348819/223866855-c7e69af8-5922-4d3b-9897-cf95421df781.png)

**Comment by makseq** [comment]
Sorry, your screenshot is very confusing: you are talking about DOM and showing network panel with API requests. Also I don't remember LS using /annotations?project=31 endpoint actively. 

Annotation IDs can be found in api/tasks/ requests.
