### ISSUE TITLE
MySQL composite unique key index max size is exeeded by "unique_title" key of label table

### ISSUE THREAD

**Issue by MangoBird** [heartexlabs/label-studio#3811]
**Describe the bug**
MySQL composite unique key index max size is exeeded by "unique_title" key of label table

**To Reproduce**
1. Use MySQL with InnoDB as data store
2. Run migrate

**Expected behavior**
Migration should run without alteration

**Environment (please complete the following information):**
 - Label Studio Version 1.7.0

**Additional context**
MySQL InnoDB's unique key max size is 3,072 bytes
If char set is utfmb4, 4 bytes/varchar * 767 chats + 4 bytes/int * 1 foreign key = 3,072 bytes
So max_lenght of title column of label table should be 767 if MySQL is supported.

../labels_manager/models.py
line 14: title = models.CharField(_('Title'), max_length=767, help_text=f'Label title')

**Comment by makseq** [comment]
Hello, LS doesn't support MySQL.

**Comment by MangoBird** [comment]
Oh, okay. I thought it did because it has docker-compose for MySQL. Thank you for checking out the issue.

**Comment by makseq** [comment]
Previously LS worked with mysql, but we never tested it. Maybe another mysql version work.
