### ISSUE TITLE
Action Annotation in a Video

### ISSUE THREAD

**Issue by asaeed9** [heartexlabs/label-studio#3812]
**Ahsan, Saeed, he/him/his**

**Georgia Institute of Technology**

I am looking to annotate activities/actions that happen over time in a video for one of our action recognition projects. That would mean annotating multiple actors performing multiple actions in a single video over time. Please can someone help me with how I can annotate this kind of data in LabelStudio? Thanks.

Best,
Ahsan

**Comment by makseq** [comment]
@asaeed9 Hello, seems it will be enough to check Video Object Detection template: 
* https://labelstud.io/blog/label-studio-1-6-video-object-tracking-and-new-annotation-ui/#new-video-object-tracking-functionality
* https://labelstud.io/templates/video_object_detector.html
