### ISSUE TITLE
Update requests

### ISSUE THREAD

**Issue by krlng** [heartexlabs/label-studio#3820]
Hi :)

Is there a reason, why you limit the allowed [requests library version to 2.27](https://github.com/heartexlabs/label-studio/blob/abcc5eaaa495c009871509f82dec8acd33276236/deploy/requirements.txt#L54)? IWithin my setup, I would like to update my dependencies and one important update then depends on 2.28.

**Comment by makseq** [comment]
Hi! There were some problems with pytest when requests > 2.27. 
You can try to create a PR and pass pytests. If you know how to resolve this issue, we will be able to use higher versions of requests library.

**Comment by jombooth** [comment]
Just closing this one as requests is now set at 2.31.0 - thanks for using Label Studio!
