### ISSUE TITLE
How to import multiple predictions for the same task

### ISSUE THREAD

**Issue by Berttwm** [heartexlabs/label-studio#3821]
(Disclaimer: I am unsure if this is a bug or an intended feature.)

**Describe the bug**
There is no way to import multiple predictions. I currently import my images and their respective predictions through an input `.json` file. I need to generate a `.json` file which can input different predictions on the same task. This way, the annotator of the task can cherry-pick which prediction of the 2 (or even multiple) initial predictions 
to use for annotation. The image below shows what I have accomplished so far with 1 initial prediction.
![Untitled](https://user-images.githubusercontent.com/44689249/224267229-e6892567-cbae-49fc-bdea-ac7ff28ef078.png)

**To Reproduce**
1. Create a `.json` import with both image link and prediction values.
2. Create a new project on LabelStudio, import with your `.json` file and set-up the required labelling template. (Polygon instance segmentation in my example)
3. Finish and click on the image to change between annotation or prediction table as seen in the above image.

**Expected behavior**
I have two (or multiple) prediction tabs. In this example, I only have "INITIAL" as my prediction tab ready to be used.

**Comment by CamilleMaurice** [comment]
I have the same use-case! No solutions to propose. If I even find something I'll let you know.

**Comment by makseq** [comment]
@Berttwm @CamilleMaurice you should put your predictions to import file as 
```
task['predictions'] = [ { ..prediction1.. }, {.. prediction2..}] 
```

**Comment by Berttwm** [comment]
Hi @makseq I followed your method and did manage to produce the intended result of creating 2 predictions.
![image](https://user-images.githubusercontent.com/44689249/224590004-b50664b5-9d51-4349-816d-b6fd544b1b98.png)

The `.json` file I imported follows the format below. I have changed the `points` value-pair to `...` for ease of readability. 

What I did was that I appended the `prediction` list with new `results` dictionary instead of simply appending `results` with newer points as per suggestion. 

```
[
  {
    "data": {
      "image": "<path>"
    },
    "predictions": [
      {
        "result": [
          {
            "from_name": "label",
            "to_name": "image",
            "original_width": 4000,
            "original_height": 3000,
            "type": "polygonlabels",
            "value": {
              "points": [...
              ],
              "polygonlabels": [
                "label1"
              ]
            },
            "score": 0.5
          }
        ]
      },
      {
	 "result": [
          {
            "from_name": "label",
            "to_name": "image",
            "original_width": 4000,
            "original_height": 3000,
            "type": "polygonlabels",
            "value": {
              "points": [...
              ],
              "polygonlabels": [
                "label1"
              ]
            },
            "score": 0.5
          }
        ]
      }
    ]
  }
]
```

Thanks you can consider this issue closed on my end
