### ISSUE TITLE
"Organizations > add people" invite link not working 

### ISSUE THREAD

**Issue by bobyfisch** [heartexlabs/label-studio#3827]
**Describe the bug**
As described in the docs, when clicking on the hamburger icon and "Organizations > add people" and transfering the created link of the kind http://localhost:8080/user/signup/?token=XXXXXXXXXX to another user, this link just opens up his project page, not enabling him to join my organization

**To Reproduce**
1. click on hamburger icon, organizations, add people
2. copy link
3. open link in another user account on another PC
4. Link only opens the localhost:8080/projects/ window

**Expected behavior**
I expected the user to be able to join my organization and collaborate on my projects

**Screenshots**
NA

**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version v1.7.1

**Additional context**
Is there any other way to invite people to my organization/projects? Maybe trying through a more manual way can solve the problem

**Comment by makseq** [comment]
@bobyfisch you should setup an external LS server, it must be accessible for all users in the external network. It won't work if you use two different LS instances.

**Comment by makseq** [comment]
![image](https://user-images.githubusercontent.com/501780/224713279-7fb5b671-6712-4af2-b333-22dcf1269dd7.png)

**Comment by bobyfisch** [comment]
Thank you for you reply @makseq. Is there any reference in the docs on recommended practices to set this up? 
I have only found: https://labelstud.io/guide/storage.html

**Comment by makseq** [comment]
@bobyfisch You need something like this: 
https://labelstud.io/guide/start.html#Expose-a-local-Label-Studio-instance-outside-using-ngrok
if you want to use your local machine as LS server.
