### ISSUE TITLE
Installation error Label Studio (Apple M1, python3.11)

### ISSUE THREAD

**Issue by Efimka08** [heartexlabs/label-studio#3843]
Installation error Label Studio.
Steps to reproduce the error:
python3 -m venv env
source env/bin/activate
python -m pip install label-studio

Error text:
Collecting psycopg2-binary==2.9.1
  Using cached psycopg2-binary-2.9.1.tar.gz (380 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /Users/user/env/lib/python3.11/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running egg_info
      creating /private/var/folders/gd/_s26xj2s2sl67g_brwsjgpmh0000gn/T/pip-pip-egg-info-2l6cffk3/psycopg2_binary.egg-info
      writing /private/var/folders/gd/_s26xj2s2sl67g_brwsjgpmh0000gn/T/pip-pip-egg-info-2l6cffk3/psycopg2_binary.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/gd/_s26xj2s2sl67g_brwsjgpmh0000gn/T/pip-pip-egg-info-2l6cffk3/psycopg2_binary.egg-info/dependency_links.txt
      writing top-level names to /private/var/folders/gd/_s26xj2s2sl67g_brwsjgpmh0000gn/T/pip-pip-egg-info-2l6cffk3/psycopg2_binary.egg-info/top_level.txt
      writing manifest file '/private/var/folders/gd/_s26xj2s2sl67g_brwsjgpmh0000gn/T/pip-pip-egg-info-2l6cffk3/psycopg2_binary.egg-info/SOURCES.txt'
      
      Error: pg_config executable not found.
      
      pg_config is required to build psycopg2 from source.  Please add the directory
      containing pg_config to the $PATH or specify the full executable path with the
      option:
      
          python setup.py build_ext --pg-config /path/to/pg_config build ...
      
      or with the pg_config option in 'setup.cfg'.
      
      If you prefer to avoid building psycopg2 from source, please install the PyPI
      'psycopg2-binary' package instead.
      
      For further information please check the 'doc/src/install.rst' file (also at
      <https://www.psycopg.org/docs/install.html>).
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

 - OS: macOS Ventura 13.2.1
 - Apple M1
 - python3.11

**Comment by makseq** [comment]
@Efimka08 please try the latest develop branch. Or wait until 1.7.2, it will be released very soon.

**Comment by makseq** [comment]
Also you can install LS using brew: 
```
brew install label-studio 
```

**Comment by Efimka08** [comment]
When using brew, I get an error:
Warning: No available formula with the name "label-studio".
