### ISSUE TITLE
How to upload an image file with a task over API?

### ISSUE THREAD

**Issue by DimIsaev** [heartexlabs/label-studio#3845]
API  method 
https://labelstud.io/api#operation/api_projects_import_create
http://{URL_LABEL}/api/projects/{id}/import'

How to upload a source file for a task via API?

**Comment by makseq** [comment]
You should call `/api/projects/<id>/import` with form data, e.g.:

```
curl 'http://localhost:8000/api/projects/353/import' \
  -H 'Content-Type: multipart/form-data;' \
  --data-raw $'------WebKitFormBoundary9QieDF8NQI7gPZdx\r\nContent-Disposition: form-data; name="img.png"; filename="img.png"\r\nContent-Type: image/png\r\n\r\n\r\n------WebKitFormBoundary9QieDF8NQI7gPZdx--\r\n' \
```

However, I strongly discourage the use of downloads in production. LS is not meant for that. 
Use Local Storage instead: https://labelstud.io/guide/storage.html#Local-storage

**Comment by DimIsaev** [comment]
> However, I strongly discourage the use of downloads in production. LS is not meant for that. Use Local Storage instead: https://labelstud.io/guide/storage.html#Local-storage

Yes, I had to use local storage to add images manually

Is it possible to add files to local storage via API?

**Comment by makseq** [comment]
@DimIsaev no, but you can use your own python webserver for this:

```python
import os
from flask import Flask, request, jsonify
from werkzeug.utils import secure_filename

app = Flask(__name__)

UPLOAD_FOLDER = 'uploaded_files'
ALLOWED_EXTENSIONS = {'txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'}

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/upload', methods=['POST'])
def upload_file():
    if 'file' not in request.files:
        return jsonify({'error': 'No file part in the request'}), 400
    file = request.files['file']
    if file.filename == '':
        return jsonify({'error': 'No file selected for uploading'}), 400
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        return jsonify({'message': f'File {filename} uploaded successfully'}), 200
    else:
        return jsonify({'error': 'File extension not allowed'}), 400

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
```

run it:
```bash
python file_upload_server.py
```

and use
```bash
curl -X POST -H "Content-Type: multipart/form-data" -F "file=@example.jpg" http://localhost:5000/upload
```

OR you can try hosting solutions like these:

1. Nextcloud: Nextcloud is an open-source, self-hosted file sharing and communication platform. It allows you to upload, manage, and share files through its web interface or APIs. You can also extend its functionality with various apps and plugins. Find more information and installation instructions here: https://nextcloud.com/

2. ownCloud: Similar to Nextcloud, ownCloud is an open-source, self-hosted file sync and share solution. It provides APIs for managing files, users, and permissions. You can find more information and installation instructions here: https://owncloud.com/

3. Seafile: Seafile is another open-source, self-hosted file synchronization and sharing solution. It offers a web interface, desktop clients, and mobile apps. It also provides APIs for managing files, users, and groups. More information and installation instructions can be found here: https://www.seafile.com/

4. FileRun: FileRun is a self-hosted file management and sharing solution that provides a web-based interface, mobile apps, and API access. It offers various features like file versioning, sharing, and access control. More information can be found here: https://filerun.com/

5. Pydio: Pydio, formerly known as AjaXplorer, is an open-source file sharing and synchronization platform that provides a web interface, desktop clients, and mobile apps. It also offers APIs for managing files and users. More information and installation instructions can be found here: https://pydio.com/

These solutions typically provide more advanced functionality than a simple file upload server, such as user management, access control, file versioning, and sharing features.

**Comment by unikill066** [comment]
Hi @makseq, @DimIsaev 

I see that you recommend using a web-server to upload images to LS, if I am running a tornado web-server; how do I go about uploading the images to label-studio using the python-sdk?
