### ISSUE TITLE
Video not loading in annotation panel

### ISSUE THREAD

**Issue by ChronoVortex07** [heartexlabs/label-studio#3855]
**Describe the bug**
mp4 files uploaded to a project does not show up in annotation panel, instead an error like the below showed:

```
There was an issue loading URL from $image value

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)
Technical description:
URL: C:/Users/user/videos/database/video1.mp4
```

**To Reproduce**
  Upload videos via upload button
  OR
  Upload videos via local cloud storage by uploading a folder of mp4 files
  OR
  Upload videos via local cloud storage by uploading a folder of json files
  
  Click annotate on any uploaded file, file will not load and error above will show

**Expected behavior**
Video loads and annotation function works as intended

**Environment (please complete the following information):**
 - OS: Windows 11
 - Label Studio Version: 1.7.1

**Comment by ChronoVortex07** [comment]
Issue was resolved after changing the labeling config from an image annotation one to a video annotation

**Comment by jonydev** [comment]
> Issue was resolved after changing the labeling config from an image annotation one to a video annotation

how to change the labeling config? I try to change the template, but not work

**Comment by YannickGibson** [comment]
Make sure the video size is under 50MB as noted in the [documentation](https://labelstud.io/guide/tasks.html#How-to-format-your-data-to-import-it).
