### ISSUE TITLE
video frame labeling

### ISSUE THREAD

**Issue by alimd94** [heartexlabs/label-studio#3860]
Hello
thank you for your great and useful application.

I worked with this for nearly one hour and I couldn't find **frame level classification**. although it has much more complex feature like object tracking and ... , it doesn't have that feature or at least I don't know how should I do that.

I just want to give each frame in a video a class number, consider it as a frame level classification not a video level.

looking forward to hear from you soon

**Comment by makseq** [comment]
Hello, the video object detection task is more popular, so we did it first. 

I can recommend two options here:
1. use object detection template and put a new box at each new frame with a specific label instead of a choice. Not super convenient, but should work. 
2. split your video into frames and import all images as separate LS tasks, then do the task by task classification with choices.

**Comment by zfqy** [comment]
Same with alimd94, I just want to label time segments of a video, is there any simple way? Thanks.

**Comment by makseq** [comment]
OK, maybe I found some workaround: you can use audio labeling with video sync:

```
<View>
  <Header value="Video timeline segmentation via AudioPlus sync trick"/>
  <Video name="video" value="$video_url" sync="audio"/>
  <Labels name="tricks" toName="audio" choice="multiple">
    <Label value="Kickflip" background="#1BB500"/>
    <Label value="360 Flip" background="#FFA91D"/>
    <Label value="Trick" background="#358EF3"/>
  </Labels>
  <AudioPlus name="audio" value="$video_url" sync="video" speed="false"/>
</View>
```

**Comment by zfqy** [comment]
Much thanks for your reply. It really satisfies most needs for video timeline segmentation. Although some of my video files don't contain audio channels, I could add empty audio sequences to fit this configuration.  I wonder if it is possible to create a "VideoPlus" object in the future edition, which enables directly labeling the frame on the video timeline, similar to the marker function in the Adobe Premiere Pro.

**Comment by makseq** [comment]
Yes, I will add a similar idea to our product backlog.
