### ISSUE TITLE
Preview pdf and draw on pdf

### ISSUE THREAD

**Issue by juhonkang** [heartexlabs/label-studio#3862]
Hi, I want to build an OCR product website that have feature like in UBIAI. 

https://screenpal.com/watch/c0e2QZV4tea](https://screenpal.com/watch/c0e2QZV4tea)

I want to draw the rectangle on the pdf and extract the text inside, how can I do that in label studio and integrate that into my website?

**Comment by makseq** [comment]
Sorry, your image is not loaded :(
![image](https://user-images.githubusercontent.com/501780/226948887-8a85eb34-0f40-443d-8054-06b0fb4faf2d.png)

You can convert your PDF to images and label them with OCR template:
https://labelstud.io/templates/optical_character_recognition.html
