### ISSUE TITLE
healthcheck fails for ml backend + docker compose

### ISSUE THREAD

**Issue by dslim23** [heartexlabs/label-studio#387]
**Describe the bug**
health check `curl http://localhost:9090/health` works when using flask server, fails when using prod server with `docker-compose up`
**To Reproduce**
1.` docker-compose up` with ml backend
2.  run command `curl http://localhost:9090/health` 
3. returns Internal Server Error

**Expected behavior**
should return` {"status":"UP"}`

**Environment (please complete the following information):**
 - OS: Debian GNU/Linux 9.12 (stretch) (GNU/Linux 4.9.0-12-amd64 x86_64\n) on GCE

**Additional context**

**Comment by makseq** [comment]
Have you any suggestions why is it so?

**Comment by nabinkhadka** [comment]
Which script are you using? You will need to add dependencies to the `requirements.txt` file and then only bring the containers up. For example if you want to use the simple_text_classifier.py script, then add `sklearn` in the requirements.txt file, and then `docker-compose up` should work. @dslim23

**Comment by dslim23** [comment]
thank you @nabinkhadka just forgot about that!
