### ISSUE TITLE
How to activate Magic Wand tool in 1.7.2

### ISSUE THREAD

**Issue by YugangDuan** [heartexlabs/label-studio#3879]
I have upgraded to V 1.7.2 but I can't find how to activate Magic Wand Tool.

**Comment by createemir** [comment]
I agree with you, I couldn't find on templates, too.

**Comment by makseq** [comment]
Please check docs here:
https://labelstud.io/tags/magicwand.html

**Comment by YugangDuan** [comment]
![image](https://user-images.githubusercontent.com/70528083/226829400-85d72da4-02a7-4219-85be-16960533dce2.png)
Thank you for your answer, 

I find that fflag_feat_front_dev_4081_magic_wand_tool is default set as true. But I still can not activate it. Am I finding the right file?

Best regards

**Comment by a-goose95** [comment]
Hi I also, am having issues activating the magic wand function? I have upgraded to 1.7.2. But can't find any option in the feature flags to activate the magic wand?

**Comment by makseq** [comment]
@a-goose95 did you use [`<MagicWand>`](https://labelstud.io/tags/magicwand.html) tag? doesn't it work?

**Comment by makseq** [comment]
Related: https://github.com/heartexlabs/label-studio/issues/3903

**Comment by hlomzik** [comment]
@YugangDuan @a-goose95 @createemir if you use [config from docs](https://labelstud.io/tags/magicwand.html#Example) and you see Magic Wand in toolbar, but it doesn't work, try to disable another conflicting feature flag via env var like this:
`fflag_feat_front_lsdv_4583_6_images_preloading_short=0 label-studio`
or in any other convenient way.
We'll release fix for this clash soon.

**Comment by YugangDuan** [comment]
> 

Unfortunately, I did not see the Magic Wand toolbar. And try to edit the config like the Magic Wand example, it shows that can not find the module.

**Comment by YugangDuan** [comment]
> 

Sorry for the Typo. I mean I still can not activate it, and I am not sure whether I find the right setting file.

**Comment by makseq** [comment]
Please follow this instruction about the feature flag: 
https://labelstud.io/tags/magicwand.html#Feature-Flag

and this labeling config:
```
<View>
  <Labels name="labels" toName="image">
    <Label value="Person" />
    <Label value="Animal" />
  </Labels>
  <MagicWand name="magicwand" toName="image" />
  <Image name="image" value="$image" crossOrigin="anonymous" />
</View> 
```

**Comment by createemir** [comment]
Thanks, I can activate with the code on docs:
![image](https://user-images.githubusercontent.com/124001681/229312977-dd0e03d3-af25-48ba-aa72-907e1f97fc86.png)

**Comment by doantientai** [comment]
Sorry if the question is not elevant, but how do you limit the expanding of MagicWand? I see how to expand the region by dragging the mouse, but what can I do to limit the region to a selected zone?
