### ISSUE TITLE
Option to Update/Retrain model on every task complete

### ISSUE THREAD

**Issue by devonkinghorn** [heartexlabs/label-studio#389]
**Is your feature request related to a problem? Please describe.**
We have a workflow where every task has multiple items to label.
Some of the items across tasks are identical, and we would like the ml-model to memorize labeler choices, but telling the model to retrain on all of the data is a hassle and isn't instant. So some tasks show up and aren't memorized.

**Describe the solution you'd like**
I would find sending every labeled task to the model in near real time to be very helpful. It would help our memorization model stay up to date. This could be a function in the model for individual labeled tasks or minibatches of tasks.

**Comment by fromnorthpole** [comment]
Hi, @devonkinghorn ! 
Sorry for the late response.
Yes, I think it's a good idea to include that option in ML backend connection settings. We'll make it in future releases. Meanwhile, you can do it programmatically by creating hooks sending POST requests to `/api/train`

**Comment by makseq** [comment]
@devonkinghorn This feature added since LS 1.0.2.
