### ISSUE TITLE
Single label exported as multiple png images

### ISSUE THREAD

**Issue by linnabraham** [heartexlabs/label-studio#3892]
**Describe the bug**
Annotations made for image segmentation task appear as separate ones for a single label. When exported as PNG I get multiple masks for the same label.

**To Reproduce**
1. Take an image and use the brush to make an annotation.
2. Click on another image and return back to same image
3. Continue annotation by applying brush over another region in same image for the same label
4. Annotation listed separately
5. Export annotations as PNG.

**Expected behavior**
As shown in the export dialog box, single label should be output as a single image (binary mask)

**Environment (please complete the following information):**
 - OS: ArchLinux 
 - Label Studio Version1.7.2

**Comment by makseq** [comment]
Can you merge all images from the same label into the one png? Seems it's not a big deal.

**Comment by linnabraham** [comment]
It might be doable to manually merge the exported images. I just wanted to confirm if this was an issue with the program or me not understanding how the program works. 

I just found out how to read the exported json data and manually rename the filenames to match with the input files. So I think this would involve something similar. Exporting the json data and parsing it in python or something and reading the image corresponding to single task id and multiple annotation ids and then adding those together to merge it right?

**Comment by makseq** [comment]
@linnabraham  Yes, I believe you are on the right way. Also you can contribute this behaviour here https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/brush.py#L148 if some option (like env variable BRUSH_EXPORT_MERGE_ALL_LAYERS) is enabled.

**Comment by linnabraham** [comment]
> @linnabraham Yes, I believe you are on the right way. Also you can contribute this behaviour here https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/brush.py#L148 if some option (like env variable BRUSH_EXPORT_MERGE_ALL_LAYERS) is enabled.

Thanks for providing an easy way to contribute. I shall consider doing that.

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
