### ISSUE TITLE
Go to next tasks

### ISSUE THREAD

**Issue by mrijken** [heartexlabs/label-studio#39]
When I submit a task on the front-end, it will show "all done", although tasks are tasks left. Is it possible to automatically load the next task when after submitting a task? This can improve the speed of labeling.

**Comment by makseq** [comment]
Try the last commit in master f23ba74e27f15eb8af138fd41986aa27df068458 ("Load next task on submit in label stream"). It was something like a bug and now it's fixed, next task is working after each submit.
