### ISSUE TITLE
Ability too zoom in on images

### ISSUE THREAD

**Issue by undefdev** [heartexlabs/label-studio#390]
Thanks for working on this software, it's great to be able to self-host this!
However I've noticed something that is very inconvenient, especially when working on a smaller screen.

When annotating bigger images with bounding boxes/ellipses, there are sometimes details that need bounding boxes that are rather small.

To make labeling these easier, it would be a huge help to be able to zoom in on an image and perform the labeling at an arbitrary zoom level.

Thank you very much!

**Comment by hlomzik** [comment]
Hi! Thank you!
Yes, we have zoom controls for sure, but you have to enable this feature with `zoom="true"` on `Image` tag. This enables zoom by `ctrl+wheel` and pan by `shift+drag`. Also you can enable visual controls for zooming with `zoomControl="true"`.

Here is example for reference: https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CImage%20name%3D%22image%22%20value%3D%22%24image%22%20zoom%3D%22true%22%20zoomControl%3D%22true%22%2F%3E%3Cbr%3E%20%20%3CRectangleLabels%20name%3D%22label%22%20toName%3D%22image%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Airplane%22%20background%3D%22green%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Car%22%20background%3D%22blue%22%2F%3E%3Cbr%3E%20%20%3C%2FRectangleLabels%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E

**Comment by makseq** [comment]
@undefdev
