### ISSUE TITLE
Loading pre-annotations for video task example?

### ISSUE THREAD

**Issue by SiftingSands** [heartexlabs/label-studio#3904]
I didn't see any tutorials or examples of loading pre-annotations for videos.

I tried this w/ the Python SDK to see if I could load a single bounding box into the first frame of a video task that was already present. However, this would give a 400 error. 
```
tasks_ids = project.get_tasks_ids()
predictions = [{
    "task": tasks_ids[0],
    "result": [{
        "sequence": [{
            "frame": 1,
            "rotation": 0,
            "x":20,
            "y":20,
            "width":40,
            "height":40
            }],
        "labels":"Woman"
    }],
}]
project.create_prediction(predictions)
```

Loading the video along with the pre-annotation wouldn't error out, but the video playback would freeze on the dashboard.
```
<removed misc. stuff above>
  tasks.append({
      'name': <removed>,
      'video' : <removed>,
      "predictions": [{
          "id": 1,
          "result": [{
              "sequence": [{
                  "frame": 1,
                  "rotation": 0,
                  "x":20,
                  "y":20,
                  "width":40,
                  "height":40,
                  "enabled":True,
                  "time":0.04
                  }],
              "labels":"Woman",
              "id":"x-qq0Yhy98",
              "from_name":"box",
              "to_name":"video",
              "type":"videorectangle"
          }],
      }],
  })

project.import_tasks(
    tasks,
    preannotated_from_fields=['predictions']
)
```
![image](https://user-images.githubusercontent.com/43226539/227624628-b8530aa3-d1d7-4473-b4fd-8736073abc93.png)

I assume that there's some field that I'm not declaring that's causing this to not work, but I can't figure it out from the annotation exports from the dashboard. Could an example for loading pre-annotations for videos be given, or is this actually a missing feaure?

**Comment by SiftingSands** [comment]
I finally got a single bounding box to show up as a prediction with the following. I'm really not sure what changed in terms of content that allowed this to work.
```
tasks_ids = project.get_tasks_ids()
predictions = [
        {
          "from_name": "box",
          "to_name": "video",
          "type": "videorectangle",
          "value": {
            "framesCount": 1862,
            "duration": 62.062,
            "sequence": [
              {
                "frame": 1,
                "enabled": True,
                "rotation": 0,
                "x": 20,
                "y": 20,
                "width": 40,
                "height": 40,
              }
            ],
            "labels": [
              "Woman"
            ]
          },
        }
      ]
project.create_prediction(tasks_ids[0], result=predictions, model_version='1')
```

**Comment by makseq** [comment]
At least this one - 
```
"labels":"Woman",
```
=> 
```
 "labels": [
              "Woman"
            ]
```

**Comment by SiftingSands** [comment]
Not putting the label into a list produces a distinct error message on the dashboard, which I never saw during my initial troubleshooting.
![image](https://user-images.githubusercontent.com/43226539/227959403-c3137d3a-e971-4781-847b-97969f1d60d5.png)

I think having the predictions be sent to the "result" arg (`project.create_prediction(tasks_id, result=predictions)`) was necessary for the Python SDK for videos, where images are more flexible with pre-annotations? Just my speculations here.

**Comment by MMa321** [comment]
> 我终于得到了一个边界框，显示为预测，其中包含以下内容。我真的不确定在内容方面发生了什么变化，使它能够工作。
> 
> ```
> tasks_ids = project.get_tasks_ids()
> predictions = [
>         {
>           "from_name": "box",
>           "to_name": "video",
>           "type": "videorectangle",
>           "value": {
>             "framesCount": 1862,
>             "duration": 62.062,
>             "sequence": [
>               {
>                 "frame": 1,
>                 "enabled": True,
>                 "rotation": 0,
>                 "x": 20,
>                 "y": 20,
>                 "width": 40,
>                 "height": 40,
>               }
>             ],
>             "labels": [
>               "Woman"
>             ]
>           },
>         }
>       ]
> project.create_prediction(tasks_ids[0], result=predictions, model_version='1')
> ```

Hello, my import pre-comment is not displayed, may I ask how you import it
