### ISSUE TITLE
Toggle visibility of bounding boxes/ellipses.

### ISSUE THREAD

**Issue by undefdev** [heartexlabs/label-studio#391]
When annotating images with bounding boxes, they may often overlap and it's frustrating when one accidentally selects the wrong one.
To solve this problem it would be nice to be able to toggle the visibility of certain labels or even single bounding boxes.
For example, the interior of the circles with the numbers in them could gray out when clicking on them, causing the selected ellipse to be invisible/unselectable on the image.

![image](https://user-images.githubusercontent.com/13840966/89635727-b8d00500-d8a7-11ea-85d1-f4dc64340090.png)

**Comment by makseq** [comment]
Released in https://github.com/heartexlabs/label-studio/pull/350
