### ISSUE TITLE
Pypi Label Studio 1.7.1 regular crashes on CentOS with more than 5k tasks.

### ISSUE THREAD

**Issue by vpasquier** [heartexlabs/label-studio#3916]
**Describe the bug**
Crash when using label studio with a lot of data.

**To Reproduce**
- Import more than 5000 tasks spread on different projects
- It crashes at some point
- There is no error in the logs

**Expected behavior**
The process is getting killed. I'm using the pip package.

**Screenshots**
No screenshot

**Environment (please complete the following information):**
- Label Studio 1.7.1 pypi package
- CentOS

**Additional context**
Nop.

## Questions

- Do you have any optimization to make on the django server to allocate maybe more memory?
- What would be the best configuration and how to make it?

**Comment by vpasquier** [comment]
I see here https://github.com/heartexlabs/label-studio/blob/develop/deploy/uwsgi.ini that we can maybe set a global variable to optimize the number of processes. Is it a good guideline to change this `UWSGI_PROCESSES` variable?

**Comment by farioas** [comment]
The pip package is running without uwsgi. You can check `dmesg` and I'm sure you'll find there a message from OOM killer :)

**Comment by vpasquier** [comment]
Yes it was indeed the reason thank you so much!
