### ISSUE TITLE
Fit vs Train in ml-backend

### ISSUE THREAD

**Issue by nabinkhadka** [heartexlabs/label-studio#392]
I cannot understand these two functions. Is fit just an API endpoint that spawns train function?

1. The endpoint called from UI to trigger training is called `/train` ([here](https://github.com/heartexlabs/label-studio/blob/1b6294c40f69c1a761f3f3c8ab4fad931e755167/label_studio/templates/model.html#L253))
2. And [here](https://github.com/heartexlabs/label-studio/blob/master/docs/source/tutorials/dummy_model.md), it says two methods should be overridden: predict() and train()
3. And [here](https://github.com/heartexlabs/label-studio/blob/1b6294c40f69c1a761f3f3c8ab4fad931e755167/label_studio/ml/model.py#L30), it says two abstract methods: predict() and fit()
4. And [here](https://github.com/heartexlabs/label-studio/blob/1b6294c40f69c1a761f3f3c8ab4fad931e755167/label_studio/ml/examples/pytorch_transfer_learning.py#L196), it looks like the method that needs to be overridden is the `fit()` not the `train()`. But again a `train()` method is created in the same file (pytorch_transfer_learning.py) which looks like has nothing to do with the framework and would have been called anything.

My conclusion until now is the methods to override are `predict()` and `fit()`. If that is so, the `fit()` method in `pytorch_transfer_learning.py` sample script will be triggered by the `Start Training` button. This method calls the `train()` function present in the same file, right? Will this training (or should I call fitting?) be asynchronous? If yes, which line sends the fitting to async? Or will the API wait until the training is finished?

I am clearly confused somewhere and cannot understand something. Thank you in advance :)

**Comment by niklub** [comment]
Hi, @nabinkhadka !

Indeed, two methods should be overridden - `fit()` and `predict()`. [That's an error in docs](https://github.com/heartexlabs/label-studio/blob/master/docs/source/tutorials/dummy_model.md#create-dummy-model-script), and thank's for pointing on it!

The `train()` method [here](https://github.com/heartexlabs/label-studio/blob/1b6294c40f69c1a761f3f3c8ab4fad931e755167/label_studio/ml/examples/pytorch_transfer_learning.py#L118) is just an inner method of a model instance, without any specificity, you can call them whatever you want.

**Comment by nabinkhadka** [comment]
@niklub Thank you for the response.

What about another question?
```
This method calls the train() function present in the same file, right? 
Will this training (or should I call fitting?) be asynchronous? 
If yes, which line sends the fitting to async? 
Or will the API wait until the training is finished?
```

**Comment by fromnorthpole** [comment]
@nabinkhadka Sorry for the late response!

- Yes, when you are specifying Redis as tasks queueing server, the `train()` function is called explicitly in a separate process https://github.com/heartexlabs/label-studio/blob/master/label_studio/ml/model.py#L370)
- if Redis server is disabled - training function is running synchronously (though it could be easily managed as non-blocking requests provided by Flask, e.g. by setting `threaded=True` option)

Hope that the answer would still be helpful.

**Comment by nabinkhadka** [comment]
I had figured out that. But thank you for response. :)
