### ISSUE TITLE
Video Annotation

### ISSUE THREAD

**Issue by asaeed9** [heartexlabs/label-studio#3928]
**Describe the bug**
I installed Label Studio 1.7.2 (community edition) on a fresh Ubuntu 20.04 VM. I am trying to label videos. In total, I have around 80 2-minute videos divided into multiple tabs for different annotators to work on. 

The problem that I am seeing is related to timeline. I hit play button, video starts. I hit pause button, video stops at say 30th frame. Now, if I select 35th or 40th frame in the timeline two things happen. 

One, the video sort of freezes. As if, clicking on different frames doesn't have any impact on the videos position.

Secondly, if I hit play, the video starts from the 1st frame and not from the frame it was earlier paused on. It's as if I can't touch the timeline window without resetting it.  

I wonder if anyone's seen this issue before.

Metadata:

```
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.29.100
  Duration: 00:02:00.09, start: 0.000000, bitrate: 1415 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 1412 kb/s, 29.97 fps, 29.97 tbr, 11988 tbn, 59.94 tbc (default)
```

****EDIT****
The application is installed on a server. When I connect to the server directly and run the GUI, I see that it works. However, when I access the application as an annotator from the network, it gives above errors.

**Comment by makseq** [comment]
@asaeed9 where do you store video files?

**Comment by asaeed9** [comment]
video files are stored on the same server where the software is installed, an ubuntu 20.04 virtual machine on Oracle Cloud. Annotators access the software from their client machines through a URL. Everything works well on the server itself. It definitely seems a network issue, but with this network issue or congestion, label studio's behavior is rather unexpected (above errors).

**Comment by makseq** [comment]
Try using s3/gcp cloud storages, they well distributed across internet network. Seems it's not a LS issue, because LS doesn't touch user data or pre-load it somehow. All loads happen in user browsers.

**Comment by plutonium-239** [comment]
Hi, I am facing the same issue with files hosted both locally and on google drive

Clicking on any frame in the timeline or inputting any frame number does not show that frame in the video player, and instead it resets to the first frame.
i.e., The only way to move between the video is pause/play.

Latest version (1.9.2-post0)

My video is 15 mins long, so importing it directly just never succeeds.
Update: even uploading a 1 minute video directly does not succeed.
