### ISSUE TITLE
ML backend fails on labeling config validation with control tags

### ISSUE THREAD

**Issue by LouisHeck** [heartexlabs/label-studio#3934]
I was doing Relation Extraction Task, labeling Tag used a  relation extraction template. When I add model for machine learing predictions,
it throws as error for control_type:  RectangleLabels. But I've setting template for relation extraction. what's wrong ? Why the control type is RectangleLabels ,not Relation Extraction labels?

screen shot 1: labeling template
![1680190352751](https://user-images.githubusercontent.com/38588261/228888102-f9b67b15-1d79-4a0d-996e-c2a11f1227e2.png)

screen shot 2: error message from ml-backend for control type.

![1680190491381](https://user-images.githubusercontent.com/38588261/228888829-cfd67480-51b0-4a66-86c9-5fe6d400cf0a.png)

Please Help me , Many thanks!

**Comment by makseq** [comment]
> Why the control type is RectangleLabels ,not Relation Extraction labels?

check line 14 in your ml backend code, RectangleLabels tag is specified there.

**Comment by LouisHeck** [comment]
> > Why the control type is RectangleLabels ,not Relation Extraction labels?
> 
> check line 14 in your ml backend code, RectangleLabels tag is specified there.

Yes, you're right. I pass error tags in parsed_label_config() function. After changed, it works.
Thank you for your help!
