### ISSUE TITLE
"Cannot find bucket" only when specifying S3 endpoint, otherwise works

### ISSUE THREAD

**Issue by nikolaydyankov** [heartexlabs/label-studio#3939]
I'm getting the following error ONLY when I try to specify S3 endpoint for cloud storage. If I don't specify an endpoint, it works fine, so the problem is not the bucket name or the credentials.

```
Validation error
Cannot find bucket **** in S3
Version: 1.7.2
```

The URL I'm providing for the endpoint looks like this

```
http://****.s3-website.eu-central-1.amazonaws.com
```

I have static website hosting enabled on the bucket in order to get an endpoint URL. When I try to curl one of the objects from the terminal it works, so the issue is not the endpoint URL either.

Is it possible that this is a bug with Label Studio?

Thanks

**Comment by makseq** [comment]
If you use common s3 storage, you don't need to provide endpoint in source cloud settings. Why do you try to do it?

**Comment by nikolaydyankov** [comment]
> If you use common s3 storage, you don't need to provide endpoint in source cloud settings. Why do you try to do it?

Just for convenience. When I export COCO json, images have s3:// URLs. I would like them to have the endpoint URL instead.

**Comment by makseq** [comment]
Endpoint url is needed when you host your own s3-like cloud storage (e.g. minio) and you want to provide a path for it.
