### ISSUE TITLE
Pre-annotations of TextArea missing

### ISSUE THREAD

**Issue by michaelachmann** [heartexlabs/label-studio#3941]
**Describe the bug**
I'm trying to transcribe audio files. When uploading tasks with pre-annotations using the Python SDK (API), the annotations are not displayed in the interface.

Maybe a duplicate of #3093

**To Reproduce**

1. Create a new project and Interface:
```python
interface = """
<View>
  <Audio name="audio" value="$audio" zoom="true" hotkey="ctrl+enter" />
  <Header value="Provide Transcription" />
  <TextArea name="transcript" toName="audio"
            rows="5" editable="true" maxSubmissions="1" />
</View>
"""

project_name = "Audio Project" 

ls = Client(url=labelstudio_url, api_key=labelstudio_key)
project = ls.start_project(
    title=project_name,
    label_config=interface,
)
```
2. Upload Tasks with pre-annotations
```python
project.import_tasks(
        df_tasks.to_dict('records'),
        preannotated_from_fields=['transcript'])
```
3. Start the annotation: Pre-Annotations are missing in the interface (but present in the task files):
```json
"predictions": [
    {
      "id": 28489,
      "model_version": "undefined",
      "created_ago": "1 hour, 22 minutes",
      "result": [
        {
          "type": "textarea",
          "value": {
            "textarea": [
              "... transcription ..."
            ]
          },
          "to_name": "audio",
          "from_name": "transcript"
        }
      ],
      "score": null,
      "cluster": null,
      "neighbors": null,
      "mislabeling": 0,
      "created_at": "2023-03-31T11:32:38.613079Z",
      "updated_at": "2023-03-31T11:32:38.613085Z",
      "task": 43936
    }
]
```

**Expected behavior**
The pre annotations should be display in the textarea.

**Environment (please complete the following information):**
Tested with different versions on  Ubuntu with Docker Compose:
 - LS Version 1.4.1 
 - LS Version 1.5.0
 - LS Enterprise 2.4.6dev

**Comment by hlomzik** [comment]
Hey! For TextArea there should be `text` key in `value` instead of `textarea`:
```json
"value": {
  "text": [
    "... transcription ..."
  ]
},
```
That's not clear from our documentation, thanks, we'll fix it soon!
