### ISSUE TITLE
DOCS: Documentation for local Minio installation

### ISSUE THREAD

**Issue by Gornoka** [heartexlabs/label-studio#3944]
**Is your feature request related to a problem? Please describe.**
using LS with a local Minio installation has some pitfalls that make it annoying to set up.
This makes developing and testing more complicated than it has to be. 

**Describe the solution you'd like**
Some docs and a docker-compose file to run the Minio as an additional component of a local label-studio deployment, similar to the MySQL-specific compose file.

This could also be used as part of the ci pipeline to validate that the S3-related functions of LS work, without requiring external connections.

**Describe alternatives you've considered**
* Using throwaway cloud S3 instances
  cons:
  - expensive ( >0$)
  - higher latency
  - requires internet
  pros:
  + easier to set up, depending on your orga
  + less local load
* adding some docs on self-hosting Minio and linking to it
  pros:
  + less stuff to maintain
  cons:
  - less convenient for the user/developer
  - not significantly less work

**Additional context**
this was discussed with @farioas on the LS slack

**Comment by iraadit** [comment]
I would be interested by this doc / docker-compose :)

**Comment by Gornoka** [comment]
> I would be interested by this doc / docker-compose :)

you can have a look here https://github.com/heartexlabs/label-studio/pull/3945
