### ISSUE TITLE
Annotating large images (+- 2Gb) images for object detection

### ISSUE THREAD

**Issue by sdhungan** [heartexlabs/label-studio#3956]
**Is your feature request related to a problem? Please describe.**
I am working on a project where i need to build an AI model that detects multiple objects on drone images. The images themselfs are stiched together into a large image (with some of size of 11 GB). I already split them into pieces of just below 2GB, which worked fine with labelIMG. But because labelImg is no longer maintained i kept getting issues so i decided to try out label-studio which is way more user friendly to work on a project. But the issue i keep getting is that the images are too large (max size is apparenly 250 MB). I relly want to avoid splitting the images into even smaller sizes because this will cause alot more overhead in the preprocessing and dealing with the result of the AI model. 

**Describe the solution you'd like**
Make a variable that allows me to upload very large images (around 2GB).

**Describe alternatives you've considered**
I have tried to change the parameter "DATA_UPLOAD_MAX_MEMORY_SIZE " to a bigger number. The upload works fine but the webserver is not able to load in the image. The "Post" message fails. My pc should be able to handle this large image to render, so i don't understand why the "POST" failed to the webserver.

**Additional context**
If there is an alternative solution (maby another program) that does support large image imports for annotating multiple objects on a single image, that would also suffice. I am not bound to this specific label-studio application at the moment.

**Comment by makseq** [comment]
@sdhungan
1. Please don't use UI imports, they are only for toy tests. For heavy tasks you have to use [Local Storages](https://labelstud.io/guide/storage.html#Local-storage) or other source cloud storages (s3/gcs/azure)
2. To be frank I am not sure that you will be able to label this huge images, most likely a web browser will die loading this huge files.

As I remember labelimg was standalone app, it's much easier to support this huge images there rather in the web browser that is not optimized for such tasks.

**Comment by sdhungan** [comment]
Thank you! Yea i noticed that the pip install of labelImg from the python version i was using was an old version. After installing the correct python version labelImg worked properly. It's a specific usecase for using object detection on drone images that are stiched together. The large images are one of the requirements that we got as an assignment for our bachelor project.
