### ISSUE TITLE
Annotations not exported for images with no BBoxes in COCO and VOC formats

### ISSUE THREAD

**Issue by Hanysix** [heartexlabs/label-studio#3959]
**Is your feature request related to a problem? Please describe.**
I have 1062 images for object detection loaded via Local Storage sync. Some of those images don't have annotations, because the object I want to detect is not present in the image. When I export the annotations, YOLO format exports those empty annotations as empty .txt and LS JSON has "result":[] instead of annotation details. Would it be possible to have similar feature for COCO and VOC formats? And also would those libraries that use those two format for training be able to handle such modification?

Label Studio version: 1.7.2
**Describe the solution you'd like**
I would like to have empty annotations exported for COCO and VOC formats as well. 

**Describe alternatives you've considered**
Take LS JSON or YOLO txt formats and convert them via [LS Converter](https://github.com/heartexlabs/label-studio-converter), but I don't know how or where can I get config.xml

**Additional context**
*For VOC:*

![Capture](https://user-images.githubusercontent.com/118185769/229503380-8f551560-f13b-413c-9325-619baad1c9d0.PNG)

*or*

![Capture](https://user-images.githubusercontent.com/118185769/229503540-0197944c-39a6-45af-a19d-e355e5e5c812.PNG)

*And for COCO:*

![image](https://user-images.githubusercontent.com/118185769/229503997-1199ccc3-5bda-4828-9415-0ad48c64e9d3.png)

**Comment by kielnino** [comment]
@Hanysix I have a simular usecase, where the object is not present in some of the images. However in the coco-export the empty images should by listet in the `images`-key, so it is easy to distinguish images with annotations (id is listed in `annotations`) from empty images (id is not listed under `annotations`).

Back then we disscussed the issue in #1470

**Comment by Hanysix** [comment]
I tried the API command mentioned [here](https://github.com/heartexlabs/label-studio/issues/1470#issuecomment-1122329969), but I was not able to get the annotations

`api/project/14/export?export_type=VOC&download_resources=true&download_all_tasks=true`

The response I got is:

> 'download_resources' is not recognized as an internal or external command, operable program or batch file.

With the log looking like this:

>  [django.server::log_message::161] [WARNING] "GET /api/project/14/export?export_type=VOC HTTP/1.1" 404 1474

#### Screenshots

![image](https://user-images.githubusercontent.com/118185769/230326022-8d452a18-25ca-4fb9-8b93-0a5bbc83fc2f.png)

![image](https://user-images.githubusercontent.com/118185769/230327234-db33ac14-8ddf-4729-9a89-2343bf847c6b.png)

**Comment by kielnino** [comment]
According to the [API Documentation](https://labelstud.io/api#operation/api_projects_export_read) it should be `api/projects/14/` with an **s** instead of `api/project/14/`

**Comment by Hanysix** [comment]
With modified command the response is this:

>{"id":"2bc776de-5474-4997-b1d7-475e3fed4775","status_code":401,"version":"1.7.2","detail":"Authentication credentials were not provided.","exc_info":null}'download_resources' is not recognized as an internal or external command, operable program or batch file.

The full command I use is this:

`curl -X GET http://{ip}:{port}/api/projects/14/export?export_type=VOC&download_resources=true -H "Authorization: Token {token number}" --output {path/to/output/folder}`

The result is the same both for "  " and for '  ' around the Authorization, with and without the `--output`.  I also tried the `download_all_tasks=true` parameter.

I also tried running the command 
`curl -X GET http://{ip}:{port}/api/projects/ -H "Authorization: Token {token number}"`, 
which works fine

**Comment by makseq** [comment]
```
curl -X GET "http://{ip}:{port}/api/projects/14/export?export_type=VOC&download_resources=true" -H "Authorization: Token {token number}" --output {path/to/output/folder}
```
You should quote the path I guess.

**Comment by Hanysix** [comment]
Sure, the output path is:
`C:\Users\hanysix\Pictures\Bolt_tower_dataset\test`

**Comment by Hanysix** [comment]
I did not solve the issue and moved to other projects.
