### ISSUE TITLE
Playing an audio file on a mounted volume (docker image)

### ISSUE THREAD

**Issue by loic-mt** [heartexlabs/label-studio#3962]
**Describe the bug**

When uploading (import) a task involving an audio file, the UI plays it fine if that file has been imported to the UI (lands in /label-studio/data).
However, the UI won't play an audio file that sits on volume mounted on the docker container.

**To Reproduce**
1. Launch the docker container

`docker run -it -p 8080:8080 -v /mnt/data:/label-studio/data --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true --env LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files -v /mnt/files:/label-studio/files --security-opt seccomp=unconfined heartexlabs/label-studio:latest`

3. Use Python SDK to create project

```
project = ls.start_project(
        title=projectname,
        label_config='''
        <View>
            <Header value="Listen to the audio" />
            <Audio name="audio" value="$audio" />
            <Header value="Write the transcription" />
            <TextArea name="transcription" toName="audio"
            rows="4" editable="true" maxSubmissions="1" />
        </View>''')
```
5. Import task via SDK

```
task = 
{
  "data": {
    "audio": "/files/audiofiles/myfile.wav"
  },
  "annotations": [
    {
      "id": 1,
      "created_username": " john@doe.com 1",
      "created_ago": "2 days, 22 hours",
      "completed_by": {
        "id": 1,
        "first_name": "",
        "last_name": "",
        "avatar": null,
        "email": "john@doe.com",
        "initials": "jd"
      },
      "result": [
        {
          "from_name": "transcription",
          "origin": "manual",
          "original_length": 1359.730022675737,
          "to_name": "audio",
          "type": "textarea",
          "value": {
            "channel": 0,
            "end": 5.939999999999998,
            "start": 0,
            "text": [
              "Blah blah blah"
            ]
          }
        },
        {
          "from_name": "transcription",
          "origin": "manual",
          "original_length": 1359.730022675737,
          "to_name": "audio",
          "type": "textarea",
          "value": {
            "channel": 0,
            "end": 12.069999999999993,
            "start": 5.939999999999998,
            "text": [
              "Bleeh bleeh"
            ]
          }
]
}
```

`project.import_tasks([task])`

7. Go to project on web page

Click on that same task.

9. See error

The audio file won't load (counter stays stuck at 0 Mb, 100%

**Expected behavior**
Audio file should upload and we should be able to review and edit each segment's transcription.

**Screenshots**
![image](https://user-images.githubusercontent.com/26817866/229537380-955ba58a-2b54-4ae4-b9d4-172e64f021d9.png)

**Environment (please complete the following information):**
 - OS: docker container (running on Ubuntu 18.04)
 - Label Studio Version 1.7.1

**Additional context**

If the audio file has been uploaded previously, specifying a path to `/data` (something like `/data/media/upload/2/4rt45g_audio.wav`) has everything to work fine.

**Comment by makseq** [comment]
You didn't [connect Local Storage](https://labelstud.io/guide/storage.html#Set-up-connection-in-the-Label-Studio-UI-4).

**Comment by loic-mt** [comment]
Many thanks!
