### ISSUE TITLE
Prediction results cannot be displayed immediately

### ISSUE THREAD

**Issue by LiJianGuo2333** [heartexlabs/label-studio#3970]
Hi there,
I have met several problems when using the label studio in named entity recognition(NER) tasks. Hoping to find possible solutions.

**Environment**:

- OS: Linux, Ubuntu 18.04
- Python: 3.8.16
- LabelStudio 1.7.1
- LabelStudio ML BackEnd 1.0.8rc3

**Issues**:

1. Prediction results, which are text spans, cannot be displayed immediately on the labeling page. Only after refreshing the page then the prediction results can be displayed.
2. The prediction tasks cannot be performed automatically.

More details about my issues are described as follows. Here is a screenshot of my ML backend settings. 
![image](https://user-images.githubusercontent.com/26438402/229677402-73e59cb1-3cc3-49f3-a4ac-fd78eece2ed8.png)

And here is a screen recording video.

https://user-images.githubusercontent.com/26438402/229679376-3f6a13bf-5c85-46e5-bf85-cc07d34ff1ea.mp4

It takes about 30s for my NER model to perform one operation. As the video show, after the prediction is finished, the results will not be displayed on the labeling page immediately. Only after refreshing the page, the results can be seen. So how to display the results immediately after the prediction is done?

Another question, I want to run the prediction model on the whole dataset automatically. But as the video shows, the prediction job is triggered just on the one piece of data/task that I click. Are there any operations or settings I miss? Or what should I do to meet my demands?

Thanks

**Comment by makseq** [comment]
@LiJianGuo2333 Thank you for your great explanation, seems it's a bug, I've created a ticket LSDV-4913.

Similar problem:
https://github.com/heartexlabs/label-studio/issues/3717

> I want to run the prediction model on the whole dataset automatically.

Try to use Data manager => Select all tasks => Actions => Retrieve predictions.

**Comment by LiJianGuo2333** [comment]
Thanks a lot!!
