### ISSUE TITLE
CSS style is missing on style.html page

### ISSUE THREAD

**Issue by AbubakarSaad** [heartexlabs/label-studio#3980]
**Describe the bug**
There seems to be styles issue on https://labelstud.io/tags/style.html 

@erinmikailstaples @carly-bartel for vis

**Screenshots**
<img width="1512" alt="Screenshot 2023-04-04 at 4 47 43 PM" src="https://user-images.githubusercontent.com/4449857/229916916-04653ffe-76f0-44b3-8f60-75b62470936b.png">

**Comment by makseq** [comment]
Fixed.
