### ISSUE TITLE
Only download annotations.

### ISSUE THREAD

**Issue by kfarivar** [heartexlabs/label-studio#3992]
**Is your feature request related to a problem? Please describe.**
I think downloading just the annotations is essential since most people already have the data. 

**Describe the solution you'd like**
currently exporting in yolo format downloads the uploaded images which is unnecessary. I just want to download the segmentation coordinates.

Thank you.

**Comment by dao027** [comment]
got same issue

**Comment by makseq** [comment]
Check this endpoint
https://api.labelstud.io/#operation/api_projects_export_read

And use it with `download_all_resources=false`.
