### ISSUE TITLE
Label multiple tasks at once

### ISSUE THREAD

**Issue by mrijken** [heartexlabs/label-studio#40]
**Is your feature request related to a problem? Please describe.**
We want to use this tool for labeling texts. We  have a lot of texts which are almost the same. It will be convenient when it is possible to select a few tasks based on a simple query and label them at once with the selected label

**Describe the solution you'd like**

- enter a text to query all tasks for
- show all queried tasks
- select the tasks which are look-a-likes (with (de)select all option)
- select the label
- apply the label on all selected tasks

**Describe alternatives you've considered**
Labeling all tasks indivudually can be time consuming.

**Additional context**
n/a

**Comment by deppp** [comment]
@mrijken thanks for bringing that up. Interesting idea, but I'd assume it can only work for classification and not the region labeling?

We will be updating the data manager to something more powerful in the upcoming version and will consider how to add that, probably after we finalize the images support.

**Comment by vade** [comment]
I too would like some form of multiple task management - perhaps a simple first step might be something along the lines of:

* allow arrays in the backend `config.json` for each task. 

Something like:
* allow an array of front end label / view `config.json` files in the `backend/config.json` file  - letting a custom UI per task be created. 
* allow an array of task.jsons to be listed in the `backend/config.json` file, along with a change so output has the file name of the task.json prepended or appended. 
* allow an array of output folders in the `backend/config.json` file, allowing a 1:1 mapping of task input to output.

A 3 task setup might look like:

```
more config.json 
{
  "title": "Synopsis - Label Studio",
  "port": 8200,
  "debug": true,

  "label_config": ["../examples/synopsis_image/config_task1.xml", 
                             "../examples/synopsis_image/config_task2.xml", 
                             "../examples/synopsis_image/config_task3.xml"],
  "input_path": ["../examples/synopsis_image/some_taskname.json",
                          "../examples/synopsis_image/some_other_taskname.json",
                          "../examples/synopsis_image/last_task.json"],

  "output_dir": ["../examples/synopsis_image/completions/task1",
                          "../examples/synopsis_image/completions/task2",
                          "../examples/synopsis_image/completions/task3"],

  "instruction": "Choose a task, and complete the instructions in the UI shown",
  "allow_delete_completions": true,

  "editor": {
    "build_path": "../build/static",
    "debug": false
  }
}

```

Clearly there'd have to be a check to ensure each label_config,  input_path and output_dir had matching array sizes.

Finally, Some simple UI to chose which task, which could be even some sort of URL component string like

```http://192.168.1.183:8200/?taskname=some_taskname&task_id=1```

Just thinking aloud. Thanks again for this project!

**Comment by NandaBalakrishnan** [comment]
are we supporting labeling multiple task at once? (only for image classfication)

**Comment by makseq** [comment]
@NandaBalakrishnan We are very close to it. I think it will be in one release.
