### ISSUE TITLE
Heroku security setting up

### ISSUE THREAD

**Issue by yemregundogmus** [heartexlabs/label-studio#401]
Hello Everyone, 

Is it possible to set "Auth with login and password" for security while deploying via heroku?

Best Regards,

**Comment by makseq** [comment]
Hello! 
Check this: https://labelstud.io/guide/#Auth-with-login-and-password

**Comment by makseq** [comment]
@yemregundogmus

**Comment by yemregundogmus** [comment]
Hello!
Thank you very much for your answer. 
I was wondering could i make direct changes in "one click heroku deploy" instead of change in config file.

**Comment by makseq** [comment]
I think we need to do some preparations in docker. Can you add additional environment variables for login & password on heroku?

**Comment by makseq** [comment]
@yemregundogmus

**Comment by makseq** [comment]
@yemregundogmus 

1. Setup USERNAME=xxx and PASSWORD=zzz
2. Run image heartexlabs/label-studio:0.7.5
