### ISSUE TITLE
Make a copy of a project

### ISSUE THREAD

**Issue by jeremiahbudiman** [heartexlabs/label-studio#4021]
Is there a way to make a copy of a project in label studio? Let's say I have an existing project. I want to make a copy of it and make edits to it but keep the original in case something goes wrong. Is there a way to do this?

**Comment by makseq** [comment]
In Label Studio Enterprise we have project duplication. In the community version you can export your json snapshot and reimport it back to the new project.

**Comment by saskra** [comment]
> you can export your json snapshot and reimport it back to the new project.

Unfortunately, this only exports and imports labels and not, for example, labeling interface, cloud storage, images etc. Is there also a possibility for this?

**Comment by parabolabam** [comment]
@saskra Hi, I stumbled upon this issue just occasionally, I don't know when this was released, but you can export all your tasks using this endpoint of CE version of LabelStudio 
https://labelstud.io/guide/export#Export-all-tasks-including-tasks-without-annotations 

You can use it to export your both your tasks and annotations altogether

**Comment by parabolabam** [comment]
I personally find it quite weird to have a project duplication as an enterprise feature by the way 😉

**Comment by DefacedFace** [comment]
Agreed. It's a bit of a nickel and dime thing that should just be standard.
