### ISSUE TITLE
text highlight color (i.e., change color from black to a different color) doesn't seem to work

### ISSUE THREAD

**Issue by ronadar** [heartexlabs/label-studio#4045]
I want to change the text color in a Text field. 

There is an example in the manual here:
https://labelstud.io/tags/text.html

<View>
  <Text name="text-1" value="$text" granularity="word" highlightColor="#ff0000" />
  <Labels name="ner" toName="text-1">
    <Label value="Person" />
    <Label value="Location" />
  </Labels>
</View>

But though the font color should be red, it is not. It remains black. I tried it with some other color as well, nothing changed. 
Am I missing anything? Seems weird for me that a formal example doesn't work (you can also see that it doesn't work in the preview\background).

**Comment by ronadar** [comment]
I will appreciate any help! (It is the first time for me using this tool, so if I missed the correct way of doing things, pls send me a link\code example that do work and change the text color. Thank you!!

**Comment by makseq** [comment]
I apologize for the confusion. It seems that there might be an issue with the example provided in the documentation. You can try using the `<Style>` tag to change the text color. Here's an example:

```xml
<View>
  <Style>
    .custom-text {
      color: red;
    }
  </Style>
  <View className="custom-text">
    <Text name="text" value="$text"/>
  </View>
</View>
```
In this example, we define a custom CSS class called "custom-text" and set the color property to red. Then, we apply this class to the `<Text>` tag using the `className` attribute. This should change the text color to red.

Or you can do it using style inside of View explicitly:

```xml
<View>
  <View style="color:red">
    <Text name="text" value="$text" />
  </View>
</View>
```
