### ISSUE TITLE
How to turn on pan image by default

### ISSUE THREAD

**Issue by jet-c-21** [heartexlabs/label-studio#4047]
How can I enable the pan image feature by default when switching to a new task? So that user doesn't need to press "H"

**Comment by dao027** [comment]
got same issue

**Comment by makseq** [comment]
Thank you for this improvement request, we will discuss it with out frontend team. 
I've created a ticket: [LSDV-5013](https://labelstudio.aha.io/develop/features/LSDV-5013)

**Comment by deppp** [comment]
Hey @jet-c-21 @dao027, have you tried the setting "Remember Selected Tool"?

**Comment by jet-c-21** [comment]
"Remember Selected Tool" ? Is it in the web GUI? where is it? @deppp

**Comment by AbubakarSaad** [comment]
<img width="1512" alt="Screenshot 2023-05-31 at 1 59 23 AM" src="https://github.com/heartexlabs/label-studio/assets/4449857/84de82d3-d54d-4a84-a9a3-6b834f8c4d51">
When you click these 
<img width="53" alt="Screenshot 2023-05-31 at 2 00 01 AM" src="https://github.com/heartexlabs/label-studio/assets/4449857/0ee121bb-dc79-4047-8cba-6694ca370789"> in a task view
