### ISSUE TITLE
why "Bbox object detection" cannot review result after labelled

### ISSUE THREAD

**Issue by zhl5317** [heartexlabs/label-studio#406]
**Screenshots**
![12](https://user-images.githubusercontent.com/17403033/91029130-f74c1a80-e630-11ea-9f43-573fc4b8a0bb.png)
![image](https://user-images.githubusercontent.com/17403033/91029194-08952700-e631-11ea-8bcd-99ac126dc2ec.png)

**Comment by makseq** [comment]
@zhl5317 Can you go to 
![image](https://user-images.githubusercontent.com/501780/91051068-3e81dd80-e628-11ea-9418-6fb3ef9510ea.png)
and reload page fully to check if image could be loaded?

**Comment by hlomzik** [comment]
Hi! This error shows that image was not loaded for some reason. Could you please show the top of console output? You can hide all urls except protocols, I'm just interested in errors)

**Comment by zhl5317** [comment]
> @zhl5317 Can you go to Network
> ![image](https://user-images.githubusercontent.com/501780/91051068-3e81dd80-e628-11ea-9418-6fb3ef9510ea.png)
> and reload page fully to check if image could be loaded?

**Comment by zhl5317** [comment]
> Hi! This error shows that image was not loaded for some reason. Could you please show the top of console output? You can hide all urls except protocols, I'm just interested in errors)

hI, all console outpout is
![image](https://user-images.githubusercontent.com/17403033/91052433-07292600-e654-11ea-97cc-e45820555fd2.png)



and i check the network img, the image link can be accessed

![image](https://user-images.githubusercontent.com/17403033/91052731-7272f800-e654-11ea-90a4-9bcd89f90f1f.png)

**Comment by zhl5317** [comment]
> > @zhl5317 Can you go to Network
> > ![image](https://user-images.githubusercontent.com/501780/91051068-3e81dd80-e628-11ea-9418-6fb3ef9510ea.png)
> > and reload page fully to check if image could be loaded?

hi  this is all console output, only show "react-reconciler.production.min.js:2371 DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0."  and i check the network img, the image link can be accessed.
![image](https://user-images.githubusercontent.com/17403033/91052923-b534d000-e654-11ea-8753-6512e7c9fe4b.png)
![image](https://user-images.githubusercontent.com/17403033/91053117-f5944e00-e654-11ea-8d24-a8d6a0690abc.png)

**Comment by zhl5317** [comment]
hi


Reload the page can not load either, and console all output only show







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heartexlabs/label-studio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 晚上9:39
收件人:&nbsp;"heartexlabs/label-studio"<label-studio@noreply.github.com&gt;;
抄送:&nbsp;"809041737"<zhl85948034@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [heartexlabs/label-studio] why "Bbox object detection" cannot review result after labelled (#406)





 
@zhl5317 Can you go to
 
 and reload page fully to check if image could be loaded?

**Comment by zhl5317** [comment]
that's all console output







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heartexlabs/label-studio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 晚上9:41
收件人:&nbsp;"heartexlabs/label-studio"<label-studio@noreply.github.com&gt;;
抄送:&nbsp;"809041737"<zhl85948034@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [heartexlabs/label-studio] why "Bbox object detection" cannot review result after labelled (#406)





 
Hi! This error shows that image was not loaded for some reason. Could you please show the top of console output? You can hide all urls except protocols, I'm just interested in errors)

**Comment by makseq** [comment]
@zhl5317 Why did you close this issue? Have you found a solution?

**Comment by zhl5317** [comment]
oh, thanks, wrong click, i have reopen it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heartexlabs/label-studio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 晚上10:36
收件人:&nbsp;"heartexlabs/label-studio"<label-studio@noreply.github.com&gt;;
抄送:&nbsp;"809041737"<zhl85948034@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [heartexlabs/label-studio] why "Bbox object detection" cannot review result after labelled (#406)





 
@zhl5317 Why did you close this issue? Have you found a solution?

**Comment by makseq** [comment]
Can you show your labeling config and sample task?

**Comment by zhl5317** [comment]
please refer to attached


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heartexlabs/label-studio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 晚上10:49
收件人:&nbsp;"heartexlabs/label-studio"<label-studio@noreply.github.com&gt;;
抄送:&nbsp;"809041737"<zhl85948034@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [heartexlabs/label-studio] why "Bbox object detection" cannot review result after labelled (#406)





 
Can you show your labeling config and sample task?

**Comment by makseq** [comment]
@zhl5317 Sorry, what attachment do you mean?

**Comment by zhl5317** [comment]
task.json:
{
&nbsp; "4": {
&nbsp; &nbsp; "id": 4,
&nbsp; &nbsp; "data": {
&nbsp; &nbsp; &nbsp; "image": "https://timgsa.baidu.com/timg?image&amp;quality=80&amp;size=b9999_10000&amp;sec=1598012320734&amp;di=bc1a884bdcba036c1c426443692d24d3&amp;imgtype=0&amp;src=http%3A%2F%2Fwww.demodashi.com%2Fueditor%2Fjsp%2Fupload%2Fimage%2F20170802%2F1501642981629058693.jpeg"
&nbsp; &nbsp; }
&nbsp; },
&nbsp; "5": {
&nbsp; &nbsp; "id": 5,
&nbsp; &nbsp; "data": {
&nbsp; &nbsp; &nbsp; "image": "https://timgsa.baidu.com/timg?image&amp;quality=80&amp;size=b9999_10000&amp;sec=1598012320734&amp;di=bc1a884bdcba036c1c426443692d24d3&amp;imgtype=0&amp;src=http%3A%2F%2Fwww.demodashi.com%2Fueditor%2Fjsp%2Fupload%2Fimage%2F20170802%2F1501642981629058693.jpeg"
&nbsp; &nbsp; }
&nbsp; }
}



config.xml:
<View&gt;
&nbsp; <Image name="image" value="$image"/&gt;
&nbsp; <EllipseLabels name="tag" toName="image"&gt;
&nbsp; &nbsp; <Label value="Airplane" background="green"/&gt;
&nbsp; &nbsp; <Label value="Car" background="blue"/&gt;
&nbsp; </EllipseLabels&gt;
</View&gt;





completions:
{
&nbsp; "completions": [
&nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; "created_at": 1598263591,
&nbsp; &nbsp; &nbsp; "id": 1001,
&nbsp; &nbsp; &nbsp; "lead_time": 3.879,
&nbsp; &nbsp; &nbsp; "result": [
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "from_name": "tag",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "id": "h7iQidjIqx",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "original_height": 240,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "original_width": 490,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "source": "$image",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "to_name": "image",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "ellipselabels",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "value": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "ellipselabels": [
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "Car"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ],
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "radiusX": 6.326530612244898,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "radiusY": 9.583333333333334,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "rotation": 0,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "x": 46.53061224489796,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "y": 45.416666666666664
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; ]
&nbsp; &nbsp; }
&nbsp; ],
&nbsp; "data": {
&nbsp; &nbsp; "image": "https://timgsa.baidu.com/timg?image&amp;quality=80&amp;size=b9999_10000&amp;sec=1598012320734&amp;di=bc1a884bdcba036c1c426443692d24d3&amp;imgtype=0&amp;src=http%3A%2F%2Fwww.demodashi.com%2Fueditor%2Fjsp%2Fupload%2Fimage%2F20170802%2F1501642981629058693.jpeg"
&nbsp; },
&nbsp; "id": 1
}









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heartexlabs/label-studio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 晚上11:15
收件人:&nbsp;"heartexlabs/label-studio"<label-studio@noreply.github.com&gt;;
抄送:&nbsp;"809041737"<zhl85948034@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [heartexlabs/label-studio] why "Bbox object detection" cannot review result after labelled (#406)





 
@zhl5317 Sorry, what attachment do you mean?

**Comment by makseq** [comment]
@zhl5317 Could you test LS release/0.7.4 now? Is your error still there?

**Comment by zhl5317** [comment]
Hi max


i test on LS0.7.4, still same error









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heartexlabs/label-studio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 晚上11:34
收件人:&nbsp;"heartexlabs/label-studio"<label-studio@noreply.github.com&gt;;
抄送:&nbsp;"809041737"<zhl85948034@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [heartexlabs/label-studio] why "Bbox object detection" cannot review result after labelled (#406)





 
@zhl5317 Could you test LS release/0.7.4 now? Is your error still there?

**Comment by makseq** [comment]
@zhl5317 
Why do you have doubled "completions" seсtions? 

```
completions:
{
&nbsp; "completions": [
...
```

**Comment by zhl5317** [comment]
@makseq

no, Just one example

actually my completions is:
![image](https://user-images.githubusercontent.com/17403033/91372503-6058ab80-e846-11ea-8420-5e9c1f440f36.png)

**Comment by makseq** [comment]
@hlomzik Can you check this issue about canvas: https://github.com/niklasvh/html2canvas/issues/1859
It seems really something strange in it...

**Comment by makseq** [comment]
@zhl5317 do you have this trouble in the each task?

**Comment by zhl5317** [comment]
@makseq 

no， other image tagging task are all ok， only “object detection“  have this trouble

**Comment by makseq** [comment]
@zhl5317 I explored your completion more detailed and found that there is "ellipselabels" inside, but you are talking about bboxes. I think you broke the integrity somewhere between the labeling config and task completions.

**Comment by zhl5317** [comment]
@makseq 

thank you for your attention

actually, ithing my data is ok, because the data is created by LS tagging, not created by by myself. the following pic is my test data

![image](https://user-images.githubusercontent.com/17403033/91790606-cb89ef80-ec43-11ea-8302-dbeb05369a1f.png)

`{
  "completions": [
    {
      "created_at": 1598929260,
      "id": 1001,
      "lead_time": 4.093,
      "result": [
        {
          "from_name": "label",
          "id": "f2I9aRX-3x",
          "image_rotation": 0,
          "original_height": 403,
          "original_width": 600,
          "parent_id": null,
          "source": "$image",
          "to_name": "image",
          "type": "rectanglelabels",
          "value": {
            "height": 56.96517412935324,
            "rectanglelabels": [
              "Airplane"
            ],
            "rotation": 0,
            "width": 22.666666666666668,
            "x": 39.333333333333336,
            "y": 31.8407960199005
          }
        }
      ]
    }
  ],
  "data": {
    "image": "https://app.heartex.ai/static/samples/sample.jpg"
  },
  "id": 1
}`

 you can try "Bbox object detection" in your side to check whether has the issue

**Comment by makseq** [comment]
I checked your completion on my side. Everything is ok... 
Do you use google chrome? Or some custom version of it?

**Comment by zhl5317** [comment]
@makseq 

yes, im using chrome, Is there a compatibility issue on Chrome?

**Comment by makseq** [comment]
Maybe. I'm trying to do some checks.
Can you try another browser? And please show your label config.

**Comment by zhl5317** [comment]
@makseq 
anyway, thank you for your quick reply, i will track  my configrations in more detail, and i will try on other another browser

mysql label config is official website example
`<View>
  <Image name="image" value="$image"/>
  <RectangleLabels name="label" toName="image">
    <Label value="Airplane" background="green"/>
    <Label value="Car" background="blue"/>
  </RectangleLabels>
</View>
`

I will give you feedback on any discovery， one more thanks

**Comment by zhl5317** [comment]
@makseq 

i try on other browser (ie Edge) is ok, 

but on chrome sometimes is ok, sometime will occurs " Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0", its very strange
![image](https://user-images.githubusercontent.com/17403033/91938127-fba9bf00-ed25-11ea-8c2d-7d445f1645af.png)

![image](https://user-images.githubusercontent.com/17403033/91938079-e5036800-ed25-11ea-8067-823534d5b095.png)

**Comment by makseq** [comment]
@zhl5317 Do you still have this issue? Can you try release 0.7.5rc3? (it's in pypi: pip install label-studio==0.7.4rc3)

**Comment by makseq** [comment]
I faced this issue. The problem could be in the too small area where LSF is placed. Try to pre-define it at least with width=500px.

**Comment by makseq** [comment]
@zhl5317 Does it help you?

**Comment by korotaS** [comment]
> I faced this issue. The problem could be in the too small area where LSF is placed. Try to pre-define it at least with width=500px.

Hi @makseq ! I also faced this issue. Where can i pre-define the LSF area width?

**Comment by makseq** [comment]
@korotaS Hi, I hope we fixed it since 0.7.5.post0 release. Check this release, please.
