### ISSUE TITLE
SDK create_user unable to log in

### ISSUE THREAD

**Issue by QuanCheng-QC** [heartexlabs/label-studio#4061]
```
class LabelStudioSdk:
    """
    skd: https://labelstud.io/guide/sdk.html
    """
    def __init__(self):
        self.client = Client(url=LABEL_STUDIO_URL, api_key=LABEL_STUDIO_TOKEN)
        self.client.check_connection()
    async def create_user(self, user: dict):
        """create_user
       {
                'username': user.username,
                'email': user.email,
                'first_name': user.first_name,
                'last_name': user.last_name,
                'phone': user.phone,
            }
        """
        response = self.client.create_user(user)
        return response
```

  my data is:

```
    user_dict = {
                "username": "chengquan",
                "email": "cq2004@163.com",
                "password": "cq1008611001",
                "first_name": "cheng",
                "last_name": "quan",
                "phone": phone,
                "active_organization": 1
            }
            response = await LabelStudioSdk().create_user(user_dict)
     reponse_code is 201
     cq2004@163.com  Unable to log in on the page
```

**Comment by QuanCheng-QC** [comment]
![image](https://user-images.githubusercontent.com/52530795/233043604-ea55d214-eb32-499b-90af-c7a4ba6ee385.png)

**Comment by QuanCheng-QC** [comment]
docker image  heartexlabs/label-studio:latest
I found that this user data is not available in the database
![image](https://user-images.githubusercontent.com/52530795/233044516-0287692e-1e72-4090-a940-e1c73208e7e1.png)
![image](https://user-images.githubusercontent.com/52530795/233044470-07bdcaad-53d5-4bcb-8a66-7d4b7de3d9d4.png)
![image](https://user-images.githubusercontent.com/52530795/233044295-0d60b654-e6d2-436a-ad66-653d94d8ad9c.png)

**Comment by makseq** [comment]
Seems the problem is here:
https://github.com/heartexlabs/label-studio/blob/c3fb3f69089e065c923ea7218ca3d850fc1ab98a/label_studio/users/serializers.py#L37

Label Studio doesn't save passwords for users via API. 

You can try to implement a special user serializer for UserAPI.create() method which will store passwords. You need to add password into the serializer's fields.

**Comment by QuanCheng-QC** [comment]
> 似乎问题就在这里： https://github.com/heartexlabs/label-studio/blob/c3fb3f69089e065c923ea7218ca3d850fc1ab98a/label_studio/users/serializers.py#L37
> 
> Label Studio 不会通过 API 保存用户密码。
> 
> 您可以尝试为 UserAPI.create() 方法实现一个特殊的用户序列化器，该方法将存储密码。您需要将密码添加到序列化器的字段中。

Thanks

**Comment by QuanCheng-QC** [comment]
> 似乎问题就在这里： https://github.com/heartexlabs/label-studio/blob/c3fb3f69089e065c923ea7218ca3d850fc1ab98a/label_studio/users/serializers.py#L37
> 
> Label Studio 不会通过 API 保存用户密码。
> 
> 您可以尝试为 UserAPI.create() 方法实现一个特殊的用户序列化器，该方法将存储密码。您需要将密码添加到序列化器的字段中。

Alternatively, you can use the invitation link to save the user password
http://xxxxx/user/signup/?token=xxxxx
