### ISSUE TITLE
Inconsistent RectangleLabels Export

### ISSUE THREAD

**Issue by tlaud** [heartexlabs/label-studio#407]
**Edit: Just my stupidity, no bug... After studying label-studio-converter/label_studio_converter/converter.py in detail, I realized that the mentioned values are not absolute but percentage values w.r.t. the original size. 

Straight-forward calculations like x = x * original_width /100.0, etc., did the trick.

My suggestion would be to document this behavior somewhere :-)**

Hi,

When I label bounding boxes, the exported JSON will look like this:
{
    "from_name": "tag",
    "id": "JEzqD6xkmq",
    "image_rotation": 0,
    "original_height": 154,
    "original_width": 66,
    "parent_id": null,
    "source": "$image",
    "to_name": "image",
    "type": "rectanglelabels",
    "value": {
        "height": 14.285714285714286,
        "rectanglelabels": [
            "box_name"
        ],
        "rotation": 0,
        "width": 28.78787878787879,
        "x": 40.90909090909091,
        "y": 7.142857142857143
    }
}

My intuitive guess was that x and y refer to the top-left corner of the bounding box and that (x+width, y+height) will yield to bottom-right corner of the bounding box. However, this is not the case. 

Instead, x and y appear to randomly point to either of the following corner: top-left, top-right, bottom-left, bottom-right.

Furthermore, width and height can be either horizontally or vertically. 

Is the mistake on my side, am I missing something, or is this behavior unintended? 

Info: The problem occurs with a fresh version of label Studio installed via pip. The corresponding config snippet is:
```
<RectangleLabels name="tag" toName="image">
    <Label value="box_name" background="red"></Label>
</RectangleLabels>
```

**Comment by makseq** [comment]
> My suggestion would be to document this behavior somewhere :-)

It's a good idea!
