### ISSUE TITLE
Ability to have alternate versions of the same image to annotate with RoiPolygon

### ISSUE THREAD

**Issue by p-sodmann** [heartexlabs/label-studio#408]
## Why
In biomedical images there are usually different image modalities of the same object. For example different weightings in MRI for the same slice or different staining / immunofluorescence channels with different proteins in the same specimen in microscopy.
Just having the possibility to make a ROI selection based on one modality limits the use of label-studio.

Conditional Labeling with choices provides an Opportunity but cannot share the annotation across different images.

## Solution
One possibility would be to give Annotation objects the ability to attach toName to a list of objects
```<PolygonLabels name="label" toName=["image_x", "image_y", "image_z"]>```

Or Group the images together, since only one can be displayed at every time anyway
```HTML
  <View visibleWhen="choice-selected"
        whenTagName="image_modality" whenChoiceValue="Vx">
  	<Image name="image_x" group="image" value="$image_z" zoomControl="true" zoom="true"/>
  </View>
  <View visibleWhen="choice-selected"
        whenTagName="image_modality" whenChoiceValue="Vy">
  	<Image name="image_y" group="image" value="$image_y" zoomControl="true" zoom="true"/>
  </View>

<PolygonLabels name="label" toName=image>
```

**Comment by makseq** [comment]
@theudas We have discussed this issue with the team, I hope we implement it soon.

**Comment by makseq** [comment]
@hlomzik Have you any news?

**Comment by makseq** [comment]
@p-sodmann Sorry for a late answer, but we have implemented a multi-layer image approach finally: 
https://github.com/heartexlabs/label-studio-frontend/pull/164

I think we will include it into release 0.9.1. 

Feel free to reopen this issue if you have any problems.
