### ISSUE TITLE
NameError: name 'total' is not defined

### ISSUE THREAD

**Issue by motionlife** [heartexlabs/label-studio#4081]
https://github.com/heartexlabs/label-studio/blob/6a05a3dce33cb2ca735da988477521ed22408cff/label_studio/data_import/uploader.py#L59

If number of files exceed the settings.TASKS_MAX_FILE_SIZE, this error will happen, clearly total variable is not defined here.
Should we change it to `value` ?

**Comment by AbubakarSaad** [comment]
Hello Motionlife,

Yes, please. Try increase the size of this and see what happens. When does this happen, when importing files?

**Comment by joshhansen** [comment]
I am getting this when importing files. It never happens when I import just one file, only when I drag and drop (or select) more than one file. And yet if I select the same files individually, or in other groupings, there is no error.

**Comment by uzahid** [comment]
> @AbubakarSaad 

Is there a way to change this setting while running label studio through docker image?

**Comment by Axel-Jacobsen** [comment]
It's a bug introduced by https://github.com/heartexlabs/label-studio/commit/1d3c9bf51f5ec6dbc8f7f29efa83745f68c96dcf#

I'll create a pr to fix this

**Comment by Axel-Jacobsen** [comment]
> I am getting this when importing files. It never happens when I import just one file, only when I drag and drop (or select) more than one file. And yet if I select the same files individually, or in other groupings, there is no error.

This is because when you select multiple files at once, their total size is greater than `settings.TASKS_MAX_FILE_SIZE` (or some other max size perhaps). The error occurs in the error message reporting, where it references a variable named `total`. The error message is `Maximum total size of all files is {settings.TASKS_MAX_FILE_SIZE} bytes`. For me, `settings.TASKS_MAX_FILE_SIZE = 250` Mb

**Comment by Axel-Jacobsen** [comment]
@uzahid by setting `DATA_UPLOAD_MAX_MEMORY_SIZE` in terminal - e.g. `DATA_UPLOAD_MAX_MEMORY_SIZE=1073741824` to set the max upload size to 1 Gb (see https://github.com/heartexlabs/label-studio/blob/dab42819ce419a78a80c8ea738beb2eaf03af739/label_studio/core/settings/base.py#L445-L447)

**Comment by MichaelGMoore** [comment]
I am receiving this error " name 'total' is not defined " when I try to import a video. 
I run "label-studio start" from command line and enter a browser-based interface. It prompts me to import data. When I try to import my .avi file, I get this error.
I am not a python programmer.
Any suggestions for how to get my video to load?

**Comment by Axel-Jacobsen** [comment]
Hi @MichaelGMoore! This is the right issue for the problem. I've opened up a [pull request to fix the issue with the weird error message](https://github.com/heartexlabs/label-studio/pull/4292), but the actual fix will be to do what I suggested above. Depending on how large your `.avi` file is, you'll have to adjust `DATA_UPLOAD_MAX_MEMORY_SIZE` to accommodate it. 

So, if your `.avi` file is 500 Mb, you would want to adjust `DATA_UPLOAD_MAX_MEMORY_SIZE` to, say, 600 Mb for safety. So 600 * 1024 * 1024 = 629,145,600, so you would want to start label studio like so:

`DATA_UPLOAD_MAX_MEMORY_SIZE=629145600 label-studio start`

**Comment by MichaelGMoore** [comment]
Thank you. This worked for me.

**Comment by migoVanDingo** [comment]
Despite trying @Axel-Jacobsen 's answer that worked for Michael. It did not work for me.  Still getting the `[4fccf696-35c1-44e5-8eda-dc09cf02fcb1] name 'total' is not defined` error. Do I need to rebuild the project somehow? Once I made the change in the code, I simply ran `label-studio start`. Maybe I missed something...?

**Comment by migoVanDingo** [comment]
Okay changing the code didn't work, but exporting the variable as environment variable did the trick.  Thanks @Axel-Jacobsen

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
