### ISSUE TITLE
Unable to Load Mask from RLE in LabelStudio despite it showing there is a prediction

### ISSUE THREAD

**Issue by shantanudev** [heartexlabs/label-studio#4084]
I am using cv2 to perform adaptivethreshold and take the mask outputs from there and utilize the brush library encode_rle and the example function image2annotation. I load that into predictions but when I click on the image in labelstudio it says there is a prediction but doesn't render the mask overlay.

**To Reproduce**
1. CV2 --> Adaptive Threshold to generate mask
2. Convert numpy --> RLE
3. Format RLE using image2annotation
4. Load json into labelstudio

**Expected behavior**
Says there is a mask annotation on labelstudio, but will not load it. I attached screenshots of my code and outputs below.

<img width="742" alt="Screenshot 2023-04-23 at 9 48 28 PM" src="https://user-images.githubusercontent.com/6792587/233881589-91eb0888-0943-402b-8904-ae09fc8d0932.png">
<img width="546" alt="Screenshot 2023-04-23 at 9 48 42 PM" src="https://user-images.githubusercontent.com/6792587/233881607-ad5a2c5c-b353-406d-91fe-316635bfec19.png">
<img width="590" alt="Screenshot 2023-04-23 at 9 48 58 PM" src="https://user-images.githubusercontent.com/6792587/233881618-f9c4e363-67b6-411e-af96-dd4d866925bc.png">

**Comment by AbubakarSaad** [comment]
Hello shantanudev,

Is it possible to show the json and how that prediction compare to the task source of any annotation? I think you should load it under "prediction" rather than "annotations"

**Comment by shantanudev** [comment]
I tried both but had no luck with either. `{"id": 483445, "annotations": [{"result": [{"id": "65893112-2__9", "type": "brushlabels", "value": {"rle": [], "format": "rle", "brushlabels": ["Mask"]}, "origin": "manual", "to_name": "image", "from_name": "tag", "image_rotation": 0, "original_width": 1024, "original_height": 1024}]}], "drafts": [], "predictions": [], "data": {"image": "/data/local-files/?d=label-studio/angio_slices/00005391-b__12.jpg"}, "meta": {}, "created_at": "2023-04-23T06:01:22.687474Z", "updated_at": "2023-04-23T06:01:22.687520Z", "inner_id": 5, "total_annotations": 0, "cancelled_annotations": 0, "total_predictions": 0, "comment_count": 0, "unresolved_comment_count": 0, "last_comment_updated_at": null, "project": 13, "updated_by": null, "comment_authors": []}]`

**Comment by shantanudev** [comment]
project.create_prediction(
    task_id=483444,
    model_version=None,
    result=[
        {
            "from_name": "tag",
            "to_name": "image",
            "type": "brushlabels",
            'value': {"format": "rle", "rle": rle, "brushlabels": ['Mask']},
        }
    ],
)
tried this way as well but fail

**Comment by AbubakarSaad** [comment]
I think the issue is that `"rle": []` is empty. There isn't a mask to show. Is it possible to make sure the object has values before loading in LS? Can you also paste the output of that method here?

**Comment by shantanudev** [comment]
Thank you for the reply. I did finally solve it! This is for everyone else that couldn't figure it out. Just use the SDK Library to help you load this. It is much faster this way. Here is my code snippet:

```
import label_studio_converter.brush as brush
from label_studio_sdk import Client

def mask2labelstudio(task_id):
    project.create_prediction(task_id=task_id, model_version=None, result = [{
    "from_name": "tag",
    "to_name": "image",
    "type": "brushlabels",
    'value': {
        "format": "rle",
        "rle": rle,
        "brushlabels": ['Mask']
    }
}])

for task in tqdm(project_tasks):
    mask=np.load(os.path.join(mask_path,task['storage_filename'].split('/')[-1].split('.jpg')[0]+'.npy'))
    mask = np.array(mask > 0) * 255
    rle=brush.mask2rle(mask)
    mask2labelstudio(task['id'])
```
