### ISSUE TITLE
Missing Comment Section On Image Annotation

### ISSUE THREAD

**Issue by vabt-igd** [heartexlabs/label-studio#4086]
**Description**
This may well be a user error and not a bug report, as I am new to Label Studio:
When I use the latest Label Studio tag (1.7.3) for image annotation, the comment section is missing.
In the previous version (1.7.2), the comment panel was on the right side under the annotation history section.
In case it matters: 
I use brush and rectangle annotations and a pre-annotation backend which provides brush annotation predictions.

**To Reproduce**
1. Install label studio via pip on a supported python version
2. Add a brush label config via a template or add the following:
```
<View>
  <Image name="image" value="$image" zoom="true" zoomControl="true" rotateControl="true"/>
  <View>
    <Filter toName="BrushLabels" minlength="0" name="BrushLabelFilter"/>
    <BrushLabels smart="true" name="BrushLabels" toName="image">
      <Label value="BL 1" background="#a7f8a5"/>      
      <Label value="BL 2" background="#b5b6e8"/>
      <Label value="BL 3" background="#D4380D"/>
    </BrushLabels>
    <Filter toName="RectangleLabels" minlength="0" name="RectangleLabelFilter"/>
    <RectangleLabels name="RectangleLabels" toName="image">
      <Label value="RL 1" background="#FFA39E"/>
      <Label value="RL 2" background="#D4380D"/>
      <Label value="RL 3" background="#FFC069"/>
    </RectangleLabels>
  </View>
</View>
```
3. Upload images to annotate
4. Go to annotation view by clicking on an image
5. Attempt to find the comment section and fail...

**Expected behavior**
The comment section should be available on the right-hand side (assuming no customization).

**Environment (please complete the following information):**
 - OS: Windows 11 x64
 - Label Studio Version 1.7.3

**Comment by AbubakarSaad** [comment]
Hello vabt-igd,

Comments are only available for Enterprise version. Might been a little glitch or something

**Comment by vabt-igd** [comment]
Okay, got it. Thanks!
