### ISSUE TITLE
Different Mouse Pointer on ROI Polygon

### ISSUE THREAD

**Issue by p-sodmann** [heartexlabs/label-studio#409]
## Why
When using the ROI Polygon Tool, it is frustrating to have no visual feedback weather you will drag the whole polygon or change a single point. This often results in me dragging the whole polygon instead of a single point as intended.

## Solution
Change the cursor icon depending on the action that will happen when I drag at the current position. 
For example curser:grab if I would move the whole polygon and cursor:move when I would move a single polygon corner. 
Maybe also change the cursor to cursor:crosshair while drawing new points / a new polygon.

**Comment by makseq** [comment]
@hlomzik I think you can implement this very quickly.

**Comment by hlomzik** [comment]
Yes, sounds very easy and helpful, just to change `cursor` in one place. Will deploy soon, thanks!

**Comment by makseq** [comment]
It's fixed after 0.8.1 release.
