### ISSUE TITLE
Export format list doesn't include COCO and PASCAL VOC

### ISSUE THREAD

**Issue by fsalmasri** [heartexlabs/label-studio#410]
I have 
label-studio==0.7.4.post0
label-studio-converter==0.0.18

But in the list as shown below it doesn't include of the other formats. 
![coco](https://user-images.githubusercontent.com/5776719/91554069-b143cf00-e92e-11ea-8aaf-1c10650ff0a5.png)

**Comment by makseq** [comment]
@fsalmasri Can you show your label config?

**Comment by fsalmasri** [comment]
Config.xml 

```
<View>

  <Header value="Select label and start to click on image"></Header>
  <Image name="image" value="$image"></Image>

  <PolygonLabels name="label" toName="image" strokeWidth="3" pointSize="small" opacity="0.9">
    <Label value="Person" background="red"/>
    <Label value="Car" background="blue"/>
    <Label value="Var" background="black"/>
  </PolygonLabels>

</View>
```

config.Json

`{"title": "Label Studio", "protocol": "http://", "host": "0.0.0.0", "port": 8080, "debug": false, "label_config": "C:\\Users\\fedai\\Desktop\\projects\\dataset\\ULB-VISTI-V2\\Test\\test\\config.xml", "input_path": "C:\\Users\\fedai\\Desktop\\projects\\dataset\\ULB-VISTI-V2\\Test\\test\\tasks.json", "output_dir": "C:\\Users\\fedai\\Desktop\\projects\\dataset\\ULB-VISTI-V2\\Test\\test\\completions", "instruction": "Type some <b>hypertext</b> for label experts!", "allow_delete_completions": true, "templates_dir": "examples", "editor": {"debug": false}, "sampling": "sequential", "ml_backends": [], "source": {"name": "Tasks", "type": "tasks-json", "path": "C:\\Users\\fedai\\Desktop\\projects\\dataset\\ULB-VISTI-V2\\Test\\test\\tasks.json"}, "target": {"name": "Completions", "type": "completions-dir", "path": "C:\\Users\\fedai\\Desktop\\projects\\dataset\\ULB-VISTI-V2\\Test\\test\\completions"}, "config_path": "C:\\Users\\fedai\\Desktop\\projects\\dataset\\ULB-VISTI-V2\\Test\\test\\config.json", "label_config_updated": true}`

**Comment by makseq** [comment]
@fsalmasri As I know VOC and probably COCO support bounding box annotations only. Use <RectangleLabels> to export COCO/VOC.

**Comment by fsalmasri** [comment]
COCO object segmentation is part of its format 
https://cocodataset.org/#home

**Comment by makseq** [comment]
@fsalmasri in this case we can extend our implementation to support polygons. Or if you could make a PR with the implementation it will be really cool.

**Comment by makseq** [comment]
COCO added for polygons in release 0.7.5.
