### ISSUE TITLE
How Can I hide "Auto accept annotation suggestions"

### ISSUE THREAD

**Issue by jvivo** [heartexlabs/label-studio#4103]
I need the auto-Annotation function. But this  "Auto accept annotation suggestions" tag always blocks the image, making it difficult for me to label the part that is blocked by it. How can I hide this tag or remove it?

**Comment by AbubakarSaad** [comment]
Hello jvivo,

Is it possible to get some screenshots for this? I couldn't find it

**Comment by jvivo** [comment]
It like this 
![image](https://user-images.githubusercontent.com/55818599/235066729-e9a31627-9669-4bb1-9880-80104da15018.png)

**Comment by jvivo** [comment]
> Hello jvivo,
> 
> Is it possible to get some screenshots for this? I couldn't find it

It like this 
![image](https://user-images.githubusercontent.com/55818599/235067260-3c24b244-6b1f-49d3-8181-749c07eb1283.png)

**Comment by jvivo** [comment]
I have solve this problem by adding "position:relative" in the main.css file. The tag has been moved to the bottom.
![image](https://user-images.githubusercontent.com/55818599/235067884-f8f8339e-6360-40b0-b935-2ebb91d552af.png)

**Comment by Yobol** [comment]
@jvivo Hi, jvivo~ Which file did you modify? <repo>/label_studio/core/static/css/main.css?
