### ISSUE TITLE
Parsing segmentation points values

### ISSUE THREAD

**Issue by fsalmasri** [heartexlabs/label-studio#411]
Hello, 

I'm trying to parse the segmentation values myself to create a custom label for my problem case.  I found that points values do not correspond to their actual values on the image. It seems like if there is a small mask size stretched to fit the original image. 

The image below is taken from the label studio showing that labels are correct on their original place. 
![image](https://user-images.githubusercontent.com/5776719/91657798-4cba7880-eac4-11ea-8a79-fa81014ec27e.png)

The image here is me parsing the value and plotting them using opencv fillPoly. 
![image](https://user-images.githubusercontent.com/5776719/91657811-6cea3780-eac4-11ea-8b9c-e07a1dd7c60c.png)

from the first sight, we see that the mask resolution and all dimensions are not correct with what we can see on labelstudio. 

Could you please tell if you are using any fixed interpolation method or any other technique to fix it on my side?

Thanks

**Comment by makseq** [comment]
@fsalmasri point coordinates are in percent format. From 0% to 100% of width and height.

**Comment by fsalmasri** [comment]
@makseq worked perfectly. I have a full code to create a binary mask I can share it if needed.

**Comment by makseq** [comment]
@fsalmasri Yes, it's a good idea to share it!
