### ISSUE TITLE
Syncing files from Azure container storage doesn't properly load task data

### ISSUE THREAD

**Issue by ginic** [heartexlabs/label-studio#4115]
**Describe the bug**
I can import URLs from an Azure storage container by inputting the Azure blob storage URL in the LabelStudio UI and they appear as HTML to be annotated. However, if I try to sync the same HTML files from blob storage container, only the URL appears in LabelStudio, the HTML does not get loaded. I would like to be able to sync the HTML, so I don't have to copy each URL individually into the UI.

**To Reproduce**
1. Configure an annotation task in LabelStudio as follows: 
```
<View>
  <HyperTextLabels name="label" toName="text">
    <Label value="BYLINE" background="blue"/>
  </HyperTextLabels>
  <Header value="Label and normalize the names of the authors."/>
  <HyperText name="text" value="$html"/>
  
  <TextArea name="nomalized_authors" toName="text" editable="true" perRegion="true" required="true" maxSubmissions="1" rows="2" placeholder="Normalized Author Name" displayMode="region-list"/>
</View>
```
2. Upload HTML files in a publicly accessible Azure storage, where they are saved with content-type text/html
3. Copy the URL for an individual file from the Azure container. For example, `https://labelstudiodocs.blob.core.windows.net/labelstudiohtml/Eklat bei Hamburger Grünen Wie ein Streit über einen NSU-Mord eskalierte - DER SPIEGEL.html`
4. In the task on the LabelStudio UI, click 'Import', paste the URL from the previous step into the Add URL field. Click "Add URL", then "Import". You should now see the HTML file as an annotatable task, looking very similar to how it would appear in a web browser.
5. In the LabelStudio annotation task settings, configure the Azure Blob storage sync using the storage account, container name and storage account access key. Make sure "Treat every bucket object as a source file" is checked. Click "Sync Storage" and wait until the tasks are synced.
6. Open one of the synced files to annotate in LabelStudio. See that the task only contains a URL and doesn't show the HTML like it would appear on a browser. 

**Expected behavior**
The HTML files imported from syncing the Azure container appear exactly as if I had copied the URLs for the files from Azure blob storage individually and pasted them into the LabelStudio UI.

**Screenshots**
Importing using Azure container URL works as expected, displaying the full HTML:
![2023-04-28_12-09](https://user-images.githubusercontent.com/2014181/235202450-ce73c293-10a6-4717-856c-d4f87b3914f9.png)
![2023-04-28_12-10](https://user-images.githubusercontent.com/2014181/235202448-475c5cf1-b919-4080-88df-d9e22d554159.png)

Syncing to the same Azure container doesn't result in annotatable HTML files.
![2023-04-28_12-05](https://user-images.githubusercontent.com/2014181/235202455-b985fa57-8b24-45fc-9c6e-8a4ca0d3649e.png)
![2023-04-28_12-07](https://user-images.githubusercontent.com/2014181/235202454-0fd37997-9ee9-4820-8ed1-49b25e69295f.png)
![2023-04-28_12-07_1](https://user-images.githubusercontent.com/2014181/235202452-3fd1d76a-3581-4399-8893-22a6cc900565.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Label Studio Version 1.7.3 (installed in a conda environment)
 - Azure container in a storage account

**Additional context**
A similar issue occurs if I try to submit all the Azure container links in bulk in a txt file or task json. The link doesn't get loaded, and only the URL appears for annotation.

**Comment by makseq** [comment]
Please use this line: 
```
<HyperText name="text" value="$html" valueType="url"/>
```

https://labelstud.io/tags/hypertext.html#Parameters

**Comment by ginic** [comment]
Thanks. I tried creating a new project with the suggested change. Unfortunately, that doesn't work for me either. 
Here's the config for the new project:
```
<View>
  <HyperTextLabels name="label" toName="text">
    <Label value="BYLINE" background="blue"/>
  </HyperTextLabels>
  <Header value="Label and normalize the names of the authors."/>
  <HyperText name="text" value="$html" valueType="url"/>
  
  <TextArea name="nomalized_authors" toName="text" editable="true" perRegion="true" required="true" maxSubmissions="1" rows="2" placeholder="Normalized Author Name" displayMode="region-list"/>
</View>
```

And the issues I see when I sync the container and try to annotate files: 
![Screenshot from 2023-05-03 10-36-38](https://user-images.githubusercontent.com/2014181/235949430-5c396eb4-f005-4cc7-8994-6da8b0999b30.png)

**Comment by ginic** [comment]
That was just a CORs issue on our side. Thanks for the help!

**Comment by rudra404** [comment]
> That was just a CORs issue on our side. Thanks for the help!

How did you solve the issue? I'm currently facing the same problem and it is also CORS related as confirmed by the error displayed on browser console.
