### ISSUE TITLE
No predictions are seen on task page

### ISSUE THREAD

**Issue by nabinkhadka** [heartexlabs/label-studio#412]
**Describe the bug**
Even though a model server is connected to an instance of label studio, no predictions are seen in the task page.

**To Reproduce**
1. Create a model server using `label-studio-ml init my_ml_backend --script ml/examples/simple_text_cssifier.py` and then `label-studio-ml start my_ml_backend`
2. Check if the model server is up  `curl http://XX.XX.XX.XX:9090/health`
`{"model_dir":"./my_ml_backend","status":"UP"}`
3. Go to model setup page and connect it. Confirm it's connected
4. Go to tasks page to not get any predictions

**Expected behavior**
Predictions should be seen

**Screenshots**
![Screen Shot 2020-08-30 at 20 38 57](https://user-images.githubusercontent.com/6050613/91662249-e1db6280-eb00-11ea-9b48-d1528b342729.png)

**Environment (please complete the following information):**
 - OS: Linux and MacOS both
 - Browser Brave
 - Version Latest all

**Comment by makseq** [comment]
@nabinkhadka And do you see predictions on labeling page?

**Comment by nabinkhadka** [comment]
@makseq Yes, I do
![Screen Shot 2020-08-31 at 23 31 19](https://user-images.githubusercontent.com/6050613/91750041-225edd00-ebe2-11ea-9e95-4f28625fe108.png)
.

**Comment by makseq** [comment]
@nabinkhadka it is just a not implemented for task page. I will do it in 0.7.5 release and inform you when done.

**Comment by nabinkhadka** [comment]
I can confirm that that was there in the previous release. @makseq

**Comment by makseq** [comment]
Can you check now release 0.7.5 here: 
https://github.com/heartexlabs/label-studio/pull/399

I've added prediction calc on api/task/<id>.
