### ISSUE TITLE
Label Studio can't load image from local storage on Windows 11

### ISSUE THREAD

**Issue by bn999286** [heartexlabs/label-studio#4121]
**Describe the bug**
Label Studio can't load image from local storage 

**To Reproduce**
1. Open Git Bash, activate conda environment
2.  Start Label Studio:   LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=D:\\data\\media label-studio start
3. Create new Project, set up local storage, Absolute path I set up is  D:\\data\\media\\dataset1. Click "Sync Storage"
4. The images stored in dataset1 directory appear in project. but can't display the image. It shows error:

There was an issue loading URL from $image value
Things to look out for:
URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)
Technical description:
URL: /data/local-files/?d=dataset1%5C3293148.jpg

**Expected behavior**
Label Studio can load image from local storage on Windows
The docs should provide clear instructions for Windows

**Screenshots**

![屏幕截图 2023-04-29 093055](https://user-images.githubusercontent.com/39345161/235277909-e9406ed5-bc34-44ca-8a3a-acbc738421ab.png)

![2023-04-29 093010](https://user-images.githubusercontent.com/39345161/235277923-b04d4bc6-75f3-4407-9377-ce30ddea08d8.png)

![04-29 093224](https://user-images.githubusercontent.com/39345161/235277939-80b694f4-b155-4357-90f8-b997c51ec942.png)

![04-29 093245](https://user-images.githubusercontent.com/39345161/235277949-3ea667bf-52a2-4176-92f3-7c9868772eff.png)

**Environment (please complete the following information):**
 - Windows 11 Pro
 - Label Studio Version = 1.7.2

**Additional context**

**Comment by AbubakarSaad** [comment]
Hello bn999286, 

Are you able to just open the images if you click on the link?

**Comment by laugh12321** [comment]
I also have the same problem.

**Comment by arditobryan** [comment]
me too

**Comment by Rxelux** [comment]
This [part](https://github.com/heartexlabs/label-studio/blob/7daeee9da92cdfc5c063e825099c143c62d5fcd8/label_studio/core/views.py#L187-L193) seems to cause the issue!

**Comment by arushirai1** [comment]
Is there supposed to be a % in your path ( /data/local-files/?d=dataset1%5C3293148.jpg), and does the link open the image? I've debugging and I realized that my paths were off. Let me know if that works!! I managed to get it to work on my machine.

**Comment by 1andDone** [comment]
Same exact issue using Label Studio == 1.8.0. Any one find a work around?

**Comment by arushirai1** [comment]
I can try helping since I figured it out for myself.

Just like me, I think the OP has an issue in their relative path. The
percent in the path doesn't look right to me.

What is the absolute path on your machine of the data you want to serve and
what is the parent path and absolute path supplied to your source storage
(the image shown in OP). Lastly, what is the error shown (so I can see the
relative path that's loaded).

**Comment by 1andDone** [comment]
To answer your questions, I'm noticing a "%5C" in my path in place of single or double escape sequences (i.e. `\\`). For instance, I think OP is trying to display an image that is located at the following path: `D:\\data\\media\\dataset1\\3293148.jpg` and the URL that is generated is `/data/local-files/?d=dataset1%5C3293148.jpg`. From my experience, if you click on the URL, it does not display the image. 

What paths were you using where you got it to work?

**Comment by laugh12321** [comment]
The problem has been resolved. Just follow the instructions in the figure below to set the environment variables and place all the local datasets that need to be loaded via **Cloud Storage** under the path specified in "LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT".

![Snipaste_2023-08-02_16-19-27](https://github.com/HumanSignal/label-studio/assets/38065710/1e34d688-fd40-45a0-8ca5-dfe97ce5b370)

![Snipaste_2023-08-02_16-20-30](https://github.com/HumanSignal/label-studio/assets/38065710/097c6c64-1bab-44e7-80f5-0d7f439d0dac)

**Comment by 1andDone** [comment]
That worked! The key was going into my Windows settings and adding `LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT` and `LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED` as System variables. I guess setting them from the command line didn't work the same way. It turns out my local/absolute paths were correct, though.

**Comment by muskan-khanam** [comment]
hey! I have enabled the  LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT and LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED as System variables. Even though it is showing the Validation error.

have a look to the below image.
![Capture](https://github.com/HumanSignal/label-studio/assets/119946161/d7cc5af9-733b-402c-942d-848e3e30dda2)

**Comment by makseq** [comment]
You have to set this variables in the same terminal where you run LS. Or if you use docker, you have to pass this variables to the docker run command, something like this: 

```
docker run -d \
  -e LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/path/to/your/local/files \
  -e LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true \
  -v /path/to/your/local/files:/path/to/your/local/files \
  ...
```

I am closing this issue as a non-active, and it seems like it has been resolved.
