### ISSUE TITLE
Annotation coordinates outside image

### ISSUE THREAD

**Issue by Raven888888** [heartexlabs/label-studio#4128]
**Describe the bug**

I have a standard bounding box annotation for image object detection. Recently I revisit a project that I have annotated some time ago, and found out that the annotations not showing in the UI, and turns out the coordinates are too large outside the boundary of the image.

![image](https://user-images.githubusercontent.com/58241952/235607103-dd7b420b-2daf-47d0-95fb-f0e2d268ff54.png)

There is no way I am able to draw annotations so big outside the image, even when zooming out. How did this happen? Is this a bug?

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version 1.6.0 docker

**Comment by makseq** [comment]
Yes, it's known issue and it was fixed several months ago. It's recommended to update your LS instance. 
To fix this issue, you need to activate your LS python environment and run this script:

```
import os
import time
import django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "htx.settings.label_studio")
django.setup()

import logging

from tasks.models import Annotation, Task
from projects.models import Project

logger = logging.getLogger(__name__)


def check_range(v, mini, maxi):
  score =  mini < v['x'] <= maxi
  score += mini < v['y'] <= maxi
  score += mini < v['width'] <= maxi
  score += mini < v['height'] <= maxi

  if score >= 2:
    return mini


def detect_range(v):
  mini, maxi = 100, 10000
  while maxi <= 1e+100:
    if check_range(v, mini, maxi):
      return mini
    mini *= 100
    maxi *= 100


def fix_project(id):
  p = Project.objects.get(id=id)
  for t in p.tasks.all():
    fix_task(t.id)

def fix_task(id):
  t = Task.objects.get(id=id)
  annos = t.annotations.all()
  for a in annos:
    fixed = fix_annotation(a)
    if fixed:
      print('\n==> Task', id, 'Annotation', a.id, 'fixed!')

def fix_annotation(a):
  # print('  ==> Annotation', a.id)
  result = a.result
  fixed = False

  for i, r in enumerate(result):
    if 'value' not in r:
      continue
    v = r['value']
    if 'x' not in v:
      continue

    c = detect_range(v)
    if c is None:
      # print(f'Range is not detected: {v}')
      continue

    # print(f"     => i={i} {v['x']} {v['y']} --- {v['width']} {v['height']}  =>  ",)
    c_x, c_y = c, c
    v['x'] /= c_x
    v['y'] /= c_y
    v['width'] /= c_x
    v['height'] /= c_y
    # print(f"    => i={i} {v['x']} {v['y']} --- {v['width']} {v['height']}")
    fixed = True

  if fixed:
    # pass
    # a.pk = None
    # a.save()
    Annotation.objects.filter(id=a.id).update(result=result)

  return fixed

if __name__ == '__main__':
  project_id = 123  #  <==== Specify the project_id
  fix_project(project_id)
```

Don't forget to make a DB dump before running it.

Note: it's written for bounding boxes, but seems in your case there are points, and you should a little bit modify this script to cover KeyPointLabels case.

**Comment by Raven888888** [comment]
Thanks @makseq 

If this is a resolved issue, can you give me the issue link? And which LS version has resolved this (or the changelog link)?
I did try to find in Issues before posting this, but to no avail.
