### ISSUE TITLE
Adjusting label coding/order when exporting project

### ISSUE THREAD

**Issue by MarkoMFilip** [heartexlabs/label-studio#4129]
Exporting a project in COCO format (haven't tested for others) assigns label IDs to labels in alphabetical order, instead of the order defined in the project settings. 

E.g., for a document layout task my labels are - in the order that I wish them to be - `Text`, `Title`, `List`, `Table`, `Figure`. When I export the project in COCO format, I get

```json
"categories": [
    {
      "id": 0,
      "name": "Figure"
    },
    {
      "id": 1,
      "name": "List"
    },
    {
      "id": 2,
      "name": "Table"
    },
    {
      "id": 3,
      "name": "Text"
    },
    {
      "id": 4,
      "name": "Title"
    }
  ],
```

I would like however for the order to stay the same:
```json
"categories": [
    {
      "id": 0,
      "name": "Text"
    },
    {
      "id": 1,
      "name": "Title"
    },
    {
      "id": 2,
      "name": "List"
    },
    {
      "id": 3,
      "name": "Table"
    },
    {
      "id": 4,
      "name": "Figure"
    }
  ],
```

Is this possible to do within LabelStudio, or do I need to modify the resulting JSON manually?

**Comment by MarkoMFilip** [comment]
Found the answer in the documentation, at the very bottom of the export page: https://labelstud.io/guide/export.html#Question-3-How-to-modify-order-of-categories-for-COCO-and-YOLO-exports

**Comment by davidlinner** [comment]
Tried to export my annotations in YOLO format after changing the settings according to above hint. ~~The change had no effect~~ and the category property is not documented: https://labelstud.io/tags/label
Has there been a change I missed?

**EDIT:** Correction. Only the exported `classes.txt` file lists the labels in any order and not according to the category property. The class index in the actual YOLO label files is correct.

**Comment by makseq** [comment]
> EDIT: Correction. Only the exported classes.txt file lists the labels in any order and not according to the category property. The class index in the actual YOLO label files is correct. 

Is it enough to solve your problem?

**Comment by makseq** [comment]
Docs fix: https://github.com/HumanSignal/label-studio/pull/5710/

**Comment by davidlinner** [comment]
@makseq Thank you for extending the docs. I guess the order of classes in `classes.txt` is of less interest as long as the `notes.json` contains the correct class IDs. Great tool btw.

**Comment by HouseWay** [comment]
> Found the answer in the documentation, at the very bottom of the export page: https://labelstud.io/guide/export.html#Question-3-How-to-modify-order-of-categories-for-COCO-and-YOLO-exports

Thank you so much.I am confused by the order of labels  now.
