### ISSUE TITLE
Bounding Boxes (aka Rectangle Labels) have invalid coordinates laying outside of the image boundaries

### ISSUE THREAD

**Issue by Johnson145** [heartexlabs/label-studio#416]
**Describe the bug**
When exporting bounding boxes within completions, we expect their relative coordinates to lay in the range of [0, 100]. However, sometimes there are negative values as well as values greater than 100.

The associated bounding boxes shown in the UI do not leave the image boundary though. (Eventhough they may get very close.)

**To Reproduce**
Draw a bounding box on top of an image and try to stretch it to (some of) the image boundaries.

Not sure whether it's reproducable like this each and every time though.

**Expected behavior**
Two options:
- either explicitly allow and visualize bounding boxes outside of the image boundary
- or disallow them and ensure that the exported values are within the range of [0, 100] (at least my preferred option)

**Environment:**
 - Version 0.7.4

**Comment by hlomzik** [comment]
Hmm, that sounds bad and strange a bit. In previous release I made fixes exact for image boundaries. I'll check, fix and try to write some test to cover this. Thank you!

**Comment by makseq** [comment]
@hlomzik any news?

**Comment by makseq** [comment]
@Johnson145 could you test release 0.7.5? I hope it fixed there.

**Comment by Johnson145** [comment]
Sounds good, I'll test it within the next days.

**Comment by makseq** [comment]
I hope it's fixed now in 0.8.0.

**Comment by Johnson145** [comment]
It took some time, but I've just finalized the tests on v0.7.5:

Unfortunately, the issue does still seem to exist. However, I think the outliers have drastically been reduced. Whenever the value limit is exceeded, it's now about the same value: `100.00000000000002`. I think it used to have much higher differences and variance, too.

Thus, it's almost fixed, but not completely.

Have you made any further related changes in 0.8.0 or did you hope for this to be fixed as of the 0.7.5 changes?

**Comment by Johnson145** [comment]
Update: The changes seem to have introduced a new bug: Some of the returned bounding box data does now include minimum coordinates which are greater than the declared maximum values (affects x coordinates as well as y coordinates).

**Comment by hlomzik** [comment]
`100.(0)2` looks like common annoying float problem, I'll fix this by reducing precision.
But I need some more details about min-max bug. What the returned bounding boxes? If those in the final results, they don't have any min and max values? Or internally in functions which control the outliers?

**Comment by Johnson145** [comment]
I'm parsing the result of a task contained in the completion files. I'm using the given `x`, `y`, `height` and `width` values to calculate `x_min=x`, `y_min=y`, `x_ max=x_min+width` and `y_max=y_min+height`. My script throwed an error, because afterwards e.g. `y_min` may be greater than `y_max`. Obviously, that shouldn't happen.

I just looked into it a little bit closer and found out that the actual cause is **the `height` attribute containing a negative value** (in my case e.g. `-52.62..`. I guess the same applies to the `width` attribute.
