### ISSUE TITLE
Import project in Label Studio

### ISSUE THREAD

**Issue by Chaouabti** [heartexlabs/label-studio#4169]
I would like to know if it is possible to re-upload a project in Label Studio? I imported a project onto my computer which was then deleted from my Label Studio projects. Is it possible to re-upload it with the downloaded data?

**Comment by AbubakarSaad** [comment]
Hello Chaouabti,

Yes, you can import the exported project.  Follow these steps:

1. Make sure you have the exported JSON file containing tasks and annotations from the deleted project. If you don't have it, you'll need to obtain it from a backup or another source.

2. Set up Label Studio on your computer, if not already installed.

3. Create a new project in your Label Studio instance:
 3.1. Use the labeling configuration from the deleted project. If you don't have it, you'll need to recreate it manually.

4. Import the previously exported JSON file into the new project: 
4.1. Go to Project => Data manager page, click the Import button, and select the JSON file.

5. If the deleted project had images, audio, video, or other resources uploaded via the GUI, follow these steps:
 5.1. Make sure you have the resources on your computer. 
 5.2. If necessary, update the paths in the imported JSON file to match the paths on your computer.

By following these steps, you can re-upload a deleted Label Studio project using the downloaded data.
