### ISSUE TITLE
Only remembering filters and orderings per account.

### ISSUE THREAD

**Issue by cozeybozey** [heartexlabs/label-studio#4178]
**Is your feature request related to a problem? Please describe.**
When a certain user applies a filter to a project, then everybody who uses that project afterwards automatically has the same filter applied. The same holds for ordering. This can get confusing if multiple people are working on annotating in the same projects, because they constantly have to pay attentions that their filters and orderings are actually in place and not someone else's.

**Describe the solution you'd like**
It would be nice if filters and orderings would be saved per account and not across the entirety of the project.

**Describe alternatives you've considered**
Right now we just tell every annotator to always check the filters and orderings before annotating, but it feels to me as if that should not be necessary.

**Comment by AbubakarSaad** [comment]
Hello Cozey,

As workaround could you try using the tabs? would that solve your case for filters?

**Comment by cozeybozey** [comment]
Hi Abukabar,

Thanks for your response, but I am not sure what you mean with tabs. Are there like tabs you can make within label studio or something?

**Comment by AbubakarSaad** [comment]
Yes, something like this:
<img width="1512" alt="Screenshot 2023-05-18 at 11 41 55 PM" src="https://github.com/heartexlabs/label-studio/assets/4449857/df8857dc-d614-49a6-9fa7-7ec2eb33212d">

**Comment by cozeybozey** [comment]
Okay yes thanks we are using that now. Maybe having filters and orderings saved per account is still interesting, but for now this will work as well.
