### ISSUE TITLE
Filter completed annotations on the task page based on choices/text boxes etc.

### ISSUE THREAD

**Issue by Rishabh-hyperverge** [heartexlabs/label-studio#418]
**Is your feature request related to a problem? Please describe.**
While going through large annotation QC, the ability to do targeted checks is very essential. I want to go through only positive samples right there in the portal.

**Describe the solution you'd like**
A simple filter or search based on choices/ text fields in the completed tasks page.

**Describe alternatives you've considered**
Exporting the completions and parsing the JSON to get the images file list and then manually checking them.

**Comment by makseq** [comment]
@Rishabh-hyperverge do you want a simple sub-string search over completion JSONs?

**Comment by Rishabh-hyperverge** [comment]
@makseq Yes, Initially that should do the job. 
But Ideally, I think queries like search filters based on choices, labels, entities would be better.

**Comment by Rishabh-hyperverge** [comment]
Hi @makseq, is it possible to include this in the upcoming release, also its been a while since there was a new release? Hoping for some really big stuff this time :)

**Comment by makseq** [comment]
@Rishabh-hyperverge I'll try to do it, but I can't promise..

**Comment by makseq** [comment]
@Rishabh-hyperverge Hello! Sorry for a late solution, but we have released a new LS version with the  filtering of completion results. If it's still actual for you, you may try it: 

```
pip install label-studio==0.9.0rc1
```

**Comment by Rishabh-hyperverge** [comment]
It works 🕺🙏🏻
