### ISSUE TITLE
label-studio: command not found during installation in Ubuntu session of EC2

### ISSUE THREAD

**Issue by katreparitosh** [heartexlabs/label-studio#419]
Hello,

I was installing Label Studio on my AWS EC2 instance. In the Ubuntu session, I could successfully install label-studio using the 'pip install label-studio' command. 

However, when I was performing the "init" and "start" commands. I am getting an error that says 'label-studio: command not found'.

Python version - 3.6 and Ubuntu 18.4

What could be the possible reason? Also, is this the correct method to deploy on EC2 instance.

**Comment by makseq** [comment]
Try this one: 
```
python3 -m pip install label-studio
python3 -m label-studio init my_project
python3 -m label-studio start my_project
```

**Comment by makseq** [comment]
Do you use virtualenv?

**Comment by katreparitosh** [comment]
@makseq Thanks for the suggestions.

However, a simple re-SSH into the instance did the work. But anyway, thanks. Closing now.
