### ISSUE TITLE
Missing `Vary: Accept` http response header

### ISSUE THREAD

**Issue by graingert** [heartexlabs/label-studio#420]
**Describe the bug**
When browsing to an item and pressing back, sometimes the browser will respond with the cached json response

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by makseq** [comment]
Do you think that adding "Vary: Accept" to the response resolves this issue?

**Comment by graingert** [comment]
hmm, I can't repeat this behaviour anymore

**Comment by makseq** [comment]
Let's wait for several days and close this issues if everything is ok.
