### ISSUE TITLE
Renaming or moving the project folder permanently breaks the project

### ISSUE THREAD

**Issue by Johnson145** [heartexlabs/label-studio#421]
**Describe the bug**
Renaming or moving the project folder (,which is based on absolute paths,) permanently breaks the project. More precisely, all completions get lost (according to the UI). If one goes ahead and creates new ones, the project gets completely broken and can't get opened at all anylonger.

Looks like this is due to the absolute paths being included in the project files. This affects especially the `source.json` file. After opening the renamed project, all information in that file gets duplicated based on the new path and all associated information gets lost. There are absolute paths in the `config.json` file, too, but that didn't cause any noticeable trouble for me yet.

Do such absolute paths really need to be saved in there? It looks like the paths could actually be represented relatively to the project folder and thus renaming/moving shouldn't be an issue.

**To Reproduce**
1. Initialize a new Label Studio project by using an absolute path: `label-studio init /path/to/labeling_project`
2. Start the project: `label-studio start /path/to/labeling_project`
3. Create some completions.
4. Stop Label Studio.
5. Rename or move the project folder. For instance, just rename `/path/to/labeling_project` to `/path/to/labeling_project_renamed`
6. Start the project again: `label-studio start /path/to/labeling_project_renamed`

**Expected behavior**
The project should still work the same way as before.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version 0.7.4

**Comment by makseq** [comment]
It's fixed after 0.8.2 LS release.
