### ISSUE TITLE
Redis Storage sync tasks not found

### ISSUE THREAD

**Issue by CuriousDolphin** [heartexlabs/label-studio#4219]
Im unable to get annotation task from redis storage.

at first i save a test jpg images in bytes into redis with SET comand on raw image bytes.
images are correctly saved on redis.

flow:
- save images on redis
- setup a new project on LS and setup import storage
- label studio see correctly redis instance and check connection is ok
<img width="778" alt="image" src="https://github.com/heartexlabs/label-studio/assets/36967518/dce39240-2bbc-435c-9d71-e0b9b4b98a88">
- label studio (on sync storage ) does not see previously uploaded images 
<img width="514" alt="image" src="https://github.com/heartexlabs/label-studio/assets/36967518/8d329886-dbf7-488a-a43f-7d0a6cbbbd63">

**Expected behavior**
Label studio would found images saved on redis storage

**Environment (please complete the following information):**
 - OS: Docker-compose + Dockerfile
 - Label Studio Version 1.7.3

**Additional context**
i tried with no or different regex filter and redis base path

**Comment by makseq** [comment]
Could you check LS from the latest develop branch? There should be more debug info for storage.

**Comment by jiangtangaaaa** [comment]
> Could you check LS from the latest develop branch? There should be more debug info for storage.你能从最新的开发分支检查LS吗？应该有更多存储的调试信息。

I left a message below several of your replies.
Hello, excuse me, I have a difficult problem now. I want to import images from local redis and images from Alibaba Cloud redis. Can you tell me how to do it, or remind me of some relevant documents. Thank you very much.

**Comment by jiangtangaaaa** [comment]
> Im unable to get annotation task from redis storage.我无法从 redis 存储中获取注释任务。
> 
> at first i save a test jpg images in bytes into redis with SET comand on raw image bytes.首先，我使用 SET 命令将测试的 jpg 图像（以字节为单位）保存到 redis 中，并在原始图像字节上保存。 images are correctly saved on redis.图像正确保存在 Redis 上。
> 
> flow: 流：
> 
> * save images on redis在 Redis 上保存图像
> * setup a new project on LS and setup import storage在 LS 上设置一个新项目并设置导入存储
> * label studio see correctly redis instance and check connection is okLabel Studio 正确查看 Redis 实例并检查连接是否正常
> 
> <img alt="image" width="778" src="https://private-user-images.githubusercontent.com/36967518/239895124-dce39240-2bbc-435c-9d71-e0b9b4b98a88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTQ2NzksIm5iZiI6MTcwMTM5NDM3OSwicGF0aCI6Ii8zNjk2NzUxOC8yMzk4OTUxMjQtZGNlMzkyNDAtMmJiYy00MzVjLTlkNzEtZTBiOWI0Yjk4YTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAxMzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYTUyMDhiYWFhZWZlMTI1NDBmYTJkYzkyNWQ2NWVmODBiZDZkZTgxN2JjOWM1MWZlN2NlZGJkOTE3MDFmNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o3syoS2kG20IGmrvXtHbkw0a-tTjy-9GRTU_9zXtfQI"> - label studio (on sync storage ) does not see previously uploaded images
> - Label Studio（在同步存储上）看不到之前上传的图像<img alt="image" width="514" src="https://private-user-images.githubusercontent.com/36967518/239895841-8d329886-dbf7-488a-a43f-7d0a6cbbbd63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTQ2NzksIm5iZiI6MTcwMTM5NDM3OSwicGF0aCI6Ii8zNjk2NzUxOC8yMzk4OTU4NDEtOGQzMjk4ODYtZGJmNy00ODhhLWE0M2YtN2QwYTZjYmJiZDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAxMzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYWY2YTg2OGU4MmE1ZGQ1ZDZiOTUyYThhYTE3ODlkZWVjYWUzNmRlNjVkMWMyYzc3ZmFhZjk0YzZiNzk0ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eUEngWAsn8C0IaS4VsJcPbVcxUM1boas6WsERkTMiWE">
> **Expected behavior 预期行为** Label studio would found images saved on redis storageLabel Studio 会发现保存在 redis 存储上的图像
> 
> **Environment (please complete the following information):环境（请填写以下信息）：**
> 
> * OS: Docker-compose + Dockerfile操作系统： Docker-compose + Dockerfile
> * Label Studio Version 1.7.3Label Studio 版本 1.7.3
> 
> **Additional context 其他背景** i tried with no or different regex filter and redis base path我尝试没有或使用不同的正则表达式过滤器和 Redis 基本路径

How do you do it? I entered the same information as you and it shows 
![image](https://github.com/HumanSignal/label-studio/assets/101043186/4b43e31f-1f9b-401a-a3a5-dbd41142bbde)

**Comment by makseq** [comment]
Looks like this problem was related to missing `db` (Database number) field in Label Studio Redis storage cards. 
I've added it here:
https://github.com/HumanSignal/label-studio/pull/6255/files

The fix is merged to main branch.

**Comment by makseq** [comment]
A little demo on how to use it:
https://www.youtube.com/watch?v=wW1iuDSFYJw
