### ISSUE TITLE
Undocumented schema for ML predictions

### ISSUE THREAD

**Issue by andreaferretti** [heartexlabs/label-studio#422]
Hello, first of all, thank you for your great project! Seems very useful!

I am trying to to connect some custom ML backends. In order to do that, I would need to understand what format the various tasks expect as a response. The ML examples all use the same schema which, if I understand correctly, is for a classification task. I am trying to connect a NER task and I cannot figure out what is the schema of the expected response.

Is this documented anywere (possibly for other tasks too)?

**Comment by tlaud** [comment]
What I did to figure out the required format for the responses was to study a JSON file in the completions folder. Once any example is labeled manually, a file should appear in the completions folder and contain the schema. Then, you would only have to identify where your values from the backend have to be inserted.

**Comment by andreaferretti** [comment]
Thank you, that works! Still, I will leave this open, since it would be better to have it documented explicitly

**Comment by makseq** [comment]
I'll add it into docs. Also in 0.7.5 it will be more comfortable way to explore the task body.

**Comment by p-sodmann** [comment]
It would be nice to get an example JSON similar to task creation.
Also, please document, that fields can be left empty.

We have different tasks for annotation of the same image, it took me a while to figure out, that I could leave some results empty.

**Comment by smoreface** [comment]
https://labelstud.io/guide/predictions.html now contains more details and example JSON
