### ISSUE TITLE
Hotkey for toggling visibilty of bounding boxes

### ISSUE THREAD

**Issue by tlaud** [heartexlabs/label-studio#423]
**Is your feature request related to a problem? Please describe.**
One of the great features of Label Studio is the possibility of keyboard-only labeling by relying on hotkeys. Another great feature is the machine learning backend for label suggestions. In a use case, in which not only a bounding box is labeled but also classes are annotated, it would be nice to toggle the bounding box - which might occlude image parts relevant to the classes labeling - on/off with a hotkey

**Describe the solution you'd like**
A hotkey which toggles the visibility of all bounding boxes for an image.

**Describe alternatives you've considered**
1. Moving the hands from the keyboard to the mouse, clicking on the icon to toggle the visibility, moving the hands back to the keyboard.

Thanks :)

**Comment by hlomzik** [comment]
Hi! That's good and simple idea, thank you! First of all we have to add button to hide all regions and then hotkey can be assigned to it)
We'll do this soon, I'll update you here.

**Comment by makseq** [comment]
Please, try alt + h.
