### ISSUE TITLE
Hotkey to remove / add points in roi poly

### ISSUE THREAD

**Issue by p-sodmann** [heartexlabs/label-studio#424]
**Is your feature request related to a problem? Please describe.**
Especially when modifying existing roi polygons, e.g. prelabeling it is not possible (?) to  add or remove points.

**Describe the solution you'd like**
add ctrl click on polygon points to remove points and alt click to add new points when clicking on a line.
also please add different cursors: https://github.com/heartexlabs/label-studio/issues/409

**Comment by hlomzik** [comment]
Hi! You can always add a point on any edge of polygon — there is green ghost point appears under the cursor when you mouse over the edge. Do you have it?
But currently you can not remove point from polygon, this is important lack of functionality, we'll fix it soon. Our plan to delete point by double click on it — pretty common behaviour. Does it fit?

**Comment by p-sodmann** [comment]
That would work as well.

**Comment by hlomzik** [comment]
fixed by heartexlabs/label-studio-frontend#166 some time ago
now you can delete polygon point with double click
