### ISSUE TITLE
multi-instance connection to the same PostgreSQL database

### ISSUE THREAD

**Issue by DiTo97** [heartexlabs/label-studio#4263]
**Environment**
 - OS: Ubuntu 18.04
 - Label Studio version: 1.7.3

**Additional context**
At my research group we have a privacy-constrained labelling task that prevents us from using any cloud-hosted labelling services. Thefore, we decided to try Label Studio out, connecting to our local workstation. The problem is that we cannot host a common Label Studio instance that everyone has access to for security reasons of the workstation. Instead, anyone has its own space on the workstation from which it launches its own Label Studio instance to work with. Now, we would like to create a single project shared among us, that anyone could see and reference. The initial solution was to create only one Label Studio instance from one of the guys' space and share the organization link to all the others, which sort of worked fine but generated some inconsistencies on who and when could connect to the Label Studio instance and would require the hosting guy to always have its space on. I'm looking for a more flexible solution, and I'm wondering if it's possibile to let everyone have their own Label Studio instance pointing to the same PostgreSQL dabatase hosted in a common directory fixing the `--data-dir` and `--database` args.

Is that even possible or would it generate synchronization issues or race conditions in the Label Studio instance? If that's the case, could you suggest any other workarounds that would allow this multi-instance access (a long-running Label Studio instance exposed on the Internet with Ngrok, as you suggest in the docs, does not satisfy our privacy constraints)?

**Comment by AbubakarSaad** [comment]
Hello DiTo97, 

You could try this setting up multiple Label Studio instances pointing to the same PostgreSQL database. This setup should not generate synchronization issues or race conditions, as PostgreSQL is designed to handle concurrent connections and transactions (but I would make sure it doesn't by double checking it)

To achieve this, you can follow these steps:

1. Set up a PostgreSQL database in a common directory accessible by all users.
2. For each user, install and configure Label Studio on their local workstation.
3. When starting Label Studio for each user, provide the same PostgreSQL connection details using the `--database` argument, like this:

```
label-studio start --database "postgresql://username:password@hostname:port/dbname"
```

This way, all users will have their own Label Studio instance connected to the same shared PostgreSQL database, allowing them to work on the same project concurrently.

However, please note that this setup might have some performance implications if multiple users are working simultaneously, as the database will need to handle multiple connections and transactions. To mitigate this, you can consider using a more powerful PostgreSQL server or optimizing the database configuration for better performance.

Additionally, make sure that the Label Studio instances have the same labeling configuration and access to the same data storage (e.g., local storage or cloud storage) to ensure consistency across all instances.

**Comment by DiTo97** [comment]
Thank you @AbubakarSaad,

The solution you suggested is exactly what I ended up implementing. I can confirm that the shared PostgreSQL instance is able to mitigate race conditions nicely, and that the overall setup has been working absolutely fine.

I'm closing the issue.

**Comment by NaveDanan** [comment]
Hey is there more detailed guide on how I can also multi-instance connection to the same PostgreSQL database.
our lab also uses local shared file system and want to work together in labeling. But I'm new to Postgres and don't really understand how I can set it up
