### ISSUE TITLE
Display of label on top of bounding box region.

### ISSUE THREAD

**Issue by taritro98** [heartexlabs/label-studio#428]
When we show pre-annotated regions using completions, we are trying to display the respective class/label name on each bounding box region of the image. We have tried multiple ways but nothing seems to work. Does label studio have any feature for this purpose, if not, is there any other way we can show them ?

**Comment by makseq** [comment]
@taritro98 we have implemented it in our development branch of label studio front end. If you want I can send you this build.

**Comment by taritro98** [comment]
Yes please. That would be very helpful. Thank you.

**Comment by makseq** [comment]
@taritro98 Sorry, I was wrong, it's already in the build. 

Go to settings: 
![image](https://user-images.githubusercontent.com/501780/94137249-cdc02200-fe6e-11ea-9836-5e6727f95603.png)

and enable "Show labels inside the regions"
![image](https://user-images.githubusercontent.com/501780/94137232-c567e700-fe6e-11ea-9c45-7d097bd05a6e.png)

**Comment by makseq** [comment]
Feel free to ask more question here.

**Comment by taritro98** [comment]
Hi, I've one more doubt. I've enabled the settings in my application, however the settings are getting refreshed everytime I login. Is there a way that we show these label names by setting an attribute or something?

**Comment by makseq** [comment]
@taritro98 I hope we can store it in cookies. I've asked frontend developer to solve it. Hope it will be soon

**Comment by makseq** [comment]
@taritro98 what login do you mean?

**Comment by hlomzik** [comment]
Hi, @taritro98!
We store these settings in browser's localStorage, very convenient and easy thing, it can't be broken by itself.
It stores data locally in the browser, per protocol-domain-port, so please check, that you have them the same each launch. And that you don't use some incognito mode or other things for very strong privacy.
