### ISSUE TITLE
Missing headers on some calls to S3 (No origin so CORS fails intermittently)

### ISSUE THREAD

**Issue by asaworld** [heartexlabs/label-studio#4284]
Version 1.7.3 is making some requests for audio files from S3 with missing headers. This is intermittent but frequent enough that it happens 1 in 10 times or more of loading the labelling panel. The missing request headers are causing a CORs failure and the big red box of failure. I have rolled back to 1.7.1 and it does not seem to be a problem. Unfortunately there is a different bug with 1.7.1 meaning that I cannot S3 expiry so hopefully you can prioritise a fix for this issue asap.

**Comment by AbubakarSaad** [comment]
Hello asaworld,

Yes, its known issue. The fixes is coming in 1.8.0, which will be releasing soon

**Comment by asaworld** [comment]
Perfect, thank you. I will look forward to it.

**Comment by AbubakarSaad** [comment]
1.8.0 has been released. Please try it on there and reopen the issue if it causes problems :)

**Comment by DoctorSlimm** [comment]
Same issues here using HF Spaces, CORS erorrs are very intermittent and in batches despite the bucket being totally public and having all headers on responses? @AbubakarSaad @asaworld

**Comment by DoctorSlimm** [comment]
bbump
