### ISSUE TITLE
Is that possible to delete the labels created inside?

### ISSUE THREAD

**Issue by zhimin-z** [heartexlabs/label-studio#4287]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I attempt to delete the labels created inside. The figure shows the example:
![image](https://github.com/heartexlabs/label-studio/assets/8592144/8b089ca3-b307-404a-8a40-e0bc25e92fa4)
If you have created a label inside the template ad hoc, then there is no way I can remove this label (there is no regret) since the inside labels do not appear in my template. What can I do now?

**Describe the solution you'd like**
Is that a way to remove the inside labels after creation?

**Describe alternatives you've considered**

**Additional context**

**Comment by AbubakarSaad** [comment]
Hello zhimin-z,

You can use API (https://labelstud.io/api#operation/api_labels_delete) to delete those labels.
