### ISSUE TITLE
Unexpected sequential sampling behaviour

### ISSUE THREAD

**Issue by huntzhan** [heartexlabs/label-studio#431]
**Describe the bug**

Tasks are NOT sampled according to the order of `id` (*Tasks are ordered ascending by their "id" fields. This is default mode.*)

**To Reproduce**

1. Import tasks JSON file.
2. Confirm the `sampling` mode is set to `sequential`.
3. Start labeling, and tasks are sampled randomly.

**Expected behavior**

*Tasks are ordered ascending by their "id" fields. This is default mode.*

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

Turns out the `ids` are not sorted:

https://github.com/heartexlabs/label-studio/blob/b23bba43855cdd519eba671b28f914be9b12d3e7/label_studio/project.py#L410-L414

https://github.com/heartexlabs/label-studio/blob/b23bba43855cdd519eba671b28f914be9b12d3e7/label_studio/storage/filesystem.py#L24-L25

https://github.com/heartexlabs/label-studio/blob/b23bba43855cdd519eba671b28f914be9b12d3e7/label_studio/storage/filesystem.py#L53-L54

**Comment by makseq** [comment]
What LS version do you use?

**Comment by huntzhan** [comment]
> What LS version do you use?

I use the docker image `heartexlabs/label-studio:latest` and import the `tasks.json` formatted like

```
[
  {
    "id": 0,
    "data": ...
  },
  {
    "id": 1,
    "data": ...
  },
  ...
]
```

**Comment by makseq** [comment]
@huntzhan Please, check 0.7.5rc1, it is fixed there.

**Comment by huntzhan** [comment]
thank you!

**Comment by makseq** [comment]
@huntzhan have it helped you? Can I close this issue?

**Comment by huntzhan** [comment]
@makseq I'll try to test the change later and thank you again for your active response!
