### ISSUE TITLE
import data and export data;user management

### ISSUE THREAD

**Issue by yangaiping** [heartexlabs/label-studio#4328]
Hello,
I have recently been using your tool, label-studio, and have encountered some difficulties and issues. I have summarized the problems below and hope to receive your response. Thank you very much!

1. I would like to upload pre-labeled JSON files along with their corresponding images to label-studio and display the pre-labeled results in the UI interface. However, label-studio modifies the names of the uploaded images, causing errors in the image paths in the JSON file and resulting in the pre-labeled results not being displayed.

2. I would like to export images and annotation files together, but I found that I have to click "submit" for each image before I can export them. This is very inefficient when I have a large dataset to annotate.

3. When my team members and I log into label-studio on the same LAN with our respective accounts, we can see and modify each other's annotation tasks. How can we solve this problem?

**Comment by feifeizuo** [comment]
As far as I known, for 3, these is not a free feature, you can use it in enterprise.

**Comment by yangaiping** [comment]
Do you know how to get the enterprise version? Does it have to be an organization?

**Comment by yangaiping** [comment]
> 据我所知，对于3，这些不是免费功能，您可以在企业中使用它。

Do you know how to get the enterprise version? Does it have to be an organization?

**Comment by farioas** [comment]
No, you don't have to be an organization to use the Enterprise, just follow the link: https://app.heartex.com/user/trial

**Comment by yangaiping** [comment]
> 



> No, you don't have to be an organization to use the Enterprise, just follow the link: https://app.heartex.com/user/trial

"Have you previously registered and logged in to the enterprise version? Why does the registration page ask me to provide an organizational email and the login page tells me that the email address and password I entered do not match, but I am sure that my password is correct?"

**Comment by yangaiping** [comment]
> No, you don't have to be an organization to use the Enterprise, just follow the link: https://app.heartex.com/user/trial

Have you previously registered and logged in to the enterprise version? Why does the registration page ask me to provide an organizational email and the login page tells me that the email address and password I entered do not match, but I am sure that my password is correct?

**Comment by farioas** [comment]
Just created an account with no issues. 

> ask me to provide an organizational email 

No it's not. It asks about your email, that you have to confirm later. The Org name - this name will be used with-in account as display name, you can use any name.

> my password is correct

Maybe you used some non utf symbols

**Comment by yangaiping** [comment]
> 刚刚创建了一个没有问题的帐户。
> 
> > 要求我提供组织电子邮件
> 
> 不，不是。它询问您的电子邮件，您必须稍后确认。组织名称 - 此名称将在帐户内用作显示名称，您可以使用任何名称。
> 
> > 我的密码正确
> 
> 也许您使用了一些非utf符号


I still cannot solve this problem.
![image](https://github.com/heartexlabs/label-studio/assets/109123962/e84b4e16-b313-4e89-a33b-276487d9376c)

**Comment by farioas** [comment]
Just tested you email and I was able to pass the validation. Looks like you have some problem with browser and/or autofill or bulit-in browser translator.

**Comment by yangaiping** [comment]
> Just tested you email and I was able to pass the validation. Looks like you have some problem with browser and/or autofill or bulit-in browser translator.

"Did you just use my email to pass through the registration page and enter the login page?"

**Comment by yangaiping** [comment]
> Just created an account with no issues.
> 
> > ask me to provide an organizational email
> 
> No it's not. It asks about your email, that you have to confirm later. The Org name - this name will be used with-in account as display name, you can use any name.
> 
> > my password is correct
> 
> Maybe you used some non utf symbols

"I tried to retrieve my password, but I haven't received any instructions regarding setting a new password in my email."
<img width="274" alt="f1352d937a843815ff92a1460e374b0" src="https://github.com/heartexlabs/label-studio/assets/109123962/39cbae16-2b61-49fd-9c1f-6182e835fad3">
<img width="372" alt="d6ace943f7812f03131c1859610cc93" src="https://github.com/heartexlabs/label-studio/assets/109123962/b963a894-daa7-4168-a54f-a96c4c930d26">

**Comment by farioas** [comment]
Sorry to mislead you. The domain 163.com is not allowed to register, you can use gmail.com or any org related email.

**Comment by yangaiping** [comment]
> Sorry to mislead you. The domain 163.com is not allowed to register, you can use gmail.com or any org related email.

"You don't have to apologize. On the contrary, I should thank you. Thank you very much for patiently answering my questions. I have just registered with my Google account and successfully accessed the enterprise version."
