### ISSUE TITLE
DOM vs page loads time (appears on screen)

### ISSUE THREAD

**Issue by ghanshyamdev** [heartexlabs/label-studio#435]
**Describe the bug**
Currently, the DOM loads fast, but the browser page renders very slowly. It is taking up to `22 seconds` or sometimes even more 

**To Reproduce**
I've attached the **config** and **JSON file** to reproduce the issue
1. Create a New Project
2. Save the config which I've attached
3. Go to the import page and import the JSON file which I've attached
4. Now try to load the labeling page and it will take a lot of time to appear the work on the screen

**Expected behavior**
I think, the page loads as quickly as the DOM

**Screenshots**
![timing](https://user-images.githubusercontent.com/45035063/93884154-2a50ff00-fd00-11ea-8eff-706e7456dbee.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version: 0.7.4

**Additional context**
- Files which I've used : [files.zip](https://github.com/heartexlabs/label-studio/files/5261546/files.zip)
- I've also tested on your app https://app.labelstud.io/

**Comment by ghanshyamdev** [comment]
![time_taken](https://user-images.githubusercontent.com/45035063/93886039-90d71c80-fd02-11ea-8dba-84cc71cf2fbe.gif)

**Comment by makseq** [comment]
@ghanshyamdev Can you check LS version from this branch https://github.com/heartexlabs/label-studio/pull/399 ?

**Comment by ghanshyamdev** [comment]
@makseq In `0.7.5` version, work is impressive.

but I just want to ask you a few questions:
- My above issue totally depends on the [front-end repository](https://github.com/heartexlabs/label-studio-frontend)?
- If yes, then which branch depicts this `LS 0.7.5` in front-end repo for the latest changes. I mean from where I can find the latest front-end code?

**Comment by makseq** [comment]
@ghanshyamdev 
1. yes, totally.
2. tmp/deserialize. 
3. today-tomorrow :smiley_cat:

**Comment by ghanshyamdev** [comment]
Wow, that's good news :tada:
