### ISSUE TITLE
Can not import data when using multi page document annotation template

### ISSUE THREAD

**Issue by Lonepic** [heartexlabs/label-studio#4357]
Validation error

Error at item 0: "document" key is expected in task data [assume: item["data"] = task root with values] :: {'data': {'document[{{idx}}].page': '/data/upload/1/5d355b15-document_page_0001.jpg'}, 'file_upload_id': 38}

Version: 1.7.3

**Comment by AbubakarSaad** [comment]
Hello Lonepic,

Is it possible to show how your are importing the data and the labeling interface?

**Comment by axengine** [comment]
I'm getting the same error.
1. Create a project, select "Multi-Page document annotation" in Labeling Setup, and leave other parameters as default;
2. After the project is successfully created, select a picture and then import it, and get the error message:

Error at item 0: "document" key is expected in task data [assume: item["data"] = task root with values] :: {'data': {'document[{{idx}}].page': '/data/upload/6/3a72a25b-page_1.jpg'}, 'file_upload_id': 13}

VERSION：1.9.1.post0

**Comment by fdejax90** [comment]
Same probleme here, I try to import a pdf located at https://app.heartex.ai/static/samples/sample.pdf 
And get the error below:
> Error at item 0: "document" key is expected in task data [assume: item["data"] = task root with values] :: {'data': {'document[{{idx}}].page': '/data/upload/7/2cdc34dd-sample.pdf'}, 'file_upload_id': 15}

**Comment by makseq** [comment]
When you create a new project from "Multi-page document annotation" template, you have a task data example in the Code section:
![image](https://github.com/HumanSignal/label-studio/assets/501780/32f7e54f-227a-49b0-bd99-ca63adffea65)

You can't merely import an image file, because this template uses Repeater tag, it's a complex annotation type with multiple import sources:

```
<View>
  <Repeater on="$document" indexFlag="{{idx}}" mode="pagination">
      <Image name="page_{{idx}}" value="$document[{{idx}}].page" inline="true"/>
      <RectangleLabels name="labels_{{idx}}" toName="page_{{idx}}">
        <Label value="Title" background="green" />
        <Label value="Date" background="blue" />
        <Label value="Author" background="yellow"/>
        <Label value="Organization" background="orange"/>
        <Label value="Amount" background="red"/>
      </RectangleLabels>
      <View style="display: flex; justify-content: center;">
        <Header value="Rate this page:"/>
        <Rating name="rating_{{idx}}" toName="page_{{idx}}"/>
      </View>
  </Repeater>
</View>
```

Logically it's not possible to combine all images per one task in one import step, so you have to orchestrate them into a JSON file with your tasks that points to your images on some hosting (https, s3, gcs, azure). Example of such a JSON file: 

```
 {
"document": [
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0001.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0002.jpg"
    },
    {
      "page": "https://htx-pub.s3.amazonaws.com/demo/images/demo_stock_purchase_agreement/0003.jpg"
    }
  ]
}
```
