### ISSUE TITLE
azuredeploy will be deprecated on 10/1/2020

### ISSUE THREAD

**Issue by kasuteru** [heartexlabs/label-studio#436]
Just click on the one-click-deploy button and you will see the message.

https://deploy.azure.com/?repository=https://github.com/heartexlabs/label-studio/#/form/setup

**Comment by makseq** [comment]
@kasuteru Can you check "Deploy to Azure" button on this page - https://github.com/heartexlabs/label-studio/tree/release/0.7.5 ?
Is it everything ok now?

**Comment by makseq** [comment]
Fixed in release 0.7.5.

**Comment by kasuteru** [comment]
Hi, sorry I was not able to check since I am on vacation. Will let you know
if any problems arise.

Max <notifications@github.com> schrieb am Mo., 28. Sept. 2020, 15:57:

**Comment by makseq** [comment]
@kasuteru feel free to reopen this issue if you have any troubles.
