### ISSUE TITLE
Add line break support for paragraphs

### ISSUE THREAD

**Issue by Jason3900** [heartexlabs/label-studio#4364]
**Is your feature request related to a problem? Please describe.**
I think label-studio is a wonderful work to simplify the labeling process. But I'm a bit confused when I use `paragraphs` tag for dialogue data. For each turn, there're line breaks and indents such as codes and list of items in the original data. However, they disappear in the front-end which make the content hard to read.

**Describe the solution you'd like**
I believe it's better to preserve what original data looks like. What do you think?

**Comment by cpwan** [comment]
any updates on this issue?

**Comment by DogeWatch** [comment]
any updates on this issue?

**Comment by RobinChiu** [comment]
I found the solution is using the style with the 'white-space' to change it. 
for example:
```
<View style="white-space: pre-wrap;">
  <Paragraphs name="dialogue" value="$messages" layout="dialogue" nameKey="role" textKey="content" />
</View>
```

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
