### ISSUE TITLE
Adding new labeling methods

### ISSUE THREAD

**Issue by tpetri94** [heartexlabs/label-studio#438]
Hi everyone,

I am currently trying to add .csv data labeling to label studio (classification and segmentation). For that, my first step idea was to simply duplicate the text classification example and replace the text field with a table to display a single csv file. 
Now, my problem is that the default <Table> does not support this. While digging through the code and looking at the examples, I ended up at the huge main.158af312.js file which didn't quite help either.

My question now is: Can you explain how completely new ways of labeling data can be added to the project? 

(I am sorry if that seems like a stupid question to anyone, but it really is not to me :smile: )

**Comment by makseq** [comment]
@tpetri94 Hi! Can you tell more about your labeling task? Do you want to label cells of table? And read table from CSV. 

To build a new labeling type you need to know JS React, this part of our library is here:
https://github.com/heartexlabs/label-studio-frontend

Then you need to build your own version of label-studio-frontend and copy it to label_studio/static/editor:
https://labelstud.io/guide/frontend.html#Custom-LSF-LSB-integration

**Comment by makseq** [comment]
@tpetri94 have you any questions? Can I close this issue?

**Comment by tpetri94** [comment]
Hi! Thanks a lot for the quick response. I haven't had time to look into it deeply yet, but it looks as if it answers my question, so thank you and yes, you can close it!

**Comment by makseq** [comment]
@tpetri94 Thanks! Feel free to reopen it.

**Comment by jtlz2** [comment]
@makseq I have the use case of labelling cells of tables. Do you have any pointers on how one would go about implementing this? Thanks!

PS Label Studio is awesome - thank you!

**Comment by hlomzik** [comment]
@jtlz2 in what form do you have this table already? if it's like html table use can simply use HTML NER labeling (`HyperText` tag), like in our examples in playground. You'll get text and xpath with tr/td as a result of such labeling.
If you have it as a csv also, it's not that simple, you have to convert it anyway. It maybe html table again, the easiest and common way. Also consider using `Table` for key-value and `TimeSeries` for numeric values.
