### ISSUE TITLE
Pre-Annotated data cannot be displayed when using task format that I create

### ISSUE THREAD

**Issue by williamAddison** [heartexlabs/label-studio#4397]
**Describe the bug**
I have created a task json creation script that follows the format that Label Studio supports but when I link it over S3 and look at the image I can see that the annotation exists but I cannot see it overlaid in the image. I have compared it between other manually annotated task jsons and they appear nearly identical at this point I am unsure if it is even possible to view and modify the annotations. 

**To Reproduce**
Look atthe images below

**Expected behavior**
An image with the preannotated polygon shapes would show up

**Screenshots**
![image](https://github.com/heartexlabs/label-studio/assets/25141907/1cadb388-a959-42d6-919c-fad404b847d9)

{
  "id": 33,
  "data": {
    "image": "http://hercules:30600/master.full.json/0001397-601295486976-1_Detect_EBR.AdlRef_Top.png"
  },
  "annotations": [
    {
      "id": 30,
      "created_username": "",
      "created_ago": "22 hours, 26 minutes",
      "result": [
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        },
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        },
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        },
        {
          "original_width": 512,
          "original_height": 512,
          "image_rotation": 0,
          "value": {
            "points": [
              [
                269,
                258
              ],
              [
                267,
                270
              ],
              [
                265,
                273
              ],
              [
                264,
                274
              ],
              [
                263,
                274
              ],
              [
                258,
                272
              ],
              [
                254.99999999999997,
                270
              ],
              [
                250.99999999999997,
                260
              ],
              [
                250,
                254
              ],
              [
                250,
                249.00000000000003
              ],
              [
                250.99999999999997,
                245.00000000000003
              ],
              [
                258,
                223
              ],
              [
                260,
                223
              ],
              [
                266,
                225
              ],
              [
                267,
                227.99999999999997
              ],
              [
                268,
                239
              ]
            ],
            "polygonlabels": [
              "Car"
            ]
          },
          "id": "def",
          "from_name": "label",
          "to_name": "image",
          "type": "polygonlabels",
          "origin": "manual"
        }
      ],
      "was_cancelled": false,
      "ground_truth": false,
      "created_at": "2023-06-15T19:47:37.008854Z",
      "updated_at": "2023-06-15T19:47:51.425691Z",
      "lead_time": 1265.961,
      "task": 33,
      "completed_by": null,
      "parent_prediction": null,
      "parent_annotation": null
    }
  ],
  "predictions": []
}

**Environment (please complete the following information):**
 - Running the container with `docker run -it --rm -p8080:8080 -v ~/.pachyderm/config.json:/root/.pachyderm/config.json -device=/dev/fuse --cap-add SYS_ADMIN --name label-studio --entrypoint=/usr/local/bin/label-studio jimmywhitaker/label-studio:pach2.2-ls1.4v3`
 - Connected to a pachyderm cluster where I sync the data from
 - Running on a linux VM

**Additional context**

**Comment by AbubakarSaad** [comment]
Hello William,

Try moving that into "predictions" rather than the "annotations" object

**Comment by williamAddison** [comment]
I tried that earlier and they were visible in the predictions tab in the same way but were not overlayed on the image like I wanted them to appear. The whole goal is to have images that appear in label studio with preannotations that can then be modified and exported and seen outside of label studio

**Comment by williamAddison** [comment]
Update: I formatted everything correctly however the points I was given to annotate the image were in the scale of the original image but for some reason the image in Label Studio is formatted in a 100 x 100 grid so I had to transpose the points to fit that (point x * (100/orig_width) and (point y * (100/orig_height)
