### ISSUE TITLE
Use database in backend

### ISSUE THREAD

**Issue by heyrict** [heartexlabs/label-studio#44]
## Description
Currently the backend uses json to store tasks. It is flexible but less efficient when task size increases, as the backend have to store all tasks in memory.

## Solution
Using external databases e.g. mongodb to store tasks.

## Benefits
- Database operations are much more efficient than direct r/w to json.
- It will be easier to implement an authentication backend described in #38.

## Drawbacks
- It will be harder to write tasks and configure the server.
- If SQL database is used, the database schema should be generated on the fly.

## Notes
#29 should be resolved first to avoid extra setup procedures on the database. (use `docker-compose`)

**Comment by deppp** [comment]
Hey, thanks for the topic.

Currently, we're not planning to add a support for the database. Rationale is that we're concentrating our efforts on covering different data types and types of labeling, and current plain file implementation can be used for quite large datasets. I agree on the limitation with #38, but that functionality is implemented in our commercial offering and at some point will become part of the open-source anyway.

I'll leave the ticket open for a couple of days if you have any additional comments. Thanks!

**Comment by heyrict** [comment]
Thank you for your response. I'll close this issue for now.
