### ISSUE TITLE
can't start label-studio by docker offline

### ISSUE THREAD

**Issue by YuantianGao** [heartexlabs/label-studio#4405]
> 

Hi I have same problem. But I can start serve in docker, but when I access the internet. It logs `RuntimeError: can't start new thread.

_Originally posted by @YuantianGao in https://github.com/heartexlabs/label-studio/issues/3561#issuecomment-1596723673_

**Comment by YuantianGao** [comment]
My docker commend:
```docker run --rm -it -u root --name label-studio --env OPENBLAS_NUM_THREADS=1 --env SENTRY_DSN=  -p 53320:8080 -v /sage/dl-envs/label-data/data:/label-studio/data --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true --env LABEL_STUDIO_LOACL_FILES_DOCUMENT_ROOT=/label-studio/files  -v /sage/dl-envs/label-data/files:/label-studio/files 0958 label-studio --log-level DEBUG --no-browser```
The error message:
```Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
----------------------------------------
Exception occurred during processing of request from ('***.***.**.***', 54290)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 697, in process_request
    t.start()
  File "/usr/lib/python3.10/threading.py", line 935, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread```

**Comment by zixiaosunbro** [comment]
how did u fix it?
