### ISSUE TITLE
Docker image v0.7.4 unavailable

### ISSUE THREAD

**Issue by kir4h** [heartexlabs/label-studio#441]
Opening this issue, not exactly a bug but I guess it's the best category out of the 3 (not using the template because it doesn't make sense)

I was taking a look at the versioning and noticed:

* Version `0.7.4` is tagged in the repository but not available on Docker Hub. Is this on purpose?
* Version `0.7.5` is not yet tagged, currently there is only a release branch; however, version `0.7.5` is available on Docker Hub. Is this correct? (wondering if some kind of suffix should be added if this is still based on a release branch)

Thank you for the clarifications!

**Comment by makseq** [comment]
@kir4h Yes, it's some confusion in docker tags. But as far as I remember the latest tag is 0.7.4 version. 
0.7.5 is not officially released yet, it's only a release candidate for tests.

**Comment by kir4h** [comment]
Yup, that's what it looks like from the repository point of view; but I think `0.7.4` should be pushed so that anyone using docker can use the latest stable version (and maybe relabeling current `0.7.5` to `0.7.5rcx` like it was done in the past with `0.7.2`)

**Comment by makseq** [comment]
Yes, it's a good point and we missed it unfortunately

**Comment by kir4h** [comment]
Out of curiousity: Are those images manually built/pushed? Checking Github Actions I don´t see any docker related stuff. I wouldn´t mind rebuilding and pushing the missing version but this should be done by someone with the required priviledges in Docker Hub

**Comment by makseq** [comment]
Yes, now it's manually. But before we had auto-builds, they was broken because of npm install into dockerhub problems. 

By the way, I pushed 0.7.4.post0 build.

**Comment by kir4h** [comment]
> By the way, I pushed 0.7.4.post0 build.

thanks!
