### ISSUE TITLE
Switching between completions and predictions will remove my labelling from text

### ISSUE THREAD

**Issue by ghanshyamdev** [heartexlabs/label-studio#443]
**Describe the bug**
- when I switch between completions and predictions will lose my labels from the text, which is already labeled previously. 

**To Reproduce**
1. Create a NER based project and import completions and predictions

```
[
  {
    "predictions": [
      {
        "created_ago": "2020-06-17T13:42:06.499Z",
        "created_username": "admin",
        "honeypot": false,
        "id": 1,
        "lead_time": 5.542,
        "result": [
          {
            "from_name": "label",
            "id": "HNmOUgR3rR",
            "source": "$text",
            "to_name": "text",
            "type": "labels",
            "value": {
              "end": 47,
              "labels": [
                "Fact"
              ],
              "start": 42,
              "text": "water"
            }
          },
          {
            "from_name": "label",
            "id": "1oDqSgNvL8",
            "source": "$text",
            "to_name": "text",
            "type": "labels",
            "value": {
              "end": 34,
              "labels": [
                "Ordinal"
              ],
              "start": 26,
              "text": "yourself"
            }
          }
        ]
      }
    ],
    "data": {
      "text": "To have faith is to trust yourself to the water"
    },
    "id": 0
  }
]
```
2. Go to the labeling page
3. Switch between completions and predictions 
4. See an error, that not able to see the label selected on the text

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45035063/94515269-ca4ae300-0240-11eb-978c-2b3e2287c3e8.gif)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version: latest LSB [tmp/deserialize](https://github.com/heartexlabs/label-studio-frontend/tree/tmp/deserialize)

**Additional context**
- I've compared between `master` and `tmp/deserialize` branch

**Comment by makseq** [comment]
> I've compared between master and tmp/deserialize branch

Is there no difference between in versions for this bug?

**Comment by ghanshyamdev** [comment]
In the `tmp/deserialize` branch when I switch between completions to predictions and predictions to completions then my already labeled text will be removed (see below screenshots)

### Before switching
**Here ` February 22` text is labeled with Date**
![image](https://user-images.githubusercontent.com/45035063/94645991-d56a4580-030a-11eb-9295-daef10665662.png)

### After switching from completions to predictions and predictions to completions
**Here ` February 22` text is not showing that it is labeled or not but at RHS it is showing in the region that text is labeled**
![image](https://user-images.githubusercontent.com/45035063/94646095-1febc200-030b-11eb-9f7c-ab13107bea9c.png)

**Comment by ghanshyamdev** [comment]
@hlomzik @makseq 
Even **`Show labels inside the regions`** is not working in `tmp/deserialize`

### Current
![image](https://user-images.githubusercontent.com/45035063/94918522-5de61300-04d0-11eb-996f-09cc8ba64ba0.png)

### Old
![image](https://user-images.githubusercontent.com/45035063/94918663-a271ae80-04d0-11eb-9d79-12cef4473b6a.png)

**Comment by hlomzik** [comment]
Hi, @ghanshyamdev thank you for reports!
The first part is fixed and released both to LSF and LS release branch. The second part about labels in text I'll fix soon. Sorry for inconvenience

**Comment by ghanshyamdev** [comment]
Thanks, @hlomzik @makseq for solving the issues. I think you've also solved the above issue as well. So I'm closing, the issue is no more persist.
