### ISSUE TITLE
How to get the content(e.g. images) from request with out cookie?

### ISSUE THREAD

**Issue by HtwoOtwo** [heartexlabs/label-studio#4455]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by erinmikailstaples** [comment]
Hey @HtwoOtwo in order to best help you we'll need more information about how to solve this issue.

Without any further context I'm unable to understand how to best help you.

Closing this for the meantime.

**Comment by HtwoOtwo** [comment]
Apologies for not providing enough details earlier. What I meant is, how can I access my images? Currently, both my Label Studio and data are stored in place A. However, I need to access this data from place B. Currently, the only way I can do this is by using "request" to fetch the images via their URLs, but it requires cookies. Is there any other method to achieve this? Thank you.
