### ISSUE TITLE
Migrating URL

### ISSUE THREAD

**Issue by menandro** [heartexlabs/label-studio#4463]
**Describe the bug**
Not sure if it's a bug or a feature. Please feel free to move.

Changing URL from:
`label-studio -p PORT --host URL1`
to:
`label-studio -p PORT --host URL2`
results in a forbidden access error. [WARNING] Forbidden /dev/local...

The annotation are still there but the locally linked images shows broken file icon.

**To Reproduce**
1. Run LS on one URL: `label-studio -p PORT --host URL1`
2. Create a project
3. Add a folder containing the images as local storage
4. Save
5. Exit LS and close LS server.
6. Reopen LS on a different URL `label-studio -p PORT --host URL2`
7. Open previously created project

**Expected behavior**
After step 7 above, the images should show broken icons.

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

**Comment by hogepodge** [comment]
Since the images are stored locally, it's likely that the images are pointing to the old URL. Can you check this by right-clicking the broken image link and copying the address? It's likely that it's pointing to URL1 rather than URL2.

**Comment by menandro** [comment]
@hogepodge It does point to URL1. How do I fix this?

**Comment by hogepodge** [comment]
It's difficult to say without direct access to the filesystems and setup to debug.

**Comment by menandro** [comment]
I resolved this by manually editing the db (label_studio.sqlite3) file and changing the "task" table's "data" column to the new URL.
