### ISSUE TITLE
Disable Nested Entity Annotations "Named Entity Recognition" in "Natural Language Processing"

### ISSUE THREAD

**Issue by yanwenjie1** [heartexlabs/label-studio#4469]
In the named entity recognition task, it seems that nested entities are allowed by default. To disable nested entity annotations, how can i set?

**Comment by hogepodge** [comment]
This is managed in the labeling configuration file.

**Comment by erinmikailstaples** [comment]
Hey @yanwenjie1 — thank you for reaching out. 

You can further customize the Named Entity Recognition (NER) template to suit your need. 

Here's a link to our documentation on how to customize our Named Entity Recognition template https://labelstud.io/templates/named_entity.html

I'm closing this issue out and marked resolved. 

In the meantime come join us on the [community slack](https://slack.labelstud.io/?source=GitHub) if you have any further questions.
