### ISSUE TITLE
Backward slash is appearing in the file_name field of the exported COCO json file on Ubuntu

### ISSUE THREAD

**Issue by roshansinghbisht** [heartexlabs/label-studio#4473]
**Description**
When exporting annotations in the COCO format, a backward slash appears in the file_name field of the exported COCO JSON file.

**To Reproduce**

1. I had a pre-annotated COCO json file (generated by the model), and I wanted to refine the bounding boxes. 
2. I followed the steps mentioned over [here](https://github.com/heartexlabs/label-studio/issues/2806#issuecomment-1210000572), and I was able to import the annotations.
3. I have set 'Local files' as my Source storage type, and my absolute path is: /home/roshan/images
4. Now, when I export my tasks in the COCO file format, the project gets downloaded and I get the images and result.json in my Downloads folder.
5. [ISSUE: ] In the result.json file, the file_name field is in the following format: \/home\/roshan\/images\/image_name.jpg

**Expected behavior**
The file_name field should be in this format: /home/roshan/images/image_name.jpg

**Screenshots**
![label-studio-slash](https://github.com/heartexlabs/label-studio/assets/40305442/a4f073b1-5d1d-4ce8-bece-46bd4acf01e4)

**Environment:**
 - OS: Ubuntu 22.04.2 LTS
 - Label Studio Version: 1.8.0

**Comment by hogepodge** [comment]
JSON requires that special characters be escaped to render properly. The `\/` is an escape sequence that represents `/`.
