### ISSUE TITLE
Blanks appearing in Choices

### ISSUE THREAD

**Issue by RachellCordero** [heartexlabs/label-studio#4492]
There are blanks that appear as choices  and when scrolled down, the correct choices disappear as well. 
 So when I click the dropdown of Choices the choices that appear are :
 FOOD
 BEVERAGE
 blank
 blank
 blank

My Choice tag looks like this 
	```
<Choices value="department" name="Department" toName="text" layout="select" placeholder="Select department">
          <Choice value="FOOD"/>
          <Choice value="BEVERAGE"/>        
         </Choices>
``

**Comment by hogepodge** [comment]
@RachellCordero can you [join the Slack community](https://slack.labelstud.io/?source=github)? It looks like there might be an issue with your label config, and the community will be able to give you more help there.
