### ISSUE TITLE
Loading time for brush labels is too high

### ISSUE THREAD

**Issue by MitanshuShaBa** [heartexlabs/label-studio#4497]
**Describe the bug**
I have dataset of images on which I perform semantic segmentation. These annotations of brush labels take too long to open and then it is stuck at the loading screen.

**Expected behavior**
Images load quickly 

**Screenshots**

https://github.com/heartexlabs/label-studio/assets/42906426/51c2c410-355a-48e9-93fa-9ddd30c5eee1

**Environment (please complete the following information):**
 - OS: Windows 11
 - Label Studio Version: 1.7.1

**Additional context**

**Comment by JonasZaoui2** [comment]
Hi @MitanshuShaBa ,
Same problem..

**Comment by hogepodge** [comment]
@MitanshuShaBa can you update to Label Studio 1.8? Also, can you paste the resources available on your machine, and possibly your labeling configuration? Depending on the labeling configuration, number of images, location, and host resources, there are a number of different things that could be happening. Thanks!

**Comment by MitanshuShaBa** [comment]
Yes, updating to 1.8 fixed the issue
