### ISSUE TITLE
Available storages: Auto-generate instead of hardcode. (Refactor / Low priority)

### ISSUE THREAD

**Issue by kasuteru** [heartexlabs/label-studio#450]
Not a bug but more of a todo at some point, since it only affects developers. Wasn't sure how to report.

I got stuck for quite a while trying to have Azure source show up in the GUI. Turns out this was because the list of source to show is not generated by 

https://github.com/heartexlabs/label-studio/blob/d0ddb68f7d6d14d2a9f33973c8f688250eb5f4c0/label_studio/storage/base.py#L23-L26

but instead hardcoded somewhere else:

https://github.com/heartexlabs/label-studio/blob/d0ddb68f7d6d14d2a9f33973c8f688250eb5f4c0/label_studio/project.py#L83-L84

This was very unexpected to me - I did not assume that I had to change anything outside of storage.

I propose refactoring this with an additional flag in register_storage, e.g. ´show_in_GUI´ - and creating the list of storages on-the-fly depending on the registered modules.

This is low priority.

**Comment by kasuteru** [comment]
I am not able to re-assign this issue to myself, nor can I replace the issue:bug label with an issue:refactor. Feel free to do so.

**Comment by kasuteru** [comment]
@makseq: I am looking at this, however, since I am not a front-end expert, I am stuck understanding one part: In multiple parts, e.g. in the function below, an instance of LabelStudio is created. However, I cannot find where this function is defined?

https://github.com/heartexlabs/label-studio/blob/47fc8dc96d82f8c91ca282f224afbbcdbe2cf9d1/label_studio/static/js/lsf-sdk.js#L230

**Comment by kasuteru** [comment]
Edit: Nevermind, I misinterpreted this part. Please ignore.

**Comment by kasuteru** [comment]
@makseq : I am making progress with this. Meanwhile, I think I found some dead execution paths / functions:

get_available_storage_names is defined twice: Once in 
https://github.com/heartexlabs/label-studio/blob/14f7ddff64660ea0094ff0e7bfcc0d72d477c981/label_studio/project.py#L70
and once in 
https://github.com/heartexlabs/label-studio/blob/14f7ddff64660ea0094ff0e7bfcc0d72d477c981/label_studio/storage/base.py#L41

as far as I can see, only the upper one is ever really used - the lower one is imported by https://github.com/heartexlabs/label-studio/blob/master/label_studio/storage/__init__.py , but never used.

Is there a reason behind this or are these leftovers? Otherwise, I will remove this during the refactor.

**Comment by kasuteru** [comment]
Sorry for prematurely replying, I figured out what you are trying to do and will keep the functionality.

**Comment by makseq** [comment]
We are completely reworking our codebase, so I think this is no longer relevant.
