### ISSUE TITLE
Npm install failing because of `sh scripts/postinstall.sh`

### ISSUE THREAD

**Issue by pieterjandebruyne** [heartexlabs/label-studio#4503]
**Describe the bug**
Installation of the npm package is not working

**To Reproduce**
`npm i @heartexlabs/label-studio --save`

**Expected behavior**
Installation of the npm package

**Screenshots**
![Screenshot 2023-07-11 at 14 30 45](https://github.com/heartexlabs/label-studio/assets/9568274/c20d1d87-81c5-4077-b76a-8b6348f4bd3f)

**Environment (please complete the following information):**
 - OS: macOS 13.4.1
 - Label Studio Version 1.8.0

**Additional context**
`scripts/postinstall.sh` not available but triggered

Seems like 1.8.0 is. missing the build folder: https://unpkg.com/browse/@heartexlabs/label-studio@1.8.0/

also https://github.com/heartexlabs/label-studio-frontend/issues/370 seems to mention we should use
`import LabelStudio from "@heartexlabs/label-studio"` instead of `import LabelStudio from "label-studio"` as mentioned in the readme
I get `TS2307: Cannot find module '@heartexlabs/label-studio' or its corresponding type declarations.`on both imports in a new react-create-app ts app.
Also tried without typescript without success, IDE says "Module is not installed" while it is.

**Comment by hogepodge** [comment]
Thanks for the bug report @pieterjandebruyne. We'll file an internal ticket and report back with updates.

**Comment by jbaex** [comment]
@hogepodge any updates on this issue? Is there a workaround for this?

**Comment by ZGW99** [comment]
If you have a solution to this problem, please reply to me, thank you.

**Comment by hogepodge** [comment]
@nicholasrq bringing your attention to this in case you have insight

**Comment by zheyunwu** [comment]
Same problem here

**Comment by priteshjain0310** [comment]
Still facing this issue. Any resolution in sight?

**Comment by johanneszellinger** [comment]
I have the same issue, working within a nodejs project in Visual Studio.

**Comment by fgiuba** [comment]
Same here. Any update?

**Comment by hogepodge** [comment]
With the migration of Label Studio to a monorepo and integrated development, the Label Studio Frontend package is no longer supported. The installation issues with that script will likely not be addressed. I understand that this isn't the answer that you would have hoped for, but limited development resources forced us to make this difficult decision.

**Comment by Basantrajshakti** [comment]
Use: npm i @heartexlabs/label-studio@1.4.0

Worked in my case.
