### ISSUE TITLE
just a little bug

### ISSUE THREAD

**Issue by aiyou9** [heartexlabs/label-studio#451]
when I want to use nightly builds, I am download the source code using Git and run Label Studio locally，but when I run “python setup.py develop” ，It give me a bug as show below：

![image](https://user-images.githubusercontent.com/15712822/95775433-ff513e00-0cf4-11eb-9c2d-fd1ce4dc6f9c.png)

It can be fix by add the code in yellow box at file “setup.py ”
![image](https://user-images.githubusercontent.com/15712822/95775780-9b7b4500-0cf5-11eb-8eed-38c57820af49.png)

i wish it maybe help

**Comment by makseq** [comment]
We ll fix it in nearest release 🙂

**Comment by makseq** [comment]
Added in 0.7.5.post0
