### ISSUE TITLE
I want to add a feature of members page which is on label studio enterprise version but I am not able to find the header section inside label-studio, so can anyone help me out.

### ISSUE THREAD

**Issue by ujjwalbharadwaj** [heartexlabs/label-studio#4516]
I want to add  members button feature here on my local server as you can see in the below image.
![image](https://github.com/heartexlabs/label-studio/assets/79165874/22660b60-ccc4-4811-b52a-e9045da05000)

I want to add this feature as in the image below.
![image](https://github.com/heartexlabs/label-studio/assets/79165874/2337fdd5-e940-4c97-a8b3-a2a1aec02fbd)

**Comment by hogepodge** [comment]
Advanced members management is an enterprise-only feature.

**Comment by erinmikailstaples** [comment]
Hey @ujjwalbharadwaj — this is an enterprise only feature and unfortunately from the OS version is not available for adapting and editing. 

I'm closing this ticket — but happy to help if you have any further questions
