### ISSUE TITLE
How to import completions?

### ISSUE THREAD

**Issue by kathoum** [heartexlabs/label-studio#452]
I'd like to import pre-annotated tasks (with completions).

When I import tasks from a JSON file with completions, the imported tasks have an attached completion, but the list of completions is still empty: I can't train a ML model with them. I have to open every task and click either 'Update' or 'Set Ground Truth' on the completion.

To reproduce the issue:
- create a new project
- import a sample task
- add a completion
- export to JSON
- delete all tasks
- import tasks from the exported JSON file
  The import status messages will say: 1 task and 1 completion created
- go to Tasks page: you'll see 1 task and 0 completions

**Comment by makseq** [comment]
> but the list of completions is still empty

Where is it empty?

**Comment by kathoum** [comment]
1. In the Tasks page, it says '0 completions'
2. When I try to train a model, I get the error "No completions found"
3. The API /api/projects/1/completions_ids/ returns an empty list

**Comment by makseq** [comment]
Can you check release/0.7.5 branch? I've fixed this issue there.

**Comment by kathoum** [comment]
It's fixed now. Thanks!
