### ISSUE TITLE
Bug while making zoom in Label Studio

### ISSUE THREAD

**Issue by AntonioSanchezGutierrez** [heartexlabs/label-studio#4528]
**Describe the bug**
I'm trying to correct a prediction model based on bbox detection. It must be so accurate as i can fit it so i need to make zoom in. The bug comes while i'm making zoom if i try to move one of the edges of the bbox, it automatically gets resized to the window image dimensions.

**To Reproduce**
1. Make a prediction model so you can obtain an image or several images with different objects detected with bbox.
2. Click on any label for improving the precision.
3. Make zoom in so you can be more accurate and move any edge.
4. Bbox is resized automatically itself and when you make zoom out the bbox is smaller so you lose original dimensions.

**Expected behavior**
What i expected to happen is that bbox got adjusted without resizing itself automatically. I'll try to explain better with images.

**Screenshots**
First of all, i have in this image lots of bbox generated by prediction.
![Captura desde 2023-07-18 11-39-44](https://github.com/heartexlabs/label-studio/assets/136337283/a09db553-2951-41d3-88c4-c1106b259483)
Then i make zoom at the right part of the object and i slightly modify the position of the right edge of the bbox and the entire bbox gets resized as you can see on the corners of the next image.
![Captura desde 2023-07-18 11-40-08](https://github.com/heartexlabs/label-studio/assets/136337283/60c61bcb-8121-4601-a761-ecfd355da26c)
Then i finally get this:
![Captura desde 2023-07-18 11-40-27](https://github.com/heartexlabs/label-studio/assets/136337283/e9f3712a-968c-4593-a7f3-17a617798753)
This way i cant get the precision i need for my project.

**Environment**
 - OS: [Ubuntu 22.04.2 LTS]
 - Label Studio Version [1.6.1dev]

**Additional context**
The bug takes place not only with predicted models. If i try to make the bbox detection by myself and not by prediction it happens the same.
Thanks for your attention.

**Comment by erinmikailstaples** [comment]
ooh thanks @AntonioSanchezGutierrez for this well written description and organization of this — it's really appreciated (and helps us solve the issue quicker!) 

I'm going to look into this a bit further and attempt to reproduce the issue — is there anything that I should keep in mind when looking to reproduce?

**Comment by hogepodge** [comment]
This has been fixed in Label Studio 1.7.0+.

**Comment by AntonioSanchezGutierrez** [comment]
> ooh thanks @AntonioSanchezGutierrez for this well written description and organization of this — it's really appreciated (and helps us solve the issue quicker!)
> 
> I'm going to look into this a bit further and attempt to reproduce the issue — is there anything that I should keep in mind when looking to reproduce?

Hi! Sorry for replying so late. I think everything was already well explained in the issue. Thanks for your attention!

**Comment by AntonioSanchezGutierrez** [comment]
> This has been fixed in Label Studio 1.7.0+.

Oh Thank you!
