### ISSUE TITLE
Uploading to tasks table takes very long larger projects

### ISSUE THREAD

**Issue by harshithere** [heartexlabs/label-studio#4549]
**Describe the bug**
Our system currently has ~200 active projects and the tasks table has roughly 3.8 million rows. While uploading multiple new tasks for annotation using the `/api/projects/{id}/import` api with a Csv file as input, we often run into 504 gateway timeout errors on the service calling label studio. The code has validation for format checks [[ref](https://github.com/heartexlabs/label-studio/blob/develop/label_studio/data_import/functions.py#L20)] which loads the existing data in the table belonging to the particular project. My guess is that this loads all existing rows which is very memory and time intense. Is there a more memory efficient way to upload new tasks.

**To Reproduce**
Requirement: A system where there are sufficient number of rows in the tasks table
1. Move to a project with large number of existing annotations (120k in our case)
2. Try uploading a new file with tasks (>1k) to that project
3. Monitor the time taken for the various Sql queries.

**Expected behavior**
Ideally, uploading new n number of datapoints to existing large projects should have similar memory and time footprint as uploading same number of tasks to a newer project

**Environment (please complete the following information):**
 - Pod RAM: [5.5 Gb]
 - Label Studio Version [1.6.0]
 
 Please let me know if the problem needs more description or details

**Comment by erinmikailstaples** [comment]
Hey @harshithere – thanks for reaching out, we're going to flag this to be looked at internally and test things out on our end. 

Is there anything else we can help out with?

**Comment by hogepodge** [comment]
If it's possible, breaking up the CSV into smaller files should help with import. In the meantime we've added this to our internal tracker for review.

**Comment by harshithere** [comment]
We tried the smaller files approach. This has happened on files as small as 300 rows. My hypothesis is that is depends more on number of existing rows in the table rather than size of the new upload. 
Also, this is a flaky bug. Same upload with same parameters can work in multiple attempts. 
Thanks for the quick response.

**Comment by hogepodge** [comment]
@harshithere one last thing, I noted that you're using LS 1.6.0. We've made a lot of improvements to the workflow since then. Can you upgrade to 1.8+ and see if this has been fixed in a newer version?

**Comment by harshithere** [comment]
Hey, do we have any updates here? @hogepodge @erinmikailstaples 
Did any of you try replicating the bug

**Comment by makseq** [comment]
>  ~200 active projects and the tasks table has roughly 3.8 million rows

These sizes are huge and it requires a very specific tuning of your DB. Label Studio Community is not designed to work in scale, I recommend to switch to enterprise. E.g. the enterprise version uses background workers for importing and it avoids gateway timeout errors. Also our devops engineers always monitor the DB state and do lots of optimizations there.
