### ISSUE TITLE
Support Hypertext inside Lists

### ISSUE THREAD

**Issue by query-as** [heartexlabs/label-studio#4552]
**Is your feature request related to a problem? Please describe.**
I want to use Ranker to have my labelers rank relatively long and complex text. But right now, Lists only support plaintext, so everything just gets dumped into one difficult-to-read blob.

**Describe the solution you'd like**
I would like to be able to put HTML inside the `body` field of the `items` in a `List`. That way I could format the text nicely.

**Describe alternatives you've considered**
Two smaller versions of this ask:
1. Just add newline support inside `body`s. Right now, a `\n` inside the `body` field is not reflected in the UI.
2. Allow basic markdown support inside `body` so that we can add newlines, bold, italicize, etc.

**Additional context**
Status quo:
```
          "items": [
              {
                  "title": "LlamaModel",
                  "body": "Mary had a little llama.\n\nIts zero-covariance fleece was white as snow. Look, Mom, I can format!",
                  "id": "llama_model"
              },
```
<img width="479" alt="image" src="https://github.com/heartexlabs/label-studio/assets/130112337/6c83aaa5-89cf-49b7-8e28-d8ec2769591d">

Possible future:
```
          "items": [
              {
                  "title": "LlamaModel",
                  "body": "<p>Mary had a little llama.</p></br><p>Its zero-covariance fleece was white as snow.</p></br><i>Look, Mom, I can format!</i></br><b>Look at me go!</b>",
                  "id": "llama_model"
              },
```
<img width="474" alt="image" src="https://github.com/heartexlabs/label-studio/assets/130112337/6b1565f8-6678-4f27-ab6f-5e160e0545c2">

**Comment by query-as** [comment]
Upon further search, it turns out that this _is_ supported, just not documented on the [List](https://labelstud.io/tags/list.html) page. The [Visual Ranker](https://labelstud.io/templates/generative-visual-ranker.html) template reveals that you can actually put things in the `html` field.

I think the List documentation should be updated, but I will close this issue since it's already been done.

**Comment by rq-aszasz** [comment]
Thank you @query-as, awesome hint.
