### ISSUE TITLE
The number of files exceeded settings.DATA_UPLOAD_MAX_NUMBER_FILES

### ISSUE THREAD

**Issue by htdung167** [heartexlabs/label-studio#4556]
I am labeling data with a large amount of data, but when importing data, it is limited to only 100 files. 
How to increase the number of imported files?

![image](https://github.com/HumanSignal/label-studio/assets/73953274/b5c931e0-9f0f-4725-b7a7-49231dee48b6)

**Comment by dxv2k** [comment]
I'm facing the same problem with using the API via label-studio-sdk too

**Comment by htdung167** [comment]
> API via label-studio-sdk too

I have solved this problem with docker version. I added "DATA_UPLOAD_MAX_NUMBER_FILES = None" into label-studio/label_studio/core/settings/base.py and rebuild image. Same handling for DATA_UPLOAD_MAX_MEMORY_SIZE error when you upload large file. 
This is a problem of django in new version.

**Comment by erinmikailstaples** [comment]
Hey all! 

@htdung167 and @dxv2k thanks for flagging this!  This is something caused by the latest Django updates that does impact Label Studio.

As @htdung167 mentioned — the current workaround is to: 

> "DATA_UPLOAD_MAX_NUMBER_FILES = None" into label-studio/label_studio/core/settings/base.py and rebuild image.

We are passing this to our support and engineering teams to work towards resolving this. 

In the meantime, thanks for the documentation and flagging it for our review. :) 

Happy Labeling!

**Comment by hogepodge** [comment]
@bmartel @makseq @niklub this looks like a regression in label studio behavior introduced by a new version of Django.

Can we also set this variable on the command-line as a workaround, or does it need to happen in the base.py file?

**Comment by dxv2k** [comment]
I tried a workaround by using a variable environment but didn't have any luck. 
Only modified `settings/base.py` works.

**Comment by mkrupczak3** [comment]
> Hey all!
> 
> @htdung167 and @dxv2k thanks for flagging this! This is something caused by the latest Django updates that does impact Label Studio.
> 
> As @htdung167 mentioned — the current workaround is to:
> 
> > "DATA_UPLOAD_MAX_NUMBER_FILES = None" into label-studio/label_studio/core/settings/base.py and rebuild image.
> 
> We are passing this to our support and engineering teams to work towards resolving this.
> 
> In the meantime, thanks for the documentation and flagging it for our review. :)
> 
> Happy Labeling!

@erinmikailstaples Unfortunately, this does not work when running label-studio in a docker container. Is there any solution for this environment?

**Comment by htdung167** [comment]
> > Hey all!
> > @htdung167 and @dxv2k thanks for flagging this! This is something caused by the latest Django updates that does impact Label Studio.
> > As @htdung167 mentioned — the current workaround is to:
> > > "DATA_UPLOAD_MAX_NUMBER_FILES = None" into label-studio/label_studio/core/settings/base.py and rebuild image.
> > 
> > 
> > We are passing this to our support and engineering teams to work towards resolving this.
> > In the meantime, thanks for the documentation and flagging it for our review. :)
> > Happy Labeling!
> 
> @erinmikailstaples Unfortunately, this does not work when running label-studio in a docker container. Is there any solution for this environment?

you should clone this source code, add "DATA_UPLOAD_MAX_NUMBER_FILES = None" , rebuild image, then run docker.

**Comment by mkrupczak3** [comment]
Thanks, it seems the old [labelImg](https://github.com/HumanSignal/labelImg) project is a better fit for our needs right now

**Comment by mkrupczak3** [comment]
Hi @erinmikailstaples, any ETA on a fix?

We're waiting for one before deploying a label-studio server.

**Comment by uasdev** [comment]
Hi all,

I installed label-studio using python as per the docs. When I add:
> DATA_UPLOAD_MAX_NUMBER_FILES = None
> DATA_UPLOAD_MAX_MEMORY_SIZE = None

It still does not work for me. Is there an older version of label-studio that would still work?

Thanks in advance!

**Comment by FrankwaP** [comment]
@uasdev I have a feeling you've added this variable after the install ?


I can confirm that it's possible to fix it for a classical (non-docker) install:
1. `git clone` the repo
2. add `DATA_UPLOAD_MAX_NUMBER_FILES = None` into the `label-studio/label_studio/core/settings/base.py` file
3. install with `pip install .` while in the label-studio root folder

This means it will also fix the official install (`pip install label-studio`). 
 @erinmikailstaples  I can make a pull request if needed… but it's just one line to add! 
 
**EDIT**
The import can be extremely slow however.
I had +1000 images and decided to use the [Local Storage method](https://labelstud.io/guide/storage.html#Local-storage). It worked very well and took me 2min (sftp+setting).
So **one should consider this method when having problems with files number!**

**Comment by makseq** [comment]
Can you try running this PR? 
https://github.com/HumanSignal/label-studio/compare/LSDV-5462

You have to set environment variable when you run LS:
DATA_UPLOAD_MAX_NUMBER_FILES = 1000000

**Comment by hogepodge** [comment]
A fix for this has been merged in the main repository and is scheduled for release in the next version of Label Studio. Thanks to everyone who reported on this and helped us to write up a patch.

**Comment by mks2192** [comment]
> @uasdev I have a feeling you've added this variable after the install ?
> 
> I can confirm that it's possible to fix it for a classical (non-docker) install:
> 
> 1. `git clone` the repo
> 2. add `DATA_UPLOAD_MAX_NUMBER_FILES = None` into the `label-studio/label_studio/core/settings/base.py` file
> 3. install with `pip install .` while in the label-studio root folder
> 
> This means it will also fix the official install (`pip install label-studio`). @erinmikailstaples I can make a pull request if needed… but it's just one line to add!
> 
> **EDIT** The import can be extremely slow however. I had +1000 images and decided to use the [Local Storage method](https://labelstud.io/guide/storage.html#Local-storage). It worked very well and took me 2min (sftp+setting). So **one should consider this method when having problems with files number!**

could you please make a pull request @FrankwaP

**Comment by hogepodge** [comment]
@mks2192 this has already [been fixed upstream](https://github.com/HumanSignal/label-studio/blob/558cd177050d785668ae019cc4dc423f86c1ec66/label_studio/core/settings/base.py#L454), and is in the latest releases.

**Comment by mks2192** [comment]
Thanks @hogepodge , anyway i was able to fix it just by changing base.py in the installation folder
f"C:\Users\{user_id}\AppData\Local\anaconda3\envs\{env_name}\Lib\site-packages\label_studio\core\settings"

**Comment by aimlnerd** [comment]
@hogepodge I am getting the same error in version 1.9.2 
Is there a fix for this?

i pip installed label studio

**Comment by MOXHAN** [comment]
Any fix for this with the pip installation? Is it possible to at least get to know the maxim upload size? Im stuck on trial & error

**Comment by jombooth** [comment]
@MOXHAN you can't set `DATA_UPLOAD_MAX_NUMBER_FILES` to `None`, but you could either run:

```
$ export DATA_UPLOAD_MAX_NUMBER_FILES=10000000  # just any large number, bc None doesn't work
$ label-studio
``` 

or just

```
$ DATA_UPLOAD_MAX_NUMBER_FILES=10000000 label-studio
```

**Comment by MOXHAN** [comment]
Alright, I will try that out. Thanks a lot :)

**Comment by MOXHAN** [comment]
@jombooth Maybe you can help me with this one too: Im trying to export my labels, but after loading a few minutes the server crashed. It gave me a warning like " No completions found for Item #123" . First I thought that might be background images, so no labels. But that doesnt match up. I read on another post somebody had the same problem and they are on docker and increased the servers Ram. How can I achieve something similar in the pip installation?

**Comment by ogbanugot** [comment]
In case anyone is wondering this how you would set DATA_UPLOAD_MAX_NUMBER_FILES when running the container:

`docker run -it -p 8080:8080 -e DATA_UPLOAD_MAX_NUMBER_FILES=2000 -v $(pwd)/mydata:/label-studio/data heartexlabs/label-studio:latest`

**Comment by halqadasi** [comment]
Adding `-env DATA_UPLOAD_MAX_NUMBER_FILES=10000` worked with me

`docker run -it -p 8080:8080 -env DATA_UPLOAD_MAX_NUMBER_FILES=10000 heartexlabs/label-studio:latest`

**Comment by makseq** [comment]
Note that we highly not recommend using file uploads for big projects. Use cloud storages instead: https://labelstud.io/guide/storage

**Comment by topherbuckley** [comment]
> Note that we highly not recommend using file uploads for big projects. Use cloud storages instead: https://labelstud.io/guide/storage

Why is this the case? If I have all the data locally, why make users buy cloud storage to use this?

**Comment by ManuelZ** [comment]
I just installed Label Studio 1.13.0  in a freshly created environment and I faced this same problem. Setting the env variable solved it, but is a little annoyance.

**Comment by JET00wy** [comment]
It has been more than a year. Is there anyone to fix this problem?

**Comment by mraduldubey** [comment]
> Can you try running this PR? https://github.com/HumanSignal/label-studio/compare/LSDV-5462
> 
> You have to set environment variable when you run LS: DATA_UPLOAD_MAX_NUMBER_FILES = 1000000

Shortest  & sweetest fix for me. I added it in environment  variable in win. Thank you.

**Comment by simofildi** [comment]
sept 2025 and still having the same issue lol

**Comment by rohanrajBC** [comment]
January 2026 and same problem

**Comment by rgmantovani** [comment]
September 2026, and same problem here
