### ISSUE TITLE
doc : Broken Links on LSE Documentation Page

### ISSUE THREAD

**Issue by erinmikailstaples** [heartexlabs/label-studio#4569]
**Describe the bug**
Broken Links on API documentation page. 

**To Reproduce**
1. Go to https://docs.humansignal.com/guide/api.html
2. Click on API reference documentation —as well as many others are broken.  Double check links
3. Hit 404 page 

**Expected behavior**
Links take you to the correct link

**Environment (please complete the following information):**
 in documentation

**Additional context**
On Label Studio Enterprise Docs page.

**Comment by erinmikailstaples** [comment]
Hey @huguestennier — the API docs should link here: 

https://labelstud.io/api

**Comment by hogepodge** [comment]
@huguestennier @farioas @bmartel What would be the appropriate link for the enterprise side of things? Do we just want to send everyone to the label studio api docs?
