### ISSUE TITLE
What is json filter?

### ISSUE THREAD

**Issue by nabinkhadka** [heartexlabs/label-studio#458]
I googled a little and cannot find where does [this](https://github.com/heartexlabs/label-studio/blob/14f7ddff64660ea0094ff0e7bfcc0d72d477c981/label_studio/templates/labeling.html#L15) jinja filter come from. Is this a typo and should have been `tojson` instead of `json`?

**Comment by fromnorthpole** [comment]
It's (re)implemented [here](https://github.com/heartexlabs/label-studio/blob/master/label_studio/server.py#L121)
