### ISSUE TITLE
Unable to annotate relations locally: Label studio entity panel is missing

### ISSUE THREAD

**Issue by nopper** [heartexlabs/label-studio#460]
**Describe the bug**
I am unable to use relations annotations, both using latest `pip` version of label-studio or using the cloned github repository.

**To Reproduce**

1. `pip install label-studio`
1. `label-studio init test && label-studio start test`
2. Connect to  http://0.0.0.0:8080/ via browser.
3. Click on `Setup your label config`.
4. Click on `Relations among entities` and confirm on the dialog box by clicking on `Proceed`.
5. On the interface preview on the right you will see the text `Note: To manage relations you need Label Studio entity panel to be shown`. 

**Expected behavior**
I am expecting to see relation annotation pane as I see in the label-studio playground site.

**Screenshots**
What I see locally:
![image](https://user-images.githubusercontent.com/129937/96624440-08ea2f80-130d-11eb-9463-e880fd17435d.png)

What I see on the official playground site:
![image](https://user-images.githubusercontent.com/129937/96624332-e48e5300-130c-11eb-8425-aa840f3c9edc.png)

**Comment by makseq** [comment]
@nopper Can you show your screen entirely?

**Comment by makseq** [comment]
I've just checked this in latest LS version, everything looks ok..

**Comment by nopper** [comment]
Sure here's the screenshot of the full page:

![image](https://user-images.githubusercontent.com/129937/96727686-a39d4980-13b3-11eb-9225-1716b3b8bd10.png)

**Comment by makseq** [comment]
@nopper But it's Setup page, you don't need to make a labeling here. Use Labeling or Tasks page, after you setup the project.

**Comment by nopper** [comment]
Ok then my bad.

I was a confused by the fact that this was working in the Setup page on the playground site, but not locally in the Setup page. Therefore I didn't even bother saving the setup because I thought something was off.

I would probably add a clarification in the Setup page, if what you will see in the labeling phase will be different then what I am seeing in the project/Setup phase.

**Comment by makseq** [comment]
Yes, it's a good point to write about it. Thank you, I think we will add it.

**Comment by makseq** [comment]
We've added Result panel on the Setup page in 0.8.0.
