### ISSUE TITLE
S3 Target Storage Connection Error

### ISSUE THREAD

**Issue by shuyangsun** [heartexlabs/label-studio#4605]
When using AWS S3 as Target Storage, the "Check Connection" step fails if the IAM Policy does not grant list bucket access.

1. Go to "Settings" in the project.
2. Click on 'Cloud Storage' and 'Add Target Storage'.
3. Fill in "Bucket Name", "Bucket Prefix" and "Region".
4. Add IAM user credential with the following IAM policy (console and write access not shownfor simplicity):

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowListSourceSubFolders",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::<BUCKET_NAME>"
            ],
            "Condition": {
                "StringLike": {
                    "s3:prefix": [
                        "<PREFIX>",
                        "<PREFIX>/*"
                    ]
                }
            }
        }
    ]
}
```
5. Click 'Check Connection'.
6. See error "RUNTIME ERROR \n Validation error \n An error occurred (403) when calling the HeadBucket operation: Forbidden"

**Expected behavior**
The connection check should pass as long as the IAM policy has "s3:ListBucket" permission on the prefix, Bucket-level access is unnecessary and is a security risk.

 - OS: Windows 11
 - Label Studio Version 1.8.1

The problem is due to `S3StorageMixin` class in `label_studio/io_storages/s3/models.py` calling `client.head_bucket(...)` instead of `client.list_objects_v2(...)` when it's the Export class.

**Comment by shuyangsun** [comment]
In the case of exporting, the program should check both scenarios: `list_objects_v2` on the prefix first, if that fails, call `client.head_bucket` to make sure there is permission to write to the entire bucket.

**Comment by jombooth** [comment]
Hi @shuyangsun - thank you so much for your report, detailed repro instructions, and suggestion for a fix! It's been implemented in https://github.com/HumanSignal/label-studio/pull/4759.
