### ISSUE TITLE
Attribute `selected` ignored in `Choice` in latest stable version

### ISSUE THREAD

**Issue by nopper** [heartexlabs/label-studio#461]
**Describe the bug**
Attribute `selected` is not honored in `Choice`. I am using the latest installable pip version.

**To Reproduce**
1. `pip install label-studio`
2. Use the following template for the task:

```
<View>
  <Choices name="whatever" toName="txt-1" choice="single">
    <Choice value="A" selected="true" />
    <Choice value="B" />
  </Choices>
  <Text name="txt-1" value="John went to see Marry" />
</View>
```

**Expected behavior**
I am expecting to see option `A` being pre-selected / toggled.

**Comment by makseq** [comment]
Seems like a bug. We will fix it soon

**Comment by makseq** [comment]
It's fixed after 0.8.1 release.

**Comment by nopper** [comment]
It looks like there is still a bug with the current behavior and the way it interacts with `predictions` (https://labelstud.io/guide/export.html#predictions), when this information is set in the task.

That is the `selected` property seems to take priority and trumps the selection of the predicted choice.

**Comment by hlomzik** [comment]
@nopper checked this — predefined choices are set only if this is "new" annotation and it takes this "new" status from `id` field of prediction, so if you don't have this field, the choice will be preselected as in config. And as I know `id` field is required anyway, there are some other possible issues if you miss it.
Is this the problem you have or there is something else?

**Comment by nopper** [comment]
Not exactly the problem is that if you have a config like the one above:

```
<View>
  <Choices name="whatever" toName="text" choice="single">
    <Choice value="A" selected="true" />
    <Choice value="B" />
  </Choices>
  <Text name="txt-1" value="John went to see Marry" />
</View>
```

And then a simple task with some pre-existing predictions provided by a ML backend like this one:

```
...
    "predictions": [
      {
        "created_at": 1606759077,
        "id": 1,
        "lead_time": 6.666,
        "result": [
          {
            "from_name": "whatever",
            "id": "0",
            "to_name": "text",
            "type": "choices",
            "value": {
              "choices": [
                "B"
              ]
            }
          }
        ]
      }
    ]
...
```

The choice A will be selected (the one with attribute `selected="true"`) during labeling phase instead of choice B (the one predicted by the ML model, which IMHO should take precedence here).

**Comment by makseq** [comment]
@hlomzik Check it please.

**Comment by hlomzik** [comment]
Check it with `"id": "1"`, please

**Comment by beatanyari** [comment]
Hi, is there any update on this? I'm using the span labeling template and running into a similar issue. The box doesn't get pre-checked, no matter if the class is provided as `selected = "true"` or in the JSON data.

**Comment by makseq** [comment]
@beatanyari It was fixed long time ago. Could you check the latest master of LS github repo?

**Comment by beatanyari** [comment]
Doesn't work with the latest master either. If I add `selected="true"` to one of the choices in the ["Text spans labeling" template](https://labelstud.io/playground/), the choice doesn't get pre-selected.

**Comment by makseq** [comment]
@beatanyari Thank you for your report. You are right, it's broken again. Created a ticket about this bug.

**Comment by makseq** [comment]
relative: https://github.com/heartexlabs/label-studio/issues/2130
