### ISSUE TITLE
How to launch label studio on Windows

### ISSUE THREAD

**Issue by HencyChen** [heartexlabs/label-studio#462]
Thanks for providing such wonderful tools for labeling. I have a dump question about how to launch the app on windows. I've already installed the app correctly following github tutorial, and I'm trying to open Windows PowerShell to open the app. 

Thanks for helping !

**Comment by kasuteru** [comment]
Did you make sure the installation runs through correctly? Notice that sometimes errors occur during installation, e.g. cargo path not found or libraries missing.

https://labelstud.io/guide/#Running-with-pip

If installation indeed ran through correctly, see the documentation and run:

        label-studio start my_project --init

If this doesn't work, we need more information on what went wrong, e.g. error messages.

**Comment by HencyChen** [comment]
Dear @kasuteru ,

Thanks for the reply. I think the installation is correct, since the final information is the "label-studio is installed successfully".

So do you mean to type "label-studio start my_project --init" in PowerShell?

**Comment by kasuteru** [comment]
Yes. If Powershell does not work, try cmd so that we now more.

Po-Heng Chen <notifications@github.com> schrieb am Do., 22. Okt. 2020,
09:37:

**Comment by HencyChen** [comment]
The problem is solved by following "local host part" in the github
