### ISSUE TITLE
Completions comparison is not working on labelling page

### ISSUE THREAD

**Issue by ghanshyamdev** [heartexlabs/label-studio#463]
**Describe the bug**
I've completed `2 completions`, and when I tried to compare both the completions then I'm not able to see the comparison for completions.
**To Reproduce**
1. Create `Named entity recognition project`
2. Import sample tasks
3. Perform some completions
4. Try to compare the completions
5. Comparision not working

**Screenshots**
## Completions
![Screenshot_1](https://user-images.githubusercontent.com/45035063/96830814-a05c9900-1459-11eb-91a5-7bb5cab31e1f.png)

## Comparision
![image](https://user-images.githubusercontent.com/45035063/96830922-cd10b080-1459-11eb-9200-b066902432a7.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version: [sample app](https://app.labelstud.io/tasks) and `master` branch of LSF and also tested with the latest `master branch` LS

**Additional context**

**Comment by makseq** [comment]
@ghanshyamdev Yes, we are working on it already, but it takes some time.

**Comment by ghanshyamdev** [comment]
Thanks for your time @makseq, One more thing to mention that completion comparison is not working with all the different types of configs.

**Comment by makseq** [comment]
@ghanshyamdev It's fixed after 0.9.0rc0. There is release candidate version with a lot of changes in LS engine and data manager. But you could try it if you really need completion comparison mode.

**Comment by ghanshyamdev** [comment]
Thank you, you’re amazing! @makseq :)
