### ISSUE TITLE
Unable to display multiple entity predictions

### ISSUE THREAD

**Issue by sagarmk** [heartexlabs/label-studio#465]
**Describe the bug**
I am using the NER labeling configuration and am unable to display all predicted labels back to the labeling task.

**To Reproduce**
This is my prediction json:

`[{'result': [{'value': {'start': 74, 'end': 77, 'text': 'the', 'labels': ['B-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.007846807291408187}, {'result': [{'value': {'start': 78, 'end': 84, 'text': 'Eighth', 'labels': ['I-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.09022461136845028}, {'result': [{'value': {'start': 78, 'end': 84, 'text': 'Eighth', 'labels': ['I-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.5405680728536595}, {'result': [{'value': {'start': 78, 'end': 84, 'text': 'Eighth', 'labels': ['I-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.9590188407351059}, {'result': [{'value': {'start': 74, 'end': 77, 'text': 'the', 'labels': ['B-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.6662584887354467}, {'result': [{'value': {'start': 78, 'end': 84, 'text': 'Eighth', 'labels': ['I-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.01752317346211263}, {'result': [{'value': {'start': 78, 'end': 84, 'text': 'Eighth', 'labels': ['I-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.9649109626149007}, {'result': [{'value': {'start': 78, 'end': 84, 'text': 'Eighth', 'labels': ['I-ORG']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.9074288404729026}, {'result': [{'value': {'start': 183, 'end': 186, 'text': 'the', 'labels': ['B-EVENT']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.4013598897365015}, {'result': [{'value': {'start': 187, 'end': 194, 'text': 'Hundred', 'labels': ['I-EVENT']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.014944580851937728}, {'result': [{'value': {'start': 187, 'end': 194, 'text': 'Hundred', 'labels': ['I-EVENT']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.6445915392368938}, {'result': [{'value': {'start': 187, 'end': 194, 'text': 'Hundred', 'labels': ['I-EVENT']}, 'from_name': 'label', 'to_name': 'text', 'type': 'labels'}], 'score': 0.6656635828767326}]`

In this only the first entity is getting tagged in the labeling task

**Expected behavior**
All the entities predicted should be tagged back

<img width="1092" alt="screenshot_labelstudio" src="https://user-images.githubusercontent.com/4992875/96889992-cd567f00-144c-11eb-98b6-b37c442db0d5.png">

**Comment by bocharm** [comment]
Hello, @sagarmk 
I have same issue like this. Did you solve it?
Thank you in advance

**Comment by bocharm** [comment]
oh, I solved this issue
FYI, to be same as completion format, "result" should be the "list of dictionary" that holds each entity prediction
