### ISSUE TITLE
I'd just created my own machine learning backend and start it, but the port isn't showing up

### ISSUE THREAD

**Issue by laurence-lin** [heartexlabs/label-studio#466]
Hello! I'd successfully open the localhost 8080 on my computer and tested for the work. Now that I'm trying to build my own machine learning backend, I tried to customize a model.py file from the document example like this: 
https://github.com/laurence-lin/labelstudio/blob/main/model.py

After that, I go to the directory and initialize backend by `label-studio-ml init my_backend`
and then start by: `label-studio-ml start my_backend --force`

The message in command line shows like this:

![image](https://user-images.githubusercontent.com/19323465/96974690-29ec9380-154c-11eb-9bcf-4232e5bfc538.png)

But the port didn't open automatically, and when I pasted the 9090 port to browser it shows nothing. What's happening? Is my model.py file have problems with it?

**Comment by kasuteru** [comment]
I feel like we can't help you there without you providing additional information... At least your model.py, what environment you are running in, etc...

**Comment by laurence-lin** [comment]
> I feel like we can't help you there without you providing additional information... At least your model.py, what environment you are running in, etc...

My model.py is presented in the link above. I was working on Windows 10 with Python 3.8.
I installed label-studio via this command:
![image](https://user-images.githubusercontent.com/19323465/96990984-67f0b400-155a-11eb-8455-d864693d6fb6.png)

Then I start to work with tutorials of building machine learning framework via this link:
https://labelstud.io/tutorials/dummy_model.html

I adjust the model.py file as the link in the origin post, and when I run `label-studio-ml start my_backend`

The error shows as in the post.

**Comment by makseq** [comment]
Have you connected your ML backend to LS on Model page?

**Comment by laurence-lin** [comment]
> Have you connected your ML backend to LS on Model page?

Yeah! I forgot about that, it's solved. Thank you!
