### ISSUE TITLE
Audios not loading when upgrading from v1.7.2 to higher versions.

### ISSUE THREAD

**Issue by javanton** [heartexlabs/label-studio#4661]
Hello, 

We tried to **upgrade from v1.7.2 to v1.8.1** and when doing it, the audios are not being loaded when entering project annotations. Audios are deposited in S3 and the credential is a static credential that is not expiring.

I attach a screenshot of the problem we have encountered, that has been mitigated rolling back to v1.7.2 and not performing any change. **We also tried to roll back to v1.7.3, and same error appeared**, which was strange for us, since it is a patch change in version.

No errors are found in kubernetes deployment, but rather on the web client we are accessing to label studio with (Screenshot 2). 

**Screenshots**
![Captura desde 2023-08-21 11-27-36](https://github.com/HumanSignal/label-studio/assets/36293800/c2bd6c78-70ec-4bc2-ad7e-e378e0e21900)

![image](https://github.com/HumanSignal/label-studio/assets/36293800/5c287c4a-0783-467b-9968-92cbdcfe30f3)

Could you help us understand what is happening? Currently we are ok using this version but we plan to upgrade to higher versions in the future.

**Comment by javanton** [comment]
I have discovered that it is a potential issue with the view. 

If I get the URL using right click->Copy link address and then pasting it into the browser, I get to the audio, but when I click directly on the link appearing below `Technical description`, I am not able to retrieve the audio.

The audio also loads in the preview (left part):
![image](https://github.com/HumanSignal/label-studio/assets/36293800/aa1fb904-c0d5-42e0-be47-114d287b4799)


What can this happen? I don't have any clue...

**Comment by hogepodge** [comment]
@AbubakarSaad @TylerConlee can you create an issue to investigate this problem?
