### ISSUE TITLE
Training is displayed as in progress even when its complete

### ISSUE THREAD

**Issue by sagarmk** [heartexlabs/label-studio#468]
**Describe the bug**
The backend shows that the training is in progress, even when its complete, it never turns complete

**To Reproduce**
This happened while using two deep learning models, one using Bert and spacy
Also happened with the sample code provided as sample here:
https://github.com/heartexlabs/label-studio-transformers/blob/master/models/ner.py

**Expected behavior**
Completed training should be reflected back 

**Screenshots**
![image](https://user-images.githubusercontent.com/4992875/97068354-4ad4d900-158c-11eb-84f7-e0ce1880bc0a.png)

**Environment (please complete the following information):**
 - mac os 10.14
- chrome browser Version 86.0.4240.75

**Comment by makseq** [comment]
What if you will refresh the page?

**Comment by Pradip2205** [comment]
Even I am facing the same issue.

**Comment by sagarmk** [comment]
Hey guys got update from labelstudio team.

This behaviour is as expected, there isn't any ajax reload, you can manually reload the page and check if its done or not. Also the logs should give you an idea.
