### ISSUE TITLE
Tasks path / Completion path not fully shown if long

### ISSUE THREAD

**Issue by kasuteru** [heartexlabs/label-studio#471]
This is probably trivial to solve, but I don't want to mess with the front-end code too much:

When using a long path (as is often the case with ADLS storage), the full path is not displayed any more.

Edit: In case it is not obvious (maybe not the best screenshot): The path does not end after "user", it goes on, but this is not shown any more.

![image](https://user-images.githubusercontent.com/16296708/97189937-71219100-17a5-11eb-8666-a18fda26cb35.png)

**Comment by makseq** [comment]
I made short version for paths, check this branch: 
https://github.com/heartexlabs/label-studio/pull/472
