### ISSUE TITLE
Some bugs for visual genome template

### ISSUE THREAD

**Issue by jihwanp** [heartexlabs/label-studio#4724]
**Describe the bug**
When I started the project with visual genome templates, there were so many blank labels in regions, and image was not displayed as in Expected behavior. Other templates seem to work fine except for the visual genome.

**To Reproduce**
I follow the installation from the local pip and start with visual genome templates.

**Expected behavior**
As in UI preview
![image](https://github.com/HumanSignal/label-studio/assets/70801434/8a181521-b9e9-4c7c-b3fe-14c163283f03)

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/70801434/2adcedab-21b4-4880-b741-4c1244524678)

**Environment (please complete the following information):**
 - OS: Linux
 - Label Studio Version 1.8.3.dev0

**Additional context**
None

**Comment by mypydl** [comment]
same bug
windows11 / ubuntu2204(wsl2)
LS ver: 1.11/1.9

**Comment by kamalmalikofficial** [comment]
same bug still in 2025 
windows 11
