### ISSUE TITLE
Cannot find skip button

### ISSUE THREAD

**Issue by iinntteerrnn** [heartexlabs/label-studio#473]
**Describe the bug**

Hi, I can't find the skip button on my local project
I have never been like this and i don't know how to activate the skip button

How can I activate it?
![image](https://user-images.githubusercontent.com/70555571/97382351-8960ef80-190e-11eb-9c88-a9b86215dfae.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**

**Additional context**

**Comment by makseq** [comment]
On what page did you try to find the skip button?

**Comment by iinntteerrnn** [comment]
> On what page did you try to find the skip button?

On Task tab. but Nikolai Liubimov told me about latest update on Slack, thanks
