### ISSUE TITLE
Brush and Polygon Segmentation Loading Time 

### ISSUE THREAD

**Issue by anshul-dt** [heartexlabs/label-studio#476]
**Describe the bug**
After Labeling Brush and Polygon, the loading time in tasks is huge, could take upto minutes sometimes. 

**To Reproduce**
1. Label an image with Polygon or Brush segmentation, submit
2. Go to Tasks and try to load the image
3. You will observe that it takes a huge time to load (2-3 minutes sometimes) 

**Expected behavior**
Should Load quickly 

**Environment (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Browser: Chrome, Firefox, Safari

**Comment by makseq** [comment]
@anshul-dt What storage do you use? Is it s3, gcs or local?

**Comment by anshul-dt** [comment]
local

**Comment by makseq** [comment]
What is this LS version?

**Comment by anshul-dt** [comment]
0.7 and 0.8

**Comment by makseq** [comment]
I've checked it here: https://app.labelstud.io/api/project-switch?uuid=83ce5d2f-61b3-4409-ac30-863ae7f0d741
And polygons work fast enough. Brushes can be not too fast if there are a lot of strokes (RLE is a heavy format). 
I think it will be easier to find the problem if you record video.

**Comment by tristanratz** [comment]
I had the same problem. Only thing that worked for me was downsampling the photos to a smaller shape

**Comment by makseq** [comment]
@tristanratz What image sizes do you have?

**Comment by tristanratz** [comment]
My images are sized 700px on the x-axis and dynamically on the y axis (according to the ratio)

**Comment by hlomzik** [comment]
Hi! That's sad, but currently brushes are not optimized, so their speed and size are badly depend on the image size (more specifically, number of pixels). So if it's possible to downsample your images, that's a good temporary solution.
I'm working on optimization, which increase speed significantly, will be released soon.
Sorry for inconvenience.

**Comment by smoreface** [comment]
This should be fixed with [version 1.3.0 release](https://github.com/heartexlabs/label-studio/releases/tag/v1.3.0), please try it out!

**Comment by vchaparro** [comment]
Hi,

I'm using version 1.7.2, and it seems that the issue has not been resolved. I am using images of approximately 1500x1500 (around 5 MB) with segmentation polygons. When attempting to open these pre-labeled images, which have a relatively high number of polygons per image (it's about buildings footprint segmentation), it takes too long to open. Additionally, the user experience suffers when transitioning from one image to the next, zooming, and so on. The client-side web browser begins to consume high CPU resources.
