### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by cobac** [heartexlabs/label-studio#4769]
Can I ask you to tag a new _(minor, whatever)_ release? I would like to pin a dependency to label-studio with https://github.com/HumanSignal/label-studio/commit/0caeaf01f4b0413332bd0bdcb8db9a4550ae80a8#diff-662d879fc60dc3cadd50fb1dbf49fdd8bd54c912820f5093a7167a8cfa39ec52L49-L55 `python_dateutil>=2.8.1` merged to solve a dependency conflict.

Right now it's conflicting with Pandas when using a strict dependencies resolver (e.g. poetry).

**Comment by cobac** [comment]
Reopening. I assumed 1.8.2.post0 was tagged on `develop`, but nope.

**Comment by jombooth** [comment]
Hi @cobac, thanks for raising this issue! We didn't include the commit you linked in 1.8.2.post0, but will be releasing version 1.9 as soon as tomorrow, which will include it.

**Comment by jombooth** [comment]
Hi @cobac.

We're still working on 1.9.0, but in the meantime, we've released [1.8.2.post1](https://github.com/HumanSignal/label-studio/releases/tag/1.8.2.post1) with a hotfix for the requirements issue you identified. Thanks for using Label Studio!

**Comment by cobac** [comment]
Great, thanks!
