### ISSUE TITLE
NER Tokenization

### ISSUE THREAD

**Issue by david-waterworth** [heartexlabs/label-studio#477]
Is it possible to supply a custom tokenizer for NER. I've been evaluating `Prodigy` and used the huggingface tokenizers library to tokenizes my examples before annotation. In my case I cannot use a "word" based tokenizer - i.e. I have AHU-G1-V-1-1-Ctrl-Out, which I tag "AHU-G1-V-1-1" and "Ctrl-Out". I composed a tokenizer that splits on spaces, punctuation, and numbers and then uses BPE. So I get something like "AHU" "-" "G" "1" "-" "V" "-" "1" "-" "1" "-" "Ctrl" "-" "Out"

`Prodigy` ensures that the selected text always aligns to token boundaries so it's easy to select AHU-G1-V-1-1 and then map to BIO tags (which obviously are token based). They do this by creating a pipeline that adds tokens and other metadata to each example before it's processed by the UI.

`label-studio` seems to work at the character level, i.e. I can select any span of characters including mid-token, can I prevent this? I guess I can convert from a character span to a token span and then to BIO (i.e. select any token which overlaps with a selected character)?

**Comment by makseq** [comment]
Right now LS supports two modes of text selection - per word and per symbol. The property is called "granularity" in Text tag - https://labelstud.io/tags/text.html#Parameters
