### ISSUE TITLE
Labelling Interface does not load

### ISSUE THREAD

**Issue by emcgrath01** [heartexlabs/label-studio#4771]
**Describe the bug**
Labelling interface will not load.

**To Reproduce**
I have been labelling data for several days, the data still loads when I click on the project but when I click on individual data points or select 'label all tasks', nothing loads.  No errors are given.

**Expected behavior**
I would expect to see the data point to label and the labelling interface (in this case multiple choice labels)

**Environment (please complete the following information):**
 - OS: [iOS]
 - Label Studio Version [1.8.2

**Comment by hogepodge** [comment]
@emcgrath01 we're not able to reproduce this issue,
