### ISSUE TITLE
I need to annotate  rotated bounding boxes that exceed the image range

### ISSUE THREAD

**Issue by zytx121** [heartexlabs/label-studio#4775]
**Is your feature request related to a problem? Please describe.**
I need to annotate rotated bounding boxes that exceed the image range. However, the rotation box cannot be dragged beyond the image range.

**Describe the solution you'd like**
Unlimit the drag range of the rotated bounding box.

**Describe alternatives you've considered**
Not yet.

**Additional context**
![1694601564001](https://github.com/HumanSignal/label-studio/assets/10410257/429e4108-d677-4fb3-a205-176d504f9cea)

**Comment by AbubakarSaad** [comment]
Hello Zytx121, 
<img width="1145" alt="Screenshot 2023-09-18 at 10 09 26 PM" src="https://github.com/HumanSignal/label-studio/assets/4449857/ae1ce519-dd20-45ff-a703-b8493f605033">


How far off image are you planning to go? I got it up to image as height is.

**Comment by victoriaagj** [comment]
Hi! I have the exact same request! I this matter solved?
