### ISSUE TITLE
server.json is overwritten by parse_input_args?

### ISSUE THREAD

**Issue by kasuteru** [heartexlabs/label-studio#478]
**Describe the bug**
It looks like any server config provided in server.json is overwritten in server.main() by parse_input_args.

Detailed:
Here, server.json is parsed to global input_args:
https://github.com/heartexlabs/label-studio/blob/1f8974514ac76087eb34ffba855a570c84612da0/label_studio/server.py#L79-L86

However, here, it is overwritten in main():

https://github.com/heartexlabs/label-studio/blob/1f8974514ac76087eb34ffba855a570c84612da0/label_studio/server.py#L1100-L1104

I tested this and it looks like server.json, if provided, does nothing since it is simply overwritten.

In addition, when hosting label-studio from e.g. gunicorn instead over label-studio start, _all_ arguments have to be provided in server.json currently. This makes configuring over server.json complicated. 

I would try to tackle both issues and write a PR in the next days.

**Comment by kasuteru** [comment]
Feel free to assign this issue to me.

Also, I accidentally sent this issue early before finishing the text, sorry about that.

**Comment by makseq** [comment]
@kasuteru I recommend you to wait a little bit more until we release a new commit with API refactoring. There will be a lot of changes inside of blueprint.py (ex. server.py).

**Comment by makseq** [comment]
Feel free to reopen if you have this problems again.
