### ISSUE TITLE
), or review the [existing ones](https://github.com/heartexlabs/label-studio/issues

### ISSUE THREAD

**Issue by MohammadRezaHosseinian** [heartexlabs/label-studio#4790]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AbubakarSaad** [comment]
Hello MohammadRezaHosseinian,

I'm closed this issue as there isn't enough description about anything in there. Please reopen issues with some context and description of the problem
