### ISSUE TITLE
There was an issue loading URL from $csv value. Most likely that's because static server has wide-open CORS. Read more on that here.

### ISSUE THREAD

**Issue by tibhar940** [heartexlabs/label-studio#481]
**Describe the bug**
Can't open uploaded file from host

**To Reproduce**
1. I'm starting project `label-studio start {project}`
2. After that label studio url is reachable from another hosts
3. But on another host it can't open files for labeling with this error

> There was an issue loading URL from $csv value. Most likely that's because static server has wide-open CORS. Read more on that here.
> 
> Also check that:
> 
> URL is valid
> Network is reachable
> URL: http://localhost:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv

**Environment **
 - OS: WIndows
 - Browser: chrome
 - Version: latest

**My config for project**

`<View>
    <Header value="Time Series from CSV" style="font-weight: normal"></Header>

    <TimeSeriesLabels name="label" toName="ts">
        <Label value="-1" background="red"></Label>
        <Label value="+1" background="green"></Label>
    </TimeSeriesLabels>

    <TimeSeries
            name="ts"
            valueType="url"
            timeColumn="tradedate"
            value="$csv"
            sep=","
            timeFormat="%Y-%m-%d"
            timeDisplayFormat="%Y-%m-%d"
            overviewChannels="waprice"
    >
        <Channel
                column="waprice"
                strokeColor="#1f77b4">
        </Channel>
        <Channel
                column="val"
                strokeColor="#ff7f0e">
        </Channel>
    </TimeSeries>
</View>
`

**Comment by makseq** [comment]
@tibhar940 What if you open csv link directly? 
`http://localhost:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1csv` 

I see there is no dot before csv in this URL, it's a little bit strange..

**Comment by tibhar940** [comment]
@makseq  Sorry, my fault. Fixed.

**Comment by makseq** [comment]
Does it resolve this issue?

**Comment by tibhar940** [comment]
@makseq  No, it was a problem then I write an example.

**Comment by makseq** [comment]
Ok. So, what if you open csv link directly?
`http://localhost:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv`

**Comment by tibhar940** [comment]
@makseq  I also add my config file

**Comment by tibhar940** [comment]
@makseq I can open csv directly from localhost, but can't from another. Host http://{SERVER}:8080 reachable, but I got error with this file `http://localhost:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv` . But (I guess) it should open `http://{SERVER}:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv`
I tried to open `http://{SERVER}:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv` directly and it works

**Comment by makseq** [comment]
Try to run LS with --host {SERVER}. Will it fix this issue?

**Comment by tibhar940** [comment]
@makseq  No, the same error

**Comment by makseq** [comment]
Is {SERVER} an ip address?

**Comment by tibhar940** [comment]
@makseq Yes.

**Comment by makseq** [comment]
I'll check it and will be back.

**Comment by tibhar940** [comment]
I started server on IP_1, and try to open from another machine (IP_2)

**Comment by makseq** [comment]
I think the solution for right now is to open `your_project/tasks.json` and change all paths like 
```
http://localhost:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv
```
to 
```
http://{SERVER}:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv
```

Plus you need to use `--host={SERVER}` in `label-studio start your_project --host={SERVER}`. 

I think you used `--host` after the file import and path was formed as `http://localhost:8080/data/...` instead of `http://{SERVER}:8080/data/...`.

**Comment by tibhar940** [comment]
@makseq Is it necessary to use quotes in this command? `label-studio start your_project --host={SERVER}`?

**Comment by tibhar940** [comment]
> I think the solution for right now is to open your_project/tasks.json and change all paths like
> 
> http://localhost:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv
> to
> 
> http://{SERVER}:8080/data/upload/23a6a3ba2a65dde741c97818c0f586e2-file_1.csv
> 
I replaced and it works!

**Comment by makseq** [comment]
Do you use --host option now? And have you check a new import for file?

**Comment by tibhar940** [comment]
@makseq  Yes, used. No, haven't. I'll check now.

**Comment by tibhar940** [comment]
Well.

1. I started server on IP_1 with --host option
2. Open http://{IP_1}:8080 from IP_2 and import task files
3. When open labeling from IP_2 and all works fine
4. After that I checked {PROJECT}/tasks.json on IP_1 and all urls was just as I expected.

**Comment by makseq** [comment]
Well! So, have your issue been fixed?

**Comment by tibhar940** [comment]
@makseq Thank you!

**Comment by nopper** [comment]
Is it possible to allow CORS when using label studio? I am having the same issue because my tasks contains external URLs. This is the error that I get:

![image](https://user-images.githubusercontent.com/129937/99886774-6e4c7b80-2c3f-11eb-8c2d-8e99c4b6c024.png)

If I click on the `Read more on that here` link the suggested solution is to use ngnix as a proxy server to bypass CORS. Wouldn't be possible to just allow CORS in the `blueprint.py`, something like this (maybe flag guarded somehow):

```python
@blueprint.after_request
def after_request(response):
    header = response.headers
    header['Access-Control-Allow-Origin'] = '*'
    return response
```

I'd prefer to avoid having to install nginx to address this issue.

**Comment by makseq** [comment]
Where are the files, which the links lead to, stored? The CORS is the problem of the external server where the files are stored. It's not LS problem..

**Comment by nopper** [comment]
Oh yes! sorry you are right. My bad. I had to configure the other server to return CORS headers. Now everything works fine. Please ignore my previous comment.
