### ISSUE TITLE
Is there a way to customize plots in timeseries labeling?

### ISSUE THREAD

**Issue by tibhar940** [heartexlabs/label-studio#482]
I tried the basic solutions with timeseries labeling according to this example https://labelstud.io/blog/release-080-time-series-labeling.html

Could I somehow add custom type of plots (eg. area plots, barplots), customize linestyle, use custom markers, etc?

**Comment by makseq** [comment]
Type of plots is not supported now. You can customize line width and color (strokeColor). These params you can find in docs about TimeSeries tags: https://labelstud.io/tags/timeseries.html

**Comment by tibhar940** [comment]
@makseq It would be great if customization of plots will be supported in future releases. Thank you.

**Comment by makseq** [comment]
Got it! :+1:
