### ISSUE TITLE
A view that allows grouping images into a thread

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [heartexlabs/label-studio#4825]
**Is your feature request related to a problem? Please describe.**
I have 200,000+ images. On a file system (and cloud storage) they are sorted using directories. The directory structure is lost (flattened) in the "List" and "Grid" views. 

**Describe the solution you'd like**
Similar to a file explorer or an email client like Thunderbird or Outlook, images should be groupable into directories or threads.
This could be a different view from the List view or, added feature to the List view.

**Describe alternatives you've considered**
The storage filename column contains the original directory structure but cannot currently filter on it (#4824).

**Comment by hogepodge** [comment]
@sheldonmaschmeyer thanks for your feature request. I'll bring this to the product team.

**Comment by hogepodge** [comment]
Fixed upstream, this should be available in an upcoming Label Studio release (likely 1.10.3+, since this patch was added after the 1.10.2 cut)
