### ISSUE TITLE
Automatic labelling of the same text in NER

### ISSUE THREAD

**Issue by sathiyabalu89** [heartexlabs/label-studio#484]
**Is your feature request related to a problem? Please describe.**
I am using NER annotation for chemical documents. There would be many repeated chemical formulas each of which I should annotate. For example I should annotate each 'CA' as formula even if it appears 100 times in the document

**Describe the solution you'd like**
Is it possible to add button/feature like "mark all" ? with this option if a text "CA" is labelled, all remaining text "CA" should also be automatically annotated with the label. 

**Describe alternatives you've considered**
As of now doing it manually. Rather planning to programmatically handle the exported JSON.

**Comment by makseq** [comment]
@sathiyabalu89 you can achieve this using ML backend with simple heuristic rules on predictions stage (you don't need to train anything). Check this docs: https://labelstud.io/guide/ml.html

**Comment by sathiyabalu89** [comment]
I am using label-studio==0.7.5.post2. Thank you for the link, will check it.
