### ISSUE TITLE
v1.9.0 regression: predictions are not shown when labeling images for an machine vision object detection task

### ISSUE THREAD

**Issue by davidblom603** [heartexlabs/label-studio#4844]
**Describe the bug**
When using the button "Label All Tasks" , the predictions are not shown. This used to work with v1.8.0.post2. When clicking directly on an image (so not using the button label all tasks), the predictions are shown.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

**Comment by hogepodge** [comment]
@davidblom603, thanks for your bug report. Unfortunately, we aren't able to reproduce this issue with the information given. In general we require the labeling configuration, the configuration you're using to generate predictions, and data to recreate the conditions you're experiencing the problem with.

**Comment by WillieMaddox** [comment]
I Have the same issue after upgrading from 1.8.2 to 1.9.2.  Clicking on "Label All Tasks" or "Label Tasks As Displayed" shows the image, but not the predictions.  If I click "back" to the previous task and then click "forward", the prediction appears. Predictions are also not being displayed for Tasks appearing after clicking "Submit".  For predictions generated prior to the upgrade, I have observed this issue in the following two situations:
  1. Predictions generated using the ML backend, and
  2. Predictions generated offline and then pushed to Label-Studio via the API. 

Note that in both cases the observations were made with the ML backend turned OFF.

With it turned on, the backend generates predictions regardless of whether or not the task already has them. In previous LS versions this was not the case; the task would simply show the most recent prediction and only call the backend if there weren't any.  I also tried setting the model version to match the existing predictions but that had no effect.

The Back/Forward trick works but is cumbersome.  This is definitely a bug.

**Comment by davidsblom** [comment]
Hi @hogepodge ,

Here is the labeling config:
```
<View>
  <View style="display:flex;align-items:start;gap:8px;flex-direction:column-reverse">
    <Image name="image" value="$image" brightnessControl="true" contrastControl="true" negativeZoom="true" zoom="true" zoomControl="true"/>
    <View>
      <Header value="Bounding box labels"/>
      <Filter toName="label" minlength="0" name="filter"/>
      <RectangleLabels name="label" toName="image" showInline="true">
        <Label value="class1"/>
        <Label value="class2"/>
        <Label value="class3"/>
        <Label value="class4"/>
        <Label value="class5"/>
        <Label value="class6"/>
        <Label value="class7"/>
        <Label value="class8"/>
        <Label value="class9"/>
        <Label value="class10"/>
        <Label value="class11"/>
        <Label value="class12"/>
        <Label value="class13"/>
        <Label value="class14"/>
        <Label value="class15"/>
        <Label value="class16"/>
        <Label value="class18"/>
      </RectangleLabels>
      <Header value="Instance Segmentation labels"/>
      <BrushLabels name="tag" toName="image">
        <Label value="class1"/>
        <Label value="class2"/>
        <Label value="class3"/>
        <Label value="class4"/>
        <Label value="class5"/>
        <Label value="class6"/>
        <Label value="class7"/>
        <Label value="class8"/>
        <Label value="class9"/>
        <Label value="class10"/>
        <Label value="class11"/>
        <Label value="class12"/>
        <Label value="class13"/>
        <Label value="class14"/>
        <Label value="class15"/>
        <Label value="class16"/>
        <Label value="class18"/>
      </BrushLabels>
      <Header value="$image_hash"/>
    </View>
  </View>
</View>
```
Is this sufficient info?

**Comment by doantientai** [comment]
In [this issue](https://github.com/HumanSignal/label-studio/issues/5032), @jombooth said they are working on it.
