### ISSUE TITLE
CSV Export does not have any mapping with Label studio portal. 

### ISSUE THREAD

**Issue by Rishabh-hyperverge** [heartexlabs/label-studio#485]
**Describe the bug**
CSV generated through label studio export feature does not contain any task-id, any other mapping to link annotations on the portal. It only has an Image column which is a URL to the image, but one filter task by image URL on the portal. It would require task-id.

**To Reproduce**
1. Export the annotations as CSV.
2. Check for columns in the CSV.

**Expected behavior**
there should be a Task-ID column, task URL in the CSV.

**Comment by makseq** [comment]
@Rishabh-hyperverge I'll try to fix it soon

**Comment by makseq** [comment]
@Rishabh-hyperverge Can you check the last commit from master of https://github.com/heartexlabs/label-studio-converter ? I hope it's fixed now.

**Comment by niklub** [comment]
Hi, @Rishabh-hyperverge ! 
The issue has been resolved in `label-studio==0.8.1`. Now you should be able to see task IDs in exported CSV file. Please, check it and reopen the issue if the error persists on your side.
