### ISSUE TITLE
Is it possible to implement label-studio in a jupyterlab?

### ISSUE THREAD

**Issue by Chaouabti** [heartexlabs/label-studio#4852]
I would like to know if it is possible to install label studio in a JupyterLab server on the server itself. 
The idea is to be able to process data and annotations directly from JupyterLab without going through the local machine. 

If this is possible, how can I implement it?

**Comment by hogepodge** [comment]
Thanks for your request @Chaouabti. Launching Label Studio from Jupyter is not a supported configuration, and is not on our feature roadmap. You can use the Label Studio API and SDK to automate a number of annotation tasks from other platforms. Thank you for your feedback.
