### ISSUE TITLE
S3 Storage: Support AWS Signature Version 4 query parameters 

### ISSUE THREAD

**Issue by darthhexx** [heartexlabs/label-studio#4868]
**Is your feature request related to a problem? Please describe.**

When setting `STORAGE_TYPE=s3` the requests to `/storage-data/uploaded/?filepath=upload/1/somefile` result in generated URLs for AWS presigned with the old format: `URL?AWSAccessKeyId=AKIA...redacted...&Signature=F1H25pgUkZwDhV0S2b%2F48rPibWk%3D&Expires=1696592186`.

This is due to this call to [the Django S3Boto3Storage class](https://github.com/HumanSignal/label-studio/blob/154ac5df133dd037671f0e7c5c4f9de3d8126c3f/label_studio/core/storage.py#L66) and, because the setting for the signature version in the [Django setting AWS_S3_SIGNATURE_VERSION](https://github.com/jschneier/django-storages/blob/37a40a6565e93a4265a00acd7d210f4ace093c41/storages/backends/s3.py#L351) is `None`, the old signature version is being used.

**Describe the solution you'd like**

We should introduce an environment variable that enable us to override the setting to `s3v4`, the only supported version in AWS S3, but keeps the existing behaviour by default so as not to break existing setups.

**Describe alternatives you've considered**

I think this is the best option, as it keeps the existing behaviour but allows it to be overridden to the latest version.

**Comment by hogepodge** [comment]
Thanks for catching this. I'll bring it to the engineering team to get the work scoped out.

**Comment by darthhexx** [comment]
Thanks @hogepodge. I have a proposed fix in https://github.com/HumanSignal/label-studio/pull/4869 that I am using in my deployment, which works as expected.

**Comment by bmartel** [comment]
Thanks a bunch @darthhexx. This has been merged back in, closing this issue!
