### ISSUE TITLE
Textarea tags remove all newline character if any editing is conducted

### ISSUE THREAD

**Issue by heartcored98** [heartexlabs/label-studio#487]
**Describe the bug**
I am working with the pre-filled textarea tag with certain text. 
Annotator has to make some change on those pre-filled text in the textarea.

However, whenever any key stroke is pushed while the textarea is in the editing mode, 
all the newline character is removed. 

Also, I figured out that current text area cannot contain newline character when it is in the editing mode.
I think textarea considers 'enter' key as the escaping editing mode command. 

**To Reproduce**
1. Make any textarea tags
2. Add new submission with the text contains newline character (\n)
3. Click pencil icon to enter editing mode
4. Press any key then the newline characters are removed
5. If we press the 'Enter' key in order to make newline, editing mode is terminated. Therefore, we cannot append additional new line. 

**Expected behavior**
1. Newline characters should not be removed during the editing mode
2. Newline characters could be inserted during the editing mode

**Screenshots**
![image](https://user-images.githubusercontent.com/33013451/98658861-dde08200-2386-11eb-8195-4edc9b4af390.png)
Submitting text with multiple newline : ok

![image](https://user-images.githubusercontent.com/33013451/98658942-f94b8d00-2386-11eb-9737-664822f42fd3.png)
But whenever click the pencil icon and try to edit and press any key, all the text turned into single line. 

**Environment (please complete the following information):**
 - OS: Mac
 - Browser chrome, safari (both browser show same issue)
 - Version 86 chrome

**Comment by makseq** [comment]
@heartcored98 What LS version do you use?

**Comment by heartcored98** [comment]
@makseq 

I am using 0.7.5.post0 version LS :)

**Comment by makseq** [comment]
@heartcored98 Try 0.8.0, will this bug there?

**Comment by heartcored98** [comment]
I tried with 0.8.0, but it still makes same issues

**Comment by makseq** [comment]
I talked with our frontend dev, they fixed this in https://github.com/heartexlabs/label-studio-frontend/tree/release/0.8.1. You can get npm build here: https://github.com/heartexlabs/label-studio-frontend/actions/runs/367000254 and unzip it to `label_studio/static/editor/*`

**Comment by hlomzik** [comment]
That one is fixed in 0.8.* releases and overall TextArea ux was improved, so closing this.
