### ISSUE TITLE
How to remove the top right bracket for each choice in classification?

### ISSUE THREAD

**Issue by xinyuliu-jeffrey** [heartexlabs/label-studio#4878]
**Describe the bug**
With the following code:

  <View style="box-shadow: 2px 2px 5px #999;
               
               border-radius: 5px;">
    <Header value="Choose text sentiment"/>
    <Choices name="a1" toName="text"
             choice="multiple" showInLine="true">
      <Choice value="1"/>
      <Choice value="2"/>
      <Choice value="3"/>
      <Choice value="4"/>
      <Choice value="5"/>
    </Choices>
  </View>

The labelling screen shows the choices:

1[1]

2[2]

3[3]

4[4]

5[5]

With brackets at the top right of each choice. How to remove them brackets?

**Comment by hogepodge** [comment]
@xinyuliu-jeffrey, those brackets are hotkey shortcuts. There's no way to remove them right now, but I can add a feature request to disable them as others have faced this issue.
