### ISSUE TITLE
Problem in displaying nested text in GUI

### ISSUE THREAD

**Issue by sathiyabalu89** [heartexlabs/label-studio#488]
I am trying to convert XML to text with certain tags retained and saved this as JSON for importing. As of now, only \n tags in the text are retained and all the \t are deleted. Because of this, the text is displayed with proper nesting and it is hard to read. 
![image](https://user-images.githubusercontent.com/44389070/98832613-076edb80-2463-11eb-923a-4eea696397d0.png)

Is it possible to do pretty print kind of ? Or what is the best method to import XML files in label-studio? Please advise

**Comment by hlomzik** [comment]
Hi! This is default browser's html/text displaying behaviour. However it can be changed easily with simple css.
You can add `<Style>.htx-text{ white-space: pre-wrap; }</Style>` to your config to fix tabbed indents.
Maybe we should make this default. Or at least consider this as an option...

**Comment by sathiyabalu89** [comment]
Thank you the immediate reply. It worked.
