### ISSUE TITLE
a issue in pdf classification

### ISSUE THREAD

**Issue by yanwenjie1** [heartexlabs/label-studio#4883]
i can not import pdf file, show The filetype of file "sample.pdf" is not supported.(I downloaded the PDF file in the example)
and The import interface also did not see support for PDF files

**Environment (please complete the following information):**
 - OS: windows and linux
 - Label Studio Version 1.8.2 and 1.9.0

**Comment by yanwenjie1** [comment]
after i upgrade Label Studio from 1.6.0 to 1.9.0,  this issue occurred.

**Comment by yanwenjie1** [comment]
And i tried both Python versions 3.8.8 and 3.10.0, but got the same results.

**Comment by hogepodge** [comment]
@yanwenjie1 Label Studio doesn't have direct support for PDF labeling. There is a workaround using HTML embeds, but it's not guaranteed to work or be supported. 

https://labelstud.io/templates/pdf_classification

**Comment by yanwenjie1** [comment]
thanks
