### ISSUE TITLE
How to use local file on the tasks.json?

### ISSUE THREAD

**Issue by checker20** [heartexlabs/label-studio#49]
Hi I'm trying to do audio classification but the files are too big to upload somewhere, plus it's sensitive data too. Is there a way to provide the url field locally on the tasks.json?

Thanks in advance

**Comment by makseq** [comment]
Can you move you audio files over your hard disk? If you can place them nearby server.py, we will implement the fast solution.

**Comment by checker20** [comment]
> Can you move you audio files over your hard disk? If you can place them nearby server.py, we will implement the fast solution.

Yes I can! What is the fast solution?

**Comment by makseq** [comment]
If you place your file to label-studio/backend/static/data/1.wav then it will be available as http://localhost:8200/static/data/1.wav. Or you can make symlink to your data folder.

**Comment by shevchenkonik** [comment]
@checker20 Did you manage to solve this issue? @makseq suggested a quick solution for you.

But need to do the correct support of local data and if you can make such functionality, then we will approve PR for community. 👍

**Comment by maxpv** [comment]
I tried the suggested solution above with no success.

```html
#config.xml
<View>
  <Header value="Choose text sentiment:"/>
  <Text name="my_text" value="$url"/>
  <Choices name="sentiment" toName="my_text" choice="single" showInLine="true">
    <Choice value="Positive"/>
    <Choice value="Negative"/>
    <Choice value="Neutral"/>
  </Choices>
</View>
```

```json
#task.json
[{
    "url": "http://127.0.0.1:8200/static/file1.txt"
},
{
    "url": "http://127.0.0.1:8200/static/file2.txt"
}
]
```

This yield the following result:
![Screenshot 2019-10-24 at 16 54 59](https://user-images.githubusercontent.com/820657/67497997-11b70f80-f67f-11e9-9aca-208526cabcb3.png)

**Comment by shevchenkonik** [comment]
@maxpv 
Currently, LS doesn't support .txt files, text format only:

```javascript
[{
  "text": "Lorem.."
}]
```

**Comment by maxpv** [comment]
Ok thanks for your answer, I came from #101

**Comment by oQuantumDecayo** [comment]
> > Can you move you audio files over your hard disk? If you can place them nearby server.py, we will implement the fast solution.
> 
> Yes I can! What is the fast solution?

**Comment by oQuantumDecayo** [comment]
> Hi I'm trying to do audio classification but the files are too big to upload somewhere, plus it's sensitive data too. Is there a way to provide the url field locally on the tasks.json?
> 
> Thanks in advance

**Comment by YongWookHa** [comment]
Hi. 
I have similar problem.
I ran the server locally with this command.
```
label-studio start my-project -i sample-2020-01-22-09-10.json --init
```

and, in the json, I wrote like
```
[{"image": "000.png"}, 
{"image": "001.png"}, 
{"image": "002.png"}]
```
![image](https://user-images.githubusercontent.com/12293076/72952486-62045180-3dd5-11ea-9b3c-a0869691c231.png)
And I found this.

Where should i put the image?
I have put the image in cwd of `label-studio start my-project ...`, but it doesn't work.

According to the server log, I can assume that the error is about 'not found'(404).

Please help me to solve!
Thanks in advance.

**Comment by niklub** [comment]
Hi,

Label Studio doesn't support local file paths, but URLs. If you can't host somewhere your images or audio files for some reason, I suggest the following aforementioned workaround:

1. Copy your files or make a symlink to static dir:
  ```bash
   ln -s my/dir/with/images label-studio/static/my_images
  ```
2. Create your file.json with:
```json
[
{"image": "http://localhost:8200/static/my_images/000.png"},
{"image": "http://localhost:8200/static/my_images/001.png"},
{"image": "http://localhost:8200/static/my_images/002.png"}
]
```
3. Upload file.json via UI or start `label-studio start my-project -i file.json --init`

**Comment by Khanifsaleh** [comment]
> Hi YongWookHa,
> 
> Label Studio doesn't support local file paths, but URLs. If you can't host somewhere your images or audio files for some reason, I suggest the following aforementioned workaround:
> 
>     1. Copy your files or make a symlink to static dir:
> 
> 
> ```shell
>  ln -s my/dir/with/images label-studio/static/my_images
> ```
> 
>     1. Create your file.json with:
> 
> 
> ```json
> [
> {"image": "http://localhost:8200/static/my_images/000.png"},
> {"image": "http://localhost:8200/static/my_images/001.png"},
> {"image": "http://localhost:8200/static/my_images/002.png"}
> ]
> ```
> 
>     1. Upload file.json via UI or start `label-studio start my-project -i file.json --init`

Hai, I installed label studio using pip, where is `label-studio/static/` location? I've copy my-file-folder to `anaconda3/envs/my_env/lib/python3.6/site-packages/label_studio/core/static/` and create file.json like you mentioned. But it still failed.

**Comment by makseq** [comment]
This ticker is very outdated. Please, check this docs: https://labelstud.io/guide/tasks.html#Import-data-from-the-Label-Studio-UI
