### ISSUE TITLE
Distorted Original Image Resolution ?

### ISSUE THREAD

**Issue by mylifeasazucchini** [heartexlabs/label-studio#490]
Hi! Great Tool first of all! 

I had a simple query though related to the coordinates of the annotated points, the annotated points have values in the range 0-100 both in x and y coordinates but the original image resolution is about 600x403 (I tested it on the sample image). Is there any way of saving the points as json/csv such that they are already scaled to the the actual image resolution ? (I know it is quite easy to do it by computing the scaling value along the x and y axis)

**Comment by makseq** [comment]
Hi! Thank you! 
Yes, we are thinking in this direction to: LSF must have an option in config to allow use original coordinates instead of 0-100. But unfortunately it's not supported right now.
