### ISSUE TITLE
Deploying to Google Cloud Run with frontend changes

### ISSUE THREAD

**Issue by monurcevik** [heartexlabs/label-studio#4900]
**Is your feature request related to a problem? Please describe.**
I'm able to run the project locally with the frontend changes I made. However, when I deploy it to Cloud Run, frontend changes are lost and the original frontend version is deployed successfully.

**Describe the solution you'd like**
I would expect the frontend changes to be included in the newly build docker image and deployed like that to Google Cloud Run, assuming this is allowed. I assumed it was allowed due to the instructions on how to modify the frontend and how to build it again using the set of commands mention in README.

**Describe alternatives you've considered**
I've tried the steps mentioned in #1616 but the deployed image still had the original frontend. I have tried building a docker image and then deploying, and also directly building from the source without luck.

**Additional context**
Thank you for open sourcing this. It is really helpful as a labelling tool.

**Comment by hogepodge** [comment]
HI @monurcevik, you should be able to launch your own docker builds within your infrastructure, but it will probably require some additional steps (especially if you're using something like docker-compose for the deployment).

If you're deploying into the cloud, you will want to host your custom images somewhere that your deployment files can find them. The steps would be something along the lines of:

* Do a docker build of your custom application, and apply a tag that matches your docker hub account. It might be something like `monurcevik/label-studio:latest`, but the actual value depends strongly on your infrastructure setup.
* modify your deployment files to point to that image tag

Unfortunately, I'm not sure we can help much further beyond that. Managing the deployment of applications to cloud infrastructure is a process that depends heavily on your own needs and your organizations policies. Hopefully this helps you to get unblocked, though.
