### ISSUE TITLE
Lost all my annotations because the absolute local path changed

### ISSUE THREAD

**Issue by 1andDone** [heartexlabs/label-studio#4902]
![image](https://github.com/HumanSignal/label-studio/assets/63823064/2df19671-7ea5-425f-b41d-d70d44f8ad9b)

I changed around the folder structure of my project, which resulted in the absolute local path changing. This, in turn, led to me losing all of my previous annotations. Is there a fix for this?

**Comment by SheldonWBM** [comment]
There are two possible solutions (although someone from HumanSignal might have better advice).
Annotations create a task file (a number like 2741) without an extension. They are JSON files and can be edited (recommend prettify JSON before editing). You can fix the image file path and reimport the files (images and tasks).
The default database is SQLite3 (PostgreSQL is also an excellent choice).
You may manually edit the database. I did this after importing converted annotations. The "storage filename" was missing from the imported annotations so had to remap the "storage filename" for S3 and, quickly (not one at a time) delete duplicate tasks. Check your previous annotations are in the 'task' table. If you are uncomfortable with SQL commands in a terminal, you can use DB Browser for SQLite to open the database and, make careful edits.
Note: Editing a database is like editing the Windows registry, a mistake can be a huge headache so, back up the database before editing.

**Comment by 1andDone** [comment]
@SheldonWBM thanks for your response!

I created the old folder path, moved my images back to this location, and then updated the "Cloud Storage" with this path (without hitting the "Sync Storage" button) and looks like that worked! Both the images and their annotations are now visible once again.

In the future, if I do want to change the location of these images locally, what's the best way to make this change so that I don't run into similar issues? Surely, there's a better way than running an update statement on a SQLite table?

**Comment by hogepodge** [comment]
I don't think that there's a general solution for this problem. Label Studio assumes fixed data locations for the data source, and if they change there's not an easy way for the application to implement migrating from one storage source to another.

**Comment by makseq** [comment]
You can use the experimental feature called "Add Or Modify Data Field" in the Data Manager actions to replace a part of your old path to the new one. 

1. Enable experimental features and run label studio: 
```
ff_back_experimental_features=1 label-studio
```

2. Go to the Data manager for your project. 

3. Select tasks where you need to make path replacement. 

4. Click Actions > Add Or Modify Data Field.

5. Fill all inputs in the dialog: 
```
 Name = <your-column-name-where-you-need-to-replace-path>
 Type = Expression
 Value = replace('old-path','new-path')
```

7. Click OK and refresh the data manager page completely. 

**Note:** this action is experimental and can corrupt your data if you do something wrong. 

![image](https://github.com/user-attachments/assets/f470bcdd-0818-4a70-b0e2-157eca45e583)

![image](https://github.com/user-attachments/assets/410f4396-cd0d-4934-acd9-f3e6b2710dcf)

**Comment by nkinnaird** [comment]
Not sure it matters as I may have just messed things up the first go around when trying this, but using `replace("old-path","new-path")` with double quotes as opposed to single quotes worked whereas the latter I think resulted in my table replacing "image" with "$undefined$" which required going into the database and manually changing. (Instruction box uses double quotes but image shows single quotes.)

Also I believe it's still necessary to update Settings/Cloud Storage/path variable along with this update in order to see the image tasks in the Data Manager.

Lastly this didn't work for me on version 1.12.1, but did work on version 1.13.1.
