### ISSUE TITLE
Shortcuts overlap

### ISSUE THREAD

**Issue by tristanratz** [heartexlabs/label-studio#491]
**Describe the bug**

The shortcuts for the different labels can have the same shortcut as many of the root shortcuts. Like "s", which is also the shortcut for "skip". 

**To Reproduce**

Add a certain amount of labels to config.xml.

**Expected behavior**

The root shortcuts of labelstudio should be locked.

**Screenshots**

![image](https://user-images.githubusercontent.com/9249847/99399933-9f971580-28e6-11eb-8990-09405ead9823.png)

**Environment (please complete the following information):**
 - OS: any
 - Label Studio Version: 0.8.0

**Comment by makseq** [comment]
@tristanratz Thank you for your report, it's well known issue. We are working on a new shortcut system, it will be overhauled.

**Comment by hlomzik** [comment]
For now the hotkey for skipping task is `ctrl+space` (not good for Mac users though). And I checked another hotkeys — they don't clash with available symbols for labels' hotkeys. So that's not an issue anymore.
But we are working on better hotkeys anyway.
