### ISSUE TITLE
Image Segmentation/Brush Tool does not work as expected, Scissor/Multiple brush-strokes

### ISSUE THREAD

**Issue by tristanratz** [heartexlabs/label-studio#492]
**Describe the bug**

The scissortool in brush segmentation does not erase the whole brush stroke but only makes it lighter. The opacity of the stroke gets reduced. 

Furthermore another brushstroke/scissorstroke can only be started from an area where I never have drawn with the scissortool or a brush. One has always to drag/start the tools outside of the "used" areas to work.

**To Reproduce**

1. Create a config.xml which uses the brush image segmentation
2. Draw a brushstroke
3. Try to erase the drawn area or to draw a new stroke in the used area - it will not work

**Expected behavior**

It should be possible to start new brush-/scissorstrokes from anywhere inside the picture. Furthermore the scissortool should erase the brushes to zero opacity.

**Screenshots**

After erasing with scissor (still fragments of the brushtool):
![image](https://user-images.githubusercontent.com/9249847/99401921-0a495080-28e9-11eb-9fb0-69212100ae99.png)

**Environment (please complete the following information):**
 - OS: any
 - Label Studio Version [0.8.0]

**Comment by makseq** [comment]
Thank you for your report, we've created a ticket about this bug.

**Comment by davidblom603** [comment]
Noticed this problem too.

**Comment by faizan170** [comment]
Same issue, any update?

**Comment by tcapelle** [comment]
Did you manage to make it work?
I have a somewhat related issue, the pixel output should be solid (not different opacity levels). For each label, one gray value. I get soft borders. Maybe it is related.
![image](https://user-images.githubusercontent.com/18441985/99955933-6f87c080-2d85-11eb-867a-abdd92b44aa6.png)

**Comment by makseq** [comment]
@faizan170 We are working on it. 

@tcapelle Why can't you apply a simple thresholding to this array? For example: 
```
img[img > 0] = 1
mask = img.astype(np.bool)
```

**Comment by tcapelle** [comment]
Thanks you for looking at this.
- The brush should be hard, and paint (segment) only the given value. 
- Have not been able to find where to set this value. (e.g. Label Plane - > 128 value on mask, for instance.)

**Comment by nicholasrq** [comment]
This issue was fixed and available since LS 1.0.1
