### ISSUE TITLE
The document claims to support annotation for AVI files, but in reality, AVI files cannot be annotated.

### ISSUE THREAD

**Issue by jsxzhub** [heartexlabs/label-studio#4921]
document ：

![image](https://github.com/HumanSignal/label-studio/assets/6895480/70fc5ffe-92e5-444b-850e-9b0ccbe42843)

reality：
![image](https://github.com/HumanSignal/label-studio/assets/6895480/6a982b61-ba9a-48ce-8829-ed2cad62f031)

**Comment by hogepodge** [comment]
We've filed a ticket to resolve this in the documentation. Thanks.

**Comment by caitlinwheeless** [comment]
Updated the docs to remove .avi as supported file type
