### ISSUE TITLE
Quickview Next/Prev Image Hotkey Enter no longer working

### ISSUE THREAD

**Issue by LemonGraZ** [heartexlabs/label-studio#4922]
Since upgrading to 1.8.2 from 1.6.0 I can no longer switch to next / prev task by pressing:
- Shift + up/down
- Enter

Shift / Up Down is still selecting the prev / next task in the list, but Enter does no longer switch to that task.

**To Reproduce**
1. Go to Quick View of a Task, after it has already been labeled.
2. Press Shift + Down to select the next task in the list in the left panel.
3. Press Enter

**Expected behavior**
The the selected task should be loaded.

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/105200595/db360509-3022-4480-bc42-964e753e5933)

**Environment (please complete the following information):**
 - OS: Windows 11, Chrome
 - Label Studio Version 1.8.2

**Additional context**
This is absolutely crucial! Relabeling or rechecking already labeled tasks is an absolute standard during labeling. If hotkey does not work, the user has to click on every task one by one, which is horrific.

This **was** working in 1.6.0 we were using before.

**Comment by hogepodge** [comment]
Thanks @LemonGraZ, I know that we made some changes to how hotkeys worked in a recent release to make it more consistent across different platforms. I'll check in with the team and see exactly how the changes have impacted the enter hotkey, and next steps.

**Comment by LemonGraZ** [comment]
@hogepodge  Are there any updates? This is quite a problem  working efficiency for us.

**Comment by hogepodge** [comment]
@LemonGraZ I’m no longer with HumanSignal, and don’t have any insights into the status of this. My apologies

**Comment by nachouve** [comment]
> @hogepodge Are there any updates? This is quite a problem working efficiency for us.

I don't know if you can use the mode "Label Tasks As Displayed" explained in that [comment](https://github.com/HumanSignal/label-studio/issues/4422#issuecomment-1600121562)

**Comment by makseq** [comment]
@LemonGraZ @nachouve I've just checked shift+up/down => shift+right/left - these combinations work and allow to navigate over tasks as it worked previously. You just need to use shift + right instead of enter.

**Comment by makseq** [comment]
Also you can try running LS this way:
```
feat_front_dev_4008_quick_task_open_short=1 label-studio 
```
and you will be able to navigate across tasks just using shift + up/down with the second hotkey like shift+right.
