### ISSUE TITLE
Cannot export COCO format in image segmentation project

### ISSUE THREAD

**Issue by plannaAlain** [heartexlabs/label-studio#4923]
**Describe the bug**
Trying to export COCO json of a image segmentation project no longer works in version 1.9.x - This was working fine but it broke in new version.

`Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/label-studio/label_studio/data_export/api.py", line 190, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "/home/ubuntu/label-studio/label_studio/data_export/models.py", line 162, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_converter/converter.py", line 212, in convert
    self.convert_to_coco(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/label_studio_converter/converter.py", line 651, in convert_to_coco
    (x / 100 * width, y / 100 * height) for x, y in label["points"]
KeyError: 'points'`

**To Reproduce**
1. Go to Export Data
2. Select COCO format

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version 1.9.1.post0

**Additional context**
We were able to export in previous versions.

**Comment by plannaAlain** [comment]
Same error when trying to export YOLO format - we checked that all our annotations have a points field.

**Comment by plannaAlain** [comment]
We found that one record was causing issues  and it worked after we deleted it. We will close for now but there might be some bug.

**Comment by AymanTalkhani** [comment]
@plannaAlain Not sure if you need still images labeled for segmentation/bounding boxes, but if you do, have you tried using [InstaLabel](https://www.instalabel.ai/)? It supports formats like COCO, and automates the entire labeling task with custom AI models. All you need to do is upload your dataset, select and label a few samples you'd like to finetune the model on, and hit the 'Train annotator' button. You can then head over to the 'Annotate' tab, click 'Instant Annotation' and have the finetuned model label the rest of your dataset for you. There's even a crowdsourcing option to correct AI predictions for verified ground truth labels. Could be useful for your CV labeling use cases if you're on the lookout.

**Comment by olojuwin** [comment]
I encountered the same issue :  @plannaAlain 
Label Studio version: 1.13.1 

{
    "release": "1.13.1",
    "label-studio-os-package": {
        "version": "1.13.1",
        "short_version": "1.13",
        "latest_version_from_pypi": "1.13.1",
        "latest_version_upload_time": "2024-08-20T17:38:07",
        "current_version_is_outdated": false
    },
    "label-studio-os-backend": {
        "message": "ci: Build frontend",
        "commit": "d9b816a3781ee806bba50c8c5589fcdb8555a277",
        "date": "2024/08/19 19:14:23",
        "branch": "",
        "version": "1.13.1+0.gd9b816a.dirty"
    },
    "label-studio-frontend": {
        "message": "ci: Build frontend",
        "commit": "d9b816a3781ee806bba50c8c5589fcdb8555a277",
        "date": "2024-08-19T19:14:23.000Z",
        "branch": "develop"
    },
    "dm2": {
        "message": "ci: Build frontend",
        "commit": "d9b816a3781ee806bba50c8c5589fcdb8555a277",
        "date": "2024-08-19T19:14:23.000Z",
        "branch": "develop"
    },
    "label-studio-converter": {
        "version": "1.0.5"
    },
    "label-studio-ml": {
        "version": "1.0.9"
    }
}
