### ISSUE TITLE
Data import on localhost is very slow/perpetual

### ISSUE THREAD

**Issue by dioptrique** [heartexlabs/label-studio#4936]
**Describe the bug**
When importing 541 images in Data Import in Create Project it takes forever.

**To Reproduce**
1. Go to 'Create New Project'
2. Click on 'Data Import'
3. Click on 'Upload files'
4. All the files are loading pertetually. 541 images should not take this long

**Expected behavior**
I expected the images to load quickly as it is simply being uploaded locally.

**Screenshots**
<img width="771" alt="image" src="https://github.com/HumanSignal/label-studio/assets/30422345/24f45fd0-7766-4999-b55b-139ce3626df0">

<img width="457" alt="image" src="https://github.com/HumanSignal/label-studio/assets/30422345/4005ed73-818c-492c-9268-3354c818f0e8">

**Environment:**

It does not work on both of these OSes;

 - OS: Ubuntu 22.04.2 LTS
 - Label Studio Version: 1.9.1.post0
 
 AND 
 
 - OS: macOS Ventura 13.4.1
 - Label Studio Version: 1.9.1.post0

**Comment by hogepodge** [comment]
Looking into this, I'll see what the team has to say. Can you share your machine specs with us?

**Comment by hogepodge** [comment]
@dioptrique checking in with the team, we face a few issues. The first is, on the open source edition, Label Studio uses a single thread to upload files. For a large number of files, this will be a slow and blocking process. Implementing this with a thread-pool is a more complicated process, and I've filed a feature request for it, but it's currently not on the roadmap.

Our suggestion is to use a cloud storage connecter (we also have a ["local" cloud storage connector](https://labelstud.io/guide/storage.html#Local-storage)) if you have a large volume of data to manage. Thanks for your feedback, and we understand that this likely isn't the outcome you're looking for.

**Comment by neekey** [comment]
I know this issue has been closed, but just wanted to flag it again, installed label studio today myself, and face this issue right away when trying to import like 1000 images (which i would say pretty common for ML projects). Would be better to have this documented somewhere

**Comment by Sc00ba** [comment]
This sounds insane to a Go developer. It hangs on a whopping 28 files! I can do one at a time faster than all 28. Something ain't right with it!
