### ISSUE TITLE
Availabile delete target output data when use cloud storage

### ISSUE THREAD

**Issue by bruce32118** [heartexlabs/label-studio#494]
When I use the change the target path to the cloud storage, I can't delete the labeled data in the s3.
If I delete the output data, the label-studio would show the error message. Otherwise, the delete icon also be hidden on web UI.

I found that if the target output data path was set to cloud storage , the '[can_delete_tasks](https://github.com/heartexlabs/label-studio/blob/master/label_studio/project.py#L172)': self.can_delete_tasks set to false.
By the way, the cloud storage delete command is not implemented.

**Comment by makseq** [comment]
@bruce32118 we resolved that the deletion of completions for storages has very complex logic with a lot of unwanted side effects for users. Therefore it's bad by security reasons: user could delete his important data from storage unexpectedly.

**Comment by bruce32118** [comment]
@makseq There some error in using cloud storage. If I delete the target file in the s3 by AWS console. 
<img width="483" alt="截圖 2020-11-22 下午9 50 53" src="https://user-images.githubusercontent.com/9030781/99905663-301d8d80-2d0d-11eb-993f-99593ec6e6c3.png">
Is it a bug?

**Comment by makseq** [comment]
As I mentioned before - we don't support deletion for the target storage.

**Comment by bruce32118** [comment]
@makseq Thanks for your response.

**Comment by makseq** [comment]
But we will develop more features for storage in the next releases.
