### ISSUE TITLE
How to build a VQA labeling page with a lot of questions, with the image at the left and a rolling QA at the right?

### ISSUE THREAD

**Issue by xinyuliu-jeffrey** [heartexlabs/label-studio#4943]
I want to build a VQA (Visual Question Answering) labeling page with a lot of questions, and displaying the image on the left and a rolling QA (Question-Answer) interface on the right. I used the default VQA page, but the image cannot be seen when the question is quite a lot, which really confuses me. I am wondering how could I build a page with a FIXED image on the left, and a ROLLING QA part on the right. Thank you.

**Comment by hogepodge** [comment]
Can you share your labeling interface with us, and a diagram of what you're looking for? We need a bit more information to know how to write up the feature request.
