### ISSUE TITLE
 The case sensitive **email** and password you entered don't match

### ISSUE THREAD

**Issue by shmilee** [heartexlabs/label-studio#4955]
## Describe the Bug
Hi, I‘m’ using the codes below to deploy a label-studio instance, and create 10 accounts for my group. But always see this error when log in to Label Studio:
![2023-11-02-114917_352x249_scrot](https://github.com/HumanSignal/label-studio/assets/2681740/8a471fd5-7651-45fd-b6b6-ba170955f53a)

```
[$] label-studio user --username GNlxV@localhost
.... skip ....
=> User info:
{'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'GNlxV@localhost', 'last_activity': '2023-11-02T03:14:26.879705Z', 'avatar': None, 'initials': 'GN', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'token': '2b4d77f4bc8ff7ff688e926191abd6c54b531782', 'status': 'ok'}

[$] cat label-studio/user-info
1  GNlxV@localhost  pWd+47f9BgUXs8bz

2  eSjAY@localhost  pWd+47da5UTk3SZd
.... skip ....
```

## Codes To Reproduce

```
studio_path=~/label-studio
python3 -m venv "$studio_path"
source "$studio_path/bin/activate"
python3 -m pip install label-studio
echo "export LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true" >> "$studio_path/bin/activate"
echo "export LABEL_STUDIO_BASE_DATA_DIR=$studio_path/data" >> "$studio_path/bin/activate"
mkdir "$studio_path/data"
```

```
studio_path=~/label-studio
source "$studio_path/bin/activate"
for i in `seq 1 10`; do
    who="$(tr -dc A-Za-z </dev/urandom | head -c 5)@localhost"
    key="pWd+$(cat /proc/sys/kernel/random/uuid | cut -d- -f3)$(tr -dc A-Za-z0-9 </dev/urandom | head -c 8)"
    echo -e "$i  $who  $key\n" >> "$studio_path/user-info"
    label-studio start -b --username "$who" --password "$key"
done

label-studio user --username ?name?from?user-info?
label-studio start
```

## How to Fix

Capitals don't really matter in email addresses, but here, in label studio, it does!
So just replace this line:
```
who="$(tr -dc A-Za-z </dev/urandom | head -c 5)@localhost"
```
to:
```
who="$(tr -dc a-z </dev/urandom | head -c 5)@localhost"
```

Is this a bug? Do we need to translate the uppercase letters in email addresse all the time, no only in server side, but also in browser side?

**Comment by hogepodge** [comment]
@shmilee this is a fairly complicated issue, with some security implications. In the RFC specifying email case sensitivity:

> The local-part of a mailbox MUST BE treated as case sensitive.
> Therefore, SMTP implementations MUST take care to preserve the case
> of mailbox local-parts.  In particular, for some hosts, the user
> "smith" is different from the user "Smith".

While Label Studio doesn't implement this fully, we have to consider the security ramifications of attacks based on: 

> suppose [smith@case-sensitive-server.com](mailto:smith@case-sensitive-server.com) has a label studio account. I create [Smith@case-sensitive-server.com](mailto:Smith@case-sensitive-server.com) , and request a password reset for that email account; then Label Studio sends a password reset token for the [smith@case-sensitive-server.com](mailto:smith@case-sensitive-server.com) account to [Smith@case-sensitive-server.com](mailto:Smith@case-sensitive-server.com), and I'm able to use it to take over smith@'s account.

We're looking into solutions for this, but for now, we will require exact matching in case for all email addresses until we have time to develop a secure and correct policy. Thanks for reporting this.

**Comment by hogepodge** [comment]
Regardless, in your particular case, case sensitivity for usernames will always be checked and enforced.

**Comment by shmilee** [comment]
Ok, I got it. Thanks for your reply.

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
