### ISSUE TITLE
S3 backend for Text Tasks only works with JSON files

### ISSUE THREAD

**Issue by JimmyWhitaker** [heartexlabs/label-studio#497]
**Describe the bug**
When using the s3 backend for labeling text (for a classification task) it works with json files, but not text files. 

From the logs: 
```
Exception: test-examples.txt :: Expecting value: line 1 column 1 (char 0)
[2020-11-24 20:35:27,279] [DEBUG] [label_studio.utils.misc::exception_f::75] Traceback (most recent call last):
  File "/label-studio/label_studio/storage/base.py", line 292, in get_data
    parsed_data = self._get_value(key)
  File "/label-studio/label_studio/storage/s3.py", line 90, in _get_value
    value = json.loads(obj)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
1. Create `raw_data` and `labeled_data` bucket 
2. Create a text file with with one sentence per line 
```txt
# test-examples.txt
this is a test
```
3. Start label studio with the following command:
```
label-studio start my_s3_project/ --init --source s3 --source-path raw_data --input-format=text --target s3-completions --target-path labeled_data --force --log-level DEBUG --source-params "{\"use_blob_urls\": false, \"regex\": \".*\"}"
```
4. Select the text classification task in the setup & save (even when forcing a new text project to initialize it defaults to an object detection task).
5. Upload the `test-examples.txt` to the `raw_data` bucket. 
5. Go to the "Tasks" tab. When tasks are imported from s3 bucket, an error will be thrown

<img width="1137" alt="Screen Shot 2020-11-24 at 4 04 47 PM" src="https://user-images.githubusercontent.com/10526094/100151554-48a5b900-2e6f-11eb-8fe4-3f712f460f12.png">

**Expected behavior**
When the project is started/created, it should be able to read the same types of files from s3 as it is from the file system. 

**Environment (please complete the following information):**
 - OS: Running via Docker container on MacOS 10.15
 - Label Studio Version 0.8.0

**Additional context**
JSON may be the expected format for any interaction with s3. If so, it should probably be added to the docs somewhere to keep people from chasing the error I got here.

**Comment by makseq** [comment]
Try to change 
```
--source-params "{\"use_blob_urls\": false, \"regex\": \".*\"}"
```
to 
```
--source-params "{\"use_blob_urls\": true, \"regex\": \".*\"}"
```

**Comment by JimmyWhitaker** [comment]
If you enable blob URLs for text, then it doesn't actually import the text in the file. It imports the URL to the file as the $text parameter, but not the example contained. 

E.g. Task ID: 0, $text:`s3://raw_data/test-example.txt?X-Amz-Algorithm=xxx-Amz-Credential=xxxus-east-xxxaws4_request&X-Amz-Date=xxx&X-Amz-Expires=xxx&X-Amz-SignedHeaders=xxx&X-Amz-Signature=xxx`

**Comment by makseq** [comment]
Add to your <Text> tag in labeling config valueType="url": 
``` 
<Text valueType="url" value="$text"/>

**Comment by JimmyWhitaker** [comment]
When I do that, I seem to get the CORS policy errors - which seems odd to me, since they don't surface when I use json files with no blob-urls. I'll see if I can figure out why those are popping up.

**Comment by makseq** [comment]
When you use json - the server loads your data from the bucket. When you use txt and valueType=url - the frontend tries to get data on a browser side. But I think you need to check if s3 signed urls for txt files are resolved correctly.
