### ISSUE TITLE
Time Series Improvements - Y axis Min max scaling etc

### ISSUE THREAD

**Issue by davodogster** [heartexlabs/label-studio#498]
@hlomzik  @deppp Great work guys! A couple of things from me: My electrical time series dataset has BIG outliers, so the tool isn't useful for me yet until the Y axis values are dynamic ( I can't actually see/label the small spikes in my data when the Y axis doesn't adjust to the min,max of the time series window - see first screenshot below). Exporting annotations - It would be super helpful if we could export as csv and it exports the raw data as a csv, with another column for the annotation (either categorical for the class or numerical e.g 0 = no category, 1 = Category A, 2 = Category B - see screenshot below). It would also be good to upload a csv with a pre-populated "annotation" column so we can use assisted annotation. Hope these functions can be incorporated in the near future! Best Regards, Sam. Images are in time_series.md merge/comments

**Comment by makseq** [comment]
Thank you for your valuable response! We saved your points to our backlog.

**Comment by davodogster** [comment]
@makseq Thanks so much! When do you think you will be able to start implementing these features? Especially the y axis min/max point (the other one would be super helpful but is less essential).

**Comment by makseq** [comment]
@davodogster I think it will be in one-two months.

**Comment by davodogster** [comment]
> @davodogster I think it will be in one-two months.

@makseq @hlomzik @deppp Thanks for letting me know! We were hoping the Y-axis auto adjustment would have an easy fix. Currently, it won't adjust to the min,max of the window so you can't label the data when outliers are present in the window because the signals ( / positive responses) are too small to see properly.

Cheers, Sam

**Comment by davodogster** [comment]
Happy New Year @makseq and @hlomzik . Any time estimate on these couple of time series additional features?
Best Regards, Sam

**Comment by makseq** [comment]
@davodogster Thank you very much, Happy New Year too! 
Right now we are working on a new data manager release (on this week). After this we will discuss this issue with our team.

**Comment by davodogster** [comment]
Hi @makseq and @hlomzik  I'm still very keen to use the time series annotation tool once those two small changes are made - dynamic Y axis which auto scales the current window, and the other nice feature but not essential - to be able to upload pre-annotated data.
Do you have a time frame on either of these features? I want to use the tool to label my data for a project at work.

Best Regards,
Sam

**Comment by makseq** [comment]
Hi! It's glad to hear you are still keen to use LS :smiley: 
We will discuss this feature on this week with our team.

**Comment by hlomzik** [comment]
Hi, @davodogster! That took some time to get to TimeSeries, and I found a space for improvements and optimisation, but for this exact request I've made a solution: https://github.com/heartexlabs/label-studio-frontend/pull/168
There is `fixedScale` parameter, disabled by default, so now it works as you'd like — scales to fit only currently displayed values. Give it a try!

**Comment by davodogster** [comment]
@hlomzik Awesome, thank you! I'll give it a go!

**Comment by davodogster** [comment]
@hlomzik I pip installed the latest label studio 0.9.0 and am running it in my Chrome browser. Will this new feature work in this ? I don't know how to activate it.

**Comment by makseq** [comment]
@davodogster sorry, but it is not yet included in 0.9 LSB. 
You should download the latest LS Frontend manually. 
I recommend you to wait a little, the new LSF with this fix will be included into 0.9.1 release.

**Comment by davodogster** [comment]
Hi @makseq Awesome, thanks for your quick reply!, I will wait for 0.9.1, in the meantime I may try the LS Frontend if it's quick to setup. Is the upload annotations feature also available, e.g upload a time series csv with an extra column for pre-populated points/segments. Sorry - I may be asking a bit too much here! Thanks, Sam

**Comment by davodogster** [comment]
@makseq 
It won't read in my data - I'm not sure what I'm doing wrong ?

Data:
![image](https://user-images.githubusercontent.com/46079516/107710080-2c594000-6d2b-11eb-8379-6707d6f2389a.png)

Config:
![image](https://user-images.githubusercontent.com/46079516/107709814-b48b1580-6d2a-11eb-9e08-843e9a4781da.png)

Result:
![image](https://user-images.githubusercontent.com/46079516/107710196-69253700-6d2b-11eb-96d7-2cdc482c54a4.png)

**Comment by makseq** [comment]
It seems you forgot to enable special checkbox about how to interpreter input file on the import step. Is it 0.9.1?

**Comment by davodogster** [comment]
@makseq I'm using 0.9.0 as 0.9.1 hasn't been released yet. I don't think there is any special checkbox

It appears that Time series no longer supports raw csv input, instead it can only be a url csv, else a Json.
![image](https://user-images.githubusercontent.com/46079516/107716908-54e73700-6d37-11eb-8e56-c482569d78c5.png)

**Comment by makseq** [comment]
@davodogster It seems you really forget to use checkbox on import screen. Before LS 0.9.1 it was another much twisted text. And the correct import screen must look like this: 
![image](https://user-images.githubusercontent.com/501780/107833621-e93bb300-6da4-11eb-8b61-e9fe425b75e8.png)

But I think there is another problem with previously created labeling config. Try to make the project from scratch and copy your old labeling config to the new LS project.

**Comment by hlomzik** [comment]
@davodogster to use custom (or not yet included) build of labeling interface you can just replace it via simple command from our guide: https://labelstud.io/guide/frontend.html#Github-Artifacts (I think you may skip the `GITHUB_TOKEN` part as that repo is totally open, also you may skip `<branch>` param as it is already in `master`)
Or you can just download already built package from [CI page](https://github.com/heartexlabs/label-studio-frontend/actions/runs/559050076) (artifact "build <hash>" on the bottom of the page) and unpack it into `label_studio/static`

**Comment by hlomzik** [comment]
about exporting labels as new column in csv — had no time for this yet, sorry. I hope, we'll investigate into this soon.

**Comment by davodogster** [comment]
@makseq yes it appears only the old time series config from months ago works worth 0.9.1 and the new config you guys created doesn't work. Also, there is no option to disable the fixed scale. Are you able to include that so next time I  pip install I can

**Comment by davodogster** [comment]
@hlomzik Are you able to make it easier to upload multiple time series in one project? I can't get it to work, probably because I loaded the first one it and then edited the config file then tried to load another csv in.

**Comment by makseq** [comment]
@davodogster Could you show a screenshot with an error while importing?

**Comment by davodogster** [comment]
Hi @makseq it seems to work!

My only concern now (apart from wanting to be able to export annotations as a single csv column beside the raw data .. haha) is that it might be doubling up?

For each task ID it shows **both** CSV's, so is it doubling up or am I doing something wrong? I don't want to annotate lots of time series and then export the annotations to find out I have done it wrong.
Here's what I did to get it working with multiple CSVs (and you still need the old config format)

![image](https://user-images.githubusercontent.com/46079516/108646311-401a5880-751a-11eb-875e-ef532566ccfe.png)

![image](https://user-images.githubusercontent.com/46079516/108646317-43addf80-751a-11eb-8143-8401a8c837f4.png)

![image](https://user-images.githubusercontent.com/46079516/108646319-46103980-751a-11eb-8ac5-ebf7261a7320.png)

Cheers, Sam

**Comment by makseq** [comment]
@davodogster Hi! Yes, I think now everything must be correct. One LS task is equal to one csv files.

**Comment by makseq** [comment]
Check `fixedScale` - https://labelstud.io/tags/timeseries.html#main
