### ISSUE TITLE
Docker Image Slow to Save/Update Labels (Up to 2 Seconds Each Task) - NLP

### ISSUE THREAD

**Issue by bcs1gh** [heartexlabs/label-studio#4986]
**Describe the bug**
Using the standard docker image, saving a label is very slow - meaning labelling would take a lot longer than necessary as there's a 2 second wait between each task. 
For a set of 500 simple text labels, this would be 16.5 mins of total loading time between tasks.

**To Reproduce**
1. Run the docker image
2. Import some dummy data
3. Setup basic text classification labelling interface (default)
4. Save a task
5. Inspect the api/annotations/X?taskID=X&project=X XHR request and see that it takes a long time to complete before the next task is then loaded.

**Expected behavior**
Labelling/switching to next task after saving should be snappy so that labels can be processed fast. Even if the save operation needs to take a long time it could run in the background whilst the next task is presented to the user. 

**Environment (please complete the following information):**
 - OS: Windows 10 (Docker)
 - Label Studio Version 1.9.1

**Additional context**
What's the bottleneck here? Why does the server take so long to respond for a simple save request with the default docker image?

**Comment by jombooth** [comment]
Hi @bcs1gh , could you provide more details as to the executing environment? In particular, how much memory has been allocated to the container, what database is in use, and are any volumes configured?
