### ISSUE TITLE
how to support 'Project management' ?

### ISSUE THREAD

**Issue by chriswweibo** [heartexlabs/label-studio#499]
Hi, there
Thanks for your effort on the amazing tool.

I successfully deploy the server using the git repo master branch.
But I did NOT see the 'Project management'  cascading button on the homepage as shown in the labelstudio.io website.
![image](https://user-images.githubusercontent.com/11674246/100313671-0eaff080-2ff0-11eb-8175-fb4a2a01c8c7.png)

This function is very integral for me.
Which branch should I refer to?

**Comment by makseq** [comment]
Hi, you need to start LS in mutli-session mode: 
```
label-studio start-multi-session
```

**Comment by chriswweibo** [comment]
Nice. It works!
