### ISSUE TITLE
Incorrect python requirement for installation by pip

### ISSUE THREAD

**Issue by aktzbn** [heartexlabs/label-studio#4994]
Documentation says about installation by pip:
```
# Requires Python >=3.8
```
I was not able to install the 1.9.1.post0 version of the tool in 3.11 environment (due to numpy 1.24.3). For 3.12 there is another error. 

OS: Debian 10-11. 

For 3.8 all is fine.

Fix the docs or dependencies, please.

**Comment by jombooth** [comment]
Hi @aktzbn - work is currently in flight to improve the way we manage dependencies in this project (see https://github.com/HumanSignal/label-studio/issues/5000#issuecomment-1791389203). Please stay tuned!

**Comment by hihosilvers** [comment]
Using python 3.11.5 I get this on Windows 11 (new conda env)

ERROR: Cannot install google-api-core[grpc]==2.11.0, label-studio and label-studio==1.9.1.post0 because these package versions have conflicting dependencies.

The conflict is caused by:
    label-studio 1.9.1.post0 depends on google-api-core==2.11.0
    google-cloud-appengine-logging 1.1.0 depends on google-api-core<3.0.0dev and >=1.22.2
    google-cloud-core 2.3.2 depends on google-api-core!=2.0.*, !=2.1.*, !=2.2.*, !=2.3.0, <3.0.0dev and >=1.31.6
    google-api-core[grpc] 2.11.0 depends on google-api-core 2.11.0 (Installed)

**Comment by truebit** [comment]
1.9.2post0 got the same error on python 3.11.5 using conda

> ERROR: Cannot install google-api-core, google-api-core[grpc]==2.11.0, google-cloud-appengine-logging, googleapis-common-protos[grpc]==1.56.4, label-studio and label-studio==1.9.2.post0 because these package versions have conflicting dependencies.
> The conflict is caused by:
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.59.3 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.59.2 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.59.0 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.58.0 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.57.0 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.56.2 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.56.0 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.55.3 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.54.3 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.54.2 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.54.0 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.53.2 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.53.1 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.53.0 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.51.3 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.51.1 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.50.0 depends on protobuf>=4.21.6
>     label-studio 1.9.2.post0 depends on protobuf<4.0.0 and >=3.15.5
>     google-api-core 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     google-cloud-audit-log 0.2.0 depends on protobuf>=3.6.0
>     googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     google-api-core[grpc] 2.11.0 depends on protobuf!=3.20.0, !=3.20.1, !=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.19.5
>     googleapis-common-protos[grpc] 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
>     proto-plus 1.15.0 depends on protobuf>=3.12.0
>     grpcio-status 1.49.1 depends on protobuf>=4.21.3

**Comment by hogepodge** [comment]
Label Studio 1.10.0 introduced a new dependency management system that should resolve this issue for you. Please give it a try, and let us know what you think.
