### ISSUE TITLE
Exporting 'Relation' information to output files

### ISSUE THREAD

**Issue by mippi7** [heartexlabs/label-studio#4999]
**Describe the bug**
Exporting 'Relation' information to output files

**To Reproduce**
1. Make up a random Relation between two bounding boxes in a video
2. Export data in form of ny file (e.g. .tsv for excel)

**Expected behavior**
See 'Relation' information in output .tsv files for specifi video annotation of bounding boxes

**Screenshots**
(not in .tsv spreedsheet)

**Environment (please complete the following information):**
 - OS
 - Label Studio Version [latest]

**Comment by makseq** [comment]
It's pretty tricky to have relations in tsv/csv and other format that are not designed for it. You can use native LS JSON format, it will contain relations.
