### ISSUE TITLE
script_path ':' splitting for ml backend does not work with windows absolute paths

### ISSUE THREAD

**Issue by KuenstlicheIntelligenz** [heartexlabs/label-studio#500]
`label-studio-ml init my_ml_backend --script "C:\abc\defg.py"`
will not work with
`script_path, model_class = args.script.split(':')`

  File "c:\bab\projects\extern\label-studio\label_studio\ml\server.py", line 79, in create_dir
    raise FileNotFoundError(script_path)
FileNotFoundError: C

Maybe you can just skip the first two chars in the script_path in line 67:
`if ':' not in script_path[2:]:`

**Comment by makseq** [comment]
Thank you for your report, we will fix it.

**Comment by makseq** [comment]
@KuenstlicheIntelligenz Could you check branch 0.8.2, we've fixed this bug there.
