### ISSUE TITLE
Unable to import images using json task with pre-annotations

### ISSUE THREAD

**Issue by XM-8JD2** [heartexlabs/label-studio#5013]
**Describe the bug**
Unable to import images using json task with pre-annotations

**To Reproduce**
1.Create a project and select the type as "Object Detection with Bounding Boxes"

2.Drag the json file with the following content into the import window

```
[{
    "data": {
      "image": "C:/Users/win/Desktop/1.png" 
    },
  
    "predictions": [{
      "model_version": "one",
      "score": 0.5,
      "result": [
        {
          "id": "result1",
          "type": "rectanglelabels",        
          "from_name": "label", "to_name": "image",
          "original_width": 768, "original_height": 768,
          "image_rotation": 0,
          "value": {
            "rotation": 0,
            "x": 4.98, "y": 12.82,
            "width": 32.52, "height": 44.91,
            "rectanglelabels": ["Airplane"]
          }
        }]
    }]
}]
```

Getting error:

```
There was an issue loading URL from $image value

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, more on that here
Technical description:
URL: C:/Users/win/Desktop/1.png
```

**Expected behavior**
Pre-annotations and images were successfully imported

**Screenshots**
1.png
![1](https://github.com/HumanSignal/label-studio/assets/133830244/50b65a61-3fc5-41aa-8588-61b75175533a)

![Snipaste_2023-11-07_20-16-00](https://github.com/HumanSignal/label-studio/assets/133830244/39cd599b-d65b-4542-b70b-7bef1381fcc7)

**Environment (please complete the following information):**
 - OS:[win10 21H2 LTSC]
 - Label Studio Version [v1.9.1.post0]

**Additional context**
null

**Comment by dceluis** [comment]
did you enable a local files storage as described in https://labelstud.io/guide/storage.html#Local-storage ?

**Comment by XM-8JD2** [comment]
> did you enable a local files storage as described in https://labelstud.io/guide/storage.html#Local-storage ?

Yes, I use the following code to start label-studio（.bat）
```
   @echo off
   SET LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
   SET LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=C:\Users\win\Desktop
   label-studio start
```

and I can import hundreds of images using local storage database

**Comment by dceluis** [comment]
https://github.com/HumanSignal/label-studio/issues/4722#issuecomment-1784118911
This might help you.

The "image" field in your import JSON is not correct, even though you followed the docs correctly.

The correct format is not a local path but a URL of form "/data/local-files/?d=<path_to_file>", the path to the file must be accessible under LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT .

I found this issue myself and was able to figure out a way of generating the import script correctly. Another user in that thread shared another way of achieving the same thing.

**Comment by XM-8JD2** [comment]
> [#4722 (comment)](https://github.com/HumanSignal/label-studio/issues/4722#issuecomment-1784118911) This might help you.
> 
> The "image" field in your import JSON is not correct, even though you followed the docs correctly.
> 
> The correct format is not a local path but a URL of form "/data/local-files/?d=<path_to_file>", the path to the file must be accessible under LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT .
> 
> I found this issue myself and was able to figure out a way of generating the import script correctly. Another user in that thread shared another way of achieving the same thing.


I didn't try to continue solving this problem, currently I solved it by writing API based script

Hope this helps others too
https://github.com/XM-8JD2/labelstud_preannotation_uploader

**Comment by procrastix** [comment]
It took me over a week to find this. Thank you. This should be in the documentation!!!

**Comment by makseq** [comment]
There is a video in the documentation on how to import tasks with Local storage references:
https://labelstud.io/guide/storage#Local-Storage-with-Custom-Task-Format

If you need pre-annotations to be imported as well, you need to add 'annotations' list to the task json. 

And for sure, there is steps on how to do it:
https://labelstud.io/guide/storage#Tasks-with-local-storage-file-references
