### ISSUE TITLE
how to do entity linking by using label-studio? 

### ISSUE THREAD

**Issue by glf1030** [heartexlabs/label-studio#503]
hi, 
I am working on a project that requires do entity linking after name entity recognition.  For example,  "Michael Jordan" could be labeled as a person from "LaMelo Ball insinuates that he believes Michael Jordan would beat his dad, Lavar Ball, in a 1v1 matchup". After that,  several candidates including "Michael Jeffrey Jordan (basketball star), Michael I. Jordan (machine learning star)" could pop out and human can select Michael Jeffrey Jordan according the context. 
I am wondering how to complete such task based on this project. 
Many thanks

**Comment by makseq** [comment]
@glf1030 Hello, thank for your interest to Label Studio. Could you describe more about your task? Why can't you have two different labels with supporting information? 
* Michael Jeffrey Jordan (basketball star)
* Michael I. Jordan (machine learning star)

OR you can have advanced per-region choices/textareas and more to provide more detailed labeling. 
[Check it here](https://labelstud.io/playground/?config=%3CView%20style%3D%22display%3A%20flex%3B%22%3E%3Cbr%3E%20%20%3CView%20style%3D%22width%3A%20150px%3B%20padding-left%3A%202em%3B%20margin-right%3A%202em%3B%20background%3A%20%23f1f1f1%3B%20border-radius%3A%203px%22%3E%3Cbr%3E%20%20%20%20%3CLabels%20name%3D%22ner%22%20toName%3D%22text%22%3E%3Cbr%3E%20%20%20%20%20%20%3CLabel%20value%3D%22Michael%20Jordan%22%20%2F%3E%3Cbr%3E%20%20%20%20%20%20%3CLabel%20value%3D%22Geoffrey%20Hinton%22%20%2F%3E%3Cbr%3E%20%20%20%20%3C%2FLabels%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%20%20%3CView%3E%3Cbr%3E%20%20%20%20%3CView%20style%3D%22height%3A%20200px%3B%20overflow-y%3A%20auto%22%3E%3Cbr%3E%20%20%20%20%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%20%2F%3E%3Cbr%3E%20%20%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3CView%3E%3Cbr%3E%20%20%20%20%20%20%3CChoices%20name%3D%22relevance%22%20toName%3D%22text%22%20perRegion%3D%22true%22%3E%3Cbr%3E%20%20%20%20%20%20%09%3CChoice%20value%3D%22Basketball%20star%22%20%2F%3E%3Cbr%3E%20%20%20%20%20%20%20%20%3CChoice%20value%3D%22Machine%20learning%20star%22%20%2F%3E%3Cbr%3E%20%20%20%20%20%20%3C%2FChoices%3E%3Cbr%3E%20%20%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%20%20%20%20%3CView%20style%3D%22width%3A%20100%25%3B%20display%3A%20block%22%3E%3Cbr%3E%20%20%20%20%20%20%3CHeader%20value%3D%22Select%20span%20after%20creation%20to%20go%20next%22%2F%3E%3Cbr%3E%20%20%20%20%3C%2FView%3E%3Cbr%3E%20%20%3C%2FView%3E%3Cbr%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E).

**Comment by glf1030** [comment]
thanks, it works.
