### ISSUE TITLE
Bug: After upgrading to 1.9.x, predictions from 1.8.x don't auto populate in the label stream

### ISSUE THREAD

**Issue by WillieMaddox** [heartexlabs/label-studio#5032]
**Description**

After upgrading to 1.9.2, clicking on "Label All Tasks" or "Label Tasks As Displayed" shows the image, but not the predictions carried over from 1.8.2.  If I click "back" to the previous task and then click "forward", the prediction appears. Predictions are also not being displayed for Tasks appearing after clicking "Submit". The predictions were generated prior to the upgrade in one of two ways:

 1. Either from the ML backend, or
 2. generated offline and then pushed to Label-Studio via the API.

This problem is present in both cases.  Note also that in both cases the ML backend was turned OFF. Also, when clicking on tasks directly from the Data Manager, the predictions show up as expected.

**Expected behavior**

The predictions from previous LS versions should load as normal

**Environment**
 - OS: Ubuntu 20.04
 - Label Studio Version 1.8.2 --> 1.9.2

**Comment by jombooth** [comment]
Hi @WillieMaddox - thank you for the report! We'll work on reproducing this issue on our side, and provide an update on whether we're able to.

**Comment by jombooth** [comment]
We were able to confirm this regression our side, and will be implementing a fix; I'll update here when I have more information. Thanks again for letting us know about this issue!

**Comment by doantientai** [comment]
Looking forward for the fix!

**Comment by davidblom603** [comment]
Yes, indeed. Looking forward to the fix!

**Comment by doantientai** [comment]
Still looking forward to the fix

**Comment by hogepodge** [comment]
Label Studio 1.10.0 was just released, and should address this issue. Thanks to everyone for your patience and feedback!
