### ISSUE TITLE
Data loading fails when local path is ending with "/"

### ISSUE THREAD

**Issue by patel-zeel** [heartexlabs/label-studio#5037]
**Describe the bug**

When I am trying to load the images from a local storage 
<img src="https://github.com/HumanSignal/label-studio/assets/59758528/ec778b1a-e35c-4cfc-9d4e-be870bdb3242" width="500">

I experienced the following bug:
* If the path is not ending with "/" e.g. `/home/username/some_path`, the images are loaded correctly
<img src="https://github.com/HumanSignal/label-studio/assets/59758528/bf44d465-9f0b-49a5-959d-3a7c5ddeceaa" width="500">

* If the path is ending with "/" e.g. `/home/username/some_path/`, the images are not loaded
<img src="https://github.com/HumanSignal/label-studio/assets/59758528/eba09dea-cbfc-4e8c-b0dc-3f081ba9ae80" width="500">

**Expected behavior**
It should work irrespective of if the path ends with "/" or not.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Label Studio Version 1.9.2.post0

**Comment by hogepodge** [comment]
Thanks for your bug report! We've confirmed this bug and have it on our roadmap to fix. You can track updates in this previously reported issue. https://github.com/HumanSignal/label-studio/issues/4914
