### ISSUE TITLE
how to dynamic add textarea for rewrite the dialogue

### ISSUE THREAD

**Issue by buptygz** [heartexlabs/label-studio#5041]
I have a demand, i need rewrite the dialogue by each sentence。so i don't no the num of sentence in the dialogue。But I need set a  
TextArea for each sentence in the dialogue dynamicly.
such as:
<View>
  <Text name="sentence1" value="$dialogue.sentence1" />
  <TextArea name="response1" toName="sentence1" />
  
  <Text name="sentence2" value="$dialogue.sentence2" />
  <TextArea name="response2" toName="sentence2" />

  
</View>

how to use tags to achieve above target?

**Comment by buptygz** [comment]
<img width="937" alt="image" src="https://github.com/HumanSignal/label-studio/assets/26403116/b6dc82d5-14fe-47b4-8c41-4b26fec5d4eb">

**Comment by hogepodge** [comment]
Hi @buptygz the best option is to pre-process your labeling tasks to order them and manage this in the way that you need. You can then create tasks with the appropriate fields to populate your labeling interface. You should be able to use the Label Studio API to help build out this pipeline.
