### ISSUE TITLE
Relation

### ISSUE THREAD

**Issue by Wh9511** [heartexlabs/label-studio#5059]
When using labelstud's natural language annotation task to extract relationships, how to add custom attribute fields for specified relationships?
I asked chatgpt, and the reply gpt gave me this.
```
<Relation value="org:founded">
      <Text name="founding_date" value="$founding_date"/>
</Relation>
```
But when I add this writing method, the text information cannot be displayed normally.How to solve this problem？

**Comment by hogepodge** [comment]
Hi @Wh9511 I responded to your question in the Slack channel. Can you take a look at the relationship documentation and example template and see if that helps to solve your issue? https://labelstud.io/templates/relation_extraction
