### ISSUE TITLE
'import task' button on the task page breaks

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#507]
When providing a host parameter, such as `example.com/label-studio`, to [run.sh](https://github.com/heartexlabs/label-studio/blob/master/tools/run.sh) the 'import task' button on the [task page](https://github.com/heartexlabs/label-studio/blob/master/label_studio/templates/tasks.html) breaks as it tries to resolve to `example.com/import`, instead of `example.com/label-studio/import`

Please change link for the 'import task' button' to relative path on line 140 of [templates/tasks.html](https://github.com/heartexlabs/label-studio/blob/master/label_studio/templates/tasks.html)

From:
`<a class="ui button positive" href="/import" v-if="project.can_manage_tasks">Import Tasks</a>`

To:
`<a class="ui button positive" href="./import" v-if="project.can_manage_tasks">Import Tasks</a>`

Note the "." before /import

**Comment by makseq** [comment]
@laynr Thank you for you proposal, I've done it. But this page will be deprecated in the next versions.

**Comment by lfeldb** [comment]
@makseq This is still an issue in the latest version:

I fixed it for me by modifying the following files (same fix as @laynr):

label_studio/templates/welcome.html line 64:
`<a class="ui button positive" href="/import">Import</a>`
To
`<a class="ui button positive" href="./import">Import</a>`

label_studio/static/js/build/index.js:
`{return window.location.href="/import"}`
To
`{return window.location.href="./import"}`

Same for export
Not sure what source is used to build index.js, but you probably can find it easily.

**Comment by makseq** [comment]
@lfeldb Thank you for your report, it will be fixed in 0.9.0.post6.

**Comment by lfeldb** [comment]
@makseq Perfect, thanks!

Found two others:
label-studio/label_studio/data_import/templates/import_new.html:
line 333 & 337
