### ISSUE TITLE
Issue with refreshing tasks from S3 on remote machine versus local laptop.

### ISSUE THREAD

**Issue by dahnny012** [heartexlabs/label-studio#509]
**Describe the bug**
Scenario:
1. Running label studio on docker on a remote machine
2. The next day new tasks are uploaded to S3 but label-studio doesnt detect or isnt able to update the task queue.
3. Restarting the image doesnt work

If label studio is running on my local macbook this works just fine. I have to copy over the source.json from my laptop to the remote.

**Expected behavior**
I. expect that label studio should refresh the tasks from S3 when new tasks are added on the remote machine.

**Screenshots**
Task Ui is stuck at this stage
<img width="377" alt="Screen Shot 2020-12-09 at 7 54 58 PM" src="https://user-images.githubusercontent.com/3695724/101719570-6d498580-3a58-11eb-8232-afc12702aedd.png">

**Environment (please complete the following information):**
 - OS: Amazon Linux, running on EC2
Linux version 4.9.230-0.1.ac.223.84.332.metal1.x86_64 (mockbuild@koji-pdx-corp-builder-64003) (gcc version 7.2.1 20170915 (Red Hat 7.2.1-2) (GCC) ) #1 SMP Tue Sep 8 15:48:58 UTC 2020

 - Label Studio Version: Latest version on docker

**Additional context**

Is there a directory of logs or something I can read if there are any errors?

**Comment by dahnny012** [comment]
looks like my aws credentials rotate hourly and label studio doesnt read in the new information.

however my macbook is able to pull in the new tasks when label is restarted, the remote machine does not.

**Comment by makseq** [comment]
@dahnny012 Sorry for a long answer. 

> looks like my aws credentials rotate hourly and label studio doesn't read in the new information.

What do you mean by this? Why your aws creds do rotate hourly?

**Comment by dahnny012** [comment]
Im running this on an internal company website and our aws creds are issued hourly.

**Comment by makseq** [comment]
@dahnny012 I think it's boto3 (aws python lib) problem. Try to upgrade it to the latest version on your server machine.

**Comment by makseq** [comment]
Hope it's fixed in the latest LS versions.
