### ISSUE TITLE
chatbot can be modify as I want

### ISSUE THREAD

**Issue by yinggoga** [heartexlabs/label-studio#5099]
Is there any way that I can modify the chatbot area as I want？Thanks!
![image](https://github.com/HumanSignal/label-studio/assets/27919234/412442d9-8336-4c63-a8e2-c23908df83d9)
For example.I want it can support adding/editing/deleting conversations

**Comment by yinggoga** [comment]
Is there any plan to support it？ @hogepodge

**Comment by nie3e** [comment]
+1 for this. Would be nice to do CRUD operations on conversations.
