### ISSUE TITLE
KeyError: 'created_at'

### ISSUE THREAD

**Issue by Siddhijain16** [heartexlabs/label-studio#510]
Hi,
I am using the latest version of Label-studio and trying to export my labelled images into the COCO format but as I do the export completions its showing me "KeyError: 'created_at' ". 
![Screenshot from 2020-12-11 16-52-31](https://user-images.githubusercontent.com/46879959/101899143-53807d80-3bd3-11eb-9f25-7aaa4c5c3dab.png)

I also tried label-studio-convertor but still got the key error 

(myenv) (base) billion@billion-Inspiron-3542:~/myenv/label-studio-converter$ python3 cli.py --input /home/billion/myenv/doclayout/completions/ --config /home/billion/Desktop/Siddhi/document_edge_detection_dataset/testinglabelstudio/configg/config.xml --output /home/billion/Desktop/Siddhi/document_edge_detection_dataset/new_dataset_final/voc-annotations --format VOC --image-dir /home/billion/Desktop/Siddhi/document_edge_detection_dataset/new_dataset5/Captured_Images/Nokia_phone/Images/
Traceback (most recent call last):
  File "cli.py", line 84, in <module>
    main()
  File "cli.py", line 78, in main
    c.convert_to_voc(args.input, args.output, output_image_dir=args.image_dir, is_dir=not args.heartex_format)
  File "/home/billion/myenv/label-studio-converter/label_studio_converter/converter.py", line 398, in convert_to_voc
    for item_idx, item in enumerate(item_iterator):
  File "/home/billion/myenv/label-studio-converter/label_studio_converter/converter.py", line 148, in iter_from_dir
    for item in self.iter_from_json_file(json_file):
  File "/home/billion/myenv/label-studio-converter/label_studio_converter/converter.py", line 156, in iter_from_json_file
    yield self.load_from_dict(data)
  File "/home/billion/myenv/label-studio-converter/label_studio_converter/converter.py", line 170, in load_from_dict
    result = sorted(tmp, key=lambda x: x['created_at'], reverse=True)[0]['result']
  File "/home/billion/myenv/label-studio-converter/label_studio_converter/converter.py", line 170, in <lambda>
    result = sorted(tmp, key=lambda x: x['created_at'], reverse=True)[0]['result']
KeyError: 'created_at'

**Comment by makseq** [comment]
Please, try `pip install label-studio-converter==0.0.22.post0`

**Comment by Siddhijain16** [comment]
> Please, try `pip install label-studio-converter==0.0.22.post0`

I used but again got KeyError: 'rectanglelabels'

(label_convertor) (base) billion@billion-Inspiron-3542:~/label_convertor/label-sge_detection_dataset/new_dataset_final/completions/ --config /home/billion/Desktop/Siddhi/document_edge_detection_dataset/testinglabelstudio/configg/config.xml --output /home/billion/Desktop/Siddhi/document_edge_detection_dataset/new_dataset_final/voc-annotations --format VOC --image-dir /home/billion/Desktop/Siddhi/document_edge_detection_dataset/new_dataset_final/Images/
Traceback (most recent call last):
  File "cli.py", line 84, in <module>
    main()
  File "cli.py", line 78, in main
    c.convert_to_voc(args.input, args.output, output_image_dir=args.image_dir, is_dir=not args.heartex_format)
  File "/home/billion/label_convertor/label-studio-converter/label_studio_converter/converter.py", line 455, in convert_to_voc
    name = bbox['rectanglelabels'][0]
KeyError: 'rectanglelabels'
![image](https://user-images.githubusercontent.com/46879959/102982002-d7215f00-452f-11eb-9d30-fdf76c04a21f.png)

**Comment by makseq** [comment]
Could you send me any json file as example from your_project/completions folder?

**Comment by Siddhijain16** [comment]
[test.zip](https://github.com/heartexlabs/label-studio/files/5734456/test.zip)


> Could you send me any json file as example from your_project/completions folder?

[test.zip](https://github.com/heartexlabs/label-studio/files/5734457/test.zip)

I do the polygon labeling

**Comment by makseq** [comment]
Sorry, I see you are trying to call converter manually. And you specified `--format VOC`, but VOC is not supported for polygonlabels.

**Comment by Siddhijain16** [comment]
> Sorry, I see you are trying to call converter manually. And you specified `--format VOC`, but VOC is not supported for polygonlabels.

But I need data in VOC format for my model what should I do ?
I tried external conversion but nothing work for me ...
Please suggest something 
Your help should be appreciated

**Comment by makseq** [comment]
The entry point for VOC converter is here: 
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/converter.py#L379

I think you need to modify this peace of code to use polygonlabels instead of rectanglelabels: 
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/converter.py#L454
