### ISSUE TITLE
global variable bug in base.py

### ISSUE THREAD

**Issue by dianyo** [heartexlabs/label-studio#511]
Find there's a bug when loading storage from s3. 
After tracing the code and find the global variable new_id at base.py:430 should be fixed.
I fix this bug by change it to local variable and send it by method argument.
```
def _get_new_id(key, new_id):
    id = self._extract_task_id(key)
    if id is not None:
        return id
        id = new_id
    return id
```

**Comment by makseq** [comment]
Thank you for your reported, we've already found it and fixed in the upcoming release.
