### ISSUE TITLE
The multiple labels annotated on my text in the UI are not carried over to the train_set, which serves as a training file for the NER model

### ISSUE THREAD

**Issue by EtienneFerrandi** [heartexlabs/label-studio#5111]
The json export of my annotated text looks like this :

```
{"id": 619, "annotations": [
    {"id": 96, "completed_by": 1, "result": [{"value": {"start": 0, "end": 27, "text": "I – CORRESPONDANCE GENERALE", "**labels": ["Titre 1", "unittitle"]**}, "id": "6jiKXITGB_", "from_name": "label", "to_name": "text", "type": "labels", "origin": "manual"}]...},
{"id": 620, "annotations": [
    {"id": 97, "completed_by": 1, "result": [{"value": {"start": 0, "end": 36, "text": "1 – Courrier « arrivée » (1946-1954)", **"labels": ["DATE", "Titre 2", "unittitle"]**}, "id": "N7tshFoGAK", "from_name": "label", "to_name": "text", "type": "labels", "origin": "manual"}]...}
```

We can see that for each JSON export entry, we have several labels.

I'm looking to predict the labels for the rest of the text entries with an ML backend NER. However, when I launch a training run, the `train_set.txt` that is generated retains only one label for each entry, as you can see : 

```
[CLS] X
i B-unittitle
– I-unittitle
correspond I-unittitle
##ance X
general I-unittitle
##e X
[SEP] X

[CLS] X
1 B-Titre 2
– I-Titre 2
co I-Titre 2
##ur X
##rier X
« I-Titre 2
arrive I-Titre 2
##e X
» I-Titre 2
( I-Titre 2
1946 X
- X
1954 X
) X
[SEP] X

[CLS] X
co B-Titre 3
##ur X
##rier X
arrive I-Titre 3
##e X
non I-Titre 3
protege I-Titre 3
( I-Titre 3
1952 X
– I-Titre 3
1954 I-Titre 3
) X
[SEP] X
```

I would like my `train_set.txt` to include all labels for each entry. Please help!

**Comment by hogepodge** [comment]
It looks like we should be sending all annotations. I'll file a bug with the team. Thanks for reporting this.

/jira create bug

**Comment by farioas** [comment]
/jira create bug
> Jira issue [TRIAG-278](https://humansignal.atlassian.net/browse/TRIAG-278) is created
>
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/7133702681)

[TRIAG-278]: https://humansignal.atlassian.net/browse/TRIAG-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jombooth** [comment]
Hi @EtienneFerrandi,

I dug into this issue a bit - the [ConLL2003 dataset format](https://www.clips.uantwerpen.be/conll2003/ner/) doesn't actually provide for multiple named entity tags to apply to the same word, but we think it wouldn't be unreasonable to extend it for this, e.g. by allowing the user to specify a separator, and using that separator to join together all the named entity tags that apply to that word.

The team is unlikely to be able to get to this soon, however, we'd be interested in a patch adding this option to the ConLL2003 dataset export functionality in Label Studio Converter (relevant line of code, which selects the first label for this export, is [here](https://github.com/HumanSignal/label-studio-converter/blob/master/label_studio_converter/utils.py#L107)). With this change implemented, you'd be able to get a json export from Label Studio, then use Label Studio Converter with these options to convert the json export into the ConLL2003 export you're looking for, with multiple labels for each word.

Cheers,
Jo
