### ISSUE TITLE
Predictions are shown in quick view but not in label stream

### ISSUE THREAD

**Issue by Djkmarco** [heartexlabs/label-studio#5115]
**Describe the bug**
Predictions imported manually using a .json file are shown in quick view but not in label stream.

**To Reproduce**
Create an object detection task.
Import example image
Import predictions manually using a json file
Start label stream

**Expected behavior**
Predictions appears both in quick view and label stream

**Screenshots**
Quickview
![image](https://github.com/HumanSignal/label-studio/assets/111493577/e016de31-d9c4-45e5-9670-b81b703cdc0a)
Label Stream
![image](https://github.com/HumanSignal/label-studio/assets/111493577/5161aacd-1b2e-490c-b330-6823c7a57cd0)
Settings
![image](https://github.com/HumanSignal/label-studio/assets/111493577/198f8efd-da71-45ee-8278-1984e9bae0ad)

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Label Studio Version [e.g. v1.9.0]

**Comment by CsterKuroi** [comment]
same issue

**Comment by hogepodge** [comment]
This should be addressed in the latest release of Label Studio 1.10.0. Thanks for reporting it, and please let us know if you continue to see this issue.
