### ISSUE TITLE
Label multiple task at once 

### ISSUE THREAD

**Issue by NandaBalakrishnan** [heartexlabs/label-studio#512]
**Is your feature request related to a problem? Please describe.**
specifically looking this feature for **Image Classification**
We want to use this tool for labeling images.  It will be convenient if it allows to select multiple images and label them at once with the selected label

**Describe the solution you'd like**

- show all images
- select the images which are look-a-likes (with (de)select all option)
- select the label and apply the label on all selected images

**Describe alternatives you've considered**
Enabling this option reduces labeling time 

ref: https://github.com/heartexlabs/label-studio/issues/40

**Comment by NandaBalakrishnan** [comment]
Any updates on the above ticket?

**Comment by makseq** [comment]
@NandaBalakrishnan We are working on a big update of Data Manager (DM) and preparing such functionality to the next after nearest release. If you have time you can try our new DM :slightly_smiling_face:

**Comment by jonorozcoc** [comment]
This feature could help me.

@makseq Is there something left on this issue? I mean, Can I help with something?

I think is not available on the RC you sent yesterday, right?

**Comment by makseq** [comment]
@jonorozcoc @NandaBalakrishnan 

I implemented an experimental feature for the completion copying here:
https://github.com/heartexlabs/label-studio/pull/514

1. Enable it in my_project/config.json by adding: 
```
...
"experimental_features": true,
...
```
2. Go to Tasks
3. Open some task A and create a completion with Choices you want to propagate to others tasks. 
4. Select this task A first. 
5. Select other tasks.
6. Click on "Propage completions"

**Comment by weeix** [comment]
Can we still utilize this feature? When I opened `label_studio.sqlite3`, I was unable to locate the place to put `"experimental_features": true`.

**Comment by makseq** [comment]
@weeix Please use this: 
```
EXPERIMENTAL_FEATURES=1 label-studio
```
Then you will see Propagate annotations in Data manager Actions.
