### ISSUE TITLE
Deleting a user through Django admin panel breaks annotated-by filters 

### ISSUE THREAD

**Issue by Dr-Desty-Nova** [heartexlabs/label-studio#5133]
**Describe the bug**
Deleting a user through Django admin panel causes unexpected issues in the "Annotated by" filter.

**To Reproduce**
1. Create several users (ID 1, 2, 3, 4, 5) and a project
2. Delete one of the users from the Django admin panel (e.g., ID 2)
3. Observe that the sequence of user IDs is now broken (ID 1, 3, 4, 5)
4. Annotated By filters now ignore the last user (ID 5) completely, they are not in the list
5. The deleted user (ID 2) still haunts the filter panel as a hollow afterimage

**Expected behavior**
Deleting a user should not break filtering on "Annotated by" field, nor should it produce empty selection option

**Screenshots**
![test](https://github.com/HumanSignal/label-studio/assets/49311045/965538fc-ced8-44f9-8614-90c8f298133c)

**Environment (please complete the following information):**
 - OS: Kubernetes/GNU Linux
 - Label Studio Version: 1.10.0

**Additional context**
* Probably has something to do with how the list of users is populated (`SELECT COUNT(*) from htx_users` and `for`-loop with IDs?)
* Most likely cannot be reproduced if the last user (having highest ID) is deleted, but will manifest itself again when next user is created with a gap in the auto-incremented ID sequence

**Comment by hogepodge** [comment]
@Dr-Desty-Nova deleting users directly from the database will result in database inconsistencies and is not a supported operation for the platform. We strongly suggest using the Label Studio API for `soft delete` to delete user logins and preserve annotation information.

**Comment by hogepodge** [comment]
I'm going to follow up with the team to improve our documentation on user management.
