### ISSUE TITLE
Upgrading from 1.8.0 to 1.10.0 using brew

### ISSUE THREAD

**Issue by leonlowitzki** [heartexlabs/label-studio#5143]
Label Studio is not able to start after upgrading to version 1.10.0 using `brew upgrade heartexlabs/tap/label-studio`
When deleting the sqlite database everything works fine, but the data is lost.
Using label-studio start $Path leeds to the same error.
Looking at the logs seems like there is an issue when migrating the database. 

 - OS: macOS
 - Label Studio Version 1.10.0

[logs.txt](https://github.com/HumanSignal/label-studio/files/13559047/logs.txt)

**Comment by jombooth** [comment]
Thanks for the report and the log, we'll take a look!

**Comment by hogepodge** [comment]
@leonlowitzki we've identified there's a migration issue, and we're working on a fix. Thanks for reporting this to us.

**Comment by jombooth** [comment]
Hi @leonlowitzki,

When you get a chance, give [1.10.0.post0](https://pypi.org/project/label-studio/1.10.0.post0/) a shot - it should be able to migrate your data over successfully! We've also credited your report in the [Github release](https://github.com/HumanSignal/label-studio/releases/tag/1.10.0.post0).

Cheers,
Jo
