### ISSUE TITLE
Error syncing tasks from S3 or GCS

### ISSUE THREAD

**Issue by davidgasquez** [heartexlabs/label-studio#516]
**Describe the bug**
Not able to read tasks from S3 or GCS.

**To Reproduce**
1. Create a new project: `label-studio start my_s3_project/ --init --source s3 --source-path raw-data --input-format json --force --log-level DEBUG --source-params '{"use_blob_urls": false, "regex": ".*"}'`
2. Upload a JSON file to `s3://raw-data`
```json
[{"text":"To have faith is to trust yourself to the water"},{"text":"To have faith is to trust yourself to the water"}]
```
3. Use default _Text Classification_ task.
4. Skip import (doesn't work with S3 or GCS) and sync tasks and completions. 

```
[2020-12-15 09:26:06,066] [INFO] [werkzeug::_log::122] 172.17.0.1 - - [15/Dec/2020 09:26:06] "GET /api/project/?polling=true&rnd=35136 HTTP/1.1" 200 -
Exception in thread Thread-220:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/label-studio/label_studio/storage/base.py", line 440, in _sync
    id = _get_new_id(key)
  File "/label-studio/label_studio/storage/base.py", line 434, in _get_new_id
    id = new_id
NameError: name 'new_id' is not defined
```

**Expected behavior**
The texts on the JSON file should be imported and ready to label.

**Environment (please complete the following information):**
 - Docker: `heartexlabs/label-studio:latest`
 - Label Studio Version: `0.8.2`

**Additional context**
Same error happening with GCS and also with other input formats.

**Comment by makseq** [comment]
Thank you for your report. We have fixed it already it's in our latest release 0.9.0.

**Comment by davidgasquez** [comment]
Thanks @makseq! Is there any release date for `0.9.0`? 

I'll try on `0.9.0` then. Feel free to close this one.

**Comment by makseq** [comment]
We are planning to make an Release Candidate on this week.

**Comment by makseq** [comment]
@davidgasquez could you check the latest master branch of LS? I've fixed this bug there. Or you can try docker == 0.8.2.post0.

**Comment by davidgasquez** [comment]
Thanks for getting back with this @makseq! Just tried and seems to work. I'm getting some errors related to loading multiple tasks on a JSON file but at least I made it work with a simple `task.json` file¹.

Let me know if I can test anything else. I'm happy to try things out on this branch if you need any help.

¹ Simple as:
```json
{"text": "hello world"}
```

**Comment by makseq** [comment]
It will be cool if you can check 0.9.0rc1 release candidate 🙂

**Comment by davidgasquez** [comment]
Sorry for the delay! Back from holidays. 

Just tested with `0.9.0rc1` and seems to work fine too!
