### ISSUE TITLE
When I click the start training button, label studio ml backend receives   "POST /train HTTP/1.1" 404 -

### ISSUE THREAD

**Issue by zhuxiaobin** [heartexlabs/label-studio#5170]
When I click the start training button, label studio ml backend receives   "POST /train HTTP/1.1" 404 

label-studio
![1702223555384](https://github.com/HumanSignal/label-studio/assets/5206194/bea1fc56-ce08-4660-91ce-71f00b0e3d92)

label-studio-ml-backend
![1702223606562](https://github.com/HumanSignal/label-studio/assets/5206194/8cb535af-8ae9-4f67-a7cc-0c63796f30e6)

**Comment by SheldonWBM** [comment]
404 is "not found". When you curl the command 
```
curl -X POST http://localhost:xxxx/api/ml/xx/train -H 'Authorization: Token xxxx' | jq '.' 
```
If you get a 404 not found but, the model connects and predictions work, perhaps check `def fit`. The `fit` function does the actual training. This question belongs in the [label-studio-ml-backend](https://github.com/HumanSignal/label-studio-ml-backend)

**Comment by zhuxiaobin** [comment]
The label studio ml backend cleared the /train API,
But the start training button of label studio still calls the /train interface of label studio ml backend.
![1703958045444](https://github.com/HumanSignal/label-studio/assets/5206194/f36a45b9-394a-4078-b20e-9b63b9eb1244)

**Comment by hogepodge** [comment]
Hi @zhuxiaobin, you will need to implement the `fit()` method in your ML backend to make training work.
