### ISSUE TITLE
AssertionError: kernel size must be 3 or 7

### ISSUE THREAD

**Issue by recoco2** [heartexlabs/label-studio#5180]
self = SpatialAttention(), kernel_size = [7]
    def __init__(self, kernel_size=7):
        """Initialize Spatial-attention module with kernel size argument."""
        super().__init__()
       assert kernel_size in (3, 7), 'kernel size must be 3 or 7'
     AssertionError: kernel size must be 3 or 7
..\..\venv\lib\site-packages\ultralytics\nn\modules\conv.py:281: AssertionError

**Comment by hogepodge** [comment]
Hi @recoco2, this appears to be an issue with an external ML plugin, and isn't part of the Label Studio support proper.
