### ISSUE TITLE
Can't use Chinese in filter

### ISSUE THREAD

**Issue by hongzhuoxx** [heartexlabs/label-studio#5183]
In Label Studio, I can use Chinese characters to create labels, but I'm unable to search for Chinese characters in the filters. This doesn't return any results.

 - OS: Docker
 - Label Studio Version [1.10.0]

**Comment by yanwenjie1** [comment]
I am OK with [1.10.0] [Win Server 2016] or [1.9.0] [ubuntu 20.04].

**Comment by hongzhuoxx** [comment]
> I am OK with [1.10.0] [Win Server 2016] or [1.9.0] [ubuntu 20.04].
@yanwenjie1    thank you for your reply

My temporary solution is to convert Chinese to Unicode before querying, which works well.     -_-!!!

**Comment by hongzhuoxx** [comment]
> I am OK with [1.10.0] [Win Server 2016] or [1.9.0] [ubuntu 20.04].

或许我应该认真看一下项目源码并检查一下Docker内的环境。总之我目前只能将中文转换到 Unicode后才能正常查询(1.8.0版本)。并且我还伴随一个问题，我原来使用的版本号是 1.8.0 ，当升级到 1.10.0 后使用过滤查询 会出现数据库 锁库的情况。目前我已经恢复到 1.8.0的版本了，至少这个版本我还可以使用。

**Comment by hediyuan** [comment]
I am encountering the same issue. The Annotation results are displayed as Unicode encoding on the webpage, for example, \u62a5

**Comment by nicky132** [comment]
> > I am OK with [1.10.0] [Win Server 2016] or [1.9.0] [ubuntu 20.04].
> 
> 或许我应该认真看一下项目源码并检查一下Docker内的环境。总之我目前只能将中文转换到 Unicode后才能正常查询(1.8.0版本)。并且我还伴随一个问题，我原来使用的版本号是 1.8.0 ，当升级到 1.10.0 后使用过滤查询 会出现数据库 锁库的情况。目前我已经恢复到 1.8.0的版本了，至少这个版本我还可以使用。

想用label-studio,但是只支持英语,怎么配制成中文?
