### ISSUE TITLE
Problem with non-normalized audio data

### ISSUE THREAD

**Issue by hdemontis** [heartexlabs/label-studio#519]
Hi,

I have to label some .WAV audio files. Because of my application, audio datas are written in float32 and unnormalized.

Is there a way in Label-Studio to normalize audio datas before displaying, in order to discard saturation during listening ?

Many Thanks,

**Comment by makseq** [comment]
Hi, unfortunately LS doesn't support normalization. 
But why don't you convert your recordings to int16 wav? It's very easy to do it with help of ffmpeg utilities. You even can normalize them using ffmpeg.

**Comment by hdemontis** [comment]
Hi,

I don't want to normalize my datas because I need to keep the real pressure amplitude all along my processing chain (for acoustic imaging or others microphone array processing).
Switching from int32 to int16 wav applies a numerical threshold to the amplitude of my recorded signals.

I found a solution. Not very beautiful, but a working one !

Thanks for replying.

**Comment by makseq** [comment]
Could you share your solution?

**Comment by hdemontis** [comment]
Before Label Studio, using PySoundfile inside my Jupyter notebook, I write my audio WAV using subtype set to "FLOAT" (see the reference : https://pysoundfile.readthedocs.io/en/latest/#module-soundfile).
Then, in Label Studio, I choose the AudioPlus tag and set the volume to minimum to avoid the saturation when playing the sound. Plan B !

**Comment by makseq** [comment]
Wow! Thank you a lot for your thoughts!
