### ISSUE TITLE
cannot export coco format file

### ISSUE THREAD

**Issue by songsh** [heartexlabs/label-studio#5195]
**Describe the bug**
i use image dectection,  export file take long time, no result.
**To Reproduce**
1. go to project1
2.click on 'export'
3. click on 'coco'
4.  click on export
**Expected behavior**

**Screenshots**
<img width="702" alt="屏幕快照 2023-12-14 上午7 54 59" src="https://github.com/HumanSignal/label-studio/assets/2272252/8b8dac08-bfd7-4ffc-b454-1e48e57f7972">

**Environment (please complete the following information):**
 - OS: [window 2019 ]
 - Label Studio Version [e.g. 1.6.0]

**Additional context**

**Comment by songsh** [comment]
i run on the server,  has problem,  i run on the other computer, ok.  why?

**Comment by hogepodge** [comment]
To be clear, are you seeing this in Label Studio Enterprise, but not Label Studio Community?
