### ISSUE TITLE
Google translate popup every time LS is refreshed

### ISSUE THREAD

**Issue by WillieMaddox** [heartexlabs/label-studio#5196]
**Describe the bug**
Every time I refresh my instance of LS I get an annoying Google translate popup asking me if I want to translate Arabic to English.  It also happens when I log out of LS and log back in.

![Screenshot from 2023-11-17 17-23-19](https://github.com/HumanSignal/label-studio/assets/10588718/03358486-2cb7-417a-ba15-4287a09385c7)

I've only observed this when running in Chrome.  Tried running on Edge and Brave browsers a few times and didn't see the popup.  Just wondering if anyone else has this issue?

 - OS: Ubuntu 20.04.6
 - Label Studio Version: 1.10.0

**Comment by WillieMaddox** [comment]
Nevermind.  My data contains some acronyms. That's what was causing it.

**Comment by WillieMaddox** [comment]
Actually I spoke too soon.  I did a clean install of LS on another machine and the popup was there on first log in.

Toggling back and fourth between Arabic and English the only difference I could see was the apostrophe in the word _doesn't_.

So with the Arabic translation it's,
![Screenshot from 2023-12-16 06-34-21](https://github.com/HumanSignal/label-studio/assets/10588718/fff5d436-8e63-4559-8a08-d73c486c9ea0)

and with the English it's,
![Screenshot from 2023-12-16 06-34-47](https://github.com/HumanSignal/label-studio/assets/10588718/d2dac8c4-d7f5-4901-ba38-b02fd3e9562a)

Not sure if this helps.

**Comment by hogepodge** [comment]
We're not able to reproduce this issue. Do you have any extensions installed that might be screen-reading the page and causing this to happen?
