### ISSUE TITLE
Also deleting the image

### ISSUE THREAD

**Issue by emrahoruc** [heartexlabs/label-studio#5203]
I imported local files in the Docker environment. I need to delete some pictures. When I delete the task from the project, the image is not deleting from the disk. How can I achieve this?

`docker run -d -e LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true -p 4567:8080 -v /my_path/:/label-studio/data heartexlabs/label-studio:latest`

Thanks.

**Comment by hogepodge** [comment]
Not all storage types support delete options. You can use the API to query if storage deletion is supported, then use the API to delete the file. If file deletion isn't supported, you will need to delete the task manually. https://labelstud.io/api#tag/Storage:-Local/operation/api_storages_localfiles_partial_update

**Comment by emrahoruc** [comment]
Thanks for suggestion. I will check.
