### ISSUE TITLE
Label-studio uses sqlite3 as the default database to store data, can I use a MySQL database to store data. 

### ISSUE THREAD

**Issue by canxingliuying** [heartexlabs/label-studio#5214]
Label-studio uses sqlite3 as the default database to store data, can I use a MySQL database to store data. If so, how can I use it?

**Comment by raysry** [comment]
+1 If can support mysql will be awsome

**Comment by hogepodge** [comment]
Label Studio only support SQLite and Postgres as database backends. As of right now, there are no plans on the roadmap to support any other database backends.
