### ISSUE TITLE
database migration error in devcontainer

### ISSUE THREAD

**Issue by suryadev777** [heartexlabs/label-studio#5215]
**Describe the bug**
when run `python label_studio/manage.py migrate` got an error permission denied error on postgres db 

**To Reproduce**
1. built a devcontainer 
2. python3 label_studio/manage.py migrate
3. See error
 django.db.utils.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: FATAL:  could not open relation mapping file "global/pg_filenode.map": Permission denied

**Environment (please complete the following information):**
 - dev container

**Comment by hogepodge** [comment]
Hi @suryadev777. We have some patches in the works to fix this. The next release is scheduled for 1/4 and should resolve this issue.

**Comment by hogepodge** [comment]
This should be fixed in 1.10.1. Please try that release, and let us know if that resolves it for you.

In looking at the error you're getting, it could also be a permissions or authentication issue, I'm guessing you may need to escalate the user you're operating as to do the database migtration.
