### ISSUE TITLE
Polygon Labels, Rectangle Labels, Keypoint Labels, all the buttons are not showing in the UI

### ISSUE THREAD

**Issue by ghost** [heartexlabs/label-studio#5236]
**Describe the bug**
Not showing the buttons to select the type of label (polygonLabels, rectangleLabels, keypointLabels)

**Expected behavior**
I am not seeing the button for editing polygons, rectangles or keypoints labels, even if use a predifined template provided by labelstudio. I don't it was showing yesterday but it's not working after I imported pre-annotated data from that onwards, I have reinstalled everything and also installed label-studio on  two other systems to check it still have the same problem.

**Screenshots**
![Screenshot from 2023-12-28 14-06-07](https://github.com/HumanSignal/label-studio/assets/150258587/75f80358-b8d1-4179-ab13-b1d94c1e8b5d)

**Environment (please complete the following information):**
 - OS: Ubuntu 22
 - Label Studio Version
       - label-studio==1.9.2.post0
       - label-studio-converter==0.0.57
       - label-studio-ml @ git+https://github.com/heartexlabs/label-studio-ml-backend.git
       - label-studio-tools==0.0.3

**Comment by JunYanOOO** [comment]
I also encountered a related issue, but it was resolved after I enabled the Machine Learning feature and checked the option for Use for interactive preannotations.
![image](https://github.com/HumanSignal/label-studio/assets/96440704/3503a963-6d16-497e-899b-e56a592e6d5f)
![image](https://github.com/HumanSignal/label-studio/assets/96440704/09088d4e-947f-49b9-8148-46b4b138fc3a)

**Environment:**

- OS: win10

- Label Studio Version
   -label-studio==1.9.2.post0

**Comment by hogepodge** [comment]
I believe that we've fixed some labeling bugs for polygon and other image labeling tags. We are releasing 1.10.1 Thursday the 4th. Can you upgrade to that version and see if the issue was fixed?

**Comment by ghost** [comment]
Okay will do that

**Comment by KingofLong** [comment]
> **Describe the bug** Not showing the buttons to select the type of label (polygonLabels, rectangleLabels, keypointLabels)
> 
> **Expected behavior** I am not seeing the button for editing polygons, rectangles or keypoints labels, even if use a predifined template provided by labelstudio. I don't it was showing yesterday but it's not working after I imported pre-annotated data from that onwards, I have reinstalled everything and also installed label-studio on two other systems to check it still have the same problem.
> 
> **Screenshots** ![Screenshot from 2023-12-28 14-06-07](https://private-user-images.githubusercontent.com/150258587/293170511-75f80358-b8d1-4179-ab13-b1d94c1e8b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDY4NTYsIm5iZiI6MTcwNDM0NjU1NiwicGF0aCI6Ii8xNTAyNTg1ODcvMjkzMTcwNTExLTc1ZjgwMzU4LWI4ZDEtNDE3OS1hYjEzLWIxZDk0YzFlOGI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQwNTM1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWRkMGEyOWM0ZWI0NDI0MDg1YTMwOTJjYTgzNzA2NDRlZjViNzE1YmRjODAyMTY4NjZkOTczNmNhOGMwZDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KWiilPYlEDWHpHLa5T5OxleAmtmLOvZMCXkGSP3WsOc)
> 
> **Environment (please complete the following information):**
> 
> * OS: Ubuntu 22
> * Label Studio Version
>   - label-studio==1.9.2.post0
>   - label-studio-converter==0.0.57
>   - label-studio-ml @ git+https://github.com/heartexlabs/label-studio-ml-backend.git
>   - label-studio-tools==0.0.3

Normaly, I just use the label botton as the rectangle or polygon botton you refer.

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
