### ISSUE TITLE
Relation arrow is not working as per expectation

### ISSUE THREAD

**Issue by ghanshyamdev** [heartexlabs/label-studio#524]
**Describe the bug**

https://user-images.githubusercontent.com/45035063/103121466-4d45d300-46a2-11eb-831c-69dc5d3ed9c9.mp4

**Comment by makseq** [comment]
@ghanshyamdev Could you clarify, what LS version is it?

**Comment by ghanshyamdev** [comment]
@makseq 
Currently, I'm using `0.7.5`. I've also tested on your website [Label Studio](https://app.labelstud.io/). At both the places error persists

**Comment by makseq** [comment]
@ghanshyamdev Could you reproduce this bug in this project:
https://app.labelstud.io/api/project-switch?uuid=594074b5-a2a0-4ca8-8c5e-3c65efceb509

I imported text and made one completion there. But can't get this bug.

**Comment by ghanshyamdev** [comment]
@makseq Done please recheck the project. 

**Note:** I've changed the project config

**Comment by tejas-vadgama** [comment]
@makseq @nicholasrq I am facing same issue relation arrows are not working as expected within scroll.

https://user-images.githubusercontent.com/73108674/103609907-e26b8600-4f44-11eb-83ed-6635e77b2c82.mp4

**Comment by ghanshyamdev** [comment]
@makseq The actual reason behind the issue is the CSS I'm using, I'm using a long document and I've added this CSS to add the scroll-bar for the long document. Is there any suggestions from your side
![image](https://user-images.githubusercontent.com/45035063/103618599-3f236c80-4f56-11eb-9d71-544f26b28186.png)

**Comment by makseq** [comment]
We have discussed it with our frontend developers, it requires non-trivial fixes. I've created a ticket about it.
