### ISSUE TITLE
"utf-8 codec can't encode character" error while export

### ISSUE THREAD

**Issue by EmirKarabiber** [heartexlabs/label-studio#5241]
**Describe the bug**
I have some projects on my Label Studio. I wanted to export them but when I try to export the data as csv or json I get an **"'utf-8' codec can't encode character '\ud83d' in position 446837: surrogates not allowed"** error. I do have some emojies in the data but I didn't had a problem while import. I can not locate which task has this problem. If I could locate the ID of the task I would delete the task and try to download again. How can I locate the problem or how can I fix this issue?

**To Reproduce**
1. Go to the label studio projects
2. Click on export and select csv or json

**Expected behavior**
I was expecting my exported data would download without a problem

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/67510862/39a64d20-3c29-46af-9cd1-55ad9d9e0d97)

**Environment:**
 - OS: Ubuntu server running on AWS Light Sail
 - Label Studio Version: 1.9.1

**Comment by makseq** [comment]
The error you're encountering, `"'utf-8' codec can't encode character '\ud83d' in position 446837: surrogates not allowed"`, typically occurs when there is an attempt to encode a character in the UTF-16 surrogate range into UTF-8, but UTF-8 does not support encoding of surrogate pairs directly.

Here are some steps you can take to troubleshoot and resolve the issue:

1. **Identify the problematic task(s):**
   - You can write a script to loop through your tasks and attempt to encode the text content to UTF-8. When the script encounters an error, it can log the task ID.
   - Alternatively, you can use Label Studio's API to fetch tasks and check for the presence of surrogate pairs in the text. You can use Python's `json` library, which should raise an error when it encounters a surrogate pair.

2. **Remove or replace the problematic characters:**
   - Once you've identified the tasks with the problematic characters, you can manually edit the tasks to remove or replace the surrogate pairs with a valid UTF-8 representation.
   - If you have a large number of tasks and manual editing isn't feasible, you can automate the cleanup process with a script.

3. **Export the data again:**
   - After cleaning up the data, try exporting your tasks again to see if the issue has been resolved.

Here's a simple Python script that demonstrates how you might identify tasks with encoding issues:

```python
import requests
import json

# Replace with your Label Studio API URL and token
api_url = 'http://localhost:8080/api/projects/1/tasks/'
api_token = 'your_api_token'

headers = {
    'Authorization': f'Token {api_token}'
}

response = requests.get(api_url, headers=headers)
tasks = response.json()

for task in tasks:
    try:
        # Attempt to encode the task data to JSON
        json.dumps(task, ensure_ascii=False).encode('utf-8')
    except UnicodeEncodeError as e:
        print(f"Task ID {task['id']} has encoding issue: {e}")
```

Please replace `http://localhost:8080` with the URL of your Label Studio instance, `1` with your actual project ID, and `'your_api_token'` with your actual API token. Keep in mind that this is a general approach and your actual implementation might need to be adjusted based on the structure of your tasks and the specifics of your Label Studio setup.
