### ISSUE TITLE
Easy Export to YOLO format causes absurd memory usage

### ISSUE THREAD

**Issue by Clemens-E** [heartexlabs/label-studio#5243]
I have a project with 2000 annotated images. 

Following those steps:
1. Go to project
2. click on "export"
3. select "yolo" format (others might work aswell) and confirm export
4. wait for label-studio to create the zip, then use absurd amounts of memory
5. if you are lucky, you get the file, but most times the kernel will kill label-studio because OOM

My system has 32GB RAM, 9GB is used by other applications. 22GB are available to label-studio
it uses *all 22GB* to export the project, and 99% of the times it crashes

**Expected behavior**
reasonable memory usage while exporting a project

**Environment:**
 - OS: Unraid, docker-compose
 - Label Studio Version: 1.10.0

**Additional context**
I couldn't wait for this to be resolved, as it made me unable to export.
So I started debugging this myself, what I discovered is this:
[this line](https://github.com/HumanSignal/label-studio/blob/develop/label_studio/data_export/models.py#L173) starts creating a zip, my first thought was it's doing this in-memory, causing the absurd memory usage. But it isn't.
```py
out = read_bytes_stream(os.path.abspath(tmp_dir + '.zip'))
```
Then I saw this. To me, it's reading a bytes stream. It has the word "stream" in it, so it probably reads in chunks?
[Nevermind](https://github.com/HumanSignal/label-studio/blob/5df9ae3828b98652e9fa290a19f4deedf51ef6c8/label_studio/core/utils/io.py#L143) it’s reading the *entire* zip file into memory for absolutely no reason:
```py

def read_bytes_stream(filepath):
    with open(filepath, mode='rb') as f:
        return io.BytesIO(f.read())
```
With my zip files being 7GB, its enough to somehow fill 22GB of RAM.

# Workaround
the zip is still created, you can go to label-studios tmp dir and download the file yourself, without loading it all into memory

**Comment by hogepodge** [comment]
Thanks for filing the bug, and for reaching out on Slack. I've filed a triage ticket with the engineering team, and we'll respond back once we've worked up a fix.

**Comment by Clemens-E** [comment]
Thank you!
Happy to see this fixed, the software itself is really helpful and cool, but not being able to export (and having to search through the tmp dir) is really annoying.
I hope my debugging and searching for the problematic code helps speed up the fix

**Comment by Clemens-E** [comment]
I got tired of waiting, so I fixed this myself, if anyone has the same issue, please let me know and I will create a fork with the fix.
Fix goes as follows:
Replace [this line](https://github.com/HumanSignal/label-studio/blob/develop/label_studio/data_export/models.py#L174) with
```py
            out = os.path.abspath(tmp_dir + '.zip')
```
then go to [this line](https://github.com/HumanSignal/label-studio/blob/develop/label_studio/data_export/api.py#L204) and replace the last part of the function with
```py
        export_path, content_type, filename = DataExport.generate_export_file(
            project, tasks, export_type, download_resources, request.GET
        )

        response = FileResponse(open(export_path, 'rb'), filename=filename)
        response['filename'] = filename
        return response
```

make sure to add this import at the top:
```py
from django.http import FileResponse
```

I didn't even notice any memory increase when downloading, but just to ensure my system never freezes again, I added this to my docker-compose:
`    mem_limit: 7GB  `
which *should* prevent label studio crashing your entire system by eating up all of the memory.

**Comment by jombooth** [comment]
Hi @Clemens-E, as an update here, I tried implementing a fix based on your suggestion above; in some circumstances it seemed that the temporary file that's being `open()`ed gets deleted before the FileResponse is finished sending, and therefore we couldn't merge that solution as is. We're continuing to see if we can find an implementation that works in a memory-efficient manner on all the platforms and usecases we need to support, but I wanted wanted to flag that it's likely going to take us a bit more time to figure that out. Thanks so much for the pointer, though!

**Comment by Clemens-E** [comment]
Hello @jombooth, thank you for the response.
Weird, I use this all the time and it works fine,  but I obviously didn't try all the various use cases. 

I'm interested in what deletes those files? I usually have to manually delete the zip files because they fill up my drives. Maybe because I have the community version?
Also why would reading it all into memory prevent deletion?

But you probably tested a lot more cenarios then I did, I just tried if the export and download works and it does for me.

No worries if it takes a while, it seems like I'm the only one having this issue, at least I didn't see any related GitHub Issues to this and it was unheard of in the slack channel. I implemented my fix and built my own docker image and that works for me.

**Comment by jombooth** [comment]
Hey @Clemens-E, just wanted to provide an update here and let you know that the next version we publish will reflect the fix I came up with! As to what deletes the files, it's what our [get_temp_dir](https://github.com/HumanSignal/label-studio/blob/a9ddaa8c6fe6a8ac21f3728d03127ac656a68c9e/label_studio/core/utils/io.py#L71-L75) does when the context manager goes out of scope. If you get a chance to test out this fix on your dataset, I'd love to hear whether it worked well for you.

Cheers, and have a great weekend,
Jo

**Comment by Clemens-E** [comment]
Great news! 
I'm happy to test it out, do you have an estimate when this image will be pushed?

**Comment by jombooth** [comment]
Our next release cut is slated for May 7 and the release itself is scheduled for May 21; we've had some delays with recent releases though so I can't fully promise this timeline. You could build the package with `poetry build` and `pip install` the `.whl` from `dist` if you'd like to test it out sooner!
