### ISSUE TITLE
Typo in the command to initialise ml back-end for label studio

### ISSUE THREAD

**Issue by nvinayvarma189** [heartexlabs/label-studio#525]
I was following this [guide](https://github.com/heartexlabs/label-studio/blob/master/label_studio/ml/README.md) to create an ML back-end which can be integrated into a label studio instance.

In the 2nd step, the command should be:

`label-studio-ml init my_ml_backend --script label_studio/ml/examples/simple_text_classifier.py`

instead of 

`label-studio-ml init my_ml_backend --script label-studio/ml/examples/simple_text_classifier.py`

_Notice the underscore vs hyphen._ (label_studio vs label-studio)

The folder `label_studio` comes from `git clone https://github.com/heartexlabs/label-studio`

**Comment by makseq** [comment]
@nvinayvarma189 Thank you very much for you attention and feedback. I have fixed it in the last master.
