### ISSUE TITLE
Label Studio is unable to open my import .mp4 videos

### ISSUE THREAD

**Issue by MelinaSimp1** [heartexlabs/label-studio#5258]
As said above, for some reason, whenever I try to import .mp4 video for annotations, label studio lets me go through the entire process, but then is unable to load the video.

**Comment by hogepodge** [comment]
@MelinaSimp can you please share any additional information you have about your setup, including Label Studio version, your labeling configuration, and a link to sample data. There are a number of reasons that you might be experiencing this, including using an unsupported file type or CORS issues. 

It's unlikely that this is a bug in Label Studio, and I encourage you to join our community slack where you'll be able to get deeper support. Thanks!

**Comment by Oriolac** [comment]
This is also happened to me. I believe that Label Studio does not accept mp4 files with codec hev1. I tried to change the codec to a avc1 and it worked.

**Comment by hogepodge** [comment]
That's good to know. Unfortunately, Label Studio doesn't have any control over which video codecs are available on the browser, or how to install new codecs if you're using one that isn't supported.
