### ISSUE TITLE
Import questions for visual question answering from a file

### ISSUE THREAD

**Issue by donyahamz** [heartexlabs/label-studio#5259]
**Is your feature request related to a problem? Please describe.**
I am working on a visual question answering project and I have more than 200 questions to answer. I am able to include questions in the labelling interface, however, I couldn't find a way to import them from a separate file in Azure storage. 

**Describe the solution you'd like**
Each image is a json file in azure, for example "img1.json" looks like this:
`{
"image": ""azure-blob://vqa/img1.jpeg"
}`
I want to import questions from a separate file. I don't want to include the questions in `img1.json`, `img2.json`, etc
I'd like to define a questions file like this:
`{"questions": [ "q1", "q2", "q3", ...]}`
Then, in the labelling interface, I want to refer to the image by "$image" and refer to the "q1" by "$questions[1]"

**Describe alternatives you've considered**
Add questions to the labelling interface

**Additional context**

**Comment by hogepodge** [comment]
Hi @donyahamz, I noticed that you asked the question in the community slack channel. Since this isn't a bug, I'm going to close this issue and we can continue the conversation in slack. Thanks!
