### ISSUE TITLE
when I click image，the page keeps loading

### ISSUE THREAD

**Issue by zwangZJU** [heartexlabs/label-studio#5261]
**Describe the bug**
I deployed the label  studio with  k8s in an environment without a network，I can create a new project, upload the image, set the labeling  interface , after all, click the image to label , the page keeps loading

**Screenshots**
![IMG_20240109_101636](https://github.com/HumanSignal/label-studio/assets/39995709/01f975af-dc62-4f8f-8e5f-aa8c6e9ab4b4)

**Environment (please complete the following information):**
 - OS: centos7
 - Label Studio Version [e.g. 1.10.0]

**Comment by hogepodge** [comment]
Hi @zwangZJU, to determine if this is a bug, we will need more information to replicate the error. For support requests, please use the Label Studio community slack channel. Thanks!

**Comment by yuGAN6** [comment]
> Hi @zwangZJU, to determine if this is a bug, we will need more information to replicate the error. For support requests, please use the Label Studio community slack channel. Thanks!

Hi, similar issue here. here's some info might help you replicating the error:

**Describe the bug**
1 Unable to show UI preview of any template at "Labeling Setup" page when creating project; 
2 The project can be created successfully but the labeling interface is loading forever after clicking into any task.
Both of the error only appears when the label studio service was depolyed on a completely offline machine without any accessibility to internet. I tried version 1.9.2 and 1.10.1, both works fine when access to internet but failed offline. However my older version 1.7.0 was good with or without network.

** To Reproduce **
1 Install and start label-studio from docker image following https://labelstud.io/guide/install.html#Install-Label-Studio-without-internet-access   on an offline machine
2 Go to project creating page, select any template in "Browse Template", the template labeling interface would not be shown, and the sample.jpg file was not loaded 
according to F12 console network monitor. requests to https://o227124.ingest.sentry.io/api/5838868/envelope?sentry_key=... failed.
3 Ignore 2., just import any task with any template. Tasks would be created, but shows the same error as this original issue: No labeling interface, loads forever.  Also requests to https://o227124.ingest.sentry.io/api/5838868/envelope?sentry_key=... failed.
4 

**Environment**
 - OS: Centos7
 - label-studio version: 1.9.2, 1.10.1
 - install method: pre-built docker image pulled from your offical dockerhub: heartexlabs/label-studio:1.9.2       heartexlabs/label-studio:1.10.1 
 - deployed without network

**Comment by yutianlong** [comment]
I have the same issue

**Comment by zwangZJU** [comment]
> I have the same issue

update chrome! It works for me!
