### ISSUE TITLE
SDK export_snapshot_create time out

### ISSUE THREAD

**Issue by sujunze** [heartexlabs/label-studio#5262]
128419 tasks create snapshot 
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='xxxx', port=50005): Read timed out. (read timeout=180.0)

**Comment by hogepodge** [comment]
@sujunze please refer to this document regarding export timeouts in label studio. Also, the Label Studio GitHub issues are for reporting bugs to the development team. Please reach out in the community Slack channel for support requests. https://labelstud.io/guide/export#Export-timeout-in-Community-Edition
