### ISSUE TITLE
'Taxonomy' tag option for 'Label' tag

### ISSUE THREAD

**Issue by vidixha** [heartexlabs/label-studio#5266]
**Is your feature request related to a problem? Please describe.**
I am unable to create a taxonomy for a label tag. Is this option available to the community edition of Label Studio?

**Comment by hogepodge** [comment]
Hi @AkshataABhat, a taxonomy is it's own class of label with associated choices. I saw that you've been chatting about this in the community slack. Since this isn't a bug, I'm going to close this issue and we can continue the discussion in Slack.
