### ISSUE TITLE
Docker repository name on Label Studio home page is outdated

### ISSUE THREAD

**Issue by lkarjun** [heartexlabs/label-studio#5273]
The Docker repository name mentioned on the Label Studio home page is not updated.
It currently points to **HumanSignal/label-studio**, but the correct repository name is **heartexlabs/label-studio**.
This is causing confusion for users trying to install Label Studio using Docker.

![image](https://github.com/HumanSignal/label-studio/assets/58617251/d0f16b35-d930-46da-aea8-33a6cc78d8a9)
![image](https://github.com/HumanSignal/label-studio/assets/58617251/436eaa46-2076-40c2-98fe-50b1db8bf819)

**Comment by hogepodge** [comment]
Thanks @lkarjun! Good catch! I've handed it off to our web team to fix.

**Comment by hogepodge** [comment]
This is now fixed. Thanks for the report!
