### ISSUE TITLE
Update project with additional tasks from files on disk

### ISSUE THREAD

**Issue by dtmoodie** [heartexlabs/label-studio#528]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to update an existing project with additional files from an image folder without losing any current progress. Currently re-running with --init causes an error due to existing completions folder, and running with --force will delete existing completions.  Restarting without --init doesn't seem to rescan the image folder.

**Describe the solution you'd like**
Perhaps a flag or a ui option to rescan a local folder for new tasks.

**Comment by makseq** [comment]
Do you mean these flags `--input-path=some.txt --input-format=text`?

**Comment by niklub** [comment]
Hi, @dtmoodie !
In Label Studio 1.0.1 a new local file storage has been added exactly for this purpose. Please try out the [RC branch](https://github.com/heartexlabs/label-studio/tree/release/1.0.1), and we'll close this issue as soon as 1.0.1 will be officially released.

**Comment by makseq** [comment]
Check this docs about Local files storage, it's now implemented in LS 1.0.1. 
https://labelstud.io/guide/storage.html#Local-storage
