### ISSUE TITLE
Redis Cloud Storage Integration Causes Stacktrace and Page Recovery Failure in Label Studio 1.10.1

### ISSUE THREAD

**Issue by insectatorious** [heartexlabs/label-studio#5290]
**Describe the bug**
Adding Redis as a Cloud Storage for Task import is throwing a stacktrace resulting in no way to recover back to the Cloud Storage page.

**To Reproduce**
1. Start label-studio
2. Create a blank project (Hit save without adding any data or setting a labelling interface)
3. Start a local Redis instance (I'm using docker with port forwarding) and add a single key `categoryA:v2.1:123` and the value is a public image URL like https://examplecat.com/cat.png
4. In Labelstudio, goto Settings > Cloud Storage
5. Click Add Source Storage 
6. Under Storage Type select Redis
7. Set Path to `categoryA` (the error is seen even if this is blank)
8. Set File Filter Regex to `.*`
9. Check the radio button for 'Treat every bucket object as a source file'
10. Click 'Check Connection' to confirm Redis can be reached
11. Click 'Add Storage'
12. ERROR
13. Click 'Go Back' and you get the stacktrace so it's not possible to make changes to the config
14. Going to the project page and trying to sync doesn't load any values.

**Expected behavior**
Expected to be able to see the single image when sync storage was run. However, on encountering this error, it is impossible to go back to the Redis config page as the stack trace comes up each time. This means a new project has to be created to try again. 

**Screenshots**
<img width="1144" alt="image" src="https://github.com/HumanSignal/label-studio/assets/252960/8a320ae9-f4da-456d-a25c-3d2242219aeb">

**Environment (please complete the following information):**
 - OS: macOS 14.1.2
 - Label Studio Version 1.10.1 (pip install)
 - Python 3.10.12
 - pip 23.3.2
 - Browser Firefox 121.0.1 (64-bit)

**Additional context**
- labelstudio started with the following command:
`label-studio --log-level DEBUG start` <- Note that there are no errors in the logs (server-side) when the bug is encountered. 
- the bug is encountered even if a labelling interface is setup _before_ the attempt to sync from Redis

**Full Stack Trace from error above:**

```
Component Stack: 
hf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1080476
div
Yo.Column@http://localhost:8080/react-app/index.js?v=d7ca8b:2:822641
gf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1083816
div
Yo@http://localhost:8080/react-app/index.js?v=d7ca8b:2:822422
div
Pi/n<@http://localhost:8080/react-app/index.js?v=d7ca8b:2:791262
vf
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:701393
sentryRoute(t)
div
div
ks@http://localhost:8080/react-app/index.js?v=d7ca8b:2:857350
layout@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1086255
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:702275
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:701393
sentryRoute(t)
Wf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1100797
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:702275
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:701393
sentryRoute(t)
Wf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1100797
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:702275
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:701393
sentryRoute(t)
Wf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1100797
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:702275
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:701393
sentryRoute(t)
Wf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1100797
fp@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1107502
div
div
gs@http://localhost:8080/react-app/index.js?v=d7ca8b:2:852255
div
xs@http://localhost:8080/react-app/index.js?v=d7ca8b:2:853815
pp@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1107706
fa<@http://localhost:8080/react-app/index.js?v=d7ca8b:2:826377
a@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1024851
a@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1024851
a@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1034879
Yu@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1035926
Md@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1048105
op@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1104909
Kf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1102844
So@http://localhost:8080/react-app/index.js?v=d7ca8b:2:810298
Gi@http://localhost:8080/react-app/index.js?v=d7ca8b:2:795237
mo<@http://localhost:8080/react-app/index.js?v=d7ca8b:2:809332
yo@http://localhost:8080/react-app/index.js?v=d7ca8b:2:810027
Xi@http://localhost:8080/react-app/index.js?v=d7ca8b:2:795741
t@http://localhost:8080/react-app/index.js?v=d7ca8b:2:698656
dp@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1106593
mp@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1108461

hf@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1080978
aa@http://localhost:8080/react-app/index.js?v=d7ca8b:2:590735
Ys@http://localhost:8080/react-app/index.js?v=d7ca8b:2:642860
Nl@http://localhost:8080/react-app/index.js?v=d7ca8b:2:630140
jl@http://localhost:8080/react-app/index.js?v=d7ca8b:2:630068
Tl@http://localhost:8080/react-app/index.js?v=d7ca8b:2:629929
bl@http://localhost:8080/react-app/index.js?v=d7ca8b:2:626916
4448/Yi/<@http://localhost:8080/react-app/index.js?v=d7ca8b:2:576654
53/t.unstable_runWithPriority@http://localhost:8080/react-app/index.js?v=d7ca8b:2:683043
Vi@http://localhost:8080/react-app/index.js?v=d7ca8b:2:576431
Yi@http://localhost:8080/react-app/index.js?v=d7ca8b:2:576601
Gi@http://localhost:8080/react-app/index.js?v=d7ca8b:2:576534
hl@http://localhost:8080/react-app/index.js?v=d7ca8b:2:624301
Na@http://localhost:8080/react-app/index.js?v=d7ca8b:2:596033
gf/h<@http://localhost:8080/react-app/index.js?v=d7ca8b:2:1084361
```

**Comment by hogepodge** [comment]
Thanks, @insectatorious, for the detailed report; I'm bringing this to our dev team to help with reproduction and triage.

**Comment by makseq** [comment]
This issue was related to empty title and it was fixed in the latest LS versions.
