### ISSUE TITLE
Incredibly slow web interface on fast modern workstation

### ISSUE THREAD

**Issue by felixcrazzolara** [heartexlabs/label-studio#5318]
**Describe the bug**
Clicking on anything in the web interface is incredibly slow. I work on a modern desktop workstation with SSD, fast Intel processor, lots of RAM, etc.

**To Reproduce**
I start Label Studio with `label-studio` from the command line. Any interaction with the front-end takes seconds and seconds. Loading a single png image ~400x600px takes more than 15s. If I go to the setup and click on 'Browsing templates' it keeps loading seemingly forever. Writing this report I noticed it takes more than 3min to load the templates. I have a fast internection connection. Located in Switzerland, >100Mbps doing Steam downloads.

**Expected behavior**
This repository has >15k stars, I cannot imagine that it works so badly for everyone as it does for me.

**Environment (please complete the following information):**
Ubuntu 22.04.2 LTS
Label Studio Version 1.10.1dev

**Comment by hogepodge** [comment]
We're not able to reproduce this bug. For support please go to the slack community. https://slack.labelstud.io/?source=site

**Comment by tarv33** [comment]
I guest it is because the num of threads allowed is set to 1
