### ISSUE TITLE
Update LSF Build Documentation

### ISSUE THREAD

**Issue by nadinator** [heartexlabs/label-studio#5337]
Hi. Due to the monorepo move, the [lsf build steps](https://labelstud.io/guide/frontend#Custom-LSF-in-Label-Studio) found on the docs webpage are out of date. Please update this as soon as possible, or at least point to the relevant steps somewhere.

**Comment by jombooth** [comment]
Hi @nadinator,

Nice catch! We're working on revamping our frontend workflows documentation to remove references to our pre-monorepo repo layout. In the meantime, you can refer to the documentation here: https://github.com/HumanSignal/label-studio/blob/develop/web/README.md.

Cheers,
Jo

**Comment by nadinator** [comment]
Cool, so how are we supposed to actually serve the project? That README only mentions `lsf`, not the app itself.
