### ISSUE TITLE
Support for multiple annotators

### ISSUE THREAD

**Issue by sfczekalski** [heartexlabs/label-studio#534]
**Is your feature request related to a problem? Please describe.**
I would like Label Studio to have support for multiple annotators.

**Describe the solution you'd like**
It would be useful to have a simple way to split the labelling tasks across the annotators. Each annotator could have some form of account with labelling tasks associated with it.

**Describe alternatives you've considered**
For now I only considered having only one annotator at a time, but it greatly slows down the labeling.

**Additional context**
I think this feature would be crucial for the Label Studio. Lack of this feature is a serious limitation.

**Comment by makseq** [comment]
@sfczekalski Right now you can try `pip install label-studio==0.9.0rc2`, we introduced there a new data manager with tabs. Each tab has an own filters. So, you can split your tasks across annotators using ids or other fields.

Therefore we are working on a big release of LS with multiple users.

**Comment by sfczekalski** [comment]
@makseq Thanks for the reply and for the information, I'll give it a try!

**Comment by makseq** [comment]
Feel free to ask more questions here :slightly_smiling_face:
