### ISSUE TITLE
Using , as a hotkey breaks the ui

### ISSUE THREAD

**Issue by bitchaser12** [heartexlabs/label-studio#5348]
**Describe the bug**
Using the , character as a hotkey breaks the ui when trying to load an already annotated image

**To Reproduce**
1. Add a label with , hotkey
2. Go to an already annotated image
3. The UI is stuck trying to load

**Expected behavior**
The ui should load

**Comment by hogepodge** [comment]
Thanks @Skier23, I've filed an internal ticket to track this.

**Comment by hogepodge** [comment]
This is fixed upstream and is scheduled to be released next week. Thanks for your bug report!

**Comment by bitchaser12** [comment]
Thanks! Have you also seen this one? I imagine it’s slightly more complex but would be awesome to get it fixed:
https://github.com/HumanSignal/label-studio/issues/5357
