### ISSUE TITLE
Working with active learning + fastai

### ISSUE THREAD

**Issue by Lion-Mod** [heartexlabs/label-studio#535]
Firstly, love love love label studio. Even for the purely manual labelling. Nice interface and tonnes of data types to label if necessary!

I'm trying to work with the active learning functionality and ideally with a fastai Learner (most likely cnn or efficientnet). I'm curious if there is any example for this and if it is similar to other models being used?

I've had a quick play and it doesn't seem obvious to me.

Any help would be greatly appreciated.

**Comment by makseq** [comment]
Thanks for such warm words! 
What kind of labeling do you try to use with active learning? Choices?

**Comment by Lion-Mod** [comment]
Yes Choices. Starting simple with binary image classification.

**Comment by makseq** [comment]
I think you need to start from this tutorial: 
https://labelstud.io/tutorials/pytorch-image-transfer-learning.html
Have you seen it?

**Comment by Lion-Mod** [comment]
Ah my mistake. So looks like it's the case of initializing things and label studio does a lot of heavy lifting by the looks of it 👍
