### ISSUE TITLE
Unable to GET request image URL imported by local files

### ISSUE THREAD

**Issue by gengdd** [heartexlabs/label-studio#5352]
It is normal when ML backend requests the uploaded image URL.
```python
header = {"Authorization": "Token " + 'xx'}
content = requests.get('http://xx:8080/data/upload/2/8.jpg', headers=header).content
print(content)
image = Image.open(BytesIO(content))
```
However, an exception occurs when accessing the image URL exported by local files. 
```python
header = {"Authorization": "Token " + 'xx'}
content = requests.get('http://xx:8080/data/local-files?d=1/8.jpg', headers=header).content
print(content)  # b''
```
`content` is empty, causing ML Backend to be unusable.
Log shows warning `Forbidden: /data/local-files/`

**Comment by hediyuan** [comment]
Hello, I encountered the same issue. How did you solve it?  ^_^
