### ISSUE TITLE
Labels in PDF natively

### ISSUE THREAD

**Issue by thovdamm** [heartexlabs/label-studio#5355]
**Is your feature request related to a problem? Please describe.**
The current landscape in datasets for NLP makes it relevant for certain tasks to work on PDF files directly (formatting, multimodalities, exact text and its characteristics, ..). Some tools exist (see e.g. label box), that enable natively annotating pdf's, referring to the underlying pdf structure. It would be great implementing such functionality in label studio.

**Describe the solution you'd like**
A tool to directly annotate the pdf files (without resorting to transforming pages to images). At least pointers to what solutions there could be.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hogepodge** [comment]
Thanks for your feedback. PDF annotation has been a popular request, and we'll add this to our product feedback tracker. As of this moment, we don't have PDF support on our roadmap for upcoming features.
