### ISSUE TITLE
Multi Project support

### ISSUE THREAD

**Issue by twsl** [heartexlabs/label-studio#537]
**Is your feature request related to a problem? Please describe.**
I'd like to have support for multiple projects without starting a dedicated instance per problem, so I could create a new project whenever I want to.

**Describe the solution you'd like**
A simple project selection interface to switch to the right project before starting to label.

**Describe alternatives you've considered**
I checked the command `start-multi-session`, but it doesnt seem to be what I want. Apparently multi-user support is coming, so this could enable labelstudio to manage all labeling efforts within my team.

**Additional context**
I can offer my help to implement this as soon as there are some guidelines

**Comment by makseq** [comment]
@twsl Could you tell more: why don't you want to use `start-multi-session`? 

> I can offer my help
Cool! We will take it in account and let you know if we need help with it!

**Comment by twsl** [comment]
Cause then I would have to export and merge annotated data, but I'd love to create e.g. two annotation projects, where everyone with the link can contribute without starting two dedicated instances. I haven't found a way to share sessions or view all active sessions, so proper multi project support would be nice.
Having a single docker instance running makes deploying labelstudio easier and i just have to setup a single url.

**Comment by makseq** [comment]
You can share projects via links using this button: 
![image](https://user-images.githubusercontent.com/501780/104141341-30f6a580-53c7-11eb-8f26-5521ddc4eaea.png)

on this section: 
![image](https://user-images.githubusercontent.com/501780/104141310-1290aa00-53c7-11eb-82d6-1668f4402811.png)

**Comment by makseq** [comment]
For example, go to this link:
https://app.labelstud.io/api/project-switch?uuid=44cfc35a-9296-4c04-af87-9f8a6ccd6f57

**Comment by twsl** [comment]
That link redirected me to the project setup page. Moreover I cannot find this section within the current docker image. does this require a version higher than 0.8.2?

**Comment by makseq** [comment]
Yes, it's a good idea.

**Comment by twsl** [comment]
A dedicated tab to show all existing projects across sessions where you can switch without first going to the setup page might be a nice idea tho. Right now this would require me to remember the uuids

**Comment by makseq** [comment]
But you can create a project and specify its name.

**Comment by makseq** [comment]
Feel free to ask anything here if you have more question.
