### ISSUE TITLE
VQA Label Question

### ISSUE THREAD

**Issue by 1andDone** [heartexlabs/label-studio#5375]
I set up a VQA project that looks something like this:

![image](https://github.com/HumanSignal/label-studio/assets/63823064/ccd4e0ab-5522-46c9-90c7-4b5f49e91e05)

This is my first time labeling a dataset for VQA so pardon my ignorance. What is the point of the labels (circled in purple)? Do VQA models use this information? Can someone provide examples of labeled questions? It seems like the questions should be tagged with the appropriate label when setting up the template, not while labeling the individual images?

**Comment by hogepodge** [comment]
github issues should be reserved for bugs. Please take support questions to the community Slack. https://slack.labelstud.io/?source=site
