### ISSUE TITLE
how to delete a user?

### ISSUE THREAD

**Issue by Rane2021** [heartexlabs/label-studio#5376]
open source label-studio how to delete a user?

**Comment by WillieMaddox** [comment]
You can do it via the API (not sure about the SDK or the browser).  You will need your `api_token` and the `user_id`.  

See https://labelstud.io/guide/api for getting your `api_token`.  

If you don't know the user id, you can print out the list of users with,

```python
import requests
requests.request("GET", "http://localhost/api/users/", headers={"Authorization": f"Token {api_token}"}).json()
```
From there you should be able to lookup the user id for the user you wish to delete.  Plug that number in for `user_id` below and that should do it.
```python
requests.request("DELETE", f"http://localhost/api/users/{user_id}/", headers={"Authorization": f"Token {api_token}"})
```

This comes straight from the label-studio API documentation, http://localhost/docs/api#tag/Users/operation/api_users_delete

NOTE: I've never had to delete a user, so not sure if there are any negative side effects.
