### ISSUE TITLE
Default value for Choice

### ISSUE THREAD

**Issue by sfczekalski** [heartexlabs/label-studio#538]
**Is your feature request related to a problem? Please describe.**
I'm very happy with label-studio, however the feature I'm missing is support for default value for some choice.

**Describe the solution you'd like**
I would like to have a simple way to specify default value for some choice. For example, adding an attribute "default=<value>" to the "Choices" tag.

**Describe alternatives you've considered**
Alternatively, there could be an attribute "default=True" for some "Choice" tag.

**Additional context**
I think it's an easy feature to implement, but it has the potential to speed up the labelling job.

**Comment by niklub** [comment]
Hi, @sfczekalski ! There is `selected="true"` parameter for Choice that preselects one of checkboxes (check [docs](https://labelstud.io/tags/choice.html#Parameters)). Is that what you're looking for ?

**Comment by sfczekalski** [comment]
This is something I was looking for, sorry I didn't notice it in the docs. Many thanks! I'm closing the issue.

**Comment by function2-llx** [comment]
> 
> 
> Hi, @sfczekalski ! There is `selected="true"` parameter for Choice that preselects one of checkboxes (check [docs](https://labelstud.io/tags/choice.html#Parameters)). Is that what you're looking for ?

Seems not work when `perRegion` is true, check [this playground](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CLabels%20name%3D%22label%22%20toName%3D%22text%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22label%22%2F%3E%3Cbr%3E%20%20%3C%2FLabels%3E%3Cbr%3E%20%20%3Cbr%3E%20%20%3CChoices%20name%3D%22choice%22%20toName%3D%22text%22%20choice%3D%22multiple%22%20perRegion%3D%22true%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22choice1%22%20selected%3D%22true%22%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22choice2%22%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%3Cbr%3E%20%20%3CText%20name%3D%22text%22%20value%3D%22%24text%22%2F%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E).
