### ISSUE TITLE
De-duplicating uploaded tasks

### ISSUE THREAD

**Issue by pavelgrib** [heartexlabs/label-studio#540]
**Is your feature request related to a problem? Please describe.**
While using LabelStudio, I occasionally upload duplicate tasks (text labeling) and there is no mechanism for removing duplicates.

**Describe the solution you'd like**
It would be great if there was a mechanism to deduplicate before presenting for labeling or while uploading.

**Additional context**
This happens when I do front-end upload of CSV tasks.

**Comment by makseq** [comment]
What LS version do you use? Have you tried 0.9.0 already? There are a lot of reworked import schemes.

**Comment by makseq** [comment]
Feel free to reopen if your problem hasn't gone.

**Comment by dextervip** [comment]
@makseq I am having the same issue, just installed the latest release and if I import the CSV twice, it duplicates my tasks. Any way to avoid it while importing CSV files?

**Comment by makseq** [comment]
@dextervip @pavelgrib 
I implemented removing of duplicated tasks in `feature/bring-back-experimental`. 
To enable this action in the Data manager, you need to set `LABEL_STUDIO_EXPERIMENTAL_FEATURES=1` in LS environment variables.
