### ISSUE TITLE
Support OBB 

### ISSUE THREAD

**Issue by DimIsaev** [heartexlabs/label-studio#5409]
Is it planned to support OBB (Oriented Bounding Boxes Object Detection)?

https://docs.ultralytics.com/tasks/obb/

**Comment by DimIsaev** [comment]
👀

**Comment by makseq** [comment]
Yes, it's planned! Hope it happen very soon. You can try it in this PR: https://github.com/HumanSignal/label-studio-converter/pull/281

**Comment by hamhanry** [comment]
for temporary to resolve the OBB task, i made the codes to convert to the OBB format.
please check here

https://github.com/hamhanry/label-studio-converter-for-YOLO-OBB

**Comment by makseq** [comment]
The YOLO OBB format is now supported for exports.

![image](https://github.com/user-attachments/assets/03a83fb9-e52e-43c4-8cdf-51af8c260919)

**Comment by DimIsaev** [comment]
Is this implementation planned in Label Studio?
