### ISSUE TITLE
Ability to have multiple users logged in to do labeling

### ISSUE THREAD

**Issue by pavelgrib** [heartexlabs/label-studio#542]
**Is your feature request related to a problem? Please describe.**
Different people currently connect to my local instance of Label Studio.  It would be nice if their labeling work was associated with their username.

**Describe the solution you'd like**
I would like to have multiple users be able to label tasks without accidentally labeling the same task and being able to have their own labeling workspace, including being able to label only the tasks they uploaded.  Creating a login page and user management, and a feature that lets users label a set of tasks allocated to them.

**Comment by makseq** [comment]
Yes, this is the most desirable topic we hear from the community and we working on it right now!

**Comment by CharlieBickerton** [comment]
Thats awesome to hear @makseq, do you have any idea on release timelines?

**Comment by makseq** [comment]
Yes, we are planning to release it in 2-3 month, there is a huge amount of work.

**Comment by CharlieBickerton** [comment]
Definately a large piece of work, I appreicate that!

**Comment by ericflores** [comment]
For authentication, please make sure to keep in mind all the mechanism that Flask supports, even if you cannot add all of them from the start.
https://flask-appbuilder.readthedocs.io/en/latest/security.html

Check out documentation for authenticating using Oauth2 in Doccano, for example:
https://doccano.github.io/doccano/advanced/oauth2_settings/

**Comment by makseq** [comment]
@ericflores @CharlieBickerton @pavelgrib We've release LS 1.0.0 with multi-users support: 
https://labelstud.io/blog/release-100.html
