### ISSUE TITLE
Inability to Export Labeled Images with Oriented Bounding Boxes

### ISSUE THREAD

**Issue by MosbehBarhoumiRAI** [heartexlabs/label-studio#5434]
I encountered an issue while attempting to export labeled images with oriented bounding boxes. My objective is to utilize the YOLOv8 oriented bounding box (obb) format for a specific case, as outlined in the documentation https://docs.ultralytics.com/fr/tasks/obb/#export. However, I'm unable to find a method to export the bounding boxes in the required format: **class_index, x1, y1, x2, y2, x3, y3, x4, y4**. 

Presently, all available methods seem to allow exportation solely in the format of **xcn, ycn, hn, wn**. I'm uncertain if I've overlooked a method or if this format is not supported. If not supported, is there a possibility to introduce this feature? Additionally, is there an alternative approach where we can label the data with oriented bounding boxes and subsequently export them? 
![Screenshot from 2024-02-07 15-30-51](https://github.com/HumanSignal/label-studio/assets/78423450/19d05b6e-b1c7-4d79-ac11-908455e3c011)

**Comment by ftapajos** [comment]
YOLO_OBB is not yet supported by label-studio-converter module

Related:
 https://github.com/HumanSignal/label-studio-converter/issues/280
 https://github.com/HumanSignal/label-studio-converter/issues/281
#5409

**Comment by hamhanry** [comment]
for temporary, i made the converter that support YOLO-OBB from label studio.

plase check here.
https://github.com/hamhanry/label-studio-converter-for-YOLO-OBB

**Comment by makseq** [comment]
Now LS supports YOLO OBB:

![image](https://github.com/user-attachments/assets/adc6700f-1472-49a6-a719-6fbc52130edc)

**Comment by Wajahat0** [comment]
> Now LS supports YOLO OBB:
> 
> ![image](https://private-user-images.githubusercontent.com/501780/359685928-adc6700f-1472-49a6-a719-6fbc52130edc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDgwMjYsIm5iZiI6MTczMTYwNzcyNiwicGF0aCI6Ii81MDE3ODAvMzU5Njg1OTI4LWFkYzY3MDBmLTE0NzItNDlhNi1hNzE5LTZmYmM1MjEzMGVkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxODA4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNTE2YTA4NGMxY2U2MjM5MjU1MGJjZTk4MWJmYjc5ZGU4OTc1ZjQ3ZmYwMDY4YTAxMmRiOTdiMjMxODA4MjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zgidLwe-4rXPq_CbRZuP2efKg3wxG4g5ay9CwU_1sl4)

Hi it was showing that option before but now there is no such option. How could i solve that problem?? anyone..
