### ISSUE TITLE
Change export zip name to distinguish between export types

### ISSUE THREAD

**Issue by bram2506** [heartexlabs/label-studio#544]
**Is your feature request related to a problem? Please describe.**
Currently when labelling sometimes I want to export to VOC format while other times to Brush Labels. So for example switching between image segmentation and object detection. The export zip file name is now hardcodes to the datetime of the export moment. 

**Describe the solution you'd like**
Being able to give in the export name combined with the datetime would be ideal

**Describe alternatives you've considered**
an other option i can think of is that the format chosen is added to the export name together with the datetime. I think this one will require less changes in the code.

**Comment by makseq** [comment]
@bram2506 Could you check this PR: https://github.com/heartexlabs/label-studio/pull/551, I've added this option there.
