### ISSUE TITLE
Add the ability to hide all relations at once

### ISSUE THREAD

**Issue by robinclaes** [heartexlabs/label-studio#5446]
**Is your feature request related to a problem? Please describe.**
Our team usually hides all relationships to then enable them one by one to view their relation.
This was available in past versions but seems to have gotten removed in more recent versions. 
(there was an eye-icon next to the relationships tab title)

**Describe the solution you'd like**
An eye icon that
- hides all relationships when pressed
- unhides all relationships when pressed (when one or more relationships were hidden manually) 

**Describe alternatives you've considered**
Hiding all of the relationships one by one.

**Additional context**
![image](https://github.com/HumanSignal/label-studio/assets/11699918/538858c8-8283-4911-9d2d-fb67b3dfe4e3)

**Comment by robinclaes** [comment]
I've added a bounty on this issue with [Algora](https://algora.io).
If the maintainers would like to accept it, [here's the invitation.](https://console.algora.io/invitation/HumanSignal)

**Comment by Nathy-bajo** [comment]
Hi @robinclaes 

I came across the issue and have been working on it already. But I am finding an issue accepting the bounty invitation, is it still available?

**Comment by robinclaes** [comment]
Hi @Nathy-bajo , thank you! ⭐  The maintainers still have to accept Algora on their repository.

I also launched the same bounty on Gitpay: https://gitpay.me/#/profile/task/750/add-the-ability-to-hide-all-relations-at-once
Can you claim it through this?

@caitlinwheeless @jombooth @bmartel does any of you have permission to add Algora to the repository so our company can open some bounties on some of the issues we need? Or can you tag the relevant people? Many thanks 🙏

**Comment by deppp** [comment]
@robinclaes Thanks, I'll start conversations internally on including. Please, stay tuned.

**Comment by Precious-Macaulay** [comment]
Issue has been resolved. You can close this @robinclaes
