### ISSUE TITLE
Allow sorting relationships by their creation date

### ISSUE THREAD

**Issue by robinclaes** [heartexlabs/label-studio#5447]
**Is your feature request related to a problem? Please describe.**
When the relationship list is getting extensive, adding a new relationship results in the relationship getting added at the bottom of the list. When we then want to label that relationship, we need to scroll down every time.

**Describe the solution you'd like**
- Be able to order by creation time, ascending or descending. (something like the "Regions" tab already has)

**Describe alternatives you've considered**
- Scrolling down all the way every time we add a relationship, to give it a label.
- Adding the newest relationships at the top instead of the bottom would also be a good alternative.

**Additional context**
![image](https://github.com/HumanSignal/label-studio/assets/11699918/3e2e0967-6c1f-469c-aa1c-6861b04922d7)

**Comment by robinclaes** [comment]
Pledged $50 via gitpay.me.

[https://gitpay.me/#/task/761](https://gitpay.me/#/task/761)

**Comment by makseq** [comment]
@robinclaes could you clarify how does your last message work? Are you going to implement this feature for 50$?

**Comment by robinclaes** [comment]
@makseq our company is giving out a 50 dollar bounty for some of the issues I created on this repository because we need the changes. This way we hope to encourage some developers to solve this for us.

**Comment by Precious-Macaulay** [comment]
@robinclaes i will like to contribute on this issue

**Comment by Precious-Macaulay** [comment]
Issue has been resolved you can close this @robinclaes
