### ISSUE TITLE
Change folder of tasks.json

### ISSUE THREAD

**Issue by bram2506** [heartexlabs/label-studio#545]
**Describe the bug**
For some technical reasons i want to change the folder where the tasks.json is placed so that i can update it from a mount for example but that i don;t have to mount the whole project folder. 

**To Reproduce**
1. Go to tasks.json
2. Change "input_path": "./tasks.json" to for example "input_path": "./upload/tasks.json"
3. start the labelstudio
4. You will see in tasks tab that the input path is still ./Labeller/tasks.json

Also changing the source arguments of the config json dont have effect. The thing i tried for the config json was:

```
{ input_path: "./upload/tasks.json",
 "source": {
    "name": "Tasks",
    "type": "tasks-json",
    "path": "./upload/tasks.json"
  },
``` 

**Expected behavior**
I would expect it to change the input path for the tasks.json to change to the upload folder, i have tried absolute paths also.

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS 10.14.6 and Linux VMs
 - Label Studio Version 0.8.2

**Comment by makseq** [comment]
@bram2506 why might not you use a symlink to tasks.json? Probably we won't add this feature, because right now we are working on switching to SQLite instead of files DB. But your PR with this feature is highly appreciated.

**Comment by bram2506** [comment]
@makseq Okay thanks for the explanation. Feels to me then that this issue is redundant when the switch is made to SQLite. And to be honest I don't know how to change it correctly in the code myself.
