### ISSUE TITLE
CSRF verification failed. Request aborted.  Help needed.

### ISSUE THREAD

**Issue by nitesh047** [heartexlabs/label-studio#5474]
I have installed label-studio on my ec2 instance and added an SSL from acm using aws cloudfront. But now, while I am trying to log in or signup on to my https label studio, it is giving me the error 
Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for “same-origin” requests.

while on the ec2 instance IP address, everything is working fine.
Please help me with this issues.

Thanks!

**Comment by lgq-garbage** [comment]
I meet the same problem. How did you solove this?

**Comment by nitesh047** [comment]
Initially, I tried to add SSL using Cloudfront, but it was not working. Then, I switched to an EC2 load balancer, which worked for me.

**Comment by lgq-garbage** [comment]
Thanks for your reply. How to switch to EC2 load balancer?  I don't konw what should I do.

**Comment by lgq-garbage** [comment]
I  rebuild the docker and solve this problem. Thanks angin.

**Comment by nitesh047** [comment]
Great.
