### ISSUE TITLE
Predictions added to json file not shown in Label-Studio

### ISSUE THREAD

**Issue by slychief** [heartexlabs/label-studio#548]
Hi,

I am manually adding predictions to a task json file as shown below. Unfortunately, the predictions are not shown in the label-studio. I am using Label Studio version: 0.9.0-2.

```
{
 "completions": [
  {
   "created_at": 1608552083,
   "id": 3001,
   "lead_time": 81.737,
   "result": [
    {
     "from_name": "label",
     "id": "wavesurfer_7sav2kslgkg",
     "original_length": 490.28485260770975,
     "to_name": "audio",
     "type": "labels",
     "value": {
      "end": 8.465203031605403,
      "labels": [
       "Keyword"
      ],
      "start": 7.109513556875301
     }
    }
   ]
  }
 ],
 "predictions": [
  {
   "created_at": 1608552083,
   "id": 3002,
   "lead_time": 81.737,
   "result": [
    {
     "from_name": "label",
     "id": "wavesurfer_7xav2kslgkg",
     "original_length": 490.28485260770975,
     "to_name": "audio",
     "type": "labels",
     "value": {
      "end": 18.465203031605403,
      "labels": [
       "Keyword"
      ],
      "start": 17.109513556875301
     }
    }
   ]
  }
 ],
  "data": {
  "audio": "\/data\/audio_data"
 },
 "id": 3,
 "task_path": "\/0.wav"
}
```

**Comment by makseq** [comment]
It seems it's a bug. Try to restart Label Studio.

**Comment by makseq** [comment]
@slychief Just released 0.9.0.post3, please, switch to it and check how it works there.

**Comment by slychief** [comment]
1. Thanks for the quick response!
2. Apologies for the duplicated issues. I was forwarded to a 404-Error-page after submitting the issue from. I used the back-button and tried again several times. I wasn't aware that the issues were actually created.

I've just updated to 0.9.0.post3 and unfortunately it is still not working.

Here are the steps that I am executing. Maybe there is also something wrong in my workflow:

1. Created an annotation in a new audio file and saved the completion.
2. In the completions directory opened the corresponding json file
3. Added the prediction (as shown in my first post) to the json file
4. restarted label-studio server
5. reloaded Tasks page in browser

The compleltion is shown, but the predictions facett shows "No Predictions". I experimented with adding the score attribute to the prediction, changing ID values, etc. All without success.

**Comment by makseq** [comment]
@slychief I just checked this steps: 

0. Setup labeling config
```
<View>
  <Labels name="label" toName="audio" choice="multiple">
    <Label value="Keyword" background="#ff0000" />
  </Labels>

  <AudioPlus name="audio" value="$audio"/>
</View>
```

1. Import new wav/mp3
2. Create completion
3. Press "Show task code" in data manager (last column in task row)
4. Copy task code, make prediction section the same as completion
5. Import copied and modified task code again

OR you can try to import this right now: 
```
{
  "id": 0,
  "data": {
    "audio": "/static/samples/sample.mp3"
  },
  "completions": [
    {
      "created_at": 1611016407,
      "id": 1,
      "lead_time": 81.737,
      "result": [
        {
          "from_name": "label",
          "id": "wavesurfer_7sav2kslgkg",
          "original_length": 490.28485260770975,
          "to_name": "audio",
          "type": "labels",
          "value": {
            "end": 4,
            "labels": [
              "Keyword"
            ],
            "start": 3
          }
        }
      ]
    }
  ],
  "predictions": [
    {
      "created_at": 1608552083,
      "id": 3002,
      "lead_time": 81.737,
      "result": [
        {
          "from_name": "label",
          "id": "wavesurfer_7xav2kslgkg",
          "original_length": 490.28485260770975,
          "to_name": "audio",
          "type": "labels",
          "value": {
            "end": 2,
            "labels": [
              "Keyword"
            ],
            "start": 1
          }
        }
      ]
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/501780/104974080-c7e6e180-5a07-11eb-971e-eeb6c6a96b58.png)

![image](https://user-images.githubusercontent.com/501780/104974113-d9c88480-5a07-11eb-82f3-2a27208b8831.png)

**Comment by makseq** [comment]
Will it help you?

**Comment by slychief** [comment]
OK, I found my problem. The important keyword here is “import”!

When I import the changed completion file via the import page, the predictions are shown correctly. When I just change the completion files in the completion directory and restart label-studio, the predictions are not loaded from these files and the “predictions” field in the task code is empty.

My workflow processes a lot of files in parallel and outputs the json files. Manually importing files is not feasible. Is it possible, to re-initiate the label-studio data manager from command line by supplying a directory with tasks and completions?

My current workaround is to add the predictions as additional completions with "id": "keyword_detector". Following this approach, I can alter or create completion files in the completions directory which are loaded by the data manager after restarting label-studio.



Von: Max <notifications@github.com>
Gesendet: Dienstag, 19. Januar 2021 01:40
An: heartexlabs/label-studio <label-studio@noreply.github.com>
Cc: Schindler Alexander <Alexander.Schindler@ait.ac.at>; Mention <mention@noreply.github.com>
Betreff: Re: [heartexlabs/label-studio] Predictions added to json file not shown in Label-Studio (#548)


@slychief<https://github.com/slychief> I just checked this steps:

  1.  Setup labeling config

<View>

  <Labels name="label" toName="audio" choice="multiple">

    <Label value="Keyword" background="#ff0000" />

  </Labels>



  <AudioPlus name="audio" value="$audio"/>

</View>

  1.  Import new wav/mp3
  2.  Create completion
  3.  Press "Show task code" in data manager (last column in task row)
  4.  Copy task code, make prediction section the same as completion
  5.  Import copied and modified task code again

OR you can try to import this right now:

{

  "id": 0,

  "data": {

    "audio": "/static/samples/sample.mp3"

  },

  "completions": [

    {

      "created_at": 1611016407,

      "id": 1,

      "lead_time": 81.737,

      "result": [

        {

          "from_name": "label",

          "id": "wavesurfer_7sav2kslgkg",

          "original_length": 490.28485260770975,

          "to_name": "audio",

          "type": "labels",

          "value": {

            "end": 4,

            "labels": [

              "Keyword"

            ],

            "start": 3

          }

        }

      ]

    }

  ],

  "predictions": [

    {

      "created_at": 1608552083,

      "id": 3002,

      "lead_time": 81.737,

      "result": [

        {

          "from_name": "label",

          "id": "wavesurfer_7xav2kslgkg",

          "original_length": 490.28485260770975,

          "to_name": "audio",

          "type": "labels",

          "value": {

            "end": 2,

            "labels": [

              "Keyword"

            ],

            "start": 1

          }

        }

      ]

    }

  ]

}

[image]<https://user-images.githubusercontent.com/501780/104974080-c7e6e180-5a07-11eb-971e-eeb6c6a96b58.png>

[image]<https://user-images.githubusercontent.com/501780/104974113-d9c88480-5a07-11eb-82f3-2a27208b8831.png>

**Comment by makseq** [comment]
@slychief 
I think your mistake is in the wrong place for predictions. They are stored and loaded from tasks.json, not from completions/*.json. But no matter. 

There were several requests about task updates ability. I implemented it in this PR: 
https://github.com/heartexlabs/label-studio/pull/561

Please, check it; and now you don't need to restart LS. Usage example: 

```bash
curl -X PATCH -d '{ "data": { "image": "static/samples/sample.jpg" }, "predictions": [ ... ] }' -H "Content-Type:application/json" http://localhost:8080/api/tasks/<task-id>/
```

**Comment by makseq** [comment]
Feel free to reopen it if you still have this issue.

**Comment by jet-c-21** [comment]
```json
 {
        "id": 1,
        "data": {
            "image": "s3://dev-wildbird-dataset/myhome-1_2024-01-08-20-17-10_PU-N16462-TU-P628-PM-19538-TM-35372_AR-FRAME.jpg"
        },
        "sc_name": "unknown",
        "sc_model_version": "SCM-2404",
        "predictions": [
            {
                "model_version": "RS-DEV-V3",
                "iou_thresh": 0.6,
                "conf_thresh": 0.15,
                "result": [
                    {
                        "id": "413fa2",
                        "type": "rectanglelabels",
                        "from_name": "label",
                        "to_name": "image",
                        "original_width": 3072,
                        "original_height": 1728,
                        "image_rotation": 0,
                        "value": {
                            "x": 1654.764892578125,
                            "y": 880.10302734375,
                            "width": 335.424072265625,
                            "height": 363.17816162109375,
                            "rectanglelabels": [
                                "not flying bird"
                            ]
                        }
                    },
                    {
                        "id": "9608a5",
                        "type": "rectanglelabels",
                        "from_name": "label",
                        "to_name": "image",
                        "original_width": 3072,
                        "original_height": 1728,
                        "image_rotation": 0,
                        "value": {
                            "x": 1650.45263671875,
                            "y": 906.3477783203125,
                            "width": 262.4156494140625,
                            "height": 256.42962646484375,
                            "rectanglelabels": [
                                "not flying bird"
                            ]
                        }
                    }
                ]
            }
        ]
    },
    {
        "id": 2,
        "data": {
            "image": "s3://dev-wildbird-dataset/myhome-1_2024-04-22-22-58-54-922_PU-N16350-TU-P631-PM-19650-TM-35369_TG-FRAME_JET-DEV-AIBR-2.jpg"
        },
        "sc_name": "unknown",
        "sc_model_version": "SCM-2404",
        "predictions": [
            {
                "model_version": "RS-DEV-V3",
                "iou_thresh": 0.6,
                "conf_thresh": 0.15,
                "result": [
                    {
                        "id": "e87cb3",
                        "type": "rectanglelabels",
                        "from_name": "label",
                        "to_name": "image",
                        "original_width": 3072,
                        "original_height": 1728,
                        "image_rotation": 0,
                        "value": {
                            "x": 1847.387451171875,
                            "y": 972.2208251953125,
                            "width": 267.7581787109375,
                            "height": 250.02423095703125,
                            "rectanglelabels": [
                                "not flying bird"
                            ]
                        }
                    },
                    {
                        "id": "a0077b",
                        "type": "rectanglelabels",
                        "from_name": "label",
                        "to_name": "image",
                        "original_width": 3072,
                        "original_height": 1728,
                        "image_rotation": 0,
                        "value": {
                            "x": 1850.150634765625,
                            "y": 989.95458984375,
                            "width": 216.15234375,
                            "height": 168.25396728515625,
                            "rectanglelabels": [
                                "not flying bird"
                            ]
                        }
                    },
                    {
                        "id": "ea1b4f",
                        "type": "rectanglelabels",
                        "from_name": "label",
                        "to_name": "image",
                        "original_width": 3072,
                        "original_height": 1728,
                        "image_rotation": 0,
                        "value": {
                            "x": 2864.1259765625,
                            "y": 482.01611328125,
                            "width": 115.862060546875,
                            "height": 109.72738647460938,
                            "rectanglelabels": [
                                "not flying bird"
                            ]
                        }
                    },
                    {
                        "id": "b8ba56",
                        "type": "rectanglelabels",
                        "from_name": "label",
                        "to_name": "image",
                        "original_width": 3072,
                        "original_height": 1728,
                        "image_rotation": 0,
                        "value": {
                            "x": 1487.155517578125,
                            "y": 248.25450134277344,
                            "width": 216.8153076171875,
                            "height": 166.12490844726562,
                            "rectanglelabels": [
                                "not flying bird"
                            ]
                        }
                    },
                    {
                        "id": "fa5d9e",
                        "type": "rectanglelabels",
                        "from_name": "label",
                        "to_name": "image",
                        "original_width": 3072,
                        "original_height": 1728,
                        "image_rotation": 0,
                        "value": {
                            "x": 1969.714599609375,
                            "y": 578.4515380859375,
                            "width": 312.2760009765625,
                            "height": 250.09808349609375,
                            "rectanglelabels": [
                                "not flying bird"
                            ]
                        }
                    }
                ]
            }
        ]
    }
```

here's my task json, my case is bbox, but the bbox is not show on the website
![image](https://github.com/HumanSignal/label-studio/assets/67193495/6594a34b-0ced-433c-855a-2b0c931bee4b)
