### ISSUE TITLE
Labeling Interface 

### ISSUE THREAD

**Issue by TrueWodzu** [heartexlabs/label-studio#5483]
**Describe the bug**
It is no longer possible to define Labelling Interface through code

**To Reproduce**
1. Go to project Settings / Labelling Interface 
2. Click on 'Code'

**Expected behavior**
Code descriing the interface should be visible, but instead there is an empty window which can't be edited.

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/10086987/ee66ff8a-9bff-4491-9ef1-3c3ea9875d41)

**Environment (please complete the following information):**
 - Label Studio Version 1.11.1.dev0 (Docker)

**Comment by jombooth** [comment]
Hi @TrueWodzu,

This is a known issue on `develop` branch - we'll fix it, but in the meantime, you can check out the repo at the tag from 1.11.0 and rebuild, and setting a labeling config should work (https://github.com/HumanSignal/label-studio/tree/1.11.0). I'll check in with our team about this in the meantime.

Cheers,
Jo

**Comment by jombooth** [comment]
Actually, I just checked the latest version of `develop` and the interface for configuring the labeling config as code appears to be working again. Could you pull the latest develop, rebuild, try it out, and reopen this if you're still having issues with the labeling config editor?

**Comment by TrueWodzu** [comment]
Hi @jombooth  thank you for your reply. I confirm that it got fixed / started to work again :) (tested on git commit: 93e46de00ccd72122b0fef7c5b2e27beec9a8be6)
