### ISSUE TITLE
Is there an upper limit for the "task_id" value?

### ISSUE THREAD

**Issue by MarsSu0618** [heartexlabs/label-studio#552]
## Problem
Hi, Everyone. I have a question about label studio task. When data is labeled that would be assign `Task ID`. I want to check wether "task_id" value have there an upper limit? Because our data still increasing.

## ScreenShot
![label-studio task_id](https://user-images.githubusercontent.com/72376532/104670956-c8d1f780-5717-11eb-84a4-c498f777dbb7.png)

**Comment by makseq** [comment]
@MarsSu0618 We use converts to integers somewhere, so, it's limited to python int (2 147 483 647). But LS performance is optimized for not more than 100 000 tasks. You can try to import huge amount of tasks, but you need a very powerful machine for this (especially with fast hard drive).

**Comment by hueiyuan** [comment]
@makseq Ok, Thank you for response.
