### ISSUE TITLE
Unable to build frontend code

### ISSUE THREAD

**Issue by zoooooway** [heartexlabs/label-studio#5530]
**Describe the bug**
I am trying to customize the label page, so I have modified some of the code for DM and expect to validate the update by running the label studio project after packaging.
So, i want to run the `npm run build` to build the frontend code, but I got another build failure error:
```
nx run editor:build:production
       >  NX   Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.

           - configuration.mode should be one of these:
             "development" | "production" | "none"
             -> Enable production optimizations or development hints.
          Pass --verbose to see the stacktrace.
```
I am executing this command in `git bash`, The specific construction commands to be executed are: `set NODE_ENV=production && nx run-many --target=build --configuration=production`. Originally, this command was: `NODE_ENV=production nx run-many --target=build --configuration=production`, But since I am in a Windows environment, I modified this command to avoid errors.

Any suggestions will be helpful, thanks.

**To Reproduce**
1. Go to '/web'
2. Run `npm run build`

**Expected behavior**
Built successfully.

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/70228762/674d7576-5071-4f67-a285-64454f689444)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Label Studio Version [1.11.0]

**Additional context**

**Comment by zoooooway** [comment]
At present, I have found a way to run it normally by changing the command to:  `set MODE=production && nx run-many --target=build --configuration=production` . However, I am not sure if the cause of this problem is a spelling error or something else.

**Comment by wangyang000** [comment]
Problems caused by spaces，I have found a way to run it normally by changing the command to:  `set NODE_ENV=production&& nx run-many --target=build --configuration=production`
