### ISSUE TITLE
Add Google Cloud Logging to dependencies

### ISSUE THREAD

**Issue by tsr10** [heartexlabs/label-studio#5539]
**Describe the bug**
Google cloud logging is not defined in pyproject.toml. This means that enabling GOOGLE_CLOUD_LOGGING using the published Dockerfile throws an exception as google.cloud.logging is imported. The following line needs to be added to pyproject.toml:

google-cloud-logging==3.9.0

I would create a PR, but I can't get the poetry.lock diff to look good.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

**Comment by jombooth** [comment]
Hi @tsr10 - thanks for your report! I'll get this fixed soon.

Cheers,
Jo
