### ISSUE TITLE
Unable to start a labeling job on timeseries

### ISSUE THREAD

**Issue by andreadipalma** [heartexlabs/label-studio#554]
**Describe the bug**
Trying to use the new timeseries feature. I'm unable to load any data of my dataset (a csv format) with a local installation of Label-Studio. The steps described into the documentation do not explain the precise sequence of steps to follow. This could (to me) more a documentation issue than a bug.

**To Reproduce**
Steps to reproduce:
1. From a clean project: go to Import
2. Drag & drop the csv file (with headers, contains multiples time series with time column)
3. After it has loaded successfully, I see the preview of the data with columns imported, all ok.
4. Press "Label" button, but it shows a message "Labeling is not yet fully configured. Before you can annotate the data, set up labels configuration".
5. I go to configuration settings, but at this point anyway I try to configure it seems that is not compatible with the imported data. Specifically, it seems that the configuration enables to work only with a json format.

Alternatively, I tried also:
1. Start from the configuration settings,
2. Import the csv file. 
I tried every possible combination without success.

**Expected behavior**
Should be able to load the time series and do the labeling job.

**Screenshots**

**Environment (please complete the following information):**
- Installation of Label-Studio on Macos 10.15.5
- python 3.7

**Additional context**

**Comment by makseq** [comment]
@andreadipalma what is your LS version?

**Comment by niklub** [comment]
Hi! Have you tried to uncheck the checkbox “Interpret each line in files...” while doing import? because time series works with an entire file as a single task entity

**Comment by andreadipalma** [comment]
Hi  @makseq 
the Label-Studio version is 0.9.0

@niklub 
just tried unchecking the checkbox, I see a single row now after loading the file (see screenshot) but when I click "label" I get the same error message (missing configuration, as previously described).

I'm posting also a sequence of screenshots presenting the steps I'm doing. 

![image](https://user-images.githubusercontent.com/8280980/104847942-00d96600-58e3-11eb-9023-e1cc6d2dec53.png)

![image](https://user-images.githubusercontent.com/8280980/104848098-b3112d80-58e3-11eb-950a-44e2ef17be70.png)

![image](https://user-images.githubusercontent.com/8280980/104848111-c91eee00-58e3-11eb-95c3-5d23be88dfcc.png)

![image](https://user-images.githubusercontent.com/8280980/104848124-d0de9280-58e3-11eb-8724-a6113707c2f8.png)

![image](https://user-images.githubusercontent.com/8280980/104848145-e8b61680-58e3-11eb-8663-4bb1a9707fcb.png)

**Comment by niklub** [comment]
yeah, now you need to setup your TimeSeries config, with column names specified in <Channel> tags

**Comment by andreadipalma** [comment]
That's it! Yeah now data are visible and I can move on with labeling!

Thank you so much @niklub , I appreciated your help a lot.
