### ISSUE TITLE
ERROR: label-studio-0.9.0-4.tar.gz ... has different version in metadata: '0.9.0'

### ISSUE THREAD

**Issue by Stercator** [heartexlabs/label-studio#555]
Python 3.8.6 on Windows 10.0.18363
```
C:\Users\myname>pip install label-studio
Collecting label-studio
  Downloading label-studio-0.9.0-4.tar.gz (18.7 MB)
     |████████████████████████████████| 18.7 MB 6.8 MB/s
ERROR: Requested label-studio from https://files.pythonhosted.org/packages/99/6f/20a9db116e4a399209aeac404a692bc5a34b7387e1923a464b1d1925417e/label-studio-0.9.0-4.tar.gz#sha256=819962851fc042733d54c1ddd82d43a57e2a99a04ce272b7038b45c05ba6918f has different version in metadata: '0.9.0'
```
Same output for `pip install label-studio==0.9.0` (automatically looks up same `label-studio-0.9.0-4.tar.gz` file)
`pip install label-studio==0.8.2` runs successfully.

Any ideas on how to solve this issue?

**Comment by makseq** [comment]
@Stercator What is your pip version? (check pip --version)

**Comment by makseq** [comment]
Try to use --use-deprecated legacy-resolver: 

`pip install --use-deprecated legacy-resolver label-studio==0.9.0`

Does it help?

**Comment by makseq** [comment]
@Stercator  Or try now: 
`pip install -U label-studio`

**Comment by Stercator** [comment]
Thanks @makseq, the simple update succeeded!
