### ISSUE TITLE
Missing Setup.py in the Latest Develop Branch

### ISSUE THREAD

**Issue by shuja-shah-dev** [heartexlabs/label-studio#5556]
**Describe the bug**
Yeah, there is no setup.py yet the documentation wants me to install it.

**To Reproduce**
Download the zip.

**Expected behavior**
A setup.py file to be present in the root directory.

**Environment (please complete the following information):**
 - OS: Windows 10 
 - Label Studio Version [e.g. 1.11.0]

**Comment by makseq** [comment]
Could you point us to the documentation where you found it please?

**Comment by jombooth** [comment]
We switched to Poetry for installing label studio these days - you can `pip install poetry` then `poetry install` to install the package from source. If you find any docs referring to setup.py, let us know and we'll update them.
