### ISSUE TITLE
Missing github star stat in the Home page

### ISSUE THREAD

**Issue by vatsal-mi** [heartexlabs/label-studio#5557]
![image](https://github.com/HumanSignal/label-studio/assets/136565422/3af6d609-fb90-4ff7-9bca-7d11e2d3b663)

**Comment by jombooth** [comment]
![image](https://github.com/HumanSignal/label-studio/assets/3943358/e06af98a-854d-49af-87d5-965c01e48c5b)

Seems to be working for me now - I suspect this may have been a transient issue. Thank you for reporting!
