### ISSUE TITLE
.conll export format misses labels or assigns them to the subsequent token

### ISSUE THREAD

**Issue by jbogensperger** [heartexlabs/label-studio#556]
**Describe the bug**
The .conll-format exports for Named Entity Recognition miss tags or assign them to wrong tokens.
I checked the .json exports work fine, but for some reason the .conll exports are wrong.

**To Reproduce**
Label entities in the NER setting and compare the outputs of .conll and .json

**Expected behavior**
If a token was partially or fully tagged, it should be displayed in .conll format. However the output only states entity category "O" - Other for them.

Example for darknet Market advertisment NER, where the label is on the subsequent token. I also saw other examples where no token was tagged at all..

FE -X- _ O
ONLY -X- _ O
This -X- _ O
is -X- _ O
a -X- _ O
listing -X- _ O
for -X- _ O
50 -X- _ O
of -X- _ O
our -X- _ O
" -X- _ O
Pink -X- _ O
Bears -X- _ O
XTC -X- _ O
Pills -X- _ B-Drug
200mg -X- _ O
" -X- _ O
These -X- _ O
are -X- _ O
a -X- _ O
new -X- _ O
presses -X- _ O
that -X- _ O
we -X- _ O
have -X- _ O
in -X- _ O
. -X- _ O
These -X- _ O
are -X- _ O
great -X- _ O
quality -X- _ O
and -X- _ O
a -X- _ O
great -X- _ O
strength -X- _ O
. -X- _ O
More -X- _ O
to -X- _ O
follow -X- _ O
. -X- _ O
. -X- _ O
. -X- _ O
. -X- _ O
. -X- _ O
. -X- _ O
. -X- _ O

And the correct .json format where "XTC" is labelled as Drug:

{
    "completions": [
      {
        "created_at": 1610964602,
        "id": 1748001,
        "lead_time": 10.15,
        "result": [
          {
            "from_name": "label",
            "id": "zhSTuxjn8-",
            "to_name": "text",
            "type": "labels",
            "value": {
              "end": 60,
              "labels": [
                "Drug"
              ],
              "start": 57,
              "text": "XTC"
            }
          }
        ]
      }
    ],
    "data": {
      "Unnamed: 0": 5388,
      "category": "DRUG",
      "description": "  FE ONLY  This is a listing for 50 of our  \" Pink Bears XTC Pills 200mg \" These are a new presses that we have in .  These are great quality and a great strength . More to follow .  .  .  .  .  .  . ",
      "keywords": "[('Ecstasy / MDMA', 57, 60)]",
      "lang": "en",
      "market_name": "DREAM",
      "name": "50| Pink Bears XTC Pills 200mg | UK Vendor",
      "subcategory": "Drugs, Ecstasy, Pills",
      "vendor": "stevenriley70"
    },
    "id": 1748
  }

**Screenshots**

**Environment (please complete the following information):**
-OS
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

-Labelstudio version
label-studio              0.9.0                    pypi_0    pypi
label-studio-converter    0.0.22                   pypi_0    pypi

**Comment by makseq** [comment]
Thank you very much for you contribution!

**Comment by amtam0** [comment]
Hi, I have similar issue, tested in 1.0.1 (docker image heartexlabs/label-studio:latest)
