### ISSUE TITLE
Loosen Pip Requirements

### ISSUE THREAD

**Issue by EntilZha** [heartexlabs/label-studio#557]
I am working with label-studio within another project and running into issues with pip requirements being to strict. Looking at the `requirements.txt` file indicates that there are many dependencies pinned on minor/patch versions, for example   `requests==2.22.00`. This unfortunately makes it difficult to resolve dependencies. Would it be possible to modify the dependencies on the PyPI packages to be moore open?

**Comment by makseq** [comment]
I think we can try to replace it with >=2.22.0

**Comment by makseq** [comment]
I've added it here:
https://github.com/heartexlabs/label-studio/pull/561
