### ISSUE TITLE
Filters get set for all annotators. Bug or Feature? 

### ISSUE THREAD

**Issue by bablf** [heartexlabs/label-studio#5573]
**Describe the bug**
When setting any kind of filters my co-annotators get set the same filters. Is this indended design that filters are shared between annotators or is this a bug? 

**To Reproduce**
1. Go to Data Manager of the Project and set any filter. 
2. Use a second device and log in with a different account.
4. In Data Manager and the labeling tool, the filters set in step 1 are also set for the second user.  

**Expected behavior**
I would expect everyone to be able to set their own custom filters. 

**Environment (please complete the following information):**
 - OS: Linux  
 - Label Studio Version: 
```
label-studio==1.10.1
label-studio-converter==0.0.57
label-studio-tools==0.0.3
```

**Additional context**
The annotation works perfectly, and we all get our annotations as expected, so it's not linked to us all using the same account or something like that.  
Love the tool otherwise! :)

**Comment by makseq** [comment]
Data manager tabs are shared by designed. We are thinking about new approaches here when users have their private tabs and they can make them public. So, it's expected behavior.
