### ISSUE TITLE
When previewing a 24M sized image, the page will report an error

### ISSUE THREAD

**Issue by gitymy** [heartexlabs/label-studio#5579]
For the same project, images with smaller sizes can be previewed normally, while images with larger sizes will not be displayed and an error message will appear
![5DD64F80-87B2-487D-95E8-8DE551B93608](https://github.com/HumanSignal/label-studio/assets/90229485/23bd5303-c90c-4ce1-b8b8-dcf9e184c593)

[2911.jpg.zip](https://github.com/HumanSignal/label-studio/files/14597236/2911.jpg.zip)

**Comment by makseq** [comment]
Try checking the network panel, most likely browser rejected loading of this image. The image presenting in LS depends on user's browser, if the browser doesn't support it, you won't be able to use it.
