### ISSUE TITLE
Check latest version make app hang undefinitely when running offline

### ISSUE THREAD

**Issue by LamDang** [heartexlabs/label-studio#558]
Hello, 

When I run Label Studio in an offline environment (without Internet Access), the app seems to hang indefinitely at start. I think it could be because of https://github.com/heartexlabs/label-studio/blob/707223a0a2059c63bc89aab5250450672eb746a9/label_studio/server.py#L35.

https://github.com/heartexlabs/label-studio/blob/707223a0a2059c63bc89aab5250450672eb746a9/label_studio/utils/misc.py#L386

Actually add a timeout in requests.get() may solve the issue.

**Comment by makseq** [comment]
@LamDang Thank you for your report! Could you make a PR?
