### ISSUE TITLE
Allow readjusting of label points (PolygonLabels)

### ISSUE THREAD

**Issue by imaginaryBuddy** [heartexlabs/label-studio#5585]
**Is your feature request related to a problem? Please describe.**
I would like to be able to readjust/add segmentation/label points to an existing segmentation/label. This is because I would like to allow for collaboration with my team members, where they could also readjust labels created by me.
**Describe the solution you'd like**
Add the feature as a configuration setting
**Describe alternatives you've considered**
Using pan image shows the label points, but the points cannot be moved. 
**Additional context**
![image](https://github.com/HumanSignal/label-studio/assets/81760484/55ec8e45-d4fc-47d7-867a-635225404e55)

**Comment by deppp** [comment]
This should be possible by tagging those white dots on the image.

**Comment by imaginaryBuddy** [comment]
Hi @deppp the readjusting of label points won't work if I selected any of the options from this pane: 
<img width="78" alt="Screenshot 2024-03-21 at 10 43 47 PM" src="https://github.com/HumanSignal/label-studio/assets/81760484/c0aa3a4e-ec37-4456-b713-08220c19974f">
