### ISSUE TITLE
Permission denied when syncing tasks from GCS to GCE VM 

### ISSUE THREAD

**Issue by jeannefukumaru** [heartexlabs/label-studio#559]
Hello!
Bug description
I have provisioned a GCP VM and run `label-studio-start` and am getting an error that seems similar to [this GitHub issue](https://github.com/heartexlabs/label-studio/issues/360). For the record running the same setup command on my local works fine.
The full label studio cli command is label-studio start ls_ui --init --target gcs-completions --target-path annotations --source gcs --source-path label-studio-tasks  --source-params "{\"regex\": \".*\"}" --ml-backends http://localhost:9090 --force
and the error message is :
`Tasks loading error
Error calling the IAM signBytes API: b'{\n "error": {\n "code": 403,\n "message": "The caller does not have permission",\n "status": "PERMISSION_DENIED"\n }\n}\n'`
To Reproduce
Go to Cloud tab on import page and verify Cloud settings
TASKS will show the correct number of images in cloud bucket
go to the TASKS tab and the error message pops up.
Expected behavior
Label studio should be able to load task stored as single json file per task from GCP into label studio.
Troubleshooting
export GOOGLE_APPLICATION_CREDENTIALS from VM SSH instance
provision service account permissions directly from GCP bucket
reset service account tied to VM
authenticate and provision service account using cloud shell
Environment (please complete the following information):
OS: debian
Browser safari

**Comment by makseq** [comment]
Hello, 

It's definitely a problem with credential settings. 

And where did you exactly store your google credential? What is your GOOGLE_APPLICATION_CREDENTIALS? If I understand correctly it must point to your file with credentials. 

https://cloud.google.com/storage/docs/reference/libraries#setting_up_authentication

**Comment by makseq** [comment]
@jeannefukumaru Do you still have this issue?

**Comment by jeannefukumaru** [comment]
Hi @makseq the solution turned out to be trivial - untick the box in magenta. The credentials error seems to be a side effect but it wasn't the real issue. 
![Screenshot 2021-02-16 at 4 32 37 PM](https://user-images.githubusercontent.com/26344607/108037828-158d5300-7075-11eb-8013-2cad9da4d011.png)

**Comment by jeannefukumaru** [comment]
Thanks for the suggestions though

**Comment by makseq** [comment]
Wow! Nice! Glad to hear about your success :slightly_smiling_face:
