### ISSUE TITLE
Re-import annotations from S3 target storage

### ISSUE THREAD

**Issue by pdlje82** [heartexlabs/label-studio#5601]
**Is your feature request related to a problem? Please describe.**
While it is possible to export annotations to a S3 target storage, it is not possible to import previously created annotations from there. 
In my scenario, one label-studio (LS) instance is run on a temporary cloud server. As soon as the dataset is labelled and the annotations exported to the target bucket, the cloud instance is deleted. Now, lets say I want to import the labelled data into another, central LS instance, which does not get deleted. Now the pain begins, as I have to use a python script to read out the json files from the target storage and convert them into a json task, that I can then manually import to the central LS instance. This instance then creates new annotation files with new names. If I want to export these to an S3 target I either have to remove the old annotation files or use a new bucket. Both options are too complex.

**Describe the solution you'd like**
I want to use the annotation target storage as source storage to import the annotations into new LS instances. After import, I want to update the annotations and export them again to the same storage.
If this doesn't make sense, maybe point out how the standard workflow is designed, if there is one? We use temporary LS sintances on temporary servers that get deleted after labeling, only the S3 target exports remain after deletion.

**Describe alternatives you've considered**
As written above, currently I use python to download the annotations from the target S3 and convert them to a task file, which I then import to LS.

**Additional context**

**Comment by procrastix** [comment]
I am facing the same issue

**Comment by makseq** [comment]
@dgormly @pdlje82 

There is a special environment variable that changes the behavior of Target Storages to write tasks as Label Studio JSON Task Format, not as annotations, is `FUTURE_SAVE_TASK_TO_STORAGE`. When set to `1` or `true`, tasks will be saved using the task ID as the filename stem, and the format of the target file contents will be in the standard Label Studio task format, which is suitable for re-importing tasks using the Label Studio Import dialog.

To import annotations from an S3 target storage into a new Label Studio instance, you can follow these steps:

0. Run Label Studio with this env var or add it into your environments vars: 
```
FUTURE_SAVE_TASK_TO_STORAGE=1 label-studio
```

1. Create a new project. Import new tasks. 

2. Add a Target Storage (S3/GCS/Local) in the Project settings.
  - It's recommended to use a **separate folder** to store annotations, because they don't have an extention (just task ids as filenames) and it might be difficult to separate them from other files.

3. Submit annotations. 
  - Newly added annotations will be written to the Target Storage. 
  - Or you can explicitly save annotations from scratch clicking Sync button on the Target Storage card in the Project settings. 

4. Configure the Source Storage (S3/GCS/Local) in the **new** Label Studio instance:
  - Use the save bucket and prefix as you used for the Target Storage.
  - Click Sync button on the Source Storage card. 

Now tasks with annotations should be re-imported from the previously exported tasks on the Target Storage of the old LS instance.

**Comment by makseq** [comment]
Related issue: https://github.com/HumanSignal/label-studio/issues/2512#issuecomment-1423548314

**Comment by xinnjie** [comment]
> @dgormly @pdlje82
> 
> There is a special environment variable that changes the behavior of Target Storages to write tasks as Label Studio JSON Task Format, not as annotations, is `FUTURE_SAVE_TASK_TO_STORAGE`. When set to `1` or `true`, tasks will be saved using the task ID as the filename stem, and the format of the target file contents will be in the standard Label Studio task format, which is suitable for re-importing tasks using the Label Studio Import dialog.
> 
> To import annotations from an S3 target storage into a new Label Studio instance, you can follow these steps:
> 
> 0. Run Label Studio with this env var or add it into your environments vars:
> 
> ```
> FUTURE_SAVE_TASK_TO_STORAGE=1 label-studio
> ```
> 
> 1. Create a new project. Import new tasks.
> 2. Add a Target Storage (S3/GCS/Local) in the Project settings.
> 
> * It's recommended to use a **separate folder** to store annotations, because they don't have an extention (just task ids as filenames) and it might be difficult to separate them from other files.
> 
> 3. Submit annotations.
> 
> * Newly added annotations will be written to the Target Storage.
> * Or you can explicitly save annotations from scratch clicking Sync button on the Target Storage card in the Project settings.
> 
> 4. Configure the Source Storage (S3/GCS/Local) in the **new** Label Studio instance:
> 
> * Use the save bucket and prefix as you used for the Target Storage.
> * Click Sync button on the Source Storage card.
> 
> Now tasks with annotations should be re-imported from the previously exported tasks on the Target Storage of the old LS instance.

Hi @makseq, 
In step 4, does it require to configure in the **new**  Label Studio instance? I create **a new project** in the **old** Label Studio instance and wanted to sync the Source Storage, then Label Studio failed with error log 
```
Error logs for s3 storage 7 in project 8 and job null:

  File "/label-studio/label_studio/./io_storages/base_models.py", line 341, in add_task
    prediction['task'] = task.id
TypeError: 'int' object does not support item assignment


meta = {"attempts":2,"duration":0.209478,"time_queued":"2024-05-20 11:28:14.500371+00:00","time_failure":"2024-05-20 11:28:14.712456+00:00","time_last_ping":"2024-05-20 11:28:14.502978+00:00","time_in_progress":"2024-05-20 11:28:14.502978+00:00"}
```

Thanks in advance.

**Comment by xinnjie** [comment]
I am sure that `FUTURE_SAVE_TASK_TO_STORAGE=1` env var is set properly. Here is one of output json `3123.json` :

![image](https://github.com/HumanSignal/label-studio/assets/19732802/cfad276f-4028-4a48-8252-147fcd81e696)

**Comment by makseq** [comment]
It seems that the prediction serialization is not supported. 
You have to remove all predictions, then sync the target storage and try to re-sync source storage for the re-import.

**Comment by makseq** [comment]
Probably, [this line](https://github.com/HumanSignal/label-studio/blob/develop/label_studio/io_storages/base_models.py#L532) should be fixed:
```
 expand = ['annotations.reviews', 'annotations.completed_by', 'predictions']
```

**Comment by xinnjie** [comment]
After following these steps:
1. Clear target storage in Step 2 
> 2.Add a Target Storage (S3/GCS/Local) in the Project settings.

2. Delete all predictions

`3123.json` now have no `predictions` content
![image](https://github.com/HumanSignal/label-studio/assets/19732802/7370b5a1-31a1-4261-bf15-4e0f032721f0)


But new error message came:
```
Error logs for s3 storage 7 in project 8 and job null:

  File "/label-studio/label_studio/./tasks/serializers.py", line 68, in create
    raise AnnotationDuplicateError()
tasks.exceptions.AnnotationDuplicateError: Annotation with this unique id already exists


meta = {"attempts":6,"duration":0.194515,"time_queued":"2024-05-20 14:51:00.266912+00:00","time_failure":"2024-05-20 14:51:00.464046+00:00","time_last_ping":"2024-05-20 14:51:00.269531+00:00","time_in_progress":"2024-05-20 14:51:00.269531+00:00"}
```

Is this says `annotations.id` should be unique across projects. As mentioned earlier, I create a new project in the old Label Studio instance and want import old tasks.

**Comment by makseq** [comment]
It says you already have annotation with such `annotation.unique_id`, it seems you've already imported it.

**Comment by xinnjie** [comment]
Thanks @makseq 

It looks like annotation id should be unique across projects. After deleting tasks in **old** project in the **same** Label Studio Instance, importing goes successfully.
