### ISSUE TITLE
Error in fetching TimeSeries URL from sub-property in task `data` object

### ISSUE THREAD

**Issue by harrymander** [heartexlabs/label-studio#5610]
Time series editor fails when the `value` field is set to a sub-property of the task's `data` object.

**To Reproduce**

 For example:

1. Create a labelling project
2. Add a label config with time series, e.g.:
  ```xml
<View>
  <TimeSeriesLabels name="event-label" toName="ts" maxUsages="1">
    <Label value="event"/>
  </TimeSeriesLabels>
  <TimeSeries name="ts" valueType="url" value="$files.csv" timeColumn="A">
    <Channel column="B"/>
  </TimeSeries>
</View>
```
3. Upload CSV file to data source (e.g. local file). Sample that works with the above config:
  ```csv 
A,B
1,2
2,6
3,10
4,15
```
4. Add some tasks, e.g.
```json
[
  {
    "data": {
      "files": {
        "csv": "/data/local-files/?d=local-files/test.csv"
      }
    }
  }
]
```
5. Open task from project view.
6. Get error: "Cannot find url in **files.csv** field of your task"

**Expected behavior**

The time series is displayed without error.

**Fix**

Use lodash to parse the `value` field via the `parseValue` function in `web/libs/editor/src/utils/data.js` https://github.com/HumanSignal/label-studio/pull/5611

**Comment by hlomzik** [comment]
/jira create bug LEAP
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8885358483)
> **Error**: failed to execute "create" command
>

**Comment by hlomzik** [comment]
/jira create bug
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8885402115)
> **Error**: failed to execute "create" command
>

**Comment by hlomzik** [comment]
/jira create
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8885424607)
> Jira issue [TRIAG-520](https://humansignal.atlassian.net/browse/TRIAG-520) is created

[TRIAG-520]: https://humansignal.atlassian.net/browse/TRIAG-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
