### ISSUE TITLE
Bump dependency for attrs package to comply with e.g. pytest

### ISSUE THREAD

**Issue by Zahlii** [heartexlabs/label-studio#563]
Currently, label-studio fixes the attrs dependency with 19.1.0. ( https://github.com/heartexlabs/label-studio/blob/master/requirements.txt#L3 ).

Many different libraries, including e.g. pytest however require explicitly for >=19.2.0 ( https://github.com/pytest-dev/pytest/blob/6.2.1/setup.cfg#L42)

This leads to many dependency failures as we cannot use latets pytest anymore to test diverse builds relying on label-studio.
Would it be possible to fix this incompatibility?

**Comment by makseq** [comment]
Is it ok to make it >= 19.1.0 in LS?

**Comment by Zahlii** [comment]
I would say yes; I just want to prevent the obvious conflict that you get when you do pip install pytest label-studio. As long as label-studio also supports the changes introduced by attrs 19.2, it should be fine.

**Comment by makseq** [comment]
I've done it in 0.9.0.post5
https://github.com/heartexlabs/label-studio/pull/561
Check it please.
