### ISSUE TITLE
Name 'total' is not defined

### ISSUE THREAD

**Issue by MosbehBarhoumiRAI** [heartexlabs/label-studio#5635]
**Describe the bug**
I tried to import around 500 images into Label Studio, but it's taking too long and outputting this message [a8968a53-43fc-4b80-8b28-62163da2cbac] name 'total' is not defined.

**Screenshots**
![Screenshot from 2024-03-27 11-43-50](https://github.com/HumanSignal/label-studio/assets/78423450/604e6b64-0d8a-42f1-9cd8-00c8c661c0cf)

**Environment:**
 - Label Studio installed using the latest docker image.

**Additional context**
It only happens when I try to import images manually. The weird thing is that it works sometimes for more than 500 images, even up to 1000 images, but in other cases, it gives that message. I think the issue is related to the combined size of the data, not just the number of images.

**Comment by makseq** [comment]
You can try the following steps:

1. Check the `DATA_UPLOAD_MAX_MEMORY_SIZE` environment variable, which controls the maximum size of data that can be uploaded. If the combined size of your images exceeds this limit, you may encounter issues. You can increase this limit by setting the environment variable to a higher value. For example, to set the max upload size to 1 GB, you can start Label Studio with the following command:
   ```
   DATA_UPLOAD_MAX_MEMORY_SIZE=1073741824 label-studio start
   ```

2. If you are running Label Studio through Docker, you can pass the environment variable using the `-e` flag:
   ```
   docker run -e DATA_UPLOAD_MAX_MEMORY_SIZE=1073741824 -p 8080:8080 heartexlabs/label-studio:latest
   ```

3. Consider using external storage to manage a large volume of data. Label Studio supports syncing with cloud storage or using a local storage connector. This approach is more efficient for handling large datasets and can help avoid performance issues.

**Comment by MosbehBarhoumiRAI** [comment]
@makseq Thank you!
