### ISSUE TITLE
Signed URL expires with >1000 tasks from Google Cloud Storage

### ISSUE THREAD

**Issue by Biber05** [heartexlabs/label-studio#564]
Hello,

I setup an environment using Terraform with a GCP Bucket as an image store and an App Engine with LabelStudio. Syncing the entire buckets works fine. But after a while some images cannot be loaded from GCP due X-Goog-Expire expiration.

The error message shows "Cannot load image <Signed-URL>.

Any Advice?

THANKS!

**Comment by makseq** [comment]
Hello! 

How do you import your storage data exactly? Do you use LS storage dialog? 

![image](https://user-images.githubusercontent.com/501780/105417275-6e232900-5c4c-11eb-9b4c-215ec6a4e466.png)

**Comment by Biber05** [comment]
Actual I am using Terraform and Google App Engine to setup everything. I use this script to setup LabelStudio

`label-studio start data --init --force \
  -b -l config.xml -s gcs --source-path <IMAGE_BUCKET> --source-params "{\"use_blob_urls\": true, \"regex\": \".*png\"}" \
  -t gcs-completions --target-path <IMAGE_BUCKET> --target-params "{\"create_local_copy\": true, \"prefix\": \"labels\"}" \
  --allow-serving-local-files --root-dir /tmp --user <USER> --password <PW>
`

**Comment by makseq** [comment]
And what if you will resync storage via GUI ?

**Comment by makseq** [comment]
Feel free to reopen this issue if it's not solved yet.
