### ISSUE TITLE
Storage Export ALWAYS indents data as it puts it into storage

### ISSUE THREAD

**Issue by gdoermann** [heartexlabs/label-studio#5640]
**Describe the bug**
If you setup cloud storage and export annotations, it will always indent and create a multi-line human-readable json file. This is great for debugging, but it causes real issues for tools like Glue/Hive/Spark when trying to read and create SerDe maps. 

**To Reproduce**
1. Go to Project Settings
2. Click on Cloud Storage
3. Setup Cloud Storage Export with S3
4. Export an annotation
5. Check exported file (always multi-line, indented file)

**Expected behavior**
You should be able to set an environment variable/setting/etc that would allow you to turn this off (or set the indent).  

**Environment (please complete the following information):**
 - OS: Docker
 - Label Studio Version 1.12.0 and 1.11.0

**Additional context**
Here are the locations in code that I believe are causing the issue:

label_studio/io_storages/localfiles/models.py
```python


class LocalFilesExportStorage(LocalFilesMixin, ExportStorage):
    def save_annotation(self, annotation):
        logger.debug(f'Creating new object on {self.__class__.__name__} Storage {self} for annotation {annotation}')
        ser_annotation = self._get_serialized_data(annotation)

        # get key that identifies this object in storage
        key = LocalFilesExportStorageLink.get_key(annotation)
        key = os.path.join(self.path, f'{key}')

        # put object into storage
        with open(key, mode='w') as f:
            json.dump(ser_annotation, f, indent=2)

        # Create export storage link
        LocalFilesExportStorageLink.create(annotation, self)

```

label_studio/io_storages/filesystem.py
```

class DirJSONsStorage(BaseStorage):

    description = 'Directory with JSON task files'
...
    def set(self, id, value):
        filename = os.path.join(self.path, str(id) + '.json')
        with open(filename, 'w', encoding='utf8') as fout:
            json.dump(value, fout, indent=2, sort_keys=True)
        self.cache[id] = value
```

It should be as simple as adding a setting that you use instead of hard coding: `json.dump(ser_annotation, f, indent=2)`

**Comment by makseq** [comment]
Hello! Could you make a PR?

**Comment by gdoermann** [comment]
Hey, so upon further review it is an issue on my side (ingestion).  Sorry about that.
