### ISSUE TITLE
Annotations are not saved

### ISSUE THREAD

**Issue by rajeevbaalwan** [heartexlabs/label-studio#5649]
**Describe the bug**
I am trying to annotate data for pairwise regression on images.
Template used: Ranking and Scoring --> Pairwise regression
Template Code:
![Screenshot from 2024-03-29 11-24-30](https://github.com/HumanSignal/label-studio/assets/18329235/4c57f55b-431e-444c-9e93-97bf764c55da)

Annotation:
![Screenshot from 2024-03-29 11-22-22](https://github.com/HumanSignal/label-studio/assets/18329235/69e165b9-631d-46ea-aa9a-eb993da1fe77)

Tasks:
![Screenshot from 2024-03-29 11-22-52](https://github.com/HumanSignal/label-studio/assets/18329235/a11431bd-def6-4d0c-95ec-db70ad4fcb01)

**Expected behavior**
List of task is not showing the annotation.
Exported File Data: Exported File also does not contain the annotation.

[
  {
    "profile_face": "\/data\/local-files\/?d=face-matching\/1092.jpg",
    "appointment_face": "\/data\/local-files\/?d=face-matching\/92202_0.jpg",
    "appointment_id": 92202,
    "agent_id": 1092,
    "id": 1230783,
    "annotator": 4,
    "annotation_id": 23670,
    "created_at": "2024-03-29T05:39:54.721157Z",
    "updated_at": "2024-03-29T05:52:32.001770Z",
    "lead_time": 37.426
  }
]

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version : 1.11.0

**Comment by makseq** [comment]
```
<View>
  <Header>Set how likely these images represent the same thing:</Header>
  <View style="display: grid; column-gap: 8px; grid-template: auto/1fr 1fr">
    <Image name="image1" value="$image1" />
    <Image name="image2" value="$image2" />
  </View>
  <View style="margin-left: auto; margin-right: auto; width: 16em">
    <Rating name="rating" toName="image1"/>
  </View>
</View>
```

Please change your labeling config to this one, there is an error in `toName="image1,image2"`, it should be `toName="image1"`.
