### ISSUE TITLE
Possibility of annotating whole text data at once

### ISSUE THREAD

**Issue by dikshyantacharya** [heartexlabs/label-studio#5650]
**Problem**
Right now, there is a possibility of labeling the NER of a text data by uploading it. But it only works, when the "treat as TSV" is chosen. So, the problem arises, when i have  large text data, where i need to annotate everything at once, this is tedious, since some of the line will be empty, and there will be thousands of sentneces that requires annotation.

**Solution**
Possibility of annotating entire doumets at once like in docanno would be great.

**Comment by makseq** [comment]
Could you describe step by step what you are doing and what is wrong, because right now it's not clear. 
You can import a big txt files as a whole task and label it, what is your concern?

**Comment by dikshyantacharya** [comment]
I am trying to annotate like NER in many Text datas.

For this, i created a new project, and chose the Labelling as "NLP NER" template. 

![image](https://github.com/HumanSignal/label-studio/assets/72460176/a8458fc7-7bad-413c-bcb6-5f698b103748)

Then i imported the text file through "Data Import". Then, there is a choise of either choosing it as "List of tasks" or as "Time Series or Whole Text File"
![image](https://github.com/HumanSignal/label-studio/assets/72460176/55656661-58aa-4b1e-a808-272d6d5a92d7)
![image](https://github.com/HumanSignal/label-studio/assets/72460176/325ce104-636b-4aa8-9d62-0040fed5bf5b)


Now, at first i chose the second part, "Whole Text File". Then, after chossing this, i see following : Only one file is there to be annotated, and the name of Text file is shown at the column text. But, i think there should be the content of the Text File.
![image](https://github.com/HumanSignal/label-studio/assets/72460176/df650c33-5db0-45d5-b950-7eb783e0ca59)

Now, the problem is, when i try to annotate it, you can see that there is actually the name of the file as content to annotate, which i dont think should be the case.
![image](https://github.com/HumanSignal/label-studio/assets/72460176/2b3f9d5d-2459-4ccf-b9ee-a15cc7db579a)
.

And the second option, if i chose the List of tasks and save it, then i see that the tasks are broken it into multiple tasks containing a single line of the text only.

![image](https://github.com/HumanSignal/label-studio/assets/72460176/6a41899b-102b-43f5-97ef-ffe13276445a)


I want all the text file, to be annotated at a single time, rather than annotataing many sentences, since i am trying to extract whole annotated data from the entire text, which is what i need in my case.

I installed label studio using pip, and i am using windows 11, if it helps. 

Thanks for your kind interest.

**Comment by zakcali** [comment]
Same problem, I only see undefined$ word, instead of my text to be annotated.

![image_2024-03-30_113850089](https://github.com/HumanSignal/label-studio/assets/17526947/dd3d20f6-b041-4310-9703-e3b43634adba)

**Comment by zakcali** [comment]
I understand, and fixed my problem by using
`<Text name="text" value="$text" valueType="url"/>`
in Settings->Labeling interface->Code
note, if you choose "list of tasks" when importing, then use that setting:
`<Text name="text" value="$text" />`

I think documentation is vague

**Comment by dikshyantacharya** [comment]
@zakcali It worked. Thank you for your answer.
