### ISSUE TITLE
ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by zhujun5164** [heartexlabs/label-studio#5656]
**Describe the bug**
I have import the images and label the targets, but appear the "ReferenceError: structuredClone is not defined".

![image](https://github.com/HumanSignal/label-studio/assets/49580602/8a893415-46f8-41cd-a498-231c0bf12929)

I look the data, it have label in the source.
![image](https://github.com/HumanSignal/label-studio/assets/49580602/cc8c51d5-48f5-4a93-b35c-75c9b609ae42)

**Comment by zhujun5164** [comment]
i have find the result because of the using web driving may be too old.  I open in chrome can resolve it

**Comment by hediyuan** [comment]
> i have find the result because of the using web driving may be too old. I open in chrome can resolve it

it works for me too
