### ISSUE TITLE
INIT_COMMAND override being ignored in Amazon ECS

### ISSUE THREAD

**Issue by sethfarns** [heartexlabs/label-studio#566]
Hello, I have the Label Studio (version 0.8.2) docker service running in Amazon ECS, as built from the docker-compose.yml file in your repo. It runs fine, but whenever I pass a container override for the INIT_COMMAND, it is ignored by the service. This is my syntax for the override:
```
aws ecs run-task ... --overrides '{
                "containerOverrides":
                [
                        {
                                "name":"label-studio",
                                "environment":[{"name":"INIT_COMMAND","value":"--init --force --template text_classification"}]
                        }
                ]}'
```
As I said, the task runs fine, but it's clearly ignoring this override as the given template is not loaded. I've tried with other label-studio command line arguments with the same result. I also tested setting INIT_COMMAND directly from the terminal using docker-compose, as shown in your README file, and that worked fine. So I don't know if it's an issue with the way I built the image in Docker or pushed it to ECR, and I'm fairly new to both. But can you see something I'm doing wrong?

**Comment by makseq** [comment]
@sethfarns 
Hello, as far as I remember docker-compose `command` is overridden by `tools/run.sh` called from Dockerfile.
Could you check this PR and branch: https://github.com/heartexlabs/label-studio/pull/561
I've added `INIT_COMMAND` to `run.sh`.

**Comment by sethfarns** [comment]
Worked like a charm. Thanks!

**Comment by makseq** [comment]
Wow! I was glad to help! :slightly_smiling_face:
