### ISSUE TITLE
Zoom and deselect region shortcut gone in 0.9.0.post5

### ISSUE THREAD

**Issue by bensteku** [heartexlabs/label-studio#570]
I just upgraded from 0.8.2 to 0.9.0.post5 via pip. I noticed two oversights/bugs, which make 0.9.0 greatly inferior to 0.8.2:

1. The zoom button when labeling images is gone. It is of note here that even in 0.8.2, the zoom button was only present if I started labeling trough the numbered to-do list in the start-up screen that pops up after 'label-studio start ...'. However, as that screen is gone with the new version, I cannot find a way to zoom into images other than using my browser's in-built zoom, which is much worse than what I could use in 0.8.2. Labeling large/detailed images in 0.9.0 is borderline impossible for me.
2. When doing polygon segmentation, the ESC and backspace keys used to work as shortcuts for deselecting regions in 0.8.2. This no longer works in 0.9.0. I hope this is not intended behavior, as there are no other ways of deselecting regions currently AFAIK. The only way to do it is to either click somewhere in the image, thereby creating a useless new region which needs to be deleted, or by clicking onto the info button in the top-right corner, as clicking anywhere else outside the image will not deselect the current region.

**Comment by hlomzik** [comment]
Hi! Sad to hear about this problems. But I just checked and everything works fine.
1. What config do you use? For zoom buttons there is `<Image zoomControl="true"/>` parameter; also there is `zoom="true"` for zooming by `ctrl+wheel`. And they work in latest version as well.
2. There is always "Unselect" button in region's info panel (with `u` as a hotkey). `Esc` was finally introduced recently and it works also in the latest version.

I hope this would help somehow. And if not, could you please share your config and some screencast maybe?

**Comment by makseq** [comment]
@bensteku are you still having troubles?

**Comment by makseq** [comment]
Feel free to reopen if your problem hasn't gone.
