### ISSUE TITLE
sometime show remarked data when labeling.

### ISSUE THREAD

**Issue by MarsSu0618** [heartexlabs/label-studio#573]
### Problems
Hi, I have encountered some problems when i label my data. The label studio tool sometimes show remarked data.
For example, If i had labeled `the first data`. but when i label 500 or more data, the first remarked data show again.
I have checked my data that do not duplicated. So I want to check if whether the tool bug?
Anyone have any ideas? 

### Environment
* label-studio: `0.8.0`
* text data saved on `aws s3`.
* i used `sentence label`.

**Comment by makseq** [comment]
Hi, I think you use an old LS version. There are many bugfixes in 0.9, please, try it.

**Comment by MarsSu0618** [comment]
@makseq Thanks for your response.
I will try it with new version 0.9.0. But i want to check whether if the bug show in older version?

**Comment by makseq** [comment]
You need to remember task ID of doubled tasks, if they are the same it could be a bug.

**Comment by MarsSu0618** [comment]
@makseq Yes. Task ID sometimes duplicated. If i label `task-id:101`, when i label `task-id:150` it show `101` again.
So upgrade version 0.9 that have this issue?

**Comment by makseq** [comment]
Can you check: when you see the same task again, has it a completion already? (Check it using task manager)

**Comment by MarsSu0618** [comment]
@makseq I have check it . the completion is already. But task id show again when i labeling.

**Comment by makseq** [comment]
Yep, I think it's a bug..

**Comment by MarsSu0618** [comment]
@makseq if this is a bug, it is fixed in version 0.9?

**Comment by MarsSu0618** [comment]
@makseq btw, I used version 0.9.0, connect aws s3 show some error message.follow as
<img width="1280" alt="截圖 2021-01-30 上午1 39 46" src="https://user-images.githubusercontent.com/72376532/106308704-0ac47700-629c-11eb-9665-89981443589f.png">

**Comment by makseq** [comment]
In this case you have something wrong in s3 files. Are there are json files on s3?

**Comment by MarsSu0618** [comment]
@makseq Yes, I have json file. format follow as:
```json=
[
  {"text": "......"}
]
```

**Comment by makseq** [comment]
Yep, this is an error: you must not use list of tasks inside of your json files on s3. Only one task per file. It's a limitation by LS design.

**Comment by MarsSu0618** [comment]
so I need to remove list of task?
```
{"text": "......"}
```

and remark issue still not resolve, right?

**Comment by makseq** [comment]
yes, leave task as dict {} only.

> and remark and task_id issue still not resolve

you mean duplicates in the labeling?

**Comment by MarsSu0618** [comment]
@makseq I consider the problem is `User Interface` bug.
Because I used version `0.9.0` UI that it do not have this problem. But used old user interface still have task_id duplicates problem.
So We decide to labeling with new interface. Thanks.

**Comment by MarsSu0618** [comment]
@makseq Hi, We found other problems about `version 0.9.0`.
Our data are save AWS S3. Then, Sometimes label studio interface scan have some problem. Please follow as photo.
![label-studio-image](https://user-images.githubusercontent.com/72376532/106433115-afb49f00-64aa-11eb-988d-2211ead9ba55.png)

It can not encode file text. Just show file link on s3. and current solution is restart tool service, it is normal.
Hope you can check what is problem. We guess maybe tool `redirect and decode` problem.

**Comment by makseq** [comment]
Sorry, what is RWD :slightly_smiling_face: ?

**Comment by makseq** [comment]
> Just show file link on s3. and current solution is restart tool service, it is normal.

But what will you see if you go to the labeling? Does it load for labeling normally?

**Comment by MarsSu0618** [comment]
@makseq it can not how normal text. just show text json file link on s3.
Maybe issue like #497 .

**Comment by makseq** [comment]
What files do you store on your storage? txt or json? Can you show their examples.

**Comment by MarsSu0618** [comment]
@makseq it is json file.
<img width="898" alt="截圖 2021-02-01 下午11 06 17" src="https://user-images.githubusercontent.com/72376532/106476516-199c6b00-64e2-11eb-9dc1-61100ef195ad.png">
data content:
```
{'text': '......'}
```

**Comment by makseq** [comment]
Ok, I'll check it by myself and come back to you.

**Comment by MarsSu0618** [comment]
@makseq  Thank you.
I found you use `ujson` lib instead of `json` lib. Maybe it is problem?

**Comment by makseq** [comment]
As I know it's a full analogue of json. But much faster.

**Comment by MarsSu0618** [comment]
@makseq OK, Maybe you need check `readable_path` from `s3.py`....

**Comment by makseq** [comment]
If you have public s3 storage with these example files it will be much faster to check it for me.

**Comment by MarsSu0618** [comment]
@makseq sorry. because these data are sensitive data that can not be set public  to check.

**Comment by MarsSu0618** [comment]
@makseq 
We found this problem maybe occurred in `import` interface. please follow as image:
![2021-02-02 image](https://user-images.githubusercontent.com/72376532/106563190-6033a900-6566-11eb-8d6f-f61a7bbb76cc.png)
When we click `import` button and show [s3 error](https://github.com/heartexlabs/label-studio/issues/573#issuecomment-770672187).
In addition, We found other solution, which `reset data manager`, and it become normal.
![截圖 2021-02-02 下午2 55 32](https://user-images.githubusercontent.com/72376532/106563444-b99bd800-6566-11eb-85ce-f3f429997553.png)

So, maybe you should check `import` function code.

**Comment by makseq** [comment]
@MarsSu0618 Hm, I see that you have a checkbox "Treat every bucket object as source file ...". In your case it must be off... Maybe something change its state unexpectedly?

**Comment by MarsSu0618** [comment]
@makseq I want to suggest about user interface of label studio. Hope can add `search bar` so that we can search marked data.

**Comment by makseq** [comment]
@MarsSu0618  why don't you use Filters over completion results?

**Comment by MarsSu0618** [comment]
@makseq Because our data sometime have different means according to everyone and need to relabel data.
if it have the `search bar` function , it can increase user experiences and decrease search cost.

**Comment by makseq** [comment]
@MarsSu0618 Ok, I've added it to our backlog, it's a good idea. But it's not relevant for this thread :slightly_smiling_face: 

So, what about your previous problem and my previous question?

> I see that you have a checkbox "Treat every bucket object as source file ...". In your case it must be off. Maybe something change its state unexpectedly?

 Do you still have this problem?

**Comment by makseq** [comment]
Feel free to reopen if your problem is not gone.
