### ISSUE TITLE
Remove duplicates files throws an error

### ISSUE THREAD

**Issue by Ultimatum22** [heartexlabs/label-studio#5731]
**Describe the bug**
I am running 1.11 in a docker container with a nginx proxy running also 1.11 (as described in the docs). I have enabled EXPERIMENTAL_FEATURES=1 and trying to delete duplicated tasks via web interface.

I am importing x number of images via de local storage option. [I have also tried this via the shell](https://github.com/HumanSignal/label-studio/issues/2050#issuecomment-1047465090) hoping the interface added a flavor to the code but it throws the same error.

**To Reproduce**
1.Enable EXPERIMENTAL_FEATURES=1
2. Select multiple images
3. Select `Remove Duplicate Tasks` 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/./data_manager/api.py", line 379, in post
    result = perform_action(action_id, project, queryset, request.user, **kwargs)
  File "/label-studio/label_studio/./data_manager/actions/__init__.py", line 117, in perform_action
    raise e
  File "/label-studio/label_studio/./data_manager/actions/__init__.py", line 113, in perform_action
    result = action['entry_point'](project, queryset, **kwargs)
  File "/label-studio/label_studio/./data_manager/actions/experimental.py", line 114, in remove_duplicates
    _class.create(
AttributeError: type object 'LocalFilesImportStorage' has no attribute 'create'`

**Expected behavior**
I am hoping it will delete duplicates which have not been annotated yet.

**Environment (please complete the following information):**
 - Docker
 - Label Studio Version 1.11

**Additional context**
The reason I am doing this is because the export to json only exports annotated images and not the entire database thus I cannot export it easily to another pc.

**Comment by davidpob99** [comment]
I have the same problem (#5738), did you find a workaround?

**Comment by Ultimatum22** [comment]
No not yet, I am currently trying to use Redis instead of localstorage and see if that works for my workflow.

**Comment by makseq** [comment]
Please check the fix in this PR:
https://github.com/HumanSignal/label-studio/pull/5758

BTW, you don't need to add EXPERIMENTAL_FEATURES=1, now it's official (since 1.12).

**Comment by Ultimatum22** [comment]
I've just used the latest develop docker image and it works. Awesome, thanks for the fast fix. How often are new releases created? It's fine for now, I pinned it to the PR fix which is `heartexlabs/label-studio:20240419.151443-develop-ff7105f39` for anybody who wants to use latest develop and this fix.

**Comment by makseq** [comment]
Cool! Official releases are about once per month. Develop releases are 3-7 times per week, they just are new commits in the develop branch.
