### ISSUE TITLE
Annotation result column shows to much information

### ISSUE THREAD

**Issue by StraussSab** [heartexlabs/label-studio#5735]
**Problem:**
When working on a labeling project and wishing to review the annotation results, the associated column not only displays the annotation result, but also the entire content of the JSON file from the annotation result section. In the Annotation result column, only the label itself should be visible, without the annotation ID or the type of annotation, as these details are not necessary. The inclusion of unnecessary information in the annotation result column can lead to confusion, particularly in the context of a classification task. In the case of object detection or semantic segmentation, an additional column displaying the coordinates may prove to be beneficial.

Additionally, the presence of extra information in the annotation result column complicates the filtering process, as the entire content, including the ID and type, is taken into consideration, thereby diminishing the ease of filtering.

**Solution:**
To solve the problem, the annotation result column should only show the label itself. 
For object detection or semantic segmentation an additional column for the coordinates could be included.

**Comment by makseq** [comment]
You can use experimental action "Cache Labels" to achieve this:

1. You can update your LS to the latest version from the github develop branch,
2. run LS with experimental feature `EXPERIMENTAL_FEATURES=1 label-studio` (or add this variable to your environment variables), 
3. go to the Data manager,
4. select tasks and then use the action "Cache Labels" (more deitais: https://github.com/HumanSignal/label-studio/pull/5909)

**Note:** This action can take some time. Label Studio Community doesn't have background workers and it can fail if you have too many tasks and annotations in your project. To avoid this you can split your dataset into parts by filter with the Inner ID column and apply the action "Cache Labels" part by part.

**Warning**: The cached column is not dynamically updated. It means you have to re-run Cache Labels from time to time when your annotations are changed (updated or submitted). 

**Summary**
The "Cache Labels" action introduces a new feature that allows caching labels from annotations (or predictions) into a specified column in task data. The main functionality is encapsulated in the `cache_labels_job` function, which processes tasks and annotations to extract and store labels based on a specified control tag from the labeling config. 

Example: 
![image](https://github.com/HumanSignal/label-studio/assets/501780/75c6044e-e998-4cf7-8d8f-0913b071c61a)
You will see a new data column with labels and their counters.

**Comment by ivan-kleshnin** [comment]
This cache seems to require a manual update not only after the set of labels is changed, but also when the data is changed.
I have to say, it's not really useful, given such constraints 😞 Is there really no way to just render selected labels in the column with no JSON meta fluff around?
