### ISSUE TITLE
iframe window sizing

### ISSUE THREAD

**Issue by bonjarlow** [heartexlabs/label-studio#5753]
**Describe the bug**
I'm rendering a webpage in the interface, but the iframe size seems to default to a thin rectangle. I want to control how much of the webpage is shown

**To Reproduce**
```
<View style="display:flex; flex-direction:column;">

  <Header value="URL:" size="7"/>
  <HyperText name="url" clickableLinks="true" value="&lt;a href=https://google.com>Link&lt;/a>" style="width: 100%; height: 50%;" /> 
  
  <Header value="Page Title:" size="7"/>
  <Text name="html title" value="$html_title"/>
  <View style="border: 1px solid black; padding: 20px; margin-top: 2em;">
    <Header value="Is this URL relevant to police, courts, or jails?"/>
    <Choices name="relevant" toName="url" choice="single" showInLine="true">      
    	<Choice value="Yes"/>
      	<Choice value="No"/>
    </Choices>
  </View>
</View>
```

**Expected behavior**
hypertext style parameter to adjust iframe size

**Screenshots**
<img width="980" alt="Screenshot 2024-04-18 at 2 48 40 PM" src="https://github.com/HumanSignal/label-studio/assets/32076640/ca53a633-8d71-4855-b74a-9bce8b6794a5">

**Environment (please complete the following information):**
 - OS: macOS
 - Label Studio Version 2.11.1.dev7

**Comment by cthomas-figma** [comment]
@bonjarlow I'm running into this issue as well. How did you solve it?

**Comment by hlomzik** [comment]
@cthomas-figma I don't know how to reproduce this issue, iframe is rendered well for me, even from this example. But you can try number of things:
- `inline="true"` to actually not use iframe if that's okay for your case ([docs](https://labelstud.io/tags/hypertext))
- add styles for `.lsf-htx-richtext` to `<Style>` tag, something like `min-height` or `height` if you know it
- try to use the most recent version of Label Studio
