### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by zhoumingcheng** [heartexlabs/label-studio#5755]
**Describe the bug**

"When I import the dataset, I get an error 500 'Something went wrong, the database is locked' when trying to access the project list page."

**To Reproduce**

Upload a dataset of around 30MB. While the dataset is being uploaded, refresh the project page.

**Expected behavior**

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/52434045/31a32c2e-5009-4447-b10b-bb38a0d44a26)

**Environment (please complete the following information):**
 - OS: windows  python3.11
 - Label Studio Version 1.11.0

**Additional context**

**Comment by makseq** [comment]
You have to switch to PostgreSQL DB for such heavy tasks.
