### ISSUE TITLE
psycopg2-binary installation error for python ver. 3.12.2

### ISSUE THREAD

**Issue by pirik3** [heartexlabs/label-studio#5775]
https://github.com/HumanSignal/label-studio/blob/7951ac3f5e86d490dab5facb29fce24294641ea1/pyproject.toml#L182

This has to be changed to 2.9.9 with poverty.lock packages edit.

**Comment by davy-blavette** [comment]
Yes, version 2.9.6 is not compatible with Windows, but 2.9.9 is okay.
