### ISSUE TITLE
Showing unicode when enter Non-ASCII characters for labels

### ISSUE THREAD

**Issue by azarezade** [heartexlabs/label-studio#578]
**Describe the bug**
It seems there is problem in showing Non-ASCII characters like Persian (fa). For example I transcribed some audio in Persian (فارسی) and there are unicode characters instead of Persian chars in the "Completed results" column of the following picture:

<img width="888" alt="Screen Shot 1399-11-14 at 3 11 13 PM" src="https://user-images.githubusercontent.com/11195749/106595761-447dd200-6569-11eb-993f-381806264631.png">

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version: lates

**Comment by makseq** [comment]
@azarezade Can you show your `/api/tasks` page?

**Comment by azarezade** [comment]
@makseq This is `/api/tasks` page:
<img width="1275" alt="Screen Shot 1399-11-15 at 8 13 04 AM" src="https://user-images.githubusercontent.com/11195749/106699266-c87e9b00-65f7-11eb-8662-3c89ccc98441.png">

**Comment by makseq** [comment]
Fixed in https://github.com/heartexlabs/label-studio/pull/585 (release 0.9.1).
