### ISSUE TITLE
Pagination feature gone with new 0.9.0 release

### ISSUE THREAD

**Issue by Rishabh-hyperverge** [heartexlabs/label-studio#580]
**Describe the bug**
The task page has an infinite scroll as compared to the pagination option in the previous version. 
This restricts the annotator's ability to navigate easily.

**To Reproduce**
Upload say 10k tasks.

**Expected behavior**
Paginated tasks list with configurable(say X) number of tasks per page.

**Comment by deppp** [comment]
Hey there, any context on why that restricts the ability to navigate?

**Comment by Rishabh-hyperverge** [comment]
Hi @deppp , I was speaking from a UX perspective, 
say I am at the later stage in the task list, then there is too much information with an infinite scroll on the annotation page. 

Pagination kept the UI clean and simple while providing the same functionality. 
Let me know if this was a design choice :)

**Comment by makseq** [comment]
@Rishabh-hyperverge what things do you expect from pagination exactly? Is it current page number?
I'm trying to understand what approach could be applied to the infinite scroll to solve your problem.
