### ISSUE TITLE
Authentication for multi-session mode

### ISSUE THREAD

**Issue by raisinglc** [heartexlabs/label-studio#581]
Does label-studio support signing in a multi-session project with username and password?

It works on 'start' mode, by adding username and password to config.json. However, I tried the same thing on the sub-user's config.json file. It didn't work. I still could open the project with shared link without password.

Thanks.

**Comment by makseq** [comment]
@raisinglc No, it's not supported. But we will release a new backend with these features very soon.

**Comment by raisinglc** [comment]
@makseq Glad to hear that.
Thank you:)
