### ISSUE TITLE
How to Simply Display the Video? [Enterprise Edition]

### ISSUE THREAD

**Issue by varungupta31** [heartexlabs/label-studio#5827]
My goal is NOT to annotate the video but to simply watch the video and annotate other text.
What is the simplest manner this can be achieved?

Requesting help in understanding how I can do this?

<view>
<Video name="scenevid" value="$videourl"> </Video>
</view>

<!--- {
"videourl" : <tried with random URL from places like YouTube> }

Getting into setting up Redis or GCS, seems a bit complex. What are the minimal working examples I can do to simply show a video on the annotation interface?

Note: I cannot use the local paths, because I'm on the enterprise edition, as I need to this within a small team.

Thanks!

**Comment by makseq** [comment]
To achieve your goal of watching a video while annotating text, you can use the `Video` tag to display the video and the `TextArea` tag to provide a space for text annotations. Here is a simple labeling configuration that allows you to watch a video and annotate text:

```html
<View>
  <Video name="video" value="$video" />
  <TextArea name="text_annotation" toName="video" placeholder="Enter your text annotation here" />
</View>
```

### Explanation:
1. **Video Tag**: This tag is used to display the video. The `value` attribute should be set to the URL of the video you want to display.
2. **TextArea Tag**: This tag provides a text area for annotators to enter their text annotations. The `toName` attribute should be set to the name of the `Video` tag to link the text area to the video.

### Example JSON Task:
Here is an example of how your task data might look in JSON format:

```json
{
  "data": {
    "video": "https://example.com/path/to/your/video.mp4"
  }
}
```

### Steps to Implement:
1. **Create a New Project**: In Label Studio, create a new project.
2. **Set Up Labeling Interface**: Go to the project settings and set up the labeling interface with the provided configuration.
3. **Import Tasks**: Import your tasks with the video URLs in the JSON format as shown above.
4. **Start Annotating**: Open a task, watch the video, and enter your text annotations in the provided text area.

This setup allows you to watch the video and annotate text without any additional complexity.

**Comment by varungupta31** [comment]
Thanks, my main concern was where the video should reside for it to render with the video tag.
I ultimately setup a GCP bucket as a persistent storage!
