### ISSUE TITLE
Show Lable Studio version on Web UI

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#583]
Request: A way in the Web UI for a user to identify what version of Label Studio they are using.

Going forward it would be nice for users to be able to report what version of label-studio they are using by looking at the web page.  So for example on the home page or under settings if it said "Version 0.9.0" or "Version 0.8.2" it would be helpful (especially with UI changes).

**Comment by makseq** [comment]
@laynr There is such a page and its address is `/version`

**Comment by niklub** [comment]
Hi, @laynr ! Thanks for the good suggestion. Indeed, the version in UI is highly needed, especially with fluctuating frontend part. We are currently working on the more transparent UI within Label Studio 1.0 release, where versioning will be included for sure.

**Comment by makseq** [comment]
Done in 1.0.0. It's available on the main menu in the bottom. 
![image](https://user-images.githubusercontent.com/501780/111354723-a9176b00-8697-11eb-9359-1bdfb37c8b28.png)
