### ISSUE TITLE
Choices are getting filled in quick view with the predictions from ML backend while trying to label data

### ISSUE THREAD

**Issue by nvinayvarma189** [heartexlabs/label-studio#584]
**Describe the bug**
When we open an image to label it, we are getting the choices pre-populated by the ml backend. This may induce some bias to agree with the model and hence not turn out to be effective.

**To Reproduce**
1. Create a labelling config.
2. Create an ML backend to return predictions based on the labelling config and start it.
3. Start a LS project and provide the URL where ML backend is running.
4. Go to tasks page and import some images.
5. Click on any task row to enable quick view.
6. See the choices getting filled automatically (from ML backend).

**Expected behavior**
The choices should not be pre-populated while viewing a task in the quick view mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/30727381/107002674-94e77080-67b1-11eb-9fe7-b0b8df9f01ed.png)
Here the choice "No" has been auto filled (based on the predictions from my ML backend) as soon as the image has been opened in the quick view mode.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Label Studio version: 0.9.0.post5

**Additional context**
Whole issue described in the general slack channel [here](https://label-studio.slack.com/archives/CQ8LYPPJS/p1612430389264600)

**Comment by makseq** [comment]
@nvinayvarma189 Thank you for your proposal, it has been fixed in the branch for release/0.9.1. It's highly appreciated if you could check it soon :slightly_smiling_face:

**Comment by makseq** [comment]
Feel free to reopen if you have this error in LS > 0.9.1.
