### ISSUE TITLE
output multi-label for YOLOv5

### ISSUE THREAD

**Issue by setdiaoyong** [heartexlabs/label-studio#587]
**Is your feature request related to a problem? Please describe.**

As mention  of [ Rare PLANES](https://medium.com/the-downlinq/you-only-look-once-multi-faceted-object-detection-w-rareplanes-13da3d7aaed0) by  [Ari Chadda ](https://github.com/arichadda/yolov5), multi labels for yolov5 are useful. label studio may be creating a better labeling way.    

**Describe the solution you'd like**

multi-label classification is enabled by default in YOLOv5 in an [issue](https://github.com/ultralytics/yolov5/issues/2143),  
other [web label tool](https://www.sentisight.ai/video-tutorials/multi-label-classification-tutorial/) may have this function, so please considering this multi-label function in label-studio.

      
**Describe alternatives you've considered**

**Additional context**

**Comment by makseq** [comment]
LS supports multi-labeling: [check this config](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CImage%20name%3D%22image%22%20value%3D%22%24image%22%2F%3E%3Cbr%3E%20%20%3CRectangleLabels%20name%3D%22label%22%20toName%3D%22image%22%20choice%3D%22multiple%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Airplane%22%20background%3D%22green%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Car%22%20background%3D%22blue%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Home%22%20background%3D%22red%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Tree%22%20background%3D%22yellow%22%2F%3E%20%20%20%20%3Cbr%3E%20%20%3C%2FRectangleLabels%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E).

**Comment by setdiaoyong** [comment]
> LS supports multi-labeling: [check this config](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CImage%20name%3D%22image%22%20value%3D%22%24image%22%2F%3E%3Cbr%3E%20%20%3CRectangleLabels%20name%3D%22label%22%20toName%3D%22image%22%20choice%3D%22multiple%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Airplane%22%20background%3D%22green%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Car%22%20background%3D%22blue%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Home%22%20background%3D%22red%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Tree%22%20background%3D%22yellow%22%2F%3E%20%20%20%20%3Cbr%3E%20%20%3C%2FRectangleLabels%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E).
