### ISSUE TITLE
Easily move databases

### ISSUE THREAD

**Issue by yanwenjie1** [heartexlabs/label-studio#5872]
I used to use the local SQLite3 database (start command label studio start - p 8081) before, but now I want to switch to the local PGSQL database (start command label studio - db postgreSQL - p 8081), or switch from PGSQL to SQLite3.
But I found that the data is not interconnected. Is there a convenient command to synchronize user information and annotation data with each other.Thanks.

**Comment by makseq** [comment]
You can use this script:
https://github.com/HumanSignal/label-studio-sdk/tree/master/examples/migrate_ls_to_ls

It doesn't make the full migration, however the main entities will be copied.
