### ISSUE TITLE
Unable to export tasks as VOC which were created using api

### ISSUE THREAD

**Issue by LouisDealX** [heartexlabs/label-studio#5875]
**Describe the bug**
Tasks with images were uploaded via the api/tasks endpoint. An image was converted to a base 64 string and then attached as image data. Tasks with images appear in UI and I was able to annotate however exporting to VOC I get the following error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/data_export/api.py", line 200, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "/label-studio/label_studio/data_export/models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/usr/local/lib/python3.10/dist-packages/label_studio_converter/converter.py", line 230, in convert
    self.convert_to_voc(
  File "/usr/local/lib/python3.10/dist-packages/label_studio_converter/converter.py", line 1100, in convert_to_voc
    with io.open(xml_filepath, mode='w', encoding='utf8') as fout:
OSError: [Errno 36] File name too long: '/tmp/tmpikbmhpt8/Annotations/P37t179uzZwsJCJkVJSalPnz4LFizA4GkKAoEcAAAAAAAAAAAAAIBfWnZ2dlhYWFpamo6OjoODQ3mnhIfvCoEcAAAAAAAAAAAAAAAABYU5cgAAAAAAAAAAAAAAABQUAjkAAAAAAAAAAAAAAAAKCoEcAAAAAAAAAAAAAAAABYVADgAAAAAAAAAAAAAAgIJCIAcAAAAAAAAAAAAAAEBBIZADAAAAAAAAAAAAAACgoBDIAQAAAAAAAAAAAAAAUFAI5AAAAAAAAAAAAAAAACgoBHIAAAAAAAAAAAAAAAAUFAI5AAAAAAAAAAAAAAAACgqBHAAAAAAAAAAAAAAAAAWFQA4AAAAAAAAAAAAAAICCQiAHAAAAAAAAAAAAAABAQSGQAwAAAAAAAAAAAAAAoKAQyAEAAAAAAAAAAAAAAFBQCOQAAAAAAAAAAAAAAAAoKARyAAAAAAAAAAAAAAAAFBQCOQAAAAAAAAAAAAAAAAoKgRwAAAAAAAAAAAAAAAAFhUAOAAAAAAAAAAAAAACAgkIgBwAAAAAAAAAAAAAAQEEhkAMAAAAAAAAAAAAAAKCgEMgBAAAAAAAAAAAAAABQUAjkAAAAAAAAAAAAAAAAKCgEcgAAAAAAAAAAAAAAABQUAjkAAAAAAAAAAAAAAAAKCoEcAAAAAAAAAAAAAAAABYVADgAAAAAAAAAAAAAAgIJCIAcAAAAAAAAAAAAAAEBBIZADAAAAAAAAAAAAAACgoBDIAQAAAAAAAAAAAAAAUFAI5AAAAAAAAAAAAAAAACgoBHIAAAAAAAAAAAAAAAAUFAI5AAAAAAAAAAAAAAAACgqBHAAAAAAAAAAAAAAAAAWFQA4AAAAAAAAAAAAAAICCQiAHAAAAAAAAAAAAAABAQf0PXkGnuqSq0gAAAAAASUVORK5CYII=.xml'`

**Expected behavior**
Tasks with annotations should be exported in VOC format and downloaded as a zip file, 

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/166098392/903c2c09-3737-456d-b8d1-b833543dc334)

**Environment (please complete the following information):**
 - OS: Docker Image
 - Label Studio Version 1.12.0

**Comment by LouisDealX** [comment]
Payload used:
`payload = {
        "data": {
            "image": f"data:image/png;base64,{base64_image}",
        },
        "project": project
    }`

**Comment by makseq** [comment]
It won't be possible to export images to other formats when you use base64 directly in task data.
