### ISSUE TITLE
S3 Custom Endpoint URL

### ISSUE THREAD

**Issue by g4challenge** [heartexlabs/label-studio#588]
I would suggest the ability to customize boto3's custom endpoint_url for S3 Cloud Storage.

If for example someone wants to utilize a different set of storages, one could bring ones own S3 server like minio, scaleway, wasabi or some other provider...

This would require the GUI to have one more field defining the storage endpoint_url (predefined with aws) and the boto3 session in `label_studio/storage/s3.py` could get extended.

Alternatives would be a separate flag or something to allow the custom definition, but it would be rather pleasing to just define it via GUI and cmdline.

**Comment by makseq** [comment]
Are you talking about this endpoint - https://github.com/heartexlabs/label-studio/pull/585/files#diff-638450231cc5db6e452255d98e970a1694b6989cf3236b83fefd0be5f951ad97R27 ?

**Comment by g4challenge** [comment]
Yes, this would be it, any configurable S3 Endpoint would solve this issue for me - thanks!

**Comment by makseq** [comment]
Awesome! In this case you can use branch release 0.9.1 or wait a little bit till the release happens. 🙂

**Comment by fpaupier** [comment]
Hi @g4challenge, did you manage to get a custom S3 endpoint working when specifying your endpoint URL in the GUI (let's say for a 3rd party storage such as Scaleway) ? 

On my side the "check connection" steps passes, but I have this error when trying to sync storage for source tasks:

```log
An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/io_storages/api.py", line 86, in post
    storage.validate_connection()
  File "/label-studio/label_studio/io_storages/s3/models.py", line 85, in validate_connection
    result = client.list_objects_v2(Bucket=self.bucket, Prefix=self.prefix, MaxKeys=1)
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.
```
