### ISSUE TITLE
A way to easily verify label assignment

### ISSUE THREAD

**Issue by lastant** [heartexlabs/label-studio#5880]
It would be very useful to be able to have a quick overview of all assigned labels, grouped by the class, then one could easily see if there are any wrong labels. 
I created a script to create this kind of an overview (https://github.com/lastant/yolo-annotations-verify) but hopefully Label Studio can offer this out of the box.

**Comment by makseq** [comment]
Please check this PR:
https://github.com/HumanSignal/label-studio/pull/5909

It allows you to cache labels as a new data column:
![image](https://github.com/HumanSignal/label-studio/assets/501780/c92df4c7-e7f6-4e98-88e2-82bd648dbb50)

**Comment by lastant** [comment]
I mean seeing the actual cropped-out bounding boxes themselves. The small images. If you see all bounding boxes of a specific class from all tasks you can quickly identify misclassified boxes. Otherwise it's very difficult to notice a mistake (when a class of a box is wrong or when a box is totally misplaced), and this seriously damages the model. I've noticed a lot of mistakes in my annotations using the script I provided, and I was labeling quite attentively.
