### ISSUE TITLE
In the project overview, add a column type to see the number of labels in annotations and predictions

### ISSUE THREAD

**Issue by lastant** [heartexlabs/label-studio#5881]
So far there are only columns 'Annotations' and 'Predictions', which actually mean 'revisions' it seems, but there's no way to see the actual number of labels, annotated and predicted. It would be useful if one expects a certain number of labels and could easily identify if labels are missing or too many.

**Comment by makseq** [comment]
1. You can update your LS to the latest version from the github develop branch,
2. run LS with experimental feature `EXPERIMENTAL_FEATURES=1 label-studio` (or add this variable to your environment variables), 
3. and then use the action "Cache Labels" in the Data manager: https://github.com/HumanSignal/label-studio/pull/5909

However, you have to run this action from time to time to invalidate the cache. Also note that opensource LS version doesn't have background workers and this operation might take long time if your dataset is huge. 

Example:
![image](https://github.com/HumanSignal/label-studio/assets/501780/3297087c-7e9b-44b6-9685-5471fc43aac6)
You will see a new data column with labels and their counters.

**Comment by lastant** [comment]
Thank you! But is there a way to see the total number of labels?

**Comment by makseq** [comment]
@lastant you mean for all tasks? If yes, it's an LS Enterprise feature (see regions created): 
![image](https://github.com/HumanSignal/label-studio/assets/501780/e0124846-2079-4068-a7ed-f6e909f6147e)

**Comment by lastant** [comment]
I mean showing the total number of labels in each task. Next to ID 2752 it would say 3. Next to 2753 - 1 ... Next to 427402 - 20

**Comment by makseq** [comment]
Cache Labels will show it.
