### ISSUE TITLE
Integration with existing Postgres database

### ISSUE THREAD

**Issue by mihalt** [heartexlabs/label-studio#5885]
hi! Do you have any recommendations how to sync fields with my existing postgres database (connected to my django project) and label studio? Would be good even not duplicate this fields between them, because there is a lot of info. I need just interface of label studio in my django admin panel in fact. Would be good to see any recommendations on documentation.

**Comment by makseq** [comment]
Hi! To integrate Label Studio with your existing PostgreSQL database and Django project, you can follow these steps:

1. **Use the Same PostgreSQL Database:**
   - Configure both your Django project and Label Studio to use the same PostgreSQL database. This way, you avoid duplicating data and ensure consistency.

2. **Configure Label Studio to Use Your PostgreSQL Database:**
   - Update the Label Studio configuration to point to your existing PostgreSQL database. You can do this by setting the appropriate environment variables or updating the `settings.py` file in Label Studio.

3. **Integrate Label Studio into Your Django Admin Panel:**
   - You can add Label Studio's models to your Django admin panel by registering them in your `admin.py` file. This allows you to manage Label Studio data directly from your Django admin interface.

4. **Use Django's ORM to Sync Data:**
   - Utilize Django's ORM to create views or serializers that can sync data between your existing models and Label Studio's models. This can be done using Django signals or periodic tasks with Celery.

### Example Configuration

#### 1. Configure Label Studio to Use Your PostgreSQL Database

Update the environment variables for Label Studio to use your PostgreSQL database:

```bash
export DJANGO_DB=default
export POSTGRE_NAME=your_db_name
export POSTGRE_USER=your_db_user
export POSTGRE_PASSWORD=your_db_password
export POSTGRE_PORT=5432
export POSTGRE_HOST=your_db_host
```

Alternatively, update the `settings.py` file in Label Studio:

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'your_db_name',
        'USER': 'your_db_user',
        'PASSWORD': 'your_db_password',
        'HOST': 'your_db_host',
        'PORT': '5432',
    }
}
```

#### 2. Register Label Studio Models in Your Django Admin

In your Django project's `admin.py` file, register the Label Studio models:

```python
from django.contrib import admin
from label_studio.tasks.models import Task, Annotation
from label_studio.projects.models import Project

admin.site.register(Task)
admin.site.register(Annotation)
admin.site.register(Project)
```

#### 3. Sync Data Using Django ORM

Create a Django management command or a Celery task to sync data between your existing models and Label Studio's models. For example:

```python
from django.core.management.base import BaseCommand
from myapp.models import MyModel
from label_studio.tasks.models import Task

class Command(BaseCommand):
    help = 'Sync data between MyModel and Label Studio Task'

    def handle(self, *args, **kwargs):
        my_models = MyModel.objects.all()
        for my_model in my_models:
            Task.objects.update_or_create(
                id=my_model.id,
                defaults={
                    'data': my_model.data,
                    'project': my_model.project,
                }
            )
        self.stdout.write(self.style.SUCCESS('Data sync complete'))
```

### Documentation References

For more detailed information, you can refer to the following documentation:

- [Label Studio Database Setup](https://labelstud.io/guide/storedata.html)
- [Django Admin Site Documentation](https://docs.djangoproject.com/en/stable/ref/contrib/admin/)
- [Django Management Commands](https://docs.djangoproject.com/en/stable/howto/custom-management-commands/)

By following these steps, you can integrate Label Studio with your existing PostgreSQL database and manage it through your Django admin panel without duplicating data.
