### ISSUE TITLE
heroku integration failing because of outdate version of postgresql (13)

### ISSUE THREAD

**Issue by alexislitvine** [heartexlabs/label-studio#5894]
We tried to create heroku-postgresql:essential-0, but received an error from the add-on provider. Try the request again, or log a support ticket and include this message: Unsupported version: 13. We support the following versions: 14, 15, 16

**Comment by sajarin** [comment]
Thanks @alexislitvine for making this issue, our team will look into seeing if an upgrade to a newer version of Postgres can be rolled out. 

In the meantime, did you do any upgrades/workarounds on your end to get it working with heroku? Apologies if I'm misunderstanding.

**Comment by farioas** [comment]
The issue has been resolved, please try to click on the button again.
