### ISSUE TITLE
Large file import error

### ISSUE THREAD

**Issue by yanwenjie1** [heartexlabs/label-studio#5904]
**Describe the bug**
When I uploaded a 500M (200000 samples) file to a Ner task, the sample import page reported an error [You cannot access body after reading from request's data stream].

**Screenshots**
![test](https://github.com/HumanSignal/label-studio/assets/109565045/3ad5cf0d-f703-4802-93b1-fcd8f7c9b740)

**Environment (please complete the following information):**
 - OS: windows server 2016 datacenter
 - Label Studio Version [e.g. 1.12.0.post0]

**Comment by yanwenjie1** [comment]
Later, I split a large file into 20 files (each with 10000 samples), selected and submitted them in bulk on the import interface, and succeeded. However, why is a complete large file not working.

**Comment by makseq** [comment]
### 1. **Use Cloud Storage for Large Files**
Label Studio's UI is not optimized for handling very large files directly. Instead, it's recommended to use cloud storage solutions for managing large datasets. Here’s how you can do it:

1. **Set up a Cloud Storage Bucket:**
   - Use a provider like Amazon S3, Google Cloud Storage, or Azure Blob Storage.
   - Upload your large files to the cloud storage bucket.

2. **Configure Cloud Storage in Label Studio:**
   - Go to the project settings in Label Studio.
   - Add a new cloud storage connection and configure it with the necessary credentials and details to access your cloud storage bucket.

3. **Sync Data from Cloud Storage:**
   - Use the "Sync" feature in Label Studio to synchronize the data from your cloud storage into Label Studio. This will create tasks in Label Studio without uploading the files through the UI.

For more information on setting up and using cloud storage with Label Studio, refer to the [official documentation on external storage connections and sync](https://labelstud.io/guide/storage.html).

### 2. **Adjust Server Configuration**
If you prefer to continue using local uploads, you may need to adjust your server configuration to handle large files better. Here are some adjustments you can make:

1. **Increase the Maximum Request Size in Nginx:**
   - Edit your Nginx configuration file (usually located at `/etc/nginx/nginx.conf` or `/etc/nginx/conf.d/default.conf`).
   - Add or modify the `client_max_body_size` directive to a value larger than your file size. For example:
     ```nginx
     http {
         ...
         client_max_body_size 1G;
         ...
     }
     ```
   - Restart Nginx to apply the changes:
     ```bash
     sudo service nginx restart
     ```

2. **Adjust Django Settings:**
   - Ensure that your Django settings allow for large file uploads. You can adjust the `DATA_UPLOAD_MAX_MEMORY_SIZE` setting in your `settings.py` file:
     ```python
     DATA_UPLOAD_MAX_MEMORY_SIZE = 1048576000  # 1 GB
     ```

### 3. **Split Large Files**
As you have already done, splitting large files into smaller chunks can help bypass the limitations of the server and the application. This method is effective but can be cumbersome for very large datasets.

### Summary
For optimal performance and to avoid such issues, it's highly recommended to use cloud storage solutions for large datasets. This approach not only handles large files more efficiently but also provides better scalability and management of your data.
