### ISSUE TITLE
Videos in AWS do not load in Google Chrome or Microsoft Edge

### ISSUE THREAD

**Issue by j-wilson-64** [heartexlabs/label-studio#5907]
**Describe the bug**
Videos in AWS s3 load in FireFox but not Google Chrome or Microsoft Edge. The preview on the project homepage will say "Unable to play" and attempting to load the video for annotations will play the loading animation endlessly.

**Environment:**
 - OS: Windows 10
 - Label Studio Versions: 1.12.0.post0 & 1.12.1
 - Python versions: 3.9.13 & 3.11.5 & 3.11.8

**Additional context**
- No error occurs when trying to load the videos from AWS s3 in Google Chrome or Microsoft Edge
  - Even when setting `--log-level DEBUG` the terminal output is essentially the same as when properly loading through FireFox
- Behavior has been tested and confirmed on multiple computers on Windows 10
- Both versions of `label-studio` were installed through `pip` for all versions of Python
- Using the import option to import locally stored videos will properly load videos in Google Chrome for annotation

**Comment by makseq** [comment]
Firefox supports a few video formats that are not supported by Chrome and Edge. One such format is MP4V-ES (MPEG-4 Video Elemental Stream). This format is part of the MPEG-4 Part 2 Visual standard and is primarily used for streaming MPEG-4 audio and video over mobile connections. Firefox uniquely supports MP4V-ES in 3GP containers, which is not supported by Chrome or Edge.

Another format to note is Theora. Theora is an open and free video codec developed by Xiph.org, designed for use in the Ogg container format. It is supported by Firefox but not by Safari, and while Chrome and Edge do support it, Firefox's implementation and support for Theora is more robust.

For more details on the specific formats and their support across different browsers, you can refer to the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers) and [Mozilla Support](https://support.mozilla.org/en-US/kb/fix-common-audio-and-video-issues).
