### ISSUE TITLE
Can load images from local storage, but not videos

### ISSUE THREAD

**Issue by dr-dvice** [heartexlabs/label-studio#5934]
**Describe the bug**
Unable to load videos from local storage for labeling, even though the video shows when clicking the url link.

**To Reproduce**

1. Install label-studio using anaconda instructions from docs
2. Launch label-studio from newly installed conda env
3. Press "Create" to create new project
4. Under "Labelling Setup" tab, select "Object Detection with Bounding Boxes"
5. Under Configure data select "\<set manually\>" and type in "$url" (I have also tried "$vid" and selecting \<imported file\> instead) then hit "save"
6. Select "Go To Import" then "Upload Files" and upload test video under 50 MB then "Import"
7. By "url" in the top left under "actions", select the "img" button and change it to "vid"
8. Observe error. Selecting "click to load" loads a preview of the video, but the video itself does not show up on the editor. Selecting the URL link successfully opens the file in the browser (i'm using firefox)
![Screenshot from 2024-05-30 17-02-17](https://github.com/HumanSignal/label-studio/assets/118024954/2d42cf9f-4d36-420b-bfdb-2e59c596b24a)

I've followed the steps mentioned in several other similar issues to try to fix this, including:
Making sure the environmental variables are present:
![environmentvars](https://github.com/HumanSignal/label-studio/assets/118024954/703ea2d7-a21c-4b3b-8128-6d224e308c1c)

Making sure the absolute root path is correct, and uploading by syncing files from the storage folder::
![morebug](https://github.com/HumanSignal/label-studio/assets/118024954/69cb5deb-90b9-42e3-a579-5c43b28fb39d)
![strorage](https://github.com/HumanSignal/label-studio/assets/118024954/17b7533a-ecd6-41c9-8786-be7c0572dcf2)

**Expected behavior**
I expect for the video to appear in the editor for labeling.

**Environment (please complete the following information):**
 - OS: UBUNTU 22.04
 - Label Studio v 1.12.1

**Additional context**
I've tried to upload both .mp4 files and .webm files, I've also tried reducing the size from ~50 MB to just ~1 MB, still doesn't work
Images do load successfully, videos don't.

Potentially relevant errors from browser console:
![Screenshot from 2024-05-30 17-10-39](https://github.com/HumanSignal/label-studio/assets/118024954/4ad9f2ee-d1b0-4810-a3ad-9b6d8332de35)
(however, refreshing the page makes these errors disappear)

**Comment by makseq** [comment]
It seems you are trying to use an incorrect labeling config. 
The correct one is "Video Object Tracking". 
![image](https://github.com/HumanSignal/label-studio/assets/501780/38ea3327-303b-4805-a80d-ffaf6704e98a)

**Comment by dr-dvice** [comment]
Changing the project to the correct configuration doesn't work, but starting a new one from scratch with the correct configuration does! Thank you very much.
