### ISSUE TITLE
Enhanced Crosshair Cursor for Labelling

### ISSUE THREAD

**Issue by JLZ22** [heartexlabs/label-studio#5935]
**Problem**
I have been using the tool, and it is great. However, I always find myself making boxes and then re-adjusting them because I cant quite tell where an object starts and ends on the x and y axises if the object is slanted or irregularly shaped.

**Suggestion for Solution**
I think a really useful solution to this problem is to draw an image-wide crosshair on the mouse at all times. This way, you will know if the corners of your bounding box are exactly right or not. I think this would improve efficiency in labeling because a lot of labels won't need to be readjusted. 

**Additional context**
The vision is to have something like what is shown in the last post of this thread. https://stackoverflow.com/questions/37542669/enhanced-crosshair-cursor-possible 
<img width="445" alt="image" src="https://github.com/HumanSignal/label-studio/assets/77515221/50e8d88e-d449-4249-81e9-d518c7198c30">

**Comment by sajarin** [comment]
Thanks for the feature request @JLZ22, our team will review and see how it fits into our current roadmap! 

How big of a pain would you say this is for you at the moment?

**Comment by JLZ22** [comment]
I would say it slows down the labeling process by 1.75x to 2.5x. When
labeling, I initially give each object a bounding box. Then, I zoom in to
fix any errors that I made when eyeballing it to ensure that the boxes are
as tight as possible. Since I need to pan and zoom in to almost every
object in an image object, labelling is a lot slower than it could be with
this proposed feature. Thank you for your quick response. I hope this
helps. Best of luck!

**Comment by NickSwardh** [comment]
The crosshair exist but you have to enable it manually in your labeling interface. https://labelstud.io/tags/image. Look for the `crosshair` parameter.

Basically you just add the crosshair property to your labeling interface. Click on `Settings` -> `Labeling interface` -> `Code` and then add the property to your `<image>` tag.

Ex:
`<Image name="image" value="$image" crosshair="true"/>`

**Comment by JLZ22** [comment]
Thanks for letting me know. This works perfectly!

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
