### ISSUE TITLE
How do I import image and task via API

### ISSUE THREAD

**Issue by Karmendes** [heartexlabs/label-studio#596]
I started with my instance with --allow-serve-files-locations and set a directory to scan as images.

However I did not understand how I can use an API so that from a client I can send an image and automatically a new task appears in the UI of labelstudio

**Comment by makseq** [comment]
1. LS by itself is not a good solution for image hosting. I recommend you to use another hosting server (like Amazon S3 / local nginx to save images). But if you still want to import images, you need to use `/api/project/import` with html-formatted file form:

```bash
curl -X POST -F "FileUpload=@test.jpg" http://localhost:8080/api/project/import
```

**Comment by makseq** [comment]
@Karmendes

**Comment by Karmendes** [comment]
Thank you @makseq

So, I put my images on s3. Now imagine that I put new images in BUCKET, what would be the API call for these new images to be scanned as new tasks?

**Comment by makseq** [comment]
You have two ways: 
1. Use S3 storage from LS directly (go to Settings => Cloud storage sync section), add Source storage via dialog. 
2. Get links to your s3 files and call this API: 
```
curl -X POST -H Content-Type:application/json http://localhost:8080/api/project/import \
--data "[{\"image\": \"https://s3-link.to/your-image.jpg\"}]"
```

**Comment by Karmendes** [comment]
Ok!Thanks!
