### ISSUE TITLE
Annotations for PDFs

### ISSUE THREAD

**Issue by ReedGraff** [heartexlabs/label-studio#5967]
**Problem**
There are no good open-source tools for annotating PDFs. In my project's application, I need to use CV to highlight and put rectangles around various parts of a pdf. This should be a relatively easy fix.
<img width="617" alt="Example" src="https://github.com/HumanSignal/label-studio/assets/71910763/d2726c3f-15ac-4955-8f5d-eb61ac064e03">
*Example of what annotations would look like on a pdf*

**Solution**
Enable users to upload PDFs as an approved data type.

**Alternatives**
At the moment, I have been doing this manually by uploading my document to Gimp, placing a rectangle over the images of the pdf to determine the coordinates of the rectangles, and then manually creating a CSV for this data.

**Potential Solution**
An easy way to do this is to convert them into a series of images (one image for each page). Then, treat it like any other image, just maintaining the page number as a part of the outputted data somewhere.

**Notes**
I do not need OCR; there are many tools for this. All I need is to convert a PDF to a series of images that I can then annotate for my CV. Example output for rectangles across a pdf:
```csv
Page Number, Class, Top Left, Bottom Right
0, 0, (300px, 200px), (400px, 300px)
0, 0, (600px, 200px), (750px, 250px)
0, 1, (790px, 600px), (820px, 675px)
1, 4, (810px, 100px), (880px, 145px)
1, 3, (300px, 200px), (400px, 300px)
```
etc...

**Comment by ReedGraff** [comment]
![V7Example](https://github.com/HumanSignal/label-studio/assets/71910763/57945e5e-512c-47a4-9ca5-86f0402560fe)
Here is an example using V7 Labs.

**Comment by makseq** [comment]
You can do this work in Label Studio, but you have to convert your PDF pages to images. PDF are not supported directly. 
Check this template: https://labelstud.io/templates/image_bbox
