### ISSUE TITLE
Project loading error: string indices must be integers

### ISSUE THREAD

**Issue by Yannik1337** [heartexlabs/label-studio#597]
**Describe the bug**
I am running LabelStudio on a Kubernetes cluster. I want to do audio classification, and I have initialised the project already.
When I start everything, the UI is loading, but I get the above mentioned untraceable error:

```
Project loading error
string indices must be integers
Traceback
Traceback (most recent call last):
  File "/label-studio/label_studio/utils/misc.py", line 93, in exception_f
    return f(*args, **kwargs)
  File "/label-studio/label_studio/blueprint.py", line 96, in prepare_globals
    g.project = project_get_or_create()
  File "/label-studio/label_studio/blueprint.py", line 187, in project_get_or_create
    input_args, context={'multi_session': False})
  File "/label-studio/label_studio/project.py", line 996, in get_or_create
    project = cls.get(project_name, args, context)
  File "/label-studio/label_studio/project.py", line 979, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/label-studio/label_studio/project.py", line 967, in _load_from_dir
    return cls(config, project_name, context=context, root_dir=args.root_dir)
  File "/label-studio/label_studio/project.py", line 87, in __init__
    self.load_project_and_ml_backends()
  File "/label-studio/label_studio/project.py", line 459, in load_project_and_ml_backends
    self.add_ml_backend(ml_backend_params, raise_on_error=False)
  File "/label-studio/label_studio/project.py", line 431, in add_ml_backend
    ml_backend = MLBackend.from_params(params)
  File "/label-studio/label_studio/utils/models.py", line 489, in from_params
    ml_api = MLApi(params['url'], params['name'])
TypeError: string indices must be integers
```
**To Reproduce**
1. Intialise the project locally
2. Create the image with this template:
```
FROM heartexlabs/label-studio:latest

RUN apt-get install -y \
     nano \
     tree \
     htop

RUN mkdir /.local /.config project
COPY project/ project/

RUN chown -R xyz:group /label-studio && chown -R xyz:group /.local && chown -R xyz:group /.config
USER xyz

RUN tree

CMD ["sh", "-c", "label-studio start project"]
```

3. Using kubernetes services, I can then access the running LS, but am greeted with the following error. The error is shown on every page:

![Bildschirmfoto 2021-02-15 um 14 38 18](https://user-images.githubusercontent.com/50734087/107953501-819b8880-6f9b-11eb-860d-175dee1fcaa2.png)

**Additional context**
I want to classify/label audio files that are located on disk. I initiated the project with 
```
label-studio init project --input-path=path/to/folder/ --input-format=audio-dir --label-config=config.xml
```
Locally, this setup runs fine. Any suggestions are recommended.

---

Edit:
After experimenting around more, it looks as if you do not need this complicated setup to reproduce this issue:
Create an image with this Dockerfile (I checked back to 0.8.0, issue persists there as well):

```
FROM heartexlabs/label-studio:latest

RUN apt-get install -y \
     nano \
     tree \
     htop

RUN label-studio init project

CMD ["sh", "-c", "label-studio start project"]
```
Then, create a kubernetes service, and a deployment accordingly (can't provide these files due to privacy concerns).
Afterwards, go to the IP given to you by the service, and you'll see above screenshot.

**Comment by makseq** [comment]
I'm not sure about this line:

```
CMD ["sh", "-c", "label-studio start project"]
```
Especially about "label-studio start project".
Let's try 
```
CMD ["sh", "-c", "label-studio", "start", "project", "--init"]
```

But it's better to use 
```
CMD ["./tools/run.sh"]
```
with ./tools/run.sh:
```
#!/bin/bash

label-studio start ${PROJECT_NAME:-my_project} -b \
             --host ${HOST:-0.0.0.0} --port ${PORT:-8080} --protocol ${PROTOCOL:-http://} \
             --username ${USERNAME:-""} --password ${PASSWORD:-""} ${INIT_COMMAND:-"--init"}
```

**Comment by Yannik1337** [comment]
Thanks for your input, I can now run LS on the server. For others looking for a solution, this was my approach.
I found it to be necessary to initialize the project within the image, rather than just copying an existing project to the image (see the commented lines):

```
FROM heartexlabs/label-studio:latest

RUN mkdir /.local /.config ./project
COPY run.sh run.sh
COPY project/tasks.json tasks.json
COPY project/config.xml config.xml
#COPY project ./project/

RUN apt-get update && apt-get install -y nano

#COPY project/ ./project/

RUN chown -R 1166:1002 /label-studio && chown -R 1166:1002 /.local && chown -R 1166:1002 /.config
USER 1166

RUN label-studio init project --label-config=config.xml --input-path=tasks.json --input-format=audio-dir --source=tasks-json
COPY project/tasks.json ./project/
COPY config.json ./project/

CMD ["sh", "./run.sh"]
```

After the project is initialized, I copy my stuff into the project folder--I do this since I set some settings in config.json that I can not set in the image otherwise.
