### ISSUE TITLE
Cannot Log In on Another Computer Even With Matching Passwords and Emails

### ISSUE THREAD

**Issue by Hateley123** [heartexlabs/label-studio#5980]
I downloaded label studio onto my work computer, but I am unable to log in even though I know the email and passwords match. On my personal computer, the retyped credentials let me in but when I do it on the new download it does not let me log in.

**Comment by Car85** [comment]
You should note this part of the documentation:

> SQLite database
> 
> Label Studio uses SQLite by default. You don’t need to configure anything. Label Studio stores all data in a single file in the specified directory of the admin user. After you start Label Studio, the directory used is printed in the terminal.
> [More Info](https://labelstud.io/guide/storedata)

Your user data is stored in an SQLite file on your personal computer.
![imagen](https://github.com/HumanSignal/label-studio/assets/170861775/0775e643-458c-410c-8692-d98352276628)

When I run Label Studio locally, it indicates a path near the end of the console. Within the share/label-studio directory, you should find your database with your credentials. Replace the SQLite file on your work computer with the one from your personal computer to solve your problem.

Best regards.

**Comment by sajarin** [comment]
Thanks for stepping in @Car85 and answering, love to see it! @Hateley123 feel free to make another issue if you run into any problems or message me on our Slack!
