### ISSUE TITLE
Question: Backend import of annotations from csv file

### ISSUE THREAD

**Issue by slychief** [heartexlabs/label-studio#599]
Hi,

I was wondering if there is a faster or more direct API to process label-studio data. I have a csv file with audio annotations and want to import it into label-studio. My current understanding is that I need to use "curl -X POST -H Content-Type:application/json http://localhost:8080/api/..." for each annotation I want to add.

From a Python script, I then need to use an os interface like subprocess.call("curl ...").

Is there a faster, more elegant way to do this. Something like:

```
studio = LabelStudio(ip="127.0.0.1", port=8080)
studio.post(data)
```

best regards,
Alex

**Comment by slychief** [comment]
Sorry for the bug label. I just don't know how to remove it.

**Comment by makseq** [comment]
@slychief Hi! 

Do you want to use only API / SDK ways to import annotations? Why don't you use GUI way? By GUI I mean is to prepare json file for import with tasks and annotations.

**Comment by slychief** [comment]
I need to fully automate the experimental design and reduce manual interaction to a minimum. Thus I am creating label-studio projects with an automated script and this script should also load the annotations from a csv file. After training and inference of the models, users should only evaluate the prediction results.

I'm also fine with creating the json files for the tasks and completions automatically. I just can't figure out how to do it right. I'm currently reading "How to make pre-annotations & pre-labeling & predictions" in the FAQs. But this also requires manual copy&paste.

**Comment by makseq** [comment]
Ok. I think it's optimal for you to call API as it described here: https://labelstud.io/guide/api.html#Import-data-and-tasks

```
curl -X POST -H Content-Type:application/json http://localhost:8080/api/project/import \
--data "[{\"my_key\": \"my_value_1\"}, {\"my_key\": \"my_value_2\"}]"
```

Include to your tasks `data` and `predictions` fields.

**Comment by slychief** [comment]
Thank you for the quick confirmation!

**Comment by slychief** [comment]
Hi,

I'm sorry. But I still need help on the same topic. I now try to import everything using a pre-existing json file

`label-studio init --input-path=my_tasks.json`

I'm using the tasks.json from a previous project to import the audio files into a new project:

`
{
    "1": {
        "id": 1,
        "task_path": "\/path\/to\/audio1.mp3",
        "data": {
            "audio": "\/data\/audio1.mp3?d=%2Fpath%2Fto%2Faudio1%2Fmp3"
        }
    },
    "2": {
        "id": 2,
        "task_path": "\/path\/to\/audio2.mp3",
        "data": {
            "audio": "\/data\/audio2.mp3?d=%2Fpath%2Fto%2Faudio2%2Fmp3"
        }
    }
}
`

I cannot find out from the documentation, how exactly the tasks.json should be compsed in order to correctly use it for the import.

**Comment by makseq** [comment]
Hi, it's a good point for our documentation to make it more clear :slightly_smiling_face: 
Try this one: 

```
[ 
 { "id": 1, "task_path": "\/path\/to\/audio1.mp3", "data": { "audio": "\/data\/audio1.mp3?d=%2Fpath%2Fto%2Faudio1%2Fmp3" } },  
 { "id": 2, "task_path": "\/path\/to\/audio2.mp3", "data": { "audio": "\/data\/audio2.mp3?d=%2Fpath%2Fto%2Faudio2%2Fmp3" } } 
]
```

**Comment by makseq** [comment]
Also you can check this section: 
https://labelstud.io/guide/api.html#Import-data-and-tasks
