### ISSUE TITLE
Runtime error with LOCAL_FILES_SERVING_ENABLED 

### ISSUE THREAD

**Issue by shainarazavi** [heartexlabs/label-studio#6010]
RUNTIME ERROR
Validation error
[ErrorDetail(string="Serving local files can be dangerous, so it's disabled by default. You can enable it with LOCAL_FILES_SERVING_ENABLED environment variable, please check docs: https://labelstud.io/guide/storage.html#Local-storage", code='invalid')]

**Comment by sajarin** [comment]
hey @shainarazavi 

Can you share your labelling config, as well as the version you're using of Label Studio? 

Also is the LOCAL_FILES_SERVING_ENABLED environment variable enabled? Sorry if i'm misunderstanding, It wasn't clear in your message.

**Comment by shainarazavi** [comment]
its resolved.

**Comment by NoKOUTIANWU** [comment]
How did you solve this problem, I configured the environment variables correctly but still got this error
