### ISSUE TITLE
Data disappears when zooming in, re-appears when zooming out

### ISSUE THREAD

**Issue by jardinetsouffleton** [heartexlabs/label-studio#602]
**Describe the bug**
When zooming out, the data appears, but disappears when zooming in. It re-appears when zooming out again. 

**Setting**
- Time series annotation 
- 147,000 data points in a CSV file
- 4 Channels
- 2 labels

**To Reproduce**

1. Load the data using the GUI
2. Create an XML config for 2 labels, 4 channels
3. Place some annotations in a very close zoom and move forward in time
4. At some point, the data will disappear when in close zoom and will re-appear when zoomed out

**Expected behavior**: Because of the large data volume, zooming in and out is very useful. Zooming out gives global context and zooming in allows for finer annotations to be made. Therefore, as a user, I would like to quickly zoom in and out to understand the global context and place fine annotations

**Screenshots**
![label_studio_zoom_bug](https://user-images.githubusercontent.com/30133110/108134868-f991ad80-7084-11eb-9499-3c0fa69da117.gif)

**Environment (please complete the following information):**
 - Windows 10
 - Google Chrome
 - Label Studio Version 0.9.0.post5

**Comment by makseq** [comment]
@jardinetsouffleton Thank you very much for your report. I've created a ticket with this bug in our Jira, I hope we will fix it soon. 
BTW what a cool black theme :slightly_smiling_face:

**Comment by jardinetsouffleton** [comment]
No problem! I love the tool you are building, it's a real time saver.

**Comment by kvr777** [comment]
Hi, @makseq Thank you for the great tool. Do you have any updates regarding to this issue? I have the same problem: when time series are longer than several thousands of items, this bug appears. It would be great to fix it or provide some temporary solution how to deal with it.
