### ISSUE TITLE
Metadata of labels cannot be modified

### ISSUE THREAD

**Issue by bernhofer** [heartexlabs/label-studio#6025]
**Describe the bug**
Metadata of box labels cannot be modified and saved. When I try to change and update it, the label contains the old metadata.

**To Reproduce**
1. Create a box label
2. Add metadata (alt+m) e.g. "test1" to label and submit task.
3. Change the metadata to e.g. "test2" and update.
4. Bug: label still contains "test1".

**Expected behavior**
The metadata in should change to "test2".

**Environment:**
 - OS: Docker Image 1.12.1
 - Label Studio Version: v1.12.1
 
 **Edit:**
I just saw that this is a duplicate of [#5314](https://github.com/HumanSignal/label-studio/issues/5314) which is also an open issue.

**Comment by sajarin** [comment]
hey @bernhofer, thanks for making this issue. Closing it because it's a duplicate as you pointed out but definitely please comment on the other issue so we can consolidate all of the issues, the more people who report it, the more priority it will be given
