### ISSUE TITLE
Task ID is not monotonic increasing

### ISSUE THREAD

**Issue by shisaru292** [heartexlabs/label-studio#6037]
**Describe the bug**
The task id value of the newly added item increases from the maximum value of the existing tasks, not the historical maximum value. So it's not monotonically increasing, which may lead to data inconsistency. For example, a task is annotated, exported and stored, but then deleted along with the project. The newly labeled data may have the same task id.

For this reason, the task id cannot be used as a unique/primary key either.

**To Reproduce**
1. create 3 projects and have 100 tasks in each project
  - max task id in db: 300
  - max task id in history: 300 
2. delete the 3rd project
  - max task id in db: 200
  - max task id in history: 300 
3. create the 4th project with 50 tasks, the task ID is start from 201 not 301, so that
  - max task id in db: 250
  - max task id in history: 300

**Expected behavior**
Task ID should be incremented monotonically whether or not a project or task is deleted

**Screenshots**
No

**Environment (please complete the following information):**
 - Label Studio Version 1.12.1

**Additional context**
No

**Comment by makseq** [comment]
Task ids are assigned by the DB backend that is in use for your Label Studio instance. It seems you are using sqlite backend. If you switch to postgresql, it will behave as you expect.

**Comment by shisaru292** [comment]
Thank you for your answer. @makseq 

But I'm still confused about some of the details. 

I have checked the `sqlite3` file generated by LS. Both project ID and Task ID has been set to `AUTOINCREMENT`

task table:

```
sqlite > SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'task';

CREATE TABLE "task" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "data" text NOT NULL CHECK (
        (
            JSON_VALID ("data")
            OR "data" IS NULL
        )
    ),
    "created_at" datetime NOT NULL,
    "updated_at" datetime NOT NULL,
    "project_id" integer NULL REFERENCES "project" ("id") DEFERRABLE INITIALLY DEFERRED,
    ...
)
```

project:

```
SELECT sql FROM sqlite_master WHERE type = 'table' AND name = 'project';

CREATE TABLE "project" (
    "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" varchar(50) NULL,
    "label_config" text NULL,
    "expert_instruction" text NULL,
    "show_instruction" bool NOT NULL,
    "model_version" text NULL,
    ...
)
```

But only the project ID won't use a previously used ID! 

The [document](https://www.sqlite.org/autoinc.html) of sqlite said that:

> On an INSERT, if the ROWID or INTEGER PRIMARY KEY column is not explicitly given a value, then it will be filled automatically with an unused integer, usually one more than the largest ROWID currently in use. This is true regardless of whether or not the AUTOINCREMENT keyword is used.
> If the AUTOINCREMENT keyword appears after INTEGER PRIMARY KEY, that changes the automatic ROWID assignment algorithm to prevent the reuse of ROWIDs over the lifetime of the database. In other words, the purpose of AUTOINCREMENT is to prevent the reuse of ROWIDs from previously deleted rows.

Which means the task ID should prevent the reuse of ROWIDs from previously deleted rows. And when checking the internal table named "[sqlite_sequence](https://www.sqlite.org/fileformat2.html#seqtab)", the ROWID value of `task` table seems working correctly: it stored the largest taskid in history. However, the new task does not necessarily create an id with this value.
