### ISSUE TITLE
Unable to load tiff files for labelling

### ISSUE THREAD

**Issue by smitaSalgode** [heartexlabs/label-studio#604]
In the Label studio tool, i am able to import tiff files. However, when i click on the task to preview the tiff file for labelling. I get an load error as below
<img width="631" alt="tiff error" src="https://user-images.githubusercontent.com/29054979/108168540-7d977400-711d-11eb-8ebd-198bd6e58f31.PNG">

Cannot load image (/data/upload/df8721-file_example_TIFF_1MB.tiff). Check console/network panel for more info.

**Comment by makseq** [comment]
There seems your browser doesn't support tiff images. Try to open this image directly in the browser, without LS.

**Comment by smitaSalgode** [comment]
I am able to view tiff files in Chrome.
The same issue i am facing even on other browsers. I tried with Firefox as well

**Comment by makseq** [comment]
Could you say what is the full path in the browser to your LS instance? E.g.: http://localhost:8080/ or domain.com/ls/

**Comment by smitaSalgode** [comment]
Its label-studio.domain.com/

**Comment by makseq** [comment]
In this case you need to setup a HOST environment variable. Check this guide: https://labelstud.io/guide/FAQ.html#How-to-run-LSB-with-external-domain-name

**Comment by smitaSalgode** [comment]
Thank you Max. i will try this and let you know

**Comment by makseq** [comment]
Don't forget to re-import your images, because HOST settings affect it/

**Comment by smitaSalgode** [comment]
Hi Max,
We ran this below command

nohup label-studio start --host label-studio.domain.com my_project --username ***** --password ***** --init --force > output.log &

Still no luck. Tried re-importing the file as well

**Comment by makseq** [comment]
And what error do you have now?

**Comment by smitaSalgode** [comment]
Still the same error.. unable to load the file.
It is the same error we get when we try to load non supported files like pdf

**Comment by makseq** [comment]
On your previous screenshot I see path /data/upload/...
If your domain is correct, you will see label-studio.domain.com/data/upload/...

Also you can try to upload JPG files. Will they be processed correctly?

**Comment by smitaSalgode** [comment]
Yes.. now i am able to see the path as label-studio.domain.com/data/upload
and i am able to process jpg files without any issues

You can also refer this tool tink https://app.labelstud.io/tasks?tab=1&task=0
Even in this link, the tiff file processing fails

**Comment by makseq** [comment]
Please, share your project on app.labelstud.io with me: go to Settings =>
Project management => click the mini icon near the project name in the list
of projects.

чт, 18 февр. 2021 г. в 14:49, smitaSalgode <notifications@github.com>:

**Comment by smitaSalgode** [comment]
Here is the link

https://app.labelstud.io/api/project-switch?uuid=0cfba174-08c9-48c7-91b9-9a9c338cfa40

**Comment by makseq** [comment]
Thanks. I tried to open links for tiff files in my browser directly and it
failed. It means my browser (chrome) doesn't support tiff.
Check this table:
https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support

чт, 18 февр. 2021 г. в 17:16, smitaSalgode <notifications@github.com>:

**Comment by srv-gabriel** [comment]
I'm using Chromium, that supports tiff images, as you can see on the table you shared. However I am getting the same error. "Cannot load image...".

**Comment by gmihaila** [comment]
Safari is the only browser that it's able to display TIFF files. I can't use Label-studio now because my team has Windows and there is no way for them to view the images in the browser... Only solution is to convert TIFF to other format.
