### ISSUE TITLE
export YOLO format

### ISSUE THREAD

**Issue by johnson7788** [heartexlabs/label-studio#606]
**Is your feature request related to a problem? Please describe.**
if it can export image to YOLO format, it will be better. thank you!

**Comment by makseq** [comment]
@johnson7788 It would be great if you could contribute this feature to `https://github.com/heartexlabs/label-studio-converter` repository!

**Comment by johnson7788** [comment]
> @johnson7788 It would be great if you could contribute this feature to `https://github.com/heartexlabs/label-studio-converter` repository!

Yes, YOLO format is not hard when i write like label-studio-converter COCO code, i has completed a rough code, when i check it again, I will submit the PR. thanks!

**Comment by makseq** [comment]
@johnson7788 thank you very much! It would be great!
