### ISSUE TITLE
When will lane marking annotation be supported?

### ISSUE THREAD

**Issue by flinzhao** [heartexlabs/label-studio#6060]
Thank you for this excellent open-source project! When I used Label Studio for annotation, I found that there was no annotation format for lane lines. I also found similar needs in the issues, and my needs are the same as in #2563  ! I hope Label Studio can support the annotation format for lane lines as soon as possible. Thank you again.❤️

**Comment by jombooth** [comment]
Hi @flinzhao ! Closing this one as a duplicate but I'll raise the other issue with the team since it looks like this has gotten quite a bit of interest. Thank you for using Label Studio!
