### ISSUE TITLE
 Sync is not working with S3

### ISSUE THREAD

**Issue by Karmendes** [heartexlabs/label-studio#607]
I launch a instance from the label studio with multi-session so that some users could use it, with the data in S3. After about 3 person start to use, the label studio started to have synchronization problems to create the tasks, that is, when you press the scan button, it is unable to load any task.

**Comment by makseq** [comment]
@Karmendes Try to start LS with --log-level DEBUG and check your console, what will be there?

**Comment by Karmendes** [comment]
DEBUG is saying that the images are skipped by regex filter

**Comment by makseq** [comment]
@Karmendes Sorry, but are you sure your regex is ok on `Settings => Cloud storage sync`?

**Comment by niklub** [comment]
Hi, @Karmendes ! When you leave Regex filter empty, it filters out all files stored in your bucket, so you have to explicitly set filter regular expression (e.g. `.*` for getting all files in a bucket). 
We'll close this issue as soon as 1.0.1 will be released, please reopen it if you still get the error, possibly with the details provided.
