### ISSUE TITLE
Label Studio does not upload videos that are approximately 200 MB in size

### ISSUE THREAD

**Issue by praveenporsche** [heartexlabs/label-studio#6076]
**Describe the bug**
Cannot upload videos that are roughly 200 MB in size. The progress bar keeps spinning. No error in the console.
I'm using the Object Detection with boxes template.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac M1 Ventura
 - Label Studio Version latest

**Additional context**

**Comment by jombooth** [comment]
Hi @praveenporsche ! As my colleague @makseq mentions [here](https://github.com/HumanSignal/label-studio/issues/5904#issuecomment-2126060262), Label Studio isn't optimized for handling large files directly. I hope one of the solutions in that link can work for your usecase :)
