### ISSUE TITLE
Initialization in Anaconda not possible when following the instructions

### ISSUE THREAD

**Issue by ericflores** [heartexlabs/label-studio#608]
**Describe the bug**
Initialization in Anaconda not possible when following the instructions

**To Reproduce**
1. Open Anaconda Prompt in Windows 10 using Anaconda3 64 bits 
2. Execute the following steps as instructed in the Readme:
conda create --name label-studio python=3.8
conda activate label-studio
pip install label-studio
python label_studio/server.py start labeling_project --init

3. You will get this error:
python: can't open file 'label_studio/server.py': [Errno 2] No such file or directory
4. You will also notice that your current folder is empty and Label Studio was installed at:
C:\Users\username\Anaconda3\Anaconda3\envs\label-studio\Lib\site-packages\label_studio

**Expected behavior**
I'm expecting results consistent with the instructions, so that I can initialize the application.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Anaconda 3, 64 bits, Python 3.8.5
 - Label Studio Version0.9.1.post1

**Comment by makseq** [comment]
There seems you are using `python label_studio/server.py start labeling_project --init` for cases when you install LS from git repository instead of pip. You should replace it to:

``` 
label-studio start labeling_project --init
```

**Comment by ericflores** [comment]
I was able to initialize by moving to the Anaconda environment folder:
C:\Users\myusername\Anaconda3\envs\label-studio-env\Lib\site-packages\label_studio

and executing this:
python server.py start labeling_project --init

A pretty cumbersome solution, as I don't want to be running my project from the python library folder.

Your solution, however, worked much better. Thanks. You should document it as the way to initialize the project for Anaconda users.
