### ISSUE TITLE
Is it possible to show image from base64-encoded?

### ISSUE THREAD

**Issue by luckysusanto** [heartexlabs/label-studio#6086]
I have a pre-annotated JSON file, but the image is in the form of base64-encoded. 
How can I show the image in label studio?

[Bali_1.json](https://github.com/user-attachments/files/16186410/Bali_1.json)

**Comment by caitlinwheeless** [comment]
We resolved this in another forum:

- Yes it is supported, but may affect performance
- Should be formatted as (see https://labelstud.io/guide/predictions#JSON-format-for-pre-annotations)
`[
  {
    "data": {
      "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgAB...."`
- Can reference it in the labeling config as follows:
`<View>
  <Image name="image" value="$image"/>
</View>`

**Comment by caitlinwheeless** [comment]
Closing as the user got this working
