### ISSUE TITLE
Incompability with spacy

### ISSUE THREAD

**Issue by DominikZians** [heartexlabs/label-studio#609]
label-studio is incompatible with the spaCy NLP library (https://github.com/explosion/spaCy) because spaCy needs `wasabi>=0.8.1` and label-studio needs `wasabi==0.4.2`.

Is there a specific reason why label-studio does not work with wasabi 0.8.1?

**Comment by makseq** [comment]
@DominikZians Thank you for your report. No, I think it's not a strict requirement, we will fix it in future releases.

**Comment by makseq** [comment]
@DominikZians I've added it to release/0.9.1.post2, it would be great if you could check it!
