### ISSUE TITLE
can not upload more images

### ISSUE THREAD

**Issue by jo-dean** [heartexlabs/label-studio#6095]
i just upload adout 230 mb about 100 images。but it stuck.

**Comment by haraldbo** [comment]
I have experienced the same issue. Have not looked much into it, but found a quick workaround by uploading 60 images at a time. 
I set it up locally with pip and am running it from windows terminal:
```pip install label-studio```
```label-studio```
Then I navigate to ```localhost:8080``` in browser. I have a hunch that running it in this way has its limitations 😅

**Comment by jo-dean** [comment]
upload images accroding it's api maybe works.i didn't try it.

**Comment by jombooth** [comment]
It's hard for us to tell what's wrong here without more information about your setup, but splitting your uploads into batches as @haraldbo suggests seems pretty reasonable to me. If you'd like to reopen, please provide more details about your system, how you're running label studio, what error behavior exactly you're running in to, and so on.
