### ISSUE TITLE
Allow variables in label config to create dynamic image panels

### ISSUE THREAD

**Issue by bw4sz** [heartexlabs/label-studio#6106]
I would like the annotator to be able to see a series of images at once. We are labeling unique objects among several views of the same scene.

The number of images of each scene varies. Right now my options are to 

* Create a fixed number of image [views](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CImage%20name%3D%22image%22%20value%3D%22%24image%22%2F%3E%3Cbr%3E%20%20%3CChoices%20name%3D%22choice%22%20toName%3D%22image%22%20showInLine%3D%22true%22%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Boeing%22%20background%3D%22blue%22%2F%3E%3Cbr%3E%20%20%20%20%3CChoice%20value%3D%22Airbus%22%20background%3D%22green%22%20%2F%3E%3Cbr%3E%20%20%3C%2FChoices%3E%3Cbr%3E%20%20%3Cbr%3E%20%20%3CImage%20name%3D%22image2%22%20value%3D%22%24image2%22%2F%3E%3Cbr%3E%20%20%3CPolygonLabels%20name%3D%22label%22%20toName%3D%22image2%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20strokeWidth%3D%223%22%20pointSize%3D%22small%22%3Cbr%3E%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20opacity%3D%220.9%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Airplane%22%20background%3D%22red%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Car%22%20background%3D%22blue%22%2F%3E%3Cbr%3E%20%20%3C%2FPolygonLabels%3E%3Cbr%3E%3Cbr%3E%20%20%3CImage%20name%3D%22image3%22%20value%3D%22%24image3%22%2F%3E%3Cbr%3E%20%20%3CBrushLabels%20name%3D%22tag%22%20toName%3D%22image3%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Planet%22%20background%3D%22rgba(0%2C%200%2C%20255%2C%200.7)%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Moonwalker%22%20background%3D%22rgba(255%2C%200%2C%200%2C%200.7)%22%2F%3E%3Cbr%3E%20%20%3C%2FBrushLabels%3E%3Cbr%3E%3C%2FView%3E) and sample from them (https://github.com/HumanSignal/label-studio-frontend/issues/667)
* Create a stack of images and propagate labels among them. This is not appropriate in this case.

## Desired Psuedo code

```
for $image in images:
<View>
  <Image name="image" value="$image"/>
  <Choices name="choice" toName="image" showInLine="true">
    <Choice value="Boeing" background="blue"/>
    <Choice value="Airbus" background="green" />
  </Choices>
```

Is there any other workaround for upload a .json of images and creating a dynamic view?

**Comment by jombooth** [comment]
Does `valueList` work for your usecase, as described in this example? https://labelstud.io/tags/image#Example-1

**Comment by bw4sz** [comment]
thanks for your idea, I will update.

**Comment by bw4sz** [comment]
Related to https://github.com/HumanSignal/label-studio/issues/225 for others coming here.

**Comment by bw4sz** [comment]
I am posting the solution I came up with and closing. Its not perfect, but sufficient for our needs.

Since the label config xml for each project is fixed, it was simpler to generate a new 'project' for each image panel. So using the python API, if we have a 6 image panel we need to create, loop through and name each img [img1, img2, img3], then make the corresponding labels point to each image. 

https://github.com/weecology/DoubleCounting/blob/main/scripts/labelstudio.py

```
def create_label_config(predictions):
    """
    Creates a Label Studio XML configuration based on the provided predictions.

    Args:
        predictions (dict): A dictionary containing the preannotations for each image.

    Returns:
        str: The Label Studio XML configuration.
    """

    xml = '''<View>
        <Header value="Select unique birds in each image to create a full colony count" />'''

    for i, image_name in enumerate(predictions.keys()):
        xml += f'''
            <View style="display: flex;">
                <View style="width: {100/len(predictions)}%; margin-right: 1.99%">
                <Image name="img{i+1}" value="$img{i+1}"/>
                <RectangleLabels name="label{i+1}" toName="img{i+1}">
                    <Label value="Great Egret" background="#FFA39E"/>
                    <Label value="Great Blue Heron" background="#D4380D"/>
                    <Label value="Wood Stork" background="#FFC069"/>
                    <Label value="Snowy Egret" background="#AD8B00"/>
                    <Label value="Anhinga" background="#D3F261"/>
                    <Label value="Unidentified White" background="#389E0D"/>
                    <Label value="White Ibis" background="#5CDBD3"/>
                    <Label value="Nest" background="#FFA39E"/>
                    <Label value="Help me!" background="#D4380D"/>
                    <Label value="Eggs" background="#FFA39E"/>
                    <Label value="Roseate Spoonbill" background="#FFA39E"/>
                </RectangleLabels>
                </View>
            </View>'''

    xml += '''
    </View>'''

    return xml
```

create the project

https://github.com/weecology/DoubleCounting/blob/e2563c525d1a60ea8336180153fd126b03b34c13/scripts/labelstudio.py#L23

and then format our preannotations to match the naming structure for upload

```
def label_studio_bbox_format(local_image_dir, preannotations, from_name="label"):
    """
    Create a JSON string for a single image in the Label Studio API format.

    Args:
        local_image_dir (str): The local directory where the images are stored.
        preannotations (DataFrame): A DataFrame containing the preannotations for the image.
        to_name (str, optional): The name of the image. Defaults to "image".
        from_name (str, optional): The name of the label. Defaults to "label".

    Returns:
        dict: The JSON string in the Label Studio API format.
    """
    predictions = []
    image_path = preannotations.image_path.unique()[0]
    original_width, original_height = Image.open(os.path.join(local_image_dir, os.path.basename(image_path))).size

    #Unique images and their index
    unique_images = preannotations.image_path.unique()
    image_index_dict = {}
    for index, image in enumerate(unique_images):
        image_index_dict[image] = "img{}".format(index)

    for index, row in preannotations.iterrows():
        result = {
            "value": {
                "x": row['xmin'] / original_width * 100,
                "y": row['ymin'] / original_height * 100,
                "width": (row['xmax'] - row['xmin']) / original_width * 100,
                "height": (row['ymax'] - row['ymin']) / original_height * 100,
                "rotation": 0,
                "rectanglelabels": [row["label"]]
            },
            "score": row["score"],
            "to_name": image_index_dict[row["image_path"]],
            "type": "rectanglelabels",
            "from_name": image_index_dict[row["image_path"]].replace("img", "label"),
            "original_width": original_width,
            "original_height": original_height
        }
        predictions.append(result)
            
    return {"result": predictions}
```

Closing. Thanks for your response. I appreciate it.

**Comment by makseq** [comment]
As more suitable solution you could use Multi Image Segmentation (MIG) feature: 
```
<Image valueList="$images" name="image">
```

1. Run LS with this feature flag:
```
fflag_feat_front_lsdv_4583_multi_image_segmentation_short=1 label-studio
```
or add this env variable to your docker env vars. 

2. Use this labeling configuration and task sample: 
```
<View>
  <Image name="image" valueList="$images" />

  <RectangleLabels name="labels" toName="image">
    <Label value="Cat" />
    <Label value="Dog" />
  </RectangleLabels>
</View>

<!-- {
  "images": [
    "https://data.heartex.net/open-images/train_0/mini/00607c8121301d54.jpg", 
    "https://data.heartex.net/open-images/train_0/mini/00a21fb1ed2af5e6.jpg"
  ]
} -->
```
