### ISSUE TITLE
Jupyter Notebook external application through jupyter-server-proxy

### ISSUE THREAD

**Issue by muthurajr** [heartexlabs/label-studio#611]
I'm trying to run label-studio as an external process in notebook server using jupyter-server-proxy and facing proxy issues with the URL's. Has anyone able to achieve this scenario successfully?

Examples:
Expected URL: http://localhost:8888/labelstudio/data/upload/6482e2-download.png
Actual URL: http://localhost:8888/data/upload/6482e2-download.png

Expected URL: http://localhost:8888/labelstudio/welcome
Actual URL: http://localhost:8888/welcome

**Comment by makseq** [comment]
@muthurajr What LS version do you use?

**Comment by muthurajr** [comment]
v0.9.1.post1. Even facing same issue with v0.8.2 as well.

**Comment by muthurajr** [comment]
@makseq I have tried to utilize the blueprints as well using https://github.com/heartexlabs/label-studio/blob/master/blueprint_usage_example.py. Few links are not working like below.
1. http://localhost:5000/data/upload/ed7ec5-label-studio.gif
2. http://localhost:5000/import, http://localhost:5000/export in tasks screen.

Thanks!

**Comment by makseq** [comment]
@muthurajr Have you tried to use HOST environment var? 
Check this guide: https://labelstud.io/guide/FAQ.html#How-to-run-Label-Studio-with-external-domain-name

**Comment by muthurajr** [comment]
@makseq After setting the external domain name like "example.com/notebook/sandbox/test/labelstudio/", #1 is solved. But /import & /export which are derived in label-studio/master/label_studio/static/dm/js/main.js are not getting updated. I guess some fix might be needed in the reverse proxy.

**Comment by makseq** [comment]
Yes, we need to rebuild data manager to fix it.

**Comment by muthurajr** [comment]
Is there any way to parameterize it without rebuild?

**Comment by makseq** [comment]
@muthurajr Unfortunately, no, it's hardcoded in Data Manager..

**Comment by makseq** [comment]
@muthurajr We are releasing 1.0.2 version today, this problem must be fixed there. Or you can try master branch right now.
