### ISSUE TITLE
valueList argument in the Image tag does not work

### ISSUE THREAD

**Issue by ShirokovSe** [heartexlabs/label-studio#6116]
**Describe the bug**
When forming a Label Interface for a list of images, the value List argument is ignored. 
Image column data example:
['https://103school.ru/foto/telef112.png', 'https://catherineasquithgallery.com/uploads/posts/2021-03/1614587266_10-p-kartinka-telefon-na-belom-fone-10.jpg', ...]

**To Reproduce**
1. Go to Project Settings
2. Click on Labeling Interface
3. Click on Code
4. Use Image tag with valueList  argument, pass the values of the argument

**Expected behavior**
Images reflect by the list

**Environment (please complete the following information):**
 - Label Studio Version 1.12.1

**Comment by jombooth** [comment]
/jira create
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/10188835987)
> Jira issue [TRIAG-756](https://humansignal.atlassian.net/browse/TRIAG-756) is created

[TRIAG-756]: https://humansignal.atlassian.net/browse/TRIAG-756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bw4sz** [comment]
For anyone following along on my issue #6106, follow here as well.

**Comment by makseq** [comment]
Please check this instructions: 
https://github.com/HumanSignal/label-studio/issues/6106#issuecomment-2362507754

You have to enable this feature flag:
```
fflag_feat_front_lsdv_4583_multi_image_segmentation_short=1 label-studio
```

and then use this labeling configuration:

```
<View>
  <Image name="image" valueList="$images" />

  <RectangleLabels name="labels" toName="image">
    <Label value="Cat" />
    <Label value="Dog" />
  </RectangleLabels>
</View>

<!-- {
  "images": [
    "https://data.heartex.net/open-images/train_0/mini/00607c8121301d54.jpg", 
    "https://data.heartex.net/open-images/train_0/mini/00a21fb1ed2af5e6.jpg"
  ]
} -->
```
