### ISSUE TITLE
Failed to import a json file via URL

### ISSUE THREAD

**Issue by nickjyj** [heartexlabs/label-studio#6118]
**Describe the bug**
When I created a new project, import an online json file through a url. It generated an error: 
``` 
[13ddfb9f-45c5-4a9a-bee3-7e8a09abd88c] Validation error ('content-length')
```
Here is the link to the json file: https://github.com/lmitechnologies/LMI_AI_Solutions/blob/tmp-file/label.json

**To Reproduce**
1. Create a new project
2. Click on Data Import tab
3. Paste the url of an online json file
4. Get the error 

**Expected behavior**
It should import the json file sucessfully.

**Screenshots**
![Screenshot from 2024-07-22 14-40-33](https://github.com/user-attachments/assets/60499624-0ce3-4271-a3a7-37e738b400b0)

**Environment (please complete the following information):**
 - OS: Debian 12
 - Label Studio Version: 1.9.2

**Comment by jombooth** [comment]
Hi @nickjyj -

The file link isn't working anymore - if you host label.json somewhere else does it work? I'm wondering if the issue that's coming up is particular to the case where the file is hosted on Github.

**Comment by makseq** [comment]
Closing this issue as unanswered. Feel free to reopen.
