### ISSUE TITLE
Slow loading for tasks that show 2 images.

### ISSUE THREAD

**Issue by EzrielS** [heartexlabs/label-studio#612]
**Describe the bug**
When doing image classification with two images, the rendering of the task is really slow. 

**To Reproduce**
1. In Settings set the Labeling Config as :
<View>
    <Image name="image" value="$image"/>
    <Image name="image2" value="$image2"/>
    <Choices name="choice" toName="image" showInLine="true">
      <Choice value="Correct" background="blue"/>
      <Choice value="Incorrect" background="green" />
    </Choices>
  </View>

2. On tasks.json write something like
{
    "1": {"id": 1, "data": {"image": "/data/upload/4cd389-41SXOqOIJTL._AC_.jpg", "image2": "/data/upload/55d707-21TXGXthB0L.jpg"}}, 
    "2": {"id": 2, "data": {"image": "/data/upload/4cd389-41SXOqOIJTL._AC_.jpg", "image2": "/data/upload/55d707-21TXGXthB0L.jpg"}},
    ...
}
3. In LS go to tasks/Label - when submitting, there is a long time to load the next task.

**Expected behavior**
I think that loading two images should not take so long.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version: 0.9.1.post1

**Comment by makseq** [comment]
@EzrielS Could you provide some video with this problem?

**Comment by makseq** [comment]
Deprecated bug after LS 1.0 release.
