### ISSUE TITLE
start-multi-session  (--initial-project-description expected)

### ISSUE THREAD

**Issue by OmaymaS** [heartexlabs/label-studio#613]
**Issue**

Got the following error when:
- I tried to run a docker image built with the purpose of starting a multi session.
- I deployed the same to GCP.

```
label-studio start-multi-session: error: argument --initial-project-description: expected one argument
```

**To Reproduce**
- edit `tools/run.sh` to include:
```
label-studio start-multi-session ${PROJECT_NAME:-my_project} -b \
             --host ${HOST:-0.0.0.0} --port ${PORT:-8081} --protocol ${PROTOCOL:-http://} \
             --username ${USERNAME:-""} --password ${PASSWORD:-""} ${INIT_COMMAND:-"--init"}
```
- build a local docker image and run OR deploy to GCP.

**Expected behavior**
Multi project/session up and  running.

**Environment**
 - Local: macOS
 - cloud: GCP

**Additional context**
I previously tried the [running with pip](https://labelstud.io/guide/index.html?from_search=start-multi-session#Running-with-pip) option and things worked fine for the multi-session option.

**Comment by makseq** [comment]
@OmaymaS `start-multi-session` is not supporting all these options: 
```
${PROJECT_NAME:-my_project} -b \
             --host ${HOST:-0.0.0.0} --port ${PORT:-8081} --protocol ${PROTOCOL:-http://} \
             --username ${USERNAME:-""} --password ${PASSWORD:-""} ${INIT_COMMAND:-"--init"}
```

Just leave 
```
label-studio start-multi-session 
```

**Comment by OmaymaS** [comment]
Thanks!
But what if I'd like to use a username and password?

**Comment by OmaymaS** [comment]
I could see the answer in this [slack thread](https://label-studio.slack.com/archives/CQ8LYPPJS/p1613147864456600).
Issue is resolved.

Thanks

**Comment by makseq** [comment]
@OmaymaS Thank you very much for your attentiveness and response!
