### ISSUE TITLE
Request support for SAM2

### ISSUE THREAD

**Issue by justStarG** [heartexlabs/label-studio#6157]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support SAM2 model

**Describe alternatives you've considered**
No

**Additional context**
https://github.com/facebookresearch/segment-anything-2

**Comment by jombooth** [comment]
Hi @thesby, thank you for the FR! This is something we've been discussing internally as well :)

**Comment by lsell** [comment]
Hi @thesby we published an [ML backend integration for SAM 2](https://github.com/HumanSignal/label-studio/issues/6157) and initial documentation. We're continuing to add support for additional video use cases, as well as build out documentation and tutorials. 

Please provide feedback and share any knowledge or learnings if you try it out. I'll close this issue in the meantime.

**Comment by lsell** [comment]
Hi @thesby we published an [ML backend integration for SAM 2](https://github.com/HumanSignal/label-studio/issues/6157) and initial documentation. We're continuing to add support for additional video use cases, as well as build out documentation and tutorials. 

Please provide feedback and share any knowledge or learnings if you try it out. I'll close this issue in the meantime.
