### ISSUE TITLE
how to delete my label-studio account

### ISSUE THREAD

**Issue by aryehw** [heartexlabs/label-studio#6166]
How can I delete my label-studio account?

**Comment by makseq** [comment]
Account deletion is not allowed in Label Studio. In the enterprise edition (e.g. app.humansignal.com), you can deactivate an account using Role Based control for your organization.

**Comment by aryehw** [comment]
Thank you for your reply.
I think that there should be a way for people who do not want to keep their account to delete it.

**Comment by tuomastik** [comment]
You can do it via Label Studio API:

1. Get the user ID: https://api.labelstud.io/api-reference/api-reference/users/list
2. Delete the user: https://api.labelstud.io/api-reference/api-reference/users/delete

**Comment by aryehw** [comment]
Thank you for your reply.
I cannot figure out how to do this. When I try to get the user ID, I get a page that provides a one line curl script. If I click "Try it", I get a page that wants me to enter the api_key, which I do not know. 

I think the problem is that I do not have label-studio installed on my computer.

**Comment by tuomastik** [comment]
You need to run the curl commands in a terminal on the machine where your Label Studio Community Edition is running.

You can get your API key from your Label Studio profile and use it in the curl commands.
