### ISSUE TITLE
v1.13 doesn't refresh view after submitting annotations in Safari - hangs view with loading symbol

### ISSUE THREAD

**Issue by sxwebster** [heartexlabs/label-studio#6167]
**Describe the bug**
Who digitising in Safari, on clicking submit/update after adding labels in a segmentation project type the loading symbol is shown and the page doesn't update. Refreshing the page manually and navigating back to the same image reveals the labels were saved, but this is a large hassle. 

**To Reproduce**
I've upgraded from label studio 1.12 to 1.13 on a Windows 10 with Python 3.12 installation using ```pip install -U label-studio```. 
I then added new images to an existing library. 
I'm accessing label-studio in a web browser (Safari) from a Mac when labelling. 
When I finish labelling and click submit/update the view in the web browser shows the spinning loading symbol and does not refresh the page. 
This was not the experience when using 1.12. 

**Expected behavior**
On clicking submit/update after adding a label the page should update either back to the list or a confirmation. 

**Environment (please complete the following information):**
Label studio hosted on Windows 10 Pro on main release channel. 
Digitising on macOS via Safari - up to date on main release channel. 

Edit: Word in Chrome from the same machine (though Safari goes through far less battery than Chrome, so would prefer to use Safari)

**Comment by jombooth** [comment]
Hi @sxwebster - unfortunately we don't officially support Safari: https://labelstud.io/guide/install.html#Web-browser-support - we'd welcome a PR (or additional information) if you're able to pinpoint the cause, though!
