### ISSUE TITLE
Version 1.13.0 - Unsuccessful building local image using dockerfile

### ISSUE THREAD

**Issue by superjjp123** [heartexlabs/label-studio#6175]
Run the following command：

docker build -t heartexlabs/label-studio:latest .

Error message: The .git file cannot be found. The error is caused by line 29 in the dockerfile, that is:

RUN --mount=type=cache,target=${YARN_CACHE_FOLDER},sharing=locked \
    --mount=type=bind,source=.git,target=../.git \
    yarn run build && yarn version:libs

**Comment by superjjp123** [comment]
file hidden

**Comment by mdsarfraz2002** [comment]
@superjjp123 Can you help fix the above issue, I am getting the same error
