### ISSUE TITLE
Issue setting "add source storage" under cloud storage

### ISSUE THREAD

**Issue by sowmyarajesh** [heartexlabs/label-studio#6180]
I am trying to start a new project and add cloud storage to my S3 bucket. I am using the same configurations as in my other projects where everything is working fine. 
once I set the s3 configuration in the UI and click on "Check Connection" , it says "successfully connected!".
When I click on the "Add Storage" button, I am getting the following error:

**null value in column "status" violates not-null constraint
DETAIL: Failing row contains (59, batch_2, null, 2024-08-09 13:33:12.349783+00, <BUCKET_NAME>, <BUCKET_PREFIX>, , f, null, null, null, , , t, 15, 45, null, null, f, null, null, null, null, null, null).**

Can you please guide me to resolve this issue. googling says postgres error. I did not make any changes to the code. app is running as is.

**Comment by jombooth** [comment]
Hi @sowmyarajesh, which version of Label Studio is this happening on? Can you try upgrading to the latest version of the software and see if the issue is resolved?

**Comment by sowmyarajesh** [comment]
Hi jombooth,
Thanks for the response. I tried to upgrade to the latest label-studio version. I running the docker version of label-studio. I pulled the latest image only. 
The version I see is 1.7.4dev
I am still unable to connect to my AWS S3 in the new project. The existing projects where the connection is established works fine.

**Comment by sowmyarajesh** [comment]
for some reason my docker compose build was not pulling the latest image. I manually ran docker pull and then ran docker compose up. The label studio got updated and now the error is gone. 
Thanks.
