### ISSUE TITLE
Newer version of postgresql

### ISSUE THREAD

**Issue by mkhoshbin72** [heartexlabs/label-studio#6193]
Hi. In the docker-compose file you created, the Postgres version is specified as 11.5. Can we update the Postgres version to upper versions or there is a specific reason for choosing this version of Postgres?
Thank you so much for your attention and participation.

**Comment by jombooth** [comment]
We're working on this! We needed to find a way to enable folks with existing docker compose installations to be able to upgrade gracefully. Stay tuned, and you can follow along with our progress here: https://github.com/HumanSignal/label-studio/pull/5896/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L50

There's no concerns on the code side about going ahead and upgrading to a newer version if you'd like to do that in your setup.

**Comment by makseq** [comment]
Closing this issue as unanswered and potentially solved (the PR with postgresql upgrade is merged and updated to v13).
