### ISSUE TITLE
RAM overflow when opening a new task

### ISSUE THREAD

**Issue by alter-s1** [heartexlabs/label-studio#620]
When a new task is opened, the RAM becomes full. Having reached the 11GB limit, the studio crashes.
After clearing the cache, the RAM is freed.

1. Importing a task with audio files
2. Launching labeling
3. Go to the next task

Expected behavior:
The memory is released.

Screenshots:

![Screenshot_20210225_142500](https://user-images.githubusercontent.com/69759292/109154880-959f7100-7777-11eb-9303-98ea0b4666c8.png)
![Screenshot_20210225_142519](https://user-images.githubusercontent.com/69759292/109154893-9932f800-7777-11eb-8715-beab727270e8.png)
![Screenshot_20210225_142609](https://user-images.githubusercontent.com/69759292/109154902-9cc67f00-7777-11eb-9d37-4775604cf7be.png)
![Screenshot_20210225_142649](https://user-images.githubusercontent.com/69759292/109154911-9fc16f80-7777-11eb-9f8c-50cea08091c2.png)
![Screenshot_20210225_142708](https://user-images.githubusercontent.com/69759292/109154925-a2bc6000-7777-11eb-969c-c0a51459b32c.png)
![Screenshot_20210225_142721](https://user-images.githubusercontent.com/69759292/109154943-a9e36e00-7777-11eb-88a1-741bb8c1bba5.png)
![Screenshot_20210225_142737](https://user-images.githubusercontent.com/69759292/109154952-ac45c800-7777-11eb-85e6-b31720b83be9.png)
![Screenshot_20210225_142759](https://user-images.githubusercontent.com/69759292/109154960-afd94f00-7777-11eb-9ad4-fdfc7458a18a.png)
![Screenshot_20210225_142828](https://user-images.githubusercontent.com/69759292/109154968-b4056c80-7777-11eb-9aad-1d8de810a0b4.png)
![Screenshot_20210225_142853](https://user-images.githubusercontent.com/69759292/109154980-b7005d00-7777-11eb-9e61-33cd355075cd.png)
![Screenshot_20210225_142908](https://user-images.githubusercontent.com/69759292/109154991-b9fb4d80-7777-11eb-81ea-76e472d99e19.png)
![Screenshot_20210225_142929](https://user-images.githubusercontent.com/69759292/109154997-bc5da780-7777-11eb-874a-ca11ce07c7ba.png)
![Screenshot_20210225_142952](https://user-images.githubusercontent.com/69759292/109155007-bec00180-7777-11eb-92bb-ae590098b0ad.png)
![Screenshot_20210225_143011](https://user-images.githubusercontent.com/69759292/109155023-c2ec1f00-7777-11eb-830a-cbc8b9736dd7.png)
![Screenshot_20210225_143031](https://user-images.githubusercontent.com/69759292/109155033-c5e70f80-7777-11eb-9620-8d27397215e3.png)
![Screenshot_20210225_143054](https://user-images.githubusercontent.com/69759292/109155046-c97a9680-7777-11eb-8136-33671164cd33.png)
![Screenshot_20210225_143106](https://user-images.githubusercontent.com/69759292/109155062-cda6b400-7777-11eb-8469-0a42c2afd26f.png)
![Screenshot_20210225_143154](https://user-images.githubusercontent.com/69759292/109155070-d0a1a480-7777-11eb-9901-9f3c16dbd2f5.png)
![Screenshot_20210225_143234](https://user-images.githubusercontent.com/69759292/109155088-d39c9500-7777-11eb-9691-61b4197eb908.png)
![Screenshot_20210225_143247](https://user-images.githubusercontent.com/69759292/109155104-d7301c00-7777-11eb-96e1-394a67959364.png)

 - OS: Fedora 33 (Google Chrome Version 88.0.4324.182 (64-bit))
 - Server OS: Ubuntu Server 18.04 (docker container)
 - Label Studio Version 0.9.0

**Comment by makseq** [comment]
Thank you very much for your detailed report, we will investigate it.

**Comment by makseq** [comment]
This issue was related to https://stackoverflow.com/questions/48156306/html-5-video-tag-range-header. The audio hosting should answer with the correct Ranges in headers. The similar problem was in Local storage / Imported files using GUI in LS, but now it's fixed.
