### ISSUE TITLE
Import data shell display tasks disabled

### ISSUE THREAD

**Issue by MEugeniaC** [heartexlabs/label-studio#622]
label studio version 0.9.1
Installation via pip
Python 3.8.5. 
Testing NER, reading and writing labeled text.

The problem is when you create, initialize and import via command line (all in one line).
The application initializes, reads the file (the image identifies that it reads the tasks), but it is not shown in the panel. 
If you try to label (you access the labeling functionality) it shows the text and the options for labeling, but the label readings are not interpreted correctly. 
And if you go back to "task visualization" they are not displayed.

![issue_disabled_task](https://user-images.githubusercontent.com/38731385/109281156-3f383e00-781c-11eb-9a7b-21f716c7d321.png)

**Comment by makseq** [comment]
@MEugeniaC Could you show your start command for LS?

**Comment by MEugeniaC** [comment]
label-studio start project1 --init --input-path=data_multi.json --input-format=json --label-config=config_annot_labelstudio.xml

**Comment by makseq** [comment]
Try to reset tabs: go to Settings => Project settings => Reset all tabs button

**Comment by niklub** [comment]
Please checkout the latest Label Studio version and feel free to reopen the issue if the problem still persists
