### ISSUE TITLE
Smart Polygon and Brush don't exist despite mention in docs

### ISSUE THREAD

**Issue by jneeven** [heartexlabs/label-studio#6221]
**Describe the bug**
The docs of https://labelstud.io/tags/polygon describe the use of the `smart` and `smartOnly` tags, as with most other labels. The ML labeling guideline mentions the Polygon and Brush as well: https://labelstud.io/guide/ml.html#Smart-tools

However, I find that while Rectangle and Keypoint work as expected, Polygon and Brush do not work at all. I have not tested the Ellipse. For the smart brush no web request is sent to the backend, and for the smart polygon no button even appears. Why do these not work? Are the docs incorrect or am I doing something wrong?

**To Reproduce**
Set up a new project with the following config:
```xml
<View>
  <Header value="Select label and click the image to start"/>
  <Image name="image" value="$image" zoom="true"/>
  <PolygonLabels name="label" toName="image"
                 strokeWidth="3" pointSize="small"
                 opacity="0.9" smart="true">
    <Label value="Airplane" smart="true" background="red"/>
    <Label value="Car" smart="true" background="blue"/>
  </PolygonLabels>
</View>
```

or alternatively, since the docs only mention the `smart` tag on the `Polygon` and not `PolygonLabels`:
```xml
<View>
  <Header value="Select label and click the image to start"/>
  <Image name="image" value="$image" zoom="true"/>
  <Polygon name="label" toName="image"
                 strokeWidth="3" pointSize="small"
                 opacity="0.9" smart="true"/>
</View>
```

Then specify an ML backend, e.g. [SAM2-Image]( https://github.com/HumanSignal/label-studio-ml-backend/tree/master/label_studio_ml/examples/segment_anything_2_image), and enable interactive annotations

![image](https://github.com/user-attachments/assets/3fe224b1-0766-438f-bde0-ed130ef28607)

Then import a sample image and open the label interface.
![image](https://github.com/user-attachments/assets/c15f7a31-0d94-4567-9fc2-03673f5c3532)

You see that there is no icon for smart polygon despite auto-annotation being enabled. Looking at the logs of the ML backend, no request is received upon drawing a regular polygon either.

**Expected behavior**
I would expect the smart polygon to send a request to the ML backend on each update, so that I can process it with an ML model and return an appropriate prediction.

Smart keypoints and boxes are already useful, but I find myself labeling "thin" shapes where a bbox is too large and I would require *many* keypoints to accurately capture all parts of the object... Polygons are a lot more useful (then I can create keypoints from the polygon myself and feed those to e.g. SAM2)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Label Studio Version:
 ```json
 {
    "release": "1.13.0",
    "label-studio-os-package": {
        "version": "1.13.0",
        "short_version": "1.13",
        "latest_version_from_pypi": "1.13.0",
        "latest_version_upload_time": "2024-07-31T14:50:18",
        "current_version_is_outdated": false
    },
    "label-studio-os-backend": {
        "message": "ci: Build frontend",
        "commit": "0566d2f4b552d5606226bf977c29a2f0c5493e03",
        "date": "2024/07/31 13:42:07",
        "branch": "",
        "version": "0566d2f+dirty"
    },
    "label-studio-frontend": {
        "message": "ci: Build frontend",
        "commit": "0566d2f4b552d5606226bf977c29a2f0c5493e03",
        "date": "2024-07-31T13:42:07.000Z",
        "branch": "develop"
    },
    "dm2": {
        "message": "ci: Build frontend",
        "commit": "0566d2f4b552d5606226bf977c29a2f0c5493e03",
        "date": "2024-07-31T13:42:07.000Z",
        "branch": "develop"
    },
    "label-studio-converter": {
        "version": "1.0.2"
    },
    "label-studio-ml": {
        "version": "2.0.1dev0"
    }
```

Thanks!

**Comment by makseq** [comment]
I don't think LS SAM2 ML Backend supports PolygonLabels:

It generates BrushLabels masks:
https://github.com/HumanSignal/label-studio-ml-backend/blob/master/label_studio_ml/examples/segment_anything_2_image/model.py#L109

And it waits for KeypointLabels or RectangeLabels as "magic" auto-annotation helpers: 
https://github.com/HumanSignal/label-studio-ml-backend/blob/master/label_studio_ml/examples/segment_anything_2_image/model.py#L128

**Comment by sven-knoblauch** [comment]
I have the same problem with the smart polygon, where no icon is enabled and no request is send to the ml backend (using a custom ml-backend, which can use polygons). This feature will be discarded?

**Comment by jneeven** [comment]
@makseq that's a separate issue. The backend doesn't even receive any request, so regardless of whether the model supports it it won't work. SAM2 is just an example, in reality I'm running a custom model.

**Comment by nickjyj** [comment]
Any support plan for smart polygon and brush labels in LS ml-backend?
