### ISSUE TITLE
Allow filtering by gt/lt for numeric columns

### ISSUE THREAD

**Issue by erip** [heartexlabs/label-studio#623]
**Is your feature request related to a problem? Please describe.**

I have data of the following form:

```
a,b,c
hello,world,0.2
goodbye,friends,-0.5
```

I'm frustrated that I cannot apply filters in the UI based on relationships of column c as a float; e.g., `filter c gt 0`

**Describe the solution you'd like**

I'd like to expose a filter with simple greater than/less than some number for a given numeric column  in the UI.

**Describe alternatives you've considered**

An alternative would be to pre-filter the data before importing.

**Comment by erip** [comment]
A related feature would be to sort on these columns. 😄

**Comment by makseq** [comment]
🙂 actually we have implemented it already, but it has been disabled because of some bugs :) I hope we will enable this feature in our future release.

**Comment by makseq** [comment]
@erip Fixed in this PR: https://github.com/heartexlabs/label-studio/pull/938 
We are going to include this fix into release 1.0.2 very soon.

**Comment by makseq** [comment]
Done in 1.1.
