### ISSUE TITLE
How can a second annotator annotate using the queue?

### ISSUE THREAD

**Issue by mi-bauer** [heartexlabs/label-studio#6233]
In my setup I want all tasks to be annotated at least twice by different annotators. The problem is that when annotator 1 creates an annotation then that task also disappears from the queue of annotator 2. Annotator 2 then only has the option to filter out all tasks that he has already annotated himself. Then he needs to manually click on a task, click on the "+"-button to create another annotation. When he submits it he needs to manually click again on another task, click the "+"-button again... this is quite cumbersome. A good solution would be to be able to add tasks to the queue even if they are already annotated (by another user). But it seems that there is no feature like that in label studio. Marking the tasks with the checkbox and then clicking on "Label 359 Tasks" only leads to the empty queue. Is this a bug or as intended?

Are there any workarounds or ways to simplify the annotation process for annotator 2?

**Comment by makseq** [comment]
Hello, 

This feature is supported in Label Studio Enterprise. You can set how many annotation you need per task in the project settings. You can check Label Studio enterprise here: https://app.heartex.com/user/trial
