### ISSUE TITLE
Can't import task with ID via the API

### ISSUE THREAD

**Issue by sylvinus** [heartexlabs/label-studio#626]
Hello!

I would expect the API to accept IDs in the input data for tasks:
```
curl -X POST -H Content-Type:application/json http://localhost:8808/api/project/import --data "[{\"id\":42, \"data\":{\"name\": \"test 1\", \"description\": \"y\"}}]"
```

However, IDs are discarded. Return of that command looks like:
```
{"columns_to_draw":[],"duration":0.02617335319519043,"files_as_tasks_list":{"selected":true,"type":null},"found_formats":{},"id":1,"new_task_ids":[1],"project":"./media_category","selected_formats":null,"selected_objects":null,"show_files_as_tasks_list":null,"task_preview":[{"description":"y","name":"test 1"}],"total_completions":0,"total_predictions":0,"total_tasks":1}
```

It would be useful to keep IDs stable when posting the same tasks multiple times.

thanks!

**Comment by makseq** [comment]
@sylvinus Hello! It's better to use PATCH api/tasks/id for this purpose.

**Comment by sylvinus** [comment]
Ah right, I hadn't seen that one. Feel free to close this if you don't want to implement (I guess the benefit would be to allow bulk-posting)

**Comment by makseq** [comment]
@sylvinus we are working on new backend, so we definitely won't implement this.
