### ISSUE TITLE
UI Project List Bug

### ISSUE THREAD

**Issue by tienldbnk** [heartexlabs/label-studio#6264]
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/ee1d2ed1-882a-4d01-badf-8f9d4611cd9f">

**Comment by makseq** [comment]
1. What is your LS version?
2. How do you install LS? 
3. If you install it from sources, don't forget to run 'python manage.py collectstatic'.

**Comment by tienldbnk** [comment]
> 3\. python manage.py collectstatic

I clone from github and run pthon label_studio/manage.py runserver

**Comment by tienldbnk** [comment]
> 1. What is your LS version?
> 2. How do you install LS?
> 3. If you install it from sources, don't forget to run 'python manage.py collectstatic'.

Sorry , I folow wrong scss file , thank you , I close ticket
