### ISSUE TITLE
Simplest Machine Learning backend not working.

### ISSUE THREAD

**Issue by srv-gabriel** [heartexlabs/label-studio#628]
I'm following [this tutorial](https://labelstud.io/tutorials/dummy_model.html), line by line, and I'm getting an error when trying to train the model.

![label-studio-error](https://user-images.githubusercontent.com/56798441/109545385-31461f80-7a9f-11eb-8e7c-677fc57637f3.png)

**Comment by makseq** [comment]
@srv-gabriel Sorry for a long answer, we were deeply into release LS 1.0. I hope it's fixed in this new version, please try this.
