### ISSUE TITLE
Cant Able to Add Annotations

### ISSUE THREAD

**Issue by reveur-code** [heartexlabs/label-studio#6283]
![image](https://github.com/user-attachments/assets/a3dbff42-27c7-4c64-8f38-d3937bfe12bb)
I have created a template and saved. and added a then i try to click and annotate the above  error is coming.
`<View>
  <Image name="image" value="$image"/>
 
    <View style="display: grid; "  >
        <Header value="Date"/>
        <DateTime name="date" only="date"  min="2020" max="2030"/>
      </View>
</View>`
i have got to setup and saved everything again same message
I have latest version 13.1

**Comment by jombooth** [comment]
Hi @reveur-code, is the above paste your entire label configuration? I believe you need at least one control tag (see: https://labelstud.io/tags/) in your config in order to be able to submit.

**Comment by reveur-code** [comment]
Yes, that was the issue. Didnt understand  due to improper  message.  I was trying something  else. 
Thank you
