### ISSUE TITLE
How to label obb data sets

### ISSUE THREAD

**Issue by dearMOMO** [heartexlabs/label-studio#6286]
Semantic Segmentation with Polygons？

![image](https://github.com/user-attachments/assets/68a8832f-3778-4058-82e7-bd0bb206f073)

**Comment by jombooth** [comment]
I would think Object Detection with Bounding Boxes would be a more natural fit, but keep in mind these are just templates and you can customize the label config to meet your needs. Take a look at https://labelstud.io/templates/image_bbox also!
