### ISSUE TITLE
Trying to connect to postgresql but still seems to be sqlite

### ISSUE THREAD

**Issue by NOS-AE** [heartexlabs/label-studio#6298]
**Describe the bug**
following the doc, I start label-studio using
```sh
label-studio start my_project --init -db postgresql
```
But nothing new with my postgresql. Instead a file named postgresql in the directory where I run the command appears.

**To Reproduce**
1. quick start
2. set up database

**Expected behavior**
I can find related table or data in my postgresql database.

**Environment (please complete the following information):**
 - OS: `macos/m1`
 - Label Studio Version: `1.13.1`

**Additional context**
environment variables:
```
DJANGO_DB=default
POSTGRE_HOST=127.0.0.1
POSTGRE_NAME=postgres
POSTGRE_PASSWORD=''
POSTGRE_PORT=5432
POSTGRE_USER=nosae
```

running without the db option, I find the label_studio.sqlite3 under ~/Library/Application Support/label-studio which has the same initial size as the postgresql file. And as the prompt of label-studio --help:

```
options:
  -db DATABASE, --database DATABASE
                        Database file path for storing tasks and annotations
```
so I assume that the option `db` is just to tell where the sqlite file store, rather than specify the database type. 

What's the correct way of specifying the database type, or am I missing something?

**Comment by jombooth** [comment]
Hi @NOS-AE,

Did you `export` the environment variables when you set them? They need to be exported for the label-studio process to read them. Alternatively you can start label studio like this:

```DJANGO_DB=default POSTGRE_HOST=127.0.0.1 POSTGRE_NAME=postgres POSTGRE_PASSWORD= POSTGRE_PORT=5432 POSTGRE_USER=nosae label-studio start my_project --init -db postgresql```

**Comment by jombooth** [comment]
linking relevant documentation for others who find this thread: https://labelstud.io/guide/storedata#PostgreSQL-database

**Comment by NOS-AE** [comment]
> Hi @NOS-AE,
> 
> Did you `export` the environment variables when you set them? They need to be exported for the label-studio process to read them. Alternatively you can start label studio like this:你设置环境变量的时候`export`吗？需要导出它们以供 label-studio 进程读取。或者，您可以像这样启动 label studio：
> 
> `DJANGO_DB=default POSTGRE_HOST=127.0.0.1 POSTGRE_NAME=postgres POSTGRE_PASSWORD= POSTGRE_PORT=5432 POSTGRE_USER=nosae label-studio start my_project --init -db postgresql`

Yes, I forgot to use `export` keyword, hence label-studio was not able to read those variables I set, thanks!
