### ISSUE TITLE
Why is the result wrong in bbox object detection task？

### ISSUE THREAD

**Issue by feipxyz** [heartexlabs/label-studio#630]
setting:
bbox object detection

src image:
![image](https://user-images.githubusercontent.com/26288410/109613418-155c7f80-7b6c-11eb-870f-2f372acd132a.png)

result:
![image](https://user-images.githubusercontent.com/26288410/109613263-e0502d00-7b6b-11eb-837e-efad951c0a80.png)
![image](https://user-images.githubusercontent.com/26288410/109613306-ef36df80-7b6b-11eb-9d85-0bd8f8e72074.png)
![image](https://user-images.githubusercontent.com/26288410/109613333-f65ded80-7b6b-11eb-9e4a-a236100837a1.png)

**Comment by makseq** [comment]
@feipxyz what is wrong with these coordinates?

**Comment by makseq** [comment]
@feipxyz did it solve your problem?

**Comment by makseq** [comment]
Feel free to reopen if you problem is not solved.
