### ISSUE TITLE
YOLOv8 OBB Export takes infinitely

### ISSUE THREAD

**Issue by prichinatryaski** [heartexlabs/label-studio#6300]
**Describe the bug**
Exporting the dataset of 1.5-3 thousand images takes infinitely from UI. Exporting from console at the same time produces labels only, no images.

**To Reproduce**
1. Go to 'Export'
2. Click on 'YOLOv8 OBB'

**Expected behavior**
Fast or at least finite export

**Screenshots**
![image](https://github.com/user-attachments/assets/c15da56c-3b4d-4ea1-8fb4-c17284ac934b)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Label Studio 1.13.1

**Additional context**
Other export options work as intended but are not applicable due to amount of images. Basic YOLO export is not available. It happened before with basic YOLO export, however, that time it was the lack of free space on device. This time the disk is almost free of files.

**Comment by jombooth** [comment]
hi @prichinatryaski - would you be able to leverage snapshots using the SDK or API to solve this issue? See https://labelstud.io/guide/export.html#Export-timeout-in-Community-Edition

**Comment by prichinatryaski** [comment]
> hi @prichinatryaski - would you be able to leverage snapshots using the SDK or API to solve this issue? See https://labelstud.io/guide/export.html#Export-timeout-in-Community-Edition

I was succesfully able to back up images using self-written script and console export, and the next day after pc reboot (not server, though) the export ended up being successful. However, it seems weird to me, that timeout occures with no exception messages and with no trace
