### ISSUE TITLE
Customise and display file path in the labelling interface

### ISSUE THREAD

**Issue by saskra** [heartexlabs/label-studio#6301]
I have created a LabelStudio project in which I have inserted images from the cloud that were originally sorted into subfolders according to their class, but which can only be displayed within the project in the form of the storage filename, something like this: ‘maindir/class016/filename.jpeg’. Is it possible to not only display this file path in the code for the labelling interface, but also to split it at the separators so that I only keep the class name and display it for approval or rejection? So roughly as below, but not with the complete file path, but only the relevant substring?

```
<View>
  <!-- Display of the image -->
  <Image name="image" value="$image"/>

  <!-- Display the image path/class name -->
  <Header value="Image path: $image" />

  <!-- Accept or reject the diagnosis -->
  <Choices name="diagnose_confirmation" toName="image">
    <Choice value="Diagnosis based on the image path is correct" />
    <Choice value="Diagnosis based on the image path is not correct" />
  </choice>
</View>
```

**Comment by jombooth** [comment]
Hi @saskra - afaik, we don't have a mechanism for doing this directly in the community version of Label Studio. You could however modify your task data to include another field containing the filename prepared as you need it?
