### ISSUE TITLE
Is It Possible to Create a Custom Tag in Label Studio by Modifying the Codebase?

### ISSUE THREAD

**Issue by madhuri1818** [heartexlabs/label-studio#6320]
I have cloned the Label Studio repository into my local development environment using VSCode. Now, I would like to create a custom tag that can be used within Label Studio, specifically as XML code.
Could you please outline the steps required to achieve this? I need guidance on how to modify the codebase to add a new custom tag and ensure it can be utilized effectively within the Label Studio platform.

**Comment by jombooth** [comment]
Hi @madhuri1818 - it's certainly possible, but not really something we offer a step by step guide for. I can however point you to this recent PR that adds a tag to LS: https://github.com/HumanSignal/label-studio/pull/6191
