### ISSUE TITLE
I am using version 1.9.0 and recently found that tasks uploaded after creating a project cannot be seen

### ISSUE THREAD

**Issue by new-bajie** [heartexlabs/label-studio#6324]
I am using version 1.9.0 and recently found that the tasks uploaded after creating a project cannot be seen. However, you can click on the Label ALL Tables annotation and the Actions button will be grayed out, which has not happened before. This is how I use Docker and local deployment

**Comment by jombooth** [comment]
please see https://github.com/HumanSignal/label-studio/issues/6256
