### ISSUE TITLE
Add Microsoft ADLS2

### ISSUE THREAD

**Issue by twsl** [heartexlabs/label-studio#633]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add Microsoft ADLS2 as a storage provider, which combines ADLS Gen1 and Azure Blob Storage.
Apparently requires [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake/) instead of [azure-storage-blob](https://pypi.org/project/azure-storage-blob/).

**Describe alternatives you've considered**
I haven't tested the current implementation as I need this for an upcoming project.

**Additional context**

**Comment by makseq** [comment]
@twsl Thank you for an interesting proposal! We will check it too.
