### ISSUE TITLE
How to perform batch prediction?

### ISSUE THREAD

**Issue by Schumpeterx** [heartexlabs/label-studio#6330]
I have a lots of imges need to be annotated. So i write a ML backend to do the prediction.
It takes a lot of time to perform predictions, so I hope to enable predictions in batches. 
When I click retrieve on the page, it says it will time out. As shown in the figures below.
<img width="323" alt="image" src="https://github.com/user-attachments/assets/b6d47c11-6570-4655-9624-493a1a20943b">
<img width="366" alt="image" src="https://github.com/user-attachments/assets/5cf090ea-2e1d-46dd-9f18-784edfdff149">
According to [this](https://github.com/HumanSignal/label-studio/issues/1443#issuecomment-946283167), I use the API to start the prediction.
Here is my code to call the api:

```
def start_prediction(url, token, project):
    url = f"{url}/api/dm/actions?id=retrieve_tasks_predictions&project={project}"
    headers = {
        "Authorization": f"Token {token}",
        "Content-Type": "application/json",
    }

    data = {"selectedItems": {"all": True, "excluded": []}, "project": project}
    start_time = time.time()
    print("start prediction.........")
    response = requests.post(url, headers=headers, json=data)
    end_time = time.time()
    execution_time = end_time - start_time
    print(f"Execution Time: {execution_time:.4f} seconds")

    if response.status_code == 200:
        print("Success:", response.json())
    else:
        print(f"Error {response.status_code}: {response.text}")
```
About 100 seconds after sending the http request, a response was received, indicating that the prediction was completed.
<img width="621" alt="image" src="https://github.com/user-attachments/assets/ae818748-54d3-4724-929f-31fd05fe2c7d">

But the ML backend is still making predictions. It shows that the prediction of 12 data has been completed.
<img width="1282" alt="image" src="https://github.com/user-attachments/assets/91701c79-485f-4e34-80e8-bdf48afdba90">

But the prediction results that have already ended cannot be seen on the front-end interface.
<img width="1900" alt="image" src="https://github.com/user-attachments/assets/37926880-52b7-4c5b-9966-1a68aed846d8">
After the prediction is completed on the backend, the prediction of the task cannot be obtained on the frontend.
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/e580f697-ac5a-4729-819b-46902bb7b8e7">
<img width="1907" alt="image" src="https://github.com/user-attachments/assets/04e0a9e8-1aae-4a88-9eae-5810dbc11bf0">

**Question**：If I open the tasks one by one, I can get the predictions correctly, but I need to wait for the ML backend to complete the predictions, this will waste a lot of time.  So how should batch prediction be initiated?

**Comment by Schumpeterx** [comment]
I found a method to complete the tasks prediction through iteration. Here is my code:
```
def list_tasks(url, token, project):
    page = 0
    page_size = 100
    headers = {
        "Authorization": f"Token {token}",
        "Content-Type": "application/json",
    }
    pred_num = 0
    while True:
        start_time = time.time()
        print("start prediction.........")
        page += 1
        list_url = (
            f"{url}/api/tasks?project={project}&page={page}&page_size={page_size}"
        )
        response = requests.get(list_url, headers=headers)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Execution Time: {execution_time:.4f} seconds")
        if response.status_code != 200:
            print(f"Error {response.status_code}: {response.text}")
            return
        resp_json = response.json()
        total = resp_json["total"]
        tasks = resp_json["tasks"]
        for task in tqdm(
            tasks,
            desc=f"Processing tasks of {pred_num}~{pred_num+len(tasks)} in {total}",
        ):
            pred_url = (
                f"{url}/api/dm/actions?id=retrieve_tasks_predictions&project={project}"
            )
            data = {
                "selectedItems": {
                    "all": False,
                    "included": [task["id"]],
                },
                "project": project,
            }
            response = requests.post(pred_url, headers=headers, json=data)
            get_json = response.json()
            print(get_json)
        pred_num += len(tasks)
```

**Comment by jombooth** [comment]
Hi @Schumpeterx - thanks for posting your solution!
