### ISSUE TITLE
Hints do not work for Choice tags

### ISSUE THREAD

**Issue by floschne** [heartexlabs/label-studio#6347]
**Describe the bug**
The tooltip containing the `hint` string does not show up when hovering over the respective choice. When using `Labels` and `Label` tags, it works as expected. 

Does anybody know how to resolve the issue?

**To Reproduce**
MWE labbeling config:
```html
<View>
  <Choices name="gender" toName="txt-1" choice="single">
    <!-- Here the hint property is ignored -->
    <Choice value="Man" hint="This is a hint" />
    <Choice value="Woman" hint="This is another hint" />
  </Choices>
  <Text name="txt-1" value="John went to see Mary" />
</View>
```
Playground example: https://labelstud.io/playground?config=%3CView%3E%0A%20%20%3CChoices%20name%3D%22gender%22%20toName%3D%22txt-1%22%20choice%3D%22single%22%3E%0A%20%20%20%20%3CChoice%20value%3D%22Man%22%20%2F%3E%0A%20%20%20%20%3CChoice%20value%3D%22Woman%22%20%2F%3E%0A%20%20%20%20%3CChoice%20value%3D%22Nonbinary%22%20%2F%3E%0A%20%20%20%20%3CChoice%20value%3D%22Other%22%20%2F%3E%0A%20%20%3C%2FChoices%3E%0A%20%20%3CText%20name%3D%22txt-1%22%20value%3D%22John%20went%20to%20see%20Mary%22%20%2F%3E%0A%3C%2FView%3E

**Expected behavior**
Hover over the choices and get a tooltip containing the hint string

**Environment (please complete the following information):**
 - Browsers tested: Firefox, Chrome
 - Label Studio Version: 1.13.0

**Comment by jombooth** [comment]
Hi @floschne - I tested your exact labeling config using LS 1.13.0 + Chrome and it worked fine for me:
[Screencast from 09-12-2024 02:19:24 PM.webm](https://github.com/user-attachments/assets/f1ca32b9-3d92-470d-be50-4b32c22315b3)
