### ISSUE TITLE
Authorization not included in the response header

### ISSUE THREAD

**Issue by hsethi2709** [heartexlabs/label-studio#635]
The API's built for Label Studio can be authorized with username and password. When I tried to integrate the same API's with my monitoring interface, the response header didn't include 'Authorization' in the response so the request was being blocked by the CORS policy. 

Steps to reproduce the behaviour:
1. Enable Authorization on Label Studio
2. Integrate API with another web app. API will work with Postman but not with other applications. 
3. The request will then fail if you try to access it

The response header should include 'Authorization' for cases where authorisation is enabled and API integration is required. 

I fixed the issue on my label studio set up by changing the response headers in the label-studio folder. I can do the same and create a pull request if you think it should be included.

**Comment by mary902** [comment]
> The API's built for Label Studio can be authorized with username and password. When I tried to integrate the same API's with my monitoring interface, the response header didn't include 'Authorization' in the response so the request was being blocked by the CORS policy. 
> 
> Steps to reproduce the behaviour:
> 1. Enable Authorization on Label Studio
> 2. Integrate API with another web app. API will work with Postman but not with other applications. 
> 3. The request will then fail if you try to access it
> 
> The response header should include 'Authorization' for cases where authorisation is enabled and API integration is required. 
> 
> I fixed the issue on my label studio set up by changing the response headers in the label-studio folder. I can do the same and create a pull request if you think it should be included.
