### ISSUE TITLE
How to upgrade label studio (docker)?

### ISSUE THREAD

**Issue by shinytreecko** [heartexlabs/label-studio#6360]
**I know the bug I'm describing can be fixed by updating to 1.13.1. This bug report is because I don't want to lose any data when I update, and to provide a thread for users in my situation to see and fix their installation's issues.**
**Describe the bug**
I'm experiencing the bug where tasks and images don't show up under a project. I've attached a screenshot below.

**To Reproduce**
1. Be on version 1.12.1 and use Chrome
2. Click on a project
3. See that there are no tasks

**Expected behavior**
Task list should appear and buttons should not be clustered.

**Screenshots**
<img width="1920" alt="Screenshot 2024-09-10 at 1 30 49 PM" src="https://github.com/user-attachments/assets/047f8374-95ed-4a02-a325-ac15cad651ef">

**Environment (please complete the following information):**
 - OS: Mac and Windows
 - Label Studio Version [1.12.1]

**Additional context**
My docker container has a couple source directories linked to the container. They are exactly as follows: `C:\Users \my user/mydata` links to `/label-studio/data` and `C:\Users\my user/local storage` links to `/label-studio/files`. These directories contain all of my label studio installation data as well as photos that are used in my projects. I don't want to lose/overwrite these directories and would like to preserve them when I upgrade to 1.13.1. 

Does anyone know what I need to do to upgrade to version 1.13.1 using docker to fix this bug?

**Comment by jombooth** [comment]
Hi @shinytreecko,

It should be sufficient to take your clone of the LS git repo from which you ran `docker compose up`, run a `git pull` to get the latest state in that repository, run a `git checkout` of the 1.13.1 commit (https://github.com/HumanSignal/label-studio/commit/d9b816a3781ee806bba50c8c5589fcdb8555a277), then `docker compose up --build` again. Your volumes should be persisted, but to be extra careful, I would recommend first copying those files to another location on your hard drive.

**Comment by shinytreecko** [comment]
Thank you @jombooth,

That sounds like it would do the trick, but I remember having to change some environment variables to allow Label Studio to use my local storage. I forgot to ask in my previous issue, but do you know if I would need to include anything in my `docker compose up --build` command?
