### ISSUE TITLE
In Label Studio Enterprise version I couldn't find Enable Scripts option 

### ISSUE THREAD

**Issue by madhuri1818** [heartexlabs/label-studio#6364]
I took Label Studio enterprise version for adding custom scripts but even after granting accesss from owner I couldn't see Custom Scripts option.It is said that Custom scripts are defined in the project settings under the Labeling Interface section
But I couldn't see any option Please help me with this

**Comment by RaphaelGut** [comment]
How did you solve it, i have the same problem

**Comment by madhuri1818** [comment]
Hi , I encountered a similar issue with Label Studio, and I was able to resolve it by contacting the Label Studio support team directly at [support@labelstudio.zendesk.com] or raise an issue in label studio support tab
