### ISSUE TITLE
[mobx-state-tree] error in Label window

### ISSUE THREAD

**Issue by OmaymaS** [heartexlabs/label-studio#637]
**Describe the bug**
This message appears when we go to the Label window and refreshing doesn't fix it.
`[mobx-state-tree] Instance identifier 'id' for type 'TaskModel' must be a string or a number` in the **Label** mode.

**To Reproduce**

I couldn't track a consistent behavior or certain steps leading to the issue. But here are the main setup:
- Project deployed to GCP (cloud run).
- Tasks sync from GCS *(individual json files, i file per task)*, in the form of `{"id": "100", "image":"https://...."}`.
- Completions sync to GCS.

**Expected behavior**
No errors or messages.

**Screenshots**
![bug1](https://user-images.githubusercontent.com/13340411/110121931-4a144500-7dbf-11eb-8f90-4600d24c9ec3.png)

![bug2](https://user-images.githubusercontent.com/13340411/110121939-4bde0880-7dbf-11eb-8d49-b38fdf47a0e6.png)

**Environment :**
 - Deployed on GCP
 - Accessed on Chrome

**Comment by makseq** [comment]
@OmaymaS Thank you for your report. How often does it happen?

**Comment by OmaymaS** [comment]
It happened with 3 testers so far including me. My browser was on Chrome. I can confirm with others but most probably Chrome as well.

**Comment by DominikMa** [comment]
I get the same error with a local setup and the tasks from the standard task.json file. For me it happens every time if all tasks are completed and Submit is clicked. Firefox then shows that there is no task left for labeling while chrome throws the presented error.

**Comment by OmaymaS** [comment]
I believe they happened even when some tasks weren't completed as well.
But given that it doesn't break things in Firefox, is there sth to disable/enable in Chrome to avoid the error?

**Comment by Rishabh-hyperverge** [comment]
I also have the same error.

**Comment by hlomzik** [comment]
Hi all! Very strange bug.
Is this something unusual with such tasks? Missing `id` maybe? Just checking.

**Comment by niklub** [comment]
Hi, @OmaymaS ! Just checked this on [the latest master version](https://github.com/heartexlabs/label-studio/commit/912f8de24a43da24deed2c1826fbfd1f34286be3), looks like syncing with GCS works fine. We will close this issue once releasing `label-studio==1.0.2`, please feel free to reopen if the problem still exists on your side
