### ISSUE TITLE
Time Series CSV| Can't Import in the App

### ISSUE THREAD

**Issue by vcmorini** [heartexlabs/label-studio#638]
**Description:**
Importing CSV with no header and no timestamp. Signals are column-wise, each signal contains 100 rows with values between 0 and 1.

I want to see each column (one signal) at a time, and label them, one by one, as good or bad.

**Problem:**
However I keep getting the error:

> Your config and imported data are inconsistent
> 
> Error   at item 0: "csv" key is expected in task data [assume: item["data"] = task root with values] 
> {'data': {'0.8': 0.8, '0.7': 0.7}} Error at item 1: "csv" key is expected in task data [assume: item["data"] = task root with values]
> 
> 

My config file, as described in the docs:
```
<View>
    <Header value="Time Series from headless CSV"
            style="font-weight: normal"/>

    <!-- Control tag for region labels -->
    <TimeSeriesLabels name="label" toName="ts">
        <Label value="Good" background="#5b5"/>
        <Label value="Bad" background="#55f"/>
    </TimeSeriesLabels>

    <!-- Object tag for time series data source -->
    <TimeSeries name="ts" valueType="url"
                value="$csv"
                sep=",">
        <Channel column="1"
                 strokeColor="#1f77b4"/>
    </TimeSeries>
</View>
```

App: https://app.labelstud.io

**Comment by makseq** [comment]
@vcmorini Didn't you forget to enable a checkbox on import page: "Imported files are Time-Series or Text" ? (in LS 0.9.1).

**Comment by niklub** [comment]
Hi, @vcmorini ! Label Studio 1.0.0 doesn't support importing time series data without a header. In your particular case you have to specify column name `1` in csv file. Meanwhile we're planning to add a headerless file upload support for time series, thanks for pointing out

**Comment by makseq** [comment]
You should use this labeling config to enable headless CSVs: 

```
<View>
    <Header value="Time Series from headless CSV"
            style="font-weight: normal"/>

    <!-- Control tag for region labels -->
    <TimeSeriesLabels name="label" toName="ts">
        <Label value="Run" background="#5b5"/>
        <Label value="Walk" background="#55f"/>
    </TimeSeriesLabels>

    <!-- Object tag for time series data source -->
    <TimeSeries name="ts" valueType="url"
                timeColumn="0" value="$csv"
                sep="," overviewChannels="1,2">
        <Channel column="1"
                 strokeColor="#1f77b4"/>
        <Channel column="2"
                 strokeColor="#ff7f0e"/>
    </TimeSeries>
</View>
```
