### ISSUE TITLE
How to develop the frontend?

### ISSUE THREAD

**Issue by orangecoloured** [heartexlabs/label-studio#6391]
I followed the readme. Did [this](https://github.com/HumanSignal/label-studio/tree/develop?tab=readme-ov-file#install-for-local-development), then went to the `/web` folder, did `yarn install` and `yarn watch`, `yarn serve` and then went to `http://localhost:3000`.

But it appears to be broken
<img width="1728" alt="Screenshot 2024-09-16 at 1 03 13 PM" src="https://github.com/user-attachments/assets/705cea63-c21e-4564-be8e-f854329ca4c4">

Also not sure how it should work with the backend, which I launch via `python label_studio/manage.py runserver` in the root folder.

Tried to follow [this](https://github.com/HumanSignal/label-studio/blob/develop/web/README.md#installation-instructions) guide. Did `yarn dev` in the `/web` folder, but got this on `http://localhost:8010`:
```
Error: Must provide a proper URL as target
    at ProxyServer.<anonymous> (/Users/rckt-mac-m3/Dev/label-studio/web/node_modules/http-proxy/lib/http-proxy/index.js:69:35)
    at HttpProxyMiddleware.middleware (/Users/rckt-mac-m3/Dev/label-studio/web/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:22:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**UPDATE**: Basically running `yarn watch` or `yarn build` with `poetry run python label_studio/manage.py runserver` gets the thing done with some caveats.

**Comment by Bradly-s** [comment]
how to solve it?

**Comment by orangecoloured** [comment]
@Bradly-s No idea, I ended up rebuilding the whole thing on every change. It was a PITA, but I got the work done.
