### ISSUE TITLE
Images not showing in main panel after import - Docker setup Label Studio 1.13.0

### ISSUE THREAD

**Issue by senaagacc** [heartexlabs/label-studio#6394]
I'm using Label Studio version 1.13.0 with a Docker setup. After importing images, I can label them when I click on "Label All Tasks", but they do not appear in the main panel in the tasks view.

Steps I followed:

1. The images do not show up in the task list on the main screen.
2. When I click "Label All Tasks", I can see the images and label them.
3. I am able to export the labeled images successfully, but they are still not visible on the main screen.

My setup:
- Label Studio version: 1.13.0
- Running in Docker environment

I’ve tried clearing browser cache and re-importing data, but the issue persists. Any suggestions on how to fix this?

![mainpanel](https://github.com/user-attachments/assets/cb1e146c-284e-4650-902d-4c27415da28b)

**Comment by jombooth** [comment]
Hi @senaagacc - please upgrade to 1.13.1: https://github.com/HumanSignal/label-studio/issues/6256
