### ISSUE TITLE
Label studio Data manager columns is not showing in my every project

### ISSUE THREAD

**Issue by ashuyadav2030** [heartexlabs/label-studio#6414]
![WhatsApp Image 2024-09-20 at 1 10 39 PM](https://github.com/user-attachments/assets/9123887b-082d-4c6b-a44f-be9b2e412ed9)

**Comment by austingg** [comment]
@ashuyadav2030 how do u fix the problem, I also met it.

**Comment by austingg** [comment]
Currently, I use Safari instead.

**Comment by ashuyadav2030** [comment]
> Currently, I use Safari instead.

By just updating the version of Label studio

pip install --upgrade label-studio
