### ISSUE TITLE
Small but critical bug for configuration on 0.9.1-post1 release.

### ISSUE THREAD

**Issue by seoulite** [heartexlabs/label-studio#642]
**Describe the bug**
After install recent release and initialize the project folder, when you contact setting menu to customize labeling environment, the bug has occured. 

**To Reproduce**
1. pip install label-studio (recent)
2. label-studio start my_project -- init
3. browser opened
4. access into setting page on browser

**Expected behavior**
Configuration page works well and initial configuration procedure can be completed.

**Screenshots**

<img width="485" alt="image" src="https://user-images.githubusercontent.com/4136230/110593602-2128f100-81bf-11eb-9c7d-7e518dd9748c.png">

**Environment (please complete the following information):**
 - OS: Linux 4.15.0-130-generic #134-Ubuntu SMP x86_64 GNU/Linux
 - Label Studio Version : 0.9.1-post1

**Comment by makseq** [comment]
@seoulite Thank you very much for your PR, I've merged it into 0.9.2.post2!
