### ISSUE TITLE
Helm install fails with "failed to download heartex/label-studio"

### ISSUE THREAD

**Issue by rivaratyr** [heartexlabs/label-studio#6452]
**Describe the bug**
Hey guys!
Just found this amazing tool, and trying to install to Kubernetes in Google Cloud. I know this is half-of-a Kubernetes question, but maybe you know more.

For the command: `helm install label-studio-test-1 heartex/label-studio --version 1.13.1` I get the response:
Error: INSTALLATION FAILED: failed to download "heartex/label-studio" at version "1.13.1"

Anyone met with this issue before? I did all the prerequisites, and the `helm search repo heartex/label-studio` shows:
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
heartex/label-studio            1.6.3           1.13.1          Label Studio is a data labeling tool
heartex/label-studio-enterprise 0.0.50          2.3.1-2         DEPRECATED: please use heartex/label-studio ins...

**To Reproduce**
1. Complete https://labelstud.io/guide/install_k8s up to point 8
2. Try to complete point 8

**Expected behavior**
Helm install should succeed.

**Environment (please complete the following information):**
 - OS: OSX, Google Cloud.
 - Label Studio Version 1.13.1

**Additional context**
Also, heartex/label-studio can not be found in https://artifacthub.io/ at all.

**Comment by farioas** [comment]
```
$ helm search repo heartex/label-studio --versions
NAME                           	CHART VERSION	APP VERSION 	DESCRIPTION
heartex/label-studio           	1.6.3        	1.13.1      	Label Studio is a data labeling tool
heartex/label-studio           	1.6.2        	1.13.1      	Label Studio is a data labeling tool
heartex/label-studio           	1.6.1        	1.13.0      	Label Studio is a data labeling tool
heartex/label-studio           	1.6.0        	1.12.1      	Label Studio is a data labeling tool
heartex/label-studio           	1.5.0        	1.12.1      	Label Studio is a data labeling tool
heartex/label-studio           	1.4.11       	1.12.1      	Label Studio is a data labeling tool
heartex/label-studio           	1.4.10          1.12.1      	Label Studio is a data labeling tool
```

The app version is not equal to chart version. You can use the command from the above to get the list of chart versions.

If you're looking for LS 1.13.1 the command will be:
```
helm install label-studio-test-1 heartex/label-studio --version 1.6.3
```
