### ISSUE TITLE
Azure Blob Storage sync does not import images/tasks

### ISSUE THREAD

**Issue by bennoweber** [heartexlabs/label-studio#646]
**Describe the bug**
Following the the documentation on setting up a connection to Azure blob storage (https://labelstud.io/guide/storage.html#Set-up-connection-in-the-Label-Studio-UI-2) I am not able to import tasks to Labelstudio

**To Reproduce**
1. Open Label Studio in your web browser.
2. Open Settings > Cloud storage sync.
3. For Source Storage, click the gear icon.
4 .In the dialog box that appears, select Azure Blob Storage as the storage type.
5 .Specify the name of the Azure Blob container.
6. (Optional) Adjust the remaining parameters. See Optional parameters on this page for more details.
7. Click Apply & Sync Tasks.

**Expected behavior**
Tasks are loaded to Labelstudio according to filters and parameters specified in the UI

**Screenshots**
![image](https://user-images.githubusercontent.com/73877481/110746421-1319b580-823d-11eb-8ce0-0f6bc2bfed53.png)

**Environment (please complete the following information):**
 - Docker 
 - Label Studio Version 0.9.1.post1

**Additional context**
Labelstudio is running on Docker and is connected to Azure with AZURE_BLOB_ACCOUNT_NAME="myaccountname" and AZURE_BLOB_ACCOUNT_KEY="myaccountkey".
An example on what the input parameters in the UI expect would be very helpfull. Storage path? File prefix? FIle filter by regex? I tried several combinations.
Ma Azure storage account is called "myaccountname" and the containername is called "mycontainername". Within "mycontainername" I have a subfolder with images "mysubfolder".

Any help on this would be highly appriciated!

**Comment by smoreface** [comment]
@bennoweber Did you set a file filter by regex? As it says on the UI, "if not specified, all files will be skipped". Please let us know, thanks!

**Comment by bennoweber** [comment]
Hi, thanks for your reply! Unfortunatly it is not loading tasks. I must be missing something.. Here are screenshots of my inputs in labelstudio and my Container/bucket structure in AZure:
![image (1)](https://user-images.githubusercontent.com/73877481/111270248-ee07b700-862f-11eb-8308-6baa81c4eef8.png)
![image](https://user-images.githubusercontent.com/73877481/111270251-eea04d80-862f-11eb-99fc-0e8535084de3.png)

As @makseq mentioned on my post on Slack, I tried the following inputs: 
Storage path = people
Prefix = subfolder
Regex = .*.jpe?g

IS there a way to debug this or do you have some other tips that I can try? Thanks!

**Comment by bennoweber** [comment]
So I would say that the above bug is resolved with version 1.0.0, Label Studio is loading the tasks now from Azure but the are not recognized as images:
Cannot load image (****************************.jpg', 'container': 'people', 'snapshot': None, 'version_id': None, 'is_current_version': None, 'blob_type': , 'metadata': {}, 'encrypted_metadata': None, 'last_modified': datetime.datetime(2021, 3, 11, 13, 3, 27, tzinfo=datetime.timezone.utc), 'etag': '0x8D8E48E0FEB2BFC', 'size': 143337, 'content_range': None, 'append_blob_committed_block_count': None, 'is_append_blob_sealed': None, 'page_blob_sequence_number': None, 'server_encrypted': True, 'copy': {'id': None, 'source': None, 'status': None, 'progress': None, 'completion_time': None, 'status_description': None, 'incremental_copy': None, 'destination_snapshot': None}, 'content_settings': {'content_type': 'image/jpeg', 'content_encoding': None, 'content_language': None, 'content_md5': bytearray(b'\xc7

**Comment by bennoweber** [comment]
Hi @smoreface ! Do you have any suggestions on howto get Tasks import working from Azure? Any help woul be highly appreciated.

**Comment by niklub** [comment]
Hi, @bennoweber ! Can you please try to update to the `label-studio==1.0.0.post0` or the latest master branch? And check if the problem with Azure syncing still persists

**Comment by niklub** [comment]
Hey, this problem is supposed to be fixed following `label-studio>=1.0.1`. Please feel free to reopen the issue in case it happens again.
