### ISSUE TITLE
Tasks are not visible in Chrome Version 129.0.6668.90 (Official Build) (arm64)

### ISSUE THREAD

**Issue by thonic** [heartexlabs/label-studio#6479]
**Describe the bug**

When we create a new project and import tasks into it, anyone signing with the latest Chrome sees an empty list. If we sign with Firefox, everything works and we are able to both see and label the tasks. 

**To Reproduce**
1. Create a new project.
2. Import some tasks.
3. Sign in in Chrome (Version 129.0.6668.90 (Official Build) (arm64)).

**Environment (please complete the following information):**
 - OS: iOS
 - Label Studio Version: 1.12.1

**Comment by makseq** [comment]
This bug is related to the recent update of chromium browsers. Please, upgrade your LS instance to 1.13.1 or downgrade your browser. Also, you can try Firefox.
