### ISSUE TITLE
How to stop audio auto-rewinding?

### ISSUE THREAD

**Issue by sedol1339** [heartexlabs/label-studio#6485]
Hello! Let me ask several related questions about audio waveform.

1. When I adjust the end boundary of the segment, it automatucally rewinds to the segment start. It is very inconvenient since I use large zoom to set the end point precisely, and my whole segment is long. Is it possible to stop this behaviour?
2. Also, when I create a segment, how would I stop from automatically starting to play in a loop?
3. And finally, how to add more zoom levels? With ctrl+wheel, the second zoom level is around 20x from the first zoom level.

**Comment by heidi-humansignal** [comment]
Hi there!

**Regarding the automatic rewind when adjusting the end boundary of a segment:**
Currently, when you adjust the end boundary of an audio segment in Label Studio, the playback automatically rewinds to the segment start. I understand that this behavior can be inconvenient, especially when working with long segments at high zoom levels. Unfortunately, there isn't an option available at the moment to change this behavior. I'll pass your feedback to our development team for consideration in future updates.
**Regarding stopping the segment from automatically playing in a loop upon creation:**
This is a known issue that other users have brought up as well. As of now, Label Studio doesn't provide an option to disable the automatic looping playback of new segments when they are created. Our team is aware of this limitation and is considering it for future releases.
We've got a ticket internally to track this as a feature request, and I'll be sure to add your feedback to the request as well!
In the meantime, a possible workaround is to manually stop the playback after creating a segment, though I understand this may not fully address your needs.
If you have any further questions or need assistance with anything else, please let me know.

Thanks,

Tyler Conlee
Head of Support
HumanSignal

*Comment by Tyler Conlee*

**Comment by Uzochukwu2029** [comment]
Hello
