### ISSUE TITLE
Number of Video Frames in label-studio is not the same as number of frames

### ISSUE THREAD

**Issue by mgreiner79** [heartexlabs/label-studio#6493]
**Describe the bug**
When exporting video frames, (using OpenCV) , the number of frames exported is different than the number of frames shown in label-studio.  For example, label-studio's GUI shows 535 frames, and OpenCV will export 641 frames. When I inspect the frame numbers, I can see that the frame that label-studio labelled as 395, OpenCV found at fram 474. 
Why is this a problem? Because the video frames need to be exported in order to feed it as training data to a CNN model, like YOLO5. The labels need to match correctly with the frames they are meant to annotate.

**To Reproduce**
1. Create a project that uses the video object tracking template
2. Upload a video
3. Note the number of frames in the video
4. Load the video into python and export the frames:
```python

import cv2
import os

def load_video(filepath: str) -> cv2.VideoCapture:
    video = cv2.VideoCapture(filepath)
    if not video.isOpened():
        raise ValueError(f"Cannot open the video file: {filepath}")
    return video

def read_next_image(video):
    success, frame = video.read()
    return success, frame

def save_image_to_storage(frame, output_folder, index, root_name="frame"):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    frame_filename = os.path.join(output_folder, f"{root_name}_{index:05d}.jpg")
    
    cv2.imwrite(frame_filename, frame)
    print(f"Saving image to: {frame_filename}")
    return frame_filename

def save_frames_to_storage(video, output_folder, root_name):
    success, frame = read_next_image(video)
    print(success)
    filenames = []
    index = 0
    while success:
        filename = save_image_to_storage(frame, output_folder, index, root_name)
        filenames += [filename]
        success, frame = read_next_image(video)
        index += 1
    return filenames

if __name__ == "__main__":
    filepath = "my_video.mp4"
    video = load_video(filepath)
    filenames = save_frames_to_storage(video, "./data", "my_outfile_name")
    video.release()
```
5. After running this, take note of the number of images written to disk. It will be different from the number of frames shown on the label-studio GUI.

**Expected behavior**
The frame numbers in the label-studio GUI should match 1to1 with the frame numbers exported when writing the video frames to images.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11
 - Label Studio Version 1.13.1

**Additional context**
The videos are mp4.

**Comment by mgreiner79** [comment]
I just figured it out!
The frame rate set in the labelling interface should be the same as the frame rates used by OpenCV to export the images.

```html

<View>
   <View><Filter toName="videoLabels" minlength="0" name="filter"/><Labels name="videoLabels" toName="video" allowEmpty="true">
     
 
   <Label value="Not Ready" background="#FFA39E"/><Label value="Windup" background="#D4380D"/><Label value="Stride" background="#FFC069"/><Label value="Arm Cocking" background="#AD8B00"/><Label value="Arm Acceleration" background="#D3F261"/><Label value="Arm Deceleration" background="#389E0D"/><Label value="Follow Through" background="#5CDBD3"/><Label value="Ball" background="#096DD9"/><Label value="Set" background="#FFA39E"/></Labels></View>
   
   <!-- Please specify FPS carefully, it will be used for all project videos -->
   <Video name="video" value="$video" framerate="30.0" zoom="true" zoomControl="true"/>
   <VideoRectangle name="box" toName="video"/>
</View><!--{
 "video": "/static/samples/opossum_snow.mp4"
}-->
```

The default framerate for label-studio is 24 fps, and the framerate for the videos was 30 fps. If is set the framerate in OpenCV to 24 fps then it works. Alternatively, if dont change opencv's settings, but set the framerate in label-studio's interface to 30 fps, then it works.

**Comment by nlangellier** [comment]
I have questions regarding this issue:
1. Why is the label-studio default framerate a fixed value (i.e. 24 FPS)? Wouldn't it make more sense for the default frame rate to equal the native frame rate of the uploaded video?
2. Is the 24 FPS default framerate mentioned anywhere in the documentation? I have been unable to find any mention of it.

**Comment by fuyong-han** [comment]
I ran into the same problem. It's really frustrating because I've already spent a whole day on labeling.
