### ISSUE TITLE
No more data available for labeling

### ISSUE THREAD

**Issue by Yannik1337** [heartexlabs/label-studio#650]
**Describe the bug**
I can run LS with the ML backend fine. I did set the `"sampling": "prediction-score-min"`option in the config. Unfortunately, I can't seem to get LS sample the new data for me. It always says `No more data available for labeling`, which is strange since I have only manually labeled 8 files so far. 

**Expected behavior**
Sampling with the prediction score min

**Screenshots**
That's the starting screen
![Bildschirmfoto 2021-03-15 um 11 25 42](https://user-images.githubusercontent.com/50734087/111139762-d1ad4100-8581-11eb-8efd-97e832a56ab0.png)

And that's the screen I get when I click on `Label`, in the upper right corner:
![Bildschirmfoto 2021-03-15 um 11 30 31](https://user-images.githubusercontent.com/50734087/111139831-e7bb0180-8581-11eb-9819-f789f8cae7dd.png)

**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Label Studio Version 0.9.1.post1

**Additional context**
I did create the project with this command:
`label-studio init my_project --input-path=/path/to/audio/directory/ --input-format=audio-dir --label-config=config.xml --allow-serving-local-files`, and then manually changed the config.json to `"sampling" : "prediction-score-min"`.

Running `label-studio start my_project --sampling=prediction-score-min --ml-backends http://localhost:9090`throws me an error saying that `label-studio start: error: argument --sampling: invalid choice: 'prediction-score-min' (choose from 'sequential', 'uniform')`, which is weird since you write in your [documentation ](https://labelstud.io/guide/tasks.html#Set-up-task-sampling-for-your-project): "To enable task sampling, specify one of the sampling option with the --sampling=<option> command line argument when you start Label Studio."

This is the `config.json` file I am  using:
```
{
  "title": "Label Studio",
  "description": "default",
  "protocol": "http://",
  "host": "0.0.0.0",
  "port": 8080,
  "debug": false,
  "label_config": "config.xml",
  "input_path": "tasks.json",
  "output_dir": "completions",
  "instruction": "<img src='static/images/ls_logo.png'><br> Type some <b>hypertext</b> for annotators here!<br> <a href='https://labelstud.io/guide/labeling.html'>Read more</a> about the labeling interface.",
  "allow_delete_completions": true,
  "templates_dir": "examples",
  "editor": {
    "debug": false
  },
  "sampling": "prediction-score-min",
  "enable_predictions_button": true,
  "ml_backends": [
    {
      "url": "http://0.0.0.0:9090/",
      "name": "my_project7c63"
    }
  ],
  "task_page_auto_update_timer": 10000,
  "show_project_links_in_multisession": true,
  "experimental_features": false,
  "first_page_full_render": true,
  "source": {
    "name": "Tasks",
    "type": "tasks-json",
    "path": "tasks.json"
  },
  "target": {
    "name": "Completions",
    "type": "completions-dir",
    "path": "completions"
  },
  "allow_serving_local_files": true
}
```

**Comment by makseq** [comment]
@Yannik1337 Could you check it in LS 1.0, I hope it's fixed there.

**Comment by Yannik1337** [comment]
There's much that has changed in LS 1.0, it has a cleaner UI and is definitely more responsive. 
I however have not found a way to import the data by pointing LS to a directory, as I did previously with this command:
```
label-studio init my_project --input-path=/path/to/audio/directory/ --input-format=audio-dir --label-config=config.xml --allow-serving-local-files
```
How can I achieve this? I have thousands of files, which I thus can not import manually-- I found pointing LS to a directory quite comfortable to use!

**Comment by niklub** [comment]
Hi, @Yannik1337 ! `--input-path` pointed to the directory is deprecated. Starting from version 1.0.1, you have two options for serving local files:
1. Run a separate server (e.g. with `python -m http.server 8081` to get URLs pointed to your local files as `http://localhost:8081/audio.wav`. You can collect them manually and import the list from UI (also some [helper scripts are available for that](https://github.com/heartexlabs/label-studio/blob/release/1.0.1/scripts/serve_local_files.sh))
2. Use **Local files storage** from cloud storage project settings

**Comment by Yannik1337** [comment]
Hi @niklub , thanks for this hint-- I did not see that before!
After working with the new LS 1.0.0 I have a few suggestions:

- Template for plain Audio Classification:
```<View>
  <AudioPlus name="audio" value="$audio"/>
  <Header value="Select class"/>
  <Choices name="class" toName="audio" choice="single-radio" showInLine="true">
    <Choice value="Class 1"/>
    <Choice value="Class 2"/>
  </Choices>
</View>
<!-- { "data": {"audio": "https://app.heartex.ai/static/samples/game.wav"} } -->
```

- Add a hint for local files during project setup. When creating a new project you can select the tab Data Import. Just add a short message that links to adding local files

**Comment by Yannik1337** [comment]
After importing all the tasks, I can view them, but not play the audio files:
![Bildschirmfoto 2021-04-02 um 09 58 51](https://user-images.githubusercontent.com/50734087/113397931-1caabf00-939e-11eb-8607-8c59bee0d64e.png)

Looking in the console, I find many 403s:
`Failed to load resource: the server responded with a status of 403 (Forbidden)`
As I am using local storage I can not configure CORS. In the previous LS versions I did set "serving_local_files" (or similar) to True. Might this be a problem?

**Comment by Yannik1337** [comment]
From a previous project setup, where I ran LS and local files with the CLI, I pointed it to an audio directory, which automatically created a tasks.json file.

I can see that the files are listed there as:
```
"1": {
    "id": 1,
    "task_path": "/a/b/c/d/e/f/g/2020-09-21T16:37:51.flac",
    "data": {
      "audio": "/data/2020-09-21T16%3A37%3A51.flac?d=%2Fa%2Fb%2Fc%2Fd%2Fe%2Ff%2Fg"
    }
  },
```
 whereas in the new UI they are listed as
```
{
  "id": 2986,
  "data": {
    "audio": "/data/local-files/?d=a/b/c/d/e/f/g/2020-09-21T16:30:48.flac"
  },
  "annotations": [],
  "predictions": []
}
```
The difference I want to point out is in the naming of the files.

**Comment by Yannik1337** [comment]
After working with it I found, hidden in the console logs:
`Serving local files can be dangerous, so it's disabled by default. You can enable it with LOCAL_FILES_SERVING_ENABLED environment variable`.
I'd recommend to add this as a command line option to [this page](https://labelstud.io/guide/start.html#Command-line-arguments-for-starting-Label-Studio), and place a hint more prominently (e.g. when selecting local storage in the UI)

**Comment by Yannik1337** [comment]
After upgrading to the latest Docker image `docker pull heartexlabs/label-studio:1.0.1` I am now getting a new error:
The console logs say: 
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`,
and clicking on this error I see the following screen:

![Bildschirmfoto 2021-04-06 um 10 26 46](https://user-images.githubusercontent.com/50734087/113681768-a6ba9680-96c2-11eb-9b60-f8da30152a33.png)

My labeling configuration is as listed [here](https://github.com/heartexlabs/label-studio/issues/650#issuecomment-812399750), and I have set `ENV LOCAL_FILES_SERVING_ENABLED=True` in my Dockerfile.

**Comment by niklub** [comment]
Hi, @Yannik1337 ! Sorry, I've unsuccessfully tried to reproduce your issue with the latest label studio, what it's done:
1. Install label-studio (`/version` gives backend "commit": "71278b")
2. Set local files storage, pointed to the directory where [flac file](https://filesamples.com/samples/audio/flac/Symphony%20No.6%20(1st%20movement).flac) is located
3. Specify [your labeling config](https://github.com/heartexlabs/label-studio/issues/650#issuecomment-812399750)

Then it gives me no error when checking it from the data manager view
![image](https://user-images.githubusercontent.com/6087484/113690810-7a0f7a80-96d4-11eb-9c77-19b74a798083.png)

So can you please check:
- whether your audio format is correct and you're able to play audio files from the browser
- regarding the 500 error when running from docker - ensure your local paths are accessible from inside the running container

**Comment by Yannik1337** [comment]
@niklub thank you for taking the time trying to reproduce this issue.
I have followed your steps, and at first it did not work.
I then switched from Safari 13.0.5 (15608.5.11) to Chrome. Now it works! Thanks a lot!
(You might consider adding this as a hint that this Safari version does not seem to work with audio files)
