### ISSUE TITLE
Dynamic pre-selection for `Choice` 

### ISSUE THREAD

**Issue by mspronesti** [heartexlabs/label-studio#6507]
I am trying to pre-select the label of each task of my LS project given a list of preselected options. However, I get the following error:

<img width="571" alt="image" src="https://github.com/user-attachments/assets/d4440734-d3b1-4223-be02-c202b1ebcdac">
 
Here's a minimal reproducible example:

```py
from label_studio_sdk import Client


def generate_label_config():
    return f"""
        <View>
          <Header value="Title: $title" />
          <Header value="Items and Labels:" />
          <View>
            <Text name="item_name" value="$item_name" />
            <Choices name="item_label" toName="item_name" choice="single" required="true" showInline="true">
              <Choice value="left" selected="$preselect_0"/>
              <Choice value="middle" selected="$preselect_1"/>
              <Choice value="right" selected="$preselect_2"/>
            </Choices>
          </View>
        </View>
    """


if __name__ == '__main__':
    fake_data = [
        {
            'title': 'title0',
            'preselect_0': True,  # I also tried with strings, to no avail
            'preselect_1': False,
            'preselect_2': False,
            'item_name': 'name0',
            'item_label': 'label0',
        },
        {
            'title': 'title1',
            'preselect_0': False,  # I also tried with strings, to no avail
            'preselect_1': True,
            'preselect_2': False,
            'item_name': 'name1',
            'item_label': 'label1',
        }
    ]

    ls = Client(url='http://localhost:8080', api_key='YOUR-API-KEY')
    label_config = generate_label_config()

    project = ls.start_project(
        title="Fo project",
        label_config=label_config
    )
    project.import_tasks(fake_data)

```

**Comment by heidi-humansignal** [comment]
Hey there!

Thank you for reaching out.
I understand you're trying to pre-select choices for each task in your Label Studio project by using dynamic variables in the `selected` attribute of the `<Choice>` tags. However, you're encountering an error.
The `selected` attribute in the `<Choice>` tag does not support dynamic variables directly in the way you're attempting. Instead, to pre-select choices per task, the recommended approach is to use **pre-annotations**.
Here's how you can modify your code to achieve the desired behavior:

1. **Update your labeling configuration** by removing the `selected` attributes:

    <View> <Header value="Title: $title" /> <Header value="Items and Labels:" /> <View> <Text name="item_name" value="$item_name" /> <Choices name="item_label" toName="item_name" choice="single" required="true" showInline="true"> <Choice value="left"/> <Choice value="middle"/> <Choice value="right"/> </Choices> </View> </View>

1. **Modify your task data** to include the `predictions` field with pre-selected choices:

    fake_data = [{ "data": { 'title': 'title0', 'item_name': 'name0', 'item_label': 'label0', }, "predictions": [ { "model_version": "preselect_v1", "result": [ { "from_name": "item_label", "to_name": "item_name", "type": "choices", "value": { "choices": ["left"] } } ] } ] }, { "data": { 'title': 'title1', 'item_name': 'name1', 'item_label': 'label1', }, "predictions": [{ "model_version": "preselect_v1", "result": [ { "from_name": "item_label", "to_name": "item_name", "type": "choices", "value": { "choices": ["middle"] } } ] } ] } ]

1. **Import the tasks into your project**:

    project.import_tasks(fake_data)

This way, the pre-selected choices are defined via **pre-annotations**, which Label Studio will display when you open each task.
For more information on importing pre-annotations, please refer to the Label Studio documentation on Importing pre-annotations.
Please let me know if this resolves your issue or if you have any further questions.

Thanks,

Tyler Conlee
Head of Support
HumanSignal

> Comment by Tyler Conlee
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11332123022)
