### ISSUE TITLE
Docker Compose not working

### ISSUE THREAD

**Issue by abneetwats24** [heartexlabs/label-studio#653]
**Describe the bug**

I did not get label-studio working using  docker-compose 

**To Reproduce**
1. INIT_COMMAND='--init --force' docker-compose up 
2. See an error: 
                            

> Creating label-studio ... done
>                             Attaching to label-studio
>                             label-studio    | Traceback (most recent call last):
>                             label-studio    |   File "/usr/local/bin/label-studio", line 33, in <module>
>                             label-studio    |     sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
>                             label-studio    |   File "/usr/local/bin/label-studio", line 22, in importlib_load_entry_point
>                             label-studio    |     for entry_point in distribution(dist_name).entry_points
>                             label-studio    |   File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 610, in distribution
>                             label-studio    |     return Distribution.from_name(distribution_name)
>                             label-studio    |   File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 229, in from_name
>                             label-studio    |     raise PackageNotFoundError(name)
>                             label-studio    | importlib_metadata.PackageNotFoundError: No package metadata was found for label-studio

                          
**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Label Studio Version commit f50eb03

**Comment by makseq** [comment]
@abneetwats24 Please check the latest master branch commits.
