### ISSUE TITLE
1500 images export dataset as  coco format just show annotations for 30 images

### ISSUE THREAD

**Issue by nextvirus** [heartexlabs/label-studio#6547]
My project has 1500 images when i export dataset as coco format from ui , the result.json file only shows annotations for 30 images. 
How to fix it ?

 - OS: windows 11
 - Label Studio Version 1.13.1

**Comment by nextvirus** [comment]
I have found the reaseon. My backend ml retrun the data type of the images is worng.

 result.append({
      'from_name': 'label',
      'to_name': 'image',
      'type': 'rectanglelabels',
      'value': {
          'points': [[x, y], [x + width, y], [x + width, y + height], [x, y + height]],
          'rectanglelabels': [self.categories.get(label.item(), "Unknown")]  # Ensure label is correctly fetched and is a list

      },
      'score': score.item(),
  })

**Comment by heidi-humansignal** [comment]
Hello,

Sounds good. Glad you figured it out.

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11523774991)
