### ISSUE TITLE
ComboBox/Button With State

### ISSUE THREAD

**Issue by kubzoey95** [heartexlabs/label-studio#6549]
**Is your feature request related to a problem? Please describe.**
In text classification I would like to have a label for e.g. Car but with different levels of confidence - e.g. "Exists", "Unsure", "Not exists", "Don't know".

**Describe the solution you'd like**
Option 1: Combobox text classification label.
Option 2: Button with state. The state increments when button is clicked and goes back to zero after going out of range.

**Describe alternatives you've considered**
I couldn't find a widget for such usecase, I know I could add class for each confidence value - e.g. "Car Exists", "Car Unsure", "Car Not exists", "Car Don't know" but I have a lot of classes in my project and that would quadruple number of classes to be viewed, would be very painful to annotate and is not exactly what I want as it allows user to click multiple confidence classes for one class. I've considered using ratings also but it also gets tricky to get what I want. 

**Additional context**

**Comment by heidi-humansignal** [comment]
Hello,

I think you can try conditional labeling and based on the label selected, you can give them a choice of "Exists", "Unsure", "Not exist" and "Don't know".
Something similar to this:

    <View> <Text name="text" value="$text"/> <Choices name="label_choice" toName="text" choice="single"> <Choice value="Car"/> <Choice value="Bus"/>  </Choices> <Choices name="confidence_choice" toName="text" choice="single" visibleWhen="choice-selected" whenTagName="label_choice" whenChoiceValue="Car"> <Choice value="Exists"/> <Choice value="Unsure"/> <Choice value="Not exists"/> <Choice value="Don't know"/> </Choices> </View>

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11564422722)
