### ISSUE TITLE
Add multi-selection for label instances

### ISSUE THREAD

**Issue by mbuet2ner** [heartexlabs/label-studio#655]
**Is your feature request related to a problem? Please describe.**
When using pre-labled data, e.g. bounding boxes with background class that the annotator has to assign the "real" class to, the current setup only allows to change labeling for one bounding box at a time. Especially with a lot of bounding boxes (or NER labels etc.) this is very laborious.
The feature would also benefit the ml-backend option, since one could correct wrong labels much quicker (especially if there are lots of label instances).

**Describe the solution you'd like**
The user should be able to modify several label instances (e.g, bounding boxes and their respective class) at once.

**Describe alternatives you've considered**
Multi-selection of labels, e.g. by pressing shift/ctrl and/or ability to draw selection boxes on screen when no class is selected that selects multiple instances. The latter seems more practical to me.

**Additional context**
None

Anyway, thanks a ton for the fantastic tool! 🥳

**Comment by makseq** [comment]
This feature have been released in LS 1.3.
