### ISSUE TITLE
Can support brushLabel export to yolo or yolo-seg formmat?

### ISSUE THREAD

**Issue by Twenty3hree** [heartexlabs/label-studio#6556]
![1729845808551](https://github.com/user-attachments/assets/cb3e6579-30e7-4297-a408-42f1d2ce7b19)
now, when we export to yolo, we can only export to these 3 label_format

**Comment by heidi-humansignal** [comment]
Hello,

Currently, Label Studio does not support exporting BrushLabels directly to YOLO or YOLO-Seg format. BrushLabels are used for pixel-wise segmentation tasks, and exporting them to YOLO format, which primarily supports bounding boxes and polygons, is not directly available.
However, you can export your BrushLabels as PNG or NumPy mask files and then convert them to the desired format using custom scripts. Some community members have shared solutions for converting masks to formats compatible with YOLO.

You might find this GitHub issue helpful:

- Empty Label files when using meta SAM using the label-studio-ml-backend
In that discussion, users have shared scripts and methods to convert brush masks into polygon annotations or YOLO-compatible formats.


Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11524240581)

**Comment by Twenty3hree** [comment]
Thanks a lot

**Comment by heidi-humansignal** [comment]
No problem, I'll close this issue.

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11581859926)
