### ISSUE TITLE
whenChoiceValue not working

### ISSUE THREAD

**Issue by zhanjiezhu** [heartexlabs/label-studio#657]
**Describe the bug**
`whenChoiceValue` is not working for Choices since version 0.8.2

**To Reproduce**
1. Go to https://labelstud.io/playground/
2. Click on "Advanced config templates"
3. Click on "Three level classification"
4. In the preview, select "positive" and then "Emotional", nothing show up

**Expected behavior**
4 more choices should show up when "Emotional" is selected

**Environment (please complete the following information):**
 - Label Studio Version [from 0.8.2] (works in 0.8.1)

**Comment by niklub** [comment]
Hi, @zhanjiezhu ! Seems that the problem has gone in [1.0.1 release branch](https://github.com/heartexlabs/label-studio/pull/681). Can you check it, please? We will close this issue as soon as 1.0.1 will be released

**Comment by makseq** [comment]
Feel free to reopen if the problem occurs again.
