### ISSUE TITLE
task list

### ISSUE THREAD

**Issue by Miyoshi-a** [heartexlabs/label-studio#6587]
**Describe the bug**
Do not show task list

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/0712f347-c479-4482-944e-73d012c6fa01)

**Environment (please complete the following information):**
 - OS: windows
 - Label Studio Version 1.7.3

**Additional context**

**Comment by makseq** [comment]
Upgrade your LS version to 1.13.1. Or use firefox/safari.
