### ISSUE TITLE
Synchronize local storage with pre-annotations data

### ISSUE THREAD

**Issue by arbuserUser** [heartexlabs/label-studio#6595]
**Describe the bug**
I have a local storage containing images in bmp format and json files with annotations created by a third-party application. When I import files through the UI, everything works. But if I try to synchronize the storage to add all the json files to the project at once, LS gives an error There was an issue loading URL from $image value.

**To Reproduce**
1. Сreate a new project
2. Add local storage containing images and files with pre-annotations for each image
3. Try importing a one json file through the UI with the "Import" button.  Make sure everything went well.
4. Try to sync local storage. Make sure that images referenced by field "image" in json files are not displayed in the project

**Expected behavior**
It was expected that synchronization of a storage containing many json files would work similarly to importing a file through the UI for all files.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/4421abec-602a-424a-aa9c-c83b1cff2e1e)
![изображение](https://github.com/user-attachments/assets/97a7d1f9-0651-44b4-9dfb-b3feb5d000fc)
![изображение](https://github.com/user-attachments/assets/db7bf334-d8c8-4535-b0de-def920439b34)
![изображение](https://github.com/user-attachments/assets/13347c38-5123-487e-b8c9-4e540b1f7f87)

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04.1 LTS
 - Label Studio Version 1.14.1

**Comment by makseq** [comment]
You have to disable the toggle "Treat every bucket as a source file" on the storage card settings to be able to sync json files.

**Comment by arbuserUser** [comment]
Thanks for the answer! But when I try to sync the storage like you said, I get error: 
![изображение](https://github.com/user-attachments/assets/c43fce8c-0ebd-4d61-93cc-caedaf65dd64)
Here is an example of my json file:
![изображение](https://github.com/user-attachments/assets/cc36ecf5-d396-45cc-a496-4891cb22ef6e)
Please tell me what is my mistake?

**Comment by arbuserUser** [comment]
I think I solved the problem. I needed to remove [ ] those brackets at the beginning and end of my file.

**Comment by AbubakarSaad** [comment]
Glad it worked out, I'll mark issue as closed.

**Comment by Bradly-s** [comment]
> I think I solved the problem. I needed to remove [ ] those brackets at the beginning and end of my file.

Can't there be an outermost []?
