### ISSUE TITLE
Amazon S3 Sync Data

### ISSUE THREAD

**Issue by chaserit123** [heartexlabs/label-studio#6596]
**Describe the bug**
When I sync the data from my bucket they all import into the project just fine. When I select an image to label it I get this error:
![image](https://github.com/user-attachments/assets/4d57ed37-efb4-479b-9e90-26cbba3a2fc5)

**To Reproduce**
1. Go to Projects
2. Click on a project
3. In the labeling interface select an image to label
4. You will see the error on the right in the image above.

**Expected behavior**
I would expect the app to open the image in full view of right panel for labeling.

**Screenshots**
![image](https://github.com/user-attachments/assets/79339921-28d2-43cc-a6e1-791b1f7f6181)

**Environment (please complete the following information):**
 - OS: Docker/Ubuntu
 - Label Studio Version 1.13.1

**Additional context**
Here is a screenshot of the task when I click on details:
![image](https://github.com/user-attachments/assets/e5e53082-64bd-4dca-8bbf-5a84287774c8)

**Comment by heidi-humansignal** [comment]
Hello,

Glad it worked out!

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11671999778)
