### ISSUE TITLE
Installed grounding_sam but actions are not added

### ISSUE THREAD

**Issue by trongldwork** [heartexlabs/label-studio#6607]
**Describe the bug**
I've install grounding_sam ML backend and it works, but when i click at actions button like batch predictions tutorial, the options for batch predictions with prompt by grounding DINO is not showed.

**To Reproduce**
1. Go to Data Manager
2. Select tasks
3. Click on actions button
5. See error

**Expected behavior**
Pls, help me to solve it

**Screenshots**

![image](https://github.com/user-attachments/assets/340569ad-221b-4556-8b85-1aa33cb70956)
![image](https://github.com/user-attachments/assets/7d0614df-d5db-4b69-aee9-825f43870b55)
![image](https://github.com/user-attachments/assets/8d5eb3a4-b83b-4d03-be09-4026af47d4cf)

**Comment by heidi-humansignal** [comment]
Hello,

You have to clone feature branch. Here are the instruction:

To enable batch predictions with GroundingDINO and SAM, please follow these steps:

1. **Clone the Label Studio feature branch that includes the experimental batching functionality:**

    git clone -b feature/dino-support https://github.com/HumanSignal/label-studio.git

1. **Navigate to the cloned directory:**

    cd label-studio

1. **Run Label Studio using Docker Compose:**

    docker compose up

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/11758108109)

**Comment by trantuankhoi** [comment]
Hi @trongldwork, have you resolved this issue?

**Comment by regainOWO** [comment]
Will the feature/dino-support branch be merged into the develop branch and released? This is not in correspondence with the demonstration video in the document.
