### ISSUE TITLE
I can't export the labeled dataset in the format I need

### ISSUE THREAD

**Issue by xceccon** [heartexlabs/label-studio#6611]
Dear label-studio team and community,

I labeled a small dataset with the "Semantic Segmentation with Masks" template, and I can't export it with the ultralytics standard. The ultralytics standard needs a yaml file, and then two folders, one containing images and the other one containing txt files with the information regarding the mask. As you can see the image I attach, the  exports which would be compatible are not available for my dataset. There is one export called "YOLO v8 OBB" which would sound compatible but it actually exports txt files which are empty, so it does not seem to work with masks and it's probably more suited for exporting other object detection types.

![image](https://github.com/user-attachments/assets/823f5116-039d-4757-83d1-1dc7b8dedfea)

**Describe the solution you'd like**
I would like to be able to export to ultralytics format, or have access to a script which can convert any other export to the ultralytics standard. The difficulty here is that the txt files are completely empty.

**Describe alternatives you've considered**
I've considered developping a script which converts the available exports to ultralytics standard, but generating the .txt files seems technically out of reach for me.

**Additional context**
I'm working on creating a dataset for masking trains and train tracks.
![image](https://github.com/user-attachments/assets/ca837916-e43c-49af-8162-4d6826e42133)

**Comment by makseq** [comment]
You have to use PolygonLabels in your labeling configuration, that template uses BrushLabels and export to yolo is not supported for it.

**Comment by xceccon** [comment]
Hello Max,

Thank you for your answer. You are right, I tried with PolygonLabels and now it works.

BR,
Xuban

**Comment by sumrako** [comment]
> You have to use PolygonLabels in your labeling configuration, that template uses BrushLabels and export to yolo is not supported for it.

Please make the export to Yolov8 inactive(gray) when selecting the BrushLabels mode.
