### ISSUE TITLE
pip install error if missing wheel

### ISSUE THREAD

**Issue by brharper** [heartexlabs/label-studio#662]
Pip install is erroring on Ubuntu 20.04. Running in a clean venv I get:  

```
error: invalid command 'bdist_wheel'
  ----------------------------------------
ERROR: Failed building wheel for X
```
Where X is: 
* rules
* ordered-set
* htmlmin
* django-redis-cache
* drf-generators
* attr
* coreschema
* nltk
* openapi-codec
* pyrsistent

I've attached 2 log files, label-studio_install_try1_17-Mar-2021.log, and label-studio_install_try2_17-Mar-2021.log. Both have version info and pip install output in them. 

Try 1 has a clean venv __without__ wheel installed first. This is where the failure happens. I then captured the install of wheel and the second try at label-studio 

Try 2 has a clean venv __with__  wheel installed first. Everything runs as expected.   

[label-studio_install_try1_17-Mar-2021.log](https://github.com/heartexlabs/label-studio/files/6156449/label-studio_install_try1_17-Mar-2021.log)
[label-studio_install_try2_17-Mar-2021.log](https://github.com/heartexlabs/label-studio/files/6156450/label-studio_install_try2_17-Mar-2021.log)

**Comment by makseq** [comment]
@brharper What do you think: if we include `wheel` into LS requirements.txt in the first line, will it resolve this issue?

**Comment by brharper** [comment]
@makseq I'm not familiar with how the requirements.txt interacts with the pypi package, but if it's implicitly used for dependency, I assume your proposed fix would work. Thanks!

**Comment by makseq** [comment]
We have released more LS versions, check them please, wheel must be included there.
