### ISSUE TITLE
Label studio can not display project details properly

### ISSUE THREAD

**Issue by foreverwith** [heartexlabs/label-studio#6625]
**Describe the bug**
Label studio is always running well. 
However, after I upgraded my system from Ubuntu 16.04 to 22.04, I ran "label-studio start" as I did earlier, and I could not see the presentation of the project page.

**To Reproduce**
1. Go to 'Label Studio' homepage
2. Click on 'Projects'
3. Click on 'project name'

**Expected behavior**
A list of all the tasks contained in the project.

**Screenshots**
I could see an empty page.
![image](https://github.com/user-attachments/assets/57823b2e-9c07-48b1-ac6b-89fcfd7deb1c)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Label Studio Version 1.7.2

**Additional context**
The data in Label Studio is very important to me, how do I back up my data if I need to uninstall and reinstall Label Studio? Thanks a lot.

**Comment by SouthBays** [comment]
it seems to be a fronted problem.The problem disappeared when I used firefox

**Comment by SouthBays** [comment]
> **Describe the bug** Label studio is always running well. However, after I upgraded my system from Ubuntu 16.04 to 22.04, I ran "label-studio start" as I did earlier, and I could not see the presentation of the project page.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'Label Studio' homepage
> 2. Click on 'Projects'
> 3. Click on 'project name'
> 4. See error
> 
> **Expected behavior** A list of all the tasks contained in the project.
> 
> **Screenshots** I could see an empty page. ![image](https://private-user-images.githubusercontent.com/7135401/384674943-57823b2e-9c07-48b1-ac6b-89fcfd7deb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTUxMzUsIm5iZiI6MTczMTI1NDgzNSwicGF0aCI6Ii83MTM1NDAxLzM4NDY3NDk0My01NzgyM2IyZS05YzA3LTQ4YjEtYWM2Yi04OWZjZmQ3ZGViMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMTYwNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY0ODZkNzc3NjRjZmZlZGQ0YmJlNmIyZjZkZmYwNGQxZTM2OTE5ODg5MGYxNDhjNWViMDU0OTE3ZTBkMjJlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SNhJ_N4EWjNk0ZEV9zB-RoMYzQxSYx1r0qXBVwx_9TY)
> 
> **Environment (please complete the following information):**
> 
> * OS: Ubuntu 22.04
> * Label Studio Version 1.7.2
> 
> **Additional context** The data in Label Studio is very important to me, how do I back up my data if I need to uninstall and reinstall Label Studio? Thanks a lot.

It seems to be fronted problem.The problem disappeared when I changed to use firefox

**Comment by caitlinwheeless** [comment]
Yes, this is a known issue and relates to Chrome compatibility - you need to either upgrade Label Studio to the latest version or use Firefox.

**Comment by foreverwith** [comment]
> Yes, this is a known issue and relates to Chrome compatibility - you need to either upgrade Label Studio to the latest version or use Firefox.

I could only upgrade Label Studio to 1.8.0 by running "pip install -U label-studio", how do I update it to 1.14.0?

**Comment by foreverwith** [comment]
> > **Describe the bug** Label studio is always running well. However, after I upgraded my system from Ubuntu 16.04 to 22.04, I ran "label-studio start" as I did earlier, and I could not see the presentation of the project page.
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to 'Label Studio' homepage
> > 2. Click on 'Projects'
> > 3. Click on 'project name'
> > 4. See error
> > 
> > **Expected behavior** A list of all the tasks contained in the project.
> > **Screenshots** I could see an empty page. ![image](https://private-user-images.githubusercontent.com/7135401/384674943-57823b2e-9c07-48b1-ac6b-89fcfd7deb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTUxMzUsIm5iZiI6MTczMTI1NDgzNSwicGF0aCI6Ii83MTM1NDAxLzM4NDY3NDk0My01NzgyM2IyZS05YzA3LTQ4YjEtYWM2Yi04OWZjZmQ3ZGViMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTBUMTYwNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY0ODZkNzc3NjRjZmZlZGQ0YmJlNmIyZjZkZmYwNGQxZTM2OTE5ODg5MGYxNDhjNWViMDU0OTE3ZTBkMjJlNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SNhJ_N4EWjNk0ZEV9zB-RoMYzQxSYx1r0qXBVwx_9TY)
> > **Environment (please complete the following information):**
> > 
> > * OS: Ubuntu 22.04
> > * Label Studio Version 1.7.2
> > 
> > **Additional context** The data in Label Studio is very important to me, how do I back up my data if I need to uninstall and reinstall Label Studio? Thanks a lot.
> 
> It seems to be fronted problem.The problem disappeared when I changed to use firefox

Thanks, it works. However, I wonder how to visit Label Studio through Chrome.

**Comment by foreverwith** [comment]
> Yes, this is a known issue and relates to Chrome compatibility - you need to either upgrade Label Studio to the latest version or use Firefox.

I upgraded my anaconda python version from 3.7 to 3.8 with the command "conda install -c anaconda python=3.8", and after that I ran "pip install -U label-studio", Label Studio upgraded to 1.13.1.
Now, Label Studio runs well on Chrome. Thanks a lot!
