### ISSUE TITLE
Integrate YOLOv10 to Label-Studio

### ISSUE THREAD

**Issue by datnguyen-tien204** [heartexlabs/label-studio#6646]
Thank you for an excellent tool. Currently, I want to use YOLOv10 to create an auto-labeling tool. Where can I edit the code to adjust bounding boxes and update them when I receive bounding boxes from YOLOv10 ? My task is Object Detection.
 Wishing you a productive day!

**Comment by makseq** [comment]
It's already done here:
https://github.com/HumanSignal/label-studio-ml-backend/tree/master/label_studio_ml/examples/yolo

Just add, for instance, `model_path="yolo11n.pt"` to you labeling configuration. See examples in the docs above ^.
