### ISSUE TITLE
Allow for multiple labelers

### ISSUE THREAD

**Issue by fishcharlie** [heartexlabs/label-studio#6668]
**Is your feature request related to a problem? Please describe.**

There seems to be no way to have multiple annotators for one item. For example I want to have multiple accounts annotate a single item to improve the accuracy of my labeling pipeline.

**Describe the solution you'd like**

Allow for multiple labelers per item.

**Describe alternatives you've considered**

I have considered creating a unique project for each labeler. But that is a lot to keep track of and manage. Ensuring that new items get added to every project, and having to export the data for each project to combine them is a lot of work to maintain.

**Additional context**

NA

**Comment by makseq** [comment]
Hello,

This functionality is available in Label Studio Enterprise and can significantly enhance your experience. Let us know if you'd like to explore it further!
