### ISSUE TITLE
Annotated Data Lost

### ISSUE THREAD

**Issue by abhijithautoai** [heartexlabs/label-studio#6674]
Hi I have around 10000 images in an azure blob storage container. There are intermittent network connection issues and some times the the call to azure blob store fails. But during that time some of the annotations are lost.

**To Reproduce**
1. Setup data import form azure blob store. Use a container prefix path.
2. Annotate a few files.
3. Simulate a network error (Turn off the internet connection so that the get request from azure blob fails)
4. Upto 50% of the annotations will be missing after refreshing.

My assumption was that all the annotations will be persisted in the sql lite database in my local storage. Losing half of the data that I annotated is causing great pain. During the first network connection error the task number I was annotating was 2003. Then after refresh the annotated task numbers where from 1 to 500 only. Rest of the tasks did not have any annotations.

 - OS: Macos 
 - Label Studio Version 1.14.0.post0

**Comment by Bradly-s** [comment]
So, how to solve it? I have used PostgreSQL, but this issue still exists.
