### ISSUE TITLE
Label Studio's Docker Registry has many "develop" images

### ISSUE THREAD

**Issue by shhivam** [heartexlabs/label-studio#6695]
**Describe the bug**
I was checking out the Docker Hub page for the label studio when I saw that there are a lot of images (docker images) which are not related and may be like a bug or something.

**To Reproduce**
1. Go to https://hub.docker.com/r/heartexlabs/label-studio/tags

**Expected behavior**
Ideally, we should only see the docker images which are for production and not the development images.

**Screenshots**

<img width="1498" alt="Screenshot 2024-11-21 at 16 46 30" src="https://github.com/user-attachments/assets/636bbbec-0e77-4378-9a79-96e6296aa541">

**Comment by farioas** [comment]
We have multiple tags for multiple reasons:
- `latest` tag always points to the latest available release of Label Studio.
- `develop` tag always points to the HEAD of develop branch of Label Studio.
- `$timestamp-$branch-$sha` tag points to an exact commit from a branch, on your screenshot - we build each commit from develop to ensure that nothing is broken.
- Release tags (`1.14.0`, `1.14.0.post0`) are aligned with LS releases from this page https://github.com/HumanSignal/label-studio/releases
