### ISSUE TITLE
Alt+Tab Hotkey

### ISSUE THREAD

**Issue by danielcrane** [heartexlabs/label-studio#671]
I was wondering what the rationale behind using `alt + tab` as a hotkey for "Circle through entities" is?

For me, this hotkey doesn't work in Label Studio as it's (understandably) overruled by the system-wide usage of `alt + tab` for window switching, and even if that wasn't the case it seems like strange practice to override a global hotkey (on all major operating systems).

**Comment by makseq** [comment]
@danielcrane Thank you for your feedback. Yes, LS has a not very thoughtful hotkeys, and we are planning a big update for them. 
Alt + Tab was wrongly used because MacOS doesn't have this as the default hotkey.

**Comment by danielcrane** [comment]
I see, thanks so much for the info, looking forward to it!

**Comment by nicholasrq** [comment]
take a look at #1453 please. <kbd>alt + tab</kbd> was replaced with <kbd>alt + .</kbd> and should work just fine on any platform
