### ISSUE TITLE
Heroku one click does not start

### ISSUE THREAD

**Issue by agombert** [heartexlabs/label-studio#6718]
**Describe the bug**
I've clicked on the "heroku deploy" button and it does not work.

**To Reproduce**
1. Click on the "heroku one click deploy" button

**Expected behavior**
Launch the deployment

**Screenshots**
![Capture d’écran 2024-11-26 à 14 44 40](https://github.com/user-attachments/assets/5b1a1918-5416-4406-a1b7-7ee7b2ab5cba)

**Environment (please complete the following information):**
 - OS: macOS
 - Label Studio Version latest

**Additional context**

**Comment by farioas** [comment]
The issue has been resolved, please try to click on the button again.
