### ISSUE TITLE
Image Ctrl+Scroll zoom direction to match common behavior

### ISSUE THREAD

**Issue by Zensome** [heartexlabs/label-studio#6729]
**Is your feature request related to a problem? Please describe.**
When labeling images, the Ctrl+Scroll zoom direction is not intuitive compared to standard browser behavior. Currently, scrolling up would zoom out, and scrolling down would zoom in. This is opposite to what most users expect from common applications.

**Describe the solution you'd like**
Reverse default the scroll direction, and add a setting parameter in the configuration, so the user can decide between the two modes (users who are already used to the old setting can still switch it back).

**Describe alternatives you've considered**
There is no alternative I can think of though.

**Additional context**
I will make a PR to this issue!

**Comment by heidi-humansignal** [comment]
Hello,

That be great if you can make a PR, we do know this is an issue. I'll try to get this infront of eng team once you have PR is up

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/12089853507)

**Comment by Zensome** [comment]
> Hello,
> 
> That be great if you can make a PR, we do know this is an issue. I'll try to get this infront of eng team once you have PR is up
> 
> Thank you, Abu
> 
> > Comment by Abubakar Saad
> > [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/12089853507)

Hi Abu,
Thanks for your response, I've created the PR #6730.
Happy to make any adjustments needed!

**Comment by nick-skriabin** [comment]
@Zensome just letting you know that natural scrolling is now the default behavior with an option to fall back to previous behavior -- you can find an option in the Editor settings called "Invert zoom direction"
