### ISSUE TITLE
Launching label-studio causes error - No module named 'ruamel'

### ISSUE THREAD

**Issue by karnsaurabhkumar** [heartexlabs/label-studio#675]
**Describe the bug**

ModuleNotFoundError: No module named 'ruamel'

**To Reproduce**
1. Open terminal
2. pip install -U label-studio
3. label-studio
4. ModuleNotFoundError: No module named 'ruamel'

**Expected behavior**
Label-studio launches a browser and opens the login page

**Screenshots**
![image](https://user-images.githubusercontent.com/10262962/111637195-3638fc00-881f-11eb-8664-ba9cb19dcdd7.png)

**Environment (please complete the following information):**
 - OS: Catelina
 - Label Studio Version 1.0.0

**Additional context**

**Comment by makseq** [comment]
@karnsaurabhkumar does manual `pip install ruamel` solve this problem? (After this you need to install LS again)

**Comment by karnsaurabhkumar** [comment]
No. Manual install throws another error: 

ERROR: Could not find a version that satisfies the requirement ruamel (from versions: none)
ERROR: No matching distribution found for ruamel

**Comment by antonyscerri** [comment]
The package is called "ruamel-yaml" or "ruamel_yaml" there may be issues depending on the pip. I was using conda and tried uninstalling it with pip and reinstalling with conda. Also if using conda make sure the environment is based on python 3.8 for the 1.0.0 release.

**Comment by niklub** [comment]
So it's supposed to be the problem with the (base) conda environment. Creating conda environment should fix this problem:
```
conda create --name ls-env python=3
conda activate ls-env
pip install label-studio
```

**Comment by karnsaurabhkumar** [comment]
Understood. This was a conda issue and following installation just worked for me:

`conda install ruamel.yaml`

Thank you so much for responding

**Comment by makseq** [comment]
@smoreface Could you please add this issue to installation troubleshooting as "Anaconda problem with ruamel" or something like this?

**Comment by smoreface** [comment]
Yes, will do! Thanks!

**Comment by makseq** [comment]
@smoreface have you added this into docs somewhere?

**Comment by smoreface** [comment]
Yes, it's here: https://labelstud.io/guide/install.html#Troubleshoot-installation
