### ISSUE TITLE
Issue loading time series tasks from local csv files using the API in v1.0

### ISSUE THREAD

**Issue by gamblard** [heartexlabs/label-studio#676]
Hello,

I'm working on a time series annotation pipeline using Label Studio. This pipeline involves extracting time series from a database into multiple .csv files, which are then loaded as tasks in Label Studio.

Before v1.0, I used to load tasks in my Label Studio project using the API, with a JSON task file referencing .csv time series which where manually placed within my <project_name>/upload folder.

Since v1.0, it doesn't work anymore, and as far as I can tell the issue seems to be related to the "file_upload" entry in the JSON task description : when I load my .csv files using the web interface, "file_upload" is set to some value and the data is successfully displayed, but when I use the API with a JSON file having "csv_url" entries pointing to the path of my .csv files (which are now within AppData/Local/label-studio/label-studio/media/upload), I get an error 500 when I try to visualize the series :
![image](https://user-images.githubusercontent.com/79144141/111634972-4fc64d80-87f7-11eb-8601-4fba28840b87.png)

Moreover, the "file_upload" field is null, and it's the only meaningful change between the two tasks.

Task generated using the web interface :
![image](https://user-images.githubusercontent.com/79144141/111634249-9ebfb300-87f6-11eb-8881-50ef0bc0fdd1.png)

Task generated using the API :
![image](https://user-images.githubusercontent.com/79144141/111634437-cd3d8e00-87f6-11eb-9a71-29b608fc399f.png)

Maybe I'm missing something important, or I'm not supposed to place files within the upload folder myself, but if it's the "file_upload" that is causing the issue, I wonder what is the purpose of the "csv_url" field if it's the internal file id that matters ?

Windows 10
Label Studio 1.0.0

**Comment by gamblard** [comment]
Solved my issue by first importing my .csv files using POST api/projects/<id>/import?commit_to_project=false, and then creating the tasks using my json from before v1.0.0, this time setting the "file_upload" field with the response of the import request.

The commit_to_project parameter I've mentioned is not in the API doc, but it's very useful in my case, since when I import my files the "csv_url" parameter is not set and the generated task would not be validated against my configuration.

One more thing totally unrelated, but it seems like when I try to delete all the tasks of a project using DELETE api/projects/<id>/tasks, the tasks containing annotations are not immediately deleted : instead the annotations are removed, and I need to do the request one more time for the task to disappear completely.

**Comment by oyange** [comment]
Is this bug fixed in the latest version?

**Comment by oyange** [comment]
I encountered a similar bug in version 1.0.1

When I imported the first csv file, I encountered this issue
![image](https://user-images.githubusercontent.com/23448269/113720860-9c7bb500-9721-11eb-9ab6-046ffb944dcb.png)

But the second time I imported the same file, I pass the issue
![image](https://user-images.githubusercontent.com/23448269/113720942-ac939480-9721-11eb-956d-ce616b7db0b6.png)

**Comment by hlomzik** [comment]
Hi all! So it seems like everything fixed for everyone?
After upload it should work without problems. Probably that was some cache or upload issue on the last case.
Ping us if this is still the case.
