### ISSUE TITLE
Increase image height when zooming into wide aspect ratio images

### ISSUE THREAD

**Issue by MalteWillmes** [heartexlabs/label-studio#6775]
I am working on a set of wide aspect ratio images (684x11) that I want to annotate with bounding boxes. The problem is that whenever I zoom in the image window height remains the same size instead of filling the white space (see screenshot). Is there a way to change that behavior to fill in the white space when zooming in? I tried a few combinations of changing maxHeight and Height in the image tag but couldnt get the image height increasing.

![image](https://github.com/user-attachments/assets/815a1820-0558-4632-80ee-acca3123fd36)

**Comment by bgsportsben** [comment]
I am having the same issue (see attached images)

![Screenshot from 2024-11-25 06-54-37](https://github.com/user-attachments/assets/ac5a71ef-6382-47b0-98b4-f52c4d6d7192)
![Screenshot from 2024-11-25 06-55-09](https://github.com/user-attachments/assets/f9aec71b-7868-4301-b3c4-84108096545a)

**Comment by makseq** [comment]
Hi, try to add `height` and `maxHeight` to your Image object.

**Comment by MalteWillmes** [comment]
That seems to help but not solve the issue. 
My image tag is: 
Image name="image" value="$image" zoom="true" zoomControl="true" 
         rotateControl="false" maxWidth="100%" maxheight="100%" 
         Height="2000px"/

Screenshot below shows how the canvas looks at initital zoom and then at high zoom. At high zoom there is still a lot of white space
![image](https://github.com/user-attachments/assets/0be42826-4bd0-4d1f-984d-56c99df6dabf)
![image](https://github.com/user-attachments/assets/3b00ce15-a705-49f5-b1c3-856bffc48f0f)

**Comment by MalteWillmes** [comment]
No that does not work. The image does not expand into the white space.

**Comment by hlomzik** [comment]
Hey, @MalteWillmes!
You've set height to 2000px, so it occupies all these 2000px, if you want to make it smaller, set something like 500px.
As I see from the second screenshot it doesn't cut the image, so initial issue seems resolved. And if you continue to zoom in it should expand it more.
Also for a proper work with small images I'd recommend to set `defaultZoom="original" smoothing="false"` plus you can increase zoom factor from 1.1 to higher values: `zoomBy="2"`.

Tell me if you have any other issues after this!

**Comment by bgsportsben** [comment]
My image height is fixed for all of my samples. I simply set the 'height' property as described above, and my issue is resolved (see below).
![Screenshot from 2024-12-16 10-00-22](https://github.com/user-attachments/assets/85641c53-54bb-4686-bc55-d75f4c21ddeb)
![Screenshot from 2024-12-16 10-00-51](https://github.com/user-attachments/assets/cf212ec5-d7cc-42b5-87d7-503a8a199fdf)

**Comment by MalteWillmes** [comment]
Hi. Thank you. I am using the following image tag now, that has resolved this issue:
```
<Image name="image" 
       value="$image"
       zoom="true" 
       defaultZoom="original"
       zoomControl="true"
       zoomBy="1.5"
       rotateControl="false"
       maxWidth="100%" 
       maxheight="2000px" 
       Height="500px">
```
