### ISSUE TITLE
What is the alternative of Repeater? 

### ISSUE THREAD

**Issue by mmmyjun** [heartexlabs/label-studio#6822]
In my case, I need to iterate over multiple lines, each line may have tags such as text and text field.Any suggestions will be useful

**Comment by mmmyjun** [comment]
This is a display issue in the playground, not a real bug. This tag is available

**Comment by mmmyjun** [comment]
The following is my code. There is only one text field in each row. Bug: After clicking the Update button, there is an extra text field in each row. The content of the extra box is the data I have filled in before, and sometimes there is more than one extra row.
```
<Repeater on="$source" indexFlag="{{idx}}">
   <View style="display: flex;border-bottom: 1px solid gray;">
      <View style="flex: 50%;">
        <Text name="s_{{idx}}" value="$source[{{idx}}].text" />
      </View>
      <View style="flex: 50%;">
        <TextArea name="c_{{idx}}" editable="true" maxSubmissions="1" toName="s_{{idx}}" value="$source[{{idx}}].comment" />
      </View>
    </View>
 </Repeater>
```
![i1](https://github.com/user-attachments/assets/3a34391f-6c0d-42d3-a5b0-7159783d1940)

This is my data structure:
```
[
    {
        "source": [
            {
                "inputText": "task3-  s1 No model registered for tag: repeater on CEX.IO’s Exchange Plus",
                "comment": "task3-t1"
            },
            {
                "inputText": "task3-s  s2   some Macs, link preload but not used within a few seconds from the window's  ",
                "comment": "task3-t2"
            },
            {
                "inputText": "task3-s 03  s3 have both GarageBand and the latest Toneb jweiwejirwi  ",
                "comment": "task3-t3"
            }
        ]
    }
]
```

I don’t know why this Repeater tag does not appear on the official website of the enterprise and non-enterprise or why it was removed. And I haven’t found its replacement tag.

Added: I am using the enterprise version, and the version information I see from the api/version interface is: "release": "2.20.0.dev8". Please let me know if you need additional information, I will be grateful for your help

**Comment by makseq** [comment]
Unfortunately, it's a bug in LS when you use Repeater with TextArea together: if you modify TextArea after Submit and then click Update, you will get duplicated text inputs. 

There is no alternative to the Repeater tag unfortunately. We have dropped official support for it because it is too complex to maintain; however, it still works. If you use Repeater, you should be aware of the following points:  
1. Avoid using it for more than 10-20 entities to repeat, as you will experience significant performance degradation in the browser.  
2. Agreement and other metrics (in the enterprise version of LS) will not work.  
3. You may encounter unexpected issues that could lead to labeling losses. Please test it thoroughly before the production labeling. 

if you are a starter cloud or enterprise customer, please address your question here: 
support.humansignal.com

**Comment by makseq** [comment]
After discussions with our frontend team, we found that you used a value in the TextArea. However, if you remove it, you will avoid having extra TextArea results after the update. There is a labeling config and a task sample that shows how you can use it:

```
<View>
 <Repeater on="$source" indexFlag="{{idx}}">
   <View style="display: flex;border-bottom: 1px solid gray;">
      <View style="flex: 50%;">
        <Text name="s_{{idx}}" value="$source[{{idx}}].text" />
      </View>
      <View style="flex: 50%;">
        <TextArea name="c_{{idx}}" 
                  editable="true" 
                  maxSubmissions="1" 
                  toName="s_{{idx}}" 
                />
      </View>
    </View>
 </Repeater>
</View>
```

Task data with prediction (to **preload** text to TextAreas):
```
{

  "data": {
    "source": [
      {
        "comment": "task3-t1",
        "inputText": "task3-  s1 No model registered for tag: repeater on CEX.IO’s Exchange Plus"
      },
      {
        "comment": "task3-t2",
        "inputText": "task3-s  s2   some Macs, link preload but not used within a few seconds from the window's  "
      },
      {
        "comment": "task3-t3",
        "inputText": "task3-s 03  s3 have both GarageBand and the latest Toneb jweiwejirwi  "
      }
    ]
  },
 
  "predictions": [
    {
      "id": 34671404,
      "result": [
        {
          "id": "qZ7SPvUImk",
          "type": "textarea",
          "value": {
            "text": [
              "test1"
            ]
          },
          "origin": "manual",
          "to_name": "s_0",
          "from_name": "c_0"
        },
        {
          "id": "XaKFaJR_sh",
          "type": "textarea",
          "value": {
            "text": [
              "test2"
            ]
          },
          "origin": "manual",
          "to_name": "s_1",
          "from_name": "c_1"
        },
        {
          "id": "y7z2EE3zdx",
          "type": "textarea",
          "value": {
            "text": [
              "test3"
            ]
          },
          "origin": "manual",
          "to_name": "s_2",
          "from_name": "c_2"
        }
      ],
      "model_version": "undefined"
    }
  ]
}
```

**Comment by mmmyjun** [comment]
> After discussions with our frontend team, we found that you used a value in the TextArea. However, if you remove it, you will avoid having extra TextArea results after the update. There is a labeling config and a task sample that shows how you can use it:
> 
> ```
> <View>
>  <Repeater on="$source" indexFlag="{{idx}}">
>    <View style="display: flex;border-bottom: 1px solid gray;">
>       <View style="flex: 50%;">
>         <Text name="s_{{idx}}" value="$source[{{idx}}].text" />
>       </View>
>       <View style="flex: 50%;">
>         <TextArea name="c_{{idx}}" 
>                   editable="true" 
>                   maxSubmissions="1" 
>                   toName="s_{{idx}}" 
>                 />
>       </View>
>     </View>
>  </Repeater>
> </View>
> ```
> 
> Task data with prediction (to **preload** text to TextAreas):
> 
> ```
> {
> 
>   "data": {
>     "source": [
>       {
>         "comment": "task3-t1",
>         "inputText": "task3-  s1 No model registered for tag: repeater on CEX.IO’s Exchange Plus"
>       },
>       {
>         "comment": "task3-t2",
>         "inputText": "task3-s  s2   some Macs, link preload but not used within a few seconds from the window's  "
>       },
>       {
>         "comment": "task3-t3",
>         "inputText": "task3-s 03  s3 have both GarageBand and the latest Toneb jweiwejirwi  "
>       }
>     ]
>   },
>  
>   "predictions": [
>     {
>       "id": 34671404,
>       "result": [
>         {
>           "id": "qZ7SPvUImk",
>           "type": "textarea",
>           "value": {
>             "text": [
>               "test1"
>             ]
>           },
>           "origin": "manual",
>           "to_name": "s_0",
>           "from_name": "c_0"
>         },
>         {
>           "id": "XaKFaJR_sh",
>           "type": "textarea",
>           "value": {
>             "text": [
>               "test2"
>             ]
>           },
>           "origin": "manual",
>           "to_name": "s_1",
>           "from_name": "c_1"
>         },
>         {
>           "id": "y7z2EE3zdx",
>           "type": "textarea",
>           "value": {
>             "text": [
>               "test3"
>             ]
>           },
>           "origin": "manual",
>           "to_name": "s_2",
>           "from_name": "c_2"
>         }
>       ],
>       "model_version": "undefined"
>     }
>   ]
> }
> ```

Thank you for your reply. I replied to your reply in gmail today. My reply contains some information of my company, so it is not convenient to make it public in github. You can reply to me through gmail.Thank you in advance
