### ISSUE TITLE
Error while building docker container for YOLO example in label studio ml backend

### ISSUE THREAD

**Issue by filippkabir** [heartexlabs/label-studio#6826]
Getting this kind of error while building  **ERROR [yolo stage-0  5/14] RUN conda install -c "nvidia/label/cuda-12.1.1" cuda -y**

**To Reproduce**
$/home/webmaster/label-studio-ml-backend/label_studio_ml/examples/yolo# docker compose up --build

**Screenshots**

- OS: Ubuntu 22.04
![2024-12-25_20-16-05](https://github.com/user-attachments/assets/8fb8a128-4ea5-4116-be3b-7fb7f7890572)

**Comment by makseq** [comment]
Please. get the latest commit from the master branch and try again, this problem should be fixed now.
