### ISSUE TITLE
Host CLI option not working

### ISSUE THREAD

**Issue by ADBurpitt** [heartexlabs/label-studio#688]
**Describe the bug**
I am attempting to serve label-studio from a sub-path, e.g. `example.com/label-studio`, but only receiving 404s.

**To Reproduce**
1. Run label-studio with the `--host` flag: `label-studio start --host http://localhost:8502/label-studio`
2. Go to http://localhost:8502/label-studio
3. 404 Page
4. Go to http://localhost:8502
5. Redirected to `/projects`, but page is blank

**Expected behavior**
The app to load.

**Screenshots**

![image](https://user-images.githubusercontent.com/14364646/111830805-613a5300-88e6-11eb-95b8-4e33830710e3.png)

**Environment:**
 - OS: Windows / Mac / Linux
 - Label Studio Version 1.0.0

Perhaps I am misusing the `--host` flag, from my understanding it should allow serving the app from a non-root base URL, any information or assistance would be much appreciated.

**Comment by makseq** [comment]
@ADBurpitt Do you use Nginx over Label Studio?

**Comment by makseq** [comment]
I think your nginx/other server over LS is configured incorrectly.

**Comment by ADBurpitt** [comment]
@makseq Thanks for the reply, apologies for not getting back to you sooner, was sick over the weekend/beginning of this week.

The above is running locally without any reverse proxy, which works fine without the `host` flag.
Does the use of the `host` flag mean a reverse proxy is necessary?

I have also been trying to deploy label-studio to a kubernetes environment, I have the app running both with and without nginx there:

https://ds.degreed.com/label-studio/ - no nginx

https://ds.degreed.com/label-studio/nginx - with nginx

Aside from the routing issues static files are served incorrectly also

Here's the nginx config:

```
server {
    listen       80;
    server_name  localhost;

    proxy_redirect          off;
    proxy_set_header        Host            $host;
    proxy_set_header        X-Real-IP       $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    client_body_buffer_size 128k;
    proxy_connect_timeout   90;
    proxy_send_timeout      90;
    proxy_read_timeout      300;
    proxy_buffers           32 4k;

    location /label-studio/ {
        proxy_pass http://localhost:8502;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location /label-studio/data/upload {
        alias /label-studio/data/media/upload/;
    }

    location /label-studio/data/avatars {
        alias /label-studio/data/avatars;
    }

    location /label-studio/static {
        alias /label-studio/label_studio/core/static_build/;
        add_header 'Access-Control-Allow-Origin' '*';
    }

    location /label-studio/label-studio-frontend {
        alias /label-studio/label_studio/frontend/dist/lsf;
    }

    location /label-studio/react-app {
        alias /label-studio/label_studio/frontend/dist/react-app;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

Label studio and nginx are running inside a single pod here, with nginx exposed at port 80 and label studio at port 8502.

Is there anything here that looks wrong? I tried to adapt the nginx config from this repo but I wouldn't be surprised if I made mistakes with that.

**Comment by makseq** [comment]
@ADBurpitt I hope you feel better! 

> Does the use of the host flag mean a reverse proxy is necessary?

If you want to use `https://ds.degreed.com/label-studio/` as your final path, it's necessary to use properly configured nginx.

Your nginx config looks like you are close to success. 

Maybe it's better to replace: 

```
server {
    listen       80;
    server_name  localhost;
```

=>

```
server {
    listen       80;
    server_name  ds.degreed.com;
```

**Comment by makseq** [comment]
It doesn't seem like a bug on our side, so I close this issue.

**Comment by ADBurpitt** [comment]
Thanks for the help, I've made some progress with the nginx stuff but still not fully working, will post on slack :)
