### ISSUE TITLE
OAuth Login Ability

### ISSUE THREAD

**Issue by MikeTrizna** [heartexlabs/label-studio#689]
**Is your feature request related to a problem? Please describe.**
I've been waiting eagerly for the user login system introduced in 1.0, but the way it was implemented will probably cause a lot of headaches. My organization does not allow hosting of webapps that implement their own registration/password management system, because they become targets for hacks.

**Describe the solution you'd like**
It would be great if Label Studio added the ability to let users login via OAuth2, or a similar system. It looks like LS 1.0 moved to Django, and it looks like there are several Django OAuth solutions, although I don't know enough to recommend one. Specifically, I am interested in allowing users to log in with GitHub accounts.

**Describe alternatives you've considered**
Honestly, I would have to avoid upgrading to version 1.0, or direct users to local installs.

**Comment by makseq** [comment]
@MikeTrizna Could you clarify a little: why you would have to avoid upgrading to v1.0? The previous versions haven't login at all..

**Comment by MikeTrizna** [comment]
Good question, @makseq. The main sticking point is that we are not allowed to store passwords. Even though it looks like the sqlite database does at least store hashed versions of user passwords, the fact that we're storing those would cause a security flag.

If there was a way to make login optional, that would also allow us to upgrade to v1.

**Comment by makseq** [comment]
@MikeTrizna You can try to use one account per all users, something like `team / 12345678` :slightly_smiling_face: 
Is it a problem in passwords only? Or username is a problem too?

**Comment by MikeTrizna** [comment]
Yep, unfortunately it is a problem specifically with having any kind of password.

In an OAuth-style login system, I believe you would still need to store the usernames -- but the password storage/reset mechanisms, etc. are all farmed out to someone else.

**Comment by makseq** [comment]
In this case you can skip password checks, I think we can implements it very easy.

**Comment by MikeTrizna** [comment]
That would be great!

Would you like me to create a new separate Issue? It might make sense to keep this OAuth feature request, although it's a lower priority for me.

**Comment by makseq** [comment]
It's better to create a PR :) 

You need to modify this line:
https://github.com/heartexlabs/label-studio/blob/master/label_studio/users/forms.py#L44

to something like this:  

```
user = User.object.find(username=username)
if not user.exists():
  raise ValidationError('No such user; {username}')
user = user.first()
```

And it would be ideal if we could have env var in base.py (use `get_env('VAR_NAME')`) like `LOGIN_SKIP_PASSWORD_CHECK`.

**Comment by MikeTrizna** [comment]
Sure thing. It will probably take the weekend to wrap my head around how everything works together, but your suggestions helps a lot.

**Comment by makseq** [comment]
We decided to leave this OAuth only for Label Studio for Teams and we are not planning to implement it now.

**Comment by frafra** [comment]
Would you accept a PR implementing OAuth2?
