### ISSUE TITLE
How to import pre-labeled data?

### ISSUE THREAD

**Issue by mirfan899** [heartexlabs/label-studio#694]
I've labeled the data in my project. After exporting the data how can I use it for another project?

**Comment by smoreface** [comment]
Do you want to use the data for another project in Label Studio? If so, please see this document: https://labelstud.io/guide/predictions.html

**Comment by mirfan899** [comment]
It does not pick the labeled annotations. It just import the file and shows nothing.

**Comment by mirfan899** [comment]
Also, my files are in VOC format.

**Comment by smoreface** [comment]
@mirfan899 Please try uploading a JSON file with the predicted annotations. Export to VOC format is supported but to import pre-annotations you need to use the Label Studio JSON format.

**Comment by mirfan899** [comment]
Okay, thanks.
