### ISSUE TITLE
Add item tagging and tag filtering

### ISSUE THREAD

**Issue by potipot** [heartexlabs/label-studio#696]
I think it would be beneficial to have dataset tagging included. For example, I have my dataset split in train validation and test. While loading it from different folders it always ends up mixed altogether in a single tree. The only way to filter them now is using name regex.

Also the data folders structure isn't preserved when importing and files get copied to the internal `/upload` catalogue but I guess this is something that is going to be fixed in 1.0.1 with local file storage.

**Comment by makseq** [comment]
Please check this PR: 
https://github.com/heartexlabs/label-studio/pull/2558

Now you are able to create new fields in task data and assign string, float or even expressions there. This allow to split your data set or assign some labels to the specific tasks.
