### ISSUE TITLE
The displayed waveform and audio cannot be corresponding when dealing with long audio file

### ISSUE THREAD

**Issue by wanderin-earth** [heartexlabs/label-studio#699]
Hello!

I meet a problem using label-studio. When I import long audio file (about 25-min long, 25MB), the displayed waveform and audio cannot correspond to each other after I adjust the zoom axis below the timeline. But after I compress the audio file by adopting lower bit rate, the issue gets solved.

So I wonder why this problem emerges, and by the way, would there be any other problem if I compress the audio file?

Thank you very much for your help!

**Comment by makseq** [comment]
@wanderin-earth Could you send us an example of source audio and converted audio?

**Comment by wanderin-earth** [comment]
> @wanderin-earth Could you send us an example of source audio and converted audio?
> I think there won't be other problem if you use compressed audio.

I've sent you the files by email. Thanks!

**Comment by makseq** [comment]
@wanderin-earth Could you check the master branch of LS now, I hope we've fixed this issue (in this PR https://github.com/heartexlabs/label-studio/pull/806)
