### ISSUE TITLE
random order of data for each annotator & not showing other annotators' decisions to annotators

### ISSUE THREAD

**Issue by fatihbeyhan** [heartexlabs/label-studio#702]
Hi,

I am creating a project and multiple annotators can sign up and check my project to annotate some data.
I would like to show the data to each annotator in different order. And when an annotator opens a sample to annotate, he/she has to click on the "new annotation" button to create his/her own annotation for that sample and he/she can see the previous annotations of other annotators so their decision can be biased.

How can I show data to each annotator in different order and prevent them to see other annotators decisions?

**Comment by makseq** [comment]
@fatihbeyhan Hi, it looks like different role mechanics, but LS supports only one admin role for all users. 
You can deep into codes and modify them to show limited annotations: https://github.com/heartexlabs/label-studio/blob/master/label_studio/tasks/serializers.py#L117
Also we have an advanced roles & permissions in our enterprise solution.

**Comment by makseq** [comment]
@fatihbeyhan 
> data to each annotator in different order
Do you mean order on Label button click? (Label stream)

**Comment by niklub** [comment]
Hi, @fatihbeyhan ! 
Currently, if you want to randomize show order for your annotators, you can tweak the project settings parameter via project API `PATCH /api/projects/<pk>` with the data payload like this `{"sampling": "Uniform sampling"}`. We will make it handier in the near future

**Comment by fatihbeyhan** [comment]
That is not exactly "random" actually. I tried it. First annotator will see the samples in a random order however second annotator will see the samples in the same order first annotator did. Therefore, I forked and changed the code a bit and achieved the random order for each annotator, with the help of one of your devs in Slack group (Thank you Nikolai Liubimov!).

I would like to suggest to put this as a feature. I would also suggest to put another feature. Annotators should label the data totally independent of each other. In this version, annotators can see the annotations of others. I am using your platform for academic purposes and we hire some undergrad students for labelling. I would like them to annotate the same data without being biased with others' annotations. If they use the Label button on the top right corner, they will not see any annotation of previous annotators, yet, this could be an optional feature, too.

Thank you for your help!

**Comment by makseq** [comment]
@fatihbeyhan I'd suggest you to split your tasks into different tabs based on non-intersected task ids. One tab per annotator. In this case they will be strongly separated among annotators.

**Comment by makseq** [comment]
In the Label Studio for Teams / Enterprise there are presented options that can be used to force tasks to appear in a completely random order. You have to enable `Uniform Sampling` and disable `Show tasks with ground truth labels first` + `Show tasks with overlap first` to achieve this. 
![image](https://user-images.githubusercontent.com/501780/136121275-763d8af7-a3f5-4ff2-ba6a-5d5db9f49823.png)
