### ISSUE TITLE
typo on documentation

### ISSUE THREAD

**Issue by dkalaitzidis** [heartexlabs/label-studio#704]
On Install and Upgrade and more specific on the PostgreSQL database you have `--db postgresql` instead of `-db postgresql`

**Comment by makseq** [comment]
@dkalaitzidis you are right! Thanks! 
@smoreface :smile:

**Comment by makseq** [comment]
@smoreface Please, close this issue after fixing a typo.

**Comment by svetlana21** [comment]
Hello! I noticed a small problem in the docs that doesn't deserve a new issue I guess.
At the page [Import pre-annotated data into Label Studio](https://labelstud.io/guide/predictions.html) an image isn't displayed:

![image](https://user-images.githubusercontent.com/21115815/112281764-ffe4fc00-8cb8-11eb-9089-1b7b16b1f869.png)

**Comment by makseq** [comment]
@smoreface check it please!

**Comment by smoreface** [comment]
Yup, thanks @svetlana21, this is fixed in the same branch and PR as the typo :)
