### ISSUE TITLE
Label Studio support for Kubernetes installations

### ISSUE THREAD

**Issue by Atharex** [heartexlabs/label-studio#711]
**Is your feature request related to a problem? Please describe.**
Would be great if Label Studio could support a Kubernetes native installation, where it would not need SQLite for initialization and a follow-up migration to Postgresql. Also that it would support specifying the DB connection details during run-time instead of build time (like I guess the docker-compose example is currently doing)

**Describe the solution you'd like**
Either a configurable manifest or a Helm Chart to enable best-practices installation of Label Studio on Kubernetes

**Comment by farioas** [comment]
Hi @Atharex,

The change for kustomize was prepared by the community: https://github.com/heartexlabs/label-studio/pull/1067, once it ready, we will merge it into the mainstream.
