### ISSUE TITLE
Unable to sync S3 storage with prefix

### ISSUE THREAD

**Issue by SNeugber** [heartexlabs/label-studio#712]
**Describe the bug**
I'm trying to import images from an S3 bucket as described in the documentation here: https://labelstud.io/guide/storage.html#Amazon-S3

If syncs fine when I don't add a prefix to the setup, but with the prefix it just returns immediately with a "0 tasks synced" message.

Only caveat here is that it's S3-like storage (not AWS), but so far I've not had any issues accessing it with boto3 before.

**To Reproduce**
1. Set up S3 storage as in the docs.
2. Make sure to specify a prefix.
3. Click "sync"

**Expected behavior**
Sync images from S3 storage

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10, running from source in conda environment with python 3.7
 - Label Studio Version 1.0 from master (commit at time of submitting this issue is 4117e2def96d02e50fa4a413854ac89e146205e3)

**Additional context**
N/A

**Comment by niklub** [comment]
Hi, @SNeugber ! Have you tried to play with the trailing slash in your prefix?

**Comment by SNeugber** [comment]
Just checked, the issue persists with and without the trailing slash

**Comment by makseq** [comment]
This issue was fixed somewhere in LS 1.1 - 1.2.
