### ISSUE TITLE
Filtering based on numeric value is not working

### ISSUE THREAD

**Issue by dkalaitzidis** [heartexlabs/label-studio#716]
**Describe the bug**
I'm trying to filter records based on a numeric score value, but it's not working. I've included a screenshot with the results.

**To Reproduce**
1. Go to Filters
2. Apply a greater by / less by filter.

**Expected behavior**
Filter the results based on the numeric value.

**Screenshots**
https://imgur.com/a/Hdk9G3J

**Environment (please complete the following information):**
 - OS: MacOS
 - Label Studio Version 1.0.0.post3

**Comment by makseq** [comment]
Fixed in this PR: https://github.com/heartexlabs/label-studio/issues/716 
Also it will be included into LS 1.0.2 very soon.

**Comment by niklub** [comment]
This issue has been fixed in the `label-studio==1.0.2` version
