### ISSUE TITLE
 cannot import name 'LabelStudioMLBase' from 'label_studio.ml'

### ISSUE THREAD

**Issue by abu2wu** [heartexlabs/label-studio#717]
https://labelstud.io/tutorials/sklearn-text-classifier.html
I tried to follow the steps linked above, type label-studio-ml init my_backend in CMD, and get this error.
cannot import name 'LabelStudioMLBase' from 'label_studio.ml'

**Comment by abu2wu** [comment]
To build my own machine learning backend, I need to write two scripts, right? Corresponds to _wsgi.py and simple_text_classifier.py in the example

**Comment by makseq** [comment]
@abu2wu 
1. Label Studio ML backend was moved to a new repository: https://github.com/heartexlabs/label-studio-ml-backend , you need to install it separately. 
2. You have to write simple_text_classifier.py only and then run `label-studio-ml init --script simple_text_classifier.py`

**Comment by niklub** [comment]
Hi, @abu2wu ! Please feel free to reopen the issue if you still have not succeeded to run the ML backend
