### ISSUE TITLE
Add parameters "required" and "choice" to Taxonomy

### ISSUE THREAD

**Issue by svetlana21** [heartexlabs/label-studio#718]
**Is your feature request related to a problem? Please describe.**
Taxonomy control tag is great for a long list of labels. I have a Taxonomy that is only visible when a specific checkbox is selected, but I want the Taxonomy label to be required for submission when the checkbox is selected. Besides I want the only one label from list to be selected, but now the multiple choice is default.

**Describe the solution you'd like**
Add parameters "required" and "choice" to Taxonomy

**Describe alternatives you've considered**
Some universal validation of any fields before submission

**Additional context**
Is there some way to solve my problem using existing tools?

**Comment by makseq** [comment]
Looks like these features were added near the release 1.2. 
You have to look at `leafsOnly`, `maxUsages` and `required` fields: https://labelstud.io/tags/taxonomy.html.
