### ISSUE TITLE
Multi-Template Labeling, Data Export

### ISSUE THREAD

**Issue by dalekube** [heartexlabs/label-studio#719]
When using a custom-coded template that includes multiple sections (i.e. taxonomy and sentiment classification), the export feature only provides a limited subset of the total data that is saved in the underlying 'task_completion' table in the SQLite database. When there are multiple annotations for the same task, the export only provides one of the annotations (looks like it provides the most recent annotation). The export—considering all file formats—does not provide all annotations.

Label Studio Version 1.0.0.post3

![interface](https://user-images.githubusercontent.com/12777137/112494347-f4ddaa80-8d50-11eb-9260-acf70593c205.PNG)

**Comment by makseq** [comment]
@dalekube  Could you check release/1.0.1 branch? I hope it is fixed there.

**Comment by dalekube** [comment]
@makseq, yes I can check this in the next couple days and follow up here. Thanks! I apologize for the delay.

**Comment by dalekube** [comment]
I upgraded to the latest version (v1.0.1) and confirmed this problem is resolved. Thanks!
