### ISSUE TITLE
404 GCS Annotation/Completion Sync

### ISSUE THREAD

**Issue by ThePianoDentist** [heartexlabs/label-studio#727]
**Describe the bug**
Google-cloud target storage is 404'ing on sync (and annotated tasks do not seem to be using the bucket)

**To Reproduce**
- On `projects/1/settings/storage` add a target cloud storage for gcs bucket
- Click "Sync Storage"
- See attached screenshot

**Expected behavior**
To sync completions. No 404.

**Screenshots**
![image](https://user-images.githubusercontent.com/17036692/112634345-65a8c380-8e32-11eb-827c-9527baa8febf.png)

**Environment (please complete the following information):**
- running in docker, built FROM heartexlabs/label-studio:1.0.0 
- hosted on google-cloud (saw same behaviour running docker locally)
- Browser UA: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0

**Additional context**
404s on POST request to `https://<domain>/api/storages/export/gcs/1/sync` (the request payload/body is empty [i.e. `{}` as it's JSON)

info in db:
```
sqlite> select * FROM io_storages_gcsexportstorage;
1|||2021-03-25 17:03:27.942944|1||
3|test||2021-03-26 10:11:16.562007|1||

sqlite> select * FROM io_storages_gcsexportstoragelink;

sqlite> select * FROM io_storages_gcsstoragemixin;
1|completions-bucket-name-1|myprefix||0
2|tasks-bucket-name-1||.*.mp4|1
3|completions-blocking-name2|||0
```

Note: 1st bucket didn't work. So tried a 2nd bucket, also didn't work.
Error seems to occur regardless of name/prefix settings.
Tasks sync perfectly fine.
(Noticed that when I edit an existing target gcs storage to "remove" prefix, and replace with blank, this doesn't persist. Maybe be unrelated)

**Comment by niklub** [comment]
@ThePianoDentist ,
This has been fixed in all versions since 871ce69c8f544025471ed4825b667e3b330656a3 Please update to the `heartexlabs/label-studio:latest`, or the latest git master, or `pip install label-studio==1.0.0.post3` and reopen the issue if the problem will persist
