### ISSUE TITLE
Hosts with base URL's do not work with label-studio

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#728]
**Describe the bug**
When using the option `--host` argument  with a base URL, for example the one shown in the label-studio argument help  `--host "http://ls.domain.com/subdomain/"`,  href's with absolute paths (those starting with"/") break and make label-studio unusable.  URL's  should all be changed to relative paths when using `base href` html tag (either remove leading "/" or add start with "./").
 
This issue keeps cropping up in new releases and has been discussed before in issues https://github.com/heartexlabs/label-studio/issues/358 and https://github.com/heartexlabs/label-studio/issues/507

**Locations**
- Some of these are hard coded for example in https://github.com/heartexlabs/label-studio/blob/03851cadadc2eb288e0f866adc35842817367c57/label_studio/users/templates/users/user_login.html  
-- `href="/user/signup"` 
-- `href="/user/login"`
-- `img src='/static/images/opossum_hanging.svg"`
- Other appears to be dynamically generated  on most pages with
-- `{% load static %}` and `<link rel="stylesheet" href="{% static 'css/login.css' %}"/>` resulting in `href="/static/css/login....css"`
-- I do not know the proper js to fix this, but the end results should be `href="./static/css/login....css"` or maybe prepend the "host" argument to the "static" variable?

**To Reproduce**
Steps to reproduce the behavior (it would be great if this could be added as a test case):
1. `docker run -it -p 8080:8080 heartexlabs/label-studio:latest label-studio --host "http://ls.domain.com/subdomain/"`
2. **Notice how `<a href="/user/signup">Sign up</a>` resolves to  http://ls.domain.com/user/signup, but it should resolve to http://ls.domain.com/subdomain/user/signup.**  This would be corrected with `<a href="./user/signup">Sign up</a>` when `<base href="http://ls.domain.com/subdomain/">` is in the `<head>` html tag.
3. To simulate a subdomain environment,  it may be useful to add the line `127.0.0.1 ls.domain.com` to /etc/hosts (have not tested this)

**Comment by makseq** [comment]
@nicholasrq check this please in frontend part.

**Comment by makseq** [comment]
@laynr Could you check `pip install label-studio==1.0.1rc1` please? I hope it's fixed there.

**Comment by laynr** [comment]
> @laynr Could you check `pip install label-studio==1.0.1rc1` please? I hope it's fixed there.

@makseq in attempting to verify this fix I discovered https://github.com/heartexlabs/label-studio/issues/763

**Comment by laynr** [comment]
@nicholasrq / @makseq  There are still some web page errors in the 1.0.1 release.  For example the css and images are still NOT using relative paths.

For example this line of code:
https://github.com/heartexlabs/label-studio/blob/e50c16f096a7383147d2289f324cf28990336066/label_studio/users/templates/users/user_signup.html#L9
resolved to  `<link rel="stylesheet" href="/static/css/login.<some number>.css"/>` when  viewing the source of the rendered webpage. If it resolved to `<link rel="stylesheet" href="./static/css/login.<some number>.css"/>` I believe it would work.

Similarly this line of code:
https://github.com/heartexlabs/label-studio/blob/e50c16f096a7383147d2289f324cf28990336066/label_studio/users/templates/users/user_signup.html#L26
resolved to  `<img src="/static/images/opossum_hanging.<some number>..svg` when  viewing the source of the rendered webpage. If it resolved to `img src="./static/images/opossum_hanging.<some number>..svg` I believe it would work.

However, lines of code that were updated with `{ settings.HOSTNAME }}/` like the following worked!!
https://github.com/heartexlabs/label-studio/blob/e50c16f096a7383147d2289f324cf28990336066/label_studio/users/templates/users/user_signup.html#L29
https://github.com/heartexlabs/label-studio/blob/e50c16f096a7383147d2289f324cf28990336066/label_studio/users/templates/users/user_signup.html#L30

Worrying after creating an account, and clicking the "Log in" button  the projects page is blank/all white (not rendered at all, but view source does show html) .  All the `href`, `src`, and `base href` appear correct.  Maybe the java script files need to be changed (I don't know)?
