### ISSUE TITLE
Filename is hashed 

### ISSUE THREAD

**Issue by lchunleo** [heartexlabs/label-studio#729]
After use , I noted that the original filename of image when imported into the studio for labelling r hashed. And the resulting annotation will contain the hashed filename  Is it possible to disable or able to track this information ? Thank you

**Comment by makseq** [comment]
@lchunleo It's not possible to disable hashes in uploaded filenames because of security reasons. Also if you upload two different files with the same names, the first one will be replaced by the second. However, the original part of your file name will be saved at the beginning of the filename. 

What do you mean by "track this information"?

**Comment by lchunleo** [comment]
> @lchunleo It's not possible to disable hashes in uploaded filenames because of security reasons. Also if you upload two different files with the same names, the first one will be replaced by the second. However, the original part of your file name will be saved at the beginning of the filename.
> 
> What do you mean by "track this information"?

Thanks for the reply. "Track this information" refers to maybe a file that contains the mapping of the original filename and the hashfilename. 

May i understand the "security reasons" for the design? My intent to keep the filename is to able to trace back which files are used in the annotation if the file source is no longer available.

**Comment by makseq** [comment]
@Ichunleo 
https://github.com/heartexlabs/label-studio/pull/1426 
Sorry for fix, but hope this helps. Now filename are - <project_id>-<hash>-<original_filename>.

**Comment by NguyenVanThanhHust** [comment]
For those who don't want to use hash ( to track files), you can change the line: https://github.com/HumanSignal/label-studio/blob/6580f1a35c02e86949c74fd9e45afb6a584d72a6/label_studio/data_import/models.py#L27

Hash part is: `str(uuid.uuid4())[0:8]`

**Comment by MassEast** [comment]
Keep in mind here also that the filename is automatically shortened by label studio. I was about to compare my labelling results with those of friends, and not only were our hashes different, but also the image path names. Now we have to go back and create translation tables between our different filenames exported from label studio...
