### ISSUE TITLE
Error when re-import an exported json file

### ISSUE THREAD

**Issue by lhtrieu87** [heartexlabs/label-studio#731]
Face error when importing the exported JSON file

**To Reproduce**
1. Go to a project
2. Export using JSON format
3. Go to the same project OR a new empty project
4. Import the JSON file exported in the step 2

**Expected behavior**
Can import the JSON file successfully

**Screenshots**
![Screenshot from 2021-03-29 17-03-00](https://user-images.githubusercontent.com/2397432/112813322-a9106580-90b0-11eb-8353-9d59a44b2e64.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version: 1.0.0.post3

**Additional context**

**Comment by makseq** [comment]
@lhtrieu87 Thank you for your report, it was fixed in release/1.0.1 branch.
https://github.com/heartexlabs/label-studio/pull/681
