### ISSUE TITLE
Prediction of tasks with BrushLabels

### ISSUE THREAD

**Issue by cbwchuck** [heartexlabs/label-studio#732]
Hi! I am trying to implement a ml backend for Semantic Segmentation with Masks project in LS v1.0.0. And I am wondering what I should return from the server side. I saw in the export json file that the result is RLE encoded, do I need to do the same for the prediction?

**Comment by makseq** [comment]
Hi! Yes, you need to build your mask in the RLE format.

We have some prepared codes that could help you:
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/brush.py#L305

**Comment by cbwchuck** [comment]
@makseq Thanks for the help! I had some tries today but still couldn't get the pre-annotation right. Below is my predict function

```python
import cv2
from brush import mask2rle
from mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
from mmseg.core.evaluation import get_palette

def predict(self, tasks, **kwargs):
    results = []

    for task in tasks:

        ### some download image logic ###

        img_width, img_height = get_image_size(image_cache_dir + img_name)
        model_results = inference_segmentor(self.model, image_cache_dir + img_name)
        unique_labels = np.unique(model_results[0])

        for label in unique_labels:
            binary_mask = (model_results[0] == label) # get binary mask of current label
            binary_mask = binary_mask.astype(np.uint8)
            binary_mask *= 255
            contours, hierarchy = cv2.findContours(binary_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
            
            for index in range(len(contours)): # append each pre-annotated object to result
                rle_strs = mask2rle(contours=contours, contour_id=index, img_width=img_width, img_height=img_height)
                results.append({
                    'from_name': self.from_name,
                    'to_name': self.to_name,
                    'type': 'brushlabels',
                    "original_width": img_width,
                    "original_height": img_height,
                    "image_rotation": 0,
                    'value': {
                        'format': "rle",
                        "rle": rle_strs
                    },
                    "brushlabels": [self.labels[label]],
                })
        ...
```

And this is the image shown in the frontend
![image](https://user-images.githubusercontent.com/25662762/113012637-8748d880-91ad-11eb-80ce-4b9ef5d0c6b8.png)

Web console throws some warnings
![image](https://user-images.githubusercontent.com/25662762/113012742-a21b4d00-91ad-11eb-9795-d5530af30cb1.png)

And when I click a region in Regions panel, the page crashes with some errors prompted in the web console
![image](https://user-images.githubusercontent.com/25662762/113013029-eb6b9c80-91ad-11eb-9ffe-cdb56cf8158b.png)

I am thinking there could be errors in my code and the masks I pass to frontend are wrong. Could you kindly have a look at it?

Thanks in advance!

**Comment by makseq** [comment]
@cbwchuck Thank you very much for sharing your codes. 
I think it's better to pass into RLE converter a `binary_mask`, instead of contours, use `encode_rle` from here:
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/brush.py#L177

Prepare your mask as follow (I don't know your `model_results.shape`, so it could be something like this): 
```
mask = np.zeros((img_width, img_height, 4), dtype=int)
mask[:, :, 0:4] = (model_results[0] == label) * 255
rle_out = encode_rle(mask)
```

**Comment by cbwchuck** [comment]
@makseq Much appreciated :)! I have updated my code and the colours of pre-annotated image seem right now!

```python
import cv2
import numpy as np
from brush import encode_rle
from mmseg.apis import init_segmentor, inference_segmentor, show_result_pyplot
from label_studio_ml.utils import get_image_size
from mmseg.core.evaluation import get_palette

def predict(self, tasks, **kwargs):
    results = []

    for task in tasks:

        ### some download image logic ###

        img_width, img_height = get_image_size(image_cache_dir + img_name)
        model_results = inference_segmentor(self.model, image_cache_dir + img_name)
        unique_labels = np.unique(model_results[0])

        for label in unique_labels:
            binary_mask = (model_results[0] == label) # get binary mask of current label, of shape 1080, 810
            mask = np.zeros((img_height, img_width, 4), dtype=int)
            for h in range(img_height):
                for w in range(img_width):
                    if binary_mask[h][w] == True:
                        mask[h][w][:4] = self.palette[label] + [100] #  r, g, b, a of current label

                    rle_strs = encode_rle(mask.flatten())

                    results.append({
                        'from_name': self.from_name,
                        'to_name': self.to_name,
                        'type': 'brushlabels',
                        "original_width": img_width,
                        "original_height": img_height,
                        "image_rotation": 0,
                        'value': {
                            'format': "rle",
                            "rle": rle_strs
                        },
                        "brushlabels": [self.labels[label]],
                    })
        ...
```

![image](https://user-images.githubusercontent.com/25662762/113084892-79c53a00-9211-11eb-9ba9-463dddb730de.png)

It takes around 3 minutes for the browser to render the page (backend process time not included), and the same errors occurred when I click a region in the Regions panel. Besides, no region is attached with label as passed in the code.

![image](https://user-images.githubusercontent.com/25662762/113085502-85fdc700-9212-11eb-9c34-b1f4135ad824.png)

Please let me know if there are more improvements I could make to my code for solving these issues!

Thanks for the big help 😄!

**Comment by makseq** [comment]
@cbwchuck what is your image resolution?

**Comment by cbwchuck** [comment]
@makseq It's 1280x720

**Comment by cbwchuck** [comment]
@makseq Hi! Any update on label region loss issue?

**Comment by makseq** [comment]
I think we need improve the brush performance. Right now you can try to remove some layers that cover the most parts of the image, it will make RLE not so heavy.

**Comment by cbwchuck** [comment]
@makseq Thanks a lot for all the help! I just updated the code in my previous answer to solve the label not shown issue. Looking forward to the optimised version!

**Comment by makseq** [comment]
Thank you very much for your reports!

**Comment by silverlining21** [comment]
Hi @cbwchuck，I‘m trying to implement image segmentaion backend. but I dont kown the exactly format of prediction. here is my code, could you give me some hints, thanks a lot.

```python

    def predict(self, tasks, **kwargs):
        assert len(tasks) == 1
        task = tasks[0]
        image_path = get_image_local_path(task['data'][self.value], project_dir=self.project_path)
        classes, scores, boxes, masks = inference_segmentor(self.model, image_path)
        results = []
        all_scores = []
        img_width, img_height = get_image_size(image_path)

        for c, s, b, m in zip(classes, scores, boxes, masks):
            cat = cfg.dataset.class_names[c]

            if cat not in map(str.lower, self.labels_in_config):
                continue
            rle_str = self._encode_mask(cat, m)
            results.append({
                'from_name': self.from_name,
                'to_name': self.to_name,
                'type': 'brushlabels',
                "original_width": img_width,
                "original_height": img_height,
                "image_rotation": 0,
                'value': {
                    "brushlabels": [cat],
                    "format": "rle",
                    "rle": rle_str
                },
                'score': s
            })
            all_scores.append(s)

        return [{
            'result': results,
            'score': sum(all_scores) / len(all_scores)
        }]
```

Frontend  log:
![image](https://user-images.githubusercontent.com/8264748/115395233-3bbaa500-a216-11eb-8a3b-667536f1b946.png)

**Comment by cbwchuck** [comment]
Hi! @silverlining21

It seems that your frontend logs does not provide enough info, will it be possible for you to run your ml backend in debug mode with following command and show the backend log instead?

`label-studio-ml start <BACKEND_NAME> -d --log-level DEBUG`

**Comment by silverlining21** [comment]
Hi  @cbwchuck , thanks for timely help. Here are the logs:

ml backend log produced by `label-studio-ml start <BACKEND_NAME> -d --log-level DEBUG`:
![image](https://user-images.githubusercontent.com/8264748/115641839-79b9e500-a34c-11eb-8086-d1ee5a66cf3d.png)

label-studio frontend log produced by `label-studio start my_project --init  --ml-backends http://localhost:9090  --log-level DEBUG>`:

![image](https://user-images.githubusercontent.com/8264748/115641672-26e02d80-a34c-11eb-9668-fb7f2ae6ebd9.png)

**Comment by silverlining21** [comment]
Supplementary，`label-studio` `label-studio-ml` services are both running in the same docker, which proxy `http://192.168.8.156:10081` was configed.  (I doubt if the connection probelm caused by it??, but not famliar with network issues so I'm not sure about it)

And docker ports  8080 and 9090 are exposed to the host, here is my cmd start docker:
`docker run --gpus 0 -p 8822:22 -p 8080:8080 -p 9090:9090 --shm-size 16G -v `pwd`/mydata:/localfiles --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true  -it ls/ml.backend`

**Comment by cbwchuck** [comment]
Hi @silverlining21!

From your first screenshot, it is strange that there is no error raised from the backend? Did the backend kill itself? If this is the case, I am wondering it might be helpful if you could add some print() in the predict() function so that we could better identify where the issues occurred?
