### ISSUE TITLE
Scaling of images

### ISSUE THREAD

**Issue by rahulchetlangia** [heartexlabs/label-studio#733]
Hello Team,

does this tool do any kind of scaling while tagging the images? 
when i see the coordinates of the bounding boxes and also try to validate that with MS paint pixels - i see a different values. 
Kindly clarify this doubt.

thanks in advance.

**Comment by makseq** [comment]
@rahulchetlangia Hello, LS uses percent format for coordinates. It means all x and y points have coordinates from 0% to 100% of original image width and height. 

I think you will find helpful this link:
https://labelstud.io/guide/export.html#Units-of-exported-image-annotations
