### ISSUE TITLE
Reusing labels for NER

### ISSUE THREAD

**Issue by FelipeCrispim** [heartexlabs/label-studio#735]
Hello,

When I import a csv file with labeled data, I cannot change entities for previously annotated labels from other projects.
Is there a way to be able to reuse labels from another project?

Thank you in advance.

**Comment by niklub** [comment]
Hi, @FelipeCrispim ! Do you mean that your labels from previous projects are different from what you specify in the current labeling config ?

**Comment by niklub** [comment]
Thanks, indeed, that's a good feature we plan to add (not specifically for text span but for any annotation regions)

**Comment by FelipeCrispim** [comment]
Hi @niklub, yes. I would really appreciate that. 
Thanks again and great tool!

**Comment by makseq** [comment]
Similar #181

**Comment by makseq** [comment]
Now you can import tasks with labels are not presented in the labeling config. They won't have a label and will be grey. After import, you will be able to change label according to the current labels from the labeling config.
