### ISSUE TITLE
Ability to edit starting number of catergory IDs.

### ISSUE THREAD

**Issue by jthaloor** [heartexlabs/label-studio#737]
When you perform a COCO export of a obj. detection use case, the default behavior is to start with category IDs with "0". This works well if you are training a model from scratch, but with transfer learning, it is problematic. In many models, "0" is considered the background and every other objects needs be > 0. Currently there is no way to setup the category IDs when exporting so it is a manual process (in code) to change the object IDs. 
It would be great if this ability, to change category IDs, is added to the settings UI or in the exports UI.

**Comment by makseq** [comment]
@jthaloor
Could you check this PR? Hope it's fixed your problem.
https://github.com/heartexlabs/label-studio-converter/pull/50/

**Comment by makseq** [comment]
This issue was fixed in the latest versions of label-studio-converter.

**Comment by TrueWodzu** [comment]
@makseq How this has been fixed? How can we configure ID for each class? I have similar problem for YOLOv5 export.

**Comment by makseq** [comment]
Try to use category in Label tag, e.g.: 

```
<Label category="123">
```

https://github.com/heartexlabs/label-studio-converter/pull/50/files#diff-322ce95b5aa5f02fb330c7f62be1ea0066c01829b564db0644872e09338a3ddfR745

**Comment by makseq** [comment]
Related:
https://github.com/heartexlabs/label-studio/issues/3653
https://github.com/heartexlabs/label-studio/issues/3324
https://github.com/heartexlabs/label-studio/issues/2886
https://github.com/heartexlabs/label-studio/issues/1115
https://github.com/heartexlabs/label-studio/issues/737
