### ISSUE TITLE
Protect project and set default privileges for newly registered contributors to labeling project and set user groups (admin, contributor)

### ISSUE THREAD

**Issue by BlkPingu** [heartexlabs/label-studio#742]
**Is your feature request related to a problem? Please describe.**

I can't find an option to protect the project. Every user that registers can also delete a project. I want to publicly post the project and don't want contributors to do be able to do anything else than labeling.

**Describe the solution you'd like**

Add a way to manage user privileges.

**Describe alternatives you've considered**

Not using label studio and building my own website to label the data with said feature included.

**Additional context**

None.

**Comment by BlkPingu** [comment]
cc @cvqluu

**Comment by makseq** [comment]
These features are available in our Team and Enterprise editions at app.heartex.com.
