### ISSUE TITLE
Intelligent interactive segmentation labelling through deep learning models

### ISSUE THREAD

**Issue by juan57** [heartexlabs/label-studio#756]
**Is your feature request related to a problem? Please describe.**
Semantic segmentation labelling takes a long time to individually paint all the pixels of all the different classes using a simple brush painter. If we could incorporate interactive intelligent labelling functionality, that would be awesome.

**Describe the solution you'd like**
Either a implemented interactive segmentation option, or the availability of a pipeline for users to be able to implement their own.
![fbrs_interactive_demo](https://user-images.githubusercontent.com/31523812/113602675-e3c65080-9610-11eb-8e27-5dfe97a85256.gif)
This would involve, for each class, an option to "paint" a portion of the scene as a positive or negative label wrt a single class.
Once selected, the backend would take the image and the user input, generate pixel predictions and return back the mask result.

**Comment by makseq** [comment]
The support for this feature is realized in LS 1.3 and the latest ML backend.
