### ISSUE TITLE
Two click bounding box annotation option

### ISSUE THREAD

**Issue by suvojit-0x55aa** [heartexlabs/label-studio#757]
**Is your feature request related to a problem? Please describe.**

Having to hold and drag the mouse during bounding box annotation can be a bit jarring specially if zoom level is not set correctly.

**Describe the solution you'd like**

An option to use two click bounding box drawing where user will click on two diagonal points  of the bounding box.

**Comment by makseq** [comment]
This bug was fixed in [release/1.1.0](https://github.com/heartexlabs/label-studio/tree/release/1.1.0). Feel free to reopen if you have this problem again.
