### ISSUE TITLE
Issues while Hosting label-studio in a remote ubuntu server

### ISSUE THREAD

**Issue by athulprathap** [heartexlabs/label-studio#760]
**Describe the bug**
Tried to host the app in an ubuntu -18 remote machine. Looks like most of the inside settings are configured to run the app in localhost.
Request documentation on how to configure server IP instead of localhost.

**To Reproduce**
Deploy the app using docker compose in an ubuntu 18 remote server
**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18
 - Label Studio Version :latest

**Additional context**

**Comment by makseq** [comment]
If you have external domain for LS, you need to specify it at docker start:

```
LABEL_STUDIO_HOST=https://subdomain.example.com:7777 docker-compose up
```

**Comment by athulprathap** [comment]
As suggested used LABEL_STUDIO_HOST=http://xx.xxx.xxc.xx docker-compose up to start the application.URLs are mapped to the host IP.But UI appears to be broken.Is there any configurations to be changed on UI service?
![labelerror](https://user-images.githubusercontent.com/10370721/113730714-be6f3a80-9715-11eb-89a1-61e059e64159.jpg)

**Comment by makseq** [comment]
Could you check docker console? it must be string about your current hostname at start up. Is there a correct hostname?

**Comment by athulprathap** [comment]
Sharing the docker console logs.Here at console the app_1    | => Hostname correctly is set to: http://52.172.183.38}.Is there any change required in UI settings?

Starting label-studio_db_1 ... done
Recreating label-studio_app_1 ... done
Recreating label-studio_nginx_1 ... done
Attaching to label-studio_db_1, label-studio_app_1, label-studio_nginx_1
app_1    | Postgres is up - executing command
app_1    | => Do database migrations...
app_1    | => Hostname correctly is set to: http://52.172.183.38}
app_1    | => Database and media directory: /label-studio/data
app_1    | => Static URL is set to: /static/
app_1    | 
app_1    | [2021-04-06 15:14:47,704] [urllib3.connectionpool::_new_conn::971] [DEBUG] Starting new HTTPS connection (1): pypi.org:443
app_1    | [2021-04-06 15:14:47,866] [urllib3.connectionpool::_make_request::452] [DEBUG] https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 34251
app_1    | [2021-04-06 15:14:48,469] [core.redis::<module>::14] [WARNING] Redis is not connected.
nginx_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_1  | 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db_1     | 2021-04-06 15:14:43.086 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2021-04-06 15:14:43.086 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2021-04-06 15:14:43.355 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2021-04-06 15:14:45.267 UTC [22] LOG:  database system was shut down at 2021-04-06 15:11:18 UTC
db_1     | 2021-04-06 15:14:46.196 UTC [1] LOG:  database system is ready to accept connections
app_1    | [2021-04-06 15:14:48,646] [root::_read_py::52] [ERROR] Can't read version file: version_.py
app_1    | [2021-04-06 15:14:48,646] [root::_read_py::53] [ERROR] No module named 'version_'
app_1    | [2021-04-06 15:14:49,171] [asyncio::__init__::59] [DEBUG] Using selector: EpollSelector
app_1    | Operations to perform:
app_1    |   Apply all migrations: admin, auth, authtoken, contenttypes, data_import, data_manager, io_storages, ml, organizations, projects, sessions, tasks, users
app_1    | Running migrations:
app_1    |   No migrations to apply.
app_1    | => Run bash /label-studio/deploy/start_label_studio.sh...
app_1    | => Hostname correctly is set to: http://52.172.183.38}
app_1    | => Database and media directory: /label-studio/data
app_1    | => Static URL is set to: /static/
app_1    | 
app_1    | [2021-04-06 15:14:51,620] [root::_read_py::52] [ERROR] Can't read version file: version_.py
app_1    | [2021-04-06 15:14:51,620] [root::_read_py::53] [ERROR] No module named 'version_'
app_1    | [2021-04-06 15:14:51,959] [root::_read_py::52] [ERROR] Can't read version file: version_.py
app_1    | [2021-04-06 15:14:51,959] [root::_read_py::53] [ERROR] No module named 'version_'
app_1    | Start browser at URL: http://localhost:8080
app_1    | Performing system checks...
app_1    | 
app_1    | System check identified no issues (0 silenced).
app_1    | April 06, 2021 - 15:14:52
app_1    | Django version 3.1.4, using settings 'core.settings.label_studio'
app_1    | Starting development server at http://0.0.0.0:8080/
app_1    | Quit the server with CONTROL-C.

**Comment by makseq** [comment]
No, you don't need to change anything in UI.
I see a strange character } at the end of the hostname. It's excess.

**Comment by makseq** [comment]
I think your nginx is wrongly configured.

**Comment by abhay-kum** [comment]
mount static folder in the app service in the docker-compose.yml, UI will work properly after that make sure you have pulled the latest code and build the docker locally `docker build -t label_studio_app .` and then run `docker-compose up -d --build`

version: '3.3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static:/label-studio/label_studio:rw
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/${NGINX_FILE:-default.conf}:/etc/nginx/conf.d/default.conf:ro
    command: nginx -g "daemon off;"

  app:
    stdin_open: true
    tty: true
    # build: .
    image: label_studio_app:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-http://localhost}
    volumes:
      - ./mydata:/label-studio/data:rw
      - static:/label-studio/label_studio:rw
    command: [ "./deploy/wait-for-postgres.sh", "db", "bash", "/label-studio/deploy/start_label_studio.sh" ]

  db:
    image: postgres:11.5
    hostname: db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  static: {}

**Comment by athulprathap** [comment]
@abhay-kum that works.Thank you for the suggestion. app is accessible at 8080.
Also since  I already have other applications running on port 80, unable to use port 80 as default in Nginx configuration.
Tried giving port 8008 in Nginx configuration in the docker-compose file as below.
image: nginx:latest
ports:
- 8008:80
depends_on:

But traffic is not getting routed through 8008..and I have to directly use 8080 port.Any suggestions here for routing the traffic through Nginx with custom port?

**Comment by suvojit-0x55aa** [comment]
@athulprathap facing the same problem did you find any solution?

**Comment by athulprathap** [comment]
@suvojit-0x55aa Hi Suvajit,
Yeah.Got a temporary fix. Bypass Nginx service and access the service directly in 8080.

**Comment by vaibhavsatpathy** [comment]
Facing the same issues. Though As suggested once I By-Pass Nginx and directly access 8080 it works.
