### ISSUE TITLE
Port argument not working in version 1.0.1

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#763]
**Describe the bug**
In version 1.0.1 the port argument is not working.  Previously specifying `--port 80` would start the server at http://0.0.0.0:80/.  In version 1.0.1 the server is started at  http://0.0.0.0:8080 (or the next available port) regardless of the port argument. 

**To Reproduce**
1. `docker run -d heartexlabs/label-studio:1.0.1`
2. `docker exec -it  <CONTAINER ID> /bin/sh`  (where 'CONTAINER ID' can be found with docker ps)
3. `label-studio start --port 80`
4. Output shows "Starting development server at http://0.0.0.0:8081/"

**Expected behavior**
"Starting development server at http://0.0.0.0:80/"

**Comment by niklub** [comment]
@laynr I guess the problem is because the default port was globally set within the container as 8080. (you can check `LABEL_STUDIO_PORT` variable). There are 2 alternatives I can suggest:
- try to update to the latest docker image `heartexlabs/label-studio:latest`
- or specify `LABEL_STUDIO_PORT=80` variable instead when running your current container

**Comment by laynr** [comment]
@niklub thank you for your  response

-  Setting the environmental variable `LABEL_STUDIO_PORT` worked for me thanks!
- `heartexlabs/label-studio:latest` currently pulls a version of 1.0.0.post3, but I see you recently changed this line to prioritize args over environment variables https://github.com/heartexlabs/label-studio/blob/2f890de2733f7846553bcb598265afc8dd6ab3c4/label_studio/server.py#L327 so I am confident it will work in future releases

Going forward should I use `PORT` or `LABEL_STUDIO_PORT`  environment variable for the PORT?  Does `get_env('PORT')`in the line above pull LABEL_STUDIO_PORT?

**Comment by niklub** [comment]
it's strange with version `1.0.0.post3`.. from where is it coming?

**Comment by niklub** [comment]
> Going forward should I use PORT or LABEL_STUDIO_PORT environment variable for the PORT? Does get_env('PORT')in the line above pull LABEL_STUDIO_PORT?

yes, it first checks `LABEL_STUDIO_PORT` followed by `PORT`

**Comment by laynr** [comment]
> it's strange with version `1.0.0.post3`.. from where is it coming?


My fault. My "latest" was stored locally. Once deleted and pulled remotely I got the new "latest". And yes `port` is fixed in the latest.  

Thank you and closing.
