### ISSUE TITLE
Duplicate annotations in storage export

### ISSUE THREAD

**Issue by uriel-tannen** [heartexlabs/label-studio#764]
**Describe the bug**
Following issues discussed in [this](https://label-studio.slack.com/archives/CQ8LYPPJS/p1617721944368300?thread_ts=1616102107.229400&cid=CQ8LYPPJS) thread, changes were made to align storage export with regular export. However a new issues has surfaced as a result. Regular export is a single JSON or CSV file that includes all annotations in a single file, whereas storage export has a separate JSON file per annotation...by making them the same, it turns out you now have multiple duplicate annotations in the S3 files. For example file 1 in S3 has annotation 1, but file 2 has annotations 1 and annotations 2 - so when you combine them using the LS converter, you now have multiple lines of the same data.

**Additional feature request**
Could we please include `lead_time` and `created_at` (annotation created_at, not task created_at) fields in the CSV file when converting from JSON to CSV? I think those would be quite helpful in keeping an eye on productivity of each labeller and identifying tasks that are slowing people down etc

**Comment by niklub** [comment]
Hi, @uriel-tannen ! This feature / fix was eventually merged into master https://github.com/heartexlabs/label-studio/pull/762 and be released very soon as `label-studio==1.0.2`. To save entire tasks into your S3 storage, you must enable `LABEL_STUDIO_FUTURE_SAVE_TASK_TO_STORAGE=true` option (will become default in the future releases).
Regarding additional feature requests - standalone CSV converter has been recently added to https://github.com/heartexlabs/label-studio-converter repo. You can try installing it form source via `pip install -e .` then convert Label Studio JSON export via:
```
label-studio-converter --input your-exported-data.json --output result.csv --format CSV
```
Please open a separate issue if you'll bump into some problems. This one will be closed as soon as 1.0.2 published
