### ISSUE TITLE
Error am getting on backend....

### ISSUE THREAD

**Issue by nishantbhat** [heartexlabs/label-studio#77]
Hello,
am new to this and am trying to install it on my device. But I 
![ERRORRRRR](https://user-images.githubusercontent.com/30562513/66286989-79d0cc00-e8f1-11e9-81f1-0c29eb93041f.png)
am getting below error and am not getting what exactly it is .please let me know how to resolve this.

**Comment by niklub** [comment]
> Hello,
> am new to this and am trying to install it on my device. But I
> ![ERRORRRRR](https://user-images.githubusercontent.com/30562513/66286989-79d0cc00-e8f1-11e9-81f1-0c29eb93041f.png)
> am getting below error and am not getting what exactly it is .please let me know how to resolve this.

Hi! Please make sure you are using Python>=3.6

**Comment by shevchenkonik** [comment]
@nishantbhat Did the update to the new version of Python help you? 🤞
