### ISSUE TITLE
images do not appear in the project

### ISSUE THREAD

**Issue by ViktorGlushak** [heartexlabs/label-studio#770]
When I thyed to import images, images do not appear in the project. I use linux gnome 2. Tryed to run app from docker and pip. 

![image1](https://i.ibb.co/MfhzwsF/Screenshot-at-2021-04-07-15-08-31.png)
![image2](https://i.ibb.co/KhWqjWn/Screenshot-at-2021-04-07-15-10-56.png)

> [07/Apr/2021 10:30:57] "GET / HTTP/1.1" 302 0
> [07/Apr/2021 10:30:57] "GET /projects/ HTTP/1.1" 200 2424
> [07/Apr/2021 10:31:08] "GET / HTTP/1.1" 302 0
> [07/Apr/2021 10:31:08] "GET /projects/ HTTP/1.1" 200 2424
> [07/Apr/2021 10:31:08] "GET /static/css/uikit.e49a7a43adbd.css HTTP/1.1" 200 3892
> [07/Apr/2021 10:31:08] "GET /static/fonts/roboto/roboto.css HTTP/1.1" 200 3431
> [07/Apr/2021 10:31:08] "GET /react-app/main.css?v=71278b HTTP/1.1" 200 60926
> [07/Apr/2021 10:31:08] "GET /static/css/main.3b36b24fbb6f.css HTTP/1.1" 200 15457
> [07/Apr/2021 10:31:08] "GET /static/js/jquery.min.220afd743d9e.js HTTP/1.1" 200 88145
> [07/Apr/2021 10:31:08] "GET /react-app/index.js?v=71278b HTTP/1.1" 200 578195
> [07/Apr/2021 10:31:08] "GET /static/js/helpers.9a01b074ff58.js HTTP/1.1" 200 13336
> [07/Apr/2021 10:31:08] "GET /static/icons/logo-black.svg HTTP/1.1" 200 10236
> [07/Apr/2021 10:31:08] "GET /api/version HTTP/1.1" 200 556
> [07/Apr/2021 10:31:08] "GET /api/projects HTTP/1.1" 200 3578
> [07/Apr/2021 10:31:08] "GET /favicon.ico HTTP/1.1" 301 0
> [07/Apr/2021 10:31:08] "GET /projects/ HTTP/1.1" 200 2424
> [07/Apr/2021 10:31:08] "GET /static/images/favicon.ico HTTP/1.1" 200 21822
> [07/Apr/2021 10:31:12] "GET /dm/js/main.js?v=516446 HTTP/1.1" 200 1267427
> [07/Apr/2021 10:31:12] "GET /dm/css/main.css?v=516446 HTTP/1.1" 200 49819
> [07/Apr/2021 10:31:12] "GET /api/projects/1 HTTP/1.1" 200 3576
> [07/Apr/2021 10:31:12] "GET /label-studio-frontend/css/main.css?v=516446 HTTP/1.1" 200 1311494
> [07/Apr/2021 10:31:12] "GET /label-studio-frontend/js/main.js?v=516446 HTTP/1.1" 200 2073111
> [07/Apr/2021 10:31:13] "GET /api/dm/columns?project=1 HTTP/1.1" 200 2185
> [07/Apr/2021 10:31:15] "GET /api/projects/1/file-uploads HTTP/1.1" 200 2
> [07/Apr/2021 10:31:15] "GET /api/projects/1 HTTP/1.1" 200 3576
> [07/Apr/2021 10:31:15] "GET /api/projects/1/file-uploads HTTP/1.1" 200 2
> [07/Apr/2021 10:31:15] "GET /api/projects/1 HTTP/1.1" 200 3576
> [07/Apr/2021 10:31:15] "GET /api/projects/1/file-uploads HTTP/1.1" 200 2
> [07/Apr/2021 10:31:24] "POST /api/projects/1/import?commit_to_project=false HTTP/1.1" 201 203
> [07/Apr/2021 10:31:24] "GET /api/projects/1/file-uploads?ids=%5B6%5D HTTP/1.1" 200 43
> [07/Apr/2021 10:31:28] "POST /api/projects/1/reimport HTTP/1.1" 201 169
> [07/Apr/2021 10:31:28] "GET /api/dm/columns?project=1 HTTP/1.1" 200 2185
> [07/Apr/2021 10:31:28] "GET /api/projects/1 HTTP/1.1" 200 3576

Could you help me pleas?

**Comment by makseq** [comment]
It looks like your browser is not support modern javascript extensions. 
Could you check your browser console and reload the page completely?

**Comment by ViktorGlushak** [comment]
![image](https://i.ibb.co/Vt9x0wV/Screenshot-at-2021-04-07-16-48-08.png)

Version of browser Google Chrome 72.0.3626.109

**Comment by ViktorGlushak** [comment]
It is work in Firefox.

**Comment by makseq** [comment]
I think you need to update chrome to the latest version.
