### ISSUE TITLE
import txt data failed

### ISSUE THREAD

**Issue by uRENu** [heartexlabs/label-studio#772]
**Describe the bug**
After I click "import" in the browser to import data,  the UI interface did not respond:
![image](https://user-images.githubusercontent.com/54517380/113983805-efb64a80-987c-11eb-8cf2-bfd1a3290dc7.png)

and an error has occurred in the command window:
[2021-04-08 07:08:51,262] [django.request::log_response::230] [ERROR] Internal Server Error: /user/account/
Traceback (most recent call last):
  File "/home/wrz/NER/LabelStudio/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/wrz/NER/LabelStudio/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/wrz/NER/LabelStudio/venv/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/home/wrz/NER/LabelStudio/venv/lib/python3.6/site-packages/label_studio/core/permissions.py", line 190, in wrapper
    return raise_auth_denied('Authentication credentials were not provided', request, redirect_path)
  File "/home/wrz/NER/LabelStudio/venv/lib/python3.6/site-packages/label_studio/core/permissions.py", line 233, in raise_auth_denied
    raise DRFPermissionDenied(msg)
rest_framework.exceptions.PermissionDenied: Authentication credentials were not provided

**Environment (please complete the following information):**
label-studio             1.0.1
label-studio-converter   0.0.28
ubuntu18.04
python 3.6.9

**Comment by makseq** [comment]
@uRENu Could you try the same on Chrome browser (the latest versions ~88-89)?

**Comment by uRENu** [comment]
> @uRENu Could you try the same on Chrome browser (the latest versions ~88-89)?

I tried using Google Chrome and the problem was solved. thank you very much  :)

**Comment by uRENu** [comment]
Another question: I want to import some TXT files in the local folder of my computer and label it with the entity type. Follow your tutorial:
1. On the machine with the file directory that you want Label Studio to import, call the helper script and specify a regex pattern to match the files that you want to import. 
I run: sh serve_local_files.sh /home/wrz/NER/data dd.txt   # TXT file directory: /home/wrz/NER/data/dd.txt
Then i get files.txt
![image](https://user-images.githubusercontent.com/54517380/114147592-6b7ec880-994b-11eb-8c84-84b81ca41516.png)

2. Import the file with URLs into Label Studio using the Label Studio UI.
so I clicked 'Upload Files' to upload 'files.txt' generated by step1.
![image](https://user-images.githubusercontent.com/54517380/114147881-bbf62600-994b-11eb-8c2b-5cd4170a7776.png)

But this is what I get
![image](https://user-images.githubusercontent.com/54517380/114148245-1ee7bd00-994c-11eb-8395-d1d29f591029.png)
it seems to treat the TXT file as plain text, the contents of TXT file are not read.

My configuration is as follows：
1. Ubuntu 18.04， Google Chrome 89.0.4389.114， LabelStudio 1.0.1 
2. Labeling Interface
<View>
  <Labels name="label" toName="text">
    <Label value="PER" background="red"/>
    <Label value="ORG" background="darkorange"/>
    <Label value="LOC" background="orange"/>
    <Label value="MISC" background="green"/>
  </Labels>
  <Text name="text" value="$ner"/>
</View>

I have tried to modify the Labeling Interface:
<View>
  <Labels name="label" toName="text">
    <Label value="PER" background="red"/>
    <Label value="ORG" background="darkorange"/>
    <Label value="LOC" background="orange"/>
    <Label value="MISC" background="green"/>
  </Labels>
  <Text name="text" value="$text"/>
</View>
but it still not work.

**Comment by makseq** [comment]
I hope the usage of these options solved this problem:
`valueType="url"` - LS will load data from $ner url as text file.
`valueType="text"` - LS will use $ner as text directly.
