### ISSUE TITLE
Can not import Audio file

### ISSUE THREAD

**Issue by ChasingZch** [heartexlabs/label-studio#782]
**Describe the bug**
When I tired to import a .wav or .mp3 audio file, it said that `[7e74ffb4-a210-4a96-bd4c-1ca2eb99b3bd]Validation error(undefined)`

**To Reproduce**
1. Import Data
2. Select audio file
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/23622532/114144773-42106d80-9948-11eb-8225-aa497044fcae.png)

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - Label Studio Version: 1.0.1

**Comment by makseq** [comment]
Please, send us logs from console

**Comment by ChasingZch** [comment]
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/23622532/114147706-8e10e180-994b-11eb-9422-47c90cde20a9.png">
from the above logs, it seems that the size of my audio file is too large. However, I can use the older version (0.9.0) to upload the same file to label.

**Comment by makseq** [comment]
Have you enabled toggle "Treat file objects as ..." On storage settings page? (Sorry, don't remember the exact name of the toggle)

**Comment by ChasingZch** [comment]
No, I did not enable the toggle. And I did not find the toggle or the storage settings page.

**Comment by makseq** [comment]
I mean 
Project => Settings => Storages => edit your Local files storage

**Comment by ChasingZch** [comment]
I can not find Storages under the Settings.
The below is my Settings page. (my current project is named test)
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/23622532/114150144-4a6ba700-994e-11eb-9da0-88955e4f14d0.png">

**Comment by ChasingZch** [comment]
And I can not find the Settings under the Projects page. I can only find the Settings when I select a specific project.
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/23622532/114150436-a46c6c80-994e-11eb-9999-8350b03ea051.png">

**Comment by makseq** [comment]
Cloud storage = Storages, I was wrong

**Comment by ChasingZch** [comment]
I have successfully import the audio file. However, I meet with  a new problem that it said `Error while processing audio. Check media format and availability.`. And I can not set the Target Storage as the local file. 
<img width="1513" alt="image" src="https://user-images.githubusercontent.com/23622532/114157265-0b415400-9956-11eb-9034-8ecf708968b0.png">

**Comment by niklub** [comment]
Hi, @ChasingZch ! Could you check whether you include `LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true` variable in your local environment? It is mentioned here https://labelstud.io/guide/storage.html#Set-up-connection-in-the-Label-Studio-UI-4 .
And yes, target local files storage is not supported yet. Interesting why it should be the case to store something outside the database?

**Comment by potipot** [comment]
Hi, I encounter the same issue with the same logging info. I assumed my json file was too large (1GB). Spliting the file to fit the maximum size limitation works but is cumbersome. Any idea how to bypass that limitation?

**Comment by potipot** [comment]
@ChasingZch 
1. I think there is a bug in local storage import: I could discover files and create tasks in project from local directory but then when audio files were loaded to be played, the path gets corrupted. What happens is that only filenames are kept and no folder structure is maintained. In other words, you need to import files from the main directory where the audio files are located. That directory cannot have audio files in subdirectories cause these will not be properly played.
2. Regarding local file import, you dont need to set up local storage. You can just import file info from the json. Here is a sample that works for me:
```
[
  {
    "annotations": [],
    "predictions": [
      {
        "id": "prediction_1",
        "model_version": "some_model",
        "score": 6.0,
        "result": [
          {
            "value": {
              "text": [
                "ale \u017cycie to nie jest p\u00f3\u0142g"
              ]
            },
            "from_name": "transcription",
            "to_name": "audio",
            "type": "textarea"
          }
        ]
      }
    ],
    "data": {
      "audio": "/data/local-files/?d=home/toucan/Datasets/audio/Septagon04.wav"
    }
  }
]
```

Note the missing initial slash in `/home/[...]`

**Comment by tingjhenjiang** [comment]
> Hi, @ChasingZch ! Could you check whether you include `LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true` variable in your local environment? It is mentioned here https://labelstud.io/guide/storage.html#Set-up-connection-in-the-Label-Studio-UI-4 .
> And yes, target local files storage is not supported yet. Interesting why it should be the case to store something outside the database?

Hello @niklub , it's not clear what the sentence `set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true in your environment setup` means. 
Is it a command line argument? But  I encounter the error message `label-studio: error: unrecognized arguments: --LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true`
Is it a setting in a project template? But I cannot find any.

**Comment by potipot** [comment]
> > Hi, @ChasingZch ! Could you check whether you include `LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true` variable in your local environment? It is mentioned here https://labelstud.io/guide/storage.html#Set-up-connection-in-the-Label-Studio-UI-4 .
> > And yes, target local files storage is not supported yet. Interesting why it should be the case to store something outside the database?
> 
> Hello @niklub , it's not clear what the sentence `set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true in your environment setup` means. I don't know what _environment setup_ specifically is.
> Is it a command line argument? But I encounter an error message `label-studio: error: unrecognized arguments: --LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true`
> Is it a setting in a project template? But I cannot find any.

This is a env variable that you can either set using (depending on your OS)
```bash
export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
# now run
label-studio
```
or you can do it in single command like so:
```bash
LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true label-studio
```

**Comment by niklub** [comment]
@tingjhenjiang on *nix systems, just use
```
export LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
```
before starting the app

**Comment by makseq** [comment]
Looks like it's fixed already.
