### ISSUE TITLE
How to use other SQL databases for database storage (MySQL)

### ISSUE THREAD

**Issue by astenuz** [heartexlabs/label-studio#787]
Hi! I've noticed the doc references postgres for setting up data storage (https://labelstud.io/guide/storedata.html). However, I was wondering whether it's possible to switch to other databases such as MySQL for the same task. If so, more or less how'd the process be? I'm trying to set up label-studio and the environment I'm using only allows MySQL DBs.

Thanks!

**Comment by makseq** [comment]
@astenuz hi! LS doesn't support MySQL officially. But I suppose Django could use it. You have to modify django settings to do it.

**Comment by niklub** [comment]
Just adding few hints - you may want to replace [these settings](https://github.com/heartexlabs/label-studio/blob/master/label_studio/core/settings/base.py#L59) to
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'DB_NAME',
        'USER': 'DB_USER',
        'PASSWORD': 'DB_PASSWORD',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}
```
Feel free to create a PR if it works for you, I think that would be a valuable contribution.

**Comment by makseq** [comment]
@astenuz https://docs.djangoproject.com/en/3.2/ref/databases/#mysql-notes
Check this Django documentation about MySQL. You also have to install mysqlclient package and drivers.

**Comment by astenuz** [comment]
Hey thanks! I'll check how it goes and let you know.

**Comment by makseq** [comment]
MySQL was added to LS, but not officially supported.
