### ISSUE TITLE
import TXT failed

### ISSUE THREAD

**Issue by uRENu** [heartexlabs/label-studio#789]
question: I want to import some TXT files in the local folder of my computer and label it with the entity type.
 Follow your tutorial:
1. On the machine with the file directory that you want Label Studio to import, call the helper script and specify a regex pattern to match the files that you want to import. 

      _I run: sh serve_local_files.sh /home/wrz/NER/data dd.txt   # TXT file directory: /home/wrz/NER/data/dd.txt
      Then i get files.txt
      ![image](https://user-images.githubusercontent.com/54517380/114147592-6b7ec880-994b-11eb-8c84-84b81ca41516.png)_

2. Import the file with URLs into Label Studio using the Label Studio UI.

    _so I clicked 'Upload Files' to upload 'files.txt' generated by step1.
    ![image](https://user-images.githubusercontent.com/54517380/114147881-bbf62600-994b-11eb-8c2b-5cd4170a7776.png)_

But this is what I get
![image](https://user-images.githubusercontent.com/54517380/114148245-1ee7bd00-994c-11eb-8395-d1d29f591029.png)
it seems to treat the TXT file as plain text, the contents of TXT file are not read.

My configuration is as follows：
1. Ubuntu 18.04， Google Chrome 89.0.4389.114， LabelStudio 1.0.1 
2. Labeling Interface
![image](https://user-images.githubusercontent.com/54517380/114149301-573bcb00-994d-11eb-8473-e61558e55afd.png)

I have tried to modify the Labeling Interface $ner as $text
but it still not work. 

_Originally posted by @uRENu in https://github.com/heartexlabs/label-studio/issues/772#issuecomment-816499130_

**Comment by niklub** [comment]
Try to add `valueType="url"` parameter as bellow:
```
<Text name="text" value="$ner" valueType="url">
```
get more details [here](https://labelstud.io/tags/text.html)

**Comment by johanngerberding** [comment]
I have the same problem and the change of `valueType="url"` didn't work for me.

**Comment by makseq** [comment]
`valueType="url"` - LS will load data from $ner url as text file. 
`valueType="text"` - LS will use $ner as text directly.
