### ISSUE TITLE
Bookmarks [tabs] on files list disappear after add instruction in project

### ISSUE THREAD

**Issue by kasiopac** [heartexlabs/label-studio#791]
**Describe the bug**
I had few bookmarks in my project. Then I added instruction. When I came back to my project, all bookmarks disappeared. 

**To Reproduce**
1. Go to any project 
2. Add some bookmarks
3. Go to "Settings" -> "Instructions"
4. Add some instruction and save it
5. Go back to project and see that You have only one bookmark now: "Default"

**Expected behavior**
I expect to bookmarks don't disappear until I don't delete them :)

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/65225576/114378855-68bce700-9b88-11eb-9239-3c441bc0d55b.png)

After add instruction to project:
![image](https://user-images.githubusercontent.com/65225576/114379050-a3268400-9b88-11eb-8884-87890b7f36a2.png)

**Environment (please complete the following information):**
 - Windows 7
 - Chrome
 - Label Studio Version [e.g.1.0.1]

**Comment by makseq** [comment]
@kasiopac Thank you for your report, it's a bug on our side. We will fix it asap.

**Comment by makseq** [comment]
@kasiopac Could you check this PR: https://github.com/heartexlabs/label-studio/pull/799 
There is a fix of this bug.
