### ISSUE TITLE
Configurable hotkeys

### ISSUE THREAD

**Issue by flavienbwk** [heartexlabs/label-studio#796]
**Is your feature request related to a problem? Please describe.**

It's very annoying to have to type "Ctrl" + "Enter" to confirm a labelisation. It hurts my little finger each time I have to confirm !

**Describe the solution you'd like**

Configurable hotkeys to next a labelisation or come back using **arrows**.

Thanks !

**Comment by makseq** [comment]
This problem was fixed here: https://labelstud.io/guide/labeling.html#Customize-hotkeys
