### ISSUE TITLE
loading time take more 4-5 min 

### ISSUE THREAD

**Issue by abhay-kum** [heartexlabs/label-studio#798]
**Describe the bug**
till 10-15 min the tool is working fine after that the waiting time for loading images and task it take more than 4-5 min, and sometimes it hangs the browser and system.

![Screenshot 2021-04-13 at 12 41 43 PM](https://user-images.githubusercontent.com/27910202/114511936-28c43580-9c56-11eb-9316-7163dad0be92.png)

**Environment (please complete the following information):**
 - OS: ubuntu18.04
 - Label Studio Version : 1.0.1

![2021-04-12 (15)](https://user-images.githubusercontent.com/27910202/114512311-9bcdac00-9c56-11eb-9cb8-3433268b84ce.png)

**Comment by makseq** [comment]
@abhay-kum Do you use ML Backends? Is it brush labels config?

**Comment by abhay-kum** [comment]
No, I am not using the ml backend. it is not the brush labels config, it is for the multi-image labeling config.

**Comment by makseq** [comment]
@abhay-kum Does it still work slow in the latest LS versions?
