### ISSUE TITLE
NER multiple meta values

### ISSUE THREAD

**Issue by KDercksen** [heartexlabs/label-studio#803]
Dear developers,

I am wondering if there is an option to add multiple "meta" values to a NER annotation. I am currently trying to use the tool to do labeling for entity linking, and I'd like to use an ML backend to supply multiple candidate entities for a single string span so I can go through by hand and pick the best candidate.

Any easy way to go about this, or should I look at a different annotation template? E.g. wrapping my use case into a text classification problem? I am fine with changing something in the source if you can tell me where to look :D

Thanks a lot for your work on this tool, loving it!

**Comment by makseq** [comment]
Hello, dear Koen Dercksen :slightly_smiling_face: 

* You can put into the prediction result multiple values with the same start/end positions, but with different names. 
* Also you can add to the each result item `"score": 0.5` and it will be displayed in Regions block on the right panel.

The entities will be overlapped (it's a disadvantage), but you can navigate them through via Regions and control their visibility using the eye icon.

**Comment by KDercksen** [comment]
Thanks for the quick answer! Hmm maybe I will try that then, the overlap is a disadvantage indeed.. But sorting based on score might alleviate the inconvenience haha. Thanks again! :)

**Comment by gromajus** [comment]
Hi @KDercksen !
I will be working on Entity Linking annotation task.
May I ask how you finally approached your annotations?

I want to use the meta field to store my annotations. 
However, I need to make those annotations to several KB. I know I can make meta a complex field.
But each time, annotator needs to fill in this field with the json content, then change appropriately. 
I was thinking about preannotations on meta field, but it seems not possible.
