### ISSUE TITLE
Trying to host label_studio in https:// server

### ISSUE THREAD

**Issue by MrityunjoyS** [heartexlabs/label-studio#809]
I'm trying to host label_studio in a server and configure it for https. I've followed the instruction. My docker-compose file is -->

`version: '3.3'

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static:/label-studio/label_studio:rw
      - ./files:/label-studio/files:rw
      - ./nginx/:/etc/nginx/conf.d/:ro
    command: nginx -g "daemon off;"

  app:
    build: ./
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=postgres
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
      - LABEL_STUDIO_HOST=https://example.domain.net:9002
      - LABEL_STUDIO_CERT_FILE=/path/nginx-selfsigned.crt
      - LABEL_STUDIO_KEY_FILE=/path/nginx-selfsigned.key
    volumes:
           - static:/label-studio/label_studio:rw
      - ./files:/root/.local/share/label-studio:rw
    command: [ "/label-studio/wait-for-it.sh", "db", "/usr/local/bin/label-studio" ]

  db:
    image: postgres:11.5
    hostname: db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  static: {}
`

But while I'm trying to connect to from browser with url **https://example.domain.net:9002** , it's showing **_This site can’t be reached._**  error. 
Please suggest where else do I need to change configurations to able to successfully host label_studio in **https://** server.

**Comment by makseq** [comment]
1. You have to expose 9002 port:
```
expose:
- "8080"
```

2. Map nginx port to 9002
```
ports:
- 9002:80
```

3. LS doesn't support https starting from 1.0, you need to configure it in nginx.

**Comment by MrityunjoyS** [comment]
yeah solved, thank you
