### ISSUE TITLE
Emtpy screen when scroling to right side in timeseries labeling.

### ISSUE THREAD

**Issue by NickShargan** [heartexlabs/label-studio#811]
**Describe the bug**
When sliding window reach the end of signal visualizations disappear and it is not clear how to finish labeling. 

**To Reproduce**
1. Open project with time series data
2. Start labeling
3. Scroll sliding window to the right side
4. Visualizations are not shown

**Expected behavior**
I expect that signal should be kept visualized when sliding window reach right side.

**Screenshots**
![Screenshot from 2021-04-15 11-04-12_c](https://user-images.githubusercontent.com/6961628/114836452-58507a80-9ddb-11eb-9107-6c8e9720fe7d.png)

![Screenshot from 2021-04-15 11-03-33_c](https://user-images.githubusercontent.com/6961628/114836473-5f778880-9ddb-11eb-916f-4d14960bc2d3.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version 1.0.1
 - browser: Firefox 87.0 (64-bit)

**Comment by hogepodge** [comment]
@NickShargan It looks like we fixed this bug upstream. Please let us know if you're still encountering this issue.
