### ISSUE TITLE
Text dataset cannot  be imported

### ISSUE THREAD

**Issue by alex-eurec** [heartexlabs/label-studio#813]
First of all, thanks for your work, it is an excellent tool

**Describe the bug**
Text file cannot be uploaded.

**To Reproduce**
Try to import one dataset as mine.
Because of the dataset I am using being confidential, I will give the specs of it, so other tests can be done with similar data.
I am not sure if the problem is the quantity of lines or the size of the .txt file being uploaded, so I am sharing both:
- Lines: 249987 (one line less [101 characters] and it is working like a charm. The last line has numbers, letters and `*` signs, all ASCII characters)
- Size: 33,2 MB (33.204.068 bytes) (with less bytes equivalent to 101 characters is uploading as expected)

Any other spec you need to try it out, please ask me and I will give it.

**Expected behavior**
The dataset being uploaded

**Screenshots**
![image](https://user-images.githubusercontent.com/81571132/114893164-bc8c3200-9e0d-11eb-9db4-f4f9d770da68.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Label Studio Version: 1.0.1
 - Browser: Tested on Firefox  & Chromium

**Comment by makseq** [comment]
Hi, thank you for your kind words!

Could you show LS console logs?

**Comment by alex-eurec** [comment]
Thanks for the quickly response!

Yes, of course (sorry I didn't include that earlier):

I guess that the LS console logs are the ones shown in the browser JS console, Am I right?
In the affirmative case, the related error is this one:
```json
{
  "id": "550a256e-d015-4eba-9382-e31a1b1ce5ee",
  "status_code": 400,
  "version": "1.0.1",
  "detail": "Validation error",
  "exc_info": null,
  "validation_errors": {
    "non_field_errors": [
      "Maximum task number is 250000, current task number is 250001"
    ]
  }
}
```
![image](https://user-images.githubusercontent.com/81571132/114986916-dfadf480-9e94-11eb-8c90-3981f681193d.png)

Just as before, correct me or ask me for more info if needed.

**Comment by makseq** [comment]
LS summarizes all tasks during the single upload. I think we have to expand this limit in the next versions.

**Comment by makseq** [comment]
TASKS_MAX_NUMBER was set up to 1M tasks. 
Also now we have the Local Storage and the recommended way is to use Local Storage/S3/GCS.
