### ISSUE TITLE
connect ML model, but show error "doesn't look like a valid ML backend"

### ISSUE THREAD

**Issue by joul55320** [heartexlabs/label-studio#818]
**Describe the bug**

I follow this guide https://labelstud.io/tutorials/object-detector.html let ML modelconnected  to LS,
but LS show "doesn't look like a valid ML backend" 

**To Reproduce**
1. label-studio-ml init coco --from mmdetection.py
2. python coco/_wsgi.py --with config_file=/path/to/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_iou_1x_coco.py checkpoint_file=/path/to/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth device=gpu
3. label-studio
4. Setting -> Machine Learning -> Add model
5. type "http://0.0.0.0:9090" in "URL"
6. click "validate and save"

about step2, because when I type "label-studio-ml start [project]",
then show ImportError: No module named flask
so I run the python file that in project folder 

**Expected behavior**

**Screenshots**
![Screenshot from 2021-04-16 17-42-32](https://user-images.githubusercontent.com/32756947/115006174-27576f00-9edb-11eb-91c1-96f8808896da.png)

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04
 - Label Studio Version [e.g. 0.8.0] 1.0.1

**Additional context**

**Comment by niklub** [comment]
Hi! guess there are multiple problems I'd recommend checking:
1. Before running ML backend, its environment [should be installed first](https://github.com/heartexlabs/label-studio-ml-backend#quickstart) (that's why probably you've faced `ImportError: No module named flask`)
2. Before connecting the model by adding ML backend URL, you have to specify the labeling configuration in your project settings (should be _Browse Templates -> Object Detection with Bounding Boxes_ in your case)
3. Also it's better to use `localhost` instead of `0.0.0.0` (but this problem might be more related to Windows setup)

**Comment by joul55320** [comment]
Hi niklub:

Thanks, I think this problam is make by "flask".

Now, I can connect coco model to LS and open the button "Display ML-predicted annotations when labeling", 
but when I label datas, it always can not show any predictions.

My  labeling configuration setting was follow guide: https://labelstud.io/tutorials/object-detector.html

The score threshold of model is 0.3

And my configuration code about object is: 

<Label value="Car" predicted_values="car"/>
<Label value="Bus" predicted_values="bus"/>


Did I miss something again?

**Comment by christianjcc** [comment]
Hi all, I am experiencing same error message above but have not been able to resolve given the information provided by others in this thread. My aim is to try to execute active learning with Label-studio (ideally with BaaL) on a simple example on simple images with vehicles to perform bound-box object detection using a pre-trained model (e.g. Faster-RCNN-based or YOLvX) trained on MS COCO dataset. Any clude that you be able to spot as to what I might be either incorrectly executing on missing would be great appreciated. Below I include as much information as to how I went about installing and executing the commands to provide context

Working with the following system specs: 
- Ubuntu 20.04.3 LTS
- GeForce RTX 2070
- GeForce GTX 1080 Ti


Libraries where installed by taking the following steps
`
# Create Conda Environment
conda create --name label-studio
conda activate label-studio

# Install label studio and its dependencies
conda install pytorch cudatoolkit=10.1 torchvision -c pytorch
pip install label-studio

# Install Open-MMLab MMDetection and its dependencies
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.7.0/index.html
pip install mmdet==2.23.0

# Install Label-studio ML backend and its dependencies
git clone https://github.com/heartexlabs/label-studio-ml-backend
cd label-studio-ml-backend

# Install label-studio-ml and its dependencies
pip install -U -e .

# Install example dependencies
pip install -r label_studio_ml/examples/requirements.txt

# Export your active environment to a new file
conda env export > environment.yml

# Create the environment from the environment.yml file 
conda env create -f environment.yml

# Install Bayesian active learning with Label-studio
pip install baal==1.3.0
`

`
# Initialize ML backend
label-studio-ml init coco-detector  --from label-studio-ml-backend/label_studio_ml/examples/mmdetection/mmdetection.py –force

also tried (not sure when to use --from vs --script), 
label-studio-ml init coco-detector --script label-studio-ml-backend/label_studio_ml/examples/mmdetection/mmdetection.py --force

label-studio-ml start coco-detector --with config_file=label-studio-ml-backend/label_studio_ml/examples/mmdetection/faster_rcnn_r50_fpn_1x_coco.py checkpoint_file=label-studio-ml-backend/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth device=gpu:0 score_threshold=0.5

Checkpoint downloaded from: 
https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

# Start the ML backend server
label-studio-ml start coco-detector

# Start Label Studio
label-studio start --ml-backends http://localhost:8080
`

Inserted and enabeld smart to true, under Label Studio Labeling Inference tab,
`
<View>
  <Image name="image" value="$image" zoom="true"/>
  <BrushLabels name="tag" toName="image" **smart="true" showInline="true"**>
    <Label value="Airplane" background="rgba(255, 0, 0, 0.7)"/>
    <Label value="Car" background="rgba(0, 0, 255, 0.7)"/>
  </BrushLabels>
</View>
`

Added model URL: http://example.com:9090 (also tried  http://0.0.0.0:9090/)

Conda environment installed libraries
`
name: label-studio
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.3.29=h06a4308_0
  - certifi=2021.10.8=py39h06a4308_2
  - cffi=1.15.0=py39hd667e15_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=36.0.0=py39h9ce1e76_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1n=h7f8727e_0
  - pip=21.2.4=py39h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.11=h12debd9_2
  - pytorch=1.11.0=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - setuptools=58.0.4=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchvision=0.12.0=py39_cpu
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - appdirs==1.4.4
    - asgiref==3.5.0
    - async-timeout==4.0.2
    - attr==0.3.1
    - attrs==21.4.0
    - azure-core==1.23.1
    - azure-storage-blob==12.11.0
    - baal==1.3.0
    - boto==2.49.0
    - boto3==1.16.63
    - botocore==1.19.63
    - boxing==0.1.4
    - cachetools==4.2.4
    - click==7.1.2
    - colorama==0.4.4
    - coreapi==2.3.3
    - coreschema==0.0.4
    - cycler==0.11.0
    - datasets==2.0.0
    - deprecated==1.2.13
    - dill==0.3.4
    - django==3.1.14
    - django-annoying==0.10.6
    - django-cors-headers==3.6.0
    - django-debug-toolbar==3.2.1
    - django-extensions==3.1.0
    - django-filter==2.4.0
    - django-model-utils==4.1.1
    - django-ranged-fileresponse==0.1.2
    - django-rest-swagger==2.2.0
    - django-rq==2.4.1
    - django-user-agents==0.4.0
    - djangorestframework==3.13.1
    - drf-dynamic-fields==0.3.0
    - drf-flex-fields==0.9.5
    - drf-generators==0.3.0
    - drf-yasg==1.20.0
    - expiringdict==1.1.4
    - filelock==3.6.0
    - flask==1.1.4
    - fonttools==4.31.2
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - future==0.18.2
    - google-api-core==1.31.5
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-appengine-logging==1.1.0
    - google-cloud-audit-log==0.2.0
    - google-cloud-core==1.5.0
    - google-cloud-logging==2.7.0
    - google-cloud-storage==1.29.0
    - google-resumable-media==0.5.1
    - googleapis-common-protos==1.52.0
    - grpc-google-iam-v1==0.12.3
    - grpcio==1.44.0
    - h5py==3.6.0
    - htmlmin==0.1.12
    - huggingface-hub==0.4.0
    - importlib-metadata==4.11.3
    - inflection==0.5.1
    - isodate==0.6.1
    - itsdangerous==1.1.0
    - itypes==1.2.0
    - jinja2==2.11.3
    - jmespath==0.10.0
    - joblib==1.1.0
    - jsonschema==3.2.0
    - kiwisolver==1.4.2
    - label-studio==1.4.1.post1
    - label-studio-converter==0.0.39
    - label-studio-tools==0.0.0.dev11
    - launchdarkly-server-sdk==7.3.0
    - lockfile==0.12.2
    - lxml==4.8.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - mmcv-full==1.4.8
    - mmdet==2.23.0
    - msrest==0.6.21
    - multidict==6.0.2
    - multiprocess==0.70.12.2
    - nltk==3.6.7
    - oauthlib==3.2.0
    - openapi-codec==1.3.2
    - opencv-contrib-python-headless==4.5.5.64
    - opencv-python==4.5.5.64
    - ordered-set==4.0.2
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.0.0
    - proto-plus==1.20.3
    - protobuf==3.20.0
    - psycopg2-binary==2.9.1
    - pyarrow==7.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.4
    - pydantic==1.8.2
    - pyparsing==3.0.7
    - pyrfc3339==1.1
    - pyrsistent==0.18.1
    - python-dateutil==2.8.1
    - pytorch-lightning==0.8.5
    - pytz==2019.3
    - pyyaml==6.0
    - redis==4.2.1
    - regex==2022.3.15
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rq==1.10.0
    - rsa==4.8
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - rules==2.2
    - s3transfer==0.3.7
    - sacremoses==0.0.49
    - scikit-learn==0.24.1
    - scipy==1.8.0
    - semver==2.13.0
    - sentry-sdk==1.5.8
    - simplejson==3.17.6
    - sqlparse==0.4.2
    - structlog==21.5.0
    - supervisor==4.2.2
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminaltables==3.1.10
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - tqdm==4.63.1
    - transformers==4.17.0
    - ua-parser==0.10.0
    - ujson==5.1.0
    - uritemplate==4.1.1
    - user-agents==2.2.0
    - werkzeug==1.0.1
    - wrapt==1.14.0
    - xmljson==0.2.0
    - xxhash==3.0.0
    - yapf==0.32.0
    - yarl==1.7.2
    - zipp==3.7.0
prefix: ~/anaconda3/envs/label-studio
`

**Comment by makseq** [comment]
1. Try this ML backend using docker-compose up - https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/examples/mmdetection
2. Create a new project in LS, then add this ML backend via GUI (port 9090).

**Comment by christianjcc** [comment]
@makseq, thank you for your suggestion. I executed the following,

Step 1.
`cd label-studio-ml-backend/label_studio_ml/examples/mmdetection/
docker-compose up -d
`
after executing the last few lines gave,

`
Successfully built e75e22b88f4f
Successfully tagged mmdetection_server:latest
WARNING: Image for service server was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating redis ... done
Creating server ... done
`
Appeared fine. After following steps 2-3 you provided.

`
label-studio start coco-detector --init --ml-backends http://localhost:8080 --sampling=prediction-score-min
`
Provided the list-of-coco-labels to the LS Labeling Interface tab, but ended up getting an error message not being able to connect to the ML backend. 

![Screenshot from 2022-04-06 20-47-56](https://user-images.githubusercontent.com/64779642/162047063-21fbc394-e838-4a26-ac38-ad666b37ad43.png)
![Screenshot from 2022-04-06 20-47-28](https://user-images.githubusercontent.com/64779642/162047173-612eebeb-d106-4296-a7f0-ca99e37e62dd.png)

**Comment by christianjcc** [comment]
@KonstantinKorotaev, thank you for your suggestion. The solution was to export as environmental variables the paths pointing to the config_file and checkpoint_file (tried also hard coding these values in the mmdetection.py file) and then it worked. It appears the command line arguments are not being propagated to the python script correctly. When running,

`label-studio-ml start coco-detector --with config_file=label_studio_ml/examples/mmdetection/configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py checkpoint_file=label_studio_ml/examples/mmdetection/checkpoints/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth device=gpu:0 score_threshold=0.5`
