### ISSUE TITLE
Overlapping labels in images

### ISSUE THREAD

**Issue by amrlafi** [heartexlabs/label-studio#820]
**Is your feature request related to a problem? Please describe.**
Yes. The user should be able to label a region with different labels.

**Describe the solution you'd like**
The editor should be able to distinguish between labels so that an already labelled area can have another label.  

**Describe alternatives you've considered**
It should be a simple fix to the editor without the need for backend code.  

**Additional context**
An example, Labeling in space: user should be able to label planets, as well as labeling craters on the surface of planets.

**Comment by makseq** [comment]
@amrlafi 
Do you mean option `choice="multiple"` - https://labelstud.io/tags/rectanglelabels.html ?
Check [this example](https://labelstud.io/playground/?config=%3CView%3E%3Cbr%3E%20%20%3CImage%20name%3D%22image%22%20value%3D%22%24image%22%2F%3E%3Cbr%3E%20%20%3CRectangleLabels%20name%3D%22label%22%20toName%3D%22image%22%20choice%3D%22multiple%22%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Airplane%22%20background%3D%22green%22%2F%3E%3Cbr%3E%20%20%20%20%3CLabel%20value%3D%22Car%22%20background%3D%22blue%22%2F%3E%3Cbr%3E%20%20%3C%2FRectangleLabels%3E%3Cbr%3E%3C%2FView%3E%3Cbr%3E).

**Comment by amrlafi** [comment]
This could be it. The only issue is that the user has to draw the label outside and then move it on top of the the original label. 

Example: 
When a user label a planet, then click crater label, it should be possible to label over the planet label. As of now the editor automatically selects the planet label. The user has to label a crater outside and then move it on top of the planet label.

**Comment by makseq** [comment]
Sorry, are you talking about labels (buttons with text) or bound boxes (rectangles over images)?

**Comment by makseq** [comment]
If you are talking about the overlap for bounding boxes - you need to press CTRL and start drawing a new rectangle on top of the previous one.

**Comment by amrlafi** [comment]
Thanks!
