### ISSUE TITLE
"Get all task annotations" API limit 50 items

### ISSUE THREAD

**Issue by mbuet2ner** [heartexlabs/label-studio#826]
**Describe the bug**
It is only possible to get >50 task annotations via calling the API. However, LabelStudio frontend tells me that indeed >50 annotations are available!
Also, it is not deterministic which annotations (for files) get left out. It changes even for the same files with a new project.
E.g., 10-19 get left out, for other project with identical files 1-9

**To Reproduce**
Upload >50 files (in my case images). [Get all task annotations](http://label.dsp-stg.hannover-re.cloud:8080/docs/api#operation/tasks_annotations_list).

**Expected behavior**
API call should be identical to LabelStudio frontend. Every annotation should be listed, like the documentation suggests.

**Screenshots**
LabelStudio frontend shows >50 available tasks:
![image](https://user-images.githubusercontent.com/20720363/115367514-8f050700-a1c6-11eb-9788-843d6475f917.png)
API answers with only 50:
![image](https://user-images.githubusercontent.com/20720363/115367822-cffd1b80-a1c6-11eb-8778-25950f03bcfb.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Label Studio Version 1.0

**Additional context**
None

**Comment by makseq** [comment]
@mbuet2ner try to add  `?page_size=-1` to the endpoint

**Comment by mbuet2ner** [comment]
Thanks a lot for the quick response! That did work perfectly!
Sorry, did not realize it was a pagination issue.
