### ISSUE TITLE
"Label" button does not allow multiple annotators

### ISSUE THREAD

**Issue by tClelford** [heartexlabs/label-studio#831]
**Describe the bug**
Completing a task in Label mode removes that task from Label mode for all other users. 
**To Reproduce**
1. Spin up a fresh label studio instance in docker. Create a user and login.
2. set up a project with the following label config:
```
<View>
  <View>
    <Paragraphs name="dialogue" value="$dialogueField"
     layout="dialogue" savetextresult="yes" nameKey="nameKey" textKey="textKey"/>
  </View>
  <View >
    <ParagraphLabels name="actions" toName="dialogue">
      <label value="Label A" alias="a"/>
      <label value="Label B" alias="b"/>
      <label value="Label C" alias="c"/>
    </ParagraphLabels>
  </View>
</View>
```
3. import tasks using the following json:
```
[
    {
        "dialogueField": [{
            "nameKey": "speaker a",
            "textKey": "Boris Johnson has promised football groups that the government will consider using what he called “a legislative bomb” to stop English clubs joining a breakaway European Super League, as official efforts to thwart the plan were stepped up." 

        },
        {
            "nameKey": "speaker b",
            "textKey": "The prime minister and Oliver Dowden, the sports and culture secretary, held a meeting with the heads of the Football Association and Premier League, as well as representatives of fans’ groups from Liverpool, Manchester United and Tottenham Hotspur, three of the clubs involved."

        }
        ]
    },
    {
        "dialogueField": [{
            "nameKey": "speaker a",
            "textKey": "At one point, according to sources, Johnson told the event: 'We should drop a legislative bomb to stop it – and we should do it now.'"

        },
        {
            "nameKey": "speaker b",
            "textKey": "Plans to legislate would seemingly pass through parliament easily, with Labour saying it would support a law on the issue."

        }
        ]
    }
    
]
```
4. Click "Label"
5. Annotate the task and hit submit
6. Log out.
7. Create a new user and log in. 
8. Go to the project you created in step 2 and click "Label"
9. Observe the fact you are on the second task, with no way to get to the first.

**Expected behaviour**
Completing a task as a user should not remove it from other users' task lists. I'd expect the tasks listed in the Label interface to be controlled by the filters  on the active tab.

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version: `latest` at time of writing.

**Additional context**

**Comment by tClelford** [comment]
After some discussions in the slack channel, apparently this is by design and the behaviour I describe in "expected behaviour" is in the roadmap 👍 . Closing the bug

**Comment by makseq** [comment]
@tClelford Could you put a link to the slack message here please?

**Comment by tClelford** [comment]
Of course! https://label-studio.slack.com/archives/CQ8LYPPJS/p1619031651456900?thread_ts=1618849026.301100&cid=CQ8LYPPJS
