### ISSUE TITLE
Error ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by mgrazianoc** [heartexlabs/label-studio#832]
**Describe the bug**
Error `ModuleNotFoundError: No module named 'ruamel'` while trying to open studio with `label-studio`

**To Reproduce**
1. Open Anaconda prompt on Windows;
2. Run `pip install -U label-studio`
3. Run `label-studio`
4. See error `ModuleNotFoundError: No module named 'ruamel'`

**Expected behavior**
When localhost:8080 is reached, it should open label studio, but it only shows a default error page from the navigator.

**Environment (please complete the following information):**
 - Windows
 - Anaconda latest stable version;

**Comment by niklub** [comment]
Hi! Can you please check [this issue](https://github.com/heartexlabs/label-studio/issues/675) whether it works for you?

**Comment by mgrazianoc** [comment]
yes, it worked. Thanks
