### ISSUE TITLE
Can't build on Win 10

### ISSUE THREAD

**Issue by Dene33** [heartexlabs/label-studio#84]
**Describe the bug**
Can't build on Win 10

```
C:\Programs\label-studio>npm run start

> label-studio@0.1.6 start C:\Programs\label-studio
> npm run copy-examples && react-scripts start


> label-studio@0.1.6 copy-examples C:\Programs\label-studio
> bash scripts/copy.sh
Starting the development server...
Failed to compile.

./src/env/development.js
Module not found: Can't resolve '../examples/audio_classification' in 'C:\Programs\label-studio\src\env'




```

**Comment by shevchenkonik** [comment]
@Dene33 

Thank you, need to configure bash script for Windows environment. (https://github.com/heartexlabs/label-studio/blob/master/scripts/copy.sh). The next release will be with functionality.

But if you want to use LS with python backend you can run without development configuration:
1. Docs: https://labelstud.io/guide/backend.html
2. Docker:
```
docker run -p 8200:8200 -t -i heartexlabs/label-studio -c config.json -l ../examples/chatbot_analysis/config.xml -i ../examples/chatbot_analysis/tasks.json -o output
```

**Comment by niklub** [comment]
The frontend part is moved to https://github.com/heartexlabs/label-studio-frontend
Please, report there if the problem still exists.
