### ISSUE TITLE
images from local files sync storage cannot be shown correctly in Windows docker environment

### ISSUE THREAD

**Issue by tingjhenjiang** [heartexlabs/label-studio#840]
**Describe the bug**
images from local files sync storage cannot be shown correctly in Windows docker environment

**To Reproduce**
1. Create docker container with command `docker run --name labelstudio -it -p 8080:8080 -v /host_mnt/d/Docker/volume/labelstudio/:/label-studio/data -v /host_mnt/f/coffee-beans/:/label-studio/coffee-beans heartexlabs/label-studio:latest`
2. create any project
3. Click on 'Settings/Cloud Storage/Add Source Storage/Storage Type: Local Files/Assign any path to Local path(in this case: /label-studio/coffee-beans)/Add storage'
4. Click "Sync storage", and it shows that `Synced 1 task(s)`
5. back to the project homepage, the thumbnail image cannot be shown, as the screenshot below shows: 
![image](https://user-images.githubusercontent.com/34190920/115574723-785cce00-a2f4-11eb-8e1f-1acbfa61c561.png)

6. enter the task, and I find out that the image is still cannot be shown correctly, and the error message says that `Cannot load image (/data/local-files/?d=label-studio/coffee-beans/images/bad/IMAG0605.jpg). Check console/network panel for more info.
`, as the screenshot below indicates :
![image](https://user-images.githubusercontent.com/34190920/115574956-ae01b700-a2f4-11eb-8235-a5c7408043e7.png)

7. the console says something like `"GET /data/local-files/?d=label-studio/coffee-beans/images/bad/IMAG0605.jpg HTTP/1.1" 403 138`, as the this following screenshot shows:
![image](https://user-images.githubusercontent.com/34190920/115575043-c5d93b00-a2f4-11eb-8ed3-101bdcae82b5.png)

8. check the file permission, already **777**, and chmod recursively those files under the sync path to **777** (in this case: /label-studio/coffee-beans), sync again, and the image is still can be shown neither in the project home nor the annotation page.

**Expected behavior**
Images can be shown in the project home or the annotation page, and no error message like `"GET /data/local-files/?d=label-studio/coffee-beans/images/bad/IMAG0605.jpg HTTP/1.1" 403 138` would appear.

**Environment (please complete the following information):**
- OS: Windows 10 Traditional Chinese
- label-studio 1.0.1 built in docker desktop for windows 3.3.0 (62916), and the result of `docker -v` is Docker version 20.10.5, build 55c4c88.
- docker container volume setting as below:
![image](https://user-images.githubusercontent.com/34190920/115576613-4482a800-a2f6-11eb-84a8-e25fc0909608.png)

**Comment by smoreface** [comment]
@tingjhenjiang please try updating your docker command by following this newly revised documentation and let us know how it goes!
https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-and-use-local-storage

**Comment by tingjhenjiang** [comment]
> @tingjhenjiang please try updating your docker command by following this newly revised documentation and let us know how it goes!
> https://labelstud.io/guide/start.html#Run-Label-Studio-on-Docker-and-use-local-storage

Thank you! It worked well!
