### ISSUE TITLE
ParagraphsLabel validation error prevents editing

### ISSUE THREAD

**Issue by tClelford** [heartexlabs/label-studio#841]
**Describe the bug**
Once you have annotated a single task, you cannot edit your labelling config as the validation endpoint returns a 400.

**To Reproduce**
Steps to reproduce the behaviour:
1. Spin up a fresh label studio instance in docker. Create a user and login.
2. set up a project with the following label config:
```
<View>
  <View>
    <Paragraphs name="dialogue" value="$dialogueField"
     layout="dialogue" savetextresult="yes" nameKey="nameKey" textKey="textKey"/>
  </View>
  <View >
    <ParagraphLabels name="actions" toName="dialogue">
      <label value="Label A" alias="a"/>
      <label value="Label B" alias="b"/>
      <label value="Label C" alias="c"/>
    </ParagraphLabels>
  </View>
</View>
```
3. import tasks using the following json:
```
[
    {
        "dialogueField": [{
            "nameKey": "speaker a",
            "textKey": "Boris Johnson has promised football groups that the government will consider using what he called “a legislative bomb” to stop English clubs joining a breakaway European Super League, as official efforts to thwart the plan were stepped up." 

        },
        {
            "nameKey": "speaker b",
            "textKey": "The prime minister and Oliver Dowden, the sports and culture secretary, held a meeting with the heads of the Football Association and Premier League, as well as representatives of fans’ groups from Liverpool, Manchester United and Tottenham Hotspur, three of the clubs involved."

        }
        ]
    },
    {
        "dialogueField": [{
            "nameKey": "speaker a",
            "textKey": "At one point, according to sources, Johnson told the event: 'We should drop a legislative bomb to stop it – and we should do it now.'"

        },
        {
            "nameKey": "speaker b",
            "textKey": "Plans to legislate would seemingly pass through parliament easily, with Labour saying it would support a law on the issue."

        }
        ]
    }
    
]
```
4. Click "Label"
5. Annotate the task with "Label A" and hit submit.
6. Click "Settings" -> "Labelling Interface".
7. Observe error message "There are 1 annotation(s) created with tag "actions", you can't remove it".
8. Check the network tab in dev tools to see 400 from /validate.
9. Click code and add `<label value="Label D" alias="d"/>` to the set of labels.
10. Click save.
11. Observe forever loading
12. Open dev tools to see 400 from patch to /projects/{id}

**Expected behaviour**
* Validation should prevent removal of in-use labels, not any changes to the whole config.
*  Attempting to view the config should not cause a 400 from the /validation endpoint.
* UI should convey to user that saving the config has failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/14278954/115592845-abd73280-a2cb-11eb-9f68-7ede8dcbae5e.png)

**Environment (please complete the following information):**
 - Label Studio Version `latest` at time of writing
**Additional context**

**Comment by makseq** [comment]
@tClelford 
You are using incorrect Label tags: 

```
      <label value="Label A" alias="a"/>
      <label value="Label B" alias="b"/>
      <label value="Label C" alias="c"/>
```
=>
```
      <Label value="Label A" alias="a"/>
      <Label value="Label B" alias="b"/>
      <Label value="Label C" alias="c"/>
```

**Comment by tClelford** [comment]
🤦  Thank you @makseq
