### ISSUE TITLE
Setting up Postgres on Heroku

### ISSUE THREAD

**Issue by jplauri** [heartexlabs/label-studio#848]
**Is your feature request related to a problem? Please describe.**
I'm not at all an expert with working with Heroku, so I'm confused as to how the setup with Postgres DB there should work.

I find it simple to setup Postgres on Heroku and attach it to the app running label-studio, but then what? Is it merely about setting up the right config vars (right where the one-click deploy bit is also set)?

**Describe the solution you'd like**
The [documentation](https://labelstud.io/guide/storedata.html#Persist-data-with-a-cloud-provider) doesn't really explain anything about it which I'd like to change.

So could the the docs be updated to explain how this is to be done? Perhaps if not, consider explicitly referring the curious reader to the appropriate Heroku docs.

**Describe alternatives you've considered**
If I create a project within label-studio, there are various target databases to set (AWS, Google Cloud, Azure, Redis) which make those look easy. But what about Postgres then, specifically?

**Comment by niklub** [comment]
Hi, @jplauri ! Totally agree with you, setting up PostgresDB on Heroku or other CP is not documented nor covered by links. However, it will be not so easy to maintain those links or keep info up-to-date against what is offered by cloud providers themselves. Therefore, it might be always better to address the corresponding rigorous documentation on their side (like it is done with [Heroku for example](https://devcenter.heroku.com/articles/heroku-postgresql), then using [DB connectivity options from Label  Studio](https://labelstud.io/guide/storedata.html#Create-connection-on-startup)

**Comment by jplauri** [comment]
That's true & fair enough, thanks for checking though!

**Comment by moganesyan** [comment]
@jplauri Did you manage to figure out how to connect Heroku's PostgresDB to label studio? I'm having the same issues. Thanks!

**Comment by jplauri** [comment]
@moganesyan I don't think I did, but instead ran label-studio on-premises w/o Heroku.
