### ISSUE TITLE
User groups for better control of permissions

### ISSUE THREAD

**Issue by kenlee-ga** [heartexlabs/label-studio#859]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be useful to define user groups with different permissions for actions like:
- Deleting projects
- Inviting users via link
- View/work on projects

For example, an Admin group would be able to:
- Delete any project
- Delete user accounts
- Invite any user
- View and work on all projects (e.g. Projects 1 - 10)

Users in Group A would be able to:
- View and work on only Project 1

**Describe alternatives you've considered**
According to the documentation, user management actions are limited to account creation, invitations by link, and password reset. 

**Additional context**
N/A

**Comment by makseq** [comment]
@kenlee-ga This feature is implemented in our platform: www.heartex.com.
