### ISSUE TITLE
Error while bulding from source

### ISSUE THREAD

**Issue by Nuccy90** [heartexlabs/label-studio#862]
I'm trying to build from source because I want to get a fix for an issue with the mouse pointer in audio playback. I get the following error:  

`error: MarkupSafe 1.1.1 is installed but MarkupSafe>=2.0.0rc2 is required by {'Jinja2'}`  

I also tried to run LS afterwards and I get this error:  

`pkg_resources.ContextualVersionConflict: (MarkupSafe 1.1.1 (/home/elena/Workspace/Annotation_sound/.ls_source_env/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg), Requirement.parse('MarkupSafe>=2.0.0rc2'), {'Jinja2'})`

This happens on Ubuntu 20.04 and I am installing in a blank environment.

**Comment by makseq** [comment]
Try this one:

```
cd label-studio
python3 -m venv ls-env
source ls-env/bin/activate
pip install -e .
label-studio
```

**Comment by niklub** [comment]
@Nuccy90 please reopen if Max's suggestion won't work for you

**Comment by arianpasquali** [comment]
Same error here on Ubuntu 20.04. 

I run pipdeptree to check conflicts and this is what I get

```
Warning!!! Possibly conflicting dependencies found:
* Jinja2==3.0.0
 - MarkupSafe [required: >=2.0.0rc2, installed: 1.1.1]
```

**Comment by makseq** [comment]
@arianpasquali It looks strange, because we don't use Jinja2.. Are you on a fresh python env? Could you check that LS was installed from scratch into the new env? 

```
cd label-studio
python3 -m venv ls-env
source ls-env/bin/activate
pip install -e .
label-studio
```
