### ISSUE TITLE
Conditionnal choice not showing

### ISSUE THREAD

**Issue by rizziemma** [heartexlabs/label-studio#865]
Hello,

I hope this isn't a duplicate, i didn't found other issues mentioning this.

I tried the "Conditionnal classification" example on the playground and noticed it is not working. The second choice isn't showing up when selecting "Positive". Also, when trying the Three Level Classification, the 2nd level is effectively showing up when selecting any option of the first choice, but the 3rd level doesn't work. My guess is the problem comes from the **whenChoiceValue** option. 

I tried on Firefox and Chromium. I wasn't able to make it work on my local-deployed instance either.

Thanks!

**Comment by rizziemma** [comment]
Update : problem seems to occur only in playground, i finally got it working on my instance!

**Comment by makseq** [comment]
Yes, the playground uses an outdated version of LSF.
