### ISSUE TITLE
Undo and eraser don't work in pixel annotation tool

### ISSUE THREAD

**Issue by royschwartz2** [heartexlabs/label-studio#867]
**Describe the bug**
When using pixel annotation, undo doesn't work. Instead of undoing the last brush stroke it undos pixel by pixel. The eraser tool (assuming that the button with a scissors icon is an eraser) doesn't do anything. 

**To Reproduce**
Selecting the label and annotating, then pressing the undo button. Selecting the scissors button and applying to existing annotation. 

**Expected behavior**
- Undo of last brush stroke with undo
- Erasing of previous brush stroke with the scissors tool

**Environment (please complete the following information):**
 - OS: Tried on Linux Ubuntu 20.04, MacOS Big Sur 11.3
 - Label Studio Version 1.01

**Comment by makseq** [comment]
Hope the latest version works well.

**Comment by royschwartz2** [comment]
@makseq It does! Thanks!

**Comment by ainnotate** [comment]
This issue still seems to be on the latest version 1.6.0.  Any updates on this?
