### ISSUE TITLE
NER - Can't import preannotations using Api POST call - LS 1.0.1

### ISSUE THREAD

**Issue by amtam0** [heartexlabs/label-studio#869]
**Describe the bug**
I'm trying to make a POST call to preannotate tasks, by following the article https://labelstud.io/guide/predictions.html. 
The response is 201 but result content is empty.

**To Reproduce**

- Docker command (access link : http://0.0.0.0:10004)

`docker run -it -p 10004:8080 -v `pwd`/mydata:/label-studio/data --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true --env LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files -v `pwd`/myfiles:/label-studio/files heartexlabs/label-studio:latest
`
- Data used (some text files put inside /label-studio/files/data) : https://www.kaggle.com/shivamkushwaha/bbc-full-text-document-classification

- labeling  interface (xml) :

```
<View>
  <Relations>
    <Relation value="org:founded_by"/>
    <Relation value="org:founded"/>
  </Relations>
  <Labels name="label" toName="text">
    <Label value="Organization" background="orange"/>
    <Label value="Person" background="green"/>
    <Label value="Datetime" background="blue"/>
  </Labels>
  <Text name="text" value="$text" valueType="url"/>
</View>
```
- Added local Target & local Source Storage in UI (/label-studio/files/data_out & /label-studio/files/data). **_Treat every bucket object as a source file_** is toggled

- API CALL for preannotating task 6 : 

`curl --request POST -H 'Authorization: Token MYTOKEN' -H "Content-Type: application/json" -d '{"data":{"text":"/data/local-files/?d=data/138.txt"},"predictions":[{"result":[{"value":{"start":6,"end":13,"labels":["Person"]},"id":"VJxIliQcbWR","from_name":"label","to_name":"text","type":"labels"}]}]}' http://0.0.0.0:10004/api/tasks/6/annotations/`

**Expected behavior**
Filled annotations in UI

**Screenshots**
attached UI error displayed

![Screenshot from 2021-05-01 23-40-13](https://user-images.githubusercontent.com/17755198/116795876-663f1480-aad8-11eb-8061-c89fd953743e.png)

![Screenshot from 2021-05-01 23-40-11](https://user-images.githubusercontent.com/17755198/116795875-663f1480-aad8-11eb-9342-2fd6ff4d5b77.png)

![Screenshot from 2021-05-01 23-40-25](https://user-images.githubusercontent.com/17755198/116795874-65a67e00-aad8-11eb-92a3-fedede25211c.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 / Docker version 19.03.14
 - Label Studio Version 1.0.1

**Additional context**
The annotation used for the Api call was created in another environment of LS UI, extracted from label_studio.sqlite3 > table task_completion > column result. I wanted to test it as is, I tried to edit the Ids like mentioned but still same issue.
Am I doing something wrong ?
Thanks

**Comment by makseq** [comment]
@amtam0 Seems you are using wrong endpoint API: 

```
curl --request POST -H 'Authorization: Token MYTOKEN' -H "Content-Type: application/json" -d '{"data":{"text":"/data/local-files/?d=data/138.txt"},"predictions":[{"result":[{"value":{"start":6,"end":13,"labels":["Person"]},"id":"VJxIliQcbWR","from_name":"label","to_name":"text","type":"labels"}]}]}' http://0.0.0.0:10004/api/tasks/6/annotations/
```

It should be `http://0.0.0.0:10004/api/tasks/6/`

**Comment by amtam0** [comment]
Sorry for late reply
I managed to import tasks using a json file, which I find more convenient for my usage
`curl -H 'Authorization: Token MYTOKEN' -X POST 'http://0.0.0.0:10004/api/projects/ID/import' -F 'file=@/path_to/tasks.json'`
Thanks
