### ISSUE TITLE
Error code : Out of Memory

### ISSUE THREAD

**Issue by abhay-kum** [heartexlabs/label-studio#870]
**While using the label studio for 10-30 min it hangs and showing Error code: Out of Memory**
We are using the label studio for multiclass labeling of images, where we have around 80k datapoint, the images are loaded by URL, initially, it working fine, but after using it 20-30 min the browser got hang and showing error code: out of memory.

 - OS: Ubuntu 18.04.5
 - Label Studio Version 1.0.1

![Screenshot (20)](https://user-images.githubusercontent.com/27910202/116838680-e6ef3500-abec-11eb-9bab-01ee2e30d94f.png)

**Comment by makseq** [comment]
@nicholasrq

**Comment by pjvalla** [comment]
Our team has to restart the browser once the UI performance becomes unbearably slow.  This is a viable work-around, but it does point to a memory leak.  The current project contains ~3700 time-series tasks.  Some of the time-series are quite large, on the order of ~200K points.

**Comment by hlomzik** [comment]
Oh, sorry about this :(
So to be clear — does it happen when you label one task for some time? Or does it after digging through a lot of tasks? Or a few of them? Profiling is especially challenging when you have 3 libs sticked together and we are trying our best to improve the performance, so it's better to know what to look for. Thanks!

**Comment by pjvalla** [comment]
It happens after digging through a lot of tasks.

**Comment by makseq** [comment]
Relative: https://github.com/heartexlabs/label-studio/issues/1706

**Comment by pjvalla** [comment]
Task sidebar causing UI slow downs.  When selecting Label Task as Displayed, then no slow UI issue.

**Comment by makseq** [comment]
Thank you for your notice!

**Comment by makseq** [comment]
We did a lot of optimizations in the latest LS versions, hope it works smoothly now.

**Comment by ingura** [comment]
Its image/data loading time is still degrading significantly after browsing the data for about 30 min
