### ISSUE TITLE
Export image path for local file storage is unclear

### ISSUE THREAD

**Issue by Terizian** [heartexlabs/label-studio#878]
I've installed Label Studio using conda and I've tried a test project. I imported a few images from a local directory (which is where I have most of my data) and I've exported the files to CSV. 

Here are samples from the CSV:
/data/upload/g_mLPkNFG.jpg
/data/upload/h_DDD32r2.jpg
/data/upload/j_82HKjCw.jpg
/data/upload/k_zGYJffu.jpg
/data/upload/l_i2yscCs.jpg
/data/upload/m_m0sFmhA.jpg
/data/upload/n_FwNnubF.jpg
/data/upload/p_VtQekT6.jpg

I'm unsure how to get the original image paths in order to use this data for model training.

**Comment by makseq** [comment]
Is your LS on local machine or using docker? Is your ml backend on the same machine or on the separated instance?

**Comment by Terizian** [comment]
Local machine and I don't have an ML backend set up within the application. I was hoping I could export the data and use it in another application I have for training. Is this possible?

**Comment by makseq** [comment]
LS writes the working directory at startup in console, you can go to this directory and get the files from it. Is it suitable for you?

**Comment by Terizian** [comment]
Yes this is suitable. I was wondering if it's possible to keep track of the old names as well in the export? The reason for that is because I have some information in the file names such as location and data/time that I usually use to ensure my data is representative of the "real world"

**Comment by makseq** [comment]
In this case it's better to use Local storage
https://labelstud.io/guide/storage.html#Local-storage

**Comment by Terizian** [comment]
This fits my requirements completely! Thanks for your help and your prompt responses
