### ISSUE TITLE
Multiple labels for same image polygon

### ISSUE THREAD

**Issue by vijaygill** [heartexlabs/label-studio#89]
Hi,

Apologies if this feature is already present (I have not been unable to find it).

I am working on a (pet) project for classification and instance segmentation of vehicles. So I am going to use image polygon feature of label-studio. For that

- I need broader classification like car, truck, scooter, bus, etc.
- More specific classification (e.g. in cars, their make) like Ford, Toyota, BMW etc.
- More specific classification (e.g. in cars, their models)
- More specific classification (e.g. in cars, their colours)

For the above, if a polygon can be given multiple labels, I will be able top write data generator for different classifications.

Thanks
Vijay

**Comment by vijaygill** [comment]
And my coffee kicked in and I found the solution!!!

I can achieve it by repeating "PolygonLabels" element in the configuration.

**Comment by deppp** [comment]
@vijaygill Hey, thanks for this ticket. To follow-up, as you've already discovered, there is `Choices` tag with multiple `Choice` children. In a future version, we will be integrating a more powerful taxonomy to define multi-level relationships.

**Comment by vijaygill** [comment]
> @vijaygill Hey, thanks for this ticket. To follow-up, as you've already discovered, there is `Choices` tag with multiple `Choice` children. In a future version, we will be integrating a more powerful taxonomy to define multi-level relationships.

This fantastic!!!! I am looking for multi-level relationships but I found label-studio to be extremely easy to use so I was thinking of creating my own process of applying hierarchy using another my own code. But now it seems I can wait and have this facility as first-class citizen in label studio!
