### ISSUE TITLE
Validation Error Blocks Deletion of a Label Even After Updating Annotations

### ISSUE THREAD

**Issue by JustinGovender** [heartexlabs/label-studio#892]
**Describe the bug**
A validation error blocks the removal of labels that have existing annotations attached to them in the labeling interface (normal behaviour), however updating tasks by removing those labels does not remove the validation error even though there are no existing annotations using them anymore. 

**To Reproduce**
1. Create a label
2. Label a task with that label
3. Update that task by removing the label
4. Try to delete the label from the labeling interface

**Expected behavior**
Once tasks have been updated so that the label is no longer present in any annotation results the label should be able to be deleted from the labeling interface.

**Environment (please complete the following information):**
 - OS: Windows 10/MacOS
 - Label Studio Version 1.0.1

**Comment by niklub** [comment]
Hi, @JustinGovender ! It's a known issue - config validator fails after doing consequent update and removing steps on annotation. Hope we gonna fix it very soon in the upcoming release, just give us a little time :)

**Comment by niklub** [comment]
This issue has been fixed in the `label-studio==1.0.2` version
