### ISSUE TITLE
Collect annotator information & filter by annotators

### ISSUE THREAD

**Issue by aladagemre** [heartexlabs/label-studio#893]
**Is your feature request related to a problem? Please describe.**
When doing multi-user labeling, I want to 

* see who made the annotation (currently there's no sign of who did the annotation)
* filter the data to see which posts user X annotated.

**Describe the solution you'd like**
* Collecting information about the user-annotation-datetime pairs so that we would know who made the annotations.
* Filtering by annotator in the tab filters would help us filter "tasks annotated by X (and/or Y)". 

**Describe alternatives you've considered**
Not any

**Comment by makseq** [comment]
@aladagemre Hi, please check the latest master branch, we have implemented annotator filters and a special column with annotators.

**Comment by aladagemre** [comment]
Thanks, I checked now and it works! 

However I have one more concern: https://github.com/heartexlabs/label-studio/issues/1052
