### ISSUE TITLE
Can I create completion JSON files using my own code (to migrate annotations from other sources)?

### ISSUE THREAD

**Issue by vijaygill** [heartexlabs/label-studio#90]
Hi,

I have some datasets which have annotations in JSON or CSV. I like this tool already (this is my first day of use!) and I am thinking of converting my other annotations into the format supported by label-studio.

Is the relation of a completion json file back to the image based on the "image" field in the "data" object of the JSON file?

I hope my question makes sense. Please ask if it needs to be rephrased.

**Comment by vijaygill** [comment]
I had a peek at db.py and it seems the index of a task is used as part of the JSON file name. (e.g. in 1.json, 2.json and so on, the 1,2 etc are the index of the task in task.json).

**Comment by deppp** [comment]
@vijaygill 

Hey,

I'd suggest taking a look at one of the `tasks.json` found in examples, it's basically a list of JSON objects. Each key in that object you can further use in the config, for example, a JSON file like this:

```json 
[{ "text": "Piece of text" }, { "text": "Piece of text" } ]
```

And config:

```html
<View><Text name="txt" value="$text"></Text></View>
```

As you can see `$text` will be connected to every object in the JSON file. If you create a completion for you will get `1.json` and `2.json`.

Please let me know if that answers your question.

**Comment by vijaygill** [comment]
@deppp 
Thanks for your reply. Thanks for clearing that up.
What I was looking for was how the relation of 1.json with first "text" or 2.json with second "text" (and so on is determined. To me it looks like following:
1. Task records in the tasks.json are given index starting from 1.
2. Completion files (1.json, 2.json andso on) are rerlated back to their tasks by the number that appears in their name (1,2,etc) and the index of the task as determined by above.

Please correct me if I am wrong.
