### ISSUE TITLE
Brush label distortions

### ISSUE THREAD

**Issue by iakremnev** [heartexlabs/label-studio#909]
**Describe the bug**
Certain actions can cause brush annotations to shift and scale, corrupting the annotation. Mostly happens when the annotated image is redrawn: zooming, changing UI zone sizes.

**To Reproduce**
Follow the attached video:

1. Select a task.
2. Zoom in to annotate with the brush tool.
3. Submit.
4. Get annotation distorted.

**Expected behavior**
Brush annotations are kept intact regardless the state of the image. Some quality assurance upon submitting annotations. 

**Screenshots**

https://user-images.githubusercontent.com/13620282/117795167-987a1000-b256-11eb-8a50-6f6f91f41c51.mp4

**Environment (please complete the following information):**
 - OS: Linux 64 bit
 - Label Studio Version 1.0.1
 - Browser: Firefox/Chromium

**Additional context**
Related discussion in slack: https://label-studio.slack.com/archives/CQ8LYPPJS/p1620660402258200?thread_ts=1620659738.257600&cid=CQ8LYPPJS

**Comment by triklozoid** [comment]
Fixed in Label Studio 1.2
