### ISSUE TITLE
Not working valueType="url" for HyperText when connected to S3

### ISSUE THREAD

**Issue by arubino** [heartexlabs/label-studio#911]
**Describe the bug**
I have synced a S3 bucket containing some HTML files and used the following settings for labeling

```javascript
<View>
  <Relations>
    <Relation value="org:founded_by"/>
    <Relation value="org:founded"/>
  </Relations>
  <HyperTextLabels name="label" toName="text">
    <Label value="Organization" background="orange"/>
    <Label value="Person" background="green"/>
    <Label value="Datetime" background="blue"/>
  </HyperTextLabels>
  <HyperText name="text" value="$text" valueType="url"/>
</View>
```
When I go to the labeling interface I only get the link text and not the html file that I would like to label (notice above that I have used the option `valueType="url"`)

```json
{
  "id": 9,
  "data": {
    "text": "https://<mybucket>.s3.amazonaws.com/doc1.html?<params>"
  },
  "annotations": [],
  "predictions": []
}
```

In addition, the task postgres table contains the following in the task column
```json
{
    "$undefined$": "s3://<myname>/doc1.html"
}
```

I would not expect this behavior according to what it is expressed in the documentation for `HyperText`: https://labelstud.io/tags/hypertext.html

This bug fix would be essential in order to work in a scalable way using HTML files, as a single LS instance does not have to load all the tasks data at once. 

**Expected behavior**
I would expect that the instance of label studio would only render one HTML task (taking the data from the URL) and not all of them. The tasks should be rendered as HTML from the URL. Just one task data at the time should be loaded in the LS instance and not all of them.

**Environment:**
```json
{
  "package": {
    "version": "1.0.1",
    "short_version": "1.0",
    "latest_version_from_pypi": "1.0.1",
    "latest_version_upload_time": "2021-04-05T19:13:41",
    "current_version_is_outdated": false
  },
  "backend": {
    "commit": "0da33d",
    "date": "2021-04-29 12:26:26 +0300",
    "branch": "master",
    "version": "1.0.1+50.g0da33d6.dirty"
  },
  "label-studio-frontend": {
    "commit": "1dd1b31dfdc9368849c65dff728a551f30ab2c86",
    "branch": "master",
    "date": "2021-04-12T09:15:53Z"
  },
  "dm2": {
    "commit": "7751a996682f145d651123af27286f4f392c293c",
    "branch": "master",
    "date": "2021-04-02T13:15:22Z"
  }
}
```

**Comment by arubino** [comment]
@makseq where in the backend was supposed to retrieve the data from the URL? I had a look but I did not find where it is supposed to do so for hypertext. I would like to help fixing the bug.

**Comment by makseq** [comment]
@arubino Unfortunately, it's not a backend problem. It's LSF problem - https://github.com/heartexlabs/label-studio-frontend/blob/master/src/tags/object/HyperText.js#L37.
However, if you are able to fix it, it will be very cool!
