### ISSUE TITLE
Unable to login with username and password : The email and password you entered don't match.

### ISSUE THREAD

**Issue by jagan1333** [heartexlabs/label-studio#917]
I'm trying to disable signup page and want to send invite link to members so I've added a admin user as follows to docker run command. It disabled the signup page but the problem is when I enter username and password in browser it says "The email and password you entered don't match."

docker run -itd -p 8080:8080 --env LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true --env LABEL_STUDIO_USERNAME=lsadmin --env LABEL_STUDIO_PASSWORD=******** -v /label-studio/data:/label-studio/data heartexlabs/label-studio:latest 

![image](https://user-images.githubusercontent.com/30555574/118114099-c4d38f00-b404-11eb-8f91-a91038952bff.png)

Further I tried below command without username and password in the command,
docker run -itd -p 8080:8080 --env LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true -v /label-studio/data:/label-studio/data heartexlabs/label-studio:latest 

But here I don't know what is the default username and password if we don't set through environment variables.

I tried by entering into container (exec) and tried below commands to change password but still unable to login.

$docker exec -it container_id bash
![image](https://user-images.githubusercontent.com/30555574/118114792-b2a62080-b405-11eb-83cc-734f3a0738d2.png)

**Comment by jagan1333** [comment]
One more question if I want to enable Multisession mode in docker installation how  can I do that.

Thanks

**Comment by makseq** [comment]
@jagan1333 What multisession mode do you mean? If you are talking about multimode in LS, it was deprecated since 1.0 and there is no multisessions in it. But LS 1.0 doesn't need it, because it has multi-projects and multi-users.

**Comment by makseq** [comment]
@jagan1333 
* Try to reset database (remove label_studio.sqlite3 file) and then restart docker with username and password. Maybe you set the password before and now you are trying to use an old one? 
* Run `label-studio shell` and write:
```
u = User.objects.get(email='lsadmin')
u.set_password('12345')
u.save()
```
and then try to re-login using 12345 as password. 

Also I wouldn't recommend to user username without @, it's better to make the login as email, e.g.: lsadmin@ls

**Comment by Hmr-ramzi** [comment]
I had the same issue. @jagan1333 After fixing the username to be lowercase and including @ as @makseq suggested ex: "code@example.com" it worked fine. Before i was trying something like a person name "Myname" and it did not work.

**Comment by jagan1333** [comment]
@Hmr-ramzi @makseq  Thank you very much for the response, it's resolved. We can close this out.
