### ISSUE TITLE
Inconsistent build from source commands github vs docs

### ISSUE THREAD

**Issue by JustasB** [heartexlabs/label-studio#918]
**Describe the bug**
In [docs](https://labelstud.io/guide/install.html#Install-from-source) it says to use this command to build:

`python setup.py develop`

But in [github readme](https://github.com/heartexlabs/label-studio#install-for-local-development), it says to use this command:

`pip install -e .`

**Expected behavior**
Unless this is by design, the commands should be the same

**Comment by makseq** [comment]
@JustasB Thank you very much for your suggestion. 

@smoreface Could you leave only `pip install -e .` in the docs please?

**Comment by smoreface** [comment]
Yes, I'll fix this up! thanks @JustasB
