### ISSUE TITLE
Unable to view tasks at all

### ISSUE THREAD

**Issue by visualcortex-team** [heartexlabs/label-studio#924]
**Describe the bug**

We're trying to run a simple bounding box task. Not sure if relevant, but we're importing data from local storage. We can see image previews, but are unable to progress any further.

Looking at the debug logs, we get this stack trace:
```
Traceback (most recent call last):
  File \"/usr/local/lib/python3.8/dist-packages/rest_framework/views.py\", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File \"/label-studio/label_studio/data_manager/api.py\", line 233, in get
    serializer = self.get_serializer_class()(task, many=False, context=context)
  File \"/label-studio/label_studio/data_manager/api.py\", line 211, in get_serializer_class
    return TaskSerializer
NameError: name 'TaskSerializer' is not defined
```
We're using the `:latest` docker image, updated 5 days ago.

**To Reproduce**
1. Setup local storage using prerequistes at https://labelstud.io/guide/storage.html#Prerequisites
2. Sync data source
3. Go to the project tasks
4. Notice thumbnail of selected task disappears, no error in UI but error in console

**Expected behavior**
Task interface to load

**Screenshots**
![image](https://user-images.githubusercontent.com/82630536/118453455-958d8c80-b73a-11eb-8fe4-6be5f8038472.png)

**Environment (please complete the following information):**
 - Browser: Google Chrome Version 90.0.4430.212 (Official Build) (arm64)
 - Label Studio Version: `:latest` Docker tag
 - Runtime Environment: Kubernetes Docker (GKE)

**Additional Information**

Offending line appears to be https://github.com/heartexlabs/label-studio/blob/833011f0390620009542474171f6cd8783d870a2/label_studio/data_manager/api.py#L211

**Comment by makseq** [comment]
@visualcortex-team Please, update to the latest master, this problem must go away.

**Comment by niklub** [comment]
Hi! This problem has been fixed in Label Studio 1.0.2. You can update the docker image to the `heartexlabs/label-studio:latest`, or `heartexlabs/label-studio:1.0.2`

**Comment by OmaymaS** [comment]
Is the latest modifications merged to master here, or should the branch /release/1.0.2 be used?

**Comment by makseq** [comment]
You can use the master.
