### ISSUE TITLE
import crash

### ISSUE THREAD

**Issue by GLivshits** [heartexlabs/label-studio#940]
Hello. Label studio crashes on attempt of uploading 13000 jpg files. What is the way to upload large dataset without loading one-by-one?

**Comment by GLivshits** [comment]
The highest number for one-time upload is between 1000 and 1200, as for me. Dataset is around 40k.

**Comment by makseq** [comment]
Hello, I'd recommend to use the Local Storage - https://labelstud.io/guide/storage.html#Local-storage.
