### ISSUE TITLE
Uploading individual .txt files as individual tasks fails in multiple ways

### ISSUE THREAD

**Issue by vpm238** [heartexlabs/label-studio#954]
**Describe the bug**
For the NER usecase when each text file is a separate task; the export of annotated data exports only text file names for text content; even though there is no issues with labelling the content

**To Reproduce**
1. Set up NER labelling Task with following Config 
(I used the valueType="url" based on recommendation here to have each .txt file as a separate task : https://labelstud.io/guide/tasks.html#Plain-text; it reads "If you want to import entire plain text files without each line becoming a new labeling task, customize the labeling configuration to specify valueType="url" in the Text tag. See the Text tag documentation")

```<View>
  <Labels name="label" toName="text">
    <Label value="label1" background="#FFA39E"/>
    <Label value="label2" background="#D4380D"/>
    <Label value="label3" background="#FFC069"/>
    <Label value="label4" background="#AD8B00"/>
    <Label value="label5" background="#D3F261"/>
    <Label value="label6" background="#389E0D"/>
    <Label value="labe7" background="#5CDBD3"/>
  </Labels>
  <Text name="text" value="$text" valueType="url"/>
</View>
```

2. Upload a few .txt files and Import as Time Series (only Time Series option keeps the each .txt files as a separate task)
3. Annotate the data
4. Try to Export the annotated data through API or UX and in any format. The annotated data does not contain content of .txt files

**Expected behavior**
1) The text content is visible in the exported data
2) When uploading .txt files; there is an option to upload it as .txt or .txtl (text or textLine similar to json or jsonl)
3) Perhaps a new valueType param in Text tag to indicate text or textline

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. v1.01]

**Additional context**
https://label-studio.slack.com/archives/C01SKFX54QK/p1621488696013000

**Comment by 3nuc** [comment]
I wanted to do the same thing as you - import a whole text file as a single task.
I reporduced what you said and I can't reproduce - exporting shows me labels.

1. I set up a project with the NER template, but I needed to change the valueType="url" (even though the preview showed me errors that it couldn't find a file with the url from the example - well, the example (text about Jimi Hendrix) is plaintext, so no wonder).
![image](https://user-images.githubusercontent.com/5359825/120110359-67ae3c00-c16d-11eb-8a23-3e15b9fe903f.png)

 I clicked ok anyways (though it'd be cool if the example detected that I used valueType="url" and switched example text to an url).  The template I used is in the screenshot also.

2. Upload a .txt file as time series (this was *very* confusing - I'm uploading a text file and the app is asking me if it should interpret TSV as time series or separate tasks? I'm uploading plain text, not TSV or CSV). I have similar findings that uploading as time series is the only way to get Label Studio to interpret the file as a single task.

3. Annotate some text:
![image](https://user-images.githubusercontent.com/5359825/120110480-f58a2700-c16d-11eb-84ad-0f9c0216b3c7.png)

4. Export as CSV:
![image](https://user-images.githubusercontent.com/5359825/120110500-0dfa4180-c16e-11eb-8110-2cb1432bfa13.png)

5. The exported CSV contains annotations that seem to be correct:
![image](https://user-images.githubusercontent.com/5359825/120110532-2702f280-c16e-11eb-9259-4e6c59c02df1.png)

I downloaded the Label Studio Docker image 2 hours ago, so my version is "from today" :P Below is more detailed info
```
# docker -it exec label-studio /bin/bash
root@0a7d94e30c07:/label-studio# pip list | grep label-studio
label-studio               1.0.2         /label-studio
label-studio-converter     0.0.28
```

**Comment by vpm238** [comment]
The issue is annotated data needs to contain the original data / content of uploaded files in all formats including csv. Having just the file names requires people to manually merge and create a dataset. Also, exporting this in Standard format like CoNLL from this point is just garbage output that cannot be used

**Comment by mamafun** [comment]
Release 1.2.0 failed at step 2. Please see the attachment. Thank you for any help.
![image](https://user-images.githubusercontent.com/3885551/130770653-8add428a-79b8-4e5d-949e-9fac5d85be47.png)

**Comment by ALIYoussef** [comment]
The issue is still there. Choosing the "url" as value type makes the data text saving the path file not the source text
![test](https://user-images.githubusercontent.com/16019112/146829368-3d435256-fe3f-48ac-989a-417c164c5d82.PNG)

**Comment by smoreface** [comment]
@ALIYoussef can you set your Text tag to also include "saveTextResult" to "true"? 
https://labelstud.io/tags/text.html

**Comment by makseq** [comment]
@ALIYoussef If you try to export data that was imported with valueType = "url", then you will always get urls in your "text" field, this is the expected behavior.

**Comment by ALIYoussef** [comment]
@smoreface  @makseq  thank you for replying. By setting the saveTextResult ="yes" will save the tag only (i.e., the annotation text but the text includes the tag). So, in the field "data" the "text" will include only the the URL. 
Is there a way to save the text included in the "file.txt" in the data dictionary? or this operation should be performed after exporting  the annotation!
![image](https://user-images.githubusercontent.com/16019112/146942226-3ff19c52-b7ab-4de5-a1c6-db4a4f3d7ad3.png)

**Comment by ALIYoussef** [comment]
> @ALIYoussef If you try to export data that was imported with valueType = "url", then you will always get urls in your "text" field, this is the expected behavior.

So, no way to save the full text in the file within the data dictionary when the valueType = "url"?

**Comment by ALIYoussef** [comment]
> @ALIYoussef can you set your Text tag to also include "saveTextResult" to "true"? https://labelstud.io/tags/text.html

By setting the saveTextResult ="yes" will save the tag only (i.e., the annotation text but not the text includes the tag). So, in the field "data" the "text" will include only the the URL.
Is there a way to save the text included in the "file.txt" in the data dictionary? or this operation should be performed after exporting the annotation! 
![image](https://user-images.githubusercontent.com/16019112/146943315-a27b63ce-6125-4fce-b849-c0af0d0b05d1.png)

**Comment by dvivarelli** [comment]
using last docker build, the workaround with  valueType="url"  works

<Text name="text" value="$text" granularity="word" valueType="url"/>

**Comment by ALIYoussef** [comment]
> using last docker build, the workaround with valueType="url" works

Thank you. I will try that. So, now does it save the text included in the text instead of the url path in the annotated data?

**Comment by teebu** [comment]
I'm seeing the path not the actual text of my file with 1.16rc5

![image](https://user-images.githubusercontent.com/5531844/200686083-e93ed550-58e6-4eb7-95d1-e19f3f0916ab.png)

**Comment by alsim91** [comment]
> I'm seeing the path not the actual text of my file with 1.6.0rc5
> 
> <img alt="image" width="1248" src="https://user-images.githubusercontent.com/5531844/200686277-60ab8582-5e3d-4f82-9a8a-247f3b4489dc.png">
> 
> ![image](https://user-images.githubusercontent.com/5531844/200686083-e93ed550-58e6-4eb7-95d1-e19f3f0916ab.png)
> 
> When I choose the other option I get actual data.
> 
> ![image](https://user-images.githubusercontent.com/5531844/200686614-7e9bfacf-bcf2-41d3-b279-a074daee0d4b.png)

Hi, did you found a solution? I have the same problem. My version of LS is 1.7.1

**Comment by makseq** [comment]
what specific problem do you have?

**Comment by alsim91** [comment]
> what specific problem do you have?

i have exactly the same problem of teebu.
I have LS 1.7.1 installed on docker, when i upload a txt (choosing NER template) in the source tag i see this:
![image](https://user-images.githubusercontent.com/126158504/221127359-752edb81-db16-4e86-b1d6-d01dad6f3855.png)


When i start labeling my task, it shows correctly the content of the txt and i submit that task. When i try to export in json or json min i see again the url path instead of the content of the txt.

I set the template in this way:
![image](https://user-images.githubusercontent.com/126158504/221127719-646f018e-2409-49e1-bb87-c944e67f0058.png)


i tried to reinstall docker and label studio, i tried to update it but with no success

**Comment by makseq** [comment]
@alsim91 It's the correct behaviour by design, LS backend avoids touching user's data by security reasons. 
If you want to have texts in export, you should make tasks with text inplace.

1. When import txt file you should choose "List of tasks" 
2. You `<Text>` tag shouldn't have `valueType="url"`
3. After import you will see text in "Source for task"
4. If you need to import text with newlines as one task for labeling, you have to use JSON file for import instead of txt.

**Comment by kehao95** [comment]
I think I had the same issue. And I want to explain why it is confusing to the end users. 
So I wanted to import a plain text document as one task. Let's say the content is:
`my-doc.txt`
```
this is the first line
this is the second line
this is the third line
```

So when I import it into label studio. It as me to choice `Treat CSV/TSV as: List of tasks/Time Series or Whole Text File` which is confusing becasuse I want to import a plain text document instead of CSV/TSV file. But any way 

**when I chose `List of tasks`**
I'll get 3 tasks, which is not expected, I want one task instead of 3. 
```
task1: this is the first line
task2: this is the second line
task3: this is the third line
```

**when I chose `Time Series or Whole Text File`**
I get one task but not data imported
```
task1: `/data/my-doc.txt`
```

What I'm actually expecting is:
```
task1: this is the first line\nthis is the second line\nthis is the third line
```

## tempory solution 
conver the plain text into JSON before import
```json
{
  "id": 1,
  "data": {
    "value": "this is the first line\nthis is the second line\nthis is the third line"
  },
  "annotations": [],
  "predictions": []
}
```

Don't know if we can make the behavior more intuitive to the user.

**Comment by makseq** [comment]
when I chose Time Series or Whole Text File
I get one task but not data imported

task1: `/data/my-doc.txt`

Have you tried to use valueType="url" in the labeling config for the Text tag?

**Comment by ghassenhed** [comment]
still no solution ?

**Comment by surakumar-clgx** [comment]
how can i get content of the file with annotations after exporting?

**Comment by Gmgge** [comment]
可以参考我的分支中该[提交](https://github.com/HumanSignal/label-studio/commit/bf2dc91dccb53f6eee349d3bdecd1d3dfa43c88a)，该操作可以的实现：从ui上传txt时，选中Time Series or whole Text File时，可以解析整个文本的内容赋值给data，而不是以上传文件类型，即实现
{
  "id": 1,
  "data": {
    "value": "this is the first line\nthis is the second line\nthis is the third line"
  },
  "annotations": [],
  "predictions": []
}
