### ISSUE TITLE
Using custom annotation template to annotate based on multiple images

### ISSUE THREAD

**Issue by dsmanl** [heartexlabs/label-studio#958]
Dear all,

first of all thanks a lot for all of your efforts! I am new to Label Studio and trying to review annotated images on surface defects (object detection task). For a single defect, we typically have multiple images applying different filters and image processing techniques. Hence, a defect might be clearly visible on one image but less pronounced on another.

I would like to
1.  use a custom annotation template to show for example two images next to each other to increase annotation quality by being able to derive information from different image types and
2.  if possible to show a bounding box drawn on the first image on the second image as well - it is only necessary to annotate one of them, since they share the same sizing, etc.

I am following the following steps:
*  Create a new project
*  Create custom annotation template
*  Import/upload two images (e.g. `normal_102.jpg` and `normal_103.jpg`) to Label Studio
*  Import/upload pre-annotated data (e.g. `example_task.json`)

Custom annotation template:
```xml
<View>
  <View style="display: flex;">
    <View style="width: 49%; margin-right: 1.99%">
      <Image name="img-left" value="$image"/>
      <RectangleLabels name="label" toName="img-left">
        <Label value="Defect Type 1" background="#ffa39e"/>
      </RectangleLabels>
    </View>
    <View style="width: 49%;">
      <Image name="img-right" value="$image2"/>
    </View>
  </View>
</View>
```

`example_task.json`:
```json
[{
  "data": {
    "image": "/data/upload/normal_102.jpg",
    "image2": "/data/upload/normal_103.jpg"
  },
  "predictions": [{
     "result": [
      {
        "id": "result1",
        "type": "rectanglelabels",        
        "from_name": "label", "to_name": "image",
        "original_width": 500, "original_height": 500,
        "image_rotation": 0,
        "value": {
          "rotation": 0,          
          "x": 36.2, "y": 31.4,
          "width": 30.4, "height": 41.6,
          "rectanglelabels": ["Defect Type 1"]
        }
      }]
  }]
}]
```

The custom annotation template shows a promissing result in the preview:
![grafik](https://user-images.githubusercontent.com/67360039/119118174-3ffefb80-ba2a-11eb-9f8d-7a1cd63ecebb.png)

But when I jump into the annotation task, I am getting the following error:
![grafik](https://user-images.githubusercontent.com/67360039/119117932-04643180-ba2a-11eb-96c1-3853328eaf37.png)

I would already appreciate any help with regard to bullet point 1 mentioned above (being able to display two images next to each other, while only annotating one of them) as this would provide a huge benefit for us.

I am using the Label Studio Docker image on MacOS Big Sur (11.3.1):
```
heartexlabs/label-studio:latest
Digest:sha256:529d2023ca23225963e5fc3f2f404d3946f56219f29558624980c45b43222c6e
```
and Chrome browser with version 90.0.4430.212 (Official Build) (x86_64).

Thanks a lot!

**Comment by makseq** [comment]
@dsmanl 

Hello, 
I see an error in your prediction (as minimum this could lead to this fail):

```
 "result": [
      {
        "id": "result1",
        "type": "rectanglelabels",        
        "from_name": "label", "to_name": ====> "image" <=====, 
```

=>

```
        "from_name": "label", "to_name": ====> "img-left" <=====, 
```

**Comment by dsmanl** [comment]
Thanks a lot, @makseq!

Your advice was really helpful, I am now able to see multiple images next to each other. 

Is there a way to show a bounding box drawn on the first image on the second image as well - it is only necessary to annotate one of the images, since they share the same sizing, etc?

Thanks a lot!

**Comment by makseq** [comment]
@dsmanl it is possible, but if you want to see it in realtime you have to inject a custom js code to label studio.
