### ISSUE TITLE
Can not draw rectangle on top of another (CTRL+Mouse-Dragging stopped working)

### ISSUE THREAD

**Issue by danielspicar** [heartexlabs/label-studio#959]
**Describe the bug**
In v. 1.0.1 I could draw a rectangle (bounding box) on top of another bounding box. In v 1.0.2 this sopped working. Using the same procedure I cannot draw a new bounding box.

**To Reproduce**
1. Draw a large rectangle bounding box.
2. Draw a second rectangle bounding box inside the previously drawn bounding box while pressing and holding the CTRL key. This will fail. The previously drawn rectangle will be moved instead. A  new and very small rectangle appears at the point where the drawing began but it can not be dragged into its shape without reselecting to modify its shape.

**Expected behavior**
When drawing the second rectangle on top of the first while pressing the CTRL key, I should be able to draw the second rectangle just like the first one and it should be placed "on top" of the first rectangle.

**Environment (please complete the following information):**
 - Running in Docker Container: heartexlabs/label-studio:latest
 - Label Studio Version 1.0.2
 - Chrome web browser (90.0.4430.212)
 - OS: Windows 10

**Additional context**
I think this hotkey was undocumented. However is is extremely important for my use case to be able to draw bounding boxes on top or inside of each other.

**Comment by makseq** [comment]
@danielspicar Thank you for your report, I've reproduced this bug too. 

https://user-images.githubusercontent.com/501780/119240835-1b567100-bb5b-11eb-8915-a95c575bbfe9.mp4

**Comment by makseq** [comment]
This bug was fixed in [release/1.1.0](https://github.com/heartexlabs/label-studio/tree/release/1.1.0). Feel free to reopen if you have this problem again.
