### ISSUE TITLE
license mismatch readme vs setup.py

### ISSUE THREAD

**Issue by dehesselle** [heartexlabs/label-studio#960]
**Describe the bug**
The readme states Apache-2.0 license but setup.py states MIT. The info from setup.py is the one shown on PyPi. Which license is it?

**To Reproduce**
Open readme and setup.py and compare.

**Expected behavior**
Readme and setup.py state the same license or readme explains that multiple license are applied or ....

**Screenshots**
No screenshot necessary. Open readme, open setup.py and compare.

**Environment (please complete the following information):**
No environment necessary, text files only.

**Additional context**
Same issue here https://github.com/heartexlabs/label-studio-converter/issues/35

**Comment by makseq** [comment]
@dehesselle The correct one is Apache 2.0.

@smoreface could you fix our readme please?

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio/pull/962/files
