### ISSUE TITLE
why region is not highlighted when changing speaker

### ISSUE THREAD

**Issue by lxtadhamnawito** [heartexlabs/label-studio#965]
On using transcription per region, you have to follow these steps in-order to create a region:
1- choose "speaker 1" 
2- create the region by dragging on the waveform
3- select the region to see it highlighted 
---
but if you wanted to change the speaker after for any reason for the created region, the region is not highlighted anymore.
You have to select it again to be highlighted. 

https://user-images.githubusercontent.com/66368677/119263273-ae84ba80-bbde-11eb-920a-e8d1d5f5b952.mp4

**Comment by makseq** [comment]
Could you clarify - you mean the selected region becomes unselected after the label was changed?

**Comment by lxtadhamnawito** [comment]
What I mean, when you select a region it gets highlighted, but when you change the speaker while selecting it, it gets un highlighted like in the video (as if it's un-selected)

**Comment by lxtadhamnawito** [comment]
it's like if it's a code wise :
```
onSpeakerChange() {
if (speakerIsChanged)
  region.highlighted = false
}
```
this is just for clarification.

**Comment by lxtadhamnawito** [comment]
I looked in the code, and I found that in Label.js
`      // check if there is a region selected and if it is and user
      // is changing the label we need to make sure that region is
      // not going to endup without the label(s) at all
      if (region && sameObject) {
        if (labels.selectedLabels.length === 1 && self.selected) return;
      }`

I tried to set region.highlghted =true, in the else statment. but nothing was changed
also self.selected is always = false, so this condition above never succeed

**Comment by lxtadhamnawito** [comment]
I managed to solve this, thank you.
