### ISSUE TITLE
"Submit" doesn't work with text in TextArea

### ISSUE THREAD

**Issue by zakajd** [heartexlabs/label-studio#969]
**Describe the bug**
I'm using LS version 1.0.1 and when labelling I'd like to have optional field with comments from assessors. I used `TextArea` tag, but it doesn't work.
1. When text in entered into the box and Enter is pressed, text in the box doesn't automatically deletes and blocks pressing "Submit" button.
2. When looking through predictions via web interface, I see that comments are not saved anywhere.

**To Reproduce**
```
<View>
  <Header>
      </Header>
  <View style="display: grid; column-gap: 2px; grid-template: auto/1fr 1fr">
    <Image name="images" value="$images" maxWidth="512px" zoom="true" zoomControl="false"/>
  </View>
  <View style="display: flex;">
    <View style="flex: 50%">
      <Choices name="choice" toName="images">
        <Choice value="1"/>
        <Choice value="2"/>
        <Choice value="3"/>
      </Choices>
    </View>
    <View style="flex: 50%; margin-left: 1em">
      <Header value="Enter your comment:"/>
      <TextArea name="comment" showSubmitButton="true" editable="true" placeholder="Place for optional comment"/>
    </View>
  </View>
</View>
```

**Expected behavior**
TextAreas works properly, saving and displaying comments. 

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Label Studio Version: 1.0.1 with custom build to support multiple images https://github.com/heartexlabs/label-studio-frontend/pull/164#issuecomment-827503253

**Comment by makseq** [comment]
@zakajd Could you check this in release 1.1? We merged alternative versions of the image there and I hope the submit works as expected.

**Comment by mbrechet** [comment]
Hi @zakajd I think your problem is related to your template configuration. If think, your `<TexArea>` needs to have a reference to the data by using `toName` attribute which is mandatory. I face the same problem in another context. Your code should be like this :

```
 <TextArea name="comment" showSubmitButton="true" toName="images" editable="true" placeholder="Place for optional comment"/>
```

**Comment by zakajd** [comment]
@mbrechet Thanks, it solved my problem 👍
