### ISSUE TITLE
Taxonomy choices not pre-populated with predictions

### ISSUE THREAD

**Issue by irogers** [heartexlabs/label-studio#970]
**Describe the bug**
Taxonomy choices are not pre-populated in labeling view when predictions are present.

**To Reproduce**
1. Create new project
2. Import data
```json
[
  {
    "data": {
      "text": "You never believe what he did to the country"
    }
  },
  {
    "data": {
      "text": "You never believe what he did to the country"
    },
    "predictions": [
      {
        "result": [
          {
            "value": {
              "taxonomy": [
                [
                  "Online",
                  "Free"
                ],
                [
                  "Offline"
                ]
              ]
            },
            "from_name": "media",
            "to_name": "text",
            "type": "taxonomy"
          }
        ],
        "score": 0.95
      }
    ]
  }
]
```
3. Set config
```xml
<View>
  <Text name="text" value="$text"/>
  <Taxonomy name="media" toName="text">
    <Choice value="Online">
      <Choice value="UGC"/>
      <Choice value="Free"/>
      <Choice value="Paywall">
        <Choice value="NYC Times"/>
        <Choice value="The Wall Street Journal"/>
      </Choice>
    </Choice>
    <Choice value="Offline"/>
  </Taxonomy>
</View>
```
4. Navigate to project and the click "Label All Tasks:

**Expected behavior**
1. New annotation is pre-populated with prediction
2. Prediciton panel is shown (I toggled this in the Layout tab)

**Screenshots**
![image](https://user-images.githubusercontent.com/8482736/119461817-6087c800-bd40-11eb-91a8-b62b0b8eecf9.png)

**Environment (please complete the following information):**
 - OS: Ubuntu LTS 20.04
 - Label Studio Version 1.0.2

**Comment by smoreface** [comment]
Fixed with [version 1.3.0 release](https://github.com/heartexlabs/label-studio/releases/tag/v1.3.0).
