### ISSUE TITLE
Exporting imported data fails

### ISSUE THREAD

**Issue by timurlenk07** [heartexlabs/label-studio#976]
**Describe the bug**
When trying to export data that was imported with annotations, the export returns an empty JSON.

**To Reproduce**
1. Create a new project, with the OCR template
2. Upload any image, add some annotations (I added 2 boxes with texts)
3. Export as JSON in Label Studio Common Format
4. Select all data and delete them ("Delete tasks")
5. Import the downloaded JSON, check that the data import was successful as the annotations are there again
6. Export as JSON in Label Studio Common Format: **returns "[]"**

**Expected behavior**
I would expect that the export would return the **same** JSON file (with possibly different dates and IDs).
As the error only happens after the JSON import, I would suspect the error is probably at the *import* step.

**Environment (please complete the following information):**
 - OS: Ubuntu 16
 - Label Studio Version 1.0.2 (docker)

**Additional context**
Might be related to #889

**Comment by timurlenk07** [comment]
I have just tested it and it seems the problem persists in the current state of the master branch, as well.

**Comment by makseq** [comment]
@timurlenk07 https://github.com/heartexlabs/label-studio/pull/978 - could you check this branch please?

**Comment by timurlenk07** [comment]
It seems to be working fine now -- thanks!
