### ISSUE TITLE
Allow users to update task with pre-annotated data by API

### ISSUE THREAD

**Issue by tingjhenjiang** [heartexlabs/label-studio#979]
**Is your feature request related to a problem? Please describe.**
I create some tasks in label-studio ready for the annotation work. After I successfully built a prediction model, I would like to import predictions back to those tasks.
But when I update a task with "Update task" API patch command via http://IP:8080/api/tasks/{id}/, I found out that patch request with payloads that has a "predictions" key does not work out to update a single task so that a task would have prediction data, even though there is no error in HTTP request interacting with label-studio. The API document says that the "Update task" API patch command does not accept "predictions" in payload.
Because tasks have been created, I would not like to adopt the method ["Import pre-annotated data into Label Studio"](https://labelstud.io/guide/predictions.html), which would create new tasks.

**Describe the solution you'd like**
I got to read label-studio ML Backend tutorials, develop and test, and all these steps take me a lot of time.
I think it is a good option to allow Users to update a task with pre-annotated data by API "Update task" API patch command via http://IP:8080/api/tasks/{id}/.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by makseq** [comment]
@tingjhenjiang thank you for your request, I am working on it right now.

**Comment by tingjhenjiang** [comment]
@makseq Thank you!
I've read the docs, and I think there is insufficient information in how to use ML backend.
For example, I've launched a label-studio ML backend server on http://IP:9090 after I followed the tutorials. When I enter http://IP:9090, I see `{"model_dir":"./my_ml_backend","status":"UP"}`.
Next, I use a famous software "[Postman](https://www.postman.com/)", sending an HTTP request to http://IP:9090, which its payloads are from ["List project tasks API command"](http://192.168.10.200:8081/docs/api#operation/api_projects_tasks_list), and found out that I got nothing in return/response.
I have to check the codes, and finally I found out [label_studio_ml/api.py](https://github.com/heartexlabs/label-studio-ml-backend/blob/master/label_studio_ml/api.py) and the URL http://IP:9090/predict with a POST request are what I need.
It takes me about 2 days to achieve this.

**Comment by alex-eurec** [comment]
I have the same situation in my LS deployment, but I have one doubt: should we open another issue so we can keep track on the two problems separately?
1. PATCH call to the tasks endpoint of the Label Studio API with "predictions": [...] does not work.
2. Document API calls for LabelStudio ML backend so users are able to write or better adapt their own existent code

PS: I just want to remark that, the way documentation says to get predictions for all tasks in one project is pointing to the aforementioned PATCH usage, so any user trying to do it like it is written in the docuemntation, is going to face the same problem.
![image](https://user-images.githubusercontent.com/81571132/121677541-48d96f00-cab6-11eb-8b9f-e9d011584c09.png)

**Comment by makseq** [comment]
@alex-eurec Thank you for your reports, I hope this will be fixed soon.

**Comment by makseq** [comment]
Please, check this PR: https://github.com/heartexlabs/label-studio/pull/1102
Now you are able to create predictions for tasks.
