### ISSUE TITLE
Importing Data from Dataset URL results in "Validation error(undefined)"

### ISSUE THREAD

**Issue by laynr** [heartexlabs/label-studio#980]
**Describe the bug**
Can not import/take tasks from URL address when using the web form.

**To Reproduce**
In the web form go to Create Project -> Data Import -> Type in a  URL -> Add URL. 
Results in "Validation error(undefined)" 

**Cause of Bug**
`Add URL` results in POST request header with a content-type of `mulitpart/form-data` as shown on this [line](https://github.com/heartexlabs/label-studio/blame/b482c09a0a4b81ec41e0fe2cd73c84ea3c37bf66/label_studio/frontend/src/pages/CreateProject/Import/Import.js#L176) of code.

This results in a `Validation error(undefined)` triggered by this [line](https://github.com/heartexlabs/label-studio/blame/master/label_studio/data_import/uploader.py#L110) of code.

This is because this [line](https://github.com/heartexlabs/label-studio/blame/master/label_studio/data_import/uploader.py#L83) of code is expecting a content-type of `application/x-www-form-urlencoded` in the POST request header.

**Expected behavior**
Import/take tasks from URL address when using the web form.

**Environment:**
 - Docker deployment
 - Label Studio Version 1.0.2

**Additional context**
This can be fixed by ensuring the `content-type` match.  
This bug was not triggered in this [test cases ](https://github.com/heartexlabs/label-studio/blob/b482c09a0a4b81ec41e0fe2cd73c84ea3c37bf66/label_studio/tests/test_tasks_upload.py#L256) because the content type is hard-coded and not generated by using the web form.
When fixed please push a new "latest" Docker image and I can test.

**Comment by makseq** [comment]
@laynr Could you check this PR please? https://github.com/heartexlabs/label-studio/pull/981#pullrequestreview-669527925 - we've fixed this issue there.

**Comment by laynr** [comment]
> @laynr Could you check this PR please? [#981 (review)](https://github.com/heartexlabs/label-studio/pull/981#pullrequestreview-669527925) - we've fixed this issue there.

No this doesn't fix it.  I am still getting `Content-Type: "multipart/form-data; boundary=----WebKitFormBoundary7PL4GSvACAzoqsJs"` resulting in `Validation error(undefined)`

Logs
```
vscode ➜ /workspaces/label-studio (fix/import-by-url ✗) $ label-studio
=> Database and media directory: /home/vscode/.local/share/label-studio
=> Static URL is set to: /static/

Start browser at URL: http://localhost:8080
Performing system checks...

System check identified no issues (0 silenced).
May 27, 2021 - 16:30:01
Django version 3.1.4, using settings 'label_studio.core.settings.label_studio'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[27/May/2021 16:30:04] "GET / HTTP/1.1" 302 0
[27/May/2021 16:30:04] "GET /projects/ HTTP/1.1" 200 2261

<SNIP for brevity>

[27/May/2021 16:30:19] "PATCH /api/projects/6 HTTP/1.1" 200 1045
[2021-05-27 16:30:26,501] [core.utils.common::custom_exception_handler::79] [ERROR] 60a035c2-d2df-43a6-a9e6-abf9acccdae7 [ErrorDetail(string='load_tasks: No data found in DATA or in FILES', code='invalid')]
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/workspaces/label-studio/label_studio/data_import/api.py", line 158, in post
    return super(ImportAPI, self).post(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.9/site-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/workspaces/label-studio/label_studio/data_import/api.py", line 173, in create
    parsed_data, file_upload_ids, could_be_tasks_lists, found_formats, data_columns = load_tasks(request, project)
  File "/workspaces/label-studio/label_studio/data_import/uploader.py", line 119, in load_tasks
    raise ValidationError('load_tasks: No data found in DATA or in FILES')
rest_framework.exceptions.ValidationError: [ErrorDetail(string='load_tasks: No data found in DATA or in FILES', code='invalid')]
```

**Comment by coldtomatojuice** [comment]
I got this error when I inserted a wrong url

**Comment by makseq** [comment]
@coldtomatojuice what if you insert the correct url? Is it ok?

**Comment by MahimaBarot** [comment]
facing the same issue with right url too @coldtomatojuice

**Comment by coldtomatojuice** [comment]
@makseq In my case, yes, it is ok with a correct url (latest version docker image / k8s deployment)
@MahimaBarot do you deploy the latest version? I got the error with correct url on 1.0.1 version

**Comment by laynr** [comment]
@makseq @MahimaBarot  @coldtomatojuice @niklub 
I confirm that the latest docker image (https://hub.docker.com/layers/heartexlabs/label-studio/latest/images/sha256-c151d4b70dcd70ec864c9226eb42fd276a5e41eb0df690111e74387c911aca22) allows upload by URL. Thank you! Close issue/bug as desired.
