### ISSUE TITLE
Slow interactions with many RectangleLabels

### ISSUE THREAD

**Issue by timurlenk07** [heartexlabs/label-studio#983]
**Describe the bug**
When a lot of RectangleLabels are loaded in (> 100, like in OCR), moving around and zooming in the image becomes very slow.

**To Reproduce**
1. Create project with OCR template
2. Upload image with several hundred annotations
3. Open label editor and try to zoom in and move around the image

**Expected behavior**
It would be nice if performance (and therefore user experience) would be improved in this case.

**Environment (please complete the following information):**
 - OS: Ubuntu 16
 - Label Studio Version 1.0.2

**Comment by makseq** [comment]
Region performance was improoved in [release/1.1.0](https://github.com/heartexlabs/label-studio/tree/release/1.1.0). Feel free to reopen if you have this problem again.
