### ISSUE TITLE
Importing multiple JSON file results in only one import

### ISSUE THREAD

**Issue by timurlenk07** [heartexlabs/label-studio#992]
**Describe the bug**
When uploading multiple, pre-annotated data in LSCF, the importing process ends up showing only the tasks in the last uploaded file.

**To Reproduce**
1. Create a project that you have annotated data for
2. Click on Import
3. Upload many JSON files in LSCF
4. Click on Import and observe that only the contents of the last JSON was actually uploaded

**Expected behavior**
Obviously, I expected that **all** the JSON files get imported.

**Environment (please complete the following information):**
 - OS: Ubuntu 16
 - Label Studio Version 1.0.2

**Additional context**
My pre-annotated data set is ~200MB large, thus I split them into ~40MB chunks and uploaded them into the Import view one-by-one, because the server limits imported file size at 50MB. I don't think that this is part of the issue though.

**Comment by makseq** [comment]
@mauricio-repetto @timurlenk07 Does this bug exist in LS 1.1.0?

**Comment by mauricio-repetto** [comment]
@makseq I updated the tool version and seems to be working fine now, great work man, thanks!
