### ISSUE TITLE
Filter for range of IDs does not allow writing 

### ISSUE THREAD

**Issue by timurlenk07** [heartexlabs/label-studio#994]
**Describe the bug**
When trying to filter for IDs to see the tail of the task list, I cannot enter proper ranges into ID *between* filter, and when combining two filters, the second one has fields shown all around the first filter's fields.

**To Reproduce**
1. Create or import data set with more than 1k elements
2. Try to filter for IDs *between* two big numbers (like 300 and 600)
3. The control does not allow writing numbers (or at least numbers with more than one characters)
4. Try to combine two filters for ID by adding another filter
5. See that the second filter appears inline and above the first one, to its right

**Expected behavior**
I want to write numbers larger than 9 into the *between* type of filter and combine multiple filters with ease.

**Screenshots**
![kép](https://user-images.githubusercontent.com/25661746/120292066-3dbb5d80-c2c4-11eb-802e-445f574865a8.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 16
 - Label Studio Version 1.0.2 master
 - Browser: Mozilla Firefox

**Comment by makseq** [comment]
@timurlenk07 Could you check this PR please - https://github.com/heartexlabs/label-studio/pull/999 ?
