### ISSUE TITLE
Ranker tag do not work

### ISSUE THREAD

**Issue by zhoudoufu** [heartexlabs/label-studio#995]
**Describe the bug**
ranker not working with document example.

**To Reproduce**
1. install label-studio,launch server
2. Create new project with custom template by apply example in document https://labelstud.io/tags/ranker.html
3. Click into Labeling for first record
4. See error TypeError: Cannot read property 'type' of undefined

**Expected behavior**
expect to work without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/16586440/120309998-7a10ad00-c308-11eb-94fa-5cf63440db55.png)

**Environment (please complete the following information):**
 - tested on pip package on Mac and docker on linux
 - label-studio==1.0.2

**Additional context**
preview and launch with the playground in the document also don't work.

**Comment by smoreface** [comment]
@hlomzik  fyi

I don't see an error but I don't see success when testing this with the example JSON results and v1.2.0

**Comment by makseq** [comment]
@zhoudoufu @smoreface Yep, we skipped the support of ranker long time ago unfortunately due to rare usage. If there are lots of requests we will rework it for sure.
