### ISSUE TITLE
The --ml-backends command line option does not do anything

### ISSUE THREAD

**Issue by jpc** [heartexlabs/label-studio#996]
**Describe the bug**

The `--ml-backends` option does not do anything.

**To Reproduce**

I tried passing the flag to both `init` and `start` and the UI shows no ML backends.

**Additional context**

The code to handle this argument seems to have completely disappeared during the 1.0.0 release (commit 6ec1e79e0ff5b6b3fc033d00dad5ccb6b9f014b4, it's a large code dump, you can search/grep for `args.ml_backends` in `git show 6ec1e79e0ff5b6b3fc033d00dad5ccb6b9f014b4` in a local checkout).

**Comment by niklub** [comment]
@jpc  thanks for pointing this out. Yes, you're right, as far as Label Studio 1.0.0 this console option has been removed. Please consider connecting ML backend through UI or by using API call:
```bash
curl -X POST http://localhost:8080/api/ml --data '{"url": "http://localhost:9090", "project": <project_id>}'
```
Feel free to create a patch for using `--ml-backends` console argument - PRs are very welcome!

**Comment by jpc** [comment]
Hi, thanks for the explanation and the API tip. I don't really need for this to be a CLI option so I am just glad to see you updated the docs to avoid confusion in the future.

I think it would be also good to document this API since I could not find it in the API docs on the web page.

**Comment by makseq** [comment]
@smoreface Could you please 

1. add this

```
Consider connecting ML backend through UI or by using API call:
curl -X POST http://localhost:8080/api/ml --data '{"url": "http://localhost:9090", "project": <project_id>}'
```
somewhere here: 

https://labelstud.io/guide/ml.html#Quickstart

2. Maybe we need to hide this
![image](https://user-images.githubusercontent.com/501780/122054952-d12a7d80-cdf0-11eb-9fa0-95c64d5f6d5f.png)
because it's no working...

**Comment by smoreface** [comment]
@makseq Yup, change 2 is already in: https://github.com/heartexlabs/label-studio/commit/fd0d42f5e0c6e2e21331d5c7839af5e798827b1e

I'll update to add a link to the API documentation as well.
